lib/config/config.js

Is there a specific reason you hard coded 'us-east-1'?
I'm currently working out of 'us-west-2' and it obviously causes errors when trying to run lambda's locally.

updated aws config to use .env regions

---

lib/commands/deploy_lambda.js
lib/templates/nodejs/handler.js

On deployment the `.env` file had a filepath as its contents, not the actual environment variables.
`eval('dirname')` is required to get around browserify and find the correct place for `.env`

.env file needs contents, not its filepath

---

lib/commands/dash.js

Untag those not selected, tag those that are selected.
Return early if there are no endpoints to update or deploy.
Return early if there are no lambdas to update or deploy.

Dash fixes.

---

docs/README.md

there were two jaws.json in the list

removed duplicate lines

---

bin/jaws
lib/commands/run.js
lib/utils/context.js
tests/cli/run.js
tests/test_utils.js

I needed a way to run the lambda locally with the correct environment variables, testing in AWS Lambda is difficult offline.
```
[1] ~/w/b/b/l/h/get * ❯❯❯ jaws run local
JAWS: Error: {"id":"d073d50209e3","label":"Bobby","status":"fail"}
```
```
[1] ~/w/b/b/l/h/get * ❯❯❯ jaws run local
JAWS: {"id":"d073d50209e3","label":"Bobby","status":"ok"}
```
This does require a change in the #118 for `log_header` [here](https://github.com/jaws-framework/JAWS/pull/118/files#diff-945a66226d0012aff655853aecba7f83R53).

Run command

---

lib/commands/deploy_endpoint.js

This fixes issue https://github.com/jaws-framework/JAWS/issues/156. As @rpgreen stated (https://github.com/awslabs/aws-apigateway-swagger-importer/issues/41#issuecomment-143066855), test invokes are not tied to a stage.

Make Lambda permission stage-independent

---

lib/commands/deploy_endpoint.js

Especially when working with Lambda responses, you want to be able to configure custom selectionPatterns for responses. This was not supported. Also made some small improvements for optional config attributes.

Allow custom selectionPattern attributes

---

bin/jaws

in Commander it gets mapped to options.save = false, not noSave.
see https://github.com/tj/commander.js/blob/master/test/test.options.bool.no.js
and also https://github.com/tj/commander.js/blob/master/test/test.options.bool.js

--no-save is a special case

---

bin/jaws
lib/commands/tag.js
tests/cli/tag.js

A proposed solution to jaws-framework/JAWS#164.
Implements a new “all” type which allows a user to tag all Lambdas and
Endpoints in one command. It also makes this the default command when
running a bare `jaws tag --tag-all` or `jaws tag --untag-all` with no
type option.

Tag all can now tag all endpoints and lambdas in one command

---

bin/jaws
lib/commands/tag.js
tests/cli/tag.js

As discussed in #164, explicitly defining the type is probably better. "all" is now switched in favor of "both".

Explicit defining of tag type required, "all" is now "both"

---

lib/utils/cli.js

A proposal to address #158.
Checks to see if we are in an interactive environment. If we are not, the spinner object is replaced with a simple object that displays basic messages.
If a select prompt is shown in a non-interactive environment, we throw an error and alert the user.

Add interactive aware spinner and select

---

bin/jaws
lib/templates/nodejs/handler.js

When invoking just `jaws` command, it was spitting out:
Usage: undefined [options] [command]

Fix for "undefined" in help output

---

examples/awsm.json
lib/commands/deploy_endpoint.js
lib/templates/action.awsm.json
tests/test-prj/aws_modules/sessions/create/awsm.json
tests/test-prj/aws_modules/sessions/show/awsm.json

If you want to return custom Content-Type (like `text/html`) instead of `application/json` from lambda, you need to set method response models in API Gateway (among other things). This PR adds support for `responseModels: { "text/html": "Empty" }` which does the trick.

Response models

---

lib/commands/deploy_lambda.js

Necessary for supporting non-babel transformers like coffeeify.

Added support for 'transform' option in browserify

---

lib/commands/deploy_endpoint.js

`jaws deploy endpoint` was crashing when stage was selected from prompt.

Fixed stage setting when stage prompt is used for `jaws deploy endpoint`

---

lib/commands/postinstall.js

This fixes a bug where things would fail with an error like:
{ [Error: ENOENT: no such file or directory, lstat '.../aws_modules/awsm-cloudfront']
errno: -2,
code: 'ENOENT',
syscall: 'lstat',
path: '.../aws_modules/awsm-cloudfront' }
When the npm package name is different from the awsm package name.

Fix postinstall to use `module.name` consistently.

---

README.md

Changed to recommend n vs nvm. Doesnt mess with your profiles or $PATH.  Its a much more popular module too.
http://www.mattpalmerlee.com/2013/03/23/installing-and-switching-between-multiple-versions-of-node-js-n-vs-nvm/

Recommend n over nvm

---

package.json

Users can add aliases if they like, but `sl` conflicts, and is easy to mistype when you mean `ls`.
Closes #345

Remove `sl` command because it tramples other commands

---

lib/utils/index.js

So, this one is more tricky. I was developing a plugin, as my own module, so for development I did `npm link my-plugin` in `plugins`. It correctly created `node_modules/my-plugin` symlink, but SL didnt managed to recognize it as existing plugin. Changing `lstat` to `stat` did the right thing.
I've checked other usages of `dirExistsSync`, and it seem that all of them will have this problem. If user will e.g. create module as a symlink, at best SL will ignore the symlink and either fail or try to create folder with that name (which will fail, due to existing symlink).
Therefore, I think it is better to always use `stat` instead of `lstat`. Or, if that is not desired for any other reason, consciously make the call, provide 2 versions and then use them appropriately across the codebase.

Added support for detecting symlinks as existing folders

---

.travis.yml

This probably shouldn't be merged as-is, jscs currently raises 620 code style errors. For those of you keeping score at home, that means 7 percent of lines in the codebase have errors.

Add travisci for jscs and jshint

---

lib/actions/ProjectCreate.js

Currently `sls project create` fails because it cant create `plugins/custom` folder.

Creating parent directories during project create

---

lib/actions/FunctionRun.js

Refactored event.json loading code to be a call to a central function as opposed to duplicating the same code. See _loadTestEvent on line 159 and line 72
Referenced absolute path to event.json file in order to correctly load the file. See 162.

Centralized and fixed event.json loading

---

lib/actions/FunctionCreate.js
lib/actions/FunctionRun.js
lib/actions/FunctionRunLambdaNodeJs.js

- removes the module prefix from the function name
- supports function specific and generic event.json files
- tidies _loadTestEvent in FunctionRun.js
- removes bug in FunctionRunLambdaNodejs.js that meant event object wasn't passed through
relates to #384

Function create / run / event fixes

---

lib/Serverless.js
lib/actions/CodeDeployLambdaNodeJs.js
lib/actions/CodePackageLambdaNodeJs.js
lib/actions/CreateEventSourceLambdaNodejs.js
lib/actions/DashDeploy.js
lib/actions/EndpointBuildApiGateway.js
lib/actions/EndpointDeploy.js
lib/actions/EndpointDeployApiGateway.js
lib/actions/EnvGet.js
lib/actions/EnvList.js
lib/actions/EnvSet.js
lib/actions/EnvUnset.js
lib/actions/FunctionCreate.js
lib/actions/FunctionDeploy.js
lib/actions/FunctionRun.js
lib/actions/FunctionRunLambdaNodeJs.js
lib/actions/ModuleCreate.js
lib/actions/ModuleInstall.js
lib/actions/ProjectCreate.js
lib/actions/RegionCreate.js
lib/actions/ResourcesDeploy.js
lib/actions/StageCreate.js

Currently internal plugins/actions are having `module.exports = ProjectCreate;` kind of code, whereas all external plugins have to use `module.exports = function(SPlugin, serverlessPath) {}` approach. This change makes them equal.
Important side effect of this, is that plugins, whose path is relative (like `../../../node_modules/my_plugin`) can be loaded from outside of the project.

Refactored internal plugins to be loaded just like the external ones.

---

lib/actions/EndpointBuildApiGateway.js
lib/actions/EndpointDeployApiGateway.js

During deploying large amount of endpoints APIG occasionally sends `Too many requests` error, and Serverless fails. This PR fixes this by sleeping for 5 seconds and re-trying.

Slower endpoint deploy

---

lib/actions/CodeDeployLambdaNodeJs.js

In AWS Lambda, $LATEST is not referring to the version most recently created. It is kind of 'uncommitted head'. `updateFunctionCode` copies $LATEST to the new version and applies the config. The config of such created version cannot be changed anymore.
The old code was creating version, then updating config. So, if you had 2 stages, and stage A did the deploy the version was created with whatever was left over in $LATEST from previous deploy. Then, $LATEST was reconfigured to use stage A settings (e.g. IamRole). If stage B did the deploy in such situation, the new version was created, with stage A config, but stage B alias. And then $LATEST was reconfigured to use stage B settings. So, if stage A would deploy in this moment, bug would happen again.
This code reverses the operation, we …

Fixed function configuration during deploy.

---

lib/actions/EndpointDeploy.js
lib/actions/EndpointDeployApiGateway.js

Example usage:
```
sls endpoint deploy -a -s $SERVERLESS_STAGE -d "${SERVERLESS_STAGE} - CI build #${CIRCLE_BUILD_NUM} / ${CIRCLE_SHA1:0:7} by ${CIRCLE_USERNAME}: `git log --pretty=format:"%s" HEAD^..HEAD`"
```

Added support for custom stage deployment descriptions

---

package.json

This could, in some cases, lead to a dependency loading error.

Fix casing issue

---

lib/Serverless.js

Serverless version is now available by:
`serverless v`
`serverless version`
`serverless -v`
`serverless --version`

add shortcut -v, --version to get the version

---

lib/utils/aws/CloudFormation.js

If any errors occured while updating/creating projects, there are no messages to specify what the problem is.
I can see some of cloudformation message like below.
Then, `StackStatusReason` is really helpful for me.
{ ResponseMetadata: { RequestId: 'cd74af39-bac8-11e5-8e54-db828d2cbe44' },
Stacks:
[ { StackId: 'arn:aws:cloudformation:ap-northeast-1:120012949752:stack/CharaAPI-development-r/c3779dd0-bac8-11e5-8a91-50ba1576b00a',
StackName: 'CharaAPI-development-r',
Description: 'CharaAPI resources',
Parameters: [Object],
CreationTime: Thu Jan 14 2016 23:11:54 GMT+0900 (JST),
StackStatus: 'ROLLBACK_IN_PROGRESS',
StackStatusReason: 'The following resource(s) failed to create: [IamGroupLambda, IamRoleLambda]. . Rollback requested by user.',
DisableRollback: false,
NotificationARNs: [], …

Show cloudformation error message

---

lib/ServerlessComponent.js
lib/ServerlessFunction.js
lib/ServerlessModule.js
lib/actions/CodeDeployLambdaNodeJs.js
lib/actions/CodePackageLambdaNodeJs.js
lib/actions/FunctionCreate.js
lib/actions/FunctionDeploy.js

This is part of preparation for Python support, and gets rid off runtime properties at the function and module levels. 
Don't merge until Austen has components automatically saving themselves to the state object at create-time, or this will break the component-create action.

Get rid of runtime property hardcoding

---

lib/actions/ModuleInstall.js

Looks like ModuleInstall still tries to use package.json if it's available.

Dependencies are no longer module-level

---

lib/ServerlessEndpoint.js
lib/actions/EndpointBuildApiGateway.js

Enables support for endpoint type ("AWS" by default).

Allow other endpoint types

---

lib/ServerlessComponent.js

Looks like I missed a semicolon when adding a new template file.

Fix syntaxerror introduced with blank __init__.py file

---

package.json

The `serverless-run-python-handler` binary must be in the user's path in
order to run Python functions locally, and it wasn't in `package.json`
so users using `npm install` or `npm link` to get serverless wouldn't
have it in their $PATH.

Add binary for running Python functions to $PATH

---

bin/serverless-run-python-handler

/bin/env isn't available on all linux distros, so use `/usr/bin/env` which is a more widely used standard.

Use universal /usr/bin/env path instead of /bin/env

---

lib/actions/DashDeploy.js
lib/utils/cli.js

This adds the following hotkeys to Dash:
- pageup, pagedown: Move choice up/down by 4 steps.
- home, end: Move to the first and last choice.
- space: Toggle the current choice and move to the next.
- ctrl + enter: Select deploy.

Add additional hotkeys and instruction text to dash.

---

lib/actions/FunctionRun.js

Add functionality to allow `serverless function run` to use the current function path if one was not specified on the CLI.

Allow `serverless function run` from within a function path.

---

lib/actions/EndpointBuildApiGateway.js

This is at attempt at a workaround for the AWS quirk of requiring an invalid JSON string to use the $input.json() within a requestTemplate. After an object has been converted to a string within _prepareRequestTemplates(), this adds a regex search which removes the quotes around $input.json(). This will allow us to use the quoted string values like "$input.json('$')" or "$input.json('$.pets')"within our JSON, and eliminate the need for the big ugly stringified version.

Implement workaround for the AWS quirk on $input.json().

---

lib/ServerlessComponent.js
lib/ServerlessFunction.js

Deploying resources to AWS using `sls resources deploy` always leads to overwriting `s-templates.json` with `[object Object]` string. It's pretty annoying, because you have to revert these changes every time. The reason is that it tries to write object into file without converting it to JSON. Here's the fix for that.
Hope you can merge this PR soon. Thanks!

Fix overwriting s-templates.json

---

lib/ProviderAws.js
lib/actions/EndpointBuildApiGateway.js

Current implementation of 429 handling was totally flawed (many mistakes on promise usage, like resolving+rejection of the same promise, creating promise and throwing it away, 429 retry within 429 retry, etc.). This PR fixes this.

Bugfixes for 'Too many requests' usage

---

lib/actions/EndpointBuildApiGateway.js

This is a simple patch just to allow specifying authorizerId in s-function.json endpoints:
"authorizationType": "CUSTOM"
"authorizerId": "<id from api gateway console>"
Without this, there's no way to specify the authorizerId and deploying the endpoint will remove the custom authorization that was configured in API Gateway console.
I propose this as a temporary quick fix until more comprehensive custom authorizer support is available (https://github.com/serverless/serverless/issues/626).

Support authorizerId parameter in s-function.json endpoints for CUSTOM authorizers

---

lib/RuntimeBase.js
lib/RuntimeNode.js
lib/RuntimePython27.js

Hander is specified as "rootfolder/handler.handler", but checked against a path on windows which is along the lines of "C:\...\rootfolder\handler.handler" and so it doesn't work due to forward slashes instead of backslashes.
Windows paths work equally well with forward slashes, so I have replaced the backslashes with forwards ones in the check

Fix issue finding handler when running on windows

---

lib/utils/index.js

Update findProjectPath() to use readFileSync() so that a json error message is received if s-project.json is invalid.

v0.5 - Fix error message on invalid s-project.json.

---

lib/actions/CodeDeployLambda.js

Fixes:
The functions are being deployed without replacing the template placeholders with their values for example:
```  "vpc": {
"securityGroupIds": [
"${securityGroup}"
],
"subnetIds": [
"${subnetA}",
"${subnetB}"
]
}```
does not replace ${securityGroup} with my dev/prod values

When deploying functions, replace the variable placeholders with their values

---

lib/Runtime.js
lib/actions/CodeDeployLambda.js

* More narrowly define default function excludePatterns
* Correct reference to undefined properties in `Runtime._validateAndPrepare()`

Fixes #813 and #814 - the redux

---

README.md

The David Guetta article originally appeared on serverlesscode.com, change the link in the README to the original version.

Move David Guetta campaign link to original version

---

lib/ProviderAws.js
lib/actions/EndpointBuildApiGateway.js

Allow AWS account ID to be defined in the variables files by using it as the preferred source of the account ID.
Move the check for a valid account ID until after contingent loading of the ID has been executed and clarify the error message.
This pull request resolves https://github.com/serverless/serverless/issues/790

Allow variable declaration of AWS account ID

---

lib/Serverless.js

The error messages for "invalid context" and "invalid command" were switched. Now the proper message is shown in each case.

issue #836 - Switched error messages for context and command.

---

lib/actions/FunctionCreate.js

On Windows systems the path gets parsed now, regardless if you use '/' or '\' as separator.

Issue #839 - Use path.parse method to extract function name

---

lib/Project.js

Now project name check on `project init` and `project create` work again as expected.

Fixes #838 - Removed default name from project instance. 

---

lib/actions/FunctionDeploy.js
lib/utils/index.js

* Clear _this.deployed and _this.failed within functionDeploy after completed.
* Fix a crash in sDebug when the path does not match the regex search.

Fix plugin compatibility

---

lib/actions/CodeDeployLambda.js

Simple port of VPC support from 0.5 to 0.4.2 to support use of RDS (postgres) with lambda.

Backport 0.5 VPC support

---

lib/actions/FunctionDeploy.js

Here's a small fix to avoid Serverless throwing ugly errors when deploying a function fails and func is undefined.

Handle error case where the failed function is undefined

---

lib/actions/FunctionLogs.js
lib/actions/ProjectInit.js

Fixes ProjectInit logging:
Fixes #857, when run `sls function logs` within a function folder and the function name is different from its folder name.

Fixes ProjectInit logging; fixes #857

---

lib/RuntimeNode.js

to make the env vars available in the handler's global context (as on AWS).

Issue #874 Load function handler after environment has been set

---

lib/actions/FunctionRemove.js

v0.5 sls function remove is not using the correct endpoint name

---

lib/actions/EventLambdaSchedule.js

Fixes `Unexpected key 'input' found in params.Targets[0]`.

Fix CloudWatch events target

---

lib/actions/ProjectInstall.js

This PR is intended to fix the error `EEXIST: file already exists` when running `serverless project install ...`.
This changes a move operation into a copy in _installNpmProject(), because the destination directory was already created. This should have no adverse effects since the copied files are later removed.
This is the error I currently see on a new project install:
```
$ serverless project install serverless-authentication-boilerplate
_______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.2
`-------' …
```

Fixes 'file already exists' on install

---

lib/Runtime.js

Added `dereference` option to fs-extra copy to dereference symlinks on copy.

Issue #896 Add dereference option

---

lib/ProviderAws.js

This allows users to work around a network with a slow upload speed by setting the `AWS_CLIENT_TIMEOUT` environment variable to something greater than 120000 (2 minutes).  If found, it sets the `AWS.client.httpOptions.timeout` value.
It follows the existing convention set by looking for `HTTP_PROXY/HTTPS_PROXY` in the environment.

Fix #490: Connection timed out after 120000ms in function deployment

---

lib/actions/EventLambdaSNS.js
lib/actions/EventRemove.js

This should fix: https://github.com/serverless/serverless/issues/915
I implemented this with a new property called topicArn as in the original request rather than autodetecting whether it is a name or arn in a property called topic because I thought that the original way would be backwards compatible, whereas if I changed the name of the property it would break backwards compatibility
Happy to update this though if the autodetect way is preferred

Allow topicArn config for sns event instead of topicName

---

lib/ProviderAws.js

Currently, getProfile() changes the profile name given to lowercase. If the profile name was stored with uppercase characters elsewhere (i.e. in the ~/.aws/credentials file), then this prevents a match.
This PR removes the code that changes the profile name provided to lowercase. This effectively makes the profile name case sensitive and the case must match between Serverless config files and the AWS config files.
This change could break existing installations if the profile name is stored as lowercase in the AWS credentials file but stored with mixed case in Serverless config files. An alternative fix would be to change all profile names to lowercase when loaded from the AWS credentials file.

Fixing handling for profiles with uppercase characters

---

lib/Serializer.js
package.json

Issue #929 : `s-template` can now be specified as YAML or JSON to support better authoring of VTL enriched templates

#929 Added YAML to serializer

---

lib/actions/EndpointBuildApiGateway.js

Fixed issues #517 and #950 .
HTTP proxy endpoints can now be specified like this in `s-function.json`:
```
"endpoints": [
{
...
"type": "HTTP",
"uri": "https://www.google.com",
"targetMethod": "GET",
...
}
]
```
The creation of HTTP will bail out if `uri` or `targetMethod` are missing.
All other endpoint properties continue to work as expected.

950 added apig proxy support

---

lib/ProviderAws.js
lib/utils/context.js
lib/utils/guid.js

The AWS CLI allows you to have a profile that assumes a role when invoking commands, via a separate profile that you have configured:
http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html
e.g. I might have an ~/aws/credentials file that looks like:
```
[bob]
aws_access_key_id=XXXXXXX
aws_secret_access_key=XXXXX
```
and an ~/.aws/config file that looks like:
```
...
[profile bob]
region = us-east-1
[profile client_project_a]
role_arn = arn:aws:iam::012345678901:role/admin
source_profile=bob
[profile client_project_b]
role_arn = arn:aws:iam::012345678901:role/admin
source_profile=bob
```
This pull request adds support to serverless to make the necessary STS calls when the specified profile is a "role profile".
It also modified the credentials lookup so that it pays attention to the …

Add support for assuming a role like AWS CLI

---

lib/Serverless.js

Plugins are now discovered with the help of the projects package.json file. This makes it
possible to simply run "npm install --save" to use plugins. No need to add the
plugin name to the plugins array in the s-project.json file (it will be ignored from now on).
Refs #615

Closes #580 - Add package.json based plugin discovery

---

lib/actions/ResourcesDeploy.js

Removed conditional check on adding the variable to the file. We should be updating the variable value even if the variable exists. It's value will be old and from a previous deployment.

Fix 886 resource output values not updating

---

lib/actions/CodeDeployLambda.js

When using Serverless in a Virtual Box environment (e.g. a Windows system hosting an Ubuntu VM), the file permissions might be something like 0770 - readable only by the user and the group, but not by everyone. Due to the nature of sharing file system across the VM, these permissions cannot be changed. However, this causes issues when zipping and uploading the code to Lambda in the latest Serverless 0.5.3 release. AWS will fail to run the code and throw the following error message instead:
```
EACCES, permission denied '/var/task/<my-path>/_serverless_handler.js'
```
This small patch fixes this by enforcing all files to be at least world-readable. Thus it ensures that the code can run as expected.

Ensure files uploaded to lambda are world-readable

---

lib/actions/FunctionRollback.js

If you pass in a specific version using the command line, javascript parses it as a `number` which is unsuccessfully compared to the string `Version` returned from the AWS SDK.
The issue can be fixed multiple ways, this has the least side effects but consider alternatively passing in the version like "v3" instead because that's how the interactive version displays it.

Fix version comparison operation

---

lib/Plugin.js

Replace hardcoded amount of regions with a call to ProviderAws.
The hardcoded amount prevents creating > 4 regions (we have 5 now).

Fix Plugin.cliPromptSelectRegion

---

lib/actions/EndpointDeploy.js

The description of the API Gateway deployment was being captured but not used.
Fixes #1019

Added missing description field to the ApiGateway deploy method [Fixes #1019]

---

lib/actions/FunctionCreate.js

Fixes #1015 
Added `--template/-t` parameter to `function create` that sets the template type used for the created function. Accepted values are `function`, `endpoint` and `event` and behave exactly the same as when entered through the interactive prompt.

Issue #1015

---

.gitignore
.travis.yml
Dockerfile
docker-compose.yml
scripts/eslint.sh

We want to start using CI for Serverless so this introduces ESLint built on top of changes by @minibikini.
To introduce Eslint we don't want to kill our build immediately, but be able to improve it over time. I've implemented a ratchet so you can't add more issues and we can lower the ratchet over time until we've fixed everything.
I also added config for docker-compose to be able to run builds inside of docker-compose for various node versions if we want to.

Add travisci config

---

lib/ProviderAws.js

Feature: REST API identifier are cached, instead of being resolved in each endpoint deploy.
When deploying many endpoints in once, this speeds up the process and reduces rate of TooManyRequests failures.

Cached REST APIs

---

lib/ProviderAws.js

#993 
When deploying all endpoints, AWS SDK sometimes fails with 429 TooManyRequests, then the whole process fails.
With this fix, AWS requests are retried in such cases.

Fix for TooManyRequests

---

lib/actions/CodeDeployLambda.js
lib/actions/FunctionDeploy.js

fix typo to variable name 'functioName'

fix typo to variable name 'functioName'

---

lib/actions/VariablesList.js
lib/actions/VariablesSet.js
lib/actions/VariablesUnset.js

Fixes #998 
The `sls variables xxx` type commands now support the Serverless variable hierarchy (common, stage and region). You can now easily set a variable within the specified scope.

998 variables support stage vars

---

lib/actions/FunctionCreate.js
lib/actions/PluginCreate.js
lib/actions/ProjectRemove.js
lib/actions/RegionCreate.js
lib/actions/RegionRemove.js
lib/actions/ResourcesDeploy.js
lib/actions/ResourcesRemove.js
lib/actions/StageCreate.js
lib/actions/StageRemove.js
lib/actions/VariablesList.js
lib/actions/VariablesSet.js
lib/actions/VariablesUnset.js
lib/utils/cli.js

Addressing #657 -- discussion and screenshots are in the referenced issue.
There are a few pieces of future work I intend to tackle next:
1. Referencing loaded plugins in the top-level version of this screen
2. Find some way to have the color scheme work across light and dark background terminals.
I didn't find much in the way of test infrastructure for the CLI, and to be honest, I'm not even sure what tests would be meaningful for something like this. Open to suggestions here, please do let me know if you have ideas.
I did notice that some action descriptions had embedded new-lines. Not sure how best to handle that -- thoughts? I can obviously strip out the embedded new-lines, but not sure if that's the right move here.
Thanks!
Ankur

Issue #657: Condense CLI output to fit in a single screen

---

lib/RuntimeNode.js
lib/RuntimeNode43.js

This simple change allows one to confiugure the handler extension much like the optimizer. Used w/ an include of `ts-node/require` functions can be run locally for debugging.

Allow handler ext configuration for typescript/coffeescript local function run

---

lib/Actions.json
lib/actions/EventDeploy.js
lib/actions/EventIotRule.js
lib/actions/FunctionCreate.js

This PR adds support for AWS IoT. Serverless users can specify an IoT rule as an event source.
This also allows users to support websockets. Once a Lambda function is connected to an IoT rule, it can be invoked by opening a websocket. For more information on how to setup websockets to your IoT endpoint, [click here](http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html). 
Below is an example IoT event in **s-function.json**. The rule name and SQL are required. The SQL version, ruleDisabled flag and description are optional.
```
{
"name": "iotInvokeLambda",
"type": "iot",
"config": {
"rule": {
"name": "invokeLambda",  
"sql": "SELECT * from 'mytopic'",
"iotSQLVersion": "2016-03-23-beta",
"description": "Serverless invoke Lambda function rule.",
"ruleDisabled": false
}
}
}
```

Add support for an IoT event source

---

lib/actions/EventRemove.js

Because it is falsy, event cannot have the attribute "name".  As such, a misleading `Cannot read property 'name' of undefined` error is thrown rather than the more instructive error that the event couldn't be found for the region.  This leaves the actual identification of which event couldn't be found up to a good guess, unfortunately.
Fixes:
```
TypeError: Cannot read property 'name' of undefined
at EventRemover._eventRemove (/src/serverless/lib/actions/EventRemove.js:191:69)
at BbPromise.map.concurrency (/src/serverless/lib/actions/EventRemove.js:187:58)
From previous event:
at EventRemover._removeByRegion (/src/serverless/lib/actions/EventRemove.js:187:24)
From previous event:
at EventRemover._processRemoval (/src/serverless/lib/actions/EventRemove.js:182:10)
From previous event:
at …
```

Falsy event has no name attribute bugfix

---

lib/RuntimeNode.js
lib/RuntimeNode43.js

For example:
```
Serverless: Success! - This Response Was Returned:  
Serverless: "Completed!"  
Serverless: Duration: 273.15 ms 
```

Measure and display local function run Duration

---

README.md

Webscale is a consulting company specialized in AWS and cloud native applications. Serverless Framework fits very well in our toolset.

Added Webscale to the list of consulting companies

---

lib/classes/Service.js
lib/classes/Utils.js
lib/classes/YamlParser.js
package.json
tests/all.js
tests/tests/classes/Utils.js
tests/tests/classes/YamlParser.js

- Can parse yaml files and returns a JS object literal representing the resolved yaml file
- Can resolve any json-ref that is referring to a json file
- Can resolve any json-ref that is refering to a yaml file
- Can **recusively** resolve json-ref. Ie. `serverless.yaml` references `functions.yaml`, which references `events.yaml`
- Includes passing unit tests to assert the above statements
This parser will be used by the `Service.load()` method to load all Service data from `serverless.yaml` and `serverless.meta.yaml`.

added yaml parser

---

lib/actions/ProjectInstall.js

1. Run `serverless project install`
2. Get error: `ServerlessError: Please enter the name of the project you wish to install, like: serverless install project <projectname>`
3. Run `serverless install project <projectname>`, as directed
4. Get error: `ServerlessError: Command not found.  Enter "serverless help" to see all available commands.`
5. The proper command is `serverless project install <projectname>`

Fix error msg for server project install

---

bin/serverless
docs/plugins.md
lib/Serverless.js
lib/classes/CLI.js
lib/classes/PluginManager.js
lib/plugins/HelloWorld/HelloWorld.js
lib/plugins/Tests/Tests.js
tests/classes/CLI.js
tests/classes/PluginManager.js

Add the possibility to access arguments inside plugins (e.g. "--function function1" or "-f function").
Additionally the "lifeCycleEvent" property is renamed to "lifecycleEvent".

Add argument support for CLI and plugins

---

docs/concepts/plugins.md
lib/Serverless.js
lib/classes/CLI.js
lib/classes/PluginManager.js
lib/plugins/awsCompileFunctions/awsCompileFunctions.js
lib/plugins/awsCompileFunctions/tests/awsCompileFunctions.js
lib/plugins/awsCompileS3Events/awsCompileS3Events.js
lib/plugins/awsCompileS3Events/tests/awsCompileS3Events.js
lib/plugins/awsDeploy/awsDeploy.js
lib/plugins/awsDeploy/lib/validateInput.js
lib/plugins/awsDeploy/tests/awsDeploy.js
lib/plugins/awsDeploy/tests/validateInput.js
lib/plugins/awsInvoke/awsInvoke.js
lib/plugins/awsInvoke/tests/awsInvoke.js
lib/plugins/awsRemoveResources/awsRemoveResources.js
lib/plugins/awsRemoveResources/lib/validateInput.js
lib/plugins/awsRemoveResources/tests/awsRemoveResources.js
lib/plugins/awsRemoveResources/tests/validateInput.js
lib/plugins/create/create.js
lib/plugins/create/tests/create.js
lib/plugins/deploy/deploy.js
lib/plugins/helloWorld/helloWorld.js
lib/plugins/helloWorld/tests/helloWorld.js
lib/plugins/invoke/invoke.js
lib/plugins/remove/remove.js
tests/classes/CLI.js
tests/classes/PluginManager.js

The PluginManager now attaches the options to the constructor rather than the hooks of the plugins.
Furthermore the PluginManager will check if the passed options are required.

Refactor PluginManager functionality / Add option validation in plugin manager

---

lib/plugins/awsCompileS3Events/awsCompileS3Events.js
lib/plugins/awsCompileS3Events/tests/awsCompileS3Events.js
lib/templates/serverless.yaml

Comment out the S3 events as they may clash because of naming problems
(name should be globally unique) with the generated S3 buckets when running
integration tests in parallel.

Comment out S3 events in serverless.yaml

---

lib/plugins/awsCompileS3Events/awsCompileS3Events.js
lib/plugins/awsCompileS3Events/tests/awsCompileS3Events.js

This way users are not confused if they won't find their bucket because of the
namespacing that was previously applied.

Remove namespacing of S3 event bucket

---

README.md

The new project is [here](https://github.com/alexcasalboni/serverless-starter-python) ([npm](https://www.npmjs.com/package/serverless-starter-python)).
It's basically a clone of the [serverless-starter project](https://github.com/serverless/serverless-starter), but with Python functions.

Added link to boilerplate project for Python functions

---

lib/templates/serverless.env.yaml
lib/templates/serverless.yaml

YAML supports different indentations however dicts (which we use for events)
need a 4 level deep indentation to work correctly. The YAML files are updated so
that the user knows that he should always use a 4 level deep indentation.

Update YAML indentations

---

lib/classes/Utils.js

This way all our YAML files follow the 4 spaces best practice.

Fix YAML indentation when dumping

---

lib/plugins/aws/deploy/compile/events/s3/tests/index.js
lib/plugins/aws/deploy/compile/events/schedule/tests/index.js

So that they are in the same structure as the API Gateway event tests. Furthermore the tests are DRYed out so that we don't have code duplication / code smell.

Refactor schedule and S3 events test

---

docs/developing-plugins/building-plugins.md
lib/Serverless.js
lib/classes/CLI.js
lib/classes/PluginManager.js
lib/plugins/create/README.md
lib/plugins/create/create.js
lib/plugins/deploy/README.md
lib/plugins/deploy/deploy.js
lib/plugins/invoke/README.md
lib/plugins/invoke/invoke.js
lib/plugins/remove/README.md
lib/plugins/remove/remove.js
tests/classes/PluginManager.js

Add shortcut support.
Here's how it works:
In your plugins `option` object define the shortcut you want to associate your option with. That's it.
```
options: {
region: {
usage: 'Specify the region you want to deploy to (e.g. "--region us-east-1" or "-r us-east-1")',
required: true,
shortcut: 'r'
}
}
```
Serverless will covert `shortcuts` into `options` under the hood which means that this command: `serverless deploy -r eu-central-1` is the same as this: `serverless deploy --region eu-central-1`. The options property will include: `{ region: eu-central-1 }`.

Add shortcut support for options

---

docs/developing-plugins/building-plugins.md
docs/developing-plugins/building-provider-integrations.md
lib/Serverless.js
lib/classes/PluginManager.js
lib/plugins/aws/deploy/compile/events/apiGateway/index.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/index.js
lib/plugins/aws/deploy/compile/events/s3/index.js
lib/plugins/aws/deploy/compile/events/s3/tests/index.js
lib/plugins/aws/deploy/compile/events/schedule/index.js
lib/plugins/aws/deploy/compile/events/schedule/tests/index.js
lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/tests/index.js
lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/tests/index.js
lib/plugins/aws/invoke/index.js
lib/plugins/aws/invoke/tests/index.js
lib/plugins/aws/remove/index.js
lib/plugins/aws/remove/tests/index.js
tests/classes/PluginManager.js

Plugins can now have a `provider` definition inside the constructor.
If defined Serverless fill only consider the plugin if the `provider` definition of the service matches the one of the plugins.
All other plugins who have no provider definition will always be considered.

Add provider awareness for plugins

---

.travis.yml

Ready
Disable Integration tests on forked builds so we don't have to expose secret environment variables. otherwise the builds will always fail for them

Disable integration tests on fork builds

---

lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/tests/index.js
lib/plugins/aws/deploy/lib/initializeResources.js
lib/plugins/aws/deploy/lib/uploadDeploymentPackage.js
lib/plugins/aws/deploy/tests/uploadDeploymentPackage.js
lib/plugins/aws/index.js
lib/plugins/aws/remove/index.js
lib/plugins/aws/remove/lib/bucket.js
lib/plugins/aws/remove/tests/bucket.js
lib/plugins/aws/tests/index.js
lib/templates/core-cf.json

Ensures that the name of the `coreBucket` is always unique (AWS will auto pick the name in this implementation). This makes sure that we don't run into issues where people choose the same service name and can't proceed because the S3 bucket name where the code is stored is already taken.
See https://github.com/serverless/serverless/issues/1458 for more information.

Make coreBucket name unique

---

lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/tests/index.js
lib/plugins/aws/deploy/lib/uploadDeploymentPackage.js
lib/plugins/aws/deploy/tests/updateStack.js
lib/plugins/aws/deploy/tests/uploadDeploymentPackage.js
lib/plugins/aws/index.js
lib/plugins/aws/remove/lib/bucket.js
lib/plugins/aws/remove/tests/bucket.js
lib/plugins/aws/tests/index.js
lib/templates/core-cf.json

The bucket which is used for deployment should be more meaningful (as discussed in https://github.com/serverless/serverless/issues/1516).

Rename coreBucket name to be more meaningful

---

docs/understanding-serverless/serverless-yaml.md
docs/understanding-serverless/services-and-functions.md
lib/classes/Service.js
lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/tests/index.js
lib/plugins/create/templates/aws-nodejs/serverless.yaml
tests/classes/Service.js

This implements the functionality that the service defines which runtime is used (see https://github.com/serverless/serverless/issues/1517 for more details).

Add service bound runtime functionality

---

lib/plugins/create/README.md
lib/plugins/create/create.js
lib/plugins/create/templates/aws-python/handler.py
lib/plugins/create/templates/aws-python/serverless.env.yaml
lib/plugins/create/templates/aws-python/serverless.yaml
lib/plugins/create/tests/create.js

This PR adds Python support for AWS (it uses the recently introduced templating mechanism).
See #1552 and #1247

Add Python support for AWS

---

lib/plugins/package/lib/zipService.js
lib/plugins/package/tests/zipService.js

Ready
In a regex, `.` means any character, so the default exclude list will
actually exclude more than intended (any path containing `.serverless`
for example).
Instead, use `String#indexOf()`
See #1549

Don't use regex to test file path in package plugin

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/validate.js

Ready
HTTP Post functions shouldn't be limited to downcase. Tested with upper case and lower case, both work, but I'm still lower casing it just to make it simpler for us.
fixes #1548

Fix Validation for APIG method for upper and lower case

---

lib/classes/Error.js

putting error handling code inside a try/catch block, in rare cases where something happens during error logging, we'd just throw a native error.

Handling errors in error handling

---

lib/Serverless.js
lib/classes/Service.js
tests/classes/Service.js

Allows for `provider` property to be an object to hold provider specific config as discussed in [Issue 1567](https://github.com/serverless/serverless/issues/1567)

Provider property can be an object

---

docs/developing-plugins/building-plugins.md
docs/guide/custom-provider-resources.md
docs/guide/event-sources.md
docs/guide/overview-of-event-sources.md
docs/understanding-serverless/serverless-env-yaml.md
docs/understanding-serverless/serverless-yaml.md
docs/understanding-serverless/services-and-functions.md
docs/using-plugins/adding-custom-plugins.md
lib/classes/Utils.js
lib/plugins/create/templates/aws-nodejs/serverless.env.yaml
lib/plugins/create/templates/aws-nodejs/serverless.yaml
lib/plugins/create/templates/aws-python/serverless.env.yaml
lib/plugins/create/templates/aws-python/serverless.yaml

4 level indentation is really uncommon for YAML and may also cause some problems with the screen real estate. This PR brings back 2 level indentation.
Issue: https://github.com/serverless/serverless/issues/1514

Bring back 2 level YAML indentation

---

docs/understanding-serverless/serverless-yaml.md
docs/understanding-serverless/services-and-functions.md
lib/Serverless.js
lib/classes/Service.js
lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/tests/index.js
lib/plugins/create/templates/aws-nodejs/serverless.yaml
lib/plugins/create/templates/aws-python/serverless.yaml
tests/classes/Service.js

A service now has no hard runtime dependency. The runtime could now be stored in the provider object of the corresponding service.
Issue: https://github.com/serverless/serverless/issues/1565

Remove hard service runtime dependency

---

lib/plugins/package/lib/zipService.js
lib/plugins/package/tests/zipService.js

When zipping binaries, the file permissions (eg: executable flags) are not stored, this PR makes sure that the flags do exists, so you can run your executables (within Lambda)
This is basically the same fix as in https://github.com/serverless/serverless/pull/960, the permissions need to be set correctly. This is a regression :)

Make sure permissions are saved in the zipfile

---

tests/integration_test.js

Ready
Make sure we set a random name when running the integration test for the service we create. Otherwise it will confuse the CF stacks

Overwrite service name with random number

---

docs/guide/installation.md

This makes it clear how you can run multiple Serverless versions (e.g. the alpha and v0.5) at once on your machine.

Add note how to run multiple Serverless versions at once

---

docs/understanding-serverless/serverless-yaml.md
docs/understanding-serverless/services-and-functions.md
lib/plugins/aws/deploy/compile/functions/README.md
lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/tests/index.js

Change the name to `memorySize` so that it's the same name as AWS suggests.

Change memory to memorySize so that the config naming is consistent

---

docs/guide/custom-provider-resources.md
lib/plugins/aws/deploy/compile/events/apiGateway/README.md

This PR shows how to add custom cloud formation resources by setting up an HTTP proxy as an example. Resolves #1598 and #1603 
cc/ @flomotlik @pmuens @ac360

added docs for setting proxy via CF

---

lib/plugins/aws/deploy/compile/events/apiGateway/README.md
lib/plugins/aws/deploy/compile/events/apiGateway/index.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/apiKeys.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/all.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/apiKeys.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/index.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js

Adds support for providing API Keys for APIG as described in [Issue 1595](https://github.com/serverless/serverless/issues/1595)
**Status:** G2M from my side

Add support for setting API Keys for APIG

---

docs/guide/event-sources.md
docs/guide/overview-of-event-sources.md
docs/understanding-serverless/serverless-yaml.md
lib/plugins/aws/deploy/compile/events/apiGateway/README.md
lib/plugins/aws/deploy/compile/events/s3/README.md
lib/plugins/aws/deploy/compile/events/schedule/README.md
lib/plugins/aws/deploy/compile/events/sns/README.md
lib/plugins/create/templates/aws-java-gradle/serverless.yaml
lib/plugins/create/templates/aws-java-maven/serverless.yaml
lib/plugins/create/templates/aws-python/serverless.yaml

Event indentations are now fixed so that users won't have trouble when they refer the docs or uncomment existing, nested event definitions in the `serverless.yaml` file.

Fix wrong event indentation

---

docs/guide/overview-of-event-sources.md
lib/plugins/aws/deploy/compile/events/apiGateway/README.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js

Ready
Adds the principal identifier to the default request template. Custom authorizers are returning a response that includes the principal identifier, which is usually needed in the backend ([Output from an Amazon API Gateway Custom Authorizer](http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html#api-gateway-custom-authorizer-output)).

adding principalId to request template

---

lib/classes/PluginManager.js
tests/classes/PluginManager.js

Corresponding issue: https://github.com/serverless/serverless/issues/1695
This PR adds a quick fix to support two level deep shortcut to option conversion (so that you can enter `serverless deploy function -f hello`).
Moving forward we may refactor the PluginManager code to support more infinitely nested commands via recursions (but this should be an extra issue IMHO --> See https://github.com/serverless/serverless/issues/1716).

Add support to convert shortcut to options for two level deep commands

---

docs/using-plugins/core-plugins.md
lib/plugins/Plugins.json
lib/plugins/aws/deployFunction/README.md
lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/tests/index.js
lib/plugins/deploy/README.md
lib/plugins/deploy/deploy.js
tests/all.js

This plugin makes it possible to deploy a single function from the service directly to the lambda function via the AWS SDK (bypassing CloudFormation and S3) which makes it ⚡ blazing fast ⚡ .
Corresponding issue: https://github.com/serverless/serverless/issues/1652
**Note:** Shortcuts for nested commands is not yet implemented (so you cannot use `serverless deploy function -f <name>` but you can use `serverless deploy --function <name>`). An issue was already created (see https://github.com/serverless/serverless/issues/1695). Will update the core in a separate PR so that this is also possible.
/cc @flomotlik @eahefnawy

Add single function deployment plugin

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/resources.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/resources.js

Ready
Resources and Methods were referenced by their index which made redeploying fail when you swapped the order of functions or added new ones anywhere bar the bottom of the object
Closes #1683

fix(deploy): Functions no longer need to maintain order

---

docs/guide/custom-provider-resources.md
lib/plugins/aws/deploy/lib/core-cf.json
lib/plugins/aws/deploy/lib/initializeResources.js
lib/plugins/aws/deploy/tests/initializeResources.js

Added functionality to add custom IAM role statements to the IAM role assumed by the service functions. Resolves issue #1535.
I also removed outdated `${project}` `${stage}` & `${region}` variable references that are relics from version 0. The strings get replaced anyway in code

Added custom IAM role statements

---

lib/classes/Service.js
lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/tests/index.js
lib/plugins/aws/invoke/index.js
lib/plugins/aws/invoke/tests/index.js
lib/plugins/aws/logs/index.js
lib/plugins/aws/logs/tests/index.js
tests/classes/Service.js

This PR sets a default `name` property in the function object if it doesn't exist. This includes updating the logs and invoke plugins as they're using the function name. Resolves Issues #1718 & #1697
cc/ @flomotlik @pmuens

Set default or custom function.name property

---

lib/classes/CLI.js
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/updateStack.js
lib/plugins/aws/remove/lib/stack.js

Corresponding issue: https://github.com/serverless/serverless/issues/1446
This PR implements a . printing while loading (e.g. checking if the stack is created).
This will reduce the used terminal real estate dramatically.

Print a . while loading

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/deployment.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/deployment.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js

Adds a unique timestamp token to the APIG deployment logical id to prompt AWS CF to restart deployment.

added unique token to deployment logical id

---

docs/guide/overview-of-event-sources.md
docs/using-plugins/core-plugins.md
lib/plugins/aws/deploy/compile/events/dynamodb/README.md
lib/plugins/aws/deploy/compile/events/kinesis/README.md

Add "mock plugin directory" (where we can later on easily start the implementation in when we have enough feedback) and docs how to setup stream support for Kinesis and DynamoDB.
Furthermore links to the corresponding GitHub issues are added.
@mthenw can you take a look if the stream syntax is correct? Thanks!
Corresponding issues are:
[DynamoDB](https://github.com/serverless/serverless/issues/1441) and [Kinesis](https://github.com/serverless/serverless/issues/1608)

Add docs for DynamoDB and Kinesis stream setup

---

docs/understanding-serverless/serverless-yml.md
lib/classes/Service.js
tests/classes/Service.js

PR for issue #1728
Ready
Moves `variableVariable` syntax to the `defaults` object in `serverless.yaml`. Add the `variableSyntax` property to  `docs/understanding-serverless/serverless-yml.md` with a brief explanation explanation.
I was a little unsure about what to add in the docs. I've kept it minimal but if more explanation is required let me know.

Move variableSyntax into defaults and update docs

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js

This checks are already done in the main `awsDeploy` plugin which uses the `compileAPIGEvents` plugin.
Issue: https://github.com/serverless/serverless/issues/1774

Remove unnecessary checks in API Gateway validate method

---

lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/tests/index.js

The `functionName` is now determined by the function object instead of creating it with the stage and region parameters.
Issue: https://github.com/serverless/serverless/issues/1773

Refactor functionName retrieval for deployFunction plugin

---

docs/guide/overview-of-event-sources.md
lib/plugins/aws/deploy/compile/events/sns/README.md
lib/plugins/aws/deploy/compile/events/sns/index.js
lib/plugins/aws/deploy/compile/events/sns/tests/index.js

Added functionality for SNS events to accept a `topic_arn` configuration, which enables the function to hook to a pre-existing SNS topic. Resolves Issue #1607
cc/ @flomotlik @pmuens

Added topic_arn config to SNS events

---

docs/guide/overview-of-event-sources.md
lib/plugins/aws/deploy/compile/events/sns/README.md
lib/plugins/aws/deploy/compile/events/sns/index.js
lib/plugins/aws/deploy/compile/events/sns/tests/index.js

A simple refactor to update the naming for the event definition so that camelCase is used (as described in #1804).

Refactor YAML convention for SNS event definitions

---

lib/classes/Error.js
lib/plugins/aws/index.js

This PR adds a friendly error message for when a `default` profile is not set in the user computer as discussed in Issue #1520.
cc/ @pmuens @flomotlik

Added friendly error for missing AWS credentials

---

docs/developing-plugins/building-provider-integrations.md
lib/plugins/aws/deploy/README.md
lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/tests/index.js
lib/plugins/deploy/README.md
lib/plugins/deploy/deploy.js
lib/plugins/package/README.md
lib/plugins/package/index.js
lib/plugins/package/tests/index.js

The renaming of the lifecycle events as discussed in https://github.com/serverless/serverless/issues/1577
@flomotlik @eahefnawy a question we have to answer before merging this is whether we want to introduce a deprecation warning here.
My feeling is that we don't have that much external plugins (if any) for now so we might want to skip the deprecation warning for now. What do you think?

Rename lifecycle events of deploy plugin

---

docs/guide/provider-account-setup.md

Simple typo fix in the docs. Comparison:
To set them up through the `aws-cli` install it first the run `aws configure`
To set them up through the `aws-cli` install it first then run `aws configure`

Fix typo the -> then

---

docs/guide/overview-of-event-sources.md
lib/plugins/aws/deploy/compile/events/apiGateway/README.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js

Ready
I've included a stage reference in the body template so that I can determine the run-time environment of the lambda function; see issue #1849. This provides a quick work around until issue #1455 is resolved.

include stage reference in body mapping template

---

lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/updateStack.js
lib/plugins/aws/deploy/tests/createStack.js
lib/plugins/aws/deploy/tests/updateStack.js
lib/plugins/deploy/README.md
lib/plugins/deploy/deploy.js

This PR fixes the "wrong CloudFormation template" bug (https://github.com/serverless/serverless/issues/1880).
Furthermore a refactoring was done and test for the `writeTemplateToDisk` functions are added.

Fix and refactor noDeploy support and add tests

---

lib/classes/Utils.js

This PR removes the automatic servicePath detection as it might introduce weird / unexpected behavior (`findServicePath` will now look into the current CWD instead of doing a directory traversal if the `serverless.yml` or `serverless.yaml` file is not found).
Corresponding issue is: https://github.com/serverless/serverless/issues/1192

Remove automatic servicePath detection to prevent unintended behavior

---

lib/classes/Error.js
lib/plugins/create/templates/aws-java-gradle/serverless.yml
lib/plugins/create/templates/aws-java-maven/serverless.yml
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml

The docs are now available at docs.serverless.com (rather than v1.docs.serverless.com).

Update outdated doc references

---

lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/lib/updateStack.js
lib/plugins/aws/deploy/lib/uploadCloudFormationTemplate.js
lib/plugins/aws/deploy/lib/uploadDeploymentPackage.js
lib/plugins/aws/deploy/tests/all.js
lib/plugins/aws/deploy/tests/index.js
lib/plugins/aws/deploy/tests/updateStack.js
lib/plugins/aws/deploy/tests/uploadCloudFormationTemplate.js
lib/plugins/aws/deploy/tests/uploadDeploymentPackage.js

The CloudFormation template will now be uploaded to S3 and referenced from there
in the updateStack method.
Corresponding issue is https://github.com/serverless/serverless/issues/1740
/cc @flomotlik @eahefnawy

Fix hitting CloudFormation TemplateBody limit

---

docs/understanding-serverless/serverless-yml.md

Adds VPC configuration examples to serverless-yml.md
Not sure if the omission was intentional but it seemed missing, speak up if it was intended to be as is and I'll happily close the PR.

Add VPC Config

---

lib/plugins/aws/info/index.js
lib/plugins/aws/info/tests/index.js

This adds a check to the `awsInfo` plugin which checks for the `noDeploy` option and causes the `deploy:deploy` hook to be ignored so that the error about the missing stack is not show.
Corresponding issue: https://github.com/serverless/serverless/issues/1878

Fix noDeploy errors when stack is not created

---

docs/understanding-serverless/serverless-yml.md

service names can't have underscore as it causes validation error with CF StackName

fix example serverless.yaml service name

---

lib/plugins/aws/deploy/tests/createStack.js
lib/plugins/aws/deploy/tests/updateStack.js
lib/plugins/aws/deploy/tests/uploadDeploymentPackage.js
lib/plugins/aws/deployFunction/tests/index.js
lib/plugins/aws/invoke/tests/index.js
lib/plugins/create/tests/create.js
lib/plugins/package/tests/cleanup.js
lib/plugins/package/tests/zipService.js
lib/plugins/tracking/tests/tracking.js
tests/all.js
tests/classes/PluginManager.js
tests/classes/Serverless.js
tests/classes/Service.js
tests/classes/Utils.js
tests/classes/YamlParser.js
tests/integration_test.js
tests/utils/index.js
tests/utils/tests/index.js

Adds a testing util method so that tmpDirs are always unique and don't depend on the time.
Corresponding issue: https://github.com/serverless/serverless/issues/1887
/cc @flomotlik @eahefnawy

Add getTmpDir util method and refactor tests

---

lib/plugins/package/lib/zipService.js
npm-shrinkwrap.json
package.json

Ready
On Windows, ```process.platform``` equals ```win32```, therefore ```platformName``` was ```UNIX``` instead of ```DOS```.
This leaded into a strange behavior of resulting zip on UNIX platforms.
According to [jszip docs](http://stuk.github.io/jszip/documentation/api_jszip/generate_async.html), ```platform``` option also accepts ```process.platform``` values.
I simplified the code by passing ```process.platform``` directly.
It fixes the deploy bug on Windows described in #1835.

Fixed platform detection for generating zip

---

lib/plugins/create/templates/aws-java-gradle/serverless.yml
lib/plugins/create/templates/aws-java-maven/serverless.yml
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml

Ready
Include an `iamRoleStatements` snippet (commented-out) in the default `serverless.yml` generated as part of a service template (fixes #1923).

Fix #1923: Include commented-out IAM statements in templates' serverless.yml.

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/authorizers.js

Ready
See #1948
When using the object notation without providing a TTL, [`String(authorizer.resultTtlInSeconds)`](https://github.com/serverless/serverless/blob/85f4084e6b0fd4a6d763ace8cd0db82817bbc712/lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js#L46) returns "undefined", which makes the creation of the authorizer fail.

Fix authorizer creation error when no TTL is supplied (fixes #1948)

---

lib/plugins/create/README.md
lib/plugins/create/create.js
lib/plugins/create/tests/create.js

So that one can create a service in other directories than the cwd.
**Todos:**
Corresponding issue: https://github.com/serverless/serverless/issues/1726

Add path option to create plugin

---

lib/plugins/aws/deploy/compile/events/apiGateway/README.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/authorizers.js

***Implementing Issue:*** #1983
Changed default API Gateway custom authorizer header from Auth to Authorization.

fix #1983 - rename default custom authorizer header to Authorization

---

docs/guide/overview-of-event-sources.md
lib/plugins/aws/deploy/compile/events/apiGateway/README.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js
lib/plugins/aws/deploy/lib/core-cloudformation-template.json

This PR updates the default request / response templates support but also adds support for custom request / response templates.
The corresponding issue is: https://github.com/serverless/serverless/issues/1593
/cc @flomotlik @eahefnawy 
---
**Todos:**
---
Functionality can be validated with this `functions` definition:
```
http:
method: get
path: whatever
request:
template:
text/xhtml: { "stage" : "$context.stage" }
text/plain: { "httpMethod" : "$context.httpMethod" }
response:
headers:
Content-Type: "'text/html'"
template: $input.path('$')
```

API Gateway request / response templates support

---

lib/classes/PluginManager.js
tests/classes/PluginManager.js

***Implementing Issue:*** #1271
I implemented #1271
I implemented that the PluginManager can check against a regular expression.
If the check fail, the errorMessage is displayed.
```
foo: {
options: {
bar: {
customValidation: {
regularExpression: /^[0-9]+$/,
errorMessage: 'Custom Error Message',
},
},
},
}
```
Please set customValidation option in a plugin.
```
options: {
stage: {
usage: 'Stage of the service',
shortcut: 's',
},
region: {
usage: 'Region of the service',
shortcut: 'r',
customValidation: {
regularExpression: /^[0-9]+$/,
errorMessage: 'Custom Error Message',
},
},
}
```
If the check fail, the errorMessage is displayed.

Add custom validation for plugin options

---

lib/plugins/aws/deploy/compile/events/apiGateway/README.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js

***Implementing Issue:*** #1168 
Added ability to specify a pass-through behavior for API Gateway requests.  It requires that you select one of the valid methods (NEVER, WHEN_NO_MATCH, WHEN_NO_TEMPLATES), and uses NEVER as the default value if none was specified.
I updated the apiGateway events method processing to include a check for the "passThrough" configuration.  If none specified, it will use the default value.  If an invalid value is passed, an error will be thrown.
Update your function config under events.http.request to include a "passThrough" value.
```yml
functions:
create:
handler: posts.create
events:
- http:
method: get
path: whatever
request:
passThrough: WHEN_NO_TEMPLATES
```
You can verify that the resulting CloudFormation template under Integration -> PassthroughBehavior …

Fixing #1168 - adding ability to specify APIG pass through behavior

---

lib/plugins/aws/deploy/compile/events/apiGateway/README.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js

***Implementing Issue:*** #608
Status code support for API Gateway (that you can e.g. return a 404 from within your lambda function).
Added the `method responses` and `integration responses` to the `API Gateway compile method` method.
Use this handler to raise a 404 error:
```
module.exports.hello = (event, context, cb) => {
cb(new Error('[404] Not found'));
}
```
- Uses the old resources logical Ids in test

Add status code support for API Gateway

---

docs/01-guide/03-deploying-services.md
docs/01-guide/07-removing-services.md

***Implementing Issue:*** 
Added verbose mode to deploy and remove docs so users now right away that the verbose mode is available.

Add verbose mode to deploy and remove docs

---

lib/classes/Variables.js
tests/classes/Variables.js

***Implementing Issue:*** #2054
Fixed a bug with the variable system where referencing sub properties of files/self that are referencing other variables/properties are not populated.
I added a new `getDeepValue()` method in the `Variables` class that takes care of populating deep references. This method is used by `getValuefromSelf` and `getValueFromFile` methods. After it populates the references property, it makes sure we populate any other referenced variables by calling the `populateProperty()` method again.
using the following config:
```yml
service: serverless-complex-vars
custom:
testA: ${self:custom.testB.testD}
testB: ${self:custom.testC}
testC:
testD:
BucketName: hello-world
provider: aws
functions:
hello:
resources:
Resources:
testBucket:
Type: …
```

Bug fix for referencing sub properties of reference variables

---

README.md
docs/01-guide/04-invoking-functions.md
docs/01-guide/05-event-sources.md
docs/01-guide/06-custom-provider-resources.md
docs/01-guide/07-removing-services.md
docs/01-guide/README.md
docs/03-cli-reference/07-tracking.md
docs/04-extending-serverless/02-creating-provider-plugins.md
docs/04-extending-serverless/README.md
docs/README.md
docs/usage-tracking.md

***Implementing Issue:*** README.md links not working #2095
* Change links to `docs` folders to the `README.md` in that folder
* Include `./` for relative links that didn't have it
* Change links that started with `/` to appropriate relative path e.g. `../../lib/<whatever>`
* Update links to files that seem to have been renamed.
Click through the links as though you were following the `README.md` that is displayed when you visit https://github.com/nurous/serverless/
There were some broken links that were not clear what I should update them to in the source files they are:
```
../using-plugins/core-plugins.md
../understanding-serverless/serverless-env-yml.md
```

Fixing links in documentation

---

docs/01-guide/05-event-sources.md
docs/01-guide/07-removing-services.md

Removing links that pointed to folders and instead point to files now

point folder links to README files

---

lib/plugins/aws/deploy/tests/createStack.js
lib/plugins/aws/info/tests/index.js
lib/plugins/aws/remove/tests/bucket.js
lib/plugins/aws/tests/index.js
lib/plugins/aws/tests/monitorStack.js

Updates a few sinon stub tests that were missing argument checks.
[Issue #1899](https://github.com/serverless/serverless/issues/1899)
Looked through test implementations in all files, attempting to adhere to practices from other tests, and verified that tests with sinon stubs had argument checking (i.e., expect(sinonStub).args[*].to.be.('argument')).
Most sinon stub tests that were checking arguments ignored or skipped static argument types, in monitorStack.js, so I tried to check arguments that were dynamic, mainly StackNames.
Creates test cases to check for correct arugments from sinon stubs

Issue #1899 : Update sinon stubbed tests to always check for correct args

---

docs/02-providers/aws/events/02-s3.md

Missing `handler` in the handler path

s3 events docs typo

---

docs/01-guide/05-event-sources.md

Fixed the Quick Start Guide referencing the wrong endpoint for the given example in the "Setting up Events" section".
Changed endpoint path to match given example
Read the altered page.
None

[DOCS] Match endpoint path to example in "Setting up Events"

---

lib/plugins/aws/index.js
lib/plugins/aws/tests/index.js

***Implementing Issue:*** #2140 
Get Serverless s3 bucket physical resource id by calling `describeStackResource` instead of iterating over `describeStackResources`.
Deployment of any service will do.

Update to use describeStackResource

---

docker-compose.yml
lib/plugins/aws/index.js
lib/plugins/aws/tests/index.js

Profiles were always set in the credentials, thus if a user provided environment keys, but no profiles the build failed (as it did on master).
Only set the profile credentials if a profile is actually configured. Additionally removed the AWS_$STAGE_PROFILE functionality as its not necessary any more and confusing.
export environment variables for your AWS SDK account and remove the profile config from a serverless.yml file. The file should be correctly deployed. If you want to deploy a service to a different profile simply set up that profile and deploy there after configuring the profile config in the serverless.yml

Fix profile handling when other keys are present

---

lib/classes/Variables.js
tests/classes/Variables.js

***Implementing Issue:*** #2143
I moved assignment of `variableSyntax` in `Variables.js` from the `constructor` to a new method that is called in `populateService`. This ensures that the configuration is loaded from `serverless.yml` before `variableSyntax` is set.
Add a custom variableSyntax to `serverless.yml`.

fix bug where variableSyntax is never set from config

---

docs/04-extending-serverless/01-creating-plugins.md

Adding docs for recently merged feature #1978
This PR adds the missing documentation so that plugin authors know that they can use custom validations to validate their plugin options.
Added some docs with a code example in the `01-creating-plugins.md` file.
Go to `docs/04-extending-serverless/01-creating-plugins.md` to read the documentation

Add docs for custom validations in plugin options

---

docs/03-cli-reference/02-deploy.md
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/updateStack.js
lib/plugins/aws/deploy/tests/createStack.js
lib/plugins/aws/deploy/tests/updateStack.js

***Implementing Issue:*** #2016 
Basically made it so writeCreateTemplateToDisk() or writeUpdateTemplateToDisk() is always called on a create/update action, respectively, whether or not the -noDeploy option was used.
deploy a function as per normal
`sls deploy`
you should now see cloudformation-template-(create|update)-stack.json files in .serverless/, in addition to the .zip file

- ensure the Create/Update CloudFormation templates are always written to disk, even if the noDeploy option was not specified

---

lib/classes/Service.js
tests/classes/Service.js

***Implementing Issue:*** #2027 
At the same time as the code is checking for `functionName` and initialising `events` (if unspecified), I added a check that `events` is an array, and throw a `ServerlessError` if not.
Specify an object of values for `events` (or anything other than an array) and run an `sls` command.
Here is a sample function definition (note `events` is an object):
```yml
functions:
logging:
handler: functions/logging.handler
events:
http:
path: logging
method: get
```
You will see the following error when you try to run `sls info`:
```bash
sls info
Events for "logging" must be an array, not an object
```
- ~~Write documentation~~

Add check (and test) that function.events is an array.

---

lib/classes/Utils.js
tests/classes/Utils.js

State: is ready
No issue.
Problem: I don't know whether an error has occurred in any "yml" file
Before
After
see the js-yaml README(https://github.com/nodeca/js-yaml)
serverless.yml(valid)
```yml
service: my-serverless-app
custom: ${file(./myCustomFile.yml)}
provider:
name: aws
functions:
hello:
```
myCustomFile.yml(Invalid)
```yml
: foo
```
```sh
$ sls help
```

add filename option to YAML.load

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js

AWS now supports the ANY method for catching any http request, this adds support for it.
Here is a serverless.yml that configures the any keyword.
```
service: aws-any-test
provider: aws
functions:
hello:
events:
- http: any users
```
After deployment you can run curl against an endpoint:
```
curl ENDPOINT_URL -v # for GET reqeust
curl -X POST ENDPOINT_URL -v
```

Add any to list of allowed http methods

---

package.json
tests/classes/PluginManager.js

***Implementing Issue:*** #2044 
To enable running tests, provided a relative path to "_mocha" in the package.json.
Addressed the test invocation of the "serverless" JS script in Windows by adding "node" to the command used to invoke.
Can verify that this works on Windows by running the 'npm test' command in the root directory. The unit tests should all run. There is currently *ONE* test failure which will need to be addressed.

Windows contrib blockers

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js

***Implementing Issue:*** #2049: API Gateway returns 200 when function times out
Trivial change to add a match for "Task timed out after" in the response integration template
Working example here (times out after 20 seconds and return a 500): https://stage-stealth-monitoring.domain.com.au/services/health/users-api-v1

Fix #2049: API Gateway integration to return 500 when Lambda functions time out

---

lib/plugins/aws/invoke/tests/index.js

Added test case for verifying that YAML is properly parsed when used as the event input.
Modified the JSON version of the same test.
Replace any event.json with the equivalent event.yml, invoke the lambda with that event.yml and all results should be the same.

Fix for #1994. Adds test to verify that YAML may be used for event.

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/resources.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/resources.js

Required an AWS API resource path part to be a single `-` character,  currently ParentId for a `AWS::ApiGateway::Resource` has to be alphanumeric so Cloud Formation errors as it is removed when normalized. This pull request translates the `-` character into the word `Dash` to allow the resource to be created in AWS API Gateway.
Simple regex replace of `-` to `Dash`
Specs below, additionally using my fork currently on a project to allow me to continue with work, so it is well tested.
I do have a different version that used short SHA's of the strings for the path names but presumed you wanted to keep this format as it would have other implications for RegEx matching in methods.
Thought I would keep it simple, hopefully this will suffice. 💃

Support Dash Character for API Gateway Resource Path

---

.gitignore

Ignore tracking-id file which shows up in `git status` every time I work on serverless.
I changed .gitignore.
(before fix): Do something like `npm test` and observe the `tracking-id` file in lib under `git status`.
(after fix): Git does not care about the file

add tracking-id to .gitignore

---

tests/classes/PluginManager.js

A super small bugfix. The 'test' code actually always runs, since describe blocks are always executed, so for example if you did `mocha test -g "..."` even if it does not match this test, the test still runs. Mocha also doesn't treat it as a test failure but rather it interferes with the entire test run.
I changed a single word.
Run `npm test`. Still works :D

Fix very small bug with PluginManager tests.

---

docs/02-providers/aws/04-resource-names-reference.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/resources.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/resources.js

At the moment when you create a variable path in APIG the Cloudformation resource name does not say that its a variable path. This can be an issue when somebody calls a path by the same name as the variable, e.g.:
```
- http: get users/something
- http: get users/{something}
```
This PR adds `var` at the end of the APIG Resource CF name.
Regex parsing of CF path variable.
Copy the folliwing function config into your service and it should correctly set the names
```
functions:
hello:
timeout: 1
events:
- http: get users/{somevar}
- http: get users/{secondsomevar+}
```

Add Var at the end of path variable CF name

---

lib/plugins/package/tests/zipService.js
tests/classes/Utils.js

I made `npm test` pass on Windows.
By making one test not rely on explicit path structure (slashes problem) and one test perform a slightly less robust check if the platform is windows. (Alternatively, we could use that check on all platforms).
Run `npm test` on Windows and something not-Windows (CI counts, I guess)

fix Tests not passing on Windows

---

.eslintignore
.gitignore
lib/plugins/aws/deploy/tests/uploadArtifacts.js
tests/classes/Service.js
tests/utils/index.js

Add a subdirectory so that all directories which are generated for the tests are stored there.
Furthermore old tests are updated so that they use the tmpDir name generated by the test
utils functionality. This makes working with Docker way better as the tmpDirs are not created
It the root directory.
**Note:** This PR play nicely together with e.g. this one https://github.com/serverless/integration-test-suite/pull/25 as it uses the same nesting (tmpDirs created by both will be stored in the `tmpdirs-serverless` directory).
Added subdirectories to the path the `getTmpDirPath` test utils method generates.
Just run `npm test`. You won't see any differences (as long as you are not using Docker).
/cc @flomotlik

Add subdirectory for tmpDirs

---

tests/classes/CLI.js
tests/classes/PluginManager.js

Sometimes tests fail because integration tests have too limited timeouts set, setting timeouts higher for those integrationt tests.

Allow integration tests longer timeouts

---

docs/03-cli-reference/05-info.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/apiKeys.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/apiKeys.js
lib/plugins/aws/info/index.js
lib/plugins/aws/info/tests/index.js

This PR fixes the problem that the `id` of the API Keys was displayed in the `info` plugin (rather than the actual values).
Corresponding issue / PR: https://github.com/serverless/serverless/pull/2079 and https://github.com/serverless/serverless/issues/2058
Updated the `info` plugin so that it fetches the correct API key values via the AWS SDK when some are available for the service.
Here's the `serverless.yml` config:
```yml
service: tinker
provider:
name: aws
apiKeys:
- myKey
functions:
hello:
events:
- http:
method: get
private: true
```
Next up run `serverless deploy` and copy the value of the corresponding API Key.
After that you can use the value to perform a GET request against the endpoint.
You might even want to add other API keys in the …

Fix api key value displaying in info plugin

---

docs/02-providers/aws/events/01-apigateway.md

***Implementing Issue:*** #1968 (related)
In file **`docs/02-providers/aws/events/01-apigateway.md`**, example code in section **Using custom request templates**:
```yml
request:
template:
text/xhtml: { "stage" : "$context.stage" }                  # <--- should be quoted!
application/json: { "httpMethod" : "$context.httpMethod" }  # <--- should be quoted!
```
Strings containing `:`, `{`, `}`, `[`, `]`, `,`, `&`, `*`, `#`, `?`, `|`, `-`, `<`, `>`, `=`, `!`, `%`, `@`, `` ` `` must be quoted.
so the example should be like this:
```yml
request:
template:
text/xhtml: '{ "stage" : "$context.stage" }'
application/json: '{ "httpMethod" : "$context.httpMethod" }'
```
Without the quotes, deployments will fail at `AWS::ApiGateway::Method` step.
I've been trying to use the custom request template …

[DOCS] Fix docs example code in YML: strings should be quoted

---

docs/02-providers/aws/events/01-apigateway.md

Fixed the AWS::ApiGateway::Method referenced in the docs. According to [the AWS docs][docs] `ResourceId` and `RestApiId` should be members of `Properties`.
[docs]: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#aws-resource-apigateway-method-syntax.yaml
I changed the code example to match the AWS docs.
Compare Amazon's [YAML example][docs] to my alteration.

[DOCS] Fix AWS::ApiGateway::Method format

---

lib/plugins/aws/deploy/lib/createStack.js

***Implementing Issue:*** #1973
Add logic in lib/plugins/aws/deploy/lib/createStack.js createStack() function to test the invalid stack name and throw the correct and meaningful error message.
Just to deploy a invalid AWS CF stack name and the error message will appear.

fix: #1973 deploy fails with unhelpful error message when service name is not a valid CF stack name

---

docs/02-providers/aws/events/02-s3.md
lib/plugins/aws/deploy/compile/events/s3/README.md
lib/plugins/aws/deploy/compile/events/s3/index.js
lib/plugins/aws/deploy/compile/events/s3/tests/index.js

***Implementing Issue:*** #1873
Add support for filter rules in s3 events configuration
--
The rules can be implemented in an array of objects, each containing a single key/value with the key being the rule name (suffix, prefix)
```ynl
functions:
resize:
handler: resize.hello
name: image-resize
events:
- s3:
bucket: upload
event: s3:ObjectCreated:*
rules:
-  prefix: images/
-  suffix: .jpg
```
There can only be one rule per type, this is related to aws api, Check this [issue](https://github.com/aws/aws-cli/issues/1465)

S3 event rules

---

lib/plugins/aws/deployFunction/index.js

Add a fix so that the Promise chain in the `deployFunction` plugin resolves correctly.
Return the whole Promise and put the success message which is printed by the console into a separate `then`.
Just run `serverless deploy function -f <function-name>` and see that the console message is shown when the function is deployed (and not earlier like before).

Fix Promise chain in deployFunction plugin

---

docs/01-guide/10-packaging.md
lib/classes/Service.js
lib/plugins/create/templates/aws-java-gradle/serverless.yml
lib/plugins/create/templates/aws-java-maven/serverless.yml
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml
lib/plugins/package/README.md
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/zipService.js
lib/plugins/package/tests/packageService.js
lib/plugins/package/tests/zipService.js
npm-shrinkwrap.json
package.json
tests/classes/Serverless.js
tests/classes/Service.js

***Implementing Issue:*** #2071
* Added globs as a dependency of project
* Updated to use globs for `exclude`
* Update specs to test relevant changes
Add folder src to a project then use example config to verify they are not included.  Other glob patterns can be tested.
Example config:
```
package:
exclude:
- "src/**"
- "test/**"
- "**/spec.js"
```

Use Globs to Exclude Files

---

lib/Serverless.js
lib/classes/CLI.js
lib/classes/PluginManager.js
tests/classes/CLI.js
tests/classes/PluginManager.js

***Implementing Issue:*** #2084
***Implementing Issue:*** #2041
***Implementing Issue:*** #2037
***Implementing Issue:*** #1570
***Implementing Issue:*** #2041
I made PluginManager support arbitrarily nested commands by using loops/recursion instead of explicit checks (firstLevel -> secondLevel)
This made a bunch of stuff simpler and fixed a number of bugs. I also restricted plugin loading to just relevant ones (i.e match provider).
One of the key changes was to make the pluginManager deal with the command object itself, vs. just an array of strings pointing to the command. (Exception: run and getCommand).
I think most PluginManager actions are now fairly straight forward, self-contained functions.
N/A as it mostly just fixes up what people expected / what was documented already? …

refactor PluginManager and CLI to better support command nesting, cleanup

---

lib/classes/Error.js

***Implementing Issue:*** #2109
I added Node version and Serverless version in `lib/Error.js`
Please exec `$ serverless tracking e` in your serverless project, and show messege below

add Node version and Serverless version in CLI errors

---

tests/classes/PluginManager.js

I noticed that one test was failing but not causing Mocha to fail. 
This was because the test was not returning the promise chain. I fixed this, and fixed the test (which I had not updated in my earlier PR when I made it only load plugins of the appropriate provider).
`npm test`

fix PluginManager tests were not returning promises

---

docs/02-providers/aws/events/01-apigateway.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js

***Implementing Issue:*** #2174 
Adds the new `AWS_PROXY` feature (Lambda proxy) as a default for the method integrations in API Gateway. Furthermore users can set this integration to `AWS` --> `integration: lambda` in their `serverless.yml` file.
Updated the `method.js` file in the API Gateway compilation step.
Here's a `serverless.yml` file for validation:
```yml
service: tinker
provider:
name: aws
functions:
hello:
events:
- http:
method: get
```
Furthermore you might run the tests with `npm test`.
/cc @flomotlik @eahefnawy

Add Lambda proxy functionality for API Gateway

---

lib/classes/Error.js

I fixed the bug that there is no line break on top of `Your Environment Infomation`.
I added line break
Please exec `$ serverless tracking e` in your serverless project. I fixed it as follow

Add newline on error message

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js

***Implementing Issue:*** #2270 
Escape characters in default API Gateway form url encoded body mapping template.
Wrapped body keys and values in a `$util.escapeJavaScript()` call.
Create a handler that does anything and add a POST http event:
```
functions:
endpoint:
handler: handlers.endpoint
events:
- http:
path: endpoint
method: post
```
* Create an HTML form with a `textarea` input.
* View the form in a browser, and **type in some text with newlines** in the text area.
* Submit the form
```
<form
action="https://##########.execute-api.##-####-#.amazonaws.com/dev/endpoint"
method="POST"
>
<textarea name="message"></textarea>
<button type="submit">Send</button>
</form>
```
Fixes #2270

Correctly Escape Form URL Encoded Values

---

.travis.yml
lib/plugins/aws/tests/index.js
tests/integration_test.js

Stubbed out the AWS SDK for the `getCredentials()` so that keys are not exposed in failing tests.
Added a proxyquire and a corresponding stub and replaced the `awsSdk` usage with the proxyquired one.
Run `npm test` to see that all tests are still passing despite the fact that the source code is changed to use the proxyquire with the stub.

Stub AWS SDK for getCredentials() tests

---

docs/02-providers/aws/events/01-apigateway.md

Fixes a misleading `statusCode` usage introduced due to copy and paste.
Just updated the `statusCode`.
Take a look at the API Gateway README.

Fix wrong statusCode in API Gateway README

---

lib/classes/Utils.js
tests/classes/Utils.js

***Implementing Issue:*** #2278
Prints out a note when the tracking-id is created so that the user is aware of tracking.
Added a `log` statement in the section of `track()` where the tracking id is generated.
Run the tests with `npm test` or create a new service (without having a tracking-id in the Serverless directory).

Print note about tracking

---

bin/serverless

***Implementing Issue:*** #2328
Silences the tedious deprecation warnings.
Disabled them globally with the help of `process`.
Checkout this branch and run some commands where the `aws-sdk` will be used.

Closes #2328 - Silence deprecation warnings

---

package.json

Otherwise we've had way too many files pushed to NPM and to users.

Only include specific files into npm deployment

---

README.md

I've added the `serverless-wsgi` plugin for serving Python web applications to the list of v1.0 supported plugins, as I believe it will be useful to other developers.
This is simply a README.md change.
Read that `serverless-wsgi` appears below the *Plugins (V1.0)* header.

Add serverless-wsgi to list of plugins in README.md

---

docs/02-providers/aws/README.md
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/updateStack.js
lib/plugins/aws/deploy/tests/createStack.js
lib/plugins/aws/deploy/tests/updateStack.js

***Implement custom Stack Tags and Policy:*** #1956 
Implemented by adding two optional serverless.yml parameters:
* provider.stackTags - a map of CF stack tags
* provider.stackPolicy - a list of CF stack policies
Tags are obvious and more details about stack policies can be found at:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html#stack-policy-reference
Deploy the following config:
```yml
provider:
name: aws
stackTags:
key: value
stackPolicy:
- {Effect: Allow, Principal: "*", Action: "Update:*", Resource: "*"}
- {Effect: Deny, Principal: "*", Action: [Update:Replace, Update:Delete], Condition: {StringEquals: {ResourceType: [AWS::EC2::Instance]}}}
```
In CloudFormation console verify that the tags and policy has been set.

Implement stack tags and policy #1956

---

docs/02-providers/aws/events/01-apigateway.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js

Added the ability to customise the return codes used by APIGateway so that different strategies can be used when deciding what should be returned. i.e. JSON objects
Adapted the default codes to be customisable. Also fixed a bug with the defaults were CORS was not applied to anything other than the default return code.
See additions to the README.md file for an example on how to test
#2024 #2025 #2099

Custom status codes support

---

lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/tests/monitorStack.js

Fixes a bug where error messages were not thrown / shown during stack monitoring process (e.g. during stack creation process).
Updated the `monitorStack` method so that it immediately throws an error when a `*_FAILED` ResourceStatus is reported.
1. Install https://github.com/pmuens/serverless-crud
2. Deploy it
3. Remove it
4. Re-Deploy it
You should see the error that the DynamoDB table `users` is still there (this error was previously not shown).

Fix not thrown error after failed ResourceStatus bug

---

lib/Serverless.js
lib/classes/PluginManager.js
tests/classes/PluginManager.js

The `PluginManager` class has no more responsibility to store the provider information (what provider the service should use).
Removed the `setProvider` method and replaced the check for the provider with an access to `this.serverless.service.provider.name`
Look at code / run tests.

Remove provider storage on PluginManager level

---

lib/classes/PluginManager.js
lib/plugins/awsProvider/awsProvider.js
lib/plugins/awsProvider/awsProvider.test.js
tests/classes/PluginManager.js

The provider property in a plugin can be a string or the ProviderPlugin instance.
This introduces more beautiful code patterns when building plugins.
Extended the `PluginManager` to support both types of provider properties.
See tests.

Add string and instance powered provider check

---

lib/plugins/create/create.js

***Implementing Issue:*** #2428 
If service name exists, skip the update service message

Don’t show log message if service name exists

---

tests/integration/aws/api-gateway/integration-lambda/api-keys/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/api-keys/tests.js

API keys should be unique on a per-test basis.
Add code which parses the `serverless.yml` file and replaces the key before the deployment with a unique name.
Run the corresponding integration tests.

Update API Gateway API keys integration test

---

docs/02-providers/aws/README.md
lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/lib/configureStack.js
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/mergeIamTemplates.js
lib/plugins/aws/deploy/lib/updateStack.js
lib/plugins/aws/deploy/tests/all.js
lib/plugins/aws/deploy/tests/configureStack.js
lib/plugins/aws/deploy/tests/createStack.js
lib/plugins/aws/deploy/tests/index.js
lib/plugins/aws/deploy/tests/mergeIamTemplates.js
lib/plugins/aws/deploy/tests/updateStack.js
lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js
tests/integration/all.js
tests/integration/aws/general/overwrite-resources/service/handler.js
tests/integration/aws/general/overwrite-resources/service/serverless.yml
tests/integration/aws/general/overwrite-resources/tests.js

***Implementing Issue:*** #2359 & #2404
* Fixes overwriting default resources using custom resources
* Fixes creating IAM templates in the update step rather than the create step
* Fixes bucket region validation for us-east-1
I've moved the process of merging custom resources **after** compiling functions/events, hence enabling overwriting.
I've moved IAM templates to the update step, which works fine if no custom bucket was provided. If custom bucket is provided, it gets a little complicated because the create step does not have any resources to create (no bucket to create).
So in that case I switch to a 1 step deployment process by creating **all** resources at the same time by falling back to a create method when trying to update everything. On second deployment, update works the same …

fixed overwrite resources bug

---

tests/integration/all.js
tests/integration/aws/api-gateway/integration-lambda-proxy/api-keys/service/handler.js
tests/integration/aws/api-gateway/integration-lambda-proxy/api-keys/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/api-keys/tests.js
tests/integration/aws/api-gateway/integration-lambda-proxy/cors/service/handler.js
tests/integration/aws/api-gateway/integration-lambda-proxy/cors/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/cors/tests.js
tests/integration/aws/api-gateway/integration-lambda-proxy/custom-authorizers/service/handler.js
tests/integration/aws/api-gateway/integration-lambda-proxy/custom-authorizers/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/custom-authorizers/tests.js

Adds the same integration tests for the `lambda-proxy` integration type which are already in place for the `lambda` integration type. This way we cover both integration types with the same tests (CORS; API Keys, Authorizers, Simple API setup).
Copied the tests from the `lambda` integration type and updated them so that they work with the `lambda-proxy` integration type.
Just run the complex integration test suite.

Add additional API Gateway tests for lambda proxy integration

---

lib/classes/Utils.js

This is a simple fix which removes the name of the timezone as this information varies based on the language of the OS (which in return makes it impossible to group by timezone as some of the timezones have a different name although they are basically the same).
`GMT+0200 (CEST)` --> `GMT+0200`
Updates the regex which extracts the timezone. Furthermore the Version of the Schema was updated from `1` to `2` as this might introduce a breaking change in reports (/cc @worldsoup).
Use a regex tool and test the regex or `console.log` out the data which is gathered.

Fix timezone retrieval bug

---

docs/01-guide/README.md
docs/03-cli-reference/04-invoke.md
lib/plugins/aws/invoke/index.js
lib/plugins/aws/invoke/tests/index.js

***Implementing Issue:*** #2442
Allow for the given `path` parameter to be an absolute path.  Detect this case and do not prepend the service path in this case.
Update docs appropriately
Fix random missing apostrophe
run tests or use an absolute path with the `-p` flag

Allow invoke to accept absolute paths

---

lib/plugins/aws/deploy/compile/events/apiGateway/index.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/index.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/validate.js

Splitting up: #2262
This refactors the validate and index parts of compile apiGateway events, which is needed before I can open all the other PRs for each function that actually processes events. So while this looks like a 'pointless' change, it's a precursor.
validate returns an object now, which makes it simpler for each sub-function to enumerate http events (they don't have to loop through them all validating HTTP each time)
`npm test` passes as do the `simple-api` integration tests for both integration types.

refactor apiGateway index and validate

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/apiKeys.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/deployment.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/apiKeys.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/deployment.js

Breaking out https://github.com/serverless/serverless/pull/2262
I moved the refactoring of apiKeys and restApi from that PR to this one.
`npm test` passes, and the api-keys integration tests pass.

refactor apiKeys and restApi

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/deployment.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/apiKeys.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/deployment.js

Splitting up: https://github.com/serverless/serverless/pull/2262
This is the refactoring of apiGateway/deployments. It also includes restApi, as a dependency. It's the same changes as https://github.com/serverless/serverless/pull/2491/files
`npm test` passes, as to the `simple-api` integration tests.

refactor apiGateway deployment and restApi

---

docs/02-providers/aws/events/01-apigateway.md

Simple text addition to api-gateway docs to note that `event.body` needs to be `JSON.parse()`'d when using `lambda-proxy`

Update api-gateway.md docs to include note about parsing JSON event body

---

lib/classes/Error.js

Fixes a minor typo in the environment info of the error message.
Fixed typo.
Run `serverless deploy wasd`

Fix typo in environment error message

---

lib/plugins/aws/deploy/compile/functions/index.js

Prettifies the error message and fixes typos.
Just updated the error message.
Specify an invalid `functions` definition in `serverless.yml` and run `serverless deploy`.

Prettify AwsCompileFunctions error messages

---

tests/integration/aws/api-gateway/integration-lambda-proxy/api-keys/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/cors/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/custom-authorizers/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/simple-api/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/api-keys/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/cors/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/custom-authorizers/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/simple-api/service/serverless.yml
tests/integration/aws/general/custom-resources/service/serverless.yml
tests/integration/aws/general/nested-handlers/service/serverless.yml
tests/integration/aws/general/overwrite-resources/service/serverless.yml
tests/integration/aws/schedule/multiple-schedules-multiple-functions/service/serverless.yml
tests/integration/aws/sns/multiple-topics-multiple-functions/service/serverless.yml
tests/integration/aws/sns/multiple-topics-single-function/service/serverless.yml
tests/integration/aws/sns/single-topic-multiple-functions/service/serverless.yml
tests/integration/aws/sns/single-topic-single-function/service/serverless.yml
tests/integration/general/custom-plugins/service/serverless.yml

Add the `cfLogs: true` setting in the services of the integration tests so that the log groups will be removed automatically when the stack is removed.
Just added the setting in the corresponding `serverless.yml` file.
Run the complex integration test suite.

Update integration tests to auto remove log groups

---

docs/providers/aws/examples/hello-world/node/README.md
docs/providers/aws/examples/hello-world/python/README.md

This is a documentation fix for a broken link.
Found the correct document and changed the links in the tutorial pages. 
Go to https://serverless.com/framework/docs/providers/aws/examples/hello-world/node/ and click "see installation guide," then notice you are on a 404 page. 
***Is this ready for review?:*** Yup

Fix link from hello-world examples to framework installation docs

---

lib/classes/Service.js
lib/classes/Service.test.js
lib/plugins/aws/deploy/lib/mergeIamTemplates.js
lib/plugins/aws/deploy/tests/mergeIamTemplates.js

Closes #2267
Allows people to create services that do not contain functions.
Simply removed the error and defaulted the functions property to an empty object.
Create a project with a simple config and try a deployment.
```
service: test-sls-proj
provider:
name: aws
```

Allow services with no functions #2267

---

lib/plugins/aws/deploy/compile/events/stream/index.js

Bug fix for #2474.
Updated regular expression to remove `_` characters from`normalizedStreamName`.
Create a DynamoDB table with a name that contains an underscore, activate streams on the table, and then try to deploy a Serverless function with an event source mapping pointing to this stream. Previously you would get an error as described in #2474.

fix AWS event stream deploy fails if name contains underscore

---

lib/classes/Utils.js
lib/classes/Variables.js
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/tests/generateArtifactDirectoryName.js

Fixes the recently introduced linting errors.
Update regexes.
Run `npm run lint`

Fix regex linting errors

---

lib/plugins/aws/provider/awsProvider.js

Remove the repetitive provider name in the `setProvider()` call.
Just replaced the string with a call of the `getProviderName()` static method.
See that tests pass.

DRY out setProvider() usage

---

lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/tests/monitorStack.js

Closes #2383 and #2395
Closes the issue where the deployment failed with the nasty `endsWith` error message.
Added checks if variable is not null if `endsWith` is used.
Shoutouts to @bobby-brennan for providing the fix for it 🎉 
Deploy the example listed in the issue for it (see above).

Fix failing deployment bug

---

docs/providers/aws/guide/packaging.md
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/zipService.js
lib/plugins/package/tests/packageService.js
lib/plugins/package/tests/zipService.js
npm-shrinkwrap.json
package.json

**_Implementing Issue:**_ #2264 and #2472
- Switched out glob to use glob-all that supports `!` patterns and arrays of patterns being passed for globbing.
- Added spec demoing re-inclusion glob patterns
Example of re-including `node-fetch` module after excluding all `node_modules`
```
package:
exclude:
node_modules
!node_modules/node-fetch
```

Allow Inclusion after Exclusion using ! Globs

---

CHANGELOG.md
RELEASE_CHECKLIST.md
npm-shrinkwrap.json
package.json
scripts/prs-since-last-tag

Bumping to 1.1.0 and adding Changelog

Bump to 1.1.0

---

lib/plugins/create/templates/aws-java-gradle/build.gradle
lib/plugins/create/templates/aws-java-maven/pom.xml

Update aws-lambda-java-events to 1.3.0 in both `aws-java-gradle` and `aws-java-maven` template.
`aws-java-gradle` use old version 1.1.0 before and `aws-java-maven` didn't have this dependency.
This library includes all aws lambda trigger events like s3 events, dynamodb events etc. so it's better to include it in template. 
Create a new project with those two templates then you should able to see aws-lambda-java-events dependency with version 1.3.0

update aws-lambda-java-events to 1.3.0

---

lib/plugins/aws/deploy/lib/uploadArtifacts.js
lib/plugins/aws/deployFunction/index.js

Before
```
Serverless: Packaging service…
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading service .zip file to S3…
Serverless: Updating Stack…
Serverless: Checking Stack update progress…
```
After
```
Serverless: Packaging service…
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading service .zip file to S3 (335 B)…
Serverless: Updating Stack…
Serverless: Checking Stack update progress…
```

show package file size during deploy

---

lib/plugins/aws/invokeLocal/tests/index.js
lib/plugins/aws/provider/awsProvider.test.js

Removed test causes that `npm test` has a wrong exit code (0) when some tests are failing.
Closes #2603.

fix failing tests exit code

---

README.md

Include `serverless-subscription-filter` to the list of plugins
The plugin provide CL commands on CLI to register a Cloudwatch subscription filter for a source function and pipe to another to process.

Add serverless-subscription-filter to the plugins

---

lib/plugins/package/lib/packageService.js
lib/plugins/package/tests/packageService.js

The exclude glob was not matching .git or .serverless, so these were being included in packages.
I added `/**` to the end of the globs.
`sls deploy --noDeploy` and then unzip the file.

fix Glob for .git and .serverless directories

---

docs/providers/aws/guide/packaging.md

Small docs change to add an example for including a single file when packaging
Based on the discussion in #2529 , may update depending on my question with the `node_modules` example that doesn't seem to work for me

Updated example for only including a specific file in output

---

lib/classes/Utils.js
lib/classes/Utils.test.js

Closes #2610 
Adds a way to consider whitelisted options in the `logStat()` method.
Add an array with whitelisted options and filter against it. Store the filtered options in the object for `logStat()`.
Tests will cover that. Otherwise run e.g. `serverless deploy --help` and see that `help` appears in the `filteredOptions` object.

Add whitelisted options support for logStat

---

docs/providers/aws/guide/workflow.md

Simple correction for incorrect serverless command name in docs cheat sheet example.
Error is here: https://serverless.com/framework/docs/providers/aws/guide/workflow/

Fix command name in docs cheat sheet example

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js
lib/plugins/aws/deploy/compile/events/apiGateway/tests/authorizers.js

Closes #2587 
It has returned `false` when set to 0, then fixed to reterun 0.
Please set 0 in `resultTtlInSeconds` statement and run `sls deploy`.

fixed the bug resultTtlInSeconds defaults to 300 when set to 0

---

.github/PULL_REQUEST_TEMPLATE.md

Add a checkbox item which should notice the PR creator to enable edit permissions for Serverless maintainers. This will make the whole collaboration easier.
See: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ for more infos about this feature.
Updated the `.md` file for the PR template.
Just take a look at the PR template.

Add checklist item for change permissions to PR template

---

docs/providers/aws/events/schedule.md
lib/plugins/aws/deploy/compile/events/schedule/index.js
lib/plugins/aws/deploy/compile/events/schedule/tests/index.js

I have added support for parsing Input and InputPath variables when defining a Schedule event.
An attempt to close #2543.
```
- schedule:
rate: rate(10 minutes)
enabled: false
input: '{"key": "value"}'
- schedule:
rate: rate(10 minutes)
enabled: false
input: 
key: 'value'
- schedule:
rate: cron(0 12 * * ? *)
enabled: false
inputPath: ''
```

add input, inputPath variable, resolves #2543

---

tests/integration/aws/api-gateway/integration-lambda-proxy/simple-api/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/simple-api/tests.js
tests/integration/aws/api-gateway/integration-lambda/simple-api/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/simple-api/tests.js

Add the integration tests for the recently merged refactoring PR #2666 which cover the usage of slashes in path configuration (including root paths).
Update the `simple-api` tests in the complex integration test suite.
Run `npm run complex-integration-test`

Add integration tests for slashes in API Gateway paths

---

lib/plugins/aws/info/index.js
lib/plugins/aws/info/tests/index.js

Closes https://github.com/serverless/serverless/issues/2671
I split the path to array and filtered empty fractions.
Create a service with endpoints
```
functions:
hello:
events:
- http:
path: without
method: get
- http:
path: /starting
method: get
- http:
path: /
method: get
- http:
path: /both/
method: get
- http:
path: e
method: get
```
deploy service `serverless deploy` and run `serveless info` and output should be:
```
Service Information
service: fix-endpoints
stage: dev
api keys:
None
endpoints:
GET - https://154rulmui7.execute-api.us-east-1.amazonaws.com/dev/without
GET - https://154rulmui7.execute-api.us-east-1.amazonaws.com/dev/starting
GET - https://154rulmui7.execute-api.us-east-1.amazonaws.com/dev
GET - …
```

Fixes info plugin endpoint path issue

---

tests/integration/simple-integration-test.js

Fixes a timeout issue and set one global timeout (like we do in the `complex-integration-test` suite).
Set global timeout in `describe` block rather than `it`. Removed all the timeouts in the `it` blocks.
Run `npm run simple-integration-test`

Fix timeout issue in simple integration test

---

docs/providers/aws/guide/variables.md
lib/classes/Variables.js
lib/classes/Variables.test.js

**Problem:**  
Serverless Variables are awesome, but they don't support generating dynamic data. 
Use-cases:
* Generating a random string to use in a `serverless.yml` value, every time Serverless is run.
* I keep mock event data to test my functions with in `serverless.yml`.  But, I need to generate random values in those mocks to make them more realistic and robust.  With this, I can.
* Do anything with Serverless Variables in Javascript(!!!) 
Added a few lines of code (and moved existing code around which makes this change look larger than it is) to `Variables.js` to allow for dynamic data via javascript.
* In `serverless.yml`, use this reference:
```yml
provider:
stage: ${file(./confg.js):dynamicData}
```
* Make a `config.js` in your service root, with this code:
```js …
```

Variables js support

---

lib/plugins/aws/invokeLocal/index.js

Closes #2620 
- On success, invoke local returns only the response. Removed the message `Serverless: successfully invoked your function`.
- On error, it returns the code is wrong, the line, stacktrace as  follow
```
$../serverless/bin/serverless invoke local --function function1
/Users/horike/src/develop-serverless/src/function1/handler.js:7
sss{
^
SyntaxError: Unexpected token {
at Object.exports.runInThisContext (vm.js:76:16)
at Module._compile (module.js:528:28)
at Object.Module._extensions..js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
at AwsInvokeLocal.invokeLocalNodeJs …
```

Improve responses in `invoke local`

---

lib/classes/CLI.test.js
lib/classes/PluginManager.test.js

Remove unnecessary timeout definitions which caused the tests / build randomly to fail if the timeout was exceeded.
Just set the timeout for the tests to `0`.
Run `npm test` to see that everything is still working as expected.

Remove unnecessary timeouts in tests

---

docs/providers/aws/guide/packaging.md
lib/Serverless.test.js
lib/classes/Service.js
lib/classes/Service.test.js
lib/plugins/create/templates/aws-java-gradle/serverless.yml
lib/plugins/create/templates/aws-java-maven/serverless.yml
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml
lib/plugins/create/templates/aws-scala-sbt/serverless.yml
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/zipService.js
lib/plugins/package/tests/packageService.js
lib/plugins/package/tests/zipService.js

Closes #2460
Brings back the `include` configuration on a per-service and per-function level.
Added the include configuration and updated the zipping and packaging configuration so that the `include` definitions (globs) are appended to the `exclude` array. This way `globs.sync` will re-add the files (see https://github.com/jpillora/node-glob-all#usage).
Create the following directory structure:
With this `serverless.yml`
```yml
service: reword-include-exclude
provider:
name: aws
package:
exclude:
- excluded-by-default.json
- excluded-directory/**
include:
- excluded-directory/should-be-included.js
- excluded-directory/include-directory/**
functions:
hello:
#package:
#functions:
```
Comment out the stuff you want to test and run `serverless deploy …

Bring back include configuration for an easier packaging control

---

tests/integration/simple-integration-test.js

Ensures that the log groups of the simple integration tests are also removed once the service is removed.
Use `sed` to add the config to the created `serverless.yml file`
Just run `npm run simple-integration-test`

Add cfLogs config to simple integration test

---

tests/integration/all.js

Closes #2655
Remove the API Keys tests for now.
Just removed the tests.
Run `npm run complex-integration-test`.

Remove API Keys integration tests

---

lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/tests/createStack.js

Closes https://github.com/serverless/serverless/issues/2648
**Before**
When deploying without internet connection `serverless deploy --noDeploy` throws following error 
```
Error --------------------------------------------------
ServerlessError: ServerlessError: Inaccessible host:
`cloudformation.us-east-1.amazonaws.com'. This service
may not be available in the `us-east-1' region.
For debugging logs, run again after setting SLS_DEBUG env var.
Please report this error. We think it might be a bug.
Your Environment Information -----------------------------
OS:                 darwin
Node Version:       6.9.0
Serverless Version: 1.1.0
```
And …

Fixes --noDeploy without credentials or internet connection

---

docs/providers/aws/guide/functions.md
lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/tests/index.js

Lambda environment variable support.
Closes #2673
Added a new property to the function template object and then used Object.assign to merge the dictionaries from the provider object and the function object.
```yml
service: environment-variables
provider:
environment:
provider_level: provider
name: aws
cfLogs: true
functions:
hello:
environment:
FUNCTION_LEVEL: function
events:
- http:
path: hello
method: get
```
```javascript
'use strict';
module.exports.hello = (event, context, callback) => {
// Use this code if you don't use the http event with the LAMBDA-PROXY integration
callback(null, {
message: 'Go Serverless v1.0! Your function executed successfully!',
event,
context,
env: process.env,
});
};
```
***Is this ready for …

Lambda environment variables

---

lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/tests/index.js

Add support for lambda env vars in invoke local. Any env vars that you set in `serverless.yml` will be available when you run `sls invoke local` without having to load them manually.
Added a new `loadEnvVars()` method to invoke local that runs before running the function.
```yml
service: serverless-local-env-vars
provider:
name: aws
cfLogs: true
environment:
hello: world
functions:
hello:
environment:
hello2: world2
hello: worldOverwritten
```
```js
module.exports.hello = (event, context, callback) => {
console.log(process.env.hello)
console.log(process.env.hello2)
const body = {
message: 'Go Serverless v1.0! Your function executed successfully!',
input: event,
};
const response = {
statusCode: 200,
headers: {
'custom-header': 'Custom header value',
},
body: …
```

add support for lambda env vars in invoke local

---

lib/plugins/aws/provider/awsProvider.js

bring back provider.getStackName()

---

.travis.yml
docs/providers/aws/guide/functions.md

Closes #2699
Skips builds which only contains `.md` / `docs` changes.
Add a `before_install` script.
I ran the following tests:
- Change `README.md` --> Build skipped
- Change `docs/*.md` --> Build skipped
- Change `*.js` file --> Build ran
- Change `*.md` and `*.js` file --> Build ran

Skip Travis builds on .md changes

---

lib/plugins/aws/lib/naming.js
lib/plugins/aws/lib/naming.test.js

Closes #2771 
There was an accidental change in the logical ID name of the APIG resource. A very tiny change in capitalization.
Check the issue

fixed breaking change with apig resource with variable

---

docs/providers/aws/cli-reference/invoke.md
docs/providers/aws/guide/packaging.md
docs/providers/aws/guide/services.md
lib/plugins/create/create.test.js
tests/templates/integration-test-template

Merging #2787 brokes the tests and left some incorrect `event.json` references in the codebase. This PR fixes this.
Removed unnecessarz `event.json` references.
Look through the changes in this PR.

Cleanup after event.json removal

---

.travis.yml
docs/providers/aws/guide/functions.md

Closes #2790 
Remove the build skipping.
Remove the `before_install` script.
Look at Travis.

Remove skipping of Travis builds for .md changes

---

docs/providers/aws/guide/resources.md
lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/index.test.js
lib/plugins/aws/lib/naming.js

This change publishes a Lambda version for each deploy. Now Lambda deploys count as distinct function versions, which is really helpful for logging & monitoring.
This change adds:
- Calculation of SHA256 sums of artifacts
- An `AWS::Lambda::Alias` resource based on that SHA
- A dependency between each deployed function to its alias
- A stack output for each function `LogicalIdQualifiedArn` which is the
function ARN with the version appended.
In any serverless project, apply this patch and do a deploy. After the deploy, check in the console for the new function alias. Alternatively, use the CLI command `aws lambda list-versions-by-function --function-name yourservice-stage-functionName` and note that in addition to `$LATEST` there's also a pinned version. 
***Is this ready for review?:*** …

On every deploy, publish a new Lambda function version

---

docs/providers/aws/guide/resources.md
lib/plugins/aws/deploy/compile/functions/index.test.js
lib/plugins/aws/lib/naming.js

Quick fix for the Lambda::Version logical ID to stay consistent with our pattern. Compliments PR #2676.. (Thanks @ryansb 😊 )

fixed logical id for lambda version

---

0.5.x-RESOURCES.md
README.md

As discussed a week ago in the chat we want to keep the README slick and therefor move 0.5 resources to another file. Initially it was suggested to move into docs, but then they would end up on the website and that might be more confusing than helpful to a lot of people.
Moved the resources to a separate file and linked to it.

move 0.5 resources to a separate file

---

lib/plugins/aws/configCredentials/awsConfigCredentials.js
lib/plugins/aws/configCredentials/awsConfigCredentials.test.js
lib/plugins/config/config.js
lib/plugins/config/config.test.js

Closes #2839
I noticed that command which don't have any life-cycle event are filtered out anyway. I didn't expect this, but comes quite handy in this case without introducing any weird edge cases.
run `serverless --help` or  just `serverless` and config should not be in the list

remove the lifecycle event from config to hide it in the command list

---

lib/plugins/aws/invokeLocal/fixture/handlerWithError.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js

Closes #2612
This implements AWS Lambda behaviour.
Run `sls invoke local` against function calling back error
we shouldn't format or color error messages all over the codebase. There should be one place with logs styling. I will create issue for that becuase right now it's like inline css styles.

fix returning error from local invocation

---

lib/classes/Service.js
lib/classes/Service.test.js

Rename provider name from 'ibm' to 'openwhisk'.
OpenWhisk is open-source and the platform instance is not tied to IBM's cloud. This change is related to the upcoming OpenWhisk provider implementation.
https://github.com/serverless/serverless-ibm-openwhisk
Simple string replacement. 
Updated Service.test.js to verify this functionality change.
```
npm test
```

rename provider identifier from 'ibm' to 'openwhisk'.

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.test.js

Closes #2798
What was being 'ignored' was the parsing of the request/response configuration, not the configuration itself.
Tests pass, and example yaml in the issue now deploys.

remove request and response config when using proxy integration

---

lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js

Closes #2700 
added default lambda env vars to local invoke
make sure handler console.logs `process.env` and run the function locally, you should see something like the following:
```
{ PATH: '/usr/local/lib64/node-v4.3.x/bin:/usr/local/bin:/usr/bin/:/bin',
LANG: 'en_US.UTF-8',
LD_LIBRARY_PATH: '/usr/local/lib64/node-v4.3.x/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib',
LAMBDA_TASK_ROOT: '/var/task',
LAMBDA_RUNTIME_DIR: '/var/runtime',
AWS_REGION: 'us-west-2',
AWS_DEFAULT_REGION: 'us-west-2',
AWS_LAMBDA_LOG_GROUP_NAME: '/aws/lambda/lambda-default-env-vars-dev-hello',
AWS_LAMBDA_LOG_STREAM_NAME: '2016/12/02/[$LATEST]f77ff5e4026c45sda9a9ebcec6bc9cad',
AWS_LAMBDA_FUNCTION_NAME: 'lambda-default-env-vars-dev-hello',
AWS_LAMBDA_FUNCTION_MEMORY_SIZE: 1024, …
```

added default lambda env vars to local invoke

---

lib/plugins/aws/configCredentials/awsConfigCredentials.js
lib/plugins/aws/configCredentials/awsConfigCredentials.test.js

Closes #2878
Fixes a bug where the credentials setup errors when the `.aws/credentials` file was not present.
The `.aws` directory and the `credentials` file will now be created if not in place.
Look at the code and run the test suite.

Fix credentials setup bug

---

docs/providers/aws/cli-reference/invoke.md
lib/plugins/aws/invoke/index.js
lib/plugins/aws/invoke/index.test.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js
npm-shrinkwrap.json
package.json

Closes #2211
```
echo 123 | serverless invoke -f testfunc
echo "hello" | serverless invoke -f testfunc
echo "{\"a\": 123}" | serverless invoke -f testfunc
```

add support for stdin in invoke command

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #2890
Temporarily remove provider.variableSyntax during variable population. This will prevent the service from matching on itself.
Run `sls deploy --noDeploy` with a minimal `serverless.yml`
```
service: test-sls-proj
provider:
name: aws
cfLogs: false
variableSyntax: '\${{([\s\S]+?)}}'
```

Temporarily remove provider.variableSyntax during variable population

---

lib/plugins/slstats/slstats.js
lib/plugins/slstats/slstats.test.js

Closes #2784
I moved the code to rename the stats file to a new function called createStatsFile.
This renames the current stats file or creates it if none has been created. If there is an error in writing the file or renaming the file, fse will throw an error. (I was being mindful of #1604 and #2313.)
The code won't throw an error if the file is not found as a new one should be created.
I have moved all the code in the toggleStats method to the try, catch block so any error in the process is caught.
I have added 2 tests and modified 1.
1. Created a test for the creation of the stats file.
2. Created a test if the current file exists and the same command is run again, that the file remains.
3. Modified the error thrown test, so it will catch an example error message instead of the 'file …

Slstatsfix

---

lib/plugins/aws/deploy/compile/events/stream/index.js
lib/plugins/aws/deploy/compile/events/stream/index.test.js

I put a condition whether we have custom IAM role or not in order to create a proper EventSourceMapping template.
Fixes [#2813](https://github.com/serverless/serverless/issues/2813)
I simply check provider.role and function.role whether we have custom IAM role in ARN format `arn:aws:iam::account:role/foo` and if so, I change DependOn to be empty array, instead of `IamPolicyLambdaExecution`. Empty array behaves like there wouldn't be DependOn at all.
Note: I decided to go this way to keep `streamTemplate` the same without condition concatenating of strings. 
We should be able to successfully build this serverless.yaml script:
```yaml
service: hello-service
provider:
name: aws
cfLogs: true
role: arn:aws:iam::account:role/foo
functions:
hello: …
```

fix bug in event source mapping with custom IAM role

---

docs/providers/aws/cli-reference/install.md
lib/plugins/install/install.js
lib/plugins/install/install.test.js

Closes #2721
- Download zip that the Github repo whole things.
- Delete except for specific directories.
Please run as follow:
```
serverless install --url=https://github.com/serverless/examples/tree/master/aws-node-rest-api-with-dynamodb
```

Add support for directories in url of install command

---

npm-shrinkwrap.json

My colleague and I are working on a plugin that requires an SDK version of at least 2.7.10.
Please sync the shrinkwrap file!

Upgrade AWS SDK shrinkwrap version

---

docs/README.md
docs/providers/aws/events/schedule.md
lib/plugins/aws/deploy/compile/events/schedule/index.js
lib/plugins/aws/deploy/compile/events/schedule/index.test.js

Closes #2832
It is possible to add name and description property of scheduled event in CloudFormation.
These are not required properties.
set property as follow
```yml
events:
- schedule:
name: my-scheduled-event
description: 'my scheduled event'
rate: rate(10 minutes)
```
deployed name and description to a scheduled event Lambda 
Linting errors occurs in master branch. But my implementaion is no problem.

Add CloudWatchEvent rule name and description fields

---

docs/providers/aws/cli-reference/config.md
docs/providers/aws/cli-reference/create.md
docs/providers/aws/cli-reference/deploy.md
docs/providers/aws/cli-reference/info.md
docs/providers/aws/cli-reference/install.md
docs/providers/aws/cli-reference/invoke.md
docs/providers/aws/cli-reference/logs.md
docs/providers/aws/cli-reference/metrics.md
docs/providers/aws/cli-reference/remove.md
docs/providers/aws/cli-reference/rollback.md
docs/providers/aws/cli-reference/slstats.md

Updates the `menuOrder` property so that it matches the one in the overview `README.md` file.
Updated the numbers.
Look into the `.md` files.

Fix order of CLI docs

---

docs/README.md
docs/providers/aws/cli-reference/config-credentials.md

Split up the `config` CLI doc so that it now covers `config credentials`.
Split up the old doc.
Read the docs.

Split up config CLI doc

---

lib/plugins/aws/invoke/index.js
lib/plugins/aws/invoke/index.test.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js

Fixed a bug that prevented you from invoking (remotely or locally) functions without input data.
Try catch block wrapping stdin module
1. create service
2. invoke function locally without passing any data. It should fail with master but work with this fix.
3. deploy service
4. invoke function locally without passing any data. It should fail with master but work with this fix.

fixed bug where you can now invoke without any input data

---

docs/providers/aws/guide/credentials.md

Fixes incorrect pricing info
Documentation change
Follow the included links and see that this new information is correct.
[Free Tier Link](https://aws.amazon.com/free/#AWS_FREE_TIER)
[Lambda Pricing link](https://aws.amazon.com/lambda/pricing/)
Lambda has been moved to have it's own permanent free tier. It is no longer part of the Expiring offers.

Updating section on AWS pricing

---

lib/plugins/aws/deploy/lib/mergeIamTemplates.js
lib/plugins/aws/deploy/lib/mergeIamTemplates.test.js

Closes #2132: Yell when incorrect format for additional IAM Role Statements causes them not to be included
added a validateStatements() in lib/plugins/aws/deploy/lib/mergeIamTemplates.js
```
$ cat > serverless.yml <<EOF
> service: wed-2253
> 
> provider:
>   name: aws
>   runtime: nodejs4.3
>   iamRoleStatements:
>     Version: "2012-10-17"
>     Statement:
>     - Effect: "Allow"
>       Action:
>         - "s3:ListBucket"
>       Resource: "*"
> 
> functions:
>   hello:
>     handler: handler.hello
> 
> EOF
$ sls deploy --noDeploy
iamRoleStatements should be an array of objects, where
each object has Effect, Action, Resource fields. Specifically,
it is not an array
....
```

Fixing Conflicts in PR #2729

---

lib/plugins/aws/deploy/lib/mergeIamTemplates.js
lib/plugins/aws/deploy/tests/mergeIamTemplates.js
lib/plugins/aws/provider/awsProvider.test.js

Closes #2132: Yell when incorrect format for additional IAM Role Statements causes them not to be included
added a validateStatements() in lib/plugins/aws/deploy/lib/mergeIamTemplates.js
```
$ cat > serverless.yml <<EOF
> service: wed-2253
> 
> provider:
>   name: aws
>   runtime: nodejs4.3
>   iamRoleStatements:
>     Version: "2012-10-17"
>     Statement:
>     - Effect: "Allow"
>       Action:
>         - "s3:ListBucket"
>       Resource: "*"
> 
> functions:
>   hello:
>     handler: handler.hello
> 
> EOF
$ sls deploy --noDeploy
iamRoleStatements should be an array of objects, where
each object has Effect, Action, Resource fields. Specifically,
it is not an array
....
```

Fix issue 2132 - Fail when incorrect format for additional IAM Role Statements causes them not to be included

---

tests/integration/simple-integration-test.js
tests/utils/index.js

I tried to run the simple integration test suite on OSX and it failed. The test suite assumed to use Gnu `sed`. This is not very beginner friendly for contributors. 
Replaced sed with a simple node function
Run the simple & complex integration test suite (or at least a part of it).
Examples:
* serverless.yml - Fully functioning to easily deploy changes
* Screenshots - Showing the difference between your output and the master
* AWS CLI commands - To list AWS resources and show that the correct config is in place
* Other - Anything else that comes to mind to help us evaluate
-->

make sure the integration set suite works cross-platform (not depedent on gnu sed)

---

docs/providers/aws/events/schedule.md
lib/plugins/aws/deploy/compile/events/schedule/index.js
lib/plugins/aws/deploy/compile/events/schedule/index.test.js

Closes #2936
Schedule event always defaults to being enabled
```yml
service: simple-service
provider:
name: aws
cfLogs: true
functions:
hello:
events:
- schedule:
rate: rate(1 minute)
world:
handler: handler.world
events:
- schedule: rate(1 minute)
```
Look into the AWS Lambda console to see that it's enabled by default.

fix #2936. Enable schedule event by default.

---

tests/integration/aws/general/package/tests.js

Noticed that not all test ran. This is a fix for a new issue: https://travis-ci.org/serverless/serverless/jobs/185111559#L1811
The other ones only happen on Travis and are not reproducible for me so far.
The match now is more flexible.
Run the integration test suite

fix test as it not always have to be exactly x digits

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js

Closes #2950
Update the status code regexes for the response template so that they match newlines as well.
Updated the status codes.
Play around with different errors in your handler such as the following:
```
callback(new Error('[500] something went wrong'));
```
```
const message = "[500] Value of \"{\n  contactUsURL,\n  featuredBlogPosts\n}\" violates contract.\n\nExpected:\nHomePageProps\n\nGot:\n{\n  contactUsURL: void;\n  featuredBlogPosts: {\n      slug: string;\n      category: string;\n      title: string;\n      author: {\n        role: string;\n        name: string;\n      };\n    }[];\n}";
callback(new Error(message));
```

Update status code regex to match newlines

---

docs/providers/aws/guide/serverless.yml.md

Documentation fix of Fn::Join YAML syntax - similar to https://github.com/serverless/serverless/pull/2874

Missing indentation for Fn::Join params

---

lib/plugins/create/create.js
lib/plugins/create/create.test.js

Refs #2909, #2388 and #2972
This PR adds a check if the service directory which the user attempts to create already exists in the CWD. It's a follow-up PR of #2972 
Just added a quick `if` check if the directory the user wants to create already exists.
Run
```bash
serverless create -t aws-nodejs -p foo
```
and after that
```bash
serverless create -t aws-nodejs -p foo
```

Add check for preexistent service directory

---

docs/providers/aws/cli-reference/install.md
lib/plugins/install/install.js
lib/plugins/install/install.test.js

This PR enables to rename the service when installing from GitHub, for example `serverless install --name new-service-name --url https://github.com/SC5/serverless-messenger-boilerplate` will install `serverless-messenger-boilerplate` to folder `new-service-name` and change `service` value in `serverless.yml` to `new-service-name`.
Closes https://github.com/serverless/serverless/issues/2626
Added new parameter `name` to install class and renameService helper function for renaming service in yaml file.
`serverless install --name new-service-name --url https://github.com/SC5/serverless-messenger-boilerplate` should install service to `new-service-name` folder and change service name to `new-service-name`.

Enables service installation with a name

---

lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/lib/monitorStack.test.js

Closes #2898
Changed ine 51 of monitorStack.js:
~~~~
if (event.ResourceType === 'AWS::CloudFormation::Stack')
~~~~
to
~~~~
if (event.ResourceType === 'AWS::CloudFormation::Stack' && event.StackName === event.LogicalResourceId)
~~~~
I first thought about:
~~~~
if (event.ResourceType === 'AWS::CloudFormation::Stack' 
&& event.StackId === event.PhysicalResourceId)
~~~~
which also works, however as the event.StackId is sometimes used for the name, it seemed that comparing the equality between StackName and LogicalResourceId  is even better.
I also changed test scripts, so that the existing tests don't fail, but also so that CREATE_COMPLETE, UPDATE_COMPLETE and DELETE_COMPLETE tests make sure that the monitoring doesn't stop if the event comes from the nested stack.
1. Use a setup like this in …

fix deployment monitoring

---

docs/providers/aws/guide/credentials.md

The link gave a 404. Updated to what seems to be the correct URL.
Amended link in markdown.
* Navigate to https://serverless.com/framework/docs/providers/aws/guide/credentials/
* Find link labelled `CLI reference` 
* Note that this links to a 404
- [ x] Change ready for review message below

Fixed broken link to Config Credentials in documentation site.

---

lib/plugins/aws/lib/updateStack.js
lib/plugins/aws/lib/updateStack.test.js
lib/plugins/aws/provider/awsProvider.js

Closes #2981
Catch the error, then check for specific error message "No updates to be performed".  continue execution if it is this message, otherwise throw the error to be caught by the next Error handler
Re-deploy an already deployed service without any changes and verify that it does not error out with Error code 1
```yml
provider:
name: aws
#functions:
resources:
Resources:
S3Bucket:
Type: "AWS::S3::Bucket"
```

Fix "No updates to be performed." throwing Error code 1

---

lib/plugins/aws/deploy/compile/events/stream/index.js
lib/plugins/aws/deploy/compile/events/stream/index.test.js

Closes #2508 
Create a single policy statement to cover all DynamoDB/Kinesis stream events, greatly decreasing policy verbosity.
Deploy a function with 50+ stream events. Previously this would fail as described in #2508.

Generate a single policy statement to cover all stream events

---

.gitignore
package.json

[Added ESLint cache](http://eslint.org/docs/user-guide/command-line-interface#caching). Now it will check only files that changed.
**package.json**
```diff
-"lint": "eslint .",
+"lint": "eslint . --cache",
```
This improved speed on my laptop in 4 times:
before:
```bash
$ time npm run lint
real	0m8.896s
user	0m9.420s
sys	0m0.188s
```
after:
```bash
$ time npm run lint
real	0m1.972s
user	0m1.964s
sys	0m0.128s
```
Now it's much more convenient to run lint after code changes.
`npm run lint`

Dramatically improve ESLint’s running time by enabling cache

---

scripts/postinstall.js
scripts/preuninstall.js

Closes #3079 
Fix problem with Bluebird Promise package (might be already removed when the package is uninstalled).
Switch to native Promise support for resolving in a `catch` case.
Run `npm run postinstall` and `npm run preuninstall`

Fix Preuninstall Promise problem

---

lib/plugins/create/create.js
lib/plugins/create/create.test.js

Closes #3063 
Instead of checking `length` property which doesn't exist for numbers, we convert whatever value user provides to a string.
```diff
- const boilerplatePath = this.options
.path && this.options.path.length ? this.options.path : null;
+ const boilerplatePath = _.toString(this.options.path);
```
Previously we assigned `null` to a var, but now it'll be an empty string, which is a falsy value as well. Checked the code, we don't explicitly check for `null`, so it's safe. All the `if / else` should continue to work as expected.
```bash
$ serverless create --template aws-nodejs --path 123
```
This must create a folder `123` and a template inside.

Add support of numeric template creation path

---

lib/plugins/aws/deploy/compile/events/iot/index.js
lib/plugins/aws/deploy/compile/events/iot/index.test.js

Closes #3094 
Removed line feed code from Cloudformation's JSON
set serverless.yml as follow:
```
events:
- iot:
description: >
My multi-
line value.
name: enrollPlayer
sql: >
SELECT * FROM 'path/#'
WHERE prop = 'value'
```

fixed the bug when Multi-line values is given in iot events

---

lib/plugins/aws/deploy/lib/configureStack.js
lib/plugins/aws/deploy/lib/configureStack.test.js

Closes #2404 
Similar to original #2404 fix for us-east-1:
```if (result.LocationConstraint === 'EU') result.LocationConstraint = 'eu-west-1';```
By deploying using pre-existing bucket in eu-west-1 region in one of the affected AWS accounts (which might be tricky to find).

Fix 2404 Receive "Deployment bucket is not in the same region..." when using eu-west-1

---

tests/integration/aws/api-gateway/integration-lambda-proxy/api-keys/tests.js
tests/integration/aws/api-gateway/integration-lambda/api-keys/tests.js

Skip the API Keys integration tests so that builds no longer fail because of the API Keys inconsistencies.
We can activate them again once we've implemented a fix for the API Keys and usage plan integration issue...
/cc @nikgraf --> Note that this only resolves the API Keys problem. The S3 tests are another thing we need to investigate (although they succeed on my local machine using my private AWS account...)

Skip API Keys tests

---

lib/plugins/aws/provider/awsProvider.js

Closes #2758
Removes the deprecated `getStackName()` method.

BREAKING - Remove getStackName() method 

---

lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/index.test.js
lib/plugins/aws/info/getStackInfo.js
lib/plugins/aws/info/getStackInfo.test.js
lib/plugins/aws/lib/naming.js
lib/plugins/aws/lib/naming.test.js
lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

Closes #1825 and refs #2853
The function ARNs are now computed on the fly. Function ARN outputs are no longer generated which reduces the size of CloudFormation Outputs dramatically.
Added a `getAccountId()` method in the provider plugin. Furthermore the adding of the function output is removed in the compile functions step. The arns will be computed on the fly when invoking the `info` command.
Deploy a service and run `serverless info`. Furthermore look into the CloudFormation Outputs section in the AWS console.

BREAKING - Refactor function arn generation for info plugin

---

docs/providers/aws/cli-reference/invoke-local.md

Added two missing `local` qualifiers on invoke local function doc examples.

Add missing "local" qualifiers for invoke local function examples

---

docs/providers/aws/events/sns.md
docs/providers/aws/guide/resources.md
lib/plugins/aws/deploy/compile/events/sns/index.js
lib/plugins/aws/deploy/compile/events/sns/index.test.js
lib/plugins/aws/lib/naming.js
lib/plugins/aws/lib/naming.test.js
tests/integration/aws/sns/existing-topic/service/handler.js
tests/integration/aws/sns/existing-topic/service/serverless.yml
tests/integration/aws/sns/existing-topic/tests.js
tests/utils/index.js

Closes #2183 
Also subscribes to the existing SNS topic when the ARN is specified.
An if/else statement. I preserved the existing behavior at the expense of a small amount of code reuse, so that existing stacks do not change with this feature. (Which is to say: The "Subscription" is part of the "Topic" resource if the topic defined within serverless.yml. If the topic is an arn:, then a new Resource is added to CFN, which is an AWS:SNS:Subscription.
There are unit tests and a new integration test.
```yml
service: new-service
provider:
name: aws
functions:
hello:
events:
- sns: arn:aws:sns:us-east-1:XXXX:my-existing-topic
- sns:
topicName: new-sns-topic
displayName: some description
- sns: third-sns-topic
```

add Support for SNS Subscription to existing topics

---

docs/providers/aws/events/apigateway.md
lib/plugins/aws/deploy/compile/events/apiGateway/lib/cors.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/cors.test.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.test.js

Closes #2182
Added an `allowCredentials` (defaults to false) setting to the `cors` config which determines whether or not ` Access-Control-Allow-Credentials` will be set to true or false in the mock OPTIONS request that is configured by the existing `cors` configuration.
The original fix was implemented by @fruffin then the codebase changed significantly so I applied the same changes to the new code. I don't mean to step on toes, just trying to lend a helping hand @fruffin deserves most of the credit here.
Run unit tests.
Toggle settings in the config and verify the changes are reflected in the CloudFormation template.

Added Access-Control-Allow-Credentials for CORS settings fixes #2182

---

lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/plugins/create/templates/openwhisk-nodejs/.gitignore
lib/plugins/create/templates/openwhisk-nodejs/README.md
lib/plugins/create/templates/openwhisk-nodejs/handler.js
lib/plugins/create/templates/openwhisk-nodejs/package.json
lib/plugins/create/templates/openwhisk-nodejs/serverless.yml

Further to my conversation with @ac360 and @nikgraf about getting framework ready for openwhisk provider support, I've added OpenWhisk templates and updated the create plugin to support this template identifier.
Trivial changes to create plugin and use AWS provider template as source material. 
```
npm test
```
I've added the test case to verify this works for the template identifier.

Adding OpenWhisk NodeJS template to create plugin.

---

lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

A possible fix for https://github.com/serverless/serverless/issues/3151
Switch from using IAM `getUser` to get the account ID of the current user to calling STS `getCallerIdentity`.  It is expected that this is a less protected segment of rights and will, as a result, impact fewer users.  Of course, this is hard to guarantee.
Changes tests appropriately
Related Docs:
http://docs.aws.amazon.com/STS/latest/APIReference/API_Operations.html
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#getCallerIdentity-property
See awsProvider.spec.js tests.  Use this to deploy any project.

Use STS getCallerIdentity instead of IAM getUser

---

bin/serverless

When an error occurs, we get the immediate stack trace but not the entire stack trace.  This often results in traces like:
```
[Container] 2017/01/26 21:33:22 ServerlessError: Access Denied
[Container] 2017/01/26 21:33:22 at (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:177:20)
[Container] 2017/01/26 21:33:22 at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:355:18)
[Container] 2017/01/26 21:33:22 at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
[Container] 2017/01/26 21:33:22 at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
[Container] 2017/01/26 21:33:22 at Request.emit …
```

Enable Long Stack Traces

---

lib/plugins/aws/deploy/compile/events/stream/index.js
lib/plugins/aws/deploy/compile/events/stream/index.test.js

Fixes https://github.com/serverless/serverless/issues/3081 by allowing the role defined for a Lambda to be a reference (e.g. `{ 'Fn::GetAtt', [ 'LambdaLogicalId', 'Arn'] }`) to a role in the current service.  If the `role` attribute is defined, check whether it is a role reference and if it is, fill the `DependsOn` attribute for the event mapping to be that logical ID.
Add tests that make sure this use case is covered in future incarnations of the code.
evaluate the role attribute (from either function or provider) and if it is a `Fn::GetAtt` to an ARN (which uses a LogicalId) use that logical ID as the value for `DependsOn`.
See tests in this PR.  Alternatively, define a role in your service.  Then use that role by reference by defining role on the provider and subsequently on the …

Allow Role 'Fn::GetAtt' for Lambda `role`

---

docs/providers/aws/guide/functions.md
lib/plugins/aws/deploy/lib/iam-policy-lambda-execution-template.json
lib/plugins/aws/deploy/lib/mergeIamTemplates.js
lib/plugins/aws/deploy/lib/mergeIamTemplates.test.js
tests/integration/aws/api-gateway/integration-lambda-proxy/api-keys/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/cors/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/custom-authorizers/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/simple-api/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/api-keys/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/cors/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/custom-authorizers/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/simple-api/service/serverless.yml
tests/integration/aws/general/custom-resources/service/serverless.yml
tests/integration/aws/general/environment-variables/service/serverless.yml
tests/integration/aws/general/nested-handlers/service/serverless.yml
tests/integration/aws/general/overwrite-resources/service/serverless.yml
tests/integration/aws/general/package/service/serverless.yml
tests/integration/aws/s3/multiple-events-multiple-functions-multiple-buckets/service/serverless.yml
tests/integration/aws/s3/multiple-events-multiple-functions-single-bucket/service/serverless.yml
tests/integration/aws/s3/multiple-events-single-function-single-bucket/service/serverless.yml
tests/integration/aws/s3/single-event-single-function-single-bucket/service/serverless.yml
tests/integration/aws/schedule/multiple-schedules-multiple-functions/service/serverless.yml
tests/integration/aws/sns/existing-topic/service/serverless.yml
tests/integration/aws/sns/multiple-topics-multiple-functions/service/serverless.yml
tests/integration/aws/sns/multiple-topics-single-function/service/serverless.yml
tests/integration/aws/sns/single-topic-multiple-functions/service/serverless.yml
tests/integration/aws/sns/single-topic-single-function/service/serverless.yml
tests/integration/general/custom-plugins/service/serverless.yml
tests/integration/general/local-plugins/service/serverless.yml
tests/simple-suite/tests.js

Closes #3115 
Closes #2725 
Closes #2724
This PR removes the optional `cfLogs` property and creates log group CF resources by default. This is a breaking change if you have deployed a service previously without `cfLogs` set to true, and have invoked any function at least once (which implicitly creates a log group outside of the stack template).
Removed the `CreateLogGroup` IAM statement as it's no longer needed, removed cfLogs option and added the LogGroup resources by default.
1. Create new service
2. Deploy the service. You'll see in the CF template the new LogGroups resources, even though you haven't set the `cfLogs` to be true.
3. Invoke some of your functions and make sure the log streams are created successfully by running `sls logs`
***Is it a …

BREAKING - Create Log Group Resources By Default

---

docs/providers/aws/cli-reference/info.md
lib/plugins/aws/info/display.js
lib/plugins/aws/info/display.test.js
lib/plugins/aws/info/getStackInfo.js
lib/plugins/aws/info/getStackInfo.test.js

Removes the generation of arns. Now only the function name will be displayed on the console. This way we save one additional request and prevent deployment failures because the `accountId` retrieval might be not allowed for some users (although @erikerikson already PRed a change for that).
Remove the arn generation. Now only the names are shown.
Deploy a services and look at the output on the console (or use `serverless info`).

BREAKING - Remove on-the-fly arn generation for displayed functions

---

README.md

This links to a fork of the CRUD example that uses FaunaDB instead of DynamoDB.
A version of the CRUD example using FaunaDB.
Forked the CRUD example and changed a little code.
I've updated the readme so that you can run it by following the steps. FaunaDB is free to try.

link to FaunaDB CRUD example from README

---

lib/plugins/aws/deploy/lib/uploadArtifacts.js
lib/plugins/aws/deploy/lib/uploadArtifacts.test.js

I've been having an issue with a particularly large project that's been eating 8+ gigabytes of memory at deploytime (15+ functions, individual deploy zips). 
I switched to using a stream to read artifacts at upload, because it was being read into a `const` that the AWS SDK had to then copy to a bytearray that was wrapped in a TLSStream object, duplicating the artifact several times. 
Create a new template project (I used `aws-python`). Edit serverless.yml to package individually & have 4 functions.
```
service: aws-python # NOTE: update this with your service name
provider:
name: aws
cfLogs: true
package:
artifact: ./deployable.zip
functions:
hello1:
package: {artifact: ./deployable.zip}
hello2: …
```

Reduce memory consumption on deploy by at least 50%

---

docs/README.md

Updated docs page based on #3131.
- Replicated existing graphics
- Eliminated some of the visual clutter
- Updated the copy to include support for Whisk
Note: This layout is already a bit unwieldy with just 2 providers. It should probably be revisited.

update docs page to include whisk guide

---

lib/classes/Service.js
lib/classes/Service.test.js
lib/classes/Utils.js
lib/classes/Utils.test.js
lib/classes/Variables.js
lib/classes/Variables.test.js
lib/plugins/aws/lib/validate.js
lib/plugins/aws/lib/validate.test.js

Closes #2740 
This PR removes support for the deprecated `defaults` service property. @eahefnawy would be great if you could take a deep dive into this PR since you've implemented the variable population 👍 
Looked through the code and updated / removed all references to the `defaults` service property.
Deploy a service or take a look at the tests.

BREAKING - Remove defaults service property

---

lib/Serverless.js
lib/Serverless.test.js
lib/classes/CLI.test.js
lib/classes/Error.js
lib/classes/Error.test.js
lib/classes/Service.js

Let me try once more - as previous PR was closed by GitHub, when I changed the master branch (didn't know about that behavior, sorry).
So this one is for the issue #3169 - Error tests implementation
I was checking this Serverless framework you folks are developing, and it looked interesting. So I've decided to spend some time contributing to it. For the initial PR I've decided to start with something simple - like covering a class with tests.
`lib/classes/Error.js` was not covered - so it was a good thing to start with.
Note, that this PR contains the following changes:
1. Error coverage - major change, pretty straightforward.
2. For the `Error.js` export I renamed `SError` export to `ServerlessError` (the backwards compatibility was left, though). A couple of reasons for that. First, it …

Implementing Error tests (per issue #3169)

---

docs/providers/openwhisk/events/apigateway.md

Updated documentation for OpenWhisk HTTP event which now supports extended options.
https://github.com/serverless/serverless-openwhisk/issues/25

Update HTTP Event docs for extended options

---

docs/providers/aws/guide/credentials.md

Wrote an example how to switch AWS profiles without credentials or profile names inside `serverless.yml` for maximum flexibility when developing multiple projects on the same computer.
So how to define your AWS profile in `~/.aws/credentials` and then once `export AWS_xxxxx` before `sls deploy` and everything works.
Edited the documentation with another paragraph.
Run the code on your own computer by using 2 AWS profiles and switch between them. This is btw default functionality so you only need to verify the remark.
I've experienced that I sometimes got errors complaining that the region was not set, while I added the correct AWS region inside `serverless.yml` for my Lambda function. By adding `export AWS_REGION=eu-west-1` I fixed this issue, but perhaps I am missing functionality or …

Provide example how to switch between AWS profiles

---

lib/plugins/aws/deploy/lib/mergeIamTemplates.js
lib/plugins/aws/deploy/lib/mergeIamTemplates.test.js

Closes #3174
Fixed a bug where LogGroup resources are not created if all your functions use custom roles.
Moved the logic that adds LogGroups resources at the top of the merge method, so that they're always merged, even when no roles are merged, like in the case of custom roles.
Using this config:
```yml
service: log-group-bug
provider:
name: aws
functions:
hello:
role: something
world:
role: somethingelse
handler: handler.world
```
All functions use custom roles, so no role resources are added. Run `sls deploy --noDeploy` and you'll see that the roles resources are not added, while the LogGroup resources are added.

Merge LogGroup Resources, even when no Role resources were merged

---

lib/plugins/package/lib/zipService.js

Closes #3054 and refs #3100
Switch from `readFileSync` to `createReadStream` to reduce memory consumption.
Changed from read file content to streaming file content.
Taken from PR #3100 descriptions
- `serverless deploy --noDeploy`
- In order to notice larger difference, try packaging on this example repo https://github.com/pmuens/serverless-service-zip-testing + do the `npm install` *some large libs* for a more real-life example
- Make sure it creates same file structure, packages exotic filenames and so on.

Reduce memory consumption during zipping process

---

docs/providers/aws/guide/workflow.md

Closes #XXXXX
Minor mistake in the `serverless invoke` command example on the Workflow page of the AWS guide
Fixed markdown file
Review documentation change and confirm that `serverless invoke -f hello` is the proper command (based on a newly created serverless project) rather than `serverless invoke function -f hello` as was previously in the guide.

Fix serverless invoke command example

---

README.md

Chore: the `why-serverless` section was removed in commit 45e7f4e6c65a3d7cf9bbc7a9c350fb65a0586de7, but the anchor was left behind.
Deleted the link
---
---

chore(readme): removes why-serverless section

---

.travis.yml
lib/classes/CLI.test.js

Closes #3265
* Fixed the tests when `SLS_IGNORE_WARNING` is set in the shell environment
* Refactored the tests to clearly expose the tested input combinations (+ added the missing combination, so that we have a formally complete verification)
* Added the `SLS_IGNORE_WARNING=*` setting to Travis builds, so that their output doesn't contain unnecessary noise about upcoming changes
See [Travis CI builds](https://travis-ci.org/zerkella/serverless/builds/202528488) - no more breaking changes output there. See [Coveralls](https://coveralls.io/github/zerkella/serverless?branch=improve-breaking-changes-testing) - the coverage didn't decrease.

Improved tests for `logBreakingChange()` function (see #3265):

---

docs/providers/aws/guide/credentials.md

Add a section with a warning about the AWS profile/IAM role `invoke local` (to alleviate issue #2903)
Alleviate issue #2903 

Profile in place with the invoke local

---

docs/providers/aws/guide/resources.md

Changed the documentation for ApiGatewayResourcePathMethod resource name. should be ApiGatewayMethod{
Was:
ApiGateway::Method -> ApiGatewayResource{normalizedPath}{normalizedMethod} -> ApiGatewayResourceUsersGet
Should be:
ApiGateway::Method -> ApiGatewayMethod{normalizedPath}{normalizedMethod} -> ApiGatewayMethodUsersGet

Fixed documentation.

---

docs/providers/azure/guide/quickstart.md

Needs to either be --function or -f, not function -f
Fixes one bad command in the quickstart documentatoin
Removed a few characters
Trivial

Final command doesn't work

---

lib/plugins/aws/info/display.js
lib/plugins/aws/info/display.test.js
lib/plugins/aws/info/getStackInfo.js
lib/plugins/aws/info/getStackInfo.test.js

Updates the `name` so that it's the name one would use for e.g. the `invoke` command rather than the name on AWS (which introduces confusion).
/cc @brianneisler 
Simply renamed the function name in the `awsInfo` plugin.
See the tests or do a `serverless deploy` or `serverless info`.
***Is it a breaking change?:*** YES...for CI systems depending on stdout

BREAKING - Update function name displaying for info plugin

---

docs/providers/aws/examples/hello-world/csharp/serverless.yml
docs/providers/aws/guide/functions.md
docs/providers/aws/guide/iam.md
lib/plugins/create/templates/aws-csharp/serverless.yml
lib/plugins/create/templates/aws-java-gradle/serverless.yml
lib/plugins/create/templates/aws-java-maven/serverless.yml
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml
lib/plugins/create/templates/aws-scala-sbt/serverless.yml

The IAM role statements currently shown in the docs and templates are not valid. This is because the s3:PutObject action acts on objects/keys and not buckets. I added "/*" everywhere in the Fn::Join for the Resource element.
Updated docs and templates
See commit

Show valid iam role statements examples in docs and templates

---

lib/plugins/aws/lib/monitorStack.js

Closes #2691
Closes #3025
Fixes the bug where the stack was monitored indefinitely.
The new functionality doesn't need the local dev machines time.
It looks through the stack events which are returned by AWS and finds the first event which is a "Stack" event and started the UPDATE, CREATE or REMOVE operation. Then it uses the timestamp of this event, subtracts 5 seconds and uses this value for `monitoredSince`.
The benefits are:
- We don't rely on the correct time of the local dev machine
- The time is derived from AWSs time so it's always correct
- No need to fetch data from an external source (like it was done in the first WIP [here](#3200)
Just run simple `deploy`, `update` and `remove` commands. Optionally with the `--verbose` option.
Furthermore you can take a look at the unit and …

Fix monitorStack freezing bug

---

docs/providers/aws/events/streams.md
lib/plugins/aws/deploy/compile/events/stream/index.js
lib/plugins/aws/deploy/compile/events/stream/index.test.js

Closes #2365 
This looks at the `arn:` specification and if it's a string, uses the existing string-splitting logic. If it's an object, it uses a conditional to get a useful name to use as the streamName:
1. If the object is an `Fn::GetAtt`, it gets the first value in the GetAtt list (the logical ID of the DynamoDB table or Kinesis stream) and uses that
2. If it's using `Fn::ImportValue`, it uses the string key for the variable name.

Allow DynamoDB and Kinesis streams to use GetAtt/ImportValue

---

docs/providers/azure/cli-reference/create.md
docs/providers/azure/guide/quickstart.md
docs/providers/azure/guide/services.md
lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/plugins/create/templates/azure-nodejs/.gitignore
lib/plugins/create/templates/azure-nodejs/README.md
lib/plugins/create/templates/azure-nodejs/handler.js
lib/plugins/create/templates/azure-nodejs/package.json
lib/plugins/create/templates/azure-nodejs/serverless.yml

Closes #3333 (at least for Node.js)
I added a new template to the `create` plugin, which allows scaffolding a simple Node.js-based Azure Function, without needing to rely in `install` ing a Git repo.
This enables running the following command in order to get started quickly: `sls create -t azure-nodejs`
Added a new template called `azure-nodejs` to the existing set of templates for the `create` plugin, and added a reference to this to the list of well-known templates.
I also updated the tests and docs to make use of the new `create` support.
After setting the necessary [environment variables](https://serverless.com/framework/docs/providers/azure/guide/quickstart#2-set-up-credentials) for your Azure account, run the following commands, and verify that you see "Hello World" at the end: …

Adding Azure Functions/Node create template

---

lib/plugins/aws/invokeLocal/index.js

Virtualenv support for python invoke local 
Since the invoke local functionality overrides `process.env.PATH`, only the
system python is found, not the python provided by an active virtualenv. This
checks for the `VIRTUAL_ENV` environment variable and if present, adds it's bin
dir to `PATH`.
1. create a python serverless project
2. create & activate a virtualenv
3. install a dependency and import it in `handlers.py`
4. invoke the handler locally, you shouldn't get an error about the import.

Add virtualenv support to Python invokeLocal

---

lib/plugins/package/lib/zipService.js
npm-shrinkwrap.json
package.json

Closes #3348
The globby module uses for loops instead of recursion.
Swapping a module name!
`npm test` passes, this change is mostly unrelated to serverless itself but rather my plugin `serverless-plugin-include-dependencies` needs it for 2.0 since it produces a large list of files to include.

Use globby instead of glob-all

---

lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js

- few improvements and fix for invoke-local plugin. it's pretty much same description, but  you can see issue from [here](https://github.com/serverless/serverless/issues/3036)
**1. Added support js file that has export as an data input**
**2. You can specify the location of handlers, such as `"/dst"`**
- this might seem controversial, (and i'd love to fix this from outside of this plugin!) but there is no way to specify extra servicePath for severless. for example i'm using Typescript with serverless, which gives me seperated `src` and `dst` folders. (as you can guess, `dst` is js transpiled). in this case, deploying is not a problem since serverless supports `package.artifact`, (which could be just dst.zip, easily) but for invoke-local there is no such thing.   
**3. Support …

add features on AWSInvokeLocal Plugin.

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/method/index.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/method/index.test.js

Closes #3088 
Also fixes the claims for custom properties from the cognito pool. 
In short unlike for regular cognito pool properties for which the mappings need to look like this:
`propertyName = $context.authorizer.claims.propertyName`
for custom properties the mapping for the claim should be: 
`propertyName = $context.authorizer.claims['custom:propertyName']` ( according to [aws specs](http://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html#apigateway-enable-cognito-user-pool). ). 
As for 3088, it was simply a bug of how commas are added between and after the claims when constructing the string for the integration request template.
To cover claims for custom properties, I changed the generated string from `$context.authorizer.claims.${claim}` …

Fix for authorizer claims: multiple claims and custom property claims  (#3088)

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js
tests/utils/index.js

Closes #2619
Fix to allow plugins to be installed in parent directory. i.e for when you have some transpiling/bundling mechanism that doesn't require to package and deploy the whole `node_modules` directory nor maintain a big list of `excludes`/`includes` in the config.
This reset the `module.paths` relatively to the current working directory
`process.cwd()`. So the array of paths used to resolve packages is relative
to where the `serverless` CLI is run.
```node
const Module = require('module')
module.paths = Module._nodeModulePaths(process.cwd())
// /path_to_service/.serverless-plugins path is still added
```
Similar to i.e `babel-cli` https://github.com/babel/babel/blob/396634a51df1941b3a46f81fbee5904ceb72471a/packages/babel-cli/src/_babel-node.js#L84-L88
```shell
$ mkdir testit && cd …
```

Fix node_modules (serverless plugins) lookup

---

lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

This commit removes a hardcoded 5 second sleep intended to help handle
rate limits. The retry interval is changed during the test to 250ms from
5 seconds, with no change to the runtime behavior of the framework.
Closes 
Run `npm test` with and without this patch. It will be 2x faster with this patch. 

Reduce test time by 50%

---

lib/plugins/aws/deploy/compile/events/apiGateway/lib/cors.js
lib/plugins/aws/deploy/compile/events/apiGateway/lib/cors.test.js

The Access-Control-Allow-Methods OPTIONS response header for ANY http
verb requests now correctly includes all HTTP verbs.
Closes https://github.com/serverless/serverless/issues/3303
This PR checks if the methods array includes the `ANY` verb. If so, it replaces the unrecognised `ANY` method in the `Access-Control-Allow-Methods` header with the correct HTTP verbs `'DELETE,GET,HEAD,PATCH,POST,PUT'`.
The appropriate tests have been updated to include the ANY method.
-->

Corrected Access-Control-Allow-Methods for ANY HTTP events

---

lib/classes/Error.js
lib/classes/Error.test.js

Removes the call to action to immediately report the issue since AWS / CloudFormation quirks and not Framework related problems will also show this message.
It might be sufficient to only show the links to the Forums, the GitHub repo etc. to check out for help about AWS issues.
/cc @eahefnawy @brianneisler

Remove slightly misleading error message

---

lib/classes/CLI.js
lib/classes/CLI.test.js

Formatting update deprecation notice
Before:
```
WARNING: You are running v1.9.0. v1.10.0 will include the following breaking changes:
- Some lifecycle events for the deploy plugin will move to a new package plugin. More info -> https://git.io/vy1zC
```
After:
```
------------
WARNING: Updating and Breaking Changes
Current Serverless Version: v1.9.0
Serverless v1.10.0 will include the following breaking changes:
- Certain lifecycle events for the deploy plugin will move to a new package plugin.
For more information see -> https://git.io/vy1zC
To ignore these warnings set the "SLS_IGNORE_WARNING=*" environment variable.
------------
```

update deprication message

---

lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/index.test.js
lib/plugins/aws/deploy/lib/mergeIamTemplates.js
lib/plugins/aws/deploy/lib/mergeIamTemplates.test.js

In CloudFormation, resources are created based on a DAG built from the template file. Previously, the Lambda function IAM policy had references to all log groups like this: `{"Fn::Join": [":", [{"Fn::GetAtt": ["TestFunctionLogGroup", "Arn"]}, "*"]]},` for every log group. This made the IAM policy depend on *all* the log groups completing so they could be referenced in the policy. This patch makes use of the `AWS::Region` and `AWS::AccountID` pseudo-parameters to fill in a full ARN for the group. 
After this change, IAM policy lines look like:
```
{"Fn::Sub": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/myservice-dev-test-function:*"}
```
The upshot here is that there's no reference to the CFN `AWS::Logs::LogGroup` resource, so the dependency graph becomes more …

Reduce dependency tree depth between IAM & Log Groups

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Commands can contain an optional type property. The only allowed value currently is 'entrypoint'. This declares the command as hidden from the CLI. It will not appear in the help screen, nor can it be called from there.
However, entrypoint type commands can be called by plugins via the new PluginManager.spawn(commandsArray) method. In contrast to PluginManager.run() this method allows access to entrypoint commands and can be used to enter a plugin internal sub lifecycle. With this mechanism in place, plugins can expose their own lifecycle events which become then part of the global lifecycle and can be hooked again by dependent plugins.
Closes #XXXXX

Allow entrypoints to be defined and called by plugins.

---

lib/plugins/aws/deploy/lib/mergeIamTemplates.js
lib/plugins/aws/deploy/lib/mergeIamTemplates.test.js

Related to #3360 
This is a fix to the IAM policies for log streams that were broken by the change of where those ARNs come from. 
cc/ @eahefnawy 
Create a new project and using the base config, deploy it.
Run:
```
$ sls invoke -f hello
$ sls logs -f hello
```
In the screenshot are 3 IAM policies. The top is from 1.9.0, middle from current master, and bottom from this patch. 

PR #3360 introduced an incorrect IAM policy for log groups

---

lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js

Supporting local invokes for AWS lambda runtimes for node.js that are not 4.3
Refs #3397 
Currently it checks for an exact match string for 'node43' in order to allow local invokes. I changed it to a prefix match for 'nodejs'.
Change the runtime to node6.10 and try to invoke a function locally.

support any AWS nodejs runtime, not just 4.3

---

RELEASE_CHECKLIST.md
lib/classes/CLI.js
lib/classes/CLI.test.js

Reverts #3217 and #3375
Removes the breaking change logging since it harms DX.
/cc @ac360 @eahefnawy @brianneisler @DavidWells 
Just removed the previously added log message.
Look at the tests or run `serverless help` to see that the logging of breaking changes is not around anymore...

Remove breaking change logging

---

lib/Serverless.js
lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Adds autoloading for `serverless-alpha`.
Would be great if this could be tested with a real, globally installed plugin (on Windows as well). The tests should cover everything, but some "hacking" was required to get the correct path to the global `node_modules`.
1. Install the alpha plugin globally via npm
---
Or
---
1. Run `serverless help` to see that there's no `ServerlessAlpha` plugin yet
2. Run `npm root -g --silent` to get the path to your global `node_modules` directory (in my case this is `/usr/local/lib/node_modules`)
3. Create a new directory with the name `serverless-alpha` in the global `node_modules` directory
4. Create a `index.js` and `package.json` file in the `serverless-alpha` directory (see file content below)
5. Run `serverless help` again and see that the …

Add serverless-alpha autoloading

---

lib/plugins/aws/deploy/compile/functions/index.js
lib/plugins/aws/deploy/compile/functions/index.test.js

Closes #3428
Support `description` on Lambda Version
Add a Property `description` on Lambda Version which Property is based on function's Property `description`.
Use `mocha` for `lib/plugins/aws/deploy/compile/functions/index.test.js`.

add version description from function

---

docs/providers/openwhisk/cli-reference/create.md
docs/providers/openwhisk/cli-reference/info.md
docs/providers/openwhisk/cli-reference/invoke-local.md
docs/providers/openwhisk/examples/README.md
docs/providers/openwhisk/examples/hello-world/README.md
docs/providers/openwhisk/examples/hello-world/python/README.md
docs/providers/openwhisk/examples/hello-world/python/handler.py
docs/providers/openwhisk/examples/hello-world/python/package.json
docs/providers/openwhisk/examples/hello-world/python/serverless.yml
docs/providers/openwhisk/examples/hello-world/swift/README.md
docs/providers/openwhisk/examples/hello-world/swift/handler.swift
docs/providers/openwhisk/examples/hello-world/swift/package.json
docs/providers/openwhisk/examples/hello-world/swift/serverless.yml
docs/providers/openwhisk/guide/functions.md
docs/providers/openwhisk/guide/serverless.yml.md
lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/plugins/create/templates/openwhisk-python/README.md
lib/plugins/create/templates/openwhisk-python/gitignore
lib/plugins/create/templates/openwhisk-python/handler.py
lib/plugins/create/templates/openwhisk-python/package.json
lib/plugins/create/templates/openwhisk-python/serverless.yml
lib/plugins/create/templates/openwhisk-swift/README.md
lib/plugins/create/templates/openwhisk-swift/gitignore
lib/plugins/create/templates/openwhisk-swift/package.json
lib/plugins/create/templates/openwhisk-swift/ping.swift
lib/plugins/create/templates/openwhisk-swift/serverless.yml

New version (0.6) of the OpenWhisk plugin will include support for non-Node.js runtimes. I have added templates to the `create` plugin and also updated the documentation with new features.
Trivial changes to the `create` plugin for the new templates. Docs updated based upon the new features.
```
sls create --template openwhisk-python
sls create --template openwhisk-swift
```

Extend OpenWhisk Runtime Support

---

docs/providers/aws/guide/functions.md

Clarify documentation on AWS environment variables when you define both a function-level variable and a provider-level variable.
Simple change to docs.
Read the docs.

Clarify docs on AWS env var behavior

---

docs/providers/aws/events/cloudwatch-log.md

Fixed a couple of spelling errors in CloudWatch Logs documentation

Fixing typos in CloudWatch log docs

---

docs/providers/azure/guide/quickstart.md

As written prior to this commit, the Azure quickstart guide does not grant the created service principal access to perform a deploy.
I copied the relevant instructions from the Azure credentials guide into the quickstart guide. The credential section of the quickstart guide was previously identical to the credential guide apart from the section I copied in.
Follow the instructions in the quickstart guide and verify that `serverless invoke -f hello` produces the output "Hello World"

Copy necessary permission grant command to azure quickstart guide

---

lib/plugins/aws/lib/updateStack.js
lib/plugins/aws/lib/updateStack.test.js

Fix for https://github.com/serverless/serverless/issues/3061
The original PR didn't cover every place where a Cloudformation stack is created. It missed the `createFallback` method. 
Remove `lambda` from your IAM permissions so that you're unable to deploy a project. You should see the below error even if using the `cfnRole` attribute
```
An error occurred while provisioning your stack: HelloLambdaFunction
- User: <arn>
is not authorized to perform: lambda:GetFunction on
resource: <arn>.
```
The error is gone with this fix.

Fix for cfnRole attribute in createFallback method

---

lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/index.test.js
lib/plugins/deploy/deploy.js
lib/plugins/deploy/deploy.test.js

Support extended lifecycle at framework level. See #3344 
The new lifecycle is now triggered at framework level. This will keep other provider plugins compatible, as the package command is spawned from the uppermost deploy, depending on the existence of the package option.
This is still work in progress. Can someone test my branch with the other providers and use just a plain "serverless deploy" without package switch.
The expected behavior would be that it runs through as it did with before the package/deploy split.
***Is it a breaking change?:*** NO - It's a "restore non-breaking one" ;-)

Control command flow for deploy at framework level.

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Show warning instead of throwing an error when the command has no hooks. Throwing an error unnecessarily breaks the Azure plugin after the recent hook deprecation feature because Azure doesn't have any deprecated hooks.
Log instead of throwing an error
set the `SLS_DEBUG` env var and run the Azure plugin, you'll see the warning but execution continues.

show warning instead of error when there are no hooks

---

docs/providers/aws/events/sns.md
lib/plugins/aws/package/compile/events/sns/index.js
lib/plugins/aws/package/compile/events/sns/index.test.js

Closes #3473 
Allowed the following syntax
```yml
events:
- sns:
arn: arn:xxx
```
Added the condition that allowed the above syntax.
Please write the above in serverless.yml. Then run `sls deploy`

Add new syntax to specify arn for sns event

---

lib/plugins/aws/deploy/lib/extendedValidate.js
lib/plugins/aws/package/lib/saveServiceState.js
lib/plugins/aws/package/lib/saveServiceState.test.js
lib/plugins/package/lib/packageService.js

The `service.package.artifact` property was missing in the saveState function, so it was not available in the deploy phase.
This PR saves and restores the property correctly, and for AWS additionally sets it during packaging. For AWS the initialization of the property also was missing, possibly due to a merge conflict.
Should be merged as soon as possible!

Persist package.artifact correctly

---

README.md

Move the "add a plugin" link above the list of plugins, because it disappears (is difficult to see) when it is below the list.

Move "add a plugin" link above plugin list

---

lib/classes/Service.js
lib/classes/Service.test.js

Closes #3513 
If the parser encounters an object typed service property it sets `service.service` to the service name (retrieved from `service.name`). This is done for compatibility reasons because lots of plugins (core and 3rd party) use `service.service` directly to get the service name.
The object is stored into the service as `service.serviceObject` and all of its properties can be accessed with `service.serviceObject.XXXXX`. 
In case the service property is a string, `service.service` is set to this and `service.serviceObject` is `{ name: XXXX }`.
Additionally I added a `service.getServiceName()` method to provide an option for plugins to become more robust against changes in the serverless object structure and `service.getServiceObject()` that returns the object or objectified …

Allow service to be specified as object in serverless.yml

---

lib/plugins/aws/deploy/lib/extendedValidate.js
lib/plugins/aws/package/lib/saveServiceState.js
lib/plugins/aws/package/lib/saveServiceState.test.js
lib/plugins/aws/utils/findReferences.js
lib/plugins/aws/utils/findReferences.test.js

This is work-in-progress!
Closes #3509
Self references created with `${self:}` are now persisted as `${self:}` and will be restored properly on state restoration.
In `saveServiceState()` a deep search for self references is done now (the FQ property paths are extracted) and all refs are replaced with "${self:}".
Create a service that contains
```
...
custom:
newService: ${self:}
...
```
Run a package and then a deploy.

Persist self references with "${self:}" and restore it correctly

---

docs/providers/azure/guide/quickstart.md

Fixes an incorrect command for verifying service principal
Corrected command in markdown
run command on own azure subscription with valid service principal name
- [ n/a ] Write tests
- [ X ] Write documentation
- [ n/a ] Fix linting errors
- [ n/a ] Make sure code coverage hasn't dropped
- [ n/a ] Provide verification config / commands / resources
- [ n/a ] Enable "Allow edits from maintainers" for this PR
- [ n/a ] Update the messages below

Fix incorrect command for looking up service principal

---

docs/providers/aws/guide/plugins.md
docs/providers/azure/guide/plugins.md
docs/providers/openwhisk/guide/plugins.md
lib/plugins/aws/info/display.js
lib/plugins/aws/info/display.test.js
lib/plugins/aws/info/index.js
lib/plugins/aws/info/index.test.js

Closes #3502 
The info plugin (AWS) now exposes more detailed lifecycle events that can be used by plugins to integrate their output into the info sections, instead of putting everything after the standard info plugin.
Until now it was only possible to hook `after:info:info`.
```
-> info:info
-> aws:info:validate
-> aws:info:gatherData
-> aws:info:displayServiceInfo
-> aws:info:displayApiKeys
-> aws:info:displayEndpoints
-> aws:info:displayFunctions
-> aws:info:displayStackOutputs
```
Plugins now can hook `after:aws:info:gatherData` to implement their own data collection and then output their information next to the section they want by hooking one or more of the `after:aws:info:displayXXXX` hooks.
A plugin that adds some information to the endpoints section (maybe because it adds …

Add detailed lifecycle events to info plugin

---

docs/providers/aws/guide/variables.md
lib/Serverless.js
lib/Serverless.test.js
lib/classes/Variables.js
lib/classes/Variables.test.js
npm-shrinkwrap.json
package.json

Closes #3073
Added support for async sources in the variable system, beginning with the `file` source. Your JS files can now perform async operations and return a promise that would be resolved by the variable system.
Previously, the variable system was completely sync, so I had to control the flow of the entire system and it's methods and make it promise-ready. All methods now return a promise to assure everything is running in the correct flow.
I've also ditched the `traverse` module since it doesn't work smoothly with promises and instead I'm using a lodash based implementation for object traversal and updates.
I've tested 17 different cases for the variable systems that covers pretty much everything the variables system can do, **including the new promises in files support**. Here's …

Added support for Promises in the variable system

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

Closes #3490 
Add tagging for functions.
/cc @brianneisler @eahefnawy 
Added the `tags` function config parameter. Those tags are then translated to function specific CloudFormation resource tags.
Look at the tests or deploy the following service (and look into the `Tags` section in your Lambda console):
```yml
provider:
name: aws
functions:
hello:
tags:
foo: bar
baz: qux
goodbye:
handler: handler.goodbye
```

Add Lambda tagging functionality

---

docs/providers/aws/guide/variables.md
lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #3442
This PR adds support for cross service/stack communication by utilising CloudFormation outputs as a new source for the variable system => `${cf:stackName.outputKey}`
Added a new CloudFormation source to the variable system that allows you reference any output values in any stack you specify. This way a user can define CF outputs in one service, and reference them in another.
You'll need two services to test communication:
```yml
service: service-a
provider:
name: aws
memorySize: 512
functions:
hello:
resources:
Outputs:
memorySize:
Value: ${self:provider.memorySize}
Export:
Name: memorySize
```
```yml
service: service-b
provider:
name: aws
memorySize: ${cf:service-a-dev.memorySize}
functions:
hello:
```
deploy `service-a` then …

Added support for cross service communication via CloudFormation outputs

---

docs/providers/aws/guide/quick-start.md
docs/providers/azure/guide/quick-start.md
docs/providers/openwhisk/guide/quick-start.md

Original docs:
- Azure Functions: https://github.com/serverless/serverless-azure-functions#getting-started
- Google Functions: https://github.com/serverless/serverless-google-cloudfunctions#getting-started
- IBM Openwhisk: https://github.com/serverless/serverless-openwhisk#getting-started
I have reviewed these docs, and have come up with a generic format that fits all these providers, to make the docs simpler to use. 
Please review. @worldsoup @DavidWells

Create separate quick start docs for the providers.

---

docs/providers/README.md
docs/providers/openwhisk/guide/quick-start.md

Since the project was donated to the Apache foundation and is called "Apache OpenWhisk" from now on.

Update OpenWhisk references from IBM to Apache

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #3587
Fixed a bug with the variable system where populating variables referenced from object values of other variables was broken.
If the value of a variable is an object, we're now recursively populating that object. I've also added tests for this edge case.
With the following two files:
serverless.yml
```yml
service: vars-in-files
provider:
name: aws
functions:
hello:
resources:
Outputs:
varA:
Value: ${file(./vars.json)}
Export:
Name: varA
```
vars.json
```json
{
"vars": {
"deep": "${self:provider.name}-something"
}
}
```
run `sls package` and check the `varA` output. You should see the variable populated correctly as `aws-something`

Fixed bug when referencing variables from other variable object values

---

docs/providers/aws/events/apigateway.md
lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses.js
lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js

Several enhancements to AWS API Gateway support:
* Support for `HTTP`, `HTTP_PROXY` and `MOCK` integrations
* Support for `AWS_IAM` authorization type
* Updated test cases to cover new features
* Updated documentation
Closes #3518 
Closes #3238 
Closes #3362 
Extended AWS plugin, specifically ApiGateway's `authorization.js` and `integration.js` to support additional `.yaml` properties.
Serverless supports five distinct integration types now:
* `lambda-proxy` (alternative names are `aws-proxy` and `aws_proxy`)
* `lambda` (alternative name is `aws`)
* `http`
* `http-proxy` (alternative name is `http_proxy`)
* `mock`
As well as a new `authorizationType` property that can be set to `aws_iam` (see below for example).
**For further discussion**: It is noteworthy that providing `http`, …

API Gateway Extensions for HTTP, HTTP_PROXY, MOCK integration and AWS_IAM authorization type

---

docs/providers/aws/events/apigateway.md
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js

Closes #3586
Adds `X-Amz-User-Agent` to the default list of `Access-Control-Allow-Headers` if CORS is enabled.
Simply deploy one or more method with `cors: true` set in the `serverless.yaml`. In the AWS console the headers should be updated accordingly.
```yml
functions:
tests:
events:
- http:
path: test/cors
method: get
cors: true
- http:
path: test/cors
method: post
cors: true
```
Final header mapping in the API Gateway Console:
The new default settings for `cors: true` are:
```yml
functions:
hello:
events:
- http:
path: hello
method: get
cors:
origins:
- '*'
headers:
- Content-Type
- X-Amz-Date
- Authorization
- X-Api-Key
- X-Amz-Security-Token
- X-Amz-User-Agent         # <-- this is new, everything else is unchanged
allowCredentials: …
```

CORS: Add `X-Amz-User-Agent` to list of allowed headers

---

lib/plugins/create/templates/aws-scala-sbt/build.sbt
lib/plugins/create/templates/aws-scala-sbt/serverless.yml
lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/ApiGatewayResponse.scala
lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Handler.scala

The template for aws-java-maven got an example of how to implement the handler
when the Lambda is the backend to an API Gateway Proxy. It is a bit tricky, so having
the example makes like lots better.
Closes #XXXXX

Add ApiGateway templates for aws-scala-sbt, upgrade to Scala 2.12

---

lib/Serverless.js
lib/classes/Service.js
lib/classes/Service.test.js

I fixed the way the `resources` section supports arrays, previously it merged prior to variable resolution, which caused problems if people were trying to use files to split their custom resources out.
Closes #3511
I moved the 'merge' code to a separate function that runs after variable population, and used _.merge instead of Object.assign.
There are several new tests and I manually verified it using a service of ours.
Examples:
I can add severless.yml if needed

fix resources as an array to support variables

---

docs/providers/aws/README.md
docs/providers/aws/cli-reference/deploy-list.md
docs/providers/aws/cli-reference/rollback-function.md
lib/plugins/Plugins.json
lib/plugins/aws/deployList/index.js
lib/plugins/aws/deployList/index.test.js
lib/plugins/aws/rollbackFunction/index.js
lib/plugins/aws/rollbackFunction/index.test.js
lib/plugins/deploy/deploy.js
lib/plugins/rollback/index.js
lib/plugins/rollback/index.test.js
npm-shrinkwrap.json
package.json

Closes #3488
Add support for rolling back a single function.
Standing on the shoulders of giants here --> Shoutouts to @marcy-terui who did the heavy lifting in ( #2672) 🙌 
Add a new `rollback function` command with its corresponding plugin.
1. Deploy a service
2. Run `serverless deploy list functions` to see all the functions and their versions
3. Run `serverless rollback function -f <name-of-the-function> -v <version>` to rollback a function to the requestd version

Add rollback function support

---

lib/classes/Service.test.js
lib/classes/YamlParser.test.js
lib/plugins/deploy/deploy.test.js
lib/plugins/package/lib/packageService.test.js
lib/plugins/package/lib/zipService.test.js
lib/plugins/package/package.test.js
package.json

Relates to #3529 
Added `chai-as-promised` to devDependencies.
Updated some unit test files that expect promised results as reference.
Run the unit tests. Check the coverage.

Use chai as promised

---

docs/providers/aws/cli-reference/invoke-local.md
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js

Closes #3639 
`serverless invoke local` (AWS implementation) now sets the IS_LOCAL environment variable.
Added IS_LOCAL to the environment block of the locally run lambda. As the value itself
is not important I set it to 'true' (String). Implementations can just check for `process.env.IS_LOCAL`
to determine if the code is running in a local environment.
Start a lambda locally with `serverless invoke local` and print the environment.
`console.log(process.env.IS_LOCAL);`

Set IS_LOCAL environment variable with invoke local command

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

Closes #2982
Add config variable for function-based DeadLetterConfig support.
Add the `onError` config variable for functions.
Deploy this service. Make your Lambda error out.
```yml
provider:
name: aws
functions:
hello:
onError: arn:aws:sns:us-east-1:XXXXX:test # SNS
```

DeadLetterConfig support

---

lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js

Closes #3658 
Only set default templates if integration type is "AWS".
Additionally the default passThrough is now WHEN_NO_MATCH if type !== AWS,
NEVER otherwise. NEVER should only be set if there are default templates
See reproduction in bug report.

Do not use default templates for non AWS integrations. Only use NEVER for AWS passthrough.

---

tests/integration/aws/api-gateway/integration-lambda-proxy/cors/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda-proxy/cors/tests.js
tests/integration/aws/api-gateway/integration-lambda/cors/service/serverless.yml
tests/integration/aws/api-gateway/integration-lambda/cors/tests.js

[Travis](https://travis-ci.org/serverless/serverless) seems to fail the integration tests since my last PR for adding `X-Amz-User-Agent` to the default CORS headers (see #3614). This updated pull request should hopefully fix this. **No functional changes to Serverless have been made.**
See the test failures here: https://travis-ci.org/serverless/serverless/jobs/235197362
By running the integration tests in `tests/integration/aws/api-gateway`.

Fixed integration tests failing since latest CORS changes

---

docs/providers/openwhisk/guide/credentials.md

Adding instructions about new API Gateway integration available in OpenWhisk. 
This will be available when I release the 0.7 version of the plugin.
https://github.com/serverless/serverless-openwhisk/milestone/3
Simple doc updates, no code changes.
N/A

[openwhisk] Doc Update: Adding new API Gateway access token instructions

---

lib/plugins/create/templates/azure-nodejs/serverless.yml

Add an out HTTP event that specifies the `res` variable on the context allowing the function specified in `handler.js` to run as expected in Azure.
Closes #3669
Add an out HTTP event to `serverless.yml` for the `nodejs-azure` template that specifies the `res` variable on the context allowing the function specified in `handler.js` to run as expected in Azure.
1.  `serverless create --template azure-nodejs --path my-service`
2.  `cd my-service`
3.  `npm install`
4.  `serverless deploy -v`
5.  `serverless invoke -f hello`
Result:
Serverless: Logging in to Azure
"Please pass a name on the query string or in the request body"
[Screenshot of Evidence](https://photos-3.dropbox.com/t/2/AABAJQuLWAIOld2-athc_Q4xP05DpcdR5FuNAH_9rMX_dQ/12/5786423/png/32x32/1/_/1/2/evidence.PNG/EKbzqQQY5fsIIAIoAg/SBYsF …

Fix for #3669: Azure Quickstart fn returns nothing

---

docs/providers/aws/guide/intro.md
docs/providers/azure/guide/intro.md
docs/providers/google/guide/intro.md
docs/providers/openwhisk/guide/intro.md
lib/classes/Service.js
lib/classes/Service.test.js
lib/classes/Utils.js
lib/classes/Utils.test.js
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/packageService.test.js

Closes #3566 
Service.load() now tries to find one of the supported service filename variants (`serverless.yaml`, `serverless.yml` and **new** `serverless.json`, with this precedence). As soon as one is found, it will be loaded. Additionally the filename is remembered and printed in the error messages. Previously `some error .... in serverless.yml` was printed regardless, if the file was named .yaml or .yml.
JSON service file support is added with no tech debt, as the used YAML parser is spec compliant (a JSON is itself a valid YAML per definition) and will load the JSON out-of-the-box.
Convert any existing service.yml to JSON using some tool. Start your favorite serverless command.
It should behave and load exactly as before.
Additionally you can do some tests with multiple service files …

Added support for serverless.json. Improved error messages with filename

---

lib/plugins/aws/package/lib/generateCoreTemplate.js
lib/plugins/aws/package/lib/generateCoreTemplate.test.js

Closes #3683 
More robust error message if a deployment bucket does not exist.
The error would previously just give 'Access Denied' with no context around why it was happening. I was hunting for a bit to figure it out, so I thought a more specific error message might help.
Added a catch for errors when calling s3.getBucketLocation
Add a non-existent bucket to the `deploymentBucket` property and run `deploy`. The new error message should have more information than just 'Access denied'.

Improve "missing S3 deployment bucket" error

---

docs/providers/aws/cli-reference/remove.md
docs/providers/aws/cli-reference/rollback-function.md
docs/providers/aws/cli-reference/slstats.md

Moved the `rollback function` documentation entry after the `rollback` entry in the side menu. I thought this would make it easier to find, as `rollback function` was added to the end of the menu and people may miss it.

Moving rollback function documentation after rollback in menu

---

lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js
lib/plugins/invoke/invoke.js
lib/plugins/invoke/invoke.test.js

Closes #3652 
Added an outer `loadEnvVars` event to `invoke:local` that is used to set provider independent environment variables on local invocations. Currently only `IS_LOCAL` is set there.
Use a service configured for an arbitrary provider. Use `invoke local` to run any contained function locally and print the environment. It should contain the `IS_LOCAL` variable.

Set IS_LOCAL for every provider. Added unit tests.

---

lib/plugins/aws/package/compile/functions/index.js

Fixed a typo in an error message.
Removed the quote
Check the diff

trivial fix: removed an extra double quote

---

docs/providers/aws/guide/credentials.md
lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

Closes #1787
Adds support for the `--aws-profile` option to provide the profile which should be used e.g. for deployments.
Extended the `AwsProvider` plugin so that it supports the detection of the `aws-profile` option.
Update your `~/.aws/credentials` file and move your current `default` profile under another name. Invalidate the `default` profile by specifying wrong keys (so that a normal `serverless deploy` will fail).
Run `serverless deploy --aws-profile <your-new-profile-name>`
**Note:** Remember to update the `credentials` file later on so that your `default` profile is restored.

Add aws-profile option support

---

README.md

Closes #3726 
Updated README to link to populated labels for potential contributors.

Fix 3726: update Contributing section of README with contrib friendly labels

---

lib/plugins/aws/package/compile/events/s3/index.js
lib/plugins/aws/package/compile/events/s3/index.test.js

Closes #3038
Fixes the race condition bug where S3 events randomly fail while deploying the service.
Added a `DependsOn` declaration which contains the buckets permission. This ensures that the permission is in place before the bucket is created.
Just deploy a service like the following:
```yml
provider:
name: aws
functions:
hello:
events:
- s3: some.random.bucket.name
```
or run the S3 (complex) integration tests. They should stop failing now.

Fix s3 event race condition bug

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

Closes #2996
Add function level `awsKmsKeyArn` config parameter. This way users can define their own KMS key to encrypt environment variables.
Shoutouts to @DonMcNamara who did the first iteration in #2998 which is the foundation for this PR 🙌 
Add the `awsKmsKeyArn` config variable for a whole service and functions.
1. Create a new KMS key (can be found in the `IAM` section of your AWS dashboard).
2. Copy the generated `arn` and replace the placeholder with that value in the service below
3. Deploy the service (or run `serverless package` and inspect the CloudFormation files)
```yml
service:
name: service
awsKmsKeyArn: arn:aws:kms:us-east-1:XXXXX:key/service
provider:
name: aws
functions:
hello:
awsKmsKeyArn: …
```

Add KMS key support

---

docs/providers/aws/events/apigateway.md
lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js

Closes #2476
Adds the new `origin` config parameter which will replace the `origins` array later on.
100% backwards compatible since the string representation will be used if defined and the array representation otherwise.
/cc @eahefnawy @brianneisler @jokeyrhyme
Introduced the new `origin` config parameter and added checks to determine which config to use.
**PLEASE TEST THIS THOROUGHLY**
Here are some examples configs (you can always run `serverless package` and inspect the generated CloudFormation file):
```yml
provider:
name: aws
functions:
hello:
events:
- http:
path: hello
method: GET
cors: true
```
```yml
provider:
name: aws
functions:
hello:
events:
- http:
path: …
```

Fix CORS origin config

---

docs/providers/azure/events/servicebus.md

- I think this should be `serviceBus` type instead of `eventHub`. Please let me know if this change is incorrect.
Closes #3750

Change eventHub to serviceBus as event type

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Closes #3501 
getCommands() which is exclusively used by the help functionality now returns only publicly visible and executable commands. Entrypoint commands and hives under an entrypoint will be omitted in the list.
run `serverless` and check if `package` is shown, but `package function` is hidden.

Filter nested entrypoints on getCommands(). Used by help.

---

docs/providers/aws/cli-reference/deploy-function.md
docs/providers/azure/cli-reference/deploy-function.md
docs/providers/openwhisk/cli-reference/deploy-function.md

Addresses #3542. The issue opener suggested adding a note about the side-effects of the `deploy function` command. 
Added documentation to aws, azure, and openwhisk sections. GCP appears to have not implemented the `deploy function` command.
I use serverless exclusively with aws, so someone may want to validate whether the note is applicable to azure and openwhisk as well.

Adding note to deploy function documentation

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Closes #3780 
To verify run `serverless --help`.

Fix updateAutocompleteCacheFile() bug caused by empty commands object

---

lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

Closes #3698 
I have updated the `zipService` by adding a simple check to verify that at least one file is matched by the _include/exclude_ patterns. If no files are matched, a `ServerlessError` is thrown.
I've added only one simple test.
You can run it individually: 
```
node_modules/mocha/bin/_mocha lib/plugins/package/lib/zipService.test.js
```

Fix #3698: Throw error if an individual package is empty

---

lib/classes/Variables.js
lib/classes/Variables.test.js

A better error information when requesting a Cloudformation variable that does not exist. The previous one was:
> Cannot read property 'OutputValue' of undefined
When the variable isn't found, instead of assuming it always existing, I checked if the value is undefined and throw an error in that case.
Defining a non-existant variable in a `serverless.yml` file, like `${cf:my-stack.IDoReallyNotExist}` and run serverless.
It should throw:
```
jeremy@schiaparelli:~/$ serverless deploy --stage staging --verbose
Trying to request a non variable from Cloudformation.
Stack name: "my-stack" Requested variable: "IDoReallyNotExist"
Bugs: …
```

Throw an Error when requested Cloudformation variable does not exist

---

lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js

Currently if Lambda functions have a timeout then you will not see any errors in Cloudwatch, while the user gets a 200 http response code with `{ errorMessage: 'Task timed out in 10.0 s'}`. 
This change will show 5XX errors in Cloudwatch.
To support this I need to copy all the default patterns in `serverless.yml` per function, so therefore I think this need to be a default setting, while this is not caused by the Serverless(/our) code but by AWS Lambda itself.
Support not only 504 errors caused by Serverless/our code, but also support AWS Lambda default errors like timeouts.
Run it in a regex test tool, like https://regex101.com with 
```
Task timed out after 10.0s
[504] Error message...
```
If you change 504 in 502, you will see that the adapted regex is matching `Task timed out` and the …

Support "Task timed out" warnings as HTTP 504-errors

---

.github/PULL_REQUEST_TEMPLATE.md
docs/providers/aws/cli-reference/create.md
docs/providers/aws/guide/credentials.md

Minor changes to avoid referencing providers directly unless:
- it is part of a provider-specific section of the site
- it is a comprehensive list of providers in the few places where they should be listed
- it is an example to help provide context
Closes #3512 
Minor changes to documentation text only.
Visual review will likely suffice.

Avoid Referencing Providers

---

docs/providers/aws/events/cognito-user-pool.md

The docs link to Cognito User Pool Triggers AWS documentation is only a guide on the incoming events and doesn't contain the actual trigger names. I added a link to the CloudFormation documentation that does contain those triggers. 

Adding Cognito User Pool Trigger documentation link

---

docs/providers/aws/guide/iam.md

Creating an IAM Role with a 'Path' that does not end with a '/' will
lead to:
The specified value for path is invalid. It must begin and end with /
and contain only alphanumeric characters and/or / characters..

Ensure current documentation

---

lib/classes/Utils.js
lib/classes/Utils.test.js

Adds checks for what types of authorizers (IAM, Cognito, or custom Lambda functions) users are using for API Gateway events. Helps us to set priorities for most commonly-used features.
While iterating over each event on a function, it adds additional checks if it's an HTTP event and if it has an `authorizer`. If so, it sets a service-wide flag on the type of authorizer(s) used.
Add an authorizer to an HTTP event in your `serverless.yml`. Make sure it's logged correctly.
One thing I wasn't sure of was whether the `logStat()` method has access to the raw values from `serverless.yml`, or if it's already gone through validation and standardization, e.g. [here](https://github.com/serverless/serverless/blob/6a9e99656d3288fc797cbf9dcf7003b7b23e4413/lib/plugins/aws/package/compile/events/apiGatewa …

Add checks for HTTP Authorizers

---

docs/providers/aws/guide/packaging.md
docs/providers/azure/guide/packaging.md
docs/providers/google/guide/packaging.md
docs/providers/openwhisk/guide/packaging.md
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/packageService.test.js
lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

Closes #2709
Exclude the `dev` node_modules when zipping to decrease the bundle size.
Get a list of the production node_modules. Add the `node_modules/**` glob to the `exclude` and re-include the production `node_modules` via corresponding `<package-name>/**` globs in the `include` glob.
Create a service and do a `npm init`.
Run `npm install --save node-fetch` and `npm install --save-dev jest`.
Run `serverless package` and inspect the zip file. It should only include the dependencies necessary for the `node-fetch` module (and not the ones for `jest`).
**Note:** please use nested directories with dependencies as well. Those should also only include the dev dependencies after packaging.

Exclude Node.js dev dependencies in .zip file

---

lib/Serverless.js
lib/Serverless.test.js
lib/classes/Utils.js
lib/classes/Utils.test.js
lib/utils/sentry.js

Closes #3731
Adds an `invocationId` when spinning up `Serverless`.
Add a call to generate a `uuid` in the `constructor` of the `Serverless` class.
See the test / code.

Add invocationId

---

scripts/postinstall.js

Closes #3792 
Check `tabtab` path using `fileExistsSync` before exec.
- Create directory with `mkdir sls-project && cd sls-project`
- Run `npm init`
- Run `npm install k1LoW/serverless#get-installed-path --save` , and you will see no error like #3792 

Fix #3792: Resolve tabtab/src/cli.js path when installing locally

---

lib/classes/CLI.js
lib/classes/CLI.test.js

Closes #3847 
Added a loop to iterate through all the subcommands of the parent command and check for `type` of the command to be `entrypoint`. Subcommands with type `entrypoint` are deleted because they should be hidden.
`sls package -h` results in:
```
Plugin: Package
package ....................... Packages a Serverless service
--stage / -s ....................... Stage of the service
--region / -r ...................... Region of the service
--package / -p ..................... Output path for the package
```

Remove entrypoint subcmds in generateCommandsHelp

---

lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js

Closes #3845
Trivial
Added test

Improve error message when indentation for http event is wrong

---

lib/classes/CLI.js
lib/classes/CLI.test.js

Closes #3784 
This change adds a new option to `help` command, `--verbose`. `sls help --verbose` extracts the loaded commands and arranges them according to their plugin name and displays all the commands grouped under their plugin names.
Commit messages should be helpful enough to understand the incremental changes.

Display plugin commands alphabetically under help

---

lib/plugins/platform/platform.js

The platform code didn't properly follow the existing error handling patterns. In case of an error the code should reject the promise. This is done properly now while we explicitly make sure to inform the user what when wrong.
I wrapped the existing code into a new promise that resolved once all steps success. The error in catch is not passed to log, but rather to reject. The stack trace can be shown using `SLS_DEBUG=*`
Manipulate your id_token inside `.serverlessrc` e.g. add 12k random characters and deploy a test service. It should fail with the error: `Network error: Network request failed with status 413 - "Request Entity Too Large"`

follow the serverless framework conventions for error handling

---

bin/serverless

Closes #3579
Please test if this does the trick. Not entirely sure how to test this now since everything is Promise based and Bluebird kicks in automatically.

Add infinite stack trace limit for Errors

---

scripts/postinstall.js

Refs #3798 and #3792
Make the path to the `tabtab` CLI script OS independent.
Replace `/` with `path.sep` and `path.join()`.
Install Serverless from this branch or run `node scripts/postinstall.js`.

Fix tabtab paths in postinstall script

---

docs/providers/aws/guide/packaging.md
docs/providers/azure/guide/packaging.md
docs/providers/google/guide/packaging.md
docs/providers/openwhisk/guide/packaging.md
lib/classes/Service.js
lib/classes/Service.test.js
lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

Refs #3827
Refs #3874
Refs #3869
Add the `excludeDevDependencies` config variable to the `global` package level.
This config variable defaults to `true`.
Added the config variable and added a check in the `excludeDevDependencies()` function.
Use the following `package.json` file:
```json
{
"name": "test-service",
"version": "1.0.0",
"main": "handler.js",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "",
"license": "ISC",
"dependencies": {
"node-fetch": "^1.7.1"
},
"devDependencies": {
"ava": "^0.19.1",
"babel-cli": "^6.24.1",
"babel-core": "^6.25.0",
"babel-preset-es2015": "^6.24.1",
"browserify": "^14.4.0",
"express": "^4.15.3",
"jest": "^20.0.4",
"mocha": "^3.4.2",
"react": "^15.6.1",
"react-native": "^0.45.1",
"webpack": "^3.0.0"
},
"description": ""
} …
```

Add opt-out config for dev dependency exclusion

---

lib/plugins/package/lib/zipService.js

Adds dev dependency exclusion support for Windows 😬 .
Thanks for bringing this up @HyperBrain 👍 
Just updated the regex to use OS dependent path separators.
Same steps you can finde in https://github.com/serverless/serverless/pull/3737

Fix node_modules regex in excludeDevDependencies to be OS independent

---

docs/providers/aws/guide/deploying.md
lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/index.test.js
lib/plugins/aws/deploy/lib/checkForChanges.js
lib/plugins/aws/deploy/lib/checkForChanges.test.js
lib/plugins/aws/deploy/lib/uploadArtifacts.js
lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/index.test.js
lib/plugins/aws/lib/normalizeFiles.js
lib/plugins/aws/lib/normalizeFiles.test.js
lib/plugins/deploy/deploy.js
lib/plugins/package/lib/zipService.js

Closes #2710
Checks if the function code or service configuration has changed and only deploys if that's the case.
Add a `sha256` based hash comparison for the files in question (e.g. the `.zip` or `CloudFormation` files). Only deploy when the hashes are different.
This PR introduces a new AWS related lifecycle event (`checkForChanges`) and sets a globally available flag (`this.serverless.service.provider.shouldNotDeploy`) so that others can use the result of the check as well. Thanks for pointing that out @HyperBrain 👍 
Use the following service:
```yml
service:
name: my-service
provider:
name: aws
functions:
hello:
goodbye:
handler: handler.goodbye
```
1. Run `serverless deploy` to deploy everything.
2. Run `serverless deploy function -f hello` …

Only re-deploy when code or service updated

---

lib/plugins/create/templates/aws-fsharp/build.sh

Added a check in the `build.sh` file for the F# template for OS. The end result avoids the `apt-get not found` error. 
Stored the result of `uname -a | grep Darwin` in a variable, then checked if the variable was null before running `apt-get` commands.
Run `lib/plugins/create/templates/aws-fsharp/build.sh` and see results. 
On macOS, there should be no `apt-get not found` error.
On Linux, `apt-get` commands should run.

Cleaning up F# build template output on macOS

---

docs/providers/aws/guide/variables.md
docs/providers/azure/guide/variables.md
docs/providers/google/guide/variables.md
docs/providers/openwhisk/guide/variables.md
lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #3841
Add a conditional for the existence of `:` in the module path and check the `typeof` of the exported value.
See tests that were written also something like `custom: ${file(../myCustomFile.js)}` in serverless.yml can be used for verification.

Improve usage and error handling of javascript variables.

---

lib/plugins/aws/deploy/lib/extendedValidate.js
lib/plugins/aws/deploy/lib/extendedValidate.test.js
lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/index.test.js
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/packageService.test.js

Closes #3625 
Closes #3580 
Added function artifact check in `deployFunction()` and skip packing when an artifact is provided.
And add function artifact check in `packageService()` to use the provided artifact path and not derive some default artifact path.
* Create an aws-nodejs template project and deploy.
* Create a dummy zip file, say `foo.zip`, and add that as artifact of a function.
```
functions:
hello:
package:
artifact: foo.zip
```
* Run `sls deploy function -f hello` to deploy the function.
* Open AWS lambda console and export the function. The downloaded file is the same dummy zip file.

Add function artifact check in deployFunction

---

lib/plugins/aws/deploy/lib/extendedValidate.js
lib/plugins/aws/deploy/lib/extendedValidate.test.js
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/packageService.test.js

Added checks to *not* build a package at all if package.artifact is specified. I believe this is how it worked before it didn't.
Closes #3684 maybe
Everything was already being tracked correctly, I pretty much just changed the package service to skip the "build all" step if an artifact is given in the config.
If you check out one of the integration tests that has a package artifact in the config, you can see that it currently zips up the entire app root, even though it may not use it as the deployed artifact. With these changes, that zip is no longer built.

Skip packaging if artifact specified

---

lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

Reverts #3903 cause it's preventing users to deploy new services because it catches the "stack does not exist" error, which we've been ignoring and updating instead.

Revert #3903

---

lib/classes/Utils.test.js

Closes #3920
Added `pakage.path` element to `serverless.service` object, since errors that can not find the `path` element occurs.
Then, to standardize test code, updated to use chai-as-promised instead of chai.(This is not tha main purpose of this though)
Please run `npm run test`

fixed unhandled rejection errors in Utils test

---

lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/packageService.test.js

When packaging a service, if you've implemented [custom plugins](https://serverlesscode.com/post/customizing-serverless-with-plugins/) within the project, they're uploaded along with your functions. Given that plugins by definition run on the deploying machine, they shouldn't be included. 
Added `.serverless_plugins/**` to the default excludes.
- Create a project with a custom plugin in `.serverless_plugins`
- Run `sls package`
- Run `unzip -l .serverless/[service_name].zip` and see that the plugin is included
- Run again with this patch, and see that it's excluded.

Ignore custom plugins in the project when uploading artifacts

---

docs/providers/aws/guide/variables.md
lib/classes/Service.test.js
lib/classes/Variables.test.js

Updated the documentation and tests to use a valid custom variable syntax. The existing example did not work when doing, for example:
```yaml
custom:
foo: ${{file(config/${{opt:stage, self:provider.stage}}.js):vars}}
```
Used the default variable syntax string and modified it to match the existing custom syntax example of `${{…}}`.
Compare the custom example in the documentation against the default variable syntax.

Update example custom variable syntax to work with loading files

---

lib/plugins/aws/invokeLocal/index.js

Avoids setting `AWS_REGION` and `AWS_DEFAULT_REGION` to `undefined` when the it should come from the config.
just grab it from the config  and use it instead if `options.region` is falsey.
run a lamba with `sls invoke local` that returns `process.env.AWS_REGION`.

Also set region env vars from config, not just CLI, for invoke local

---

lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/lib/monitorStack.test.js

When calling `remove` on a stack, if there was an Export being used by another stack, no '_FAILED' status would occur but an 'UPDATE_ROLLBACK_IN_PROGRESS' would immediately fire. Serverless was silently throwing with a 'Cannot read property 'LogicalResourceId' of null' message because the reason the rollback started wasn't capture as an error. This resolves this situation and fails with the correct error message.
Catches the 'UPDATE_ROLLBACK_IN_PROGRESS' state if there is no previous error. Basically, if an '_FAILED' comes first, the rollback event is ignored. If a rollback event happens when there's no previous failed event, it treats the rollback event as a failure.
Create two stacks, one that depends on an export from the other. Try and remove the depended upon stack.
***Is this ready …

Handle Export errors when deleting CF stack

---

lib/plugins/platform/platform.js
lib/plugins/platform/platform.test.js
lib/utils/selectors/selectServicePublish.js
lib/utils/selectors/selectServicePublish.test.js

This PR adds support for a publish flag so that you can disable publishing to the platform during deploy on a service by service basis.
Added support for the flag at the `service` level
```yaml
service:
name: my-service
publish: false  #defaults to true
```
- login to platform
- deploy a service
- service should successfully publish to platform
- set `service.publish` to `false`
- deploy again
- service should skip publishing to platform

Add support for a publish flag

---

lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

Closes #3827
Closes #3874
Closes #3869
Fixes a bug where the dev dependency exclusion errors out due to a large number of dependencies (and string capacity limitations).
Also fixes the error where exclusion is not working anymore.
Speed is increased due to async operations ran concurrently.
1. Switch from sync to async calls and compute them in a `Bluebird Promise.map`
2. Switched from `execSync` to `spawn` to get a stream (mitigates the buffer limit `execSync` introduces where the packages for exclusion are capped)
3. Switch from `npm ls --prod=true` to `npm ls --dev=true` so that we exclude only the `dev` dependencies rather than excluding all `node_modules` and then re-including the prod dependencies. This should avoid side-effects when the exclusion of dev dependencies fails.
Take the …

Fix dev dependency exclusion bug

---

docs/providers/aws/guide/plugins.md
lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Functionality that allows user to specify default values for plugin options.
Closes #2242
Options without a value will be assigned a default value, if it's specified.
Specifying default in any of the options, ensures that it will be that option's value, unless we set it manually via cli.

Allow to provide a default value for plugin options

---

lib/plugins/aws/deployList/index.js
lib/plugins/aws/deployList/index.test.js

Fix retrieval when too many functions are deployed.

Fix function retrieval for "deploy list functions" command

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #3965 
Revised how the function exported from the .js variable file is executed by ensuring the fully required file is passed as the first argument of fn.call to maintain "this"
An example project, [indieisaconcept/serverless-issue-3965](https://github.com/indieisaconcept/serverless-issue-3965) illustrates this issue and steps to reproduce.

preserve context when executing exported function from .js file

---

lib/classes/Service.js
lib/classes/Service.test.js

Closes #3611
Removes the provider name validation to make it possible to support other 3rd party provider plugins.
Removed the check if for the `provider` name.
Run the tests / create a new service.

Remove provider name validation

---

docs/providers/aws/guide/services.md

I hit this section in the documentation and immediately wanted to know more,
so after a little digging, I found the issue. It'd be easier for others if
the issue were linked directly until it's fixed.
Added a link to the issue referenced in the documentation.
Added a Markdown Link to the issue.
Look at the Markdown, or generate the HTML and open it in a browser.

Adding Shared Gateway Issue Link

---

lib/classes/PluginManager.js

Closes #4010 
A little PR to improve the deprecated hook message (show to the user which hook should be used instead of the deprecated one)
I changed the `WARNING` message
Old: 
New:

Improve deprecated hook message

---

lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/plugins/create/templates/kubeless-nodejs/gitignore
lib/plugins/create/templates/kubeless-nodejs/handler.js
lib/plugins/create/templates/kubeless-nodejs/package.json
lib/plugins/create/templates/kubeless-nodejs/serverless.yml
lib/plugins/create/templates/kubeless-python/gitignore
lib/plugins/create/templates/kubeless-python/handler.py
lib/plugins/create/templates/kubeless-python/package.json
lib/plugins/create/templates/kubeless-python/serverless.yml

Closes #3969
template creation for kubeless provider
add templates in `lib/plugins/create/templates/kubeless-python`
and `lib/plugins/create/templates/kubeless-nodejs`
modified:
`lib/plugins/create/create.js`
`lib/plugins/create/create.test.js`
Plus the removal of the provider validation in:
https://github.com/serverless/serverless/pull/3941
Install the PR and try:
```
serverless create --template kubeless-nodejs --path sebgoa
Serverless: Generating boilerplate...
Serverless: Generating boilerplate in "/Users/sebgoa/Desktop/foobar/sebgoa"
_______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless …
```

Kubeless template for python and nodejs

---

docs/providers/aws/guide/functions.md

Adding a bit more background information and links on dead letter queues,
since some users of the Serverless framework won't be versed on every
detail of AWS lambda functions.
Additional documentation surrounding dead letter queues.
An additional paragraph of introductory text, and a little 'refactoring' of what was already there.
Read the revised text.

More Background on Dead Letter Queues

---

docs/providers/aws/guide/serverless.yml.md

Fixes #4079.
Fix example `serverless.yml` for creating Outputs in CloudFormation.

Fix Output example in serverless.yml docs

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Closes #4090 
If `SLS_DEBUG` is set, the original exception is rethrown for crashes in plugins. This allows plugin authors to debug their plugins properly within the context of the Serverless framework.
The check is added in the loadPlugins() where any exceptions that occur during plugin loading and initialization are catched.
Add a plugin to any project that either cannot load the plugin files (syntax error) or that throws during initialization (constructor).

Rethrow original plugin error in debug mode. Added unit tests.

---

lib/plugins/emit/index.js
lib/plugins/emit/index.test.js
lib/plugins/platform/platform.js
lib/plugins/run/index.js
lib/utils/getAuthToken.js

This PR gates the `sls run` and `sls emit` commands behind `sls login`.
Throw an error if no auth token is detected when running either command.
- Ensure you are logged out of platform.
- run `sls emit -n abc123 -d"{}"`
- framework should throw an error asking user to run `sls login`
- run `sls run` (needs to be run inside of a service project folder)
- framework should throw an error asking user to run `sls login`
- login to platform with `sls login`
- run `sls emit -n abc123 -d"{}"`
- command should run successfully (will probably indicate that event could not be emitted since gateway is not running)
- run `sls run` (needs to be run inside of a service project folder)
- command should run successfully 

Add platform gate to sls run/emit

---

docs/providers/aws/guide/services.md
docs/providers/azure/guide/services.md
docs/providers/google/guide/services.md
docs/providers/openwhisk/guide/services.md

Be sure to 'cd' into the relevant service directory before running the 'deploy' command, otherwise you'll likely see the following error message: "Avoid the following error: "This command can only be run inside a service directory".
Closes #XXXXX

Add note to change directory into service prior to deployment

---

lib/plugins/aws/info/display.js
lib/plugins/aws/info/display.test.js
lib/plugins/aws/info/getStackInfo.js
lib/plugins/aws/info/getStackInfo.test.js

Closes #4078
simply adds the stack name to the info output.
stack name is assumed to be `${service}-${stage}`
Run `sls info`

Display stack name in info output

---

lib/plugins/aws/remove/lib/stack.js

Removes the hardcoding of the stack name generation in remove stack class.
Used the getStackname from the naming lib.
Remove a deployed service. and it works.

Use naming.getStackName method instead of hardcoding.

---

lib/classes/Variables.js

Fix a typo in `Variables.js` file.
Nothing to verify.

Fix this.s3RefSyntax variable name typo

---

lib/plugins/run/index.js

Bump the version of the event-gateway to 0.5.15
run `sls run` in a test service. Make sure that http paths with leading slashes and without both work. 
```
/my-path
my-path
```

bump event-gateway version to 0.5.15

---

docs/providers/aws/cli-reference/invoke-local.md
docs/providers/aws/cli-reference/invoke.md
lib/plugins/aws/invoke/index.js
lib/plugins/aws/invoke/index.test.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js
lib/plugins/invoke/invoke.js

Please review and course-correct on parameter naming and defaults. See #3788. Thank you! 
Closes #3788 
Offer a `--raw` flag in CLI and skip JSON parsing if it is set.
Unittest should take enough care of it, but to test end-to-end, create a simple lambda function, call it as following and verify that `event` type is a string: 
```
sls invoke -f my_function -d '{"foo":"bar"}' --raw
```

Optionally skip parsing input to JSON when using `invoke` and `invoke local`

---

lib/plugins/create/templates/kubeless-nodejs/package.json
lib/plugins/create/templates/kubeless-nodejs/serverless.yml
lib/plugins/create/templates/kubeless-python/package.json

Not a feature, a quick fix for a wrong runtime version in the kubeless nodejs template
trivial change from `nodejs6.10` to `nodejs6`
Also updated the default plugin version in the meantime.
```
sls create --template kubeless-python --path foobar
cd foobar
sls deploy
```

kubeless quick fix for wrong runtime version in nodejs template

---

docs/providers/aws/guide/variables.md
docs/providers/azure/guide/variables.md
docs/providers/google/guide/variables.md
docs/providers/openwhisk/guide/variables.md

Closes #3379
Add clarifications on the need for file suffix/extension when using variables from reference files of type YAML or JSON.  Also mentioned it is possible to reference array variables and provided an example of that for both JSON and YAML.  This was under the heading "Reference Variables in Other Files" on the variables.md page for AWS
Edited serverless/docs/providers/aws/guide/variable.md in a text editor.  Used http://dillinger.io/ to check formatting.
Follow the examples provided in the updated section or proof read.  I'm unsure of another way.
None that I'm aware of.
***Is this ready for review?:Yes
***Is it a breaking change?:NO

Add clarifications on the need for file suffix/extension when using variables from reference files

---

docs/providers/aws/cli-reference/config-credentials.md
lib/plugins/aws/configCredentials/awsConfigCredentials.js
lib/plugins/aws/configCredentials/awsConfigCredentials.test.js

Added support for profile update when using the `serverless config credentials` command
Closes #3809 
This was implemented by scanning the credentials file and locating the given profile section and then replacing the key and secret lines. I tried to adapt the logic of the [aws-cli config writer](https://github.com/aws/aws-cli/blob/e2295b022db35eea9fec7e6c5540d06dbd6e588b/awscli/customizations/configure/writer.py)
The **AwsConfigCredentials** was refactored to apply more the *DRY* and *OO* patterns.
Use this command:
```bash
serverless config credentials --provider aws --key 1234 --secret 5678 --profile custom-profile --overwrite
```
Try the following:
- use the overwrite flag to update an existing profile.
- do not use the overwrite flag to update an existing profile => This should Fail. …

Allow aws credentials update

---

docs/providers/aws/guide/variables.md
lib/classes/Service.js
lib/classes/Service.test.js
lib/classes/Utils.js
lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #4072
- Changed the variable syntax to allow plain strings to be accepted as valid. 
- Changed the variable extractor to pull the quotes from strings and inject as a literal value.
In a serverless.yml file, add a variable in the form:
```
${opt:blah, 'vtha'}
```
When no opt is passed, the literal value 'vtha' should be used. 
- [x ] Write tests

Allow use of string as default values in variables

---

lib/plugins/aws/invokeLocal/fixture/handler.py
lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js
lib/plugins/aws/invokeLocal/invoke.py

The behavior of `context.getRemainingTimeInMillis` is incorrect when invoking a function locally. It is supposed to return the amount of milliseconds remaining until the timeout of the function is reached, but in actuality it's just returning the number of milliseconds since the function was invoked.
I discovered this when my workers were behaving really strangely when invoked locally. They would just pick a single item from the queue and then stop, because the time remaining would always be <1000, which I had set as the limit for when to stop working.
I have now fixed that behavior so that it counts down from the timeout instead of up from the start time.
Simply return the timeout in milliseconds minus the elapsed time since starting.
Run the tests. I couldn't find a good way to fake the …

Fix behavior of getRemainingTimeInMillis in local invokation

---

lib/plugins/aws/configCredentials/awsConfigCredentials.js
lib/plugins/aws/configCredentials/awsConfigCredentials.test.js

Closes #2970
Immediately after the `.aws/credentials` file is created, use the Node.js file system module to set the file permissions to be owner readable/writable. This changes the file permissions from `644` to `600` This is recommended in an AWS Security Blog [post](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/).
1. Remove existing `credentials` file: 
```shell
rm ~/.aws/credentials
```
2. Use CLI to create new `credentials` file: 
```shell
serverless config credentials --provider aws --key 1234 --secret 5678
```
3. Show new file permissions:
```shell
ls -l ~/.aws/credentials | awk '{print $1}'  
```
4. Output should be the symbolic value `-rw-------`, which corresponds to the octal value of `0600`.
***Is this ready for …

Set read/write owner permissions when .aws/credentials file is created

---

lib/plugins/aws/deployList/index.js
lib/plugins/aws/deployList/index.test.js

Closes https://github.com/serverless/serverless/issues/3917,
Replaces https://github.com/serverless/serverless/pull/3957 
I've removed `MaxItems` parameter from `deployList.listVersionsByFunction` and changed sorting in `displayFunctions` function.
serverless.yml
```
service: domain-manager
frameworkVersion: "<=1.17.0"
provider:
name: aws
stage: dev
- Effect: "Allow"
Action:
- "route53:*"
Resource: "*"
functions:
list-zos:
handler: zones.listt
get-zone:
handler: zones.get
create-zone:
handler: zones.create
delete-zone:
handler: zones.delete
list-records:
handler: records.list
create-record:
handler: records.upsert
update-record:
handler: records.upsert
delete-record:
handler: records.delete
```
And deploy 6 times:
```
for i in …
```

Reverse version sorting for "sls deploy list functions"

---

docs/providers/aws/cli-reference/invoke-local.md
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js
lib/plugins/aws/invokeLocal/invoke.py
lib/plugins/invoke/invoke.js

Closes #4031
Adds `--context` and `--contextPath` flags to `invoke local` command.
Because validation mechanism is the same for `path` and for `contextPath`, I've extracted a `validateFile` function to avoid redundancy. When it comes to python, custom context is sent using stdin.
```
service: invokelocal
provider:
name: aws
stage: dev
functions:
func:
handler: handler.index
```
`handler.js`
```js
'use strict';
module.exports.index = (event, context, callback) => {
console.log(context);
const response = {
statusCode: 200,
body: JSON.stringify({
context,
}),
};
callback(null, response);
};
```
`serverless invoke local -f func -c '{"data":1}'`

Add --context and --contextPath to `invoke local` cmd

---

package.json

It'll be great to have a _test_ command, that runs tests directly without _coverage_ overhead.
Main problem with _coverage_ wrap is that it manipulates source code, so eventually exposed error stacks do not relate to code as in codebase, which makes errors harder to investigate
Here I propose least invasive way, as I just configured aside `test-bare` script.
However in my eyes following two approaches could be better:
1. Make `test` a plain test command, but introduce `coverage` script, which will do what `test` does now. CI configuration will have to be updated
2. To not repeat mocha arguments setup in two scripts (certainly a mainance issue). Introduce a js program (e.g. in `bin/test`) that invokes mocha programmaticaly with exactly this setup, and then configure scripts as follows:
- …

Script command to run bare tests (without coverage overhead)

---

lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

Closes #3979
Split handling of serverless.provider.profile (from serverless.yml) and cli option aws-profile into two different cases in awsProvider.js since they have different prioritites.
Set the AWS_PROFILE env in the aws-profile option test to verify that the profile set overrides the env.
AWS_PROFILE=foobar serverless deploy --aws-profile myprofile
This now deploys to myprofile, previously it tried to deploy to foobar.

Fix aws-profile cli option to override env & config

---

lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/lib/monitorStack.test.js

Failed deletion is not discovered as expected by stack monitor, therefore it polls infinitely.
It looks as a regression introduced by: https://github.com/serverless/serverless/pull/2367/files#diff-3863240f31427c97202058562e09ec44R79 (the problem was already being fixed in a past -> https://github.com/serverless/serverless/issues/1367 )
I ensured `DELETE_FAILED` is picked as final status

Fix end of failed deletion discovery in AWS stack monitor

---

lib/Serverless.js
lib/Serverless.test.js

Goals:
An easier way to pass custom CLI arguments without messing with `process.argv` for version 1. 
Similar issues with a short description:
#1678 / #2444 Issue is open (discussion stage). Serverless response was that it is on roadmap for v2. No resolution for v1 users with multiple discussions with best way to hack around the issue.
#3895 Issue is open (status: help wanted). Suggestion was to add a configuration entry and pass it through. Serverless response was that it was on roadmap.
#2426 Closed. Serverless response was that discussions are ongoing for version 2 but nothing for version 1.
#3707 It could close this feature request?
The error handling logic in Serverless references `new this.classes.Error()` so I applied the same logic to the `init()` method so that a custom CLI class …

Allow custom CLI class instances

---

lib/plugins/create/templates/aws-python/handler.py
lib/plugins/create/templates/aws-python3/handler.py
lib/plugins/create/templates/kubeless-python/handler.py
lib/plugins/create/templates/spotinst-python/handler.py

When using Serverless with python templates, templates created were not pep8 compliant.
> Surround top-level function and class definitions with two blank lines.
[source](https://www.python.org/dev/peps/pep-0008/#blank-lines)
Checked code using pep8 CLI and added new lines where it was necessary.
Install [pep8 cli](https://pypi.python.org/pypi/pep8), position your shell in project's root in current master branch and run:
`pep8 lib/plugins/create/`
In master you will get several errors, in my branch 0.

making python templates pep8 compliant

---

docs/getting-started.md

Closes #4183
just added the menu item for kubeless
check that the menu item is there now :)

added Kubeless to "getting started" sidebar menu

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

Closes #4094
Allows the use of an object in function onError, if that object is either a Ref or Fn::ImportValue.
Create a function with a Ref instead of arn string in onerror:
```
fn:
handler: handler.main
onError: 
Ref: DeadLetterQueue  
```
The generated CFN script should allow this value. 
The current system will amend the default IAM role to provide access when using an SNS arn.
I have made no assumption here, if using a ref you will currently need to manage the permissions manually.

Allow use of Ref and Fn::ImportValue in OnError

---

bin/test
lib/Serverless.test.js
lib/classes/Service.test.js
lib/classes/Utils.test.js
lib/plugins/aws/invokeLocal/index.test.js
lib/utils/fs/writeFile.test.js
lib/utils/fs/writeFileSync.test.js
package.json

There are errors in tests which are not properly exposed, additionally due to that, some configured tests are not invoked at all.
Issue lies in not handled rejected promises, their errors are exposed only via _UnhandledRejection_ warnings which can be seen through the tests output, but which do not force tests to fail as expected.
I didn't fix code corresponding to broken tests, I thought it's better (more efficient) if it's looked after by its authors. __Due to that CI crashes, it's expected__
In tests I ensured that those rejected promises are returned to mocha functions, therefore exposed as expected.
Still, more future proof solution would be to add following code to some init test script:
```javascript
process.on('unhandledRejection', err => {
throw err;
});
```
This will ensure that …

Fix tests setup - ensure errors are exposed

---

docs/providers/aws/guide/variables.md
lib/classes/Variables.js
lib/classes/Variables.test.js
package-lock.json
package.json

Adds ability to specify SSM parameters as serverless variable references.
This is mostly intended to support discussion in #4053, so everyone can see what the code looks like.
* Created a new regex to match `ssm:` variable references
* Created a new function that calls the SSM API to retrieve the parameter value
I cribbed a lot of the implementation from the already existing code for `s3:` variable references.
In order to support decryption of SecureString parameters, I selected the `~` as a delimiter between the parameter name and a true/false value that maps to the `WithDecryption` option of the SSM GetParameter API. I selected the `~` only because it is already allowed in the default variable regex, and because it is not allowed as a character in the SSM parameter name.
The AWS SDK …

Supports SSM Parameters as serverless variable references

---

lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

Closes https://github.com/serverless/serverless/issues/4182
This line: https://github.com/serverless/serverless/pull/3924/files#diff-0e8817ce3b2d950d2b8d0e47f9fccb2eR107 changed encoding from `null` (default for `fs.readFileSync` according to the [docs](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options)) to `utf8`. 
```bash
npm install deasync --save
```
```js
require('deasync'); // or any other module that consists of executable binaries or has "weird" characters
```
Deploy & invoke, there should be no errors.
OR
```
git checkout f0b1474f1e49d69c39e27e3c8def929569e20bed # Before PR changing encoding
serverless package
git pull https://github.com/RafalWilinski/serverless master
serverless package
```

Fix getFileContent encoding

---

docs/providers/aws/cli-reference/deploy.md
docs/providers/azure/cli-reference/deploy.md
docs/providers/kubeless/cli-reference/deploy.md
docs/providers/openwhisk/cli-reference/deploy.md
lib/classes/PluginManager.js
lib/classes/PluginManager.test.js
lib/plugins/aws/info/index.test.js
lib/plugins/deploy/deploy.js
lib/plugins/deploy/deploy.test.js

Closes #3204 
* `pluginManager.spawn()` now supports an option `terminateLifecycleAfterExecution`.
When set, the *current* lifecycle will be terminated after the spawned lifecycle returns. PluginManager will automatically continue with the *outer* lifecycle, in case we were spawned too. This allows implementation of commands that spawn other commands, depending on the given Serverless options. A terminating spawn should be used in the very first lifecycle event of the *current* lifecycle, to make sure that hooks into it are not yet executed. Using it in `before:<-- delegating command -->` is sufficient to give this guarantee.
* `deploy:deploy` now checks for a function parameter
If found, it executes a terminating spawn of `deploy:function` in `before:deploy:deploy` which effectively …

Deploy --function deploys function

---

package-lock.json
package.json

Upgrades ci-info package to 1.1.1 which adds support for AWS CodeBuild.

Upgrade ci-info package

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Closes #4172 
* **Command alias support**
Commands now support an alias array that let's them define an alias through which the command can be invoked alternatively. The pluginManager will build an command alias map, that contains all defined aliases with their specific targets.
Aliases are simply defined by adding an `aliases` array to any command, that specifies the command path that will invoke the command as alias, e.g. `install:plugin` would expose the command containing the alias as `serverless install plugin`.
Aliases appear with `serverless help` with the same description as their original commands.
* **Error detection**
The pluginManager will now detect if aliases are specified somewhere and checks for the following restrictions:
* Aliases cannot overwrite commands and vice …

Added possibility to alias commands.

---

docs/providers/aws/guide/serverless.yml.md

Add missing `name` field under the sample function in [the Serverless.yml reference section of the guide](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/).
Copied the sample from <https://serverless.com/framework/docs/providers/aws/guide/functions/>

Add optional `name` under individual function

---

docs/providers/aws/events/cloudwatch-event.md
lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js
lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test.js

Closes https://github.com/serverless/serverless/issues/3498
```yml
service: aws-kotlin-jvm-maven 
provider:
name: aws
runtime: java8
package:
artifact: target/hello-dev.jar
functions:
hello:
handler: com.serverless.Handler
events:
- cloudwatchEvent:
description: 'desc2'
event:
source:
- "aws.ec2"
detail-type:
- "EC2 Instance State-change Notification"
resources:
- arn:aws:ec2:us-east-1:123456789012:instance/i-12345678
detail:
state:
- pending
```

Add Description to CloudWatch events

---

docker-compose.yml
docs/providers/aws/cli-reference/create.md
docs/providers/aws/guide/services.md
lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/plugins/create/templates/aws-kotlin-jvm-maven/gitignore
lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml
lib/plugins/create/templates/aws-kotlin-jvm-maven/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-maven/src/main/kotlin/com/serverless/ApiGatewayResponse.kt
lib/plugins/create/templates/aws-kotlin-jvm-maven/src/main/kotlin/com/serverless/Handler.kt
lib/plugins/create/templates/aws-kotlin-jvm-maven/src/main/kotlin/com/serverless/Response.kt
tests/templates/test_all_templates

Closes https://github.com/serverless/serverless/issues/3883
Adds Kotlin template. It uses JVM and Maven under the hood. Support for gradle based is coming soon.
I'm also willing to investigate Kotlin -> JS compilation so it might run using `node6.10` runtime.
`serverless create -t aws-kotlin-jvm-maven`
`serverless deploy`
It's also compatible with https://github.com/serverless/serverless/pull/4199 so you can use `invoke local` too.

Add aws-kotlin-jvm-maven template

---

lib/classes/Variables.js
lib/classes/Variables.test.js

When using the new string syntax for a variable, a double-quoted string would be rendered with the double-quotes escaped around the value.
serverless.yml:
```
service: hello
provider:
name: aws
environment:
STRING_DOUBLEQUOTE: ${env:STRING_DOUBLEQUOTE, "foo"}
STRING_SINGLEQUOTE: ${env:STRING_SINGLEQUOTE, 'foo'}
functions:
hello:
```
Rendered cfn template **without** the patch:
```
"Environment": {
"Variables": {
"STRING_DOUBLEQUOTE": "\"foo\"",
"STRING_SINGLEQUOTE": "foo"
}
}
```
Rendered cfn template **with** the patch:
```
"Environment": {
"Variables": {
"STRING_DOUBLEQUOTE": "foo",
"STRING_SINGLEQUOTE": "foo"
}
}
```

Removes escaping of double-quotes around string value

---

lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

Closes https://github.com/serverless/serverless/issues/4242
```bash
serverless info --aws-profile this-does-not-exists-for-sure
```
OR
```yml
provider:
profile: this-does-not-exists-for-sure
```
AND
```
serverless info
```

Serverless should fail if provided profile is not valid

---

lib/classes/CLI.js

Closes https://github.com/serverless/serverless/issues/3608#issuecomment-329175859
Adds notice about `--no-color` flag.
https://github.com/chalk/supports-color#info
```
serverless --no-color
```

Add --no-color flag notice

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #4248 
Modified the SSM variable reference so the hyphen is escaped, so that SSM parameters with a hyphen in the name will match the pattern.
Create the parameter:
```
aws ssm put-parameter --name /foo/foo-bar/param --value bar --type String
```
Package this serverless.yml:
```
service: hello
provider:
name: aws
environment:
FOOBAR: ${ssm:/foo/foo-bar/param}
functions:
hello:
```
Ensure package command does not generate a warning. Check the rendered template:
```
grep FOO .serverless/cloudformation-template-update-stack.json
```

Escapes the hyphen in the ssm variable syntax

---

lib/plugins/create/templates/aws-nodejs-ecma-script/serverless.yml
lib/plugins/create/templates/aws-nodejs-typescript/handler.ts
lib/plugins/create/templates/aws-nodejs-typescript/serverless.yml

Remove `LAMBDA` integration from TypeScript template.
`LAMBDA-PROXY` integration is the preferred integration and is actually stated on line 14 of the same file.

Remove LAMBDA integration for TypeScript/EcmaScript sample

---

lib/plugins/aws/deploy/lib/uploadArtifacts.js
lib/plugins/aws/deploy/lib/uploadArtifacts.test.js

This is a direct follow-up to https://github.com/serverless/serverless/pull/4035 - please see conversation there.
Addresses #3871
Per @HyperBrain's suggestion on #3871, this limits concurrency when uploading function artifacts.
Artifacts uploads are limited to 3 parallel threads and use AWS SDK's S3 `upload` method instead of `putObject` now. `upload` is designed for (large) file uploads with automatic retry, multi-part upload, etc.
On one level, you could monitor uploads while deploying a service to verify the concurrency. A better way would be to time the uploads for large service with many large functions and see how this affects things.
**Is this ready for review?**: YES
**Is it a breaking change?**: NO

Limit upload concurrency (follow-up for #4035)

---

lib/utils/log/serverlessLog.js
lib/utils/yamlAstParser.js
lib/utils/yamlAstParser.test.js

Fixes #4258.
If the yaml is being parsed and an invalid value is found:
eg.
```yaml
service:
name: my-service
spotinst:
functions:
...
```
Previously, the process would fail completely. This change is to warn the user and continue on, ignoring the invalid value.
Log a warning to the console and continue.
Create a `serverless.yml` with an invalid value and try to install a plugin in the directory:
`serverless plugin install --name serverless-webpack`

Ignore & warn on invalid yaml values

---

lib/plugins/create/templates/aws-nodejs-typescript/package.json
lib/plugins/create/templates/aws-nodejs-typescript/serverless.yml
lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js

Closes #4280 
Adding typescript extensions to webpack resolve
Create a typescript project using `aws-nodejs-typescript` template from this PR, add a new typescript (`.ts`) module file and try to import it using something like `import typescript_module from './typescript_file'`.
Before this PR one needs to add the file extension for this to work, eg: `import typescript_module from './typescript_file.ts'`.
I am also upgrading dependencies.

Adding typescript files extension to webpack resolves

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Closes #4272
`instanceof` vs `constructor.name`
Test passes and new test added to cover defect scenario.

fix #4272 use instanceof to detect duplicate plugins and log a warning

---

lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/index.test.js

Closes https://github.com/serverless/serverless/issues/4261
- Fixed inheriting provider config in `vpc` section
- Fix concurrent & conflicting `updateFunctionConfiguration` & `updateFunctionCode`. Now they are serial.
```yml
custom:
env:
common:
aws:
vpc:
securityGroupIds:
- sg-xxxxxxxx
subnetIds:
- subnet-xxxxxxxx
provider:
name: aws
vpc: ${self:custom.env.common.aws.vpc}
functions:
hello:
```
```bash
serverless deploy function -f hello
serverless deploy function -f hello
serverless deploy function -f hello
```

Fix deploy function not inheriting provider config

---

docs/providers/aws/guide/functions.md

One character documentation typo. No such thing as an SNS queue AFAIK: SQS queue.

SQS queue, not SNS queue

---

docs/providers/kubeless/README.md
docs/providers/kubeless/cli-reference/remove.md
docs/providers/kubeless/events/http.md
docs/providers/kubeless/events/scheduler.md
docs/providers/kubeless/guide/deploying.md
docs/providers/kubeless/guide/installation.md
docs/providers/kubeless/guide/intro.md

I updated the Kubeless docs for the version 0.2.0 of the `serverless-kubeless` plugin. It includes a new event type: `schedule`.

Add docs for scheduled events for Kubeless

---

lib/classes/PluginManager.js

Distinguish _not found_ errors from _initialization_ errors (so far in both cases _not found_ error was thrown)
At this point serverless throws _plugin not found_ error, also if plugin exists and its initialization crashes. This patch, fixes that. Not found errors are reported as not found, and initialization crashes are reported more meaningfully
I relied on error `MODULE_NOT_FOUND` code (recommended way to distinguish such errors)
Create setup with non existing and crashing plugin

Distinguish plugin initialization error from plugin not found error

---

lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

Partially closes https://github.com/serverless/serverless/issues/4289 (part regarding packaging artifacts)
- Instead of `forEach file { read -> append to zip }` -> `forEach file { read } onceDone sort(files) forEach readFile { append }`. This allows to sort files after all files being read and package them in the same order every time, instead of random.
- Parallelized `fs.readFileAsync` & `fs.statAsync` calls
Create service with at least 5 files with different sizes. Then:
```bash
serverless deploy function -f hello
serverless deploy function -f hello # This deployment should be skipped
```

Change packaging order in zipFiles function

---

bin/serverless
package.json

Enable bluebird long stack traces only in SLS_DEBUG mode 

---

scripts/postinstall.js

Make sure postinstall.js works with paths with spaces.
Closes #4351 
```
mkdir "path with spaces"
cd "path with spaces"
npm install serverless # Should not work
rm -Rf node_modules
npm install https://github.com/Wouter92/serverless/archive/master.tar.gz # Should work
```

Updated postinstall.js to make it also work with spaces in path

---

docs/providers/aws/guide/functions.md

Closes #4362
Provides additional configuration information and help when running AWS Lambdas inside VPC. Provides information that deals with access to internet via NAT Gateway for resources outside the VPC.
This is just a documentation update. 

provide additional information for running lambda inside VPC as part docs

---

lib/plugins/aws/invokeLocal/invoke.py

Setting `sys.stdin` to a TTY prevents `pdb.set_trace()` from immediatly throwing
`BdbQuit`. I am unsure if there is a way to make this work in Windows
PDB support in Python Invoke Local, which didn't work because it requires a TTY.
Set `sys.stdin` to a TTY in `invoke.py` after the JSON event is read from it.
1. create a new python project: `sls create -t aws-python3`
2. add `import pdb;pdb.set_trace()` in the sample handler, ie:
```python
body = {
"message": "Go Serverless v1.0! Your function executed successfully!",
"input": event
}
response = {
"statusCode": 200,
"body": json.dumps(body)
}
import pdb;pdb.set_trace()
return response
```
3. run `sls invoke local -f hello` You should get a PDB prompt rather than a `BdbExit` error. (type `c` and Enter to continue …

Set stdin to a TTY in invoke.py to allow PDB use

---

docs/providers/aws/cli-reference/create.md
docs/providers/azure/cli-reference/create.md
docs/providers/google/cli-reference/create.md
docs/providers/kubeless/cli-reference/create.md
docs/providers/openwhisk/cli-reference/create.md
docs/providers/spotinst/cli-reference/create.md
docs/providers/webtasks/cli-reference/create.md
lib/classes/Utils.js
lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/plugins/install/install.js
lib/plugins/install/install.test.js
lib/utils/downloadTemplateFromRepo.js
lib/utils/downloadTemplateFromRepo.test.js
lib/utils/fs/copyDirContentsSync.js
lib/utils/fs/dirExistsSync.js
lib/utils/renameService.js
lib/utils/renameService.test.js
package-lock.json

Closes #4099
* Abstract the download template from external repo function
* Add support for BitBucket also
* Utilize it at `create` command and add the option to pull template from repo
`install` command would accept a repository URL and download it. I have moved this function into its own utility in order to be shared by the `create` command too.
`sls create --template-url https://github.com/serverless/examples/tree/master/aws-node-rest-api-mongodb`

Create service using template from an external repository

---

docs/providers/webtasks/guide/intro.md

Fix a hyperlink that results in an HTTP 404 in both github markdown navigation and serverless.com docs

Fix relative hyperlink to quick-start page

---

lib/plugins/aws/deploy/lib/extendedValidate.js
lib/plugins/aws/deploy/lib/extendedValidate.test.js

Closes https://github.com/serverless/serverless/issues/4371
```yml
service: aws-nodejs-timeout-test
provider:
name: aws
functions:
hello:
timeout: 31
events:
- http:
path: /
method: GET
- s3:
bucket: idk
```
and then `serverless deploy`.
Expected output:
```
Serverless: WARNING: Function hello has timeout of 31 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
```

Add function attached to API Gateway effective timeout warning

---

.gitignore
lib/plugins/aws/deploy/lib/extendedValidate.test.js
lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

Closes #4359 
The `bin` properly `package.json` files of dev deps are read to check the name of the executable(s). If they exist, they are added to the glob exclude patterns.
Existing tests were updated w/ appropriate `readFileAsync` call counts & resolve values. 2 new tests were added handling executable exclusion.
NOTE: `readFileAsync` is being used to read `package.json` files & loading them into memory to access the `.bin` property which is not ideal, but this seems to be the safest way to know the name of the executables. For ex. a lib may be named `lumo-cljs`, but the executable specified in `package.json` could be named `lumo` w/o reading the file, there would be no way to know that. Also, there could be multiple executables include in the …

Exclude dev dependency .bin executables

---

lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/index.test.js

Closes https://github.com/serverless/serverless/issues/4318
Previous change introduced regression which broke uploading functions with `deploy function` command if `role` wasn't ARN-based string. 
```yml
service: iam-function-fix
provider:
name: aws
resources:
Resources:
RoleOne:
Type: AWS::IAM::Role
Properties:
Path: /somepath/a/
RoleName: RoleOneTest
AssumeRolePolicyDocument:
Version: '2012-10-17'
Statement:
Principal:
Service:
- lambda.amazonaws.com
Action: sts:AssumeRole
Policies:
- PolicyName: myPolicyNameOne
PolicyDocument:
Version: '2012-10-17'
Statement:
Action:
- '*'
Resource:
- '*'
RoleTwo:
Type: AWS::IAM::Role
Properties:
Path: /my/default/path/
RoleName: RoleTwo
AssumeRolePolicyDocument:
Version: '2012-10-17'
Statement:
- …
```

Fix `deploy function` command by normalizing role 

---

lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

I've noticed that on the course of [internal improvements](https://github.com/serverless/serverless/pull/4299) `getFileContent` method was removed.
I think it's a good point of entry for eventual module decorations (e.g. transpiling) in plugins.
e.g. I rely on it in [serverless-plugin-transpiler](https://github.com/medikoo/serverless-plugin-transpiler/blob/67f36b4d19aa97628f0e917914f5e51ed5169339/index.js#L22).
Can we have it back?

Bring back getFileContent (zipService)

---

docs/providers/azure/events/timer.md

Very tiny documentation fix. 
Based on [this](https://github.com/serverless/serverless-azure-functions/blob/629ade76534b82df0977f9e629906ded29a94fce/shared/bindings.json#L32) the default value needs to be `myTimer`

Default value for Timer Trigger Fixed

---

lib/plugins/aws/deploy/lib/createStack.test.js

Currently, unit tests are flaky, sometimes fails like this: https://travis-ci.org/serverless/serverless/jobs/287331366
One of the main reason is that stubs in createStack test are not restored properly, so I have reveraged the sandbox feature of `sinon`, then those are done inside `afterEach` even if failing the test in the process.
sandbox creation and restore process has certainly done inside `beforeEach` and `afterEach`, and then it makes the createStack test stable.
Run test on Travis.
However, we can not see the error everytime. Therefore we might want to merge once and observe if the error will not occur again.

Fixed the flaky unit tests

---

docs/providers/aws/guide/variables.md
docs/providers/azure/guide/variables.md
docs/providers/google/guide/variables.md
docs/providers/openwhisk/guide/variables.md
lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #4388
`serverless.yml` allows to include variables from external `json` files using the following syntax:
```yml
custom: ${file(./config.json)}
```
But if the file is a symlink, Serverless Framework considers it as a non-existing file.
* Create a `config/sls-variables.json` file
* Create a symlink to this file at your project root (`ln -s ./config/sls-variables.json .`)
* Reference the symlink inside your `serverless.yml`
* Run a `sls` command (ex: `sls deploy`) 

Allow symlinks as custom variable files in serverless.yml

---

docs/providers/aws/guide/resources.md

The template told me to keep the parts of the template that weren't applicable, but I want to make sure that it's clear that I'm only changing documentation in this PR.
Closes #XXXXX
Small documentation update
From the Github UI
Review the changes.

Fix typo/language in resources documentation

---

lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/index.test.js

Closes #4329 
All parts of the function configuration that contain CF references or other constructs are now omitted from the function configuration update. This should be safe as these are controlled by CF anyway.
If any reference is encountered in the environment block, this is skipped as a whole, because otherwise it would leave an incomplete set of environment variables.
Use a project that has references either in the VPC config or in the environment variables.
A following `deploy function` should now succeed.
For projects that do not use references at all nothing has changed.

Do not update function configuration parts that contain references.

---

lib/plugins/logs/logs.js
lib/plugins/logs/logs.test.js

Fixes #4434 
The 2nd argument of Logs constructor contains just a command line
arguments like `{"-f", "hello"}`.
As of the above, logs command always fail on the last of logs command.
PR #4344 aims to inject userStats, so I've solved this problem by
injecting userStats by substitution not the constructor argument.
`sls logs -f <function>`

Fixes #4434

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Closes #4435
Found the bug/fatal error in the code and fixed it with a simple test to catch the failing exception
Test a serverless stack with default values with a non-existing file in the first value.  This would fail in 1.24.0 but was not caught in any tests (see Notes).  Eg: 
```
custom:
varname: ${file(non-existant-file.yml):config, ''}
```
* In Variables.test.js for 1.24.0 the test `should get undefined if non existing file and the second argument is true` should have been catching this failure, but I believe that test is not robust enough or was not written properly and did not catch this.  Please someone (with more NodeJS experience) review and improve this test.
* Sorry maintainers, I did not have time to write tests to ensure this does not happen again, hopefully someone else …

Error when file referenced in serverless.yml does not exist

---

docs/providers/openwhisk/guide/functions.md
docs/providers/openwhisk/guide/serverless.yml.md
docs/providers/openwhisk/guide/services.md

`memorySize` was a wrong param name, updated to `memory`
Deploy function with a proper param `memory` for a provider and check it's value at a runtime vars:

Updates README for openwhisk

---

lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

There is a bug in the lambda version creation. Currently only the ZIP file hash is used to
create the logical id for the lambda version resource.
If you just change the function configuration (e.g. memory size, VPC or an environment
variable), the version resource created in the CF template will have the same logical id as before.
This leads to a bug, because if you now deploy, the function is deployed as $LATEST, but **no
new version is created**, because CF will not create one as the logical id of the version resource
is the same as before.
Only if you do source changes, a new version will be created.
This behavior is wrong. Also any change in the function configuration creates a differently
behaving deployment and thus must lead to a new function version created.
The bug gets visible …

Fix lambda version generation when only function config changes

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Partially Closes #3821
This is specifically to deal with SSM Rate Exceeded errors.
It is a complement to https://github.com/serverless/serverless/pull/4294
We are having issues with Serverless calling SSM over 50 times because around 10 variables are referenced in a number of places. This issue is currently stopping us from deploying.
I added a cache object to Variables class. This is referenced before AWS SSM is requested.
I cannot share our config as our ssm variables are secrets. But this change is a pretty simple. The tests verify that the cache is working.

Add cache to Variables class.

---

lib/plugins/aws/invokeLocal/invoke.py

Closes #4147
This affects both Python 2.7 and Python 3.6 when you try to use `logging`.
Just force `logging` module to provide a basic config, check [logging.basicConfig](https://docs.python.org/2.7/library/logging.html#logging.basicConfig). Worthy to mention:
> This function does nothing if the root logger already has handlers configured for it.
YAML:
```yaml
service: hello
provider:
name: aws
functions:
hello:
```
handler.py
```python
from __future__ import print_function
import logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
print('hello')
logger.info('world')
return '!'
```
Invoking `sls invoke local -f hello`, before:
```
No handlers could be found for logger "handler"
hello
"!"
```
after: …

Basic logging for python invoke local

---

lib/classes/Variables.test.js

Add tests to ongoingly verify the cases addressed by issues #3627, #3740, #3711, and #3882 
For augmenting #4144 

Add significant variable usage corner cases

---

docs/providers/aws/cli-reference/logs.md

I initially thought this command would return *all* the logs within the date range. I can see why it doesn't do that, but I think mentioning the limit in the docs makes sense.
The number comes from [the AWS docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchLogs.html#filterLogEvents-property)  about the function that's used for this command.
I'm not including the pull request template -- I hope that's alright. This is just a tweak to documentation.

Mention log limit in the documentation

---

lib/plugins/create/templates/aws-nodejs-typescript/package.json

Closes #4546
Modified `package.json` to reference `@types/node`.
Use the template and call `npm install`:
```bash
$ serverless create --template aws-nodejs-typescript && npm install
```
- [ x] Make sure code coverage hasn't dropped
- [ x] Provide verification config / commands / resources
- [ x] Enable "Allow edits from maintainers" for this PR
- [ x] Update the messages below

Adds @types/node per #4546

---

docs/providers/aws/events/apigateway.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js

Closes #4440.
Adds ability to specify [regional endpoints](https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-api-gateway-supports-regional-api-endpoints/) for API Gateway. :
```yml
provider:
name: aws
endpointType: regional
...
```
Adds the [EndpointConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html) attribute when we compile the RestApi resource. By default, it sets to `EDGE`, which is the default API GW setting. 
I used this example:
```yml
service: endpoint-test
provider:
name: aws
endpointType: regional
functions:
helloWorld:
handler: handler.helloWorld
events:
- http:
path: hello-world
method: get
cors: true
```
Then run `sls package` and check the …

Add API Gateway endpoint configuration

---

lib/plugins/create/templates/aws-nodejs-typescript/handler.ts
lib/plugins/create/templates/aws-nodejs-typescript/package.json
lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json

Closes #4546
I added the required configuration to include `@types/aws-lambda` as a dev dependency and updated `handler.ts` to make use of the Handler, Callback, and Context types.
Use the template and call `npm install`:
```bash
serverless create --template aws-nodejs-typescript && npm install
```

Installs @types/aws-lambda and uses types in handler, per issue #4546

---

lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

The plugin commands failed if listed plugins within serverless.yml do not exist in node_modules. 
All plugin commands shouldn't catch the error related to the state of another plugin. Then I fixed it.
Closes #4259 
when running the `plugin` commands, errors are ignored even if listed plugins within serverless.yml do not exist.
- Run `serverless create -t spotinst-nodejs`. At this time, you will see listed the spotinst plugin but that is not actually installed
- Run `serverless plugin` commands

Fix the plugin commands fail if listed plugins does not exist

---

docs/providers/aws/guide/functions.md

Fix lose/loose error.
Resolved a lose/loose error in the AWS Functions / VPC documentation text.

Grammar fix in AWS VPC documentation

---

docs/providers/aws/guide/packaging.md

The example here contradicted the preceding paragraph, which explains that you should either use include/exclude, or artifact, but not both.  However the example then shows the use of include, exclude and artifact all together.
To resolve, I removed the include and exclude options from the example.
Improvement to the example given for package Artifacts in the AWS Packaging guide document.
Closes #XXXXX

Fix Artifact example in AWS Packaging guide doc

---

docs/providers/aws/guide/intro.md
docs/providers/azure/guide/intro.md
docs/providers/google/guide/intro.md
docs/providers/kubeless/guide/intro.md
docs/providers/openwhisk/guide/intro.md
docs/providers/spotinst/guide/intro.md
docs/providers/webtasks/guide/intro.md
lib/classes/Service.js
lib/classes/Service.test.js
lib/classes/Utils.js
lib/classes/Utils.test.js
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/packageService.test.js
lib/plugins/plugin/install/install.js
lib/plugins/plugin/install/install.test.js
lib/plugins/plugin/lib/utils.js
lib/plugins/plugin/lib/utils.test.js
lib/plugins/plugin/uninstall/uninstall.js
lib/plugins/plugin/uninstall/uninstall.test.js
lib/utils/getServerlessConfigFile.js
lib/utils/getServerlessConfigFile.test.js

Closes #3269
Uses require to load js configuration file (expects config exported).
Added exception for plugin install command to log warning instead of modifying existing config file.
Changes are fully covered and tested with on my existing lambdas.

Add support of serverless.js configuration file

---

lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/createStack.test.js

I've fixed a bug that was disabling s3 transfer acceleration for already-deployed services using custom deployment buckets.
Closes #4605 
I have improved the condition that checks on the CloudFormation Stack's Outputs to verify whether S3 transfer acceleration has been already enabled or not. Such condition did not make sense if a custom bucket has been used.
1. Create a custom deployment bucket named `my-custom-sls-deployment-bucket`
2. Deploy the stack below (without using `--aws-s3-accelerate`)
3. Update the handler
4. Re-deploy (using `--aws-s3-accelerate`).
```yaml
service: s3-custom-bucket-accel-test
package:
exclude:
- "**/*"
include:
- handler.js
- huge-file.jpg  # not strictly necessary
provider:
name: aws
region: us-west-2
deploymentBucket:
name: …
```

Fixed S3 Transfer Acceleration bug with custom deployment buckets

---

lib/classes/Variables.js

There's a typo in the `Variables` class, which I have fixed.
Corrected the spelling of 'syntax' in both places this variables was used.
* Visual inspection.
* Grep the codebase for other uses of this variable - I did not find any.
* Run the tests to ensure nothing breaks.
- ~Write tests~
- ~Write documentation~
- ~Fix linting errors~
- ~Provide verification config / commands / resources~

Fix typo in 'syntax'

---

docs/providers/aws/cli-reference/create.md
docs/providers/azure/cli-reference/create.md
docs/providers/google/cli-reference/create.md
docs/providers/kubeless/cli-reference/create.md
docs/providers/openwhisk/cli-reference/create.md
docs/providers/spotinst/cli-reference/create.md
docs/providers/webtasks/cli-reference/create.md
lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/utils/fs/copyDirContentsSync.js
lib/utils/fs/walkDirSync.js
lib/utils/fs/walkDirSync.test.js

Closes #4566
Added a `--template-path` option for `serverless create`
The use case is to copy a template from a local directory (for instance a monorepo). This has 2 advantages:
- avoid to create a special repo for the template if you don't need it, or prefer it to be in your monorepo
- bypass the fact that we can't download a template from a private repo
When `--template-url` is passed, do not download but copy a local folder to the local destination
You can try to copy a template that you have locally in serverless repo:
```
cd path/to/serverless
serverless create --template-path lib/plugins/create/templates/aws-nodejs --path destination/path
serverless create --template-path lib/plugins/create/templates/aws-nodejs --path destination/path --name my-awesome-service
```
***Is this ready …

Added a `--template-path` option to `serverless create`

---

docs/providers/aws/cli-reference/deploy.md
lib/plugins/aws/package/lib/generateCoreTemplate.js
lib/plugins/aws/package/lib/generateCoreTemplate.test.js
lib/plugins/aws/provider/awsProvider.js

Closes #4625
I've made `s3:PutAccelerateConfiguration` IAM permissions optional (and documented it), and added a new `--no-aws-s3-accelerate` argument, as suggested.
No `AccelerateConfiguration` will be added to the CloudFormation template unless `--aws-s3-accelerate` or `--no-aws-s3-accelerate` are provided.
Deploy the service documented in #4293 with a limited IAM Role (i.e. without `s3:PutAccelerateConfiguration` permissions).

S3 Transfer Acceleration IAM breaking change fix

---

lib/plugins/aws/invokeLocal/index.js

Disables Python's buffering so that long running jobs with occasional output from sls display sooner than later.
Added `-u` to the python invokation.
```
sls install -u https://github.com/dschep/sls-unbuffer-example
cd sls-unbuffer-example
npm i -g dschep/serverless#py-invoke-local-unbuffered
sls invoke locla -f hello
```

Don't have Python buffer it's output in invoke local

---

docs/providers/aws/events/apigateway.md

Fix duplicated and broken markdown links to api gw

fix: duplicated and broken markdown links to api gw

---

lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js
lib/plugins/aws/invokeLocal/java/src/main/java/com/serverless/InvokeBridge.java

(this is a rebase of #4530 since it wasn't seen by Travis for some reason)
InvokeLocal/Java:
* Add support for [handlers with POJO input type](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html)
* Support different handler names (`package.class::method-reference`)
* Fixes #4526
The Java bridge for InvokeLocal will resolve the handler method using [the same rules as AWS](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-handler-types.html):
* Use the method name specified on the handler (`package.class::method-reference`), or `handleRequest` by default.
* Select the method with the largest number of parameters.
* If two or more methods have the same number of parameters, AWS Lambda selects the method that has the Context as the last parameter. …

InvokeLocal/Java: support POJO input and different handler names

---

lib/utils/autocomplete.js

Closes #3777 
Includes two separate instances of incorrect completion values:
- Duplication of commands (e.g., `create` showing up twice)
- Offering commands as sub-commands (e.g., `create` offered as an option for `serverless install` to produce `serverless install create`)
- Two `tabtab` instances were being created previously, one to deal with the `sls` alias, which was causing the issue. The solution here is to get the command name from `process.argv` and use a single `tabtab` instance.
- Because of the way `tabtab` is implemented, the completions for the root command (`serverless`) are applied to all completions by default. This implementation limits that manually.
Depending on what you have in your `.bashrc` or `.zshrc`, you may need to manually source the completion file after …

Completion fixes

---

README.md

I want to add a new service to the list of existing services.
The mention service  creates a lambda function which forward Cloudwatch alerts to slack.

Adding service : cloudwatch alerts on slack

---

lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js

Closes #4648
This is an update of @kminkler 's PR #3413 which was closed after being sat in review too long. It also includes a test.
* Added step in validate.js to see if authorizer.name had been set before automatically extracting an implicit name from the arn.
* I have added at test: `it('should handle an authorizer.arn with an explicit authorizer.name object')`.

allow authorizer.name to override implied authorizer.arn name.

---

docs/providers/aws/guide/functions.md
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

Closes #4555 
I added new `reservedConcurrency` option to functionObject in `AwsCompileFunctions` class.
If it is number and is not empty, I assign it to `ReservedConcurrentExecutions` option into CloudFormation template. Otherwise, ReservedConcurrentExecutions will not be present in CloudFormation template.
More information about ReservedConcurrentExecutions can be found at: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-reservedconcurrentexecutions
**serverless.yml**
```
functions:
hello:
handler: handler.hello # required, handler set in AWS Lambda
name: ${self:provider.stage}-lambdaName # optional, Deployed Lambda name
description: Description of what the lambda function does 
reservedConcurrency: 5
```
***Is this …

Add support for concurrency option in AWS Lambda

---

docs/providers/aws/events/alexa-skill.md
docs/providers/aws/examples/hello-world/fsharp/serverless.yml
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/deploy/lib/createStack.test.js
lib/plugins/aws/deploy/lib/extendedValidate.test.js
lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
lib/plugins/aws/lib/naming.js
lib/plugins/aws/lib/naming.test.js
lib/plugins/aws/package/compile/events/alexaSkill/index.js
lib/plugins/aws/package/compile/events/alexaSkill/index.test.js
lib/plugins/create/templates/aws-csharp/serverless.yml
lib/plugins/create/templates/aws-fsharp/serverless.yml
lib/plugins/create/templates/aws-go-dep/serverless.yml
lib/plugins/create/templates/aws-go/serverless.yml
lib/plugins/create/templates/aws-groovy-gradle/serverless.yml
lib/plugins/create/templates/aws-java-gradle/serverless.yml
lib/plugins/create/templates/aws-java-maven/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-gradle/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-maven/serverless.yml
lib/plugins/create/templates/aws-kotlin-nodejs-gradle/serverless.yml
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml
lib/plugins/create/templates/aws-python3/serverless.yml
lib/plugins/create/templates/aws-scala-sbt/serverless.yml

Closes #4700 - using the same concept as `alexaSmartHome` event which forces you to specify skill ID.
This implementation is *backwards compatible* and alerts the users to migrate to the new syntax.
Also, added the option to provide multiple `alexaSkill` events per a function, allowing it to be invoked by multiple skills.
Added the options to provide either a string or an object to the event, while the values impact the Permission Policy which is sent to AWS.
By default, the alexaSkill is enabled.
Example configs (also available in the updated documents):
```yml
functions:
mySkill:
handler: mySkill.handler
events:
- alexaSkill: amzn1.ask.skill.xx-xx-xx-xx-xx
```
```yaml
functions:
mySkill:
handler: mySkill.handler
events:
- alexaSkill:
appId: amzn1.ask.skill.xx-xx-xx-xx
- alexaSkill: …
```

Restricting alexaSkill functions to specific Alexa skills

---

lib/classes/Error.js
lib/plugins/aws/invoke/index.js
lib/plugins/aws/invoke/index.test.js
lib/plugins/aws/utils/formatLambdaLogEvent.js
lib/plugins/aws/utils/formatLambdaLogEvent.test.js

Closes #4673 
Do not color any messages in white as it is unreadable on white background
Remove any explicit calls to `chalk.white` so that no white text is output, and instead the default terminal color (e.g. black) is used.
This is consistent with the existing handling of black background as there are no explicit calls to `chalk.black` anywhere.
* Configure a terminal to have a black-on-white color scheme
* Use `sls invoke` to display a function output
* Or, try causing an error to display a "Serverless Error" message
* All the text in the error messages and the invocation output should be readable as well as it is on a white-on-black terminal.

Do not explicitly color messages in white

---

lib/plugins/aws/package/compile/events/alexaSkill/index.js
lib/plugins/aws/package/compile/events/alexaSkill/index.test.js

#4701 changes were throwing an error if an event other than `alexaSkill` was present in the events list. This fixes the issue.
Making sure the event is `alexaSkill` (whether as a string or an object)
A simple serverless.yml with an http handler for a function.

Stop throwing errors if alexaSkill is not in the events list

---

lib/plugins/aws/provider/awsProvider.js

Closes #4674
In order to maintain the end-of-sentence period, I wrapped the offending URL in angle brackets, as suggested by [RFC 3986][].
[RFC 3986]: https://tools.ietf.org/html/rfc3986?#appendix-C
It's a convention for plain text communication, and due to its inclusion in RFC 3986, it may be _the_ convention. I can confirm that it fixes the problem for VS Code. Additionally, it's safer in URL terms, as some do end with a period. (I can demonstrate it here because GitHub strips trailing periods from raw URLs.)
- Redirects: https://en.wikipedia.org/wiki/Inc. (`Redirects: https://en.wikipedia.org/wiki/Inc.`)
- Does not: <https://en.wikipedia.org/wiki/Inc.> (`Does not: <https://en.wikipedia.org/wiki/Inc.>`)
It wouldn't be the worst idea to wrap all of them in angle brackets, but only this …

Wraps Poorly Parsing URL in Angle Brackets

---

lib/classes/PromiseTracker.js
lib/classes/PromiseTracker.test.js
lib/classes/Variables.js
lib/classes/Variables.test.js
lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

Closes #4311, #4734, and #4687 
For #4311:
1. Add pre-population of the service and region values on the provider due to their requirement in the use of request.  Reject any dependencies on AWS for resolution of these values.
2. In support, added a `deep` variable type for internal use only.  This allows variable resolution to be paused and resumed.  More specifically it allows population to return to the level of the original request for validation (i.e. during pre-population check whether AWS dependencies have been found during recursive variable resolution).  This actually has an additional benefit of solving for an obscure class of bugs where the recursive population previously in getDeepValue caused potential deadlocks resulting from circular dependencies.
For #4687:
1. Add a more …

Eliminate/Report Hung Promises (#4687), Prepopulate Stage and Region (#4311), Handle Quoted Strings (#4734)

---

docs/providers/spotinst/guide/variables.md

It's supposed to say python code, but it says nodejs two times
Edited the text of the page it had a typo
-
Just check the text e.e

Fixed a typo

---

lib/plugins/aws/invokeLocal/index.js

Ref: https://github.com/serverless/serverless/issues/4663#issuecomment-366931491
Closes #4663
The problem is that Python module parsing wasn't correctly performed. For example, consider a function handler, `xyz.scripts.task.entrypoint`. Currently, it is converted into `handlerPath = 'xyz';` and `handlerName = 'scripts'`, but we actually want `handlerPath = 'xyz.scripts.task'` and `handlerName = 'entrypoint'`.
The change is quite simple: rather than splitting the `handler` variable at the first `.`, we instead split it at the last `.`.
https://github.com/dfee/serverless_pymodule_demo
If you run this with the unpatched invoke/index.js you'll get the following message:
```bash
$ sls invoke local -f entrypoint
Traceback (most recent call last):
File …
```

Fixed python module parsing

---

lib/classes/PromiseTracker.js
lib/classes/Service.js
lib/classes/Variables.js
lib/classes/Variables.test.js
lib/plugins/print/print.js
lib/plugins/print/print.test.js

Fixes:
1. deep variables can contain overwrites (see https://github.com/serverless/serverless/pull/4713#issuecomment-366975172 - thank you @laardee).  Reported on #4687.
2. deep variables can render to different variables and must thereby be deep-variable-ified too.  New bug of #4687 discovered fixing previous.
3. errors with the print command cross contaminating the given `serverless.yml` with the previously populated and adorned version processed by the framework.  OLD, painful, and previously unreported.
4. cleans a messy prepopulation implementation.  Closes #4744.
5. a cyclic references bug leading to crashes when using print.  Closes #3627, Closes #3711, Closes #3740, Closes #3882, Closes #4556, Closes #4687.
6. Silently undetected unresolved variables Closes #4699.
7. Support the …

Follow up fixes for #4713

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Only disable and restore dependent service resolution methods once.  Otherwise, subsequent removals may cache the previous replacements.  If they restore last then they will restore with the replacements, breaking standard usage.
Add tests for this guarantee.
This resolves the issue reported at https://github.com/serverless/serverless/pull/4754#issuecomment-368234177
Rather than call off-limits method replacement for each dependent configuration, just do it once, process all the configuration that needs processing, and then do the restore.
`npm run test`
and with any valid serverless.yml:
`sls print [<options>]`

#4713 Follow up fixes, take 2

---

lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js

Closes #4705
This bug was introduced by #3953, and I found the root cause was generated CloudFomation template was broken like this.
Both of integrationresponses and methodresponses were empty in v1.26.0
Set default statusCodes to response template for lambda integration if it is empty
Run `sls deploy` ,and then run `sls invoke -f hello` with following serverless.yml
serverless.yml
``` yaml
service: aws-nodejsefrefrxs
provider:
name: aws
functions:
hello:
events:
- http:
path: hello
method: get
```
handler.js
```js
'use strict';
module.exports.hello = (event, context, callback) => {
callback(null, { message: 'Go Serverless v1.0! Your function executed successfully!' });
};
```
***Is it a …

Fixed a bug which you cannot deploy with lambda integration in v1.26.0

---

docs/providers/aws/events/cloudwatch-event.md
lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js
lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test.js

Now when a user specifies a name property under the cloudwatchEvent, it will be carried over to the CF template.
Closes #4762 
Allows one to specify a custom name for a cloudwatchEvent event.
Added references to Name in the cloudwatchEvent's index.js in the same way Description is handled.
Using the proposed branch, create a project and add a cloudwatchEvent to the serverless.yml like this:
```yaml
service: add-cw-event-name
provider:
name: aws
functions:
hello:
events:
- cloudwatchEvent:
name: 'this-is-my-name'
description: 'This is my description'
event:
source:
- "aws:ec2"
detail-type:
- "EC2 Instance Terminate Successful"
detail:
AutoScalingGroupName:
- "test-asg"
enabled: false
```
Then run `sls package` and confirm that the CF template …

Added name property to cloudwatchEvent CF template

---

docs/providers/aws/events/apigateway.md
lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js

Closes #4374 
Dropped in @behrangsa's fix that has worked for myself and others.
Deploy a lambda authorizer that passes custom context in its callback (lines 4-6):
```
const generatePolicy = (principalId, effect, resourc) => {
const authResponse = {
principalId: principalId,
context: { 
myCustomKey: "myCustomValue"
}
}
if (effect && resource) {
const policyDocument = {}
policyDocument.Version = '2012-10-17'
policyDocument.Statement = []
const statementOne = {}
statementOne.Action = 'execute-api:Invoke'
statementOne.Effect = effect
statementOne.Resource = resource
policyDocument.Statement[0] = statementOne
authResponse.policyDocument = policyDocument
}
return authResponse
}
```
Then deploy a lambda that requires the authorizer and attempts to access the custom context:
``` …
```

Pass authorizer custom context to target lambda

---

CHANGELOG.md

Updated changelog to show 1.26.1 release.

Sync CHANGELOG to represent 1.26.1 release

---

docs/providers/aws/guide/variables.md

Add an alternative AWS-only variableSyntax in AWS doc, which is compatible with the current Serverless syntax `${stuff}`
Usage: `${AWS::stuff}`
(credits to @dschep)

Doc - Add AWS-only alternative for variableSyntax that is compatible with Serverless way

---

lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js

Allow UsagePlan's to be created without ApiKeys defined. Issue #4459

---

docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/createStack.test.js
lib/plugins/aws/lib/updateStack.js
lib/plugins/aws/lib/updateStack.test.js

Added a new AWS provider's property ``notificationArns`` to enable deploy events notification. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-notificationarns
Closes #3998
Set the ``NotificationARNs`` parameter if the ``notificationArns`` provider property is set.
1. Create a SNS topic and grab its ARN (i.e.: `arn:aws:sns:us-west-2:1234567890:mytopic`). Optionally you can set up a subscriber to read the messages from the topic and publish them somewhere (i.e. to a [slack channel](https://github.com/robbwagoner/aws-lambda-sns-to-slack)).
2. Add the `notificationArns` property to a `serverless.yml`:
```
provider:
name: aws
region: us-west-2
...
notificationArns:
- arn:aws:sns:us-west-2:1234567890:mytopic
```
3. Run …

Add notificationArns AWS parameter to enable Cloudformation notifications

---

lib/classes/Variables.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js

Additional fix for #4687
Continue recursion for populateValue root case.
The following serverless.yml can be used to reproduce the problem. Adjust cf reference to an existing stack with an export.
```yaml
service: test
custom: ${file(custom-properties-${opt:stage, self:provider.stage}.yml)}
provider:
name: aws
region: ${self:custom.region}
environment:
TEST: ${cf:resources-v1-dev.UserPoolArn}
```

Continue recursion for #4687

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Fixes reported issue on #4754 by @dschep 
Handle `self:service.[...]` references properly.  The prior represents what the user typed into their configuration.  In service, we move all this from `service` to `serviceObject`, therefore, by rewriting `self:service.[...]` to `self:serviceObject.[...]` user's will get the result they expect.
Cleanup: use `else if`, given exclusivity of conditions
filter `self:service.` variables, replacing that part with `self:serviceObject.` to avoid failed resolutions.
Run the offered test.

Re-write `self:service.[...]` to `self:serviceObject.[...]`

---

docs/providers/aws/guide/variables.md
lib/classes/Variables.js

When using the `${file(foo.js)` feature for `serverless.yml` it's very handy to have a reference to the serverless object available, if only for logging, but it of course be used for much more.
Specifically: I needed to generate/add a list of resources based on whether some other resource was available in the Resources section. I could have done this with CF conditionals or a plugin, but this keeps everything int he JS realm, which gives for more flexibility (especially since CF doesn't have for-loops).
By default no parameter is passed to the given exported function, with this PR it will receive the serverless object, eg:
```js
// config.js
module.exports = (sls) => {
sls.cli.consoleLog('You can access Serverless config and methods');
// serverless.provider.
return {
property1: 'some …
```

Pass serverless variable when calling function in referenced file

---

lib/plugins/aws/invokeLocal/fixture/handlerWithLoadingError.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/index.test.js

Closes #4852
By throwing an exception if the handler module can't be loaded
A unit test has been added to verify the fix

serverless invoke local error handling fix for #4852

---

docs/providers/aws/guide/functions.md
docs/providers/azure/guide/functions.md
docs/providers/google/guide/functions.md
docs/providers/kubeless/guide/functions.md
docs/providers/openwhisk/guide/functions.md
lib/Serverless.js
lib/classes/Service.js
lib/classes/Service.test.js

Closes N/A
Support for
```yml
functions:
- ${file(./functions/frontend.yml)`
- ${file(./functions/backend.yml)`
```
just like how `resources:` works.
I generalized the code that I previously wrote 😁 
Factor a function block in to separate objects in an array, or externalize to files.

Support arrays in function definition too

---

lib/plugins/aws/package/lib/mergeIamTemplates.js
lib/plugins/aws/package/lib/mergeIamTemplates.test.js

Closes #4876
I have updated how iamManagedPolicies are merged with the default role so that when VPC Config is supplied it will include any managed policies on top of the AWSLambdaVPCAccessExecutionRole
Example serverless yml: 
```yml
service: sandbox-for-managed-policies
provider:
name: aws
runtime: java8
vpc:
securityGroupIds:
- sgs
subnetIds:
- subs
iamManagedPolicies:
- 'arn:aws:iam:*****:policy/some-managed-policy'
Action:
- sns:Publish
Resource: "*"
package:
artifact: artifact.jar
functions:
myFunction:
handler: someClass
```
The CloudFormation template should have a default IAM role with the following managed policy arns:
```json
"ManagedPolicyArns": [
"arn:aws:iam:*****:policy/some-managed-policy",
{
"Fn::Join": [
"",
[
"arn:",
{
"Ref": …
```

iamManagedPolicies merging with Vpc config

---

lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
lib/plugins/aws/provider/awsProvider.js
lib/plugins/aws/provider/awsProvider.test.js

Fixes handling of `Rate exceeded` and other recoverable errors.
AWS when throwing recoverable error, exposes the `retryable: true` property on error.
e.g. we can see that on `Rate exceeded` error:
```
{ Throttling: Rate exceeded
at Request.extractError (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/aws-sdk/lib/protocol/query.js:47:29)
at Request.callListeners (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition …
```

Generalize handling of AWS retryable errors

---

README.md

Updated link for `serverless-aws-documentation` plugin.
Closes n/a
Tweaked README!
https://github.com/9cookies/serverless-aws-documention redirects to https://github.com/deliveryhero/serverless-aws-documentation

Repo location of serverless-aws-documentation was changed

---

LICENSE.txt
README.md

Hello! 👋
(CCing @dankohn who has requested this work so that the license will appear correctly in https://landscape.cncf.io/selected=serverless)
GitHub uses a library called Licensee to identify a project's license type. It shows this information in the status bar and via the API if it can unambiguously identify the license.
This commit makes changes that allow Licensee to successfully identify the license type of Serverless as MIT.
I updated the LICENSE file so that it contains only the full text of the MIT license. The info that pertains to 3rd-party software licensing has now been moved to a "Licensing" section in the README.
- Install [Licensee](https://github.com/benbalter/licensee/)
- From within the `licensee` directory, run `licensee detect …

edit Serverless license info so that GitHub recognizes it

---

lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js

Closes #4923
Used wrong function for generating CF, so I have fixed a correct one and added test case so as not to introduce this regression in the future.
Run `sls deploy` with the following serverless.yml
``` yaml
service: shared-api
provider:
name: aws
apiKeys:
- myFirstKeyss
usagePlan:
quota:
limit: 5000
offset: 2
period: MONTH
throttle:
burstLimit: 200
rateLimit: 100
apiGateway:
restApiId: xxxxxxxx # Specify your restApiId
restApiRootResourceId: yyyyyyyyy # Specify your restApiRootResourceId
functions:
hello:
events:
- http:
path: /hello
method: get
```

Fix broken shared API functionality

---

lib/classes/Variables.js
lib/classes/Variables.test.js

When constructing a deep variable, use the variable syntax present in the given variable string, extracting it from the given string that may contain embedded custom variables (i.e. `${{self:var.${{self:var.foo}}.bar}}`).
Closes #4946
extract, repeatedly if embedded variables exist, the used syntax (default or custom) for use, then use shell for deep variable construction.
See unit tests in `Variables.test.js`.

Fix customVariable syntax use results in failed variable population bug

---

docs/providers/aws/guide/functions.md
lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/index.test.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js
lib/plugins/plugin/install/install.test.js

Closes #4884
Lambda environment variables must only contain strings. Although both [CloudFormation template documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-environment.html) and [Lambda's API](https://docs.aws.amazon.com/lambda/latest/dg/API_Environment.html) state that, only Lambda's API enforces it.
As `deploy --function` uses [Lambda's UpdateFunctionConfiguration](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html) and `deploy` updates the CF template, you only see a validation issue when running the function deploy command.
This makes sure both uses will go through the same check to make sure everything is ok (and hopefully in the future, the CF validation will be fixed and no one will be …

AWS Environment variables should contain only strings

---

lib/plugins/create/templates/aws-nodejs-typescript/package.json
lib/plugins/create/templates/aws-nodejs-typescript/serverless.yml
lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json
lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js

I have updated template for typescript in order to use node 8, to have types for streams (missing in previous version) and to use webpack 4
I have updated release in package.json, modified node version in serverless.yml and modify webpack conf (rules) to support webpack 4
`~/bin/serverless create -t aws-nodejs-typescript`
`npm or yarn install`
`sls deploy`

upgrade typescript, types, node and webpack for typescript template

---

lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js

Closes #2797 partially
set CONVERT_TO_TEXT for OPTIONS method in cors config
you can test pre-flight requests (OPTIONS method) using curl or something like test-cors.org
***Is it a breaking change?:*** MAYBE
I realize there are no tests, and I don't have time to write them, but I've been running this for a few months now without issue with BinaryMediaTypes set to "*/*". See https://github.com/serverless/serverless/issues/2797#issuecomment-367342494 for more info. @eraserfusion mentioned this change helped him, perhaps it'll be of use to others.

fix: binary support for pre-flight requests (OPTIONS method)

---

lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js

Closes #4711 
AWS API Gateway allow only 1 Authorizer for 1 ARN. If serverless try to create new Authorizer, Cloudformation will alert:
> ServerlessError: An error occurred: ApiGatewayMethodUsersUseridGet - Invalid authorizer ID specified. Setting the authorization type to CUSTOM or COGNITO_USER_POOLS requires a valid authorizer..
Because each serverless.yml will create new REST API, so we don't meet this error. However, if serverless support Shared API #3934. This case will appear
Support AuthorizationType and AuthorizeId reference
```
functions:
deleteUser:
...
events:
- http:
path: /users/{userId}
...     
authorizer:
type: COGNITO_USER_POOLS
authorizerId: { Ref: "NApiGatewayAuthorizer"}
resources:
Resources:
NApiGatewayAuthorizer: 
Type: AWS::ApiGateway::Authorizer
Properties: …
```

Support Custom Authorizer Type (COGNITO_USER_POOLS) with authorizeId

---

docs/providers/aws/events/apigateway.md

Section anchor of `HTTP Endpoints with AWS_IAM Authorizers` doesn't match.

Fix documentation section anchor

---

docs/providers/kubeless/events/http.md

It would remove some frustration for the documentation skimmers out there if this last step was added, even if some may think it's a little spoon feedy.

Docs: Add a reference to ingress controllers

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

This PR makes functions tags inherit from provider tags. Same behavior as `environment`. 
Merge provider tags with function tags
Given the following `serverless.yml`, `hello` should be deployed with the tag `foo` equal to `quux` and `baz` equal to `qux`
```yml
service: xxx
provider:
name: aws
tags:
foo: bar
baz: qux
functions:
hello:
tags:
foo: quux
```

Make function tags inherit provider tags

---

lib/classes/Utils.js
lib/plugins/aws/package/lib/saveServiceState.js
lib/plugins/aws/package/lib/saveServiceState.test.js
lib/utils/fs/writeFile.js
lib/utils/fs/writeFile.test.js
lib/utils/fs/writeFileSync.js
lib/utils/fs/writeFileSync.test.js

Closes #5014
I made cycle-support opt-in, and enabled it in the one spot I was aware of that needed it, which is the serverless state file.
The example repo I gave on the associated issue has a test that will pass if you use this patch:
- git clone https://github.com/dougmoscrop/serverless-example-json-ref-issue
- `cd serverless-example-json-ref-issue`
- `npm i && npm t` (test will fail)
- (checkout this code and `npm link` from within serverless)
- go back to serverless-example-json-ref-issue and `npm link severless`
- `npm t` will pass

only use json-cycles when opt-in, for state serialization

---

docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/lib/naming.js
lib/plugins/aws/lib/naming.test.js

I implemented a feature that allows developers to customize their CloudFormation stack name and AWS API Gateway API name if they do not want to use the default of `${stage}-${service-name}`.
Closes #2638 
I added a check to see if certain properties were defined in the YAML, and if so, use it for the stack name or API name. If the properties are not defined, use the default as it has been
__You will need to replace anything inside `<` and `>` in the config below__
```
service:
name: ${self:custom.service.name}
plugins:
- serverless-webpack
- serverless-dynamodb-local
- serverless-offline
- serverless-reqvalidator-plugin
- serverless-aws-documentation
- serverless-domain-manager
- serverless-prune-plugin
provider:
name: aws
memorySize: 512
timeout: 10
stackName: …
```

Added ability to create custom stack names and API names

---

docs/providers/aws/events/apigateway.md
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js

Added `PRIVATE` [endpointType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html) for API Gateway
Closes #5063 #5052
Added `PRIVATE` to `validEndpointTypes` const variable with more specific tests.
```yaml:serverless.yml
service: private-endpoint-test
provider:
name: aws
endpointType: private
functions:
helloWorld:
events:
- http:
path: hello
method: get
```
```shell
$ aws --region us-east-1 apigateway get-rest-apis 
{
"items": [
{
"id": "gxq77iec19",
"name": "dev-private-gw-test",
"createdDate": 1530087544,
"apiKeySource": "HEADER",
"endpointConfiguration": {
"types": [
"PRIVATE"
]
}
}
]
}
```

add PRIVATE endpointType

---

docs/providers/aws/events/alexa-skill.md
docs/providers/aws/events/alexa-smart-home.md
docs/providers/aws/events/cloudwatch-event.md
docs/providers/aws/events/cloudwatch-log.md
docs/providers/aws/events/cognito-user-pool.md
docs/providers/aws/events/iot.md
docs/providers/aws/events/sqs.md
lib/plugins/Plugins.json
lib/plugins/aws/lib/naming.js
lib/plugins/aws/lib/naming.test.js
lib/plugins/aws/package/compile/events/sqs/index.js
lib/plugins/aws/package/compile/events/sqs/index.test.js

Adds SQS event integration 🎉 
EDIT 6/28: SQS integration is live! Full testing instructions below.
I saw [Brett Andrews note that Lambda + SQS integration is coming soon](https://twitter.com/AWSbrett/status/1010008780375928833). Then I peeked at the [SAM implementation](https://github.com/awslabs/serverless-application-model/pull/451) of the SQS event. It looks to be very similar to Kinesis / DynamoDB streams as it's a pull-based integration. Like the streams, you can set batch size. There is no need for the `startingPosition` parameter though.
I found the necessary IAM permissions by looking at the permissions on [this role](https://github.com/awslabs/serverless-application-model/pull/477/files#diff-dc24340def2e9285840c922890edac32R8).
We need to wait until the integration is actually …

Add SQS event integration

---

docs/providers/aws/README.md

Closes 
The events page for AWS is missing a link to SQS
Added SQS Link
click the link 😄 

Add SQS To Event List

---

package-lock.json

This updates the `package-lock.json` file so that the `npm` dependencies are locked to their most recent version following semver.
I used Node.js 10.6.0 and npm 6.2.0 to create this file.
The main reason here is to avoid security vulnerabilities creeping in.

Update package-lock.json to lock-down npm dependencies

---

lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/deployFunction/index.test.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

Closes #5094
Fixed the bug by transforming env var to string when setting num value
You can do `sls deploy` and `sls deploy function -f hello` with following yml file and will success both of them.
```yaml
service: sls-test
provider:
name: aws
functions:
hello:
environment:
AWS_ACCOUNT_ID: 1234567890
``` 

Fixed problem of v1.28.0 related environment value 

---

lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/utils/renameService.js
lib/utils/renameService.test.js

Closes #5070 
- **-t** option didn't use RenameService, so I changed to use RenameService.
- RenameService didn't care nested name under service statement so I fixed it.
- I added test for aws-nodejs-typescript's service name.
```
hiromi@hiromi-Matebook:~/git/oos/some-project$ ../serverless/bin/serverless create -t aws-nodejs-typescript -n some-project
Serverless: Generating boilerplate...
_______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.27.0
-------'
Serverless: Successfully generated boilerplate for template: …
```

Fixed that create command didn't use the service name given as -n option

---

lib/utils/downloadTemplateFromRepo.js
lib/utils/downloadTemplateFromRepo.test.js

This PR adds support for installing templates and service boilerplates from GitLab.
Besides adding the function that handles the Gitlab support, I refactored some parts of the code that are repeated to use helper functions.
`serverless create --template-url https://gitlab.com/laardee/serverless-template-example --name gitlab-example` creates service from root of the repo using master branch
`serverless create --template-url  https://gitlab.com/laardee/serverless-template-example/tree/temp/subdir --name gitlab-example-subdir` creates service from sub directory of the repo using temp branch
`serverless install --url https://gitlab.com/laardee/serverless-template-example --name gitlab-example` installs from root of the repo using master branch
`serverless install --url …

Add support for installing templates and boilerplates from GitLab

---

lib/classes/Error.js
lib/classes/PromiseTracker.js

Closes #4984
As per discussion on #4984, I add explanatory text:
```
This can result from latent connections but may represent a cyclic variable dependency
```
Also, rather than multiple messages that look as follows:
```
Serverless Information ----------------------------------
##########################################################################################
Serverless Information ----------------------------------
Serverless Information ----------------------------------
Serverless Information ----------------------------------
Serverless Information ----------------------------------
Serverless Information ----------------------------------
##########################################################################################
```
I collate the message to read like:
``` …
```

Improve messaging and formatting of pending promise warnings

---

lib/classes/Variables.js
lib/classes/Variables.test.js

When a overwrite (defaulting variable) statement is evaluated and a term is populated with a variable, that variable is replaced with a deep variable reference.  This deep variable reference can be mistaken for a valid value, even if it will later fail to resolve.  However, the current logic takes it as the valid result of the overwrite and loses the overwrite context.  This change fixes this error/bug by identifying the case and retaining the context until all deep variables are resolved.
Fixes #5027 ([confirmed](https://github.com/serverless/serverless/issues/5027#issuecomment-407578504))
Possibly #5011 
When evaluating overwrite values, identify deep values among them and if found pause population.
This avoids taking a deep value as a valid term within an overwrite (defaulting) …

During Overwrite, Pause on Deep Variables

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Ignore null errors to allow resolution instead of rejection on undefined SSM variables.
Reported to affect all versions from 1.26 through 1.28.
Closes #5119
Null check.
Using one of the affected releases try a SSM variable in a region that does not have the variable defined.
- [ x] Make sure code coverage hasn't dropped

#5110 null error on undefined AWS SSM variables

---

lib/plugins/aws/invokeLocal/index.js

On Windows machines, attempting to invoke a Java lambda locally causes the following error:
`Error: spawn mvn ENOENT`
Closes #4680 
Added a fix suggested from here: https://github.com/nodejs/node-v0.x-archive/issues/2318
Invoke a Java function locally on Windows (Win10 in our case) on a fresh install of serverless. The fix should also be compatible on other OSes. We have a team of a few devs (on a mix of Windows and OSX machines) that have been using this fix for a few months now without issue.

Add Windows support for spawning mvn

---

lib/plugins/aws/invokeLocal/index.js

#5030 & #4789
Added shell=true option to spawn API which is by default set to false. 
Run Invoke local command in windows machine.
Example : sls invoke local -f hello --data '{"a":"bar"}'

Update spawn API with {shell=true}

---

lib/plugins/platform/platform.js

Makes the `resourceId` deterministic in order to corralte old and new state items in the backend and fix issues with resource diffing.
Here's a screenshot how resource diffing looks like before and after applying the fix (note both deployments are just service-updates and no fresh deployments):
**Before (there are tons of other resource additions and removals...):**
**After:**

Deterministic resourceId to fix state diffing on Platform

---

lib/classes/Variables.js
lib/classes/Variables.test.js

Resolve an error introduced by #5156 where replacing an default/overwrite statement used the full context property rather than only the default/overwrite statement itself.
Closes #5205
Closes #5216 
Use the variable string from which the overwrite parameters were extracted (`match.match`) as the replacement target (in the case of deep variable discovery) rather than the context property (`property`) which represents the entire original value that the replacement is being waited upon.  That context property can contain far more content than the overwrite string itself (e.g. `${self:custom.foo.${opt:stage, self:provider.stage}, 'shouldNotSee'}` rather than `${opt:stage, self:provider.stage}`).
See new test, alternatively validate by cloning …

Swap in Deep Variables within Matched Variable String

---

lib/plugins/aws/package/compile/events/apiGateway/index.js
lib/plugins/aws/package/compile/events/apiGateway/index.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js

Closes #5100 
This closes the bug where large API Gateways ran into deployment issues when using CORS.
The CORS Method resource logical ids are now included in the `DependsOn` block of the API Gateway deployment resource.
Hard to actually reproduce this bug since it's a race condition. Developers affected by #5100 should try this PR and see if it resolves the issue.
Re-deploying a service via `serverless deploy` should be enough to test this fix.

Fix CORS race condition

---

docs/providers/aws/guide/quick-start.md

In the [AWS Quickstart ](https://serverless.com/framework/docs/providers/aws/guide/quick-start/) docs page there is a link at the bottom that reads _Check out the Serverless Framework Guide for more information_. Yet this link simply redirects to the same Quick Start docs page.

[docs] Remove redundant link to same docs page

---

docs/providers/aws/events/sns.md
lib/plugins/aws/package/compile/events/sns/index.js
lib/plugins/aws/package/compile/events/sns/index.test.js

Closes #5221
[Inline subscription](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-subscription.html) for the topic doesn't support filter policy, so I changed the subscription to be [separate resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html). 
This increases the resource count in the template, so it can be an issue if someone has a stack which is hitting the limits and updates the a new version.
Option would be to write separate subscription resource only when filter policy exists.
Example setup for creation a subscription with a filter policy
```yml
functions:
pets:
handler: pets.handler
events:
- sns:
topicName: pets
filterPolicy:
pet:
- dog
- cat
```
***Is …

Adds FilterPolicy to SNS event

---

lib/plugins/package/lib/zipService.js

Since `node-dependencies*` will remain in `/tmp`, cleanup added.
Add the flow to be deleted last.
File does not remain in `/tmp` after deploy.

Remove `/tmp/node-dependencies*`

---

docker-compose.yml
docs/providers/aws/cli-reference/create.md
docs/providers/aws/guide/services.md
lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/plugins/create/templates/aws-alexa-typescript/gitignore
lib/plugins/create/templates/aws-alexa-typescript/handler.ts
lib/plugins/create/templates/aws-alexa-typescript/package.json
lib/plugins/create/templates/aws-alexa-typescript/serverless.yml
lib/plugins/create/templates/aws-alexa-typescript/source-map-install.js
lib/plugins/create/templates/aws-alexa-typescript/tsconfig.json
lib/plugins/create/templates/aws-alexa-typescript/webpack.config.js
tests/templates/test_all_templates

Added a template for building Alexa skills, based on the `serverless-alexa-skills` plugin.
Adapted from the existing `aws-nodejs-typescript` template:
- Added the `serverless-alexa-skills` plugin.
- Added the `ask-sdk` package.
- Adapted the handler for Alexa.
- Added matching unit and integration tests.
1. Run the additional unit and integration tests.
2. Setup a new project using: `sls create --template-url https://github.com/danielrbradley/serverless/tree/alexa-typescript-template/lib/plugins/create/templates/aws-alexa-typescript`
3. Follow the instructions in the generated `serverless.yml` (you'll need an Amazon developer account)

Add new template for AWS Alexa Typescript

---

docs/providers/aws/events/sqs.md

From the AWS docs:
https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html
it says:
> Amazon Simple Queue Service supports both Standard and FIFO queues. AWS Lambda supports only standard queues. For more information on the difference, see What Type of Queue Do I Need?

[Docs] - Add support information for AWS lambda and SQS

---

lib/plugins/create/templates/aws-nodejs-typescript/handler.ts

`aws-nodejs-typescript` handler template of new notation similar to:
https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/aws-nodejs/handler.js
Just like the js version
`sls create --template aws-nodejs-typescript`

Update AWS TypeScript handler template

---

lib/plugins/aws/invokeLocal/invoke.py

Closes #5283
Brought the python fake local invoke context up to greater parity with aws python runtime context based on the investigation in missing attributes and attribute value type mismatches mentioned in https://github.com/serverless/serverless/issues/5283#issuecomment-420510817
I added two new property methods to invoke.py for the two attributes I was missing and corrected the value type of `memory_limit_in_mb` to match that of the aws lambda python runtime
You can essentially follow the same experiment here https://github.com/serverless/serverless/issues/5283#issuecomment-420510817
you can take the off the shelf aws lambda python3.6 runtime template and change it to output the attrs and value types defined on the context object
```python
return [(attr, …
```

more faithfully represent aws lambda python runtime context
