- cli/lib/main.js
> json strigify result of lambda context

- bin/jaws
- lib/commands/deploy_api.js
- lib/commands/deploy_lambda.js
- lib/commands/env.js
- lib/commands/generate.js
- lib/commands/install.js
- lib/commands/logs.js
- lib/commands/new.js
- lib/commands/tag.js
- lib/index.js
- lib/utils/index.js
- package.json
- tests/cli/deploy_api.js
- tests/cli/deploy_lambda.js
- tests/cli/env.js
- tests/cli/generate.js
- tests/cli/install.js
- tests/cli/new.js
- tests/cli/tag.js
- tests/config.js
- tests/test_utils.js
Dont have everything into 1 global JAWS var. Make Class and modularize everything else.
> V1.0 modularize

- bin/jaws
- lib/commands/new_action.js
Updated the New Action command help text
> New Action command help text

- lib/commands/new_project.js
This is one of 2 regions that AWS Lambda is publicly available in.
> Add us-west-2 region for project creation.

- lib/commands/new_stage_region.js
Sorry that this is a separate commit, missed this one.
> Add us-west-2 region for new stage.

- README.md
I think using a relative path works.
> Fix the header image link in README

- package.json
> Install shelljs as dependency, not devDependency

- bin/jaws
- lib/commands/new_project.js
- lib/commands/new_stage_region.js
- lib/utils/aws.js
- lib/utils/cli.js
- lib/utils/index.js
- package.json
- tests/cli/new_stage_region.js
These commands were not upgraded to support the new json structure in the v1.0 re-write.
> fixing new stage/region command

- lib/commands/deploy_lambda.js
- package.json
Add to your awsm.json
```
"optimize": {
"builder": "browserify",
"babel": true,
...
}
```
> Add option to compile with babel

- lib/commands/module_install.js
My resources weren't being updated as the readdirRecursiveAsync was only ever returning a top level stage directory and not descending correctly.
> Reworked the recursive search for cf.

- bin/jaws
- lib/commands/deploy_lambda.js
- lib/commands/module_create.js
- lib/commands/module_install.js
- lib/commands/new_project.js
- lib/utils/aws.js
- lib/utils/cli.js
- lib/utils/index.js
- package.json
- tests/test_utils.js
> Fix credential creation from `jaws new project` prompts

- bin/jaws
- lib/commands/module_create.js
- tests/cli/module_create.js
> Allows for optional package manager usage

- docs/create_reusable_module.md
Docs on creating custom AWSM modules.
> Module docs

- lib/commands/deploy_endpoint.js
> Fixed ApiKeyRequired usage

- docs/commands.md
Nothing really critical :smile:
> Fixed a typo in the commands.md file

- lib/commands/project_new.js
> Closed an unclosed bracket.

- lib/defaults/actions/ProjectCreate.js
* Support events
* added validate promise
* replaced Promise with BbPromise
> Refactor ProjectCreate

- lib/actions/ProjectCreate.js
I attempted to create domain like `my-dev.mycompany.com` and it failed, this is the fix.
> Allowing `-` in bucket subdomains

- lib/actions/ProjectCreate.js
Just lost 15 minutes figuring out why I'm getting project names with cryptic suffixes..
> Inform user about changing the provided values

- lib/actions/FunctionCreate.js
- lib/actions/ModuleCreate.js
- lib/actions/ModuleInstall.js
Looks like this got missed in the rename.
> Replace JAWS error with new SERVERLESS error

- lib/actions/StageCreate.js
- lib/templates/lambdas-cf.json
- lib/templates/resources-cf.json
- lib/utils/aws/CloudFormation.js
- lib/utils/index.js
- tests/test_utils.js
CloudFormation added support for grouping and customizing parameter ordering and labeling - it'd be great to use that by default so when people customize resources for their own projects they can keep everything organized.
> Group parameters in CFN template

- lib/actions/EnvGet.js
- lib/actions/EnvList.js
- lib/actions/EnvSet.js
- lib/actions/EnvUnset.js
- lib/actions/FunctionCreate.js
- lib/actions/FunctionRunLambdaNodeJs.js
- lib/actions/ModuleCreate.js
- lib/actions/ProjectCreate.js
- lib/actions/ResourcesDeploy.js
- lib/actions/StageCreate.js
- lib/utils/aws/CloudFormation.js
- lib/utils/aws/CloudWatch.js
- lib/utils/aws/Lambda.js
- lib/utils/aws/Misc.js
- lib/utils/aws/S3.js
- lib/utils/index.js
- tests/test_utils.js
- tests/tests/actions/EnvGet.js
- tests/tests/actions/EnvList.js
- tests/tests/actions/EnvSetUnset.js
- tests/tests/actions/FunctionRun.js
- tests/tests/actions/ResourcesDeploy.js
- tests/tests/actions/TestDefaultActionHook.js
Since so many folks have trailing whitespace removal on, we should really get
rid of these all at once to make it easier to deal with the resulting merge
conflicts.
> Monster whitespace commit

- lib/utils/aws/CloudFormation.js
Fixes:
[ServerlessError: Something went wrong while createing your cloudformation]
or
[ServerlessError: Something went wrong while updateing your cloudformation]
> Fix improper pluralization of creating or updating in CloudFormation error

- README.md
Just finished the first version of the CORS plugin. Would love to have it included in the plugin list, so people will start to find it.
> Add CORS plugin to plugins list

- lib/actions/EndpointBuildApiGateway.js
Minor change to add formatting stringified requestTemplates so that they are readable by humans in the console.
> requestTemplates+newlines

- lib/ServerlessFunction.js
This will fix creating & deploying functions from a Windows host.
> Fix handler path for Windows support (v0.1)

- lib/actions/FunctionCreate.js
This will fix creating & deploying functions from a Windows host.
Fix for `master` branch. Will do a separate PR for `v0.1.0`.
> Fix handler path for Windows support

- lib/Serverless.js
solves https://github.com/serverless/serverless/issues/392
> add aws profile support

- lib/utils/cli.js
Some cleanup of `_this` variables.
> Clean _this variables

- lib/utils/index.js
Fix to account for Windows pathways in this function.
> Account for Windows pathways in pathToContext function.

- README.md
Just a couple of nitpicks that jumped out at me.
> Spelling and grammar fixes in README.md

- lib/ServerlessProject.js
- lib/actions/ComponentCreate.js
- lib/actions/FunctionCreate.js
- lib/actions/FunctionRunLambdaNodeJs.js
- lib/actions/FunctionRunLambdaPython2.js
- lib/utils/index.js
Still not working right, but should be good for merge.
Also, some SUtils cleanups - with all references checked to be used the new SUtil syntax.
> A bit of module removal during component/function creation

- lib/actions/EventDeployS3Lambda.js
- lib/actions/EventDeploySNSLambda.js
- lib/actions/EventDeployScheduledLambda.js
- lib/actions/EventDeployStreamLambda.js
* use proper Lambda function name
* grant necessary permissions
> Reworked Scheduled Events

- lib/ServerlessProject.js
- lib/actions/PluginCreate.js
- lib/actions/ResourcesDiff.js
Recent merges got into conflict, this tries to clean up situation.
> API usage updates after recent merges

- CONTRIBUTING.md
Add contribution notes from gitter.
They detail how to run the tests.
> v0.5 add contribution notes

- lib/Stage.js
- lib/actions/CodeDeployLambda.js
- lib/actions/CodePackageLambda.js
- lib/actions/EventDeployS3Lambda.js
- lib/actions/RegionCreate.js
- lib/actions/RegionRemove.js
- lib/actions/ResourcesDeploy.js
- lib/actions/StageRemove.js
- lib/utils/index.js
> More fixes

- lib/templates/nodejs/package.json
Modules were dropped recently in favor for components.
> Fix description of nodejs package.json template

- README.md
We've got a few Serverless projects in production and many more in works.
> Add SC5 to the list of consultants.

- lib/Component.js
- lib/Function.js
- lib/Plugin.js
- lib/SerializerFileSystem.js
- lib/actions/CodePackageLambda.js
- lib/actions/ComponentCreate.js
- lib/actions/FunctionCreate.js
- lib/actions/FunctionDeploy.js
- lib/actions/FunctionLogs.js
- lib/actions/FunctionRunLambdaNodeJs.js
- lib/actions/FunctionRunLambdaPython2.js
- lib/actions/PluginCreate.js
- lib/utils/index.js
- tests/all.js
- tests/tests/actions/ComponentCreate.js
- tests/tests/actions/ResourcesDeploy.js
- tests/tests/actions/projectLifeCycle.js
All test are passing. Except `tests/actions/ProjectInstall` which fails due to function name conflict in [serverless-starter](https://github.com/serverless/serverless-starter), I guess.
> fixes many actions

- lib/actions/FunctionRollback.js
fixes this issue: https://github.com/serverless/serverless/issues/734
> FunctionRollback typo

- lib/utils/index.js
Tiny changes to allow for falsy values to be used in templates and variables.
> Allow falsy templates & variables

- README.md
Add microapps in consultants list
> Add microapps in consultants list

- lib/actions/FunctionDeploy.js
Fixes issue #823 for FunctionDeploy
> Issue #823 Check for invalid region in FunctionDeploy.

- lib/templates/plugin/index.js
Fixes the #828. Change sample hook's action to ```functionRun```.
> Fixes the plugin template error after created.

- lib/Function.js
- lib/actions/CodeDeployLambda.js
Defaults to old description if nothing is set to keep compatibility.
> Issue #845 - Added description property to `s-function.json`.

- lib/Runtime.js
Wrench copyDir now follows symlinks
PR now based on master after release of 0.5
> Issue #866 Let wrench follow symlinks while packaging

- README.md
Add Apiwise to the consultants list :)
> Add Apiwise to the consultants list

- lib/Actions.json
- lib/actions/VariablesList.js
variables per region/stage or all of them with option --all
> Issue #873 Added vsriables list action to show

- lib/Serverless.js
This resolves issue https://github.com/serverless/serverless/issues/908
> initialize providers *after* loading environment

- README.md
We're using serverless to scale out on-demand processing jobs as well as build APIs and data flows with dynamo streams. :) It's great.
> Add Useful IO to the consultants list

- lib/actions/CodeDeployLambda.js
Useful if your working with external binaries/packages.
> Add support for symbolic links and retain original file permissions

- README.md
sc5-serverless-boilerplate is a project template for test driven development of REST backends (installed using sls project install -n projectname sc5-serverless-boilerplate
serverless-mocha-plugin is a plugin to ease test driven development with serverless
> Addition of sc5-serverless-boilerplate and serverless-mocha-plugin to the documentation

- tests/all.js
- tests/tests/actions/ProjectInstall.js
- tests/tests/classes/ProviderAws.js
Now all tests with `TEST_SERVERLESS_EXE_CF=true/false` are passing!
> Fixes tests

- README.md
Before submitting a PR, please note the following:
[] Make sure that there's an issue opened that discuss this fix/feature. This is not required for simple PRs (ie. fixing a typo in README), but we just want to make sure you don't waste your time on a feature that we don't intend to support/maintain.
[] Make sure that you've tested your changes thoroughly.
[] If there are some side effects to your changes (whether positive or negative), please mention them in your PR so that we can discuss how to avoid them.
Above all, we thank you so much for your contribution! :)
> Adding MoonMail inside Projects section

- .eslintrc.js
- lib/Variables.js
- package.json
@flomotlik please, have a look.
Run the lint: `npm run lint`, don't forget to `npm install` before.
> Adds `eslint` and the airbnb rules

- README.md
Hi --
Just adding ourselves to the consultants list. Not sure if there's a formal process here, just did what the others in the list seemed to do. Please do let me know if you need us to do anything additional :)
Thanks!
Ankur
> Add Hop Labs to the consultants list

- README.md
Added reference to [serverless-sentry-plugin](https://github.com/arabold/serverless-sentry-plugin), a plugin to automatically send errors and exceptions to [Sentry](https://getsentry.com) without requiring any code changes.
> Added serverless-sentry-plugin

- tests/all.js
- tests/tests/classes/Serverless.js
> getVersion test now checks a regex

- doc/Configuration.md
- doc/services.md
Before submitting a PR, please note the following:
Make sure that there's an issue opened that discuss this fix/feature. This is not required for simple PRs (ie. fixing a typo in README), but we just want to make sure you don't waste your time on a feature that we don't intend to support/maintain.
[] Make sure that you've tested your changes thoroughly.
[] If there are some side effects to your changes (whether positive or negative), please mention them in your PR so that we can discuss how to avoid them.
Above all, we thank you so much for your contribution! :)
> V1.0 docs config

- bin/serverless
- lib/Serverless.js
- lib/classes/Service.js
- lib/classes/Utils.js
- lib/plugins/awsResourcesDeploy/tests/awsResourcesDeploy.js
- lib/plugins/create/tests/create.js
- package.json
- tests/classes/Service.js
- tests/classes/Utils.js
The service directory will be automatically detected if the users CWD is a valid
Serverless service directory.
> Add automatic servicePath detection functionality

- lib/plugins/Plugins.json
- lib/plugins/removeResources/removeResources.js
- lib/plugins/removeResources/tests/removeResources.js
- tests/all.js
Implements the basic removeResources plugin which defines a
"removeResources" lifecycle hook.
Refs #1161
> Closes #1227 - Implement removeResources plugin

- lib/plugins/Plugins.json
- lib/plugins/awsInvoke/awsInvoke.js
- lib/plugins/awsInvoke/tests/awsInvoke.js
- tests/all.js
So that it sticks to the overall used plugin naming.
> Rename invokeAws to awsInvoke

- docs/README.md
- docs/concepts/event-sources.md
- docs/concepts/plugins.md
- docs/concepts/services.md
Updated the services definition to reflect the recent changes and fixed some minor
stuff.
> Add event sources concept to docs

- docs/README.md
- docs/plugins/aws/awsDeploy.md
This makes it easier to get started on Plugin development.
> Add a new FAQ section in README.md / updates awsDeploy doc

- docs/concepts/services.md
- lib/plugins/awsDeploy/lib/initializeResources.js
- lib/templates/serverless.yaml
Fix indentations and fix naming in resources section so that it matches the recent changes.
The custom resources merging is fixed as well.
> Update serverless.yaml file

- docs/concepts/serverless-yaml.md
- docs/concepts/services.md
Fix the docs so that the custom resources section is correct again.
> Fix invalid docs

- README.md
Simple PR, just making the plugin more visible. If we want to talk about getting this in V1, I am happy to help with implementation.
> Adds Serverless Secrets to plugin list

- lib/plugins/aws/deploy/compile/events/apiGateway/tests/deployment.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/resources.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/restApi.js
- lib/plugins/aws/deploy/compile/events/s3/tests/index.js
- lib/plugins/aws/deploy/compile/events/schedule/tests/index.js
- lib/plugins/aws/deploy/compile/functions/tests/index.js
- lib/plugins/aws/deploy/tests/index.js
- lib/plugins/aws/deploy/tests/updateStack.js
- lib/plugins/aws/invoke/tests/index.js
- lib/plugins/aws/remove/tests/all.js
- lib/plugins/aws/remove/tests/bucket.js
- lib/plugins/aws/remove/tests/stack.js
- lib/plugins/aws/remove/tests/validate.js
- lib/plugins/create/tests/create.js
- tests/all.js
> Fix unreliable plugin test coverage

- lib/plugins/aws/remove/lib/stack.js
Should finally resolve https://github.com/serverless/serverless/issues/1367
> Add DELETE_FAILED to stackStatusFilter

- lib/classes/CLI.js
Shows which options are required when running the `--help` command.
> Add show required options in CLI functionality

- lib/templates/serverless.yaml
Update so that the latest changes are reflected in the file
> Update serverless.yaml template

- docs/guide/overview-of-event-sources.md
- docs/using-plugins/core-plugins.md
- lib/plugins/Plugins.json
- lib/plugins/aws/deploy/compile/events/sns/README.md
- lib/plugins/aws/deploy/compile/events/sns/index.js
- lib/plugins/aws/deploy/compile/events/sns/tests/index.js
This plugin adds functionality so that a lambda function gets called when a message is sent to a SNS topic.
> Add awsCompileSnsEvents plugin

- lib/plugins/aws/deploy/lib/uploadDeploymentPackage.js
- lib/plugins/aws/deploy/tests/uploadDeploymentPackage.js
Implementation of https://github.com/serverless/serverless/issues/1504
> Add keep 5 service versions in S3 bucket functionality

- docs/understanding-serverless/services-and-functions.md
I thing is memoryVar is correct than memoryVariable
> Change the variable

- tests/all.js
Add missing test for SNS plugin.
> Add tests for AWS SNS plugin

- lib/plugins/create/create.js
Introduced to DRY out code more.
> Update "available templates information" to be class wide constants

- lib/Serverless.js
- lib/classes/PluginManager.js
- package.json
- tests/classes/PluginManager.js
Ready
Implement service plugin loading
Resolves #1442
> Implement service plugin loading

- docs/using-plugins/core-plugins.md
> Fix missing slash for SNS docs

- docs/README.md
- docs/developing-plugins/building-plugins.md
- docs/guide/creating-a-service.md
Some minor fixes to the available docs.
> Quick doc fixes

- docs/README.md
- docs/guide/creating-a-service.md
- docs/service-templates/README.md
Basic documentation for service templates (see #1564).
> Add docs for service templates

- lib/classes/CLI.js
- lib/plugins/create/create.js
- lib/plugins/create/tests/create.js
Ready
I had git hell for PR #1503, so I'm creating this one, based on latest v1.0 and addresses the comments from the PR.
> fix issue #1380 - remove ascii greeting (take 2)

- lib/classes/CLI.js
- lib/plugins/create/create.js
- lib/plugins/create/tests/create.js
- tests/classes/CLI.js
Ready
I had git hell for PR #1503, so I'm creating this one, based on latest v1.0 and addresses the comments from the PR, for issue #1479.
> Fix 1479 - display help (take 2) 

- CONTRIBUTING.md
- README.md
Ready
Move Contribution guide back into main folder and update it and README
@ac360 @pmuens @eahefnawy can you review the changes to CONTRIBUTION and README. Contribution is a bit longer, but imho not too much and it explains everything really well.
> Update Contribution Guide and README

- docs/README.md
- docs/usage-tracking/README.md
- docs/usage-tracking/usage-tracking.md
- docs/using-plugins/core-plugins.md
- lib/Serverless.js
- lib/classes/Utils.js
- lib/plugins/Plugins.json
- lib/plugins/tracking/README.md
- lib/plugins/tracking/tests/tracking.js
- lib/plugins/tracking/tracking.js
- npm-shrinkwrap.json
- package.json
- tests/all.js
This PR implements the first, basic usage tracking functionality as discussed in https://github.com/serverless/serverless/issues/1559
> Add basic usage tracking functionality

- lib/plugins/aws/index.js
Ready
#1638 describes the detail
> fixes serverless/serverless#1638

- docs/usage-tracking/usage-tracking.md
- lib/classes/Utils.js
Here we track what events were used and how often they were used.
Corresponding issue: https://github.com/serverless/serverless/issues/1605
> Add additional event type tracking functionality

- lib/classes/Utils.js
- package.json
Version Pump: Releasing Alpha 2
> Version Pump

- README.md
Branded Crate is looking for clients who want to go serverless!
> add Branded Crate agency to README.md

- lib/classes/Service.js
- tests/classes/Service.js
Ready
If there are no events defined in the `serverless.yaml` file, the deployment will fail. Now checking for existence of events.
> existence of events

- lib/Serverless.js
This PR fixes the bug that the commands were not showing up (the Promise of the command execution was resolved and the CLI exited before going into the tracking method).
> Fix command tracking not working bug

- README.md
Ready/In Development/Hold
We use the Serverless Framework to build Serverless solutions for our clients.
> Adding cloudonaut as consultants using the Serverless Framework

- docs/guide/deploying-a-service.md
Add a note that the user knows that he can always access 5 versions of the deployed code.
> Add note about code versioning

- docs/guide/overview-of-event-sources.md
Add docs so that the user knows that and how he can use the universal velocity request template.
> Add docs for universal velocity request template

- lib/plugins/aws/deploy/compile/events/apiGateway/README.md
- lib/plugins/aws/deploy/compile/events/apiGateway/index.js
- lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js
- lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
- lib/plugins/aws/deploy/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/all.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/authorizers.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/permissions.js
- tests/all.js
This PR adds support for custom authorizers for APIG as described in issue #1594 
Status: G2M from my side
> Add support for custom authorizers for APIG

- docs/guide/deploying-a-service.md
added docs that demos how to change the default stage/region in `serverless.yaml`
> docs for changing default stage/region

- lib/classes/PluginManager.js
- tests/classes/PluginManager.js
Fixes #1521 so that plugins are only loaded once.
> Fix plugins are loaded twice bug

- lib/plugins/create/templates/aws-nodejs/serverless.yaml
Ready
The indentation of the http arguments is missing one level.
> fixed indentation

- CONTRIBUTING.md
- Dockerfile
- docker-compose.yml
- lib/plugins/create/create.js
- lib/plugins/create/templates/README.md
- lib/plugins/create/templates/aws-java-gradle/build.gradle
- lib/plugins/create/templates/aws-java-gradle/event.json
- lib/plugins/create/templates/aws-java-gradle/serverless.env.yaml
- lib/plugins/create/templates/aws-java-gradle/serverless.yaml
- lib/plugins/create/templates/aws-java-gradle/src/main/java/hello/Handler.java
- lib/plugins/create/templates/aws-java-gradle/src/main/java/hello/Request.java
- lib/plugins/create/templates/aws-java-gradle/src/main/java/hello/Response.java
- lib/plugins/create/templates/aws-java-maven/event.json
- lib/plugins/create/templates/aws-java-maven/pom.xml
- lib/plugins/create/templates/aws-java-maven/serverless.env.yaml
- lib/plugins/create/templates/aws-java-maven/serverless.yaml
- lib/plugins/create/templates/aws-java-maven/src/main/java/hello/Handler.java
- lib/plugins/create/templates/aws-java-maven/src/main/java/hello/Request.java
- lib/plugins/create/templates/aws-java-maven/src/main/java/hello/Response.java
- lib/plugins/create/templates/aws-nodejs/event.json
- lib/plugins/create/templates/aws-python/event.json
- lib/plugins/create/tests/create.js
- tests/templates/integration-test-template
- tests/templates/test_all_templates
Ready
Adding template integration testing and small fix on top of PR #1659  from @license2e
> License2e add aws java templates v2

- lib/plugins/create/create.js
- lib/plugins/create/templates/aws-java-gradle/serverless.yaml
- lib/plugins/create/templates/aws-java-maven/serverless.yaml
- lib/plugins/create/templates/aws-nodejs/serverless.yaml
- lib/plugins/create/templates/aws-python/serverless.yaml
This way the user knows that he should update the services name after the creation process.
> Add note to update the service name after creation

- lib/plugins/create/templates/README.md
Add documentation for the Node.js and Python templates as discussed in https://github.com/serverless/serverless/issues/1645
> Add Node.js and Python to templates README

- docs/guide/deploying-a-service.md
- lib/plugins/aws/deploy/compile/functions/index.js
- lib/plugins/aws/deploy/compile/functions/tests/index.js
This PR adds support for providing VPC configuration for functions as described in issue #1489 . It also includes tests and docs.
> added support for VPC with tests and docs

- docs/guide/provider-account-setup.md
Added a simple helper guide with ready to go command for setting API keys for AWS. Should make on boarding much easier.
> Added a quick guide for setting AWS API keys

- RELEASE_CHECKLIST.md
This file contains a checklist one can go through when releasing a new Serverless version.
> Add RELEASE_CHECKLIST.md file

- README.md
Ready
Fix broken link to the `Understanding Serverless and its configuration files` docs folder in the projects README.
> Fix broken v1.0.0 README docs link

- docs/README.md
- docs/guide/installation.md
Replace the old `alpha` references with `beta`.
> Replace outdated alpha references

- docs/understanding-serverless/serverless-yml.md
Added memorySize and timeout property to function configuration docs so that user knows how to overwrite the defaults. Resolves issue #1534.
> added docs for default function config properties

- lib/classes/PluginManager.js
- lib/plugins/aws/deploy/compile/events/apiGateway/index.js
- lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/deploy/lib/deployFunctions.js
- lib/plugins/aws/deploy/lib/initializeResources.js
As discussed in https://github.com/serverless/serverless/issues/1515, I removed the individual requires, and moved everything to require the whole `lodash` package for easier development and debugging.
> Removed individual lodash functions

- CONTRIBUTING.md
- README.md
adding links to those labels helps contributors find things to start contributing to
> Add help-wanted and help-wanted-easy labels to README

- docs/guide/removing-a-service.md
The change is small and does not involve code, so I hope that it's okay that I did not create an issue.
> Fix a small typo

- README.md
Serverless-dynamodb-local plugin and serverless-dependency- manager.
Ready/In Development/Hold
…all plugin links
> Added two 0.5x plugins to the list. 

- lib/plugins/create/templates/aws-java-gradle/serverless.env.yml
- lib/plugins/create/templates/aws-java-maven/serverless.env.yml
- lib/plugins/create/templates/aws-nodejs/serverless.env.yml
- lib/plugins/create/templates/aws-python/serverless.env.yml
Ready
Just a simple typo fix :)
> fixed a typo

- lib/classes/CLI.js
Sort the plugin list as described in https://github.com/serverless/serverless/issues/1257
> Sort plugins for display in help

- lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/resources.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/validate.js
- lib/plugins/aws/deploy/compile/events/s3/tests/index.js
- lib/plugins/aws/deploy/compile/events/schedule/tests/index.js
- lib/plugins/aws/deploy/compile/events/sns/tests/index.js
- lib/plugins/aws/deploy/compile/functions/tests/index.js
- lib/plugins/aws/deploy/tests/createStack.js
- lib/plugins/aws/deploy/tests/deployFunctions.js
- lib/plugins/aws/deploy/tests/uploadDeploymentPackage.js
- lib/plugins/aws/deployFunction/tests/index.js
- lib/plugins/aws/info/tests/index.js
- lib/plugins/aws/invoke/tests/index.js
- lib/plugins/aws/logs/tests/index.js
- lib/plugins/aws/remove/tests/bucket.js
- lib/plugins/aws/remove/tests/stack.js
- lib/plugins/aws/tests/index.js
- lib/plugins/aws/tests/validate.js
- lib/plugins/create/tests/create.js
- lib/plugins/package/tests/all.js
- lib/plugins/package/tests/index.js
- lib/plugins/package/tests/validate.js
- tests/all.js
Check the test coverage and added some test so that we're above 90% again.
> Add tests to increase test coverage

- lib/classes/Service.js
- tests/classes/Service.js
Ready
Support populating false/0 value variables
> fix populate boolean and 0 variables

- docs/README.md
Added docs on how to run serverless in debug mode by setting the SLS_DEBUG env var. Resolves Issue #1690
> Added docs for debug mode

- tests/classes/Serverless.js
Add tests for all methods of the Serverless class.
> Increase test coverage for Serverless class

- lib/classes/Service.js
- lib/plugins/aws/deploy/lib/initializeResources.js
- tests/classes/Service.js
Fixed a bug reported by @mthenw where the Service class doesn't populate variables based on provided shortcut options
cc/ @pmuens @flomotlik
> fixed a bug in service class to load shortcut options

- docs/developing-plugins/building-plugins.md
- docs/developing-plugins/building-provider-integrations.md
Doc fixes for incorrect examples. Thanks to @maciej who has uncovered those.
> Minor doc fixes

- docs/guide/deploying-a-service.md
a user was confused about where to find these so made it more explicit.
> doc update

- README.md
> Add PromptWorks to consultants

- lib/plugins/package/lib/zipService.js
Ready
When running on windows, 'UNIX' was incorrectly being passed into jszip as the host platform which causes it to generate a zip file which lambda doesn't unpack properly. ( I think its the \ vs / thing  - the zip file looks correct when I open it in a gui tool, but using unpack unpacks a bunch of files with '\' in the filename and no actual folder structure )
> fix #1860 - Cannot find module for any node_modules

- docs/guide/event-sources.md
Documentation typo and language fix.
change get's -> gets in event-sources.md
> fix some language and typos

- docs/understanding-serverless/serverless-yml.md
PR to add docs to answer question in http://forum.serverless.com/t/how-do-i-refer-to-module-not-at-the-root-directory-in-serverless-yml/157
> Add handler and subdir docs to serverless.yml

- README.md
Fixes the broken link to the v0 docs.
> Fix broken v0 docs link

- docs/guide/provider-account-setup.md
Ready
Fixed minor typo in documentation.
> fix minor typo

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Nicer Pull Request and Issue templates so users have a better time writing them
> Update pull request and issue template

- lib/plugins/aws/deploy/compile/functions/index.js
- lib/plugins/aws/deploy/compile/functions/tests/index.js
***Implementing Issue:*** #1772 
I  implemented #1772
If `provider > iamRoleARN` is exists in serverless.yml, all Lambdas use iamRoleARN.
If `provider > iamRoleARN` is not exists in serverless.yml, all Lambdas use the IamRoleLambda template and the IamPolicyLambda template and custom IAM policy statements.
Please settiing in serverless.yml
provider:
iamRoleARN: <Your ARN>
If `provider > iamRoleARN` is exists in serverless.yml, the cloudformation is set up below
```json
"Resources": {
"ServerlessDeploymentBucket": {
"Type": "AWS::S3::Bucket"
}, 
"hello": {
"Properties": {
"Code": {
"S3Bucket": {
"Ref": "ServerlessDeploymentBucket"
}, 
"S3Key": "xxxxxxxxxx-2016-08-28T13:08:49.211Z/serverless-develop.zip"
}, 
"FunctionName": "serverless-develop-dev-hello", 
"Handler": "handler.hello", …
```
> Add iamRoleARN to serverless.yml

- lib/plugins/aws/deploy/compile/events/kinesis/README.md
Wrong yml style in exemple
Corrected the typo
Check the page
> Small typo in documentation

- docs/01-guide/02-creating-services.md
- docs/01-guide/03-deploying-services.md
- docs/01-guide/04-invoking-functions.md
***Implementing Issue:*** 
Fixing failing links in the docs
Check all links in the documentation if they return 404 or not
> fix cli reference links

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
***Implementing Issue:*** 
Removed squashing from Contrib Guidelines, added a few updates to PR and issue template so users know exactly what to do
> Update issue/pr templates and contributing guide

- docs/02-providers/aws/events/04-sns.md
***Implementing Issue:*** 
Fixed documentation on the SNS event source
Updated doco.
Create an SNS topic and specify it in serverless.yml as an event source.
- corrected the documentation
> - fixed the topic format

- package.json
> Bump version for RC.1 release

- .github/ISSUE_TEMPLATE.md
> Add forum to issue template

- docs/02-providers/aws/examples/using-external-libraries/node/README.md
> Fix typos [skip ci]

- README.md
Fixed an error in the "Hello World" example in README.md
Updated README.md
Walk through the "Hello World" steps in README.md with new change.
> Fix "Hello World" example in README.md

- lib/plugins/create/templates/aws-java-gradle/serverless.yml
- lib/plugins/create/templates/aws-java-maven/serverless.yml
- lib/plugins/create/templates/aws-nodejs/handler.js
- lib/plugins/create/templates/aws-nodejs/serverless.yml
- lib/plugins/create/templates/aws-python/serverless.yml
***Implementing Issue:*** #2057
Updated the `serverless create` templates to reflect  rc1 changes, which includes deprecating `defaults` property and implementing the new variable referencing. I've also made a tiny edit to the node.js handler boilerplate to make it a bit easier to expand as reported by @ac360 a while back.
run `serverless create`
> Updated Serverless Create templates to reflect RC1 changes

- lib/plugins/aws/index.js
***Implementing Issue:*** #2072 
fix broken docs link in aws credentials error message
> updated link to docs

- docs/02-providers/aws/events/01-apigateway.md
- tests/classes/Variables.js
Fixed some typos in docs and unit test strings
> fixed typos

- lib/classes/CLI.js
- lib/classes/PluginManager.js
- tests/classes/PluginManager.js
I made a few small changes that reduce LOC.
- I used ES6 feature in the CLI changes
- I used BbPromise.reduce to do things in sequence instead of having to use array.reduce.
Tests pass and I have done a deployment myself.
> Small cleanup/refactoring

- .all-contributorsrc
This change is intended to fix his link in README.md the next time that is regenerated
This change is intended to fix his link in README.md the next time that is regenerated
> Fix Aaron Boushley's profile link

- docs/02-providers/aws/01-setup.md
Update broken link to Next Step (Create Service)
Changing url
Click on link and check if it goes to corresponding guide.
> Update broken link to Next Step (Create Service)

- docs/02-providers/aws/README.md
- lib/plugins/aws/deploy/compile/functions/index.js
- lib/plugins/aws/deploy/compile/functions/tests/index.js
***Implementing Issue:*** #2146 
Added new property to function object
Add description to lambda to confirm it flows through to aws ui
> Add description property for lambda function

- tests/classes/Utils.js
Add a dedicated test for this method as it has not been covered yet.
Add the test in the `Utils.js`test file.
Run `npm test`.
> Add test for writeFileDir() method

- docs/usage-tracking.md
- lib/classes/Utils.js
- npm-shrinkwrap.json
- package.json
- tests/classes/Utils.js
***Implementing Issue:*** #1958
Extend the tracking method in the utils class with the corresponding things to track which are described in (#1958). Furthermore some helper functionality was introduced to make data such as "memorySize" or "timeout" more accessible.
Tracking is now done on a "per attribute" basis. No (unpredictable) objects are passed over to segment (this will increase the overall security a lot). Additionally a new grouping of the tracking information is introduced so that the analysis of tracking information is way easier.
A `userId` will be generated (if not present) so that information can be associated with anonymized user profiles.
Update the `writeKey` variable in the `Utils.js` class with a valid test key and run a Serverless command. This command should pop up in …
> Update tracking functionality

- package.json
> Bump to RC.2

- docker-compose.yml
- npm-shrinkwrap.json
> Bump dependencies

- .editorconfig
- CONTRIBUTING.md
***Implementing Issue:*** #2180 
Editor config allows IDEs to consistently behave according to the project's proscribed formatting requirements.  This means that fewer spurious white space changes will be committed and that fewer generated white space characters will have to be eliminated by individual developers whose defaults are different than those of the Serverless project.
See ~/.editorconfig
Open an EditorConfig enabled IDE and set global tabs to 4 space chars.  Ensure that EditorConfig is enabled.  Load the Serverless project and while making changes observe whether you get 2 space char indentations or 4.
- [N/A] Write tests
- [N/A] Fix linting errors
- [N/A] Make sure code coverage hasn't dropped
- [N/A] Provide verification config/commands/resources
> Add .editorconfig File & Docs

- docs/01-guide/02-creating-services.md
- docs/03-cli-reference/01-create.md
> Add --name docs

- lib/plugins/create/templates/aws-python/handler.py
> follow pep8 - Python style guide checker

- lib/plugins/tracking/tracking.js
I just changed the content of the 'do-not-track' file to be coherent with the action/result.
> wrong description

- tests/classes/CLI.js
***Implementing Issue:*** #1391
I added some really basic integration tests for --help.
The tests call the CLI with --help and verify that the output contains some tokens.
`npm test`
> add Integration tests for CLI printing --help

- .github/PULL_REQUEST_TEMPLATE.md
Improved PR template so users have more examples what validation steps to add
[raw template](https://raw.githubusercontent.com/serverless/serverless/77f3133bf4b33bdc263f423f58087e81dbbbaccb/.github/PULL_REQUEST_TEMPLATE.md)
[rendered template](https://github.com/serverless/serverless/blob/77f3133bf4b33bdc263f423f58087e81dbbbaccb/.github/PULL_REQUEST_TEMPLATE.md)
> Improve PR template for clearer validation data

- docs/01-guide/05-event-sources.md
- docs/01-guide/07-removing-services.md
- docs/02-providers/aws/README.md
- docs/README.md
***Implementing Issue:*** #2171 
Fixed documentation links
Check links manually
> Remove reference to `readme.md` to help fix links

- docs/01-guide/09-installing-plugins.md
> Remove broken link

- docker-compose.yml
- lib/plugins/create/create.js
- lib/plugins/create/templates/aws-scala-sbt/build.sbt
- lib/plugins/create/templates/aws-scala-sbt/event.json
- lib/plugins/create/templates/aws-scala-sbt/project/assembly.sbt
- lib/plugins/create/templates/aws-scala-sbt/project/plugins.sbt
- lib/plugins/create/templates/aws-scala-sbt/serverless.yml
- lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Handler.scala
- lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Request.scala
- lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Response.scala
- lib/plugins/create/tests/create.js
- tests/templates/integration-test-template
- tests/templates/test_all_templates
***Implementing Issue:*** #2217
Utilized the existing code for templates to create a new `aws_scala_sbt` template. 
Added a Hello World example in Scala along with a basic sbt setup. The sbt build is run by the command `sbt assembly`. 
Updated tests and `docker-compose.yml`. 
Updated tests seem to cover this. 
Let me know if I should update the [Create docs](https://github.com/serverless/serverless/blob/master/docs/03-cli-reference/01-create.md) or any others.
> add aws-scala-sbt template for scala lambdas

- lib/classes/Service.js
- tests/classes/Service.js
***Implementing Issue:*** #2226
This was a pretty straightforward mistake, I added a test to cover against regression.
> fix #2226 non-aws providers throw an error

- lib/classes/Service.js
- lib/plugins/aws/deploy/compile/events/apiGateway/index.js
- lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/validate.js
Quick merge fix for the following PR:
***Implementing Issue:*** #2090 
> Quick fix for #2090

- LICENSE.txt
> update license year

- docs/02-providers/aws/events/01-apigateway.md
Fixed docs that were out of sync due to this commit:
https://github.com/serverless/serverless/commit/a5e3c3197474f1eac2672802132ef7c0a26db6a4
This will help confusion like in this issue:
https://github.com/serverless/serverless/issues/1822
> Updated docs: Changed the RestApiId logical name

- README.md
N/A
Using serverless@v1-rc.1
https://github.com/99xt/serverless-react-boilerplate
https://github.com/99xt/serverless-dynamodb-local/tree/v1
serverless-react-boilerplate focuses on offline development with Lambda, API Gateway and Dynamodb. The boilerplate consists of CRUD operations for a To-do application and a simple react web client that utilizes the api.
> Added serverless-react-boilerplate project & serverless-dynamodb-local plugin to readme

- docs/02-providers/aws/01-setup.md
> fix link to variables page

- docs/01-guide/05-event-sources.md
- lib/plugins/create/templates/aws-java-gradle/serverless.yml
- lib/plugins/create/templates/aws-java-maven/serverless.yml
- lib/plugins/create/templates/aws-nodejs/handler.js
- lib/plugins/create/templates/aws-nodejs/serverless.yml
- lib/plugins/create/templates/aws-python/handler.py
- lib/plugins/create/templates/aws-python/serverless.yml
- lib/plugins/create/templates/aws-scala-sbt/serverless.yml
***Implementing Issue:*** #2256
This PR adds the new handlers so that they work well with the recent API Gateway PROXY implementation (see: #2185).
Just added the new handler files.
`serverless create -t aws-nodejs -p my-new-service`
`serverless deploy`
`curl <url>`
> Update handler files

- docs/02-providers/aws/events/01-apigateway.md
> docs(CORS): Reminder to set CORS headers in code when using lambda-proxy

- README.md
Added Craftship as a consultancy to README
Added Link to README
> Add Craftship Consultancy

- docs/01-guide/03-deploying-services.md
- docs/01-guide/04-invoking-functions.md
fix broken links in documentation "Guide"
They might be broken at: 5f48d56f7dac095883469858d998fc4a9041f21b
update links
see filenames in https://github.com/serverless/serverless/tree/master/docs/03-cli-reference
> fix broken links in Guide

- tests/classes/Utils.js
***Implementing Issue:*** #1626 
Adds test coverage for the tracking functionality. Stubs a `fetch` request with the help of a proxyquire.
Added a stub for the `fetch` method and mocked a service.
Run `npm test`
> Add tests for tracking functionality

- lib/classes/PluginManager.js
We took too long to merge #2156 and there was a conflict. Rebasing to merge faster.
> Merging #2156

- docs/02-providers/aws/01-setup.md
***Implementing Issue:*** Comments [here](https://github.com/serverless/serverless/pull/2229#discussion_r82570969) & [here](https://github.com/serverless/serverless/pull/2229#discussion_r82570840) just prior to merge of https://github.com/serverless/serverless/pull/2229
`vars` => `custom`
remote "Et Cetera" and empty line
- [N/A] Write tests
- [N/A] Make sure code coverage hasn't dropped
- [N/A] Provide verification config/commands/resources
> Review Followup

- docs/usage-tracking.md
***Implementing Issue:*** #2279
Add /update the tracking documentation.
Updated the .md file.
Go to the tracking documentation.
> Add in-depth docs for tracking

- docs/01-guide/06-custom-provider-resources.md
> fix indentation in example provider resource

- docs/02-providers/aws/01-setup.md
***Implementing *Comment*:*** From [@pmontrasio's comment](https://github.com/serverless/serverless/issues/1736#issuecomment-252412054)
> The guide didn't explain what a service directory is yet and how to create a service.
Modify the docs to have users configure to use their credentials (and add profile declaration in case they're already set up with a profile) but then proceed in the workflow, next creating their first service.
Read and consider changes.
- [N/A] Write tests
- [N/A] Fix linting errors
- [N/A] Make sure code coverage hasn't dropped
- [N/A] Provide verification config/commands/resources
> Clarify Quick Setup Docs

- README.md
> Update read me for add serverless v1 project

- RELEASE_CHECKLIST.md
Before Releasing a new version of Serverless we want to make sure we know which PRs have been merged since a last release. The command helps with getting this list and creating a Changelog.
> Add command to get all merged PR's from git log

- docs/01-guide/11-environment-variable-handling.md
- docs/01-guide/README.md
Provide documentation about environment variables for different languages. At the moment we don't support env vars natively, but this will help people.
> Add environment variable docs

- docs/02-providers/aws/examples/cron/README.md
- docs/02-providers/aws/examples/cron/node/README.md
- docs/02-providers/aws/examples/cron/node/handler.js
- docs/02-providers/aws/examples/cron/node/serverless.yml
Close https://github.com/serverless/serverless/issues/2304
> add schedule cron example

- README.md
Adds a table of example services to the README file.
Just updated the `README.md` file.
Open up the `README.md` file and look through it.
> Add example services to README

- docs/01-guide/02-creating-services.md
Note about reusable services.
Update `README.md` file.
Take a look at the updated `.md` file.
> Add note about Serverless services in creating-services README

- docs/usage-tracking.md
- lib/classes/Utils.js
- tests/classes/Utils.js
> Revert tracking information

- docs/01-guide/05-event-sources.md
- lib/plugins/create/templates/aws-nodejs/handler.js
- lib/plugins/create/templates/aws-python/handler.py
- tests/integration_test.js
Update the handler files so that they work out of the box when a user adds a `http` event.
Switched default handlers once again.
Create a new service, invoke the function, add a HTTP event, curl the endpoint.
> Update handler files for better onboarding

- package.json
> Bump 1.0.0

- Changelog.md
Created the Changelog for the 1.0.0 release
> Add Changelog for 1.0.0 release

- docs/01-guide/08-serverless-variables.md
- docs/01-guide/12-serverless-yml-reference.md
- docs/01-guide/README.md
- docs/02-providers/aws/README.md
- docs/v0-v1-comparison.md
Users need some help to understand the differences between 0.x and 1.x and where to start to transfer their services. As 1.x is a complete rewrite we can't really give a good and comprehensive in-depth guide to upgrade, because everything is different. This docs page tries to make users undrestand where we're going and then pushes them to go through the general guide because it will show them how features work and they will easily understand how to upgrade to 1.x then.
To write that guide I also needed to introduce a serverless.yml reference to link to.
> Add comparison between 0.x and 1.x

- README.md
Add a short description why we're named Serverless to answer that regular question.
> Add Serverless Name description

- lib/plugins/create/create.js
- lib/plugins/deploy/deploy.js
- lib/plugins/info/info.js
- lib/plugins/install/install.js
- lib/plugins/invoke/invoke.js
- lib/plugins/logs/logs.js
- lib/plugins/remove/remove.js
- lib/plugins/tracking/tracking.js
Standardize commands description
Before: 
- removed dots from some description
- verbs in the same form
After
> standardize commands decription

- package.json
Remove unnecessary Python reference in `package.json`.
Remove unnecessary Python reference in `package.json`.
Run `npm link`.
> Remove Python reference in package.json

- docs/03-cli-reference/01-create.md
One simple document change
Add `aws-scala-sbt` to list
> Update supported template document

- RELEASE_CHECKLIST.md
- npm-shrinkwrap.json
- package.json
> Bump Version to 1.0.2 and update shrinkwrap and RELEASE Checklist

- RELEASE_CHECKLIST.md
> Add task to Release Checklist for included files

- Changelog.md
- RELEASE_CHECKLIST.md
> 1.0.1 and 1.0.2 changelog with Release checklist updates

- docs/02-providers/aws/02-iam.md
***Implementing Issue:*** #2028
> Add iamRoleARN statment docs

- docs/02-providers/aws/01-setup.md
- docs/04-extending-serverless/01-creating-plugins.md
- docs/04-extending-serverless/02-creating-provider-plugins.md
- docs/framework-statistics.md
***Implementing Issue:*** #2380
Revert absolute links back to be relative. @DavidWells will take care of the link transformation for the docs page in the docs build process.
Updated all the links.
Browse through the documentation.
> Closes #2380 - Update doc links to be relative

- package.json
Add glob to remove *.test files from code coverage.
Add line test section in `package.json`.
Run tests.
- Make sure code coverage hasn't dropped --> Will drop
> Remove *.test files from test coverage

- lib/classes/CLI.js
Fixes the recently introduced linting error (because of an update in the linter).
Fixed the line which makes the linting fail.
Run `npm run lint`
> Fix the liniting error which occurred because of linter updates

- docs/01-guide/02-creating-services.md
- lib/classes/CLI.js
- lib/plugins/create/templates/aws-java-gradle/.gitignore
- lib/plugins/create/templates/aws-java-maven/.gitignore
- lib/plugins/create/templates/aws-nodejs/.gitignore
- lib/plugins/create/templates/aws-python/.gitignore
- lib/plugins/create/templates/aws-scala-sbt/.gitignore
- lib/plugins/create/tests/create.js
***Implementing Issue:*** #2343 
Add .gitignore in every template, then add .serverless and meta stuff to it.
> Add .gitignore file in every template

- docs/02-providers/aws/01-setup.md
Implemented simple documentaiton fix
Added a single $ to the templating
Look at the generated documentation
> add $ to templating

- CHANGELOG.md
> Add breaking changes to 1.0.0 release

- docs/02-providers/aws/01-setup.md
Took me a while to figure out why my new service wouldn't deploy based on the documentation.
> Add missing $ to docs/02-providers/aws/01-setup.md

- lib/classes/Utils.js
CI System support for stats.
***Implementing Issue:*** #2259 
Add a check if the CI environment variable is set.
Run the tests.
> Update stats to support CI systems

- tests/integration/all.js
- tests/integration/aws/sns/multiple-topics-multiple-functions/service/handler.js
- tests/integration/aws/sns/multiple-topics-multiple-functions/service/serverless.yml
- tests/integration/aws/sns/multiple-topics-multiple-functions/tests.js
- tests/integration/aws/sns/multiple-topics-single-function/service/handler.js
- tests/integration/aws/sns/multiple-topics-single-function/service/serverless.yml
- tests/integration/aws/sns/multiple-topics-single-function/tests.js
- tests/integration/aws/sns/single-topic-multiple-functions/service/handler.js
- tests/integration/aws/sns/single-topic-multiple-functions/service/serverless.yml
- tests/integration/aws/sns/single-topic-multiple-functions/tests.js
- tests/integration/aws/sns/single-topic-single-function/service/handler.js
- tests/integration/aws/sns/single-topic-single-function/service/serverless.yml
- tests/integration/aws/sns/single-topic-single-function/tests.js
Migrate the SNS integration tests from the integration-test-suite repository.
Copied over the tests and modified them slightly so that they work in the context of the whole "complex" integration test suite.
Simply run `serverless run complex-integration-test`
> Migrate SNS integration tests

- docs/01-guide/02-creating-services.md
Fixed broken link in the context of Serverless Documentation.
https://serverless.com/framework/docs/guide/creating-services/
Replaced a relative path with an absolute path to github project.
Please look at the generated documentation.
> fix broken link in the context of Serverless Documentation

- .github/PULL_REQUEST_TEMPLATE.md
> Close issues automatically from PR

- .github/PULL_REQUEST_TEMPLATE.md
> User Upper Case

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> Bump to 1.0.3

- docs/03-cli-reference/03-deploy.md
- docs/03-cli-reference/06-info.md
> fix wording

- docs/01-guide/README.md
Changed typo.
The above aren't applicable 
> Change to 'GitHub'

- docs/02-providers/aws/README.md
fix broken links in the docs. Leftover from the merge of DynamoDB- and Kinesis streams event docs.
Removed the two old links and added a new link to the 'DynamoDB / Kinesis Streams' event doc.
leftover from the merge of DynamoDB- and Kinesis streams event docs.
> fix broken links

- docs/providers/aws/guide/intro.md
> Fix in documentation (Spelling + language)

- docs/providers/aws/guide/services.md
> Fix typo in docs

- docs/providers/aws/guide/services.md
Fixed documentation language problems.
> Fix documentation problems

- README.md
Add link in README to ES6+Jest boilerplate for creating Serverless services
> add es6+jest boilerplate link

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #2500
Allow strings or numbers to populate into variables.
* Write serverless.yml as follow
```yaml
iamRoleARN: arn:aws:iam::${opt:account}:role/lambda_full_access
```
* Excute as follow
```
sls deploy --account YourAWSaccountNumber
```
or this:
```
sls deploy --account 'YourAWSaccountNumber'
```
or this:
```
sls deploy --account "YourAWSaccountNumber"
```
All will be success.
> fixed issue 2500

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #2081, #2522
Added a check for empty object value in `overwrite` function and a test.
Setup the configurations of services, described in issues #2081, #2522 and see if generated configurations are correct and all variables are resolved.
> fix overwriting undefined variables #2081, #2522

- docs/providers/aws/guide/events.md
> Fix Documentation: Minor spelling fix

- docs/providers/aws/guide/functions.md
> added lambda description field to functions.md

- docs/providers/aws/events/schedule.md
Resolving conflict from https://github.com/serverless/serverless/pull/2424.
> add disabled cron example

- README.md
Added the Scala port of CRUD Service and updated its link in README.
Implemented Scala port of CRUD Service here - https://github.com/jahangirmohammed/serverless-crud-scala . Motivation behind this is - I didn't find many or any? decent examples around Scala using Serverless.
Implemented by using - 1. sbt assembly for packaging. 2. AWS lambda 3. API Gateway. 4. DynamoDb.
By installing the service and running CRUD operations against them.
> Scala port CRUD Service readme

- lib/plugins/aws/deployFunction/index.js
- npm-shrinkwrap.json
- package.json
Before
```
Serverless: Deploying function: hello...
Serverless: Uploading function: hello (0MB)...
Serverless: Successfully deployed function: hello
```
after
```
Serverless: Deploying function: hello...
Serverless: Uploading function: hello (335 B)...
Serverless: Successfully deployed function: hello
```
Using https://github.com/avoidwork/filesize.js#examples
> show package size in human readable way

- README.md
Added EPX Labs to consultants list
I opened the readme.md in Emacs and added some markdown
By opening the Readme.md or git diff the changes
> adds EPX Labs to consultants list

- docs/providers/aws/guide/plugins.md
A minor fix to the documentation
This is a minor correction to the docs
This is a minor correction to the docs
Corrects a minor paragraph typed twice.
> Minor Grammar Change

- docs/providers/aws/cli-reference/invoke.md
- lib/classes/Utils.js
- lib/classes/Variables.js
- lib/plugins/Plugins.json
- lib/plugins/aws/deploy/lib/createStack.js
- lib/plugins/aws/deploy/tests/generateArtifactDirectoryName.js
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/tests/index.js
- lib/plugins/invoke/invoke.js
- tests/all.js
Closes #2531 
Add `serverless invoke local -f hello -p event.json` plugin for running lambda locally.
Added a `local` subcommand to the `invoke` command.
I know you're lazy, so just copy/run the following commands/test cases on any service with a hello function: 😛 
- `echo '{"event": {"hello": "world"}, "context": {"arn": "abc:xyz"}}' >> event.json && serverless invoke local -f hello -p event.json`
- `serverless invoke local -f hello`
> added invoke local plugin

- README.md
Please add my new plugin to the readme
> Add browserify plugin

- docs/providers/aws/cli-reference/create.md
- docs/providers/aws/guide/plugins.md
- lib/classes/PluginManager.js
- lib/plugins/create/create.js
- lib/plugins/create/templates/plugin/index.js
- lib/plugins/create/tests/create.js
- tests/integration/all.js
- tests/integration/general/local-plugins/service/.serverless_plugins/one.js
- tests/integration/general/local-plugins/service/.serverless_plugins/two/index.js
- tests/integration/general/local-plugins/service/handler.js
- tests/integration/general/local-plugins/service/serverless.yml
- tests/integration/general/local-plugins/tests.js
Closes #2130 
Fixup and Merge of 2130
> Merging Pr 2130

- README.md
Updating readme, adding serverless-header-function plugin for Serverless@0.5
The plugin run a pre-specified js script for every Serverless hook, e.g `function-pre-run`
> Add [Serverless Header Function] plugin to Readme

- docs/providers/aws/cli-reference/deploy.md
- docs/providers/aws/cli-reference/rollback.md
> Add Rollback and deploy list docs back in

- lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js
- lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js
- lib/plugins/aws/deploy/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/authorizers.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/methods.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/permissions.js
- lib/plugins/aws/deploy/compile/events/apiGateway/tests/validate.js
Splitting up: #2262
This is the refactoring of apiGateway authorizers and permissions.
`npm test` passes. I've also ran most of the integration tests.
> refactor apiGateway authorizers and permissions

- CHANGELOG.md
> Fix github changelog links

- lib/plugins/aws/provider/awsProvider.js
Closes #2597 
Updates link to AWS credential setup guide.
> Updates git.io URL to aws credential setup

- lib/plugins/aws/deploy/tests/uploadArtifacts.js
- lib/plugins/aws/deployFunction/tests/index.js
> add tests for showing artifact size

- docs/providers/aws/guide/packaging.md
- lib/plugins/create/templates/aws-python/serverless.yml
- lib/plugins/create/templates/aws-scala-sbt/serverless.yml
Closes #12345
Update the docs so that the usage for `exclude` and `include` is explained in a correct way.
Update the corresponding `.md` file.
Read the docs.
> Update docs about exclude and include usage

- docs/providers/aws/events/apigateway.md
> Add stage variable to API Key docs

- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
Trivial fix to the bug in #2628
> fix for empty plugins property in serverless.yml

- docs/providers/aws/guide/deploying.md
Closes #12345
Corrected minor typo in docs
trivial change
trivial change
> Minor typo in AWS Deploying Guide

- docs/providers/aws/guide/functions.md
In a recent PR some documentation was lost including timeout and other function parameter docs. Readding them here.
> Add timeout and other additional function parameter docs

- docs/providers/aws/guide/resources.md
> added LogGroup to resources logical IDs table docs

- docs/providers/aws/guide/services.md
> Readd missing docs for provider config

- docs/providers/aws/events/apigateway.md
Fix invalid examples in docs and update code so that the overall used code convention is used.
Update the API Gateway docs.
Read the API Gateway docs.
> Fix API Gateway docs to add integration type and apply code conventions

- docs/providers/aws/guide/iam.md
Add comma after conjunctive adverbs
> Update IAM Guide

- lib/plugins/aws/tests/naming.js
Fixes spacing for better readability.
Added spaces before `describe` blocks.
Run the test with `npm test`.
> Fix spacing in naming.js test file

- README.md
- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/version.md
Refs #2713 and #2714
Replace the other ellipsis as well.
Replace ellipsis with three dots.
Just look through the code.
> Replace more ellipsis characters with dots

- docs/providers/aws/guide/README.md
Minor fix to link in documentation.
> Fixed broken link to introduction.

- docs/providers/aws/guide/functions.md
I got confused by the explanation on how to use env vars. Therefor I switched the second example and updated the wording to make sure overwriting is optional.
Updated the markdown files
Check the docs :)
> improve explaination

- tests/integration/all.js
- tests/integration/aws/general/environment-variables/service/handler.js
- tests/integration/aws/general/environment-variables/service/serverless.yml
- tests/integration/aws/general/environment-variables/tests.js
Closes #2751 
Adds a test for our `complex-integration-test` suite.
Just added the test.
Run `npm run complex-integration-test`.
> Add environment variables integration test

- lib/plugins/aws/deploy/compile/functions/tests/index.js
Unit test which checks if environment variables defined at the `provider` level can be overwritten by one defined at the `function` level.
Added a unit test.
Run `npm test`.
> Add test for overwriting environment variables

- README.md
Added a link to a service for calling PHP functions from the lambda.
There's a corresponding blog post here http://blog.zerosharp.com/the-serverless-framework-and-php/
> Added the PHP service to the README.

- tests/integration/all.js
- tests/integration/aws/s3/multiple-events-multiple-functions-multiple-buckets/service/handler.js
- tests/integration/aws/s3/multiple-events-multiple-functions-multiple-buckets/service/serverless.yml
- tests/integration/aws/s3/multiple-events-multiple-functions-multiple-buckets/tests.js
- tests/integration/aws/s3/multiple-events-multiple-functions-single-bucket/service/handler.js
- tests/integration/aws/s3/multiple-events-multiple-functions-single-bucket/service/serverless.yml
- tests/integration/aws/s3/multiple-events-multiple-functions-single-bucket/tests.js
- tests/integration/aws/s3/multiple-events-single-function-single-bucket/service/handler.js
- tests/integration/aws/s3/multiple-events-single-function-single-bucket/service/serverless.yml
- tests/integration/aws/s3/multiple-events-single-function-single-bucket/tests.js
- tests/integration/aws/s3/single-event-single-function-single-bucket/service/handler.js
- tests/integration/aws/s3/single-event-single-function-single-bucket/service/serverless.yml
- tests/integration/aws/s3/single-event-single-function-single-bucket/tests.js
- tests/utils/index.js
Closes #2733 
Migrate the S3 integration tests.
Copied over the tests from the integration test suite and updated them accordingly.
Run `npm run complex-integration-test`.
> Migrate S3 integration tests

- lib/plugins/create/templates/aws-java-gradle/serverless.yml
- lib/plugins/create/templates/aws-java-maven/serverless.yml
- lib/plugins/create/templates/aws-nodejs/serverless.yml
- lib/plugins/create/templates/aws-python/serverless.yml
- lib/plugins/create/templates/aws-scala-sbt/serverless.yml
Add examples to `create` templates as mentioned by @braahyan in https://github.com/serverless/serverless/pull/2748
Add commented out examples to `serverless.yml` templates.
Look at the templates
> Add environment variable config to templates

- lib/plugins/aws/deploy/lib/mergeIamTemplates.js
> removed cflogs deprecation notice

- npm-shrinkwrap.json
- package.json
> 1.2.0 version bump

- RELEASE_CHECKLIST.md
> add revert segment write key

- npm-shrinkwrap.json
- package.json
> v1.2.1 release

- lib/classes/Error.js
Closes #1690
Enriches the error message on how to set the operating system `SLS_DEBUG` environment variable.
Updated the error message with more information.
Force an error to pop up.
> Update SLS_DEBUG info message

- lib/plugins/aws/info/index.js
Somehow a linting violation got in which is causing [other PRs](https://github.com/serverless/serverless/pull/2799) to fail unnecessarily
I fixed the linting errors
`npm run lint` and CI passes
> fix Linting

- README.md
Adding reference to plugin list
> Adding reference to plugin list

- README.md
I proceeded according to the procedure, but there was a part that failed.
1. run `serverless create --template aws-nodejs --path my-service` referring [Create a Service](https://github.com/serverless/serverless#create-a-service)
2. run `serverless deploy -v` referring [Deploy a Service](https://github.com/serverless/serverless#deploy-a-service)
3. run `serverless deploy function -f myfunction` referring [Deploy Function](https://github.com/serverless/serverless#deploy-function)
Following error occured.
```
$ serverless deploy function -f myfunction
Serverless: Deploying function: myfunction...
Function "myfunction" doesn't exist in this Service
Docs: …
```
> Fix deploy function command at quick start.

- lib/plugins/aws/invoke/index.js
- lib/plugins/aws/invoke/index.test.js
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Closes #2685
WIP – Waiting on the gentleman who posted the issue to confirm this fix.
> Fix for #2685

- docs/providers/aws/guide/intro.md
Fix yaml comments in intro
Changed `//` to `#`
read yaml spec?
> Fix yaml comments in intro

- code_of_conduct.md
Discussed it with Austen. We want to make sure no complaints fall through.
> update contact to reach out to the team

- npm-shrinkwrap.json
- package.json
> 1.3 version bump

- docs/providers/aws/cli-reference/rollback.md
Fix copy of the "rollback" command guide.
***Is this ready for review?:***
It was "The stage in your service you want to display information about", probably a copy and paste gone wrong. :)
> Fix the --timestamp parameter description

- npm-shrinkwrap.json
Closes #2811
```
npm prune --production
npm shrinkwrap
```
> update shrinkwrap with production only packages

- RELEASE_CHECKLIST.md
Refs #2811
Add a note to use `npm prune --production` before shrinkwrapping.
Updated the corresponding `.md` file.
Read the `.md` file.
> Update RELEASE_CHECKLIST.md file

- lib/plugins/aws/lib/updateStack.js
- lib/plugins/aws/lib/updateStack.test.js
Closes https://github.com/serverless/serverless/issues/2826
> Add CAPABILITY_NAMED_IAM to initial stack creation. Fix for #2826

- lib/classes/Utils.js
Add context of where segment is running from. CLI or from https://github.com/serverless/dashboard
> Add context for segment

- lib/classes/Utils.js
Closes #2880 
Add detection of the Jenkins CI system.
Check for a Jenkins specific env variable.
set process.env.JENKINS_URL to something
> Add detection of Jenkins

- lib/classes/Service.js
- lib/classes/Service.test.js
Closes #2828
Array.reduce ;)
tests pass
> add Support for resources as an array

- lib/plugins/aws/metrics/awsMetrics.js
This PR will fix aws metrics plugin lint issue.
Closes #12345
I refactored the code just a little bit so that the intends matches lint rules.
Execute `npm run lint` and no errors should exists.
> fix aws metrics plugin lint issues

- docs/README.md
- docs/providers/aws/cli-reference/deploy-function.md
- docs/providers/aws/cli-reference/deploy-list.md
- docs/providers/aws/cli-reference/deploy.md
- docs/providers/aws/cli-reference/info.md
- docs/providers/aws/cli-reference/invoke-local.md
- docs/providers/aws/cli-reference/invoke.md
- docs/providers/aws/cli-reference/logs.md
- docs/providers/aws/cli-reference/metrics.md
- docs/providers/aws/cli-reference/remove.md
- docs/providers/aws/cli-reference/rollback.md
- docs/providers/aws/cli-reference/slstats.md
> separate commands into separate pages

- docs/providers/aws/guide/deploying.md
> added a note about deploying function versions

- bin/serverless
- lib/plugins/aws/invoke/index.js
- lib/plugins/aws/invoke/index.test.js
Based on https://github.com/serverless/serverless/pull/2836
```
sls invoke -f ...
echo $?
```
> Fix invoke exit code

- docs/README.md
> Fix examples link in docs

- docs/providers/aws/guide/serverless.yml.md
TL;DR: Enrich docs - add "Outputs" section
Adds the "Outputs" section of the CFT to the "everything" example `serverless.yml` documentation.  That example appears to propose to show all the things that can be added to serverless.yml but does not show the valid addition of an "Outputs" section, so this PR adds one.
Edit to docs.
Ask yourself, do the changes make sense and is it a valid addition to a serverless.yml?
> Add "Outputs" Section Docs

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> 1.4 version bump

- docs/providers/aws/events/alexa-skill.md
Added a hint to the Alexa Skill guides
> add hint to the alexa guides

- docs/providers/aws/guide/variables.md
> added note about variables in values

- lib/plugins/aws/deploy/compile/events/apiGateway/lib/method/integration.js
Follow up PR of #2902 Closes #2901
> Fix VTL string escaping

- docs/providers/aws/guide/plugins.md
Update  the plugin document.
I think that instead of specifying a direct proviver name, we are using the `getProvider` function, but is I correct?
https://github.com/serverless/serverless/commit/df7692ac809ead5febe1f59645ad9c3c901dcd3a
> update plugin document

- lib/Serverless.test.js
- lib/classes/CLI.test.js
Some minor updates to increase the test coverage a little bit...
> Increase test coverage

- README.md
Added Slack App to the list of services
Added a link to the [README](README.md) pointing to the service repo
`serverless install --url https://github.com/johnagan/serverless-slack-app`
> Added Slack App Service

- lib/plugins/create/templates/aws-csharp/build.sh
The "release" folder needs to be lowercase, not "Release".
Closes #12345
> Need to create the right case

- docs/providers/aws/examples/hello-world/csharp/README.md
- lib/plugins/create/create.test.js
- lib/plugins/create/templates/aws-csharp/build.ps1
- lib/plugins/create/templates/aws-csharp/build.sh
Closes #3018 
I added a `build.ps1` that mirrors the behavior of the `build.sh` bash script. Of note, the `ZipDirectory` method doesn't allow creating a zip in the file that it's zipping, so I create it in root and then copy it back to the publish.
On a Windows machine, run
```
serverless create -t aws-csharp
./build.ps1
serverless invoke -f hello
```
> add build.ps1 and update tests&docs

- docs/providers/aws/events/apigateway.md
Closes #2840 
Update the docs about API keys and usage plan usage.
Updated the docs.
Read the corresponding `.md` files.
> Update API Keys docs

- README.md
* Added Red Badger as a consultancy to README
* Added Link to README
> Add Red Badger to the consultancy list

- README.md
Added Swift service to Readme file. The linked repo contains a fully featured project template to develop Lambda functions in Swift and deploy them with Serverless.
Added link to service repo.
Run `serverless install --url https://github.com/choefele/swift-lambda-app`
N/A
> Add Swift Service

- README.md
To add community examples add them to https://github.com/serverless/examples/blob/master/community-examples.json
To add plugins to the readme add them to https://github.com/serverless/plugins/blob/master/plugins.json
The readme tables are automatically synced with the remote files when `npm run docs` is ran
> update examples and plugins and add note on where to update data

- package.json
> Add pre- and postinstall scripts to package

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing v1.5.0

- lib/classes/Utils.js
- lib/classes/Utils.test.js
Closes #3001
Add detection of Docker containers for SlStats.
Check for the `cgroup` file.
> Add Docker detection

- docs/providers/aws/examples/hello-world/python/README.md
Updated Python hello world example. Added missing 'Create a service' section, and made the rest of the guide consistent with the Node.JS version.
> Update Python hello wold example to be consistent with Node.js

- RELEASE_CHECKLIST.md
- scripts/generate-release-contributors-list
Add a script which can be used so that a list of contributors of the last release will be generated.
/cc @mthenw 
> Add release contributors list script

- docs/providers/aws/guide/workflow.md
Removed invalid argument for deploy function example in the workflow doc.
> Remove invalid argument in workflow doc

- docs/providers/aws/examples/hello-world/csharp/serverless.yml
- lib/plugins/create/templates/aws-csharp/serverless.yml
- tests/templates/test_all_templates
> Fix dotnet path casing

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing v1.5.1

- docs/providers/aws/guide/iam.md
Just added a few grammar and punctuation modifications for a bit smother reading in the IAM sections.
> Minor grammar and punctuation tweaks

- lib/classes/Service.test.js
Fixing the unit test which causes all tests to break...
> Fix broken unit test after merging #2434

- scripts/generate-readme.js
- scripts/integration-test-cleanup.js
- scripts/postinstall.js
- scripts/preuninstall.js
For better Node.js version support.
> Add missing "use strict" definitions

- package.json
> added homepage to package.json

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing v1.6

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing 1.6.1

- docs/providers/aws/cli-reference/invoke-local.md
Add a paragraph to (hopefully) clarity the mechanism behind AWS roles and permissions, while we come up with a better implementation (see issue #2903)
Temporary clarification while we find a better way to deal with #2903
> permissions details

- docs/providers/aws/guide/intro.md
Didn't make sense before: the endpoint is not an event, a request to the endpoint is.
Added a word to make api gateway events description make sense
> Minor docs readability improvement

- docs/providers/aws/events/sns.md
> Fixes minor typo in sns.md

- docs/providers/openwhisk/guide/deploying.md
> Spelling fix

- RELEASE_CHECKLIST.md
- lib/classes/CLI.js
- lib/classes/CLI.test.js
Closes #3211
Added functionality for listing all the upcoming breaking changes in the CLI. This is going to be one of each release steps.
Added a method to the CLI that logs all the breaking changes. User can opt-out by setting the `SLS_IGNORE_WARNING` env var. I've also updated the release checklist to include a step where we update the upcoming breaking changes list on every release.
- open the CLI class file and add some strings to the `breakingChanges` array.
- run any serverless command and you should see the list.
- opt out by setting the `SLS_IGNORE_WARNING` env var
> logging upcoming breaking changes

- lib/classes/CLI.test.js
- lib/classes/Utils.js
> Remove unneeded code

- scripts/docker-cleanup
Just a little convenience script to cleanup all containers and images.
> Add Docker cleanup script

- docs/README.md
> Add Azure docs overview page

- package.json
> Update OpenWhisk naming

- lib/plugins/aws/lib/monitorStack.test.js
Corrected a simple typo.
I'm looking into mimicking this monitor functionality (b/c doing it synchronously like that with the pretty logging is handy) and open sourcing the result. In digging into the test, I noticed the typos. Boy scout rule.
Not related to any ticket.
`npm test` that bad boy.
> A simple typo correction

- lib/plugins/package/lib/zipService.js
> Quickfix too many files open

- CHANGELOG.md
- lib/classes/CLI.js
- npm-shrinkwrap.json
- package.json
> releasing v1.8

- tests/integration/aws/iot/multiple-rules-multiple-functions/service/handler.js
- tests/integration/aws/iot/multiple-rules-multiple-functions/service/serverless.yml
- tests/integration/aws/iot/multiple-rules-multiple-functions/tests.js
- tests/integration/aws/iot/multiple-rules-single-function/service/handler.js
- tests/integration/aws/iot/multiple-rules-single-function/service/serverless.yml
- tests/integration/aws/iot/multiple-rules-single-function/tests.js
- tests/integration/aws/iot/single-rule-multiple-functions/service/handler.js
- tests/integration/aws/iot/single-rule-multiple-functions/service/serverless.yml
- tests/integration/aws/iot/single-rule-multiple-functions/tests.js
- tests/integration/aws/iot/single-rule-single-function/service/handler.js
- tests/integration/aws/iot/single-rule-single-function/service/serverless.yml
- tests/integration/aws/iot/single-rule-single-function/tests.js
- tests/utils/index.js
I implemented the integration test of  iot event.
Closes #2954 
I created `iot` directory in the following directory and implemented test code in it.
https://github.com/serverless/serverless/tree/master/tests/integration/aws
Please run `npm run complex-integration-test`
> add integration test for iot event

- tests/integration/aws/iot/multiple-rules-multiple-functions/service/serverless.yml
- tests/integration/aws/iot/multiple-rules-single-function/service/serverless.yml
- tests/integration/aws/iot/single-rule-multiple-functions/service/serverless.yml
- tests/integration/aws/iot/single-rule-single-function/service/serverless.yml
> Remove legacy cfLogs usage

- docs/providers/aws/guide/resources.md
Added default resource overriding guide with normalizedFunctionName description
Added description to `/docs/providers/aws/guide/resources.md`
Just check the content.
>  Added default resource overriding guide with normalizedFunctionName

- package.json
> Update coveralls dependency

- README.md
Updated README.md with latest plugins and examples
`npm run docs`
See README.md
> Update README.md with latest plugins and examples

- CHANGELOG.md
- lib/classes/CLI.js
- npm-shrinkwrap.json
- package.json
> releasing v1.9

- lib/plugins/aws/provider/awsProvider.test.js
> Restore global setTimeout to get into a clean state again

- lib/classes/Error.js
Adding links for more help
```
Forums:        forum.serverless.com
Chat:          gitter.im/serverless/serverless
```
> add forums and chat links to errors

- package.json
Temporary solution - Closes #3251
> Remove preuninstall script

- docs/providers/aws/guide/iam.md
- docs/providers/aws/guide/plugins.md
Closes #XXXXX
This change fixes a few typos and example code/description mismatches in the AWS documentation. 
Updated:
* docs/providers/aws/guide/iam.md
* docs/providers/aws/guide/plugins.md
View the AWS Guide IAM and Plugins md files.
> Fix AWS guide documentation typos and examples

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing v1.10

- docs/providers/aws/guide/credentials.md
changed file name serverless.yaml to serverless.yml
Closes #XXXXX
> fixed file name typo

- lib/Serverless.js
- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
- npm-shrinkwrap.json
- package.json
Updates the `serverless-alpha` detection so that it can detect if the plugin is locally installed. Furthermore it's capable to work if e.g. Node.js is installed via homebrew.
/cc @eahefnawy @brianneisler
> Update serverless-alpha detection

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing patch

- docs/providers/aws/guide/packaging.md
- lib/plugins/aws/deploy/compile/functions/index.js
- lib/plugins/aws/deploy/compile/functions/index.test.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
Added support for selectively choosing which function to package individually by setting a `function.package.individually` flag.
Checking for function level individually flag.
Deploy the following config. You should find two packages in the `.serverless` dir. One using the service package under the service name for the `world` function, the other is under the `hello` function name.
```yml
service: some-service
provider:
name: aws
functions:
hello:
package:
individually: true
world:
handler: handler.world
```
> added support for function.package.individually

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing v1.10.2

- README.md
> add jobs link

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing v1.11.0

- docs/providers/aws/guide/iam.md
Closes https://github.com/serverless/serverless/issues/3185
I've changed string interpolation-like syntax into proper one using `Fn::Join`.
```
service: new-service
provider:
name: aws
role: myDefaultRole
resources:
Resources:
myDefaultRole:
Type: AWS::IAM::Role
Properties:
Path: /my/default/path
RoleName: MyDefaultRole
AssumeRolePolicyDocument:
Version: '2012-10-17'
Statement:
Principal:
Service:
- lambda.amazonaws.com
Action: sts:AssumeRole
ManagedPolicyArns:
- arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
Policies:
- PolicyName: myPolicyName
PolicyDocument:
Version: '2012-10-17'
Statement:
Action:
- logs:CreateLogGroup
- logs:CreateLogStream
- logs:PutLogEvents
Resources:
- 'Fn::Join':
- ':'
-
- 'arn:aws:logs'
- Ref: 'AWS::Region' …
```
> Fix IAM documentation regarding joining parameters

- lib/plugins/create/templates/azure-nodejs/README.md
- lib/plugins/create/templates/azure-nodejs/handler.js
Corrected some spelling mistakes in the Azure template files.
Noticed the spelling mistakes when using the creation template; hunted down the usage within the repo and corrected the misspelled words.
Generate using the `azure-nodejs` template
`$ serverless create -t azure-nodejs`
Open the generated files and verify that the text in `handler.js` and `README.md` is all spelled correctly.
> Correct some spelling errors in the Azure template.

- README.md
Added Typescript Plugin to readme
> Added Typescript Plugin

- docker-compose.yml
- docs/providers/aws/cli-reference/create.md
- docs/providers/aws/guide/services.md
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/invokeLocal/invoke.py
- lib/plugins/create/create.js
- lib/plugins/create/create.test.js
- lib/plugins/create/templates/aws-python3/gitignore
- lib/plugins/create/templates/aws-python3/handler.py
- lib/plugins/create/templates/aws-python3/serverless.yml
- tests/templates/test_all_templates
Closes  #3482
[AWS Lambda has Python3.6 support now](https://aws.amazon.com/releasenotes/5198208415517126
), serverless should support it too! 
Added python3.6 to the checks for invoke local and pass the interpreter rather than relying on the shebang line and added a template.
Seems to only be on `us-east-2` when I tested it, but just do:
```bash
sls create -t aws-python3  # then change region in config
sls deploy
sls invoke -f hello
```
> Python3.6 support is coming to Lambda!

- docs/providers/aws/cli-reference/deploy.md
- docs/providers/aws/cli-reference/package.md
- docs/providers/aws/cli-reference/rollback.md
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
- lib/plugins/aws/info/index.js
- lib/plugins/aws/lib/updateStack.js
- lib/plugins/aws/lib/updateStack.test.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/rollback/index.js
- lib/plugins/aws/rollback/index.test.js
- lib/plugins/aws/utils/findAndGroupDeployments.test.js
- lib/plugins/aws/utils/getS3ObjectsFromStacks.test.js
- lib/plugins/package/lib/packageService.js
Some final fixes before releasing for the massive packaging changes:
- Bring back noDeploy option for backward-compatability
- keep the CF file names on S3 without changes
- fix bug when providing custom artifact at service level
- fix bug when packaging individually at function level
Testing & debugging magic! 🐇 
No specific verification steps other than testing packaging and deploying with different case.
> Final packaging fixes

- CHANGELOG.md
- lib/plugins/aws/deploy/lib/extendedValidate.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/package/compile/functions/index.js
- npm-shrinkwrap.json
- package.json
> releasing 1.12

- Dockerfile
Just a quick update for everyone using Docker for development.
> Update Dockerfile with new tooling

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing 1.12.1

- docs/providers/aws/guide/deploying.md
- docs/providers/azure/guide/deploying.md
- docs/providers/openwhisk/guide/deploying.md
Adding documentation for `deploy --package` command. Looking for suggestions and feedback on anything add.
> Adding deploy --package documentation

- docs/providers/aws/cli-reference/deploy.md
- docs/providers/aws/cli-reference/package.md
Fix wrong docs for deploy and package commands options
Updated docs
See updated docs
> Fix options docs for deploy and package commands

- lib/plugins/create/create.js
- lib/plugins/create/create.test.js
- lib/plugins/create/templates/hello-world/gitignore
- lib/plugins/create/templates/hello-world/handler.js
- lib/plugins/create/templates/hello-world/serverless.yml
Adding a `hello-world` template to be used on the homepage of the site and in the docs.
This will give a better experience to people coming into the framework.
```bash
npm install serverless -g
serverless create --template hello-world
http://api.amazon.com/users/update
```
Output provides the actual desired result of a live http endpoint
```
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (404 B)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..................................
Serverless: Stack update finished...
Service Information
service: …
```
> add hello-world template

- lib/plugins/create/create.test.js
Add missing `plugin` template test.
> Add plugin template scaffolding test

- lib/plugins/create/create.test.js
Removed some duplicate code and improve overall stability.
> Improve create plugin tests

- lib/plugins/create/templates/azure-nodejs/handler.js
Closes #3552
I copied the code emitted by the standard Azure HttpTrigger function
You can verify the fix by running the following command:
`serverless create --template azure-nodejs
> Fixed the azure template to make it consistent with the Azure CLI

- README.md
Added a link to serverless-ruby under Services.
> Add a link to serverless-ruby under Services

- lib/classes/Utils.js
- npm-shrinkwrap.json
- package.json
Updated CI detection
Run in CI system of your choice.
> Update CI detection

- lib/classes/PluginManager.test.js
- scripts/integration-test-cleanup.js
Slight adjustments so that Bluebird is always used (instead of native promises).
Used to reduce focus area of #3560
> Adjust Promise usages

- docs/providers/aws/guide/iam.md
Should be Resource and not Resources in 'One Custom IAM Role For All Functions'.
Closes #XXXXX
> Typo in IAM policy.

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing 1.13.0

- docs/providers/aws/README.md
- docs/providers/azure/README.md
- docs/providers/google/README.md
- docs/providers/openwhisk/README.md
> update relative paths in docs

- lib/plugins/aws/deploy/lib/extendedValidate.js
- lib/plugins/aws/deploy/lib/extendedValidate.test.js
Closes #3547 
Fixed a bug with the package plugin when the service has no functions. A `no package found` error was thrown.
We're now not throwing that error when there are no functions in the service.
run `sls package` on a functions-free service:
```yml
service: serverless-functions-free
provider:
name: aws
```
Should package without issues.
> Fix bug when packaging a functions-free service

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing v1.13.1

- lib/classes/Utils.test.js
I implemented a missing "package: {}" inside the serverless.service object for the last test of #logStat() in the Utils.js file. 
Closes #3559
All 975 tests passed when running npm test. However, a bug was found in one of the #logStat() tests. When writing the test for "it should send the gathered information" someone had forgotten to include "package: {}" at the end of the serverless.service object and forgetting to include that last part failed the test. 
Before the fix there was an error in the unit tests: "Unhandled rejection TypeError: Cannot read property 'path' of undefined". The original bug is found here https://travis-ci.org/serverless/serverless/jobs/228828787#L1079
After the fix : 
> Fix unhandled rejection TypeError in unit testing now all tests pass for #logStat()

- lib/classes/Variables.js
- lib/classes/Variables.test.js
- npm-shrinkwrap.json
- package.json
Closes #3607
Fixed a bug when using dot notation in YAML keys. The variable system didn't handle that edge case and converts the dot notation to nested objects.
The issue was caused by the deepMapValues module/mixin for lodash. It didn't handle that edge case so the property path returned was not reliable. I fixed it by removing dependency on that module and taking/customizing the logic and maintain it within the codebase. The edit mainly was changing the representation of property paths to be with arrays instead of strings.
package the following config and check the outputs. You should find the `some.dots` property properly set.
```yml
service: vars-in-files
provider:
name: aws
custom:
dots:
some.dots: hello
functions:
hello:
resources:
Outputs: …
```
> Fixed a bug when using dot notation in YAML keys

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing v1.13.2

- docs/providers/aws/guide/variables.md
> Rephrase note about Serverless env variable usage

- CONTRIBUTING.md
> added note about closing PRs

- docs/providers/aws/guide/variables.md
- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes https://github.com/serverless/serverless/issues/3581
Added support for reading variables from S3
Added a new `${s3:bucketName/keyName}` variable syntax. Uses the new async variables code to make a request to the AWS API and return a promise with the value for a given bucket/key.
Create a S3 bucket and insert a key/value into it. The following Serverless config should create a lambda with an environment variable with the value from S3.
```yml
service: hello-world
provider:
name: aws
region: us-west-2
environment:
foo: ${s3:my-bucket/my-key}
functions:
hello:
```
> Add support for S3 variables

- docs/providers/aws/guide/functions.md
Fixed a typo and a grammar error.
Updated the MD file
Check the diff.
> fixed two typos

- docs/providers/aws/guide/variables.md
Added some backticks for a code block in the Variabls guide.
View docs
> Updating missing markdown in Docs

- lib/plugins/aws/invoke/index.js
- lib/plugins/aws/invoke/index.test.js
- lib/plugins/aws/logs/index.js
- lib/plugins/aws/utils/formatLambdaLogEvent.js
- lib/plugins/aws/utils/formatLambdaLogEvent.test.js
Fix logging issues with `serverless logs` and `serverless invoke` which broke on unexpected outputs.
Closes #1796 
Closes #3594
Refactor duplicated log line formatting from invoke and logs plugins
into utils/formatLambdaLogEvent.js and add tests.
Make log line formatter understand default python logging module output
from Lambda functions.
Add payload output testing to invoke plugin.
```py
import logging
logging.basicConfig()
log = logging.getLogger("hello")
log.setLevel(logging.INFO)
log.info("Hello")
return {'message': 'logged it'}
```
`serverless invoke -f hello -l`
> Better handling for AWS Lambda logging lines.

- docs/providers/google/guide/quick-start.md
> Fixed filename misspelling

- docs/providers/aws/cli-reference/rollback-function.md
The documentation for the new `rollback function` stated to use a `--name` or `-n` argument for the function name, but the implementation expects `--function` or `-f` for the function name. I updated the documentation to reflect the actual implementation. 
> Fixing 'rollback function' parameter documentation

- docs/getting-started.md
- docs/providers/aws/guide/services.md
- docs/providers/azure/guide/services.md
- docs/providers/google/guide/services.md
- docs/providers/openwhisk/guide/services.md
Closes #3677
Added documentation as per the discussion in the issue.
By checking `docs/getting-started.md`.
> Add documentation for installing Serverless locally

- VERSIONING.md
Adds the file which describes how the Framework versioning works.
/cc @nikgraf @brianneisler @eahefnawy @DavidWells @ac360
> Add VERSIONING.md file

- docs/providers/aws/guide/functions.md
- lib/Serverless.js
- lib/classes/Error.js
- lib/classes/Error.test.js
- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
- lib/classes/Utils.js
- lib/classes/Utils.test.js
- lib/plugins/slstats/slstats.js
- lib/plugins/slstats/slstats.test.js
- lib/utils/config/config.test.js
- lib/utils/config/index.js
- lib/utils/config/initialSetup.js
- lib/utils/fs/removeFileSync.js
- lib/utils/getFrameworkId.js
- lib/utils/isTrackingDisabled.js
- lib/utils/sentry.js
- npm-shrinkwrap.json
- package.json
Tracking errors will give us far more insight on where user pain lives.
This PR will start piping errors into sentry for us to tackle common problems users are facing.
Closes #1610
> DX: Add error tracking

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> releasing 1.15

- lib/Serverless.js
- lib/utils/segment.js
- lib/utils/sentry.js
- lib/utils/userStats.js
- scripts/postinstall.js
- scripts/preuninstall.js
Fixes the postinstall error which breaks installation with tight permissions.
Closes #3757 
Closes #3760
> Fix postinstall error

- CHANGELOG.md
> Fix PR numbers in CHANGELOG.md

- docs/providers/azure/cli-reference/README.md
- docs/providers/azure/cli-reference/create.md
- docs/providers/azure/cli-reference/deploy-function.md
- docs/providers/azure/cli-reference/deploy.md
- docs/providers/azure/cli-reference/install.md
- docs/providers/azure/cli-reference/invoke.md
- docs/providers/azure/cli-reference/remove.md
- docs/providers/azure/events/blobstorage.md
- docs/providers/azure/events/eventhubs.md
- docs/providers/azure/events/http.md
- docs/providers/azure/events/other.md
- docs/providers/azure/events/queuestorage.md
- docs/providers/azure/events/servicebus.md
- docs/providers/azure/events/timer.md
- docs/providers/azure/guide/credentials.md
- docs/providers/azure/guide/deploying.md
- docs/providers/azure/guide/events.md
- docs/providers/azure/guide/functions.md
- docs/providers/azure/guide/installation.md
- docs/providers/azure/guide/intro.md
- docs/providers/azure/guide/packaging.md
- docs/providers/azure/guide/plugins.md
- docs/providers/azure/guide/quick-start.md
- docs/providers/azure/guide/services.md
- docs/providers/azure/guide/testing.md
- docs/providers/azure/guide/variables.md
- docs/providers/azure/guide/workflow.md
Better documentation for both getting started and working with serverless on Azure.
Ran through each step with all of the latest tools and made sure everything was up to date.
Check out the diff. You'll see some updated authentication steps (using the latest CLI) and some spelling corrections.
> Update Azure documentation.

- README.md
> update readme with new plugin

- docs/providers/aws/events/cognito-user-pool.md
Moved `logical resource name` link in `CognitoUserPool` documentation and added `.md` suffix to resource. Continuation of #3767.
> Updating logical resource name link

- lib/plugins/create/templates/azure-nodejs/handler.js
Removed restrictions in `azure-nodejs` for a query parameter/json body. I was helping someone in the gitter chat try to figure this out and thought it added unnecessary complexity for a template. 
Modified `handler.js` to return a default message and a `200` response code.
Create `azure-nodejs` template project, deploy, and invoke.
> Simplify Azure Template

- CHANGELOG.md
- package-lock.json
- package.json
> releasing v1.15.3

- docs/providers/aws/guide/quick-start.md
Small documentation fix since without `npm init`, `npm install` will throw an error :)
With my little hands ^_^
By reading it with your eyes ^_^
> Added missing step

- docs/providers/aws/cli-reference/invoke-local.md
- docs/providers/aws/cli-reference/invoke.md
- removed erroneous statement about "context and event properties" in mock event data files
- added example data.json
docs fixup
Closes #XXXXX
> invoke local docs fixup

- package-lock.json
- package.json
> releasing alpha

- CHANGELOG.md
- package-lock.json
- package.json
> releasing v1.16.0

- docs/providers/aws/events/apigateway.md
> Fix AWS API Gateway request parameters docs

- lib/plugins/platform/platform.js
This is necessary to support a CI/CD flow for publishing a service to the Serverless Platform. 
Open `~/.serverlessrc` and find the key `id_token` in `users.github<your-id>`. Take the value of `id_token` and set it as an environment variable on your CI/CD system e.g. export SERVERLESS_TOKEN="<your-token>".
> Platform ci support

- docs/providers/openwhisk/guide/web-actions.md
Closes #XXXXX
Incorrect URL in docs
> Update web-actions.md docs w/ correct URL

- docs/providers/google/events/event.md
Documentation fix of google cloud function usage.
> fix: correct misspelled eventType value

- lib/plugins/platform/platform.js
- lib/plugins/platform/platform.test.js
> Update console output on successful publish

- CHANGELOG.md
- package-lock.json
- package.json
> releasing 1.16.1

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/config/config.js
- lib/plugins/deploy/deploy.js
- lib/plugins/info/info.js
- lib/plugins/install/install.js
- lib/plugins/invoke/invoke.js
- lib/plugins/logs/logs.js
- lib/plugins/metrics/metrics.js
- lib/plugins/platform/platform.js
- lib/plugins/remove/remove.js
- lib/plugins/rollback/index.js
> Update user stats

- README.md
Added ETA to list of consultants
> Add ETA as Serverless Consultants

- docs/README.md
Capitalized 'Serverless' and added a full stop after 'Start here'.
N/A
Viewing `README.md`.
> Typo and grammar fixes

- package-lock.json
- package.json
> releasing 1.17.0 alpha

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing 1.17

- docs/providers/aws/guide/functions.md
> Minor edit

- lib/classes/Service.js
- lib/classes/Service.test.js
- lib/classes/Utils.js
- lib/classes/Variables.js
- lib/classes/Variables.test.js
> handle absolute paths in file()

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
- package-lock.json
Closes #3862 
You should be able to see the new message when running `serverless invoke -f hello` with bad credentials as the issue describes. I can write a simple test also when I get a chance.
> Improves invalid security token message per issue #3862

- lib/plugins/aws/deploy/lib/extendedValidate.js
- lib/plugins/aws/deploy/lib/extendedValidate.test.js
- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/deployFunction/index.test.js
- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
- package-lock.json
Closes #3625 
Closes #3580 
Added function artifact check in `deployFunction()` and skip packing when an artifact is provided.
And add function artifact check in `packageService()` to use the provided artifact path and not derive some default artifact path.
* Create an aws-nodejs template project and deploy.
* Create a dummy zip file, say `foo.zip`, and add that as artifact of a function.
```
functions:
hello:
package:
artifact: foo.zip
```
* Run `sls deploy function -f hello` to deploy the function.
* Open AWS lambda console and export the function. The downloaded file is the same dummy zip file.
> Follow up for #3876 & #3856: Fixes for custom package artifacts 

- docs/providers/aws/events/s3.md
Added documentation for custom bucket configuration on S3 event triggers.
Assists in dealing with issues like #3038, #3257, and #3448.
N/A
N/A
> Add docs for custom bucket config on S3 events

- lib/plugins/aws/invokeLocal/index.test.js
> Enhance tests for invoke local

- CHANGELOG.md
- package-lock.json
- package.json
> releasing 1.18

- docs/providers/aws/guide/serverless.yml.md
I noticed that there are several undocumented properties in serverlessyml-reference, so added those 
> Add some available properties to the doc

- CHANGELOG.md
- package-lock.json
- package.json
> releasing 1.18.1

- docs/providers/aws/guide/serverless.yml.md
> Add missing vpc property.

- CHANGELOG.md
- package-lock.json
- package.json
> releasing 1.19.0

- docs/providers/aws/guide/functions.md
I fixed a typo I noticed when reading the guide. The word `environment` was incorrectly spelled as `environemnt`.
> Fix typo in guide for functions

- docs/providers/aws/guide/services.md
Fix the link so that it's rendered correctly.
> Fix link to shared API Gateway issue

- docs/providers/aws/guide/quick-start.md
I fixed a typo I noticed when reading the guide; "an Function" should be "a Function".
> Fix typo in AWS Quick Start

- docs/providers/aws/guide/credentials.md
> Update docs for windows users

- .eslintignore
- lib/plugins/create/templates/kubeless-nodejs/handler.js
Disabling the linting warning in a template
> disable linting warning for log statement

- lib/plugins/run/utils/logEventGateway.js
- lib/plugins/run/utils/logLocalEmulator.js
- lib/plugins/run/utils/logServerless.js
- lib/plugins/run/utils/manageEventGateway.js
- lib/plugins/run/utils/manageLocalEmulator.js
Adds UI changes to terminal output.
> Serverless run mods

- lib/utils/userStats.js
Adds FrameworkId to stats calls
> Add FrameworkId to stats

- docs/providers/aws/README.md
- docs/providers/aws/cli-reference/README.md
- docs/providers/aws/events/README.md
- docs/providers/aws/examples/README.md
- docs/providers/aws/guide/README.md
- docs/providers/azure/README.md
- docs/providers/azure/examples/README.md
- docs/providers/google/README.md
- docs/providers/google/examples/README.md
- docs/providers/openwhisk/README.md
- docs/providers/openwhisk/examples/README.md
This fixes the forum links which were incorrectly pointing to gitter in a number of cases.
View the docs, click the links.
> Fix forum links

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.20.0

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.20.1

- docs/providers/aws/guide/iam.md
Closes #3185
It is mostly a copy/paste of earlier adjustments to the first example to the others that had to be done.
> Fix the last two IAM documentation regarding joining parameters

- lib/plugins/create/templates/azure-nodejs/serverless.yml
Changed `diections` property to `direction` in azure-nodejs serverless.yml.
> Fixing typo in azure-nodejs template

- package-lock.json
Dealing with inconsistencies during `npm install`.
> Fix package-lock.json file

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.20.2

- docs/providers/aws/guide/functions.md
SQS was mis-spelled
Just a typo
> Typo corrections in fucions.md

- docs/providers/aws/guide/installation.md
- docs/providers/google/guide/installation.md
- docs/providers/openwhisk/guide/installation.md
> Fix 3 typos in docs

- lib/plugins/emit/index.test.js
- lib/plugins/run/utils/logEventGateway.test.js
Fixed the newest tests so they pass on Windows.
Replaced literal `\n` with `os.EOL`.
https://ci.appveyor.com/project/plus3it/serverless
> Fixes new tests so they run on Windows

- RELEASE_PROCESS.md
This PR contains the `RELEASE_PROCESS.md` doc which outlines how we do releases.
Feel free to update / propose changes.
/cc @eahefnawy @brianneisler
> Add RELEASE_PROCESS.md doc

- docs/platform/README.md
- docs/platform/commands/README.md
Update docs to help make it clear that services are published privately.
> Add comment that services are published privately. Fix nav item

- lib/plugins/aws/provider/awsProvider.test.js
Fixes failing test introduced in #4155.
> Fix failing AWS provider test

- lib/plugins/create/templates/spotinst-nodejs/handler.js
- lib/plugins/create/templates/spotinst-nodejs/serverless.yml
- lib/plugins/create/templates/spotinst-python/serverless.yml
> Fix indentation for spotinst templates

- package-lock.json
- package.json
Upgrade FDK to the latest stable version working supporting the already used 0.5.15 version of the Event-Gateway (there were some changes on the Event Gateway side that didn't get updated in the FDK) and comes with improved error messaging.
Make the https://github.com/serverless/event-gateway-example still work fine.
> upgrade fdk to 0.5.0

- docs/providers/aws/guide/variables.md
Fixed the custom `variableSyntax` example in the docs. Prior example did not implement the double braces (which the example is attempting to demonstrate), and introduced a YAML syntax error escaping the single quote.
> Corrects the custom variableSyntax example

- docs/README.md
- docs/getting-started.md
- docs/providers/README.md
- docs/providers/kubeless/README.md
- docs/providers/kubeless/cli-reference/README.md
- docs/providers/kubeless/cli-reference/create.md
- docs/providers/kubeless/cli-reference/deploy.md
- docs/providers/kubeless/cli-reference/info.md
- docs/providers/kubeless/cli-reference/invoke.md
- docs/providers/kubeless/cli-reference/logs.md
- docs/providers/kubeless/cli-reference/remove.md
- docs/providers/kubeless/events/README.md
- docs/providers/kubeless/events/http.md
- docs/providers/kubeless/events/pubsub.md
- docs/providers/kubeless/guide/README.md
- docs/providers/kubeless/guide/debugging.md
- docs/providers/kubeless/guide/deploying.md
- docs/providers/kubeless/guide/events.md
- docs/providers/kubeless/guide/functions.md
- docs/providers/kubeless/guide/installation.md
- docs/providers/kubeless/guide/intro.md
- docs/providers/kubeless/guide/quick-start.md
- docs/providers/kubeless/guide/services.md
- docs/providers/kubeless/guide/workflow.md
Closes #4151
Kubeless provider documentation for serverless.com website
These are just docs
> Added Kubeless provider documentation

- CHANGELOG.md
- package-lock.json
- package.json
- [Allow custom CLI class instances](https://github.com/serverless/serverless/pull/4160)
- [Add support in Spotinst Functions](https://github.com/serverless/serverless/pull/4127)
- [Add PHP support for OpenWhisk](https://github.com/serverless/serverless/pull/4153)
- [Fixed a bug with stack deletion monitoring](https://github.com/serverless/serverless/pull/4132)
- [Allow AWS Profile CLI option to overwrite config and env](https://github.com/serverless/serverless/pull/3980)
- [Improve performance of the package plugin](https://github.com/serverless/serverless/pull/3924)
- [Add support for custom context with Invoke Local](https://github.com/serverless/serverless/pull/4126)
- [Add aws-nodejs-typescript template](https://github.com/serverless/serverless/pull/4058)
- [Add …
> Releasing 1.21.0

- docs/providers/aws/cli-reference/invoke-local.md
- docs/providers/aws/cli-reference/invoke.md
> Update docs with link to AWS Proxy Integration when passing data to invoke and invoke local

- lib/plugins/aws/invokeLocal/invoke.py
The changes in 1.21(#4126) allowing custom context introduced bugs in the
Python invoke local implementation:
* If no custom context is set it would error out because the handler
would never be called
* AWS Lambda context objects in python aren't dictionaries, they're
Python objects
Fixes regressions introduced in  #4126
* Always call the handler, not inside of an `if` statement
* Keep using the `FakeContext` object and allow it to have arbitrary fields
Run this:
```
sls create -t aws-python3
```
It crashes in 1.20 but not with this PR
> Fix Python invokeLocal regressions due to context changes

- docs/providers/aws/guide/variables.md
> fix typo in s3 variables docs

- lib/plugins/create/create.test.js
Hardening the `create` tests to make them more reliable and faster.
> Hardening create tests

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.21.1

- scripts/integration-test-cleanup.js
> Update integration-test-cleanup.js script

- lib/plugins/create/create.js
Fixes the annoying race condition which causes unit tests to fail randomly.
> Fix gitignore file renaming race condition

- docs/platform/README.md
See: https://github.com/serverless/serverless/pull/3950#issuecomment-327325833
> Add publish flag documentation

- package.json
- scripts/integration-test-cleanup.js
Added Integration Tests Cleanup Script
> Added Integration Tests Cleanup Script

- docs/providers/azure/guide/quick-start.md
- docs/providers/openwhisk/events/apigateway.md
- docs/providers/openwhisk/events/schedule.md
- docs/providers/openwhisk/events/triggers.md
- docs/providers/openwhisk/guide/deploying.md
- docs/providers/openwhisk/guide/intro.md
- docs/providers/openwhisk/guide/web-actions.md
Temp fix for https://github.com/serverless/site/issues/163
> update external github links

- lib/utils/fs/parse.js
- lib/utils/fs/parse.test.js
- lib/utils/fs/stringify.js
- lib/utils/fs/writeFile.js
- lib/utils/fs/writeFile.test.js
- lib/utils/fs/writeFileSync.js
- lib/utils/fs/writeFileSync.test.js
- package-lock.json
- package.json
Re-Closes #3509 
Allow for the serialization and deserialization of cyclic objects being written to file using json-decycle.  (in support of #4144)
Add `json-decycle` and use and instance of it as the second parameter for JSON.stringify/JSON.parse for file writing and reading.
A project with a `${self:}` reference should be sufficient to evoke the issue.  During serialization you would get the result:
```
[...] $SLS_DEBUG=* slsDev deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Type Error ---------------------------------------------
Converting circular structure to JSON
Stack Trace --------------------------------------------
TypeError: Converting circular …
```
> Add Cyclic Object Serialization Support

- docs/providers/aws/cli-reference/invoke.md
The Limitations section covers this, and is more accurate (includes Python as a possibility).
Documentation update.
-
In a Serverless project with a Python function, try `sls invoke local`. It works!
> [docs] Remove outdated sentence about local runtime

- docs/providers/aws/cli-reference/deploy-function.md
Some of the `deploy function` docs were out of sync with the final feature. Updating them to reflect that.
> Updating `deploy function` docs for 1.22 changes

- docs/providers/azure/guide/quick-start.md
Serverless deploy throws error without serverless-azure-functions plugin installed globally.
Closes #XXXXX
> Added serverless-azure-functions to pre-requisites

- README.md
Add more languages to README.md
> Add more supported languages to README.md

- docs/README.md
- docs/getting-started.md
- docs/providers/README.md
- docs/providers/webtasks/README.md
- docs/providers/webtasks/cli-reference/README.md
- docs/providers/webtasks/cli-reference/config-credentials.md
- docs/providers/webtasks/cli-reference/create.md
- docs/providers/webtasks/cli-reference/deploy.md
- docs/providers/webtasks/cli-reference/info.md
- docs/providers/webtasks/cli-reference/invoke.md
- docs/providers/webtasks/cli-reference/logs.md
- docs/providers/webtasks/cli-reference/remove.md
- docs/providers/webtasks/events/README.md
- docs/providers/webtasks/events/http.md
- docs/providers/webtasks/events/schedule.md
- docs/providers/webtasks/guide/README.md
- docs/providers/webtasks/guide/intro.md
- docs/providers/webtasks/guide/quick-start.md
This is the docs for the Auth0 Webtasks provider
I wrote out the docs...
Just review them I guess...
> Docs for Auth0 Webtasks Provider

- lib/plugins/platform/platform.js
- lib/plugins/platform/platform.test.js
Fixes: serverless/platform-frontend#261
> Add logic for archiveService function

- docs/providers/webtasks/README.md
- docs/providers/webtasks/cli-reference/README.md
- docs/providers/webtasks/events/README.md
- docs/providers/webtasks/events/schedule.md
- docs/providers/webtasks/guide/README.md
This fixes 2 broken links in the webtask docs. The links are currently broken on the live site. It also fixes a typo in the webtask docs.
Just review the PR
> Fix links in webtask docs

- docs/providers/aws/guide/serverless.yml.md
There was an issue with the tabbing the example YAML. I've corrected it. 
Deleted some whitespace.
Try to run a `serverless.yaml` with and without the corrected tabbing. 
> Fix tabbing for iamRoleStatements

- docs/providers/aws/cli-reference/rollback.md
- lib/plugins/aws/rollback/index.js
- lib/plugins/aws/rollback/index.test.js
- lib/plugins/rollback/index.js
- lib/plugins/rollback/index.test.js
Closes https://github.com/serverless/serverless/issues/3861
```
serverless rollback
```
> Run `serverless deploy list` if timestamp is not specified in rollback command

- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
Closes https://github.com/serverless/serverless/issues/3285
Just added else condition.
> Removing private: true from function does not change it's state

- docs/providers/openwhisk/guide/quick-start.md
> Update IBM registration URL

- docs/providers/aws/guide/resources.md
Update resources guide to include resource type in example for overwriting a resource. This is currently needed, see: https://github.com/serverless/serverless/issues/2653#issuecomment-326618029
Update resources guide
> ResourcesGuide: Specify resource type

- .travis.yml
Dropped the Travis setup which runs integration test on the master branch since we’ve abandoned them a long time ago since they are really brittle and misleading.
Dropped the complex integration test setup from .travis.yml.
To confirm that, you need to run the CI on the master branch.
I forked the repo to the personal one and run it on the master.
> Drop the complex integration test from travis.yml

- lib/utils/downloadTemplateFromRepo.test.js
https://ci.appveyor.com/project/serverless/serverless/build/1.0.541/job/dy85nmqnuu638o5y
Fixed the above error
The cause of that was due to the difference of path interpretation depends on OS, so I have fixed using the corresponding to that.
Please see the result of test on Appveyor tests.
> Fix failing tests on Appveyor

- docs/providers/google/guide/credentials.md
Fix documentation grammar error
*Edit on GitHub* link
> Google credentials.md: remove duplicate "Console"

- lib/utils/downloadTemplateFromRepo.js
linting warning occurred on top of master
```
$npm run lint
> serverless@1.23.0 lint /Users/horike/src/serverless
> eslint . --cache
/Users/horike/src/serverless/lib/utils/downloadTemplateFromRepo.js
174:3  warning  Unexpected console statement  no-console
✖ 1 problem (0 errors, 1 warning)
```
removed `console.log`, and change using the suitable function.
npm run lint
> Fixed linting warning

- docs/providers/aws/guide/variables.md
~Closes #XXXXX~
Fixed typo
Fixed typo in code snippets
Check diff
> Fix typo in aws guide

- docs/providers/spotinst/cli-reference/deploy-function.md
- docs/providers/spotinst/guide/intro.md
- docs/providers/spotinst/guide/serverless.yml.md
- docs/providers/spotinst/guide/variables.md
- lib/plugins/create/templates/spotinst-nodejs/serverless.yml
- lib/plugins/create/templates/spotinst-python/serverless.yml
- lib/plugins/create/templates/spotinst-ruby/serverless.yml
Added documentation for environment variables that can be edited in the yml file
simple docs change
Justs a docs change
> Spotinst - adding docs for environment variables and adding to templates

- lib/plugins/aws/deploy/lib/createStack.test.js
There were multiple `beforeEach()` methods in a test module which was causing issues. cc @HyperBrain 
Consolidated them
Pray that the tests pass
> Consolidate multiple beforeEach methods in test

- README.md
Using serverless for many different client projects from E-commerce, Ed-tech and entertainment.
Change to readme for consultants 
changed the readme
check us out! :P
> Consultants

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.24.0

- lib/classes/Variables.test.js
Closes #4448 
I have improved the variables test as what @HyperBrain stated, which is using `sinon-chai` syntax so that this leads to much better error messages in case of failures
https://github.com/serverless/serverless/pull/4448#pullrequestreview-74467610
Updated syntax with `sinon-chai`.
Run `npm run test`
> Improve variables test

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.24.1

- lib/classes/Variables.test.js
Closes #4389 
The functionality introduced in #4389 lacks a unit test which checks working fine if you set up symlink.
I have added a test case, otherwise, we might be going to break that in future without noticing.
Added a test which creating symlinks and read properly it via the variable system.
Run `npm run test`
> Add test case if symlink works to variable tests

- lib/utils/openBrowser.js
Closes #4458 
Instead of try/catch a call to a promise, use the promise catch chain.
Checkout this PR branch, export `BROWSER` environment variable to an invalid binary path (eg: `export BROWSER=/dumb`) and run `bin/serverless login`.
You should see something like this:
If one executes the same procedure on `master` branch, should see the following
>  Fix error handle for serverless login command

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/quick-start.md
> Improve doc links

- lib/Serverless.js
- package.json
Closes #4464
Removed the import and the dependency from `package.json`.
Note: I did not update `package-lock.json` because I was hitting https://github.com/npm/npm/issues/17749 with integrity being updated and didn't want to pollute the diff.
@RafalWilinski already said that the change did not lead to any test failures. For further verification I went through the list of [ShellJS commands](https://github.com/shelljs/shelljs#command-reference) and searched for their presence in the Serverless codebase. I did not find them being used.
> Remove shelljs dependency

- docs/providers/aws/events/apigateway.md
> document status codes in lambda-proxy integration

- docs/providers/spotinst/guide/credentials.md
Closes #XXXXX
Documentation change. Fixes account id parameter in a Spotinst [`credentials.md`](https://github.com/serverless/serverless/blob/master/docs/providers/spotinst/guide/credentials.md) guide as per [`config-credentials.md`](https://github.com/serverless/serverless/blob/master/docs/providers/spotinst/cli-reference/config-credentials.md) cli reference. 
> Fix account id parameter

- docs/providers/spotinst/guide/quick-start.md
Updated Quick Start Docs for ease of use
Closes #XXXXX
Docs change
Check docs/providers/spotinst/guide/quick-start.md
> Spotinst - Updating Quick Start Docs

- lib/classes/Variables.js
Replacement for #4412, resolves @amberlion's bug in #4144.
> Circular Vars Fix

- docs/providers/spotinst/README.md
- docs/providers/spotinst/guide/document-store.md
Another document change!! :)
Closes #XXXXX
cosmetic change to docs
providers/spotinst/guide/document-store.md
> Spotinst - updating Document Store Docs

- docs/providers/aws/guide/variables.md
- Add usage on how to reference aws Pseudo-Parameters in serverless framework
- Add usage on how to use Cloudformation stack's Ouputs export value
User guild updates only
User guild updates only
> Add usage about Pseudo-Parameters

- docs/providers/aws/guide/resources.md
Added hint to docs, how to find out the names of generated AWS resources. Our issues show, that this often introduces an additional feedback cycle.
Trivial, so nothing to do here
~~Write tests~~
~~Write documentation~~
~~Fix linting errors~~
~~Make sure code coverage hasn't dropped~~
~~Provide verification config / commands / resources~~
~~Enable "Allow edits from maintainers" for this PR~~
~~Update the messages below~~
> Added hint to docs on how to determine generated resource names easily

- lib/classes/Variables.js
- lib/classes/Variables.test.js
- package-lock.json
Refactor, simplify, correct, and add tests
* Fixes #4527, uncomments associated (now working) tests
* Increase naming consistency
* Improve names to be-what-they-are
* Reduce cyclomatic complexity
* Includes overrides population fix
* Add variable methods documentation
* Add more tests around significant variable patterns/risky cases
* Fix migrated but commented-out tests
See changes.
See unit tests
> Variables cleanup

- lib/classes/Variables.test.js
1. add tests that validate string value defaults in overrides.
2. add test of behavior when a javascript's export does not contain the attribute declared in the variable.
3. add tests of behavior when an SSM parameter is not found and the request to the SSM service fails.
add returns to tests that weren't returning their promises (and were thereby risking false positives.
> add tests to get to 100% line coverage

- lib/plugins/create/templates/aws-nodejs-typescript/handler.ts
Closes #4551
Updated the template in the `create` plugin.
By creating a new project with `sls create --template aws-nodejs-typescript`
> Add type `APIGatewayEvent` to handler

- docs/providers/aws/guide/credentials.md
Fixed a minor grammatical error in the AWS Credentials doc.
Closes #XXXX 
> Grammar fix in AWS Credentials doc

- docs/providers/aws/guide/credentials.md
The removed paragraph refers to providing credentials instructions for multiple different cloud providers, whereas this doc is for AWS credentials only.
It seems likely that this paragraph was written at a time when there was a single document to cover credentials for all providers, but now that each provider has its own credentials doc, it no longer makes sense, and was probably left in place by accident.
Removed a paragraph from the AWS Credentials guide doc, which did not seem to belong there.
Closes #XXXXX
> Remove outdated para from AWS Credentials doc

- docs/providers/aws/events/apigateway.md
Fixed a prose error in the API Gateway document text.
> Fix typo in API Gateway doc

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.25.0

- lib/classes/CLI.js
- lib/classes/PluginManager.js
- lib/utils/getCommandSuggestion.js
- lib/utils/getCommandSuggestion.test.js
- package-lock.json
- package.json
Closes #4328
Add "did you mean..." suggestions when you input any commands and make a typo.
I have leveraged [Levenshtein Distance](https://people.cs.pitt.edu/~kirk/cs1501/Pruhs/Spring2006/assignments/editdistance/Levenshtein%20Distance.htm) algorithm for this feature.
Get levenshtein distance between an inputted keyword by a user and all commands keyword, and then suggest a keyword that is minimum distance as a correct one.
Of course, added commands by external plugins are supported as well.
Make a typo by yourself like `sls pekege`, `sls deploi` and so on. 
> Add "did you mean..." suggestions when you make a typo

- README.md
Change to readme for consultants
changed the readme
heck us out! :P
> Using serverless for many different client projects

- CONTRIBUTING.md
- README.md
We have decided to change labels so that they will be automatically grabbed by GitHub and shown to visitors.
> Change labels to `good first issue` and `help wanted`

- lib/plugins/print/print.js
- lib/plugins/print/print.test.js
Fix #4556 
Replace the existing service and clear the cache (which references the amended service).
Remove cycles in that service using json-cycle.
Dump the de-cycled object as YAML to console.
See additional test.
> Fix Cycles Crash (#4556)

- lib/plugins/create/templates/aws-scala-sbt/project/assembly.sbt
- lib/plugins/create/templates/aws-scala-sbt/project/plugins.sbt
Closes #4634
Updated the version numbers in assembly.sbt and plugin.sbt template
* assembly.sbt - updated the version number to 0.14.6
* plugins.sbt - updated the version number to 1.0.7
> update aws-scala-sbt template #4634

- lib/plugins/create/templates/kubeless-nodejs/package.json
- lib/plugins/create/templates/kubeless-python/package.json
Closes https://github.com/serverless/serverless-kubeless/issues/92
Bump version of serverless-kubeless to 0.2.4
`npm i`
> Bump serverless-kubeless to 0.2.4

- docs/providers/kubeless/README.md
- docs/providers/kubeless/guide/functions.md
- docs/providers/kubeless/guide/packaging.md
- lib/plugins/create/templates/kubeless-nodejs/package.json
- lib/plugins/create/templates/kubeless-python/package.json
Closes https://github.com/serverless/serverless-kubeless/issues/88
This is a documentation (and template) update for Kubeless 0.4 and `serverless-kubeless` 0.3.
~~- [ ] Write tests~~
> Update documentation and templates for serverless-kubeless 0.3

- lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js
> enable source map generation for nodejs-typescript example

- docs/providers/google/examples/hello-world/node/README.md
Noticed an outdated example in the [Hello World Node.js Example](https://serverless.com/framework/docs/providers/google/examples/hello-world/node/), and corrected the documentation.
If a new user creates a new service with the `google-nodejs` template,
the pre-configured function is named as `first` instead of `helloWorld`.
Error message was visible when running with the original function name `helloWorld`.
```
$ serverless invoke --function helloWorld
Error --------------------------------------------------
Function "helloWorld" not found. Please check your "serverless.yml" file for the correct function name.
```
- Changed name of the function from the section: _Invoke deployed function_
- Follow …
> docs(google) update hello-world example's invoke

- docs/providers/google/cli-reference/invoke-local.md
Today is the first time I explored Google Cloud functions, leveraging `serverless`. Unfortunately, I suffered that the documentation is lacking on invoking a function locally.
On a personal note; luckily I had some experience with invoking AWS functions so I could use `docs/providers/aws/cli-references/invoke-local.md` as a reference. I still want to suggest that we add in `invoke-local.md` documentation under `docs/providers/google/cli-references`.
This would have helped me in the first place, without having to jump back into the AWS docs as reference point.
I decided for the `menuOrder: 7` since this document should directly be under `invoke`.
The `menuOrder` of following docs in the menu can be corrected after all feedback on documentation has been addressed.
***Is this ready for …
> docs(google/cli) add invoke-local.md

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.26.0

- docs/providers/aws/events/apigateway.md
Fix typo in apigateway.md
chilren -> children
look up chilren in a dictionary
> Fix typo in apigateway.md

- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
Closes #3773
Add a check to see if an override exists in the `Resources` section of `serverless.yml`. If one does exist, then merge the overrides into the base template.
By running the unit tests. I'll try and get some time to properly test it, but from what I can tell it was mainly a CF template generation issue anyway.
> Fix broken merge in CUP compile event. Fixes #3773.

- docs/providers/spotinst/README.md
- docs/providers/spotinst/examples/node/README.md
- docs/providers/spotinst/guide/active-versions.md
- docs/providers/spotinst/guide/create-token.md
- docs/providers/spotinst/guide/quick-start.md
- docs/providers/spotinst/guide/serverless.yml.md
- docs/providers/spotinst/guide/variables.md
- lib/plugins/create/templates/spotinst-java8/serverless.yml
- lib/plugins/create/templates/spotinst-nodejs/serverless.yml
- lib/plugins/create/templates/spotinst-python/serverless.yml
- lib/plugins/create/templates/spotinst-ruby/serverless.yml
Updated Spotinst docs.
Closes #XXXXX
Documentation changes.
Check Spotinst/guide/active-versions.md
Check Spotinst templates
> Spotinst - added activeVersions documentation, updated Spotinst templates

- docs/providers/google/guide/intro.md
> Google docs intro typo

- docs/providers/spotinst/README.md
- docs/providers/spotinst/guide/IAM-roles.md
- lib/plugins/create/templates/spotinst-java8/serverless.yml
- lib/plugins/create/templates/spotinst-nodejs/serverless.yml
- lib/plugins/create/templates/spotinst-python/serverless.yml
- lib/plugins/create/templates/spotinst-ruby/serverless.yml
Added support for IAM roles in the serverless.yml
Closes #XXXXX
Added an attribute in serverless.yml
See serverless.yml
> Added IAM roles support

- docs/providers/aws/events/alexa-skill.md
compatability -> compatibility (nitpicking, I know)
Closes #XXXXX
> Fix typo in sub-heading

- docs/providers/aws/guide/serverless.yml.md
Add missing attributes to the "exhaustive" `serverless.yml` configuration listing.
Add attributes and example values to `~/docs/providers/aws/guide/serverless.yml.md`
N/A
- [n/a] Write tests
> Add CloudWatch Event Attributes to `serverless.yml.md`

- docs/providers/aws/events/apigateway.md
Improved readability of docs for AWS API Gateway sharing between multiple Serverless projects.
Rewrote parts of the docs.
Read the docs.
> Improve readability

- lib/plugins/create/create.js
- lib/plugins/create/create.test.js
- lib/plugins/create/templates/openwhisk-java-maven/.gitignore
- lib/plugins/create/templates/openwhisk-java-maven/pom.xml
- lib/plugins/create/templates/openwhisk-java-maven/serverless.yml
- lib/plugins/create/templates/openwhisk-java-maven/src/main/java/com/example/FunctionApp.java
- lib/plugins/create/templates/openwhisk-java-maven/src/test/java/com/example/FunctionAppTest.java
Signed-off-by: Kamesh Sampath <kamesh.sampath@hotmail.com>
Adding support for creating OpenWhisk Java template with maven as build tool
Closes #4491
Created a another template directory called `openwhisk-java-maven` in `lib/plugins/create/templates/openwhisk-java-maven`, and added 
* Java Sample Function class with required Java Signature of OpenWhisk Java Action
* Java Sample Function Unit Test class
* `serverless.yaml` for OpenWhisk 
* `pom.xml`
Added the UT cases inline with other templates, deploying project successfully to OpenWhisk
- [*] Write documentation
- [*] Fix linting errors
- [*] Enable "Allow edits from maintainers" for this PR
> Resolving #4491 , adding support for java maven templates for OpenWhisk

- docs/providers/kubeless/events/pubsub.md
Fix a markdown link in the documentation that had an incorrect format
> Fix a broken link in the doc

- docs/providers/aws/examples/hello-world/go/README.md
- Remove duplicate sentence
- Change Node template to Go template
> Update README.md for aws/examples/hello-world/go

- docs/providers/aws/guide/iam.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Closes #3751 
I have added an optional section to the aws provider section within the serverless.yml named iamManagedPolicies to go along side iamRoleStatements. It allows users to specify any managed policies at that level without having to explicitly form the whole iam role in the resources section.
Add an iamManagedPolicies section under provider with a list of managed policies like the following serverless.yml (can contain a list of strings or objects to allow for refs and fns in cloudformation):
```yml
service: sandbox-for-managed-policies
provider:
name: aws
runtime: java8
iamManagedPolicies:
- 'arn:aws:iam:*****:policy/some-managed-policy'
Action:
- sns:Publish
Resource: "*"
package:
artifact: artifact.jar
functions:
myFunction:
handler: someClass …
```
> Add iam managed policies

- docs/providers/openwhisk/guide/functions.md
- docs/providers/openwhisk/guide/web-actions.md
Updated OpenWhisk documenation due to new release features (0.12).
https://github.com/serverless/serverless-openwhisk/releases/tag/v0.12.0
> Updating OpenWhisk provider documentation.

- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
Closes #4848
It fixes a bug introduced by https://github.com/serverless/serverless/pull/4677
The following command should fail at master branch and succeed at this PR branch.
```shell
rm -rf aws-nodejs && \
mkdir aws-nodejs && \
cd aws-nodejs && \
../bin/serverless create --template aws-nodejs && \
../bin/serverless deploy
```
> Fix upload artifact path

- docs/providers/aws/README.md
- docs/providers/azure/README.md
- docs/providers/google/README.md
- docs/providers/kubeless/README.md
- docs/providers/openwhisk/README.md
- docs/providers/spotinst/README.md
- docs/providers/webtasks/README.md
Add utm source to forum link in the various README.md files.
> Add utm source to forum link.

- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
Fixed empty REST API Logical Id when we have enabled Shared API Gateway. 
When I add in configuration:
```
provider:
apiGateway:
restApiId: [ID]
restApiRootResourceId: [ID2]
```
and generate cloudformation template, I have:
```
"ApiGatewayUsagePlan": {
"Type": "AWS::ApiGateway::UsagePlan",
"DependsOn": "ApiGatewayDeployment1523355957491",
"Properties": {
"ApiStages": [
{
"ApiId": {},
"Stage": "dev"
}
],
"Description": "Description1",
"UsagePlanName": "service1-dev"
}
},
```
and 
```
"ConvertLambdaPermissionApiGateway": {
"Type": "AWS::Lambda::Permission",
"Properties": {
"FunctionName": {
"Fn::GetAtt": [
"ConvertLambdaFunction",
"Arn"
]
},
"Action": "lambda:InvokeFunction",
"Principal": {
"Fn::Join": [
"",
[
"apigateway.",
{
"Ref": "AWS::URLSuffix"
}
]
]
},
"SourceArn": {
"Fn::Join": [ …
```
> Fix load restApiLogicalId when we have enabled Shared API Gateway

- package-lock.json
- package.json
Closes #4930 
update AWS SDK version in package.json
No additional feature.
- [y] Write tests
- [n ] Write documentation (This PR does not change anything features of sls)
- [y] Fix linting errors
- [y] Make sure code coverage hasn't dropped
- [n ] Provide verification config / commands / resources (This PR does not change anything features of sls)
- [y ] Enable "Allow edits from maintainers" for this PR
- [y ] Update the messages below
> update aws sdk version to 2.228.0

- docs/providers/openwhisk/events/apigateway.md
Small documentation update for the OpenWhisk provider HTTP event.
Updated the docs.
Check out the docs.
> OpenWhisk Docs: Update API Gateway with new features.

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.27.0

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes #4952
Revived getAccountId method which existed before.
This method was intentionally rewrited to getAccountInfo in #4665 without considering compatible.
npm run test
> Revived getAccountId method

- docs/providers/aws/events/apigateway.md
Closes #4753
Updated docs for using shared api gateway.
> Update shared apigateway docs

- docs/providers/aws/guide/iam.md
Currently, updating function code with `sls deploy --function` fails with the following error message: `The role defined for the function cannot be assumed by Lambda.`; if using a custom role with an autogenerated `RoleName`. So I thought it would be good to add a notice about that to the docs.
Not sure if it would be better explained elsewhere in the docs.
N/A
Deploying a service while using a custom role without the `RoleName` property. After running `sls deploy` try running `sls deploy --function`. It will fail with the error message shown in the section above.
> Add note about RoleName property in custom role

- docs/providers/azure/guide/quick-start.md
Make sure users know to use a globally unique name to not run into issues like #4968
FIX #4968
Closes #4968
Just a minor document edit.
Just a minor document edit.
> 👌 IMPROVE: Unique Name For Apps

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes #4957 
Closes #4976 
For 429 errors we do not check the retryable flag as these are retryable by default. Additionally, AWS does not set the retryable flag for them which caused the issue.
Retries on errors are now limited to 3 retries (i.e. 4 calls at maximum). If the last call still fails, the serverless run will be terminated. This prevents endless loops as found in #4976 .
Deploy any service that is likely to generate a 429. If one is received, it should retry now.
~~Write documentation~~
> Retry unconditionally when receiving 429

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #4973
Do a better job of extracting the current variable syntax for use in deep variable generation.
See test, requesting user feedback on issue
> Improve syntax extraction (fix #4973)

- lib/plugins/aws/provider/awsProvider.js
> Fix typo in awsProvider.js

- README.md
We currently specialize on AWS and the serverless framework.
cc @pmuens :)
> Add superluminar as consultancy

- docs/providers/openwhisk/examples/hello-world/node/README.md
- docs/providers/openwhisk/examples/hello-world/node/package.json
- docs/providers/openwhisk/examples/hello-world/php/README.md
- docs/providers/openwhisk/examples/hello-world/php/package.json
- docs/providers/openwhisk/examples/hello-world/python/README.md
- docs/providers/openwhisk/examples/hello-world/python/package.json
- docs/providers/openwhisk/examples/hello-world/swift/README.md
- docs/providers/openwhisk/examples/hello-world/swift/package.json
- docs/providers/openwhisk/guide/credentials.md
- docs/providers/openwhisk/guide/installation.md
- lib/plugins/create/templates/openwhisk-nodejs/README.md
- lib/plugins/create/templates/openwhisk-nodejs/package.json
- lib/plugins/create/templates/openwhisk-nodejs/serverless.yml
- lib/plugins/create/templates/openwhisk-php/README.md
- lib/plugins/create/templates/openwhisk-php/package.json
- lib/plugins/create/templates/openwhisk-php/serverless.yml
- lib/plugins/create/templates/openwhisk-python/README.md
- lib/plugins/create/templates/openwhisk-python/package.json
- lib/plugins/create/templates/openwhisk-python/serverless.yml
- lib/plugins/create/templates/openwhisk-swift/README.md
- lib/plugins/create/templates/openwhisk-swift/package.json
- lib/plugins/create/templates/openwhisk-swift/serverless.yml
Update OpenWhisk documentation for installing provider plugin.
Also, updated IBM Cloud registration instructions due to UI changes.
Closes #2895
Doc updates.
Check the docs :)
> Update OpenWhisk documentation for installing provider plugin.

- docs/providers/aws/guide/serverless.yml.md
Without `Resource: '*'` in the deny policy it doesn't actually affect anything.  The `Condition` property is applied only if the `Resource` property is first matched.
Fixed a typo in the deny stack policy in serverless.yml.md
Added `Resource: '*'` so the `Condition` property is properly applied
Deploy this demo stack
```
service: 'broken-deny-demo'
provider:
name: aws
stackPolicy:
Action: 'Update:*'
Principal: '*'
Resource: '*'
- Effect: Deny
Action:
- 'Update:Replace'
- 'Update:Delete'
Principal: '*'
Resource: '*'
Condition:
StringEquals:
ResourceType:
- 'AWS::DynamoDB::Table'
resources:
Resources:
AuthTable:
Type: 'AWS::DynamoDB::Table'
Properties:
TableName: 'important-table'
AttributeDefinitions:
- AttributeName: itemId
AttributeType: S
KeySchema:
- AttributeName: …
```
> Fix stack deny policy in serverless.yml.md

- docs/providers/aws/examples/hello-world/csharp/README.md
updated read.md
I got following error while invoking sls create command
Select-String : A positional parameter cannot be found that accepts argument 'aws-csharp'.
NA
NA
> Use serverless instead of sls command.

- lib/plugins/create/templates/aws-python/gitignore
Just noticed that that wasn't included and had to add it myself. :) Figured I'd share it back.
---
***Is it a breaking change?:*** No
> Update Python gitignore template to add *.pyc

- lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Handler.scala
Closes #XXXXX
+ Tab characters and spaces are mixed in Scala code.
+ Fix tab characters to spaces in Scala code.
> Tweaks in `aws-scala-sbt`

- README.md
I'm a consultant specialising in AWS and the serverless framework.
> Adds Andrew Griffiths as consultant

- README.md
> Update meetups github repo link

- README.md
Added slack-lunch-club to example projects.
Updated README.md
> add slack-lunch-club example project

- README.md
Add slack GitHub stats bot example project
> Add slack GitHub stats bot example project

- docs/providers/aws/guide/functions.md
Hi, first-time contributor here!
I have just started using serverless and I needed that my functions' environment variables reflected variables set in my build server's environment. I read the "environment" session of the "function" docs but found no reference to environment variables. After a while, I found out how to refer to those variables.
Given that those names are similar, I think more people might end up in that part of the docs while trying to solve the same problem so I've added a small note referring to the correct part.
> Adding note about referencing environment variables in function docs

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Closes #4926
Resource policy document is added to the provider block of the serverless.yml.
Example provider block in serverless.yml that whitelists IP 123.123.123.123, replace the dummy IP address with yours to test.
```yml
service: aws-nodejs-1 # NOTE: update this with your service name
provider:
name: aws
resourcePolicy:
Principal: "*"
Action: execute-api:Invoke
Resource:
- execute-api:/*/*/*
Condition:
IpAddress:
aws:SourceIp:
- "123.123.123.123"
```
> Add apig resource policy

- docs/providers/aws/guide/functions.md
Changed "for exemple" to "for example".
> Fix typo in guide/functions.md

- lib/plugins/create/templates/google-nodejs/package.json
Updates the `google-nodejs` template so that it points to the most recent plugin version and installs the Google Cloud Functions plugin as a `dev` dependency (rather than a `prod` dependency).
Just changed the `package.json`.
Create a new service based on the `google-nodejs` template and deploy it.
> Update google-nodejs create template

- lib/classes/Utils.js
This method is required by the EG plugin:
https://github.com/serverless/serverless-event-gateway-plugin/pull/71
> Add getLocalAccessKey method

- docs/providers/aws/guide/serverless.yml.md
Added SQS to serverless.yml file documentation.
> Add SQS event to serverless.yml file documentation

- .travis.yml
- lib/utils/segment.js
- lib/utils/userStats.js
Closes #5133
First, I added Node v10.6 and v10.7 to travis.yml ([1686c91](https://github.com/serverless/serverless/pull/5134/commits/1686c91cdd2b32876899352dc0ae4ece5d0c0969)):
https://travis-ci.org/serverless/serverless/builds/405660518
Then, I changed 2 lines ([62a4cea](https://github.com/serverless/serverless/pull/5134/commits/62a4cea94d2c1413bd90593e09c0f6ed7770039b))
https://travis-ci.org/serverless/serverless/builds/405661734
> Fix timeout parameters passed to node-fetch (#5133)

- .travis.yml
This PR updates the npm key in travis after "the great invalidation"
> update npm key in travis

- lib/plugins/aws/deploy/lib/validateTemplate.js
- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/platform/platform.js
- lib/utils/getAccessKey.js
> Dashboard Updates

- lib/utils/config/index.js
Fixes the `rc` file lookup to support both: `dev` and `prod` environments.
> Fix rc lookup

- lib/plugins/create/templates/aws-nodejs-typescript/package.json
moved "source-map-support" to devDependencies + upgraded "source-map-support" to "^0.5.6" & "typescript" to "^2.9.2"
Closes #XXXXX
- [x ] Update the messages below
> moved "source-map-support" to devDependencies + upgraded "source-map-support" to "^0.5.6" & "typescript" to "^2.9.2"

- CHANGELOG.md
- lib/plugins/aws/deploy/lib/createDeployment.js
- lib/plugins/platform/platform.js
- package.json
> Enable CI for Serverless Platform Deployments - Release Patch v1.30.1

- lib/plugins/create/templates/aws-go/Makefile
Closes #5220 
Fixes an incorrect copy/paste of the `Makefile` from the `aws-go-dep` template.
Removed the extraneous lines from the `Makefile`
Run the `aws-go` template example and test out an `sls deploy -v`
> addressing issue from #5220

- lib/plugins/platform/platform.js
Closes:
https://github.com/serverless/event-gateway/issues/499
> Fix a bug when using DynamoDB events with the Serverless Platform

- docs/providers/spotinst/examples/java8/README.md
- docs/providers/spotinst/examples/node/README.md
- docs/providers/spotinst/examples/ruby/README.md
Closes 
Small typo in the last sentence of Java 8 Readme. 
Changed the README.md files directly
Reading the file - no tests for it.
> Readme typo fixes

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.30.3

- docs/providers/aws/events/apigateway.md
Update the list available attributes available in the default API Gateway Request Templates. 
*NOTE* I also _think_ that `method` should be `httpMethod` or mentioned it's in the `requestContext`
Closes #XXXXX
> Update API Gateway Default Request Templates

- CHANGELOG.md
- RELEASE_CHECKLIST.md
- package-lock.json
- package.json
> Releasing v1.31.0

- CHANGELOG.md
- lib/plugins/aws/deploy/lib/createDeployment.js
- lib/plugins/aws/deploy/lib/createStack.test.js
- lib/plugins/aws/deploy/lib/validateTemplate.test.js
- lib/plugins/platform/platform.js
- package-lock.json
- package.json
Companion PR for the recent Dashboard changes.
> Backend state item generation and multi-region support

- lib/plugins/create/templates/cloudflare-workers-enterprise/package.json
- lib/plugins/create/templates/cloudflare-workers-enterprise/serverless.yml
- lib/plugins/create/templates/cloudflare-workers/package.json
- lib/plugins/create/templates/cloudflare-workers/serverless.yml
Closes https://github.com/cloudflare/serverless-cloudflare-workers/issues/1
The Cloudflare Workers templates did not use the recommended location for provider specific config. This change moves Cloudflare specific config from `service` property to `provider` property. It is paired with a PR in serverless-cloudflare workers https://github.com/cloudflare/serverless-cloudflare-workers/pull/2 and should be merged after a new release of `serverless-cloudflare-workers` package.
> Cloudflare: Specify config under provider property

- docs/providers/cloudflare/cli-reference/invoke.md
- docs/providers/cloudflare/guide/debugging.md
- docs/providers/cloudflare/guide/events.md
- docs/providers/cloudflare/guide/intro.md
- docs/providers/cloudflare/guide/quick-start.md
Cloudflare Workers invoke page showed as FN's invoke page. There were also points missing an explanation that Workers only support GET requests for now
Closes #XXXXX
Cloudflare Workers invoke page showed as FN's invoke page. There were also points missing an explanation that Workers only support GET requests for now
I just pasted in some stuff I had written that somehow didn't make the last PR
> Add information on invoking Workers.

- docs/getting-started.md
I added a link to the Cloudflare Workers section of the docs to the docs/getting-started.md page
Closes #XXXXX
I copied other HTML on the page and inserted the correct assets and links for Cloudflare Workers
By looking at the rendered markdown in github and copying the link and testing it.
> Add Cloudflare to docs/getting-started page.

- lib/plugins/create/templates/aws-go-dep/gitignore
- lib/plugins/create/templates/aws-go/gitignore
~~Closes #XXXXX~~
no issue
This PR is adding settings to `.gitignore` of Go templates. The content is based on a [github/gitignore repository](https://github.com/github/gitignore/blob/master/Go.gitignore).
The existing setting is only for serverless framework. I'd like to add general golang settings.
Add files that should be ignored on git.
```
$ cd $GOPATH/src/github.com/[your repo]
$ serverless create -t aws-go-dep -p sample-app
$ cd sample-app
$ git init
$ touch sample.test
$ git status
```
~~- [ ] Write tests~~
> add gitignore setting to Go template

- docs/providers/openwhisk/guide/functions.md
According to changes in https://github.com/serverless/serverless-openwhisk/issues/140
Documents  https://github.com/serverless/serverless-openwhisk/issues/140
> Doc update for openwhisk package name

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Closes #5051 
Edit `./lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js`.
Add a block to apply apiKeySourceType option to the CloudFormation template.
1. Prepare following resources.
handler(Anything, it's okay.)
```js
'use strict';
module.exports.hello = async (event, context) => {
return {
statusCode: 200,
body: JSON.stringify({
message: 'Go Serverless v1.0! Your function executed successfully!',
input: event,
}),
};
};
```
serverless.yml
```yml
service: service-for-verification
provider:
name: aws
apiGateway:
apiKeySourceType: HEADER
functions:
hello:
events:
- http:
path: hello/
method: get
```
2. Deploy it
```
sls deploy
```
3. Check the template of Cloud Formation.
You can check that ApiKeySourceType is correctly applied …
> APIG ApiKeySourceType support.

- docs/providers/aws/events/alexa-skill.md
Minor language changes were made to the alexa-skill documentation to improve readability and language tone consistency throughout the article.
> Improve language in alexa-skill documentation

- docs/getting-started.md
- docs/providers/README.md
- docs/providers/cloudflare/guide/installation.md
- docs/providers/cloudflare/guide/intro.md
- docs/providers/cloudflare/guide/quick-start.md
Links to the Cloudflare Documentation were missing in a couple of places, so links were added to fix that. Also, the documentation missed some information on installing the needed plugin.
Closes #XXXXX
I wrote some copy explaining how to add the plugin and inserted the needed links.
A quick peek will verify it quickly.
> Update Cloudflare Workers documentation

- docs/providers/openwhisk/cli-reference/create.md
- docs/providers/openwhisk/examples/README.md
- docs/providers/openwhisk/examples/hello-world/README.md
- docs/providers/openwhisk/examples/hello-world/ruby/README.md
- docs/providers/openwhisk/examples/hello-world/ruby/gitignore
- docs/providers/openwhisk/examples/hello-world/ruby/handler.rb
- docs/providers/openwhisk/examples/hello-world/ruby/package.json
- docs/providers/openwhisk/examples/hello-world/ruby/serverless.yml
- docs/providers/openwhisk/guide/functions.md
- docs/providers/openwhisk/guide/intro.md
- docs/providers/openwhisk/guide/services.md
- lib/plugins/create/create.js
- lib/plugins/create/create.test.js
- lib/plugins/create/templates/openwhisk-ruby/README.md
- lib/plugins/create/templates/openwhisk-ruby/gitignore
- lib/plugins/create/templates/openwhisk-ruby/handler.rb
- lib/plugins/create/templates/openwhisk-ruby/package.json
- lib/plugins/create/templates/openwhisk-ruby/serverless.yml
Adding Ruby support for OpenWhisk provider plugin.
Added new template files and updated docs.
`sls create -t openwhisk-ruby -p demo`
> Adding Ruby support for OpenWhisk provider plugin.

- docs/providers/google/guide/workflow.md
> Fix typo in Google workflow

- lib/plugins/create/templates/aws-go-mod/gomod.sh
Closes #5444
Insert a break
Run `make build` in the template using zsh or bash
> insert line break to suppress warning

- lib/plugins/create/templates/google-nodejs/package.json
Updates the version number to `*` to always fetch the latest version.
> Update plugin version of google-nodejs template

- CHANGELOG.md
- package-lock.json
- package.json
v1.33.2 release for 2 regression fixes
> version bump for #5500 and #5503

- docs/providers/aws/guide/credentials.md
fix typo in e77f7e & added syntax hilighting
put `{` on it's own line
view the rendered markdown diff
> fix 1st curly in the AWS required credentials

- docs/providers/cloudflare/cli-reference/invoke.md
- docs/providers/cloudflare/events/http.md
- docs/providers/cloudflare/guide/debugging.md
- docs/providers/cloudflare/guide/deploying.md
- docs/providers/cloudflare/guide/events.md
- docs/providers/cloudflare/guide/functions.md
- docs/providers/cloudflare/guide/intro.md
- docs/providers/cloudflare/guide/quick-start.md
- docs/providers/cloudflare/guide/services.md
- lib/plugins/create/templates/cloudflare-workers-enterprise/serverless.yml
- lib/plugins/create/templates/cloudflare-workers/serverless.yml
Updates docs to support new Cloudflare plugin changes: https://github.com/cloudflare/serverless-cloudflare-workers/pull/4
I updated all of the cloudflare docs to reflect the changes in config. Essentially removing the config:workers section and using the functions:events section for routing.
> update docs to new more consistent config

- docs/providers/google/guide/credentials.md
Removing the need for Owner and Editor role and updating with the required non primitive roles
Closes https://github.com/serverless/serverless-google-cloudfunctions/issues/135
Verified the roles requirement and successfully deployed to GCP without the need for owner or editor roles.
Assign only the roles outlined in this PR and deploy a sample function on GCP
> Updating roles requirement for GCF deployment

- lib/plugins/aws/invokeLocal/fixture/asyncHandlerWithSuccess.js
- lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess.js
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Closes #5522
Wrapped the invocation in a Promise that's resolved when `callback` is invoked.
```
git clone https://github.com/dschep-bug-repos/sls-5522
cd sls-5522
npm i -g serverless/serverless#fix-invoke-local-callback
```
> Fix invoke local when using callback in nodejs

- CHANGELOG.md
- package-lock.json
- package.json
Layers support!!! (after #5538  is merged)
> v1.34.0 release!

- docs/providers/aws/guide/layers.md
Currently, it isn't clear that you can make your own archive file and use that as the source for an AWS Lambda Layer. This change would clarify how to do that.
Updated doc source file.
Read diff below.
> Clarify how to make layer from a prebuilt archive

- docs/providers/aws/guide/variables.md
Quick fix in documentation. Serverless 1.34.1
> Resource doesn't work, but Resources does

- docs/providers/aws/events/apigateway.md
Fixing an outdated link in doc
> udpating link - Looks like this section moved to its own page

- docs/providers/google/guide/README.md
Added documentation in GCP section.
I ran into an issue while trying out Serverless with GCP. I noticed that it set the region to us-central1 when I deployed from the template. I wanted to use the region closest to me instead, which is their Canadian region. I tried different ways to change the region but nothing worked, and I later realized GCP only has Google Cloud Functions support in 4 regions right now.
I think if this were made clearer upfront, I wouldn't have spent time on that. I decided to add a note to the entry page in the docs for GCP if the maintainers are interested in this. This is my first PR for this repo, and I'm not familiar with it, so if this information isn't appropriate for the docs or if there's a better way to convey this information, I welcome feedback/changes. …
> Added currently supported regions for GCP functions

- docs/providers/aws/guide/layers.md
> update layers doc to reflect max of 5

- package-lock.json
fix github security notification 
ran `npm audit fix`
> run `npm audit fix` to fix gh security alert

- README.md
> direct link to video guide

- CHANGELOG.md
- package-lock.json
- package.json
- [Log AWS SDK calls in debug mode](https://github.com/serverless/serverless/pull/5604)
- [Added currently supported regions for GCP functions](https://github.com/serverless/serverless/pull/5601)
- [Update Cloudflare Templates](https://github.com/serverless/serverless/pull/5620)
- [AWS: Validate rate/cron syntax before Deploy](https://github.com/serverless/serverless/pull/5635)
- [Fix error log output](https://github.com/serverless/serverless/pull/5378)
- [Support for native async/await in AWS Lambda for aws-nodejs-typescript template ](https://github.com/serverless/serverless/pull/5607)
- [aws-csharp create template uses handler-specific artifact](https://github.com/serverless/serverless/pull/5411)
- [change behaviour on initial stack create …
> v1.36.0 release!

- CHANGELOG.md
- package-lock.json
- package.json
> 1.36.1 bugfix

- docs/providers/aws/guide/layers.md
Fix documentation - incorrect reference
Updated MD file
Generate docs in preview
- [n/a] Write tests
- [n/a] Fix linting errors
- [n/a] Make sure code coverage hasn't dropped
- [n/a] Provide verification config / commands / resources
> Fix layer doc reference to functions (should be layers)

- lib/plugins/create/templates/aws-nodejs-typescript/package.json
Increased the version of @types/aws-lambda in aws-nodejs-typescript to have additional types available.
Closes #XXXXX
> Increase @types/aws-lambda version in aws-nodejs-typescript template

- lib/plugins/create/templates/aws-scala-sbt/build.sbt
- lib/plugins/create/templates/aws-scala-sbt/project/assembly.sbt
- lib/plugins/create/templates/aws-scala-sbt/project/build.properties
- lib/plugins/create/templates/aws-scala-sbt/project/plugins.sbt
Closes #XXXXX
+ Bump up dependencies.
+ Tweak build definitions.
```
$ sls create -t aws-scala-sbt -p sls-scala
$ cd sls-scala
$ sbt sbtVersion # Please check the display of `1.2.8`
$ sbt scalaVersion # Please check the display of `2.12.8`
$ sbt assembly
$ sls deploy
$ sls invoke -f hello
```
> Update aws-scala-sbt template

- CHANGELOG.md
- bin/serverless
- package-lock.json
- package.json
Bump version number for release
remove one last platform-sdk import & dependency (non-use tho) that @exoego spotted
updated changelog
> version bump & remove last unused platform-sdk import

- scripts/postinstall.js
> Enable tab completion for slss shortcut

- docs/providers/aws/guide/variables.md
YAML example renamed from "Resource" to "Resources".
Closes #XXXXX
> Fix typo in Multiple Configuration Files example

- lib/classes/CLI.test.js
> fixed cli tests when running in debug mode

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.37.0

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
- lib/plugins/package/lib/zipService.js
Closes #5614
cc @lolcoolkat
If on windows, the handler files when added to the zip have their mode modified to add the execute permission.
Install with `npm i -g serverless/serverless#win-go` and  deploy the `aws-go` template from a windows machine and invoke the lambda
> Support deploying GoLang to AWS from Windows!

- docs/providers/aws/events/s3.md
> Updating cloudformation resource reference url

- CHANGELOG.md
- package-lock.json
- package.json
> Releasing v1.38.0

- docs/providers/aws/events/websocket.md
Improvement of the aws websocket event documentation.
Added:
* List of predefined routes
* example serverless.yaml including a custom route and the predefined routes
* a "hint" on how to protect the websockets backend with authorizers or with the `$connect` route.
* small explanation on how to send a message to a ws-client
Closes none
Writing the Markdown, using examples from my serverless-websockets test run.
-
> Add details to websocket documentation

- lib/plugins/print/print.js
- lib/plugins/print/print.test.js
- lib/utils/autocomplete.js
fixes oversight in #5840
fix the import in print & autocomplete
`sls print`
> follow up fixes for #5840 breaking sls print & autocomplete

- README.md
> Add Geniusee to Consultants list

- lib/Serverless.js
Just an unused code cleanup
CI check is not failing:)
> Cleanup Serverless.js file from unused code

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
Closes #5891
added fallback for when no runtime is defined
ON WINDOWS:
```
sls deploy
sls deploy function -f hello
npm i -g serverless/serverless#sls-5891
sls deploy function -f hello
```
> [SLS-6891] fix regression with golang check on windows

- lib/classes/Error.js
Closes #XXXXX
This pull request fixes the "Your Environment Information" line length so that it aligns with the "Get Support" and "Serverless Error" lines above.
> Align error logging

- CHANGELOG.md
- package-lock.json
- package.json
> Version 1.40.0 release

- bin/serverless
Closes #XXXXX
Code to remove comments
> The code for removing comments is easy to read

- lib/plugins/aws/utils/formatLambdaLogEvent.js
Removed useless variable assignment
CI check is not failing
> Remove useless variable assignment

- lib/utils/yamlAstParser.js
Very minor refactoring
Squashed identical if branches
CI check is not failing
> Merge identical IF-branches

- .eslintrc.js
Mark .eslintrc.js as the [root config](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) for the project. This stops ESLint from looking in parent directories for more .eslintrc files.
N/A
N/A
> eslint: Mark as root config

- lib/plugins/aws/invokeLocal/index.js
Closes #5990 
- Download the layer to `layerContentsCachePath` first and the copy to `layerContentsPath`. This way subsequent runs will skip download and just used cache with valid files instead of empty directory due to current bug
```yml
service: layer-cache-bug
provider:
name: aws
functions:
hello:
layers:
- <your-layer-arn-here>
```
`handler.py`
```py
import your_layer
return "hello"
```
```sh
serverless invoke local -f hello --docker
```
> #5990: Fix layer download caching during invoke local docker

- CHANGELOG.md
- package-lock.json
- package.json
/cc @dschep @eahefnawy @ganeshvlrk @billfine
> Releasing v1.41.0

- lib/plugins/create/templates/openwhisk-python/README.md
Closes #XXXXX
Fix a minor bug in Readme.MD file of OpenWhisk Python template. 
> Fix markup error with Authentication value

- docs/providers/aws/guide/credentials.md
> Drop duplicate paragraph in aws/guide/credentials

- docker-compose.yml
Closes #XXXXX
+ Specified docker image version of `hseeberger/scala-sbt`.
+ Before: Download sbt and Scala every execution because does not match versions between the docker image and aws-scala-sbt template.
+ `$ tests/templates/integration-test-template aws-scala-sbt sbt assembly`
> Improve integration test of aws-scala-sbt

- CHANGELOG.md
- package-lock.json
- package.json
/cc @ganeshvlrk @billfine @eahefnawy @dschep
> Releasing v1.42.0

- docs/providers/aws/guide/packaging.md
> Adding a more specific example of how to package individually

- docs/providers/cloudflare/guide/intro.md
- docs/providers/cloudflare/guide/quick-start.md
> Update cloudflare documentation

- docs/providers/aws/events/apigateway.md
Just a little typo "Multipe" -> "Multiple"
Just fixed a tiny typo
It's just a single letter
> Update very minor typo in apigateway.md

- RELEASE_CHECKLIST.md
- scripts/prs-since-last-tag
Updates the documentation and tooling so that the current release process is reflected.
Just updated the documentation and our scripts.
> Update release process docs and toolings

- lib/classes/Service.js
copy a field from config to internal representation of config
> Support for SFE outputs in config

- CHANGELOG.md
- package-lock.json
- package.json
release for SFO outputs support
>  version bump for version 1.43.0

- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js
- lib/plugins/aws/package/compile/events/cloudWatchLog/index.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- lib/plugins/aws/package/compile/events/iot/index.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/schedule/index.js
- lib/plugins/aws/package/compile/events/sns/index.js
- lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
- lib/plugins/aws/package/compile/events/websockets/lib/permissions.test.js
Closes https://github.com/serverless/serverless/issues/5365
The previous PR(https://github.com/serverless/serverless/pull/5366#issuecomment-486528502) could not be reopened due to "The repository that submitted this pull request has been deleted.", so this PR was created. @muja 
Replace `AWS::URLSuffix` with hardcode `<service-name>.amazonaws.com`.
Deploy a restApi in region cn-north-1.
Examples:
* `sls create -t nodejs-aws`
* Modify serverless.yml like this:
```yml
service: aws-nodejs
provider:
name: aws
region: cn-north-1
endpointType: regional
functions:
hello:
events:
- http:
method: get
```
* `sls deploy -v`
Before:
```bash
Serverless: Operation failed!
An error …
```
> Solve the problem of principal format in China region

- CHANGELOG.md
- lib/classes/PluginManager.js
- package-lock.json
- package.json
closes #6181
add global node modules dir to import path too, but after the one nested in sls install path. 
```yarn global add github:serverless/serverless#yarn-install-sfe-bug```
> fix yarn install of SFE integration

- lib/plugins/create/templates/aws-scala-sbt/build.sbt
- lib/plugins/create/templates/aws-scala-sbt/serverless.yml
- lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/ApiGatewayResponse.scala
- lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Handler.scala
Closes #XXXXX
+ Fix `scalaVersion` in `build.sbt`.
+ Migrate codebase to Scala 2.13.0.
```
$ tests/templates/integration-test-template aws-scala-sbt sbt assembly
```
>  Update Scala version to 2.13.0 for aws-scala-sbt template

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
There were some ugly typos, and message was configured to appear in one long line, which is not nice.
> Improve user message

- docs/providers/aws/guide/packaging.md
fixed a small typo.
GitHub web editor, fixed the spelling.
Read/spell check it.
> fixed a typo 🖊

- README.md
> Remove README redundant link

- CHANGELOG.md
- package.json
> Release v1.46.0

- README.md
Added Onica as a consultant in the README.
Added a line to the README.md file.
Visit the links in the added text and find the Onica logo at https://aws.amazon.com/partners/premier/
> Add Onica as a Consultant

- docs/providers/aws/events/alb.md
> Typo fix in AWS ALB event documentation

- lib/plugins/aws/package/compile/events/s3/index.test.js
Fixes a test where an async function was not returned.
Return the async function.
See that the unit tests are working fine.
- x ] Update the messages below
> Fix async S3 test

- lib/plugins/interactiveCli/setupAws.js
Closes https://serverlessteam.atlassian.net/browse/PLAT-1381
add a stdout write with the message 
> Log message out when user says no to aws setup

- lib/plugins/interactiveCli/setupAws.js
Closes https://serverlessteam.atlassian.net/browse/PLAT-1382
always use the string `'default'` instead of prompting
> If user has no profiles, always create them the default profile

- lib/plugins/interactiveCli/setupAws.js
> actually update the right aws creds link interactive setup aws

- docs/providers/aws/events/streams.md
Add a missing colon in the example yml file.  
https://serverless.com/framework/docs/providers/aws/events/streams/
``` yml
- stream
type: kinesis
arn:
Fn::Join:
```
``` yml
- stream:
type: kinesis
arn:
Fn::Join:
```
N/A
N/A
N/A
> Add the missing colon

- .travis.yml
- CHANGELOG.md
- package.json
> Release v1.48.0

- lib/plugins/interactiveCli/initializeService.js
Change the Python project in the interactive prompt to aws-python3
> Use Python3 for Python in interactive setup

- docs/dashboard/safeguards.md
- docs/getting-started.md
> Fixing broken link for Node install.

- CHANGELOG.md
- package.json
draft release https://github.com/serverless/serverless/releases/edit/untagged-9642a6bf4ca564c3a4c5
> 1.48.1 patch release

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
Closes #6364 
I added a new property to Lambda (non-proxy) integration default request template.
I just added a new line in the template
**serverless.yml**
```yaml
service: SampleService
provider:
name: aws
functions:
HelloWorld:
events:
- http:
path: hello-world
method: get
```
**index.js**
```js
module.exports.handler = async event => {
return {
body: JSON.stringify(event)
};
};
```
You should see the new property (requestPath) in the response body …
> Issue 6364 request path

- CHANGELOG.md
- lib/plugins/aws/invoke/index.test.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/lib/validate.js
- lib/plugins/aws/lib/validate.test.js
- lib/plugins/aws/logs/index.test.js
- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
- package.json
Closes #6414
Add a step to `getCredentials` which checks metadata api too
In CodeBuild, install sls with `npm i -g serverless/serverless#support-for-ecs-metadata-creds` and run a build
> Fix #6414 by checking for ec2 metadata

- docs/providers/aws/events/s3.md
We had 2 guys in the Slack channel that tried to use this feature and it didn't work because they were using an old version. I assume that we have more users that didn't reach the Slack Channel. Adding this can help people in that situation.
> Add note for supported version of existing bucket feature

- CHANGELOG.md
- lib/plugins/aws/lib/validate.js
- lib/plugins/aws/lib/validate.test.js
- package.json
fixes #6436
the creds fail-fast check is only on deploy/remove/info/logs commands
```
sls package # error!
rm ~/.aws
npm i -g serverless/serverless#hotfix-creds-pkg-bug
sls package
```
> Only check creds on deploy

- .gitignore
- docs/providers/aws/README.md
- docs/providers/aws/events/cognito-user-pool.md
- docs/providers/aws/events/event-bridge.md
- lib/plugins/Plugins.json
- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/index.test.js
- lib/plugins/aws/customResources/resources/eventBridge/handler.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/eventBridge.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/permissions.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js
- lib/plugins/aws/customResources/resources/package.json
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/eventBridge/index.js
- lib/plugins/aws/package/compile/events/eventBridge/index.test.js
- lib/utils/fs/getTmpDirPath.js
- lib/utils/fs/getTmpDirPath.test.js
- tests/integration-all/event-bridge/service/core.js
- tests/integration-all/event-bridge/service/serverless.yml
- tests/integration-all/event-bridge/tests.js
- tests/utils/eventBridge/index.js
Closes #6363
Adds support for the new AWS EventBridge service (see discussion in issue mentioned above for more 
details).
Added the logic via raw SDK calls which are wrapped in a custom CloudFormation resource.
Use the following `serverless.yml` file:
```yml
service: test
provider:
name: aws
functions:
test:
events:
- eventBridge:
schedule: rate(1 minute)
- eventBridge:
eventBus: custom-event-bus
pattern:
source:
- serverless.test
- eventBridge:
eventBus: arn:aws:events:us-east-1:12345:event-bus/existing-event-bus
pattern:
source:
- serverless.test
```
**NOTE:** You can find more config options in the service definition of https://github.com/serverless/serverless/issues/6363#issuecomment-510853941
_**Note: Run `npm run …
> Add EventBridge event source
