serverless/serverless

- docs/providers/aws/cli-reference/invoke-local.md
- docs/providers/google/cli-reference/invoke-local.md
- docs/providers/openwhisk/cli-reference/invoke-local.md
- lib/plugins/invoke/invoke.js
- lib/plugins/invoke/invoke.test.js
Closes #5096 
- sls invoke local should make it possible to override environment variables
- Added --env option to `sls invoke local` to override environment vars in lib/plugins/invoke/invoke.js
- Usage: --env NAME1=val1 --env NAME2=val2 ...
Run:
`npm run test lib/plugins/invoke/`
`sls invoke local -f helloWorld ---env NAME1=val1 --env NAME2=val2`
> Invoke local override env

- lib/classes/PluginManager.js
- lib/plugins/lib/validate.js
- lib/plugins/lib/validate.test.js
- lib/plugins/print/print.js
- lib/utils/autocomplete.js
- lib/utils/getCacheFilePath.js
- lib/utils/getServerlessConfigFile.js
- lib/utils/getServerlessConfigFile.test.js
- package-lock.json
Fix #5242
Do this by first supplying the `servicePath` in `~/lib/plugins/lib/validate.js` and `~/lib/plugins/print.js` in a consistent manner with the code in `~/lib/classes/PluginManager.js`.  Then, provide a default of `process.cwd()` for `servicePath` in `getCacheFilePath` and `getServerlessConfigFile`.
As per #5242, this bug impacts the execution of Serverless with a `servicePath` that is not the current working directory.  One could re-create this circumstance.
I have offered a new test to validate this behavior in `getServerlessConfigFile.test.js`, the corresponding change in `getCacheFilePath.js` seemed too trivial to warrant the code.  Can provide that too if desired.
Paging @eahefnawy as per discussion in issue #5242 
***Is this ready for review?:*** …
> Provide Consistent Service Path (Fix #5242)

- lib/plugins/aws/lib/cloudformationSchema.js
- lib/plugins/aws/lib/cloudformationSchema.test.js
- lib/utils/fs/parse.js
- lib/utils/fs/parse.test.js
This PR adds support for shorthand CloudFormation syntax, e.g. `!Ref`, `!GetAtt` and !Join.
This should not be a breaking change, least I don't know any cases where `!Something` syntax is used in serverless.yml.
This feature leverages `js-yaml` module's custom schema.
```yaml
service: shorthand-cf
provider:
name: aws
- Effect: "Allow"
Action:
- "kms:Decrypt"
Resource: !Join
- ":"
- - "arn:aws:kms"
- !Ref AWS::Region
- !Ref AWS::AccountId
- ":key/CMK_key_ID"
- Effect: "Allow"
Action:
- "s3:*"
Resource:
- !Join
- ":"
- - "arn:aws:s3::"
- !Ref "MyBucket"
- !Join
- ":"
- - "arn:aws:s3::"
- !Ref "MyBucket"
- "/*"
functions:
hello:
resources:
Conditions:
AndCondition: !And 
- !Not [!Equals ["prod", "${opt:stage, …
```
> Add Support for Shorthand CloudFormation Syntax

- docs/providers/aws/guide/variables.md
Please check the following issue: https://github.com/serverless/site/issues/345
This minor update fixes the way anchor links were written thereby fixing the cause behind the above issue.
> fixed anchor links in aws/guide/variables.md file

- lib/plugins/aws/invokeLocal/index.js
When running one of the SLS commands I spotted wierd log `Serverless: INVOKING INVOKE`
It feels as something committed in by mistake
/cc @lewisf
> Remove invalid log

- lib/plugins/info/info.js
- lib/plugins/info/info.test.js
#2116 
add lib/validate related to 
https://github.com/serverless/serverless/blob/master/lib/plugins/remove/remove.js
command
```
bin/serverless info
```
result
```
Error --------------------------------------------------
This command can only be run in a Serverless service directory
Issues:        forum.serverless.com
Your Environment Information -----------------------------
OS:                     darwin
Node Version:           8.10.0
Serverless Version:     1.32.0
```
npm test
before
```
1681 passing (20s)
1 pending
```
```
=============================== …
```
> validate if serverless.yml exists when running sls info command

- lib/plugins/aws/invokeLocal/invoke.py
Closes #4544
Add context.log function into FakeLambdaContext which class is used while running a handler by 'invoke local' command.
I implement context.log function as redirect function to standard output.
You can reproduce this problem as blow.
Prepare the source code like this.
```
❯ cat handler.py
import json
body = {
"message": "Go Serverless v1.0! Your function executed successfully!",
"input": event
}
response = {
"statusCode": 200,
"body": json.dumps(body)
}
context.log('log function experimental invoking.')
return response
```
and execute it by `invoke local`, then you can see the exception.
```
❯ sls invoke local -t -f hello
Traceback (most recent call last):
File "/Users/aki/.nodebrew/node/v8.11.3/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/ …
```
> fix: Implement context.log function for invoke local command on Python environment.

- docs/providers/aws/cli-reference/deploy-function.md
- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/deployFunction/index.test.js
In this PR I fixed an issue (or a not implemented feature), according the function handler name of an AWS Lambda, while deploying a single function. (using `deploy -f / --function`)
Former to that fix, when deploying a single function even if you change the code and the handler file / handler method , changing the *handler name* in the `serverless.yml` was not affected.
(BTW other configuration such as memorySize, description,  timeout, etc.. are affected as expected)
Closes #XXXXX
As done for others configuration ( such as memorySize, description,  timeout, etc..)
while  `updateFunctionConfiguration() {...} ` in [/lib/plugins/aws/deployFunction/index.js](https://github.com/serverless/serverless/blob/cfc2ac81f50427e343673e9ed2e2be6cafa99097/lib/plugins/aws/deployFunction/index.js#L114) - …
> Update handler name when deploy a single function

- lib/plugins/create/templates/aws-go-dep/Makefile
- lib/plugins/create/templates/aws-go/Makefile
Closes #XXXXX
no issues
I fixed coding style in Makefiles. `build` should be treated like `clean` and `deploy` in same Makefile.
https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
I added 2 `.PHONY:`s before build commands.
$ cd $GOPATH/src/github.com/[your repo]
$ serverless create -t aws-go-dep -p sample-app
$ cd sample-app
$ make build
~~- [ ] Write tests~~
~~- [ ] Write documentation~~
> fix Makefile style for Go template

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js
Closes #5326
Added a conditional check when cacheControl property is present on a cors property for a function, it will add the value as the header for the response.  This was only built for AWS API Gateway.
I have modified https://github.com/serverless/examples/tree/master/aws-node-simple-http-endpoint example to include the cors change.  The cacheControl property is the only new thing that I added.
```
service: serverless-simple-http-endpoint
frameworkVersion: ">=1.1.0 <2.0.0"
provider:
name: aws
functions:
currentTime:
handler: handler.endpoint
events:
- http:
path: ping
method: get
cors:
origin: '*'
allowCredentials: true
cacheControl: 'max-age=600, s-maxage=600'
maxAge: 600
headers:
- Content-Type
- X-Amz-Date
- Authorization
- X-Api-Key
- X-Amz-Security-Token
- …
```
> Add CacheControl headers on the OPTIONS response in AWS API Gateway

- lib/classes/CLI.js
- lib/classes/CLI.test.js
Closes #5050 
After the CLI get the args, before the pass to the 'minimist' I'm handling the string values and encode their to a base64 string like a workaround. After the minimist process, I get again the values and decoded again to get the original values.
If we test the CLI with numbers and numbers like strings always they going to be treated as strings:
Also, there is a **unit test** added:
> "should only return numbers like strings when numbers are given on options"
If we only executed it, we'll we have:
> Avoid args being rounded and converted to numbers

- bin/serverless
Closes #5348 
Add `.then(() => process.exit(0))` after `serverless.run()` in bin file.
> Fix bin process not always exiting

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
Closes https://github.com/FidelLimited/serverless-plugin-warmup/issues/25
The problem that this feature solves is that, if you set a service level artifact, functions marked as `package: individually: true` are not packaged individually as you would expect but use the service artifact instead.
This change simply allows you do to do:
```yml
package:
artifact: my-app.zip
function:
...
myIndividualFunc:
...
package: 
individually: true
```
So all the functions will use the `my-app.zip` artifact but `myIndividualFunc` will be packaged normally
It's a pretty trivial change. Simply check if the function is set to package individually and, if so, package it individually. :) 
I've added a test that proves that the feature works and doesn't break existing functionality.
It's pretty trivial to …
> Let function package.individually config override service artifact

- docs/providers/aws/events/cognito-user-pool.md
Reverts serverless/serverless#5384 please
The documentation is correct. The prefix CognitoUserPool must be there.
> Revert "Update cognito-user-pool.md"

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
To make less work for contributors, I factored out bug reports and feature requests into two separate gh issue templates. 
Closes #5350
The UI for selecting templates feature is [built into github](https://blog.github.com/2018-05-02-issue-template-improvements/). The markdown front matter is what drives that UI.
I took the existing issue template copy and split it into two specialized sets of copy, each for its own singular purpose with minor adjustments.
I don't think there's a way to see the github UI without merging but the pattern is the same for all repositories.
You can view rendered markdown.
> break single general issue template into two specialized templates

- lib/plugins/aws/provider/awsProvider.js
With these changes Serverless Framework should be compatible with
AWS CLI, so that these instructions for assuming a role work
out-of-the-box:
https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html
Related to #5048
This sets the AWS_SDK_LOAD_CONFIG environment variable which allows
AWS SDK to read ~/.aws/config, and implements the tokenCodeFn
callback which asks the user to enter a MFA code. Credentials are
also cached to avoid creating the object multiple times, which
makes MFA work properly when multiple requests are made.
Deploy any project using an AWS profile that has role_arn, source_profile and mfa_serial configured in ~/.aws/config.
> Assume role and MFA support for Serverless CLI

- docs/providers/openwhisk/guide/services.md
Changed the services documention of openwish
Here is an easier way to invoke a local serverless installation.
- executables have symlinks in `node_modules/.bin` folder
- npx is an easier way to invoke these local executables: (ref: https://blog.scottlogic.com/2018/04/05/npx-the-npm-package-runner.html)
Thanks for serverless framework 👍
instead of calling the local installation with
`node ./node_modules/serverless/bin/serverless deploy`
We can use
`node node_modules/.bin/serverless deploy`
Or we can use
`npx serverless deploy`
(this is bundled by default with npm 5.2.0 and later
run it locally 👍 
doc about npx: https://blog.scottlogic.com/2018/04/05/npx-the-npm-package-runner.html
https://github.com/npm/npm/releases/tag/v5.2.0
***Is it a breaking …
> Updating services.md > Invoking Serverless locally

- tests/simple-suite/tests.js
rollback was using a unix timestamp, but  expects an ISO8601 timestamp it seems
Fix simple integration test
rollback was using a unix timestamp, but  expects an ISO8601 timestamp it seems
run `npm run simple-integration-test`
> Fix integration test

- docs/providers/kubeless/guide/quick-start.md
Changed references to "hello" function -which does not exist in the proposed [kubeless-nodejs](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/kubeless-nodejs/serverless.yml) template- to function "capitalize" and updated example in the "Kubeless - Quick Start" documentation page.
> Fix wrong example function name.

- lib/plugins/plugin/lib/utils.js
Closes #5480
Create an `HttpsProxyAgent` to pass to `fetch` if any relevant env vars are set
run `sls plugins list` with an `https_proxy` env var set.
> Create an HttpsProxyAgent for plugin list if necessary

- lib/classes/CLI.js
- lib/classes/CLI.test.js
Closes #5491
- Changed the arguments parsing logic to encode all the arguments, which simplifies the decoding later, to avoid errors like the one from #5491.
- Implemented decoding of nested objects, which is required to decode encoded commands.
- Some of values were not converted back from base64, which resulted in spurious errors with base64 strings. (This was caused by nested arrays, like commands, not being converted back, combined with the wrong assumption that commands always occur before options. It is not always true, as the added test case demonstrates.)
- Some other values were converted *from* base64, but they weren't base64 in the first place, which resulted in junk binary data. (This was due to the invalid assumption that only odd-numbered values   need to be converted.)
Try …
> Fix issues with PR #5631 causing base64 errors

- CHANGELOG.md
- lib/classes/CLI.test.js
- package-lock.json
- package.json
patch release for regression causing `sls depoy --verbose --stage foobar` to fail.
>  version bump for #5492

- lib/plugins/aws/invokeLocal/invoke.py
Fixes #5499
invoke local was changed in #5355 to check for a tty by calling the `tty` executable, but it was implemented with `subprocess.run` which was added in Python 3.5 so it doesn't work with Python 2.7 projects
Switched to the older `subprocess.check_call`
```
npm i -g serverless/serverless#fix-py27-invoke-local
sls create -t aws-python
```
> Don't use py3.5+ only subprocess.run in python invoke local

- lib/plugins/aws/logs/index.js
- lib/plugins/aws/logs/index.test.js
Closes #5497
Used bluebird's `Promise.delay` instead of `setTimeout` so that `showLogs` continues to extend the promise chain so that it doesn't return, which would then cause #5349 to exit the process.
```
sls create -t aws-nodejs -p test -n test
cd test
sls deploy
sls invoke
sls logs -t # this will exit immediately, which is the bug
npm i -g serverless/serverless#fix-5497
sls invoke -t # this should not exit
```
> Convert logging to return a promise so that #5349 no longer causes #5497

- docker-compose.yml
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/create/templates/aws-python3/serverless.yml
AWS now supports Python3.7 in Lambda!
https://aws.amazon.com/blogs/compute/python-3-7-runtime-now-available-in-aws-lambda/
Updated the python3 template to use the python3.7 runtime & invoke local to support it too.
* replaced string in python3 template
* changed check for python runtime in invoke local
```
npm i -g serverless/serverless#python3.7
sls create -t aws-python3 -n py37 -p py37
cd py37
sls deploy
sls invoke -f hello
```
> Python3.7 support!!!

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Closes #5511
This is a bug where the invoke local handler attempts to parse the JSON strings supplied via `--data` and `--context` whether or not they were actually provided.  This currently manifests as the inability to pass a `--context` param unless a `--data` param is also supplied.  Currently, if the `--data` param is not supplied, but the `--context` param is, the context JSON string will not be properly parsed and will be passed to the function as a string instead of correctly parsed to an object.
I added a simple existence check before parsing both the `data` and `context` options.  Now, if one or both do not exist, serverless will not attempt to parse them.  This feels a lot more intentional than the previous behavior which relied on routinely throwing and silently swallowing …
> Fix bug where code attempts to parse nonexistent data / context objects

- lib/classes/Service.js
- lib/classes/Service.test.js
- lib/utils/getServerlessConfigFile.js
- lib/utils/getServerlessConfigFile.test.js
From discussion in #4787 this is the low-hanging fruit that still adds useful functionality.
For the (undocumented) use of `serverless.js` as a config file, it is quite useful to be able to return a promise for a config, since nearly all node APIs and packages that do something interesting are async.
As a simple example, looking up VPC configuration by name.
Fortunately, promises (including bluebird) are specified that if a promise-like value (ie. has a function-typed `then` property) would be used to resolve a promise, it gets unwrapped and the resolution value is instead used (or if it rejects, the outer promise rejects also). This handles the "might be a promise, might not be" case straightforwardly.
Oddly, I found the config is loaded in at least two places. Seems like something wiggy …
> Support returning promises from serverless.js

- docs/providers/aws/examples/README.md
- docs/providers/azure/examples/README.md
- docs/providers/google/examples/README.md
- docs/providers/openwhisk/examples/README.md
Examples listed in our docs were pointing to Github and in this PR, I've updated them to point to sls website instead since we now have Examples Explorer
Updated links in respective .md files
Since this a content update, please refer to the changed files to confirm if the updated links were referenced correctly.
> updated docs example links from github to serverless

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Closes https://github.com/serverless/serverless/issues/4593
Modified `/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js` to look for `minimumCompressionSize` in provider configuration and apply to the Cloudformation template for ApiGateway.
1. create `serverless.yml`
```yml
service: service-for-verification
provider:
name: aws
apiGateway:
minimumCompressionSize: 1024
functions:
hello:
events:
- http:
path: hello/
method: get
```
2. deploy
```bash
sls deploy
```
3. validate cloudformation template
```json
{
"ApiGatewayRestApi": {
"Type": "AWS::ApiGateway::RestApi",
"Properties": {
"MinimumCompressionSize": 1024
}
}
}
``` 
> Add support for API Gateway payload compression

- package.json
- scripts/pre-release.js
we dont actually use this and its blocking release now.
Releases just happened to work in the past because node 4 would do the deploy which doesnt
run the prerelease script
> Remove prepublish script

- docs/providers/google/cli-reference/invoke-local.md
Closes #XXXXX
There is a format issue in the documentation for "google/cli-reference/invoke-local
Fixed the markdown
Use a markdown editor
> Update invoke-local.md, fix typing error

- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Closes #5534 
Parsing `logRetentionInDays` as Integer.
If it is a numeric string like `"42"`, it is accepeted as integer.
I think the test code is  sufficient to verify, since it is just fixing trivial regression of type mis-handling.
> Fix logRetentionInDays regression in AWS

- .appveyor.yml
- docs/providers/aws/cli-reference/invoke-local.md
- lib/plugins/aws/invokeLocal/fixture/handler.rb
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/invokeLocal/invoke.rb
Adds Ruby lambda support for `invoke local` 
Closes #5545
I followed the pattern for calling Python lambda's via `invoke local`
```
mkdir aws-ruby-example
cd aws-ruby-example
serverless create --template aws-ruby
serverless invoke local -f hello
```
Here's my result, using a local checkout of this branch:
```
➜  aws-ruby-example ~/work/serverless/bin/serverless invoke local -f hello
{"statusCode":200,"body":"\"Go Serverless v1.0! Your function executed successfully!\""}
```
> `invoke local` support for Ruby lambdas

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
fixes #5563
call invoke local's env var setting code before invoke's env var setting code (which is what handles the `--env` option)
`serverless.yml`:
```yaml
service: test
provider:
name: aws
functions:
test:
handler: handler.test
environment:
FOOBAR=foo
```
`handler.js`:
```javascript
module.exports.test = () => process.env.foobar
```
then
```
sls invoke -f hello --env FOOBAR=bar
```
with master will print `foo` with this branch will print `bar`
> set env vars from --env last in invoke local

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #5558 
Remove whitespace cleaning (`.replace(/\s/g, '');`) which seems unnecessary.
I am suprised that removing it break nothing.
I am not sure that it is essentially unnecessary...
`npm test`
> BREAKING-CHANGE Preserver whitespace in variable fallback

- package-lock.json
- package.json
Closes #3833
Projects using AWS have some trouble using AWS CLI profiles. While support for profiles is now baked into the serverless framework, the version locked for the `aws-sdk` package has bugs with using profiles. 
Creating/checking the S3 bucket for a new project would fail during `sls deploy`, due to some problem in `aws-sdk`. Updating the `aws-sdk` package avoids the bug.
Using serverless 1.34.1, linked to aws-sdk 2.239.1, sls fails to deploy a project for the first time while using an AWS Profile with MFA. 
After upgrading to aws-sdk 2.373.0, sls succeeds to deploy the project for the first time using the AWS Profile with MFA.
> Upgrade to aws-sdk v2.373.0

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Restores ability to have spaces in variable refs which was broken by #5571
if the variable being cleaned isn't surrounded by `"` white space is stripped as it was before
make a config file with a variable reference with a space in it
> restore support for variable refs with spaces in them

- CHANGELOG.md
- package-lock.json
- package.json
- scripts/prs-since-last-tag
- [Fix logRetentionInDays regression in AWS](https://github.com/serverless/serverless/pull/5562)
- [`invoke local` support for Ruby lambdas](https://github.com/serverless/serverless/pull/5559)
- [Set reserved concurrency in cfn template even if zero](https://github.com/serverless/serverless/pull/5566)
- [Fix `--env` being shadowed when using `sls invoke local`](https://github.com/serverless/serverless/pull/5565)
- [Preserve whitespace in variable literal defaults](https://github.com/serverless/serverless/pull/5571)
- [Drastically improved dev dependency exclusion performance](https://github.com/serverless/serverless/pull/5574)
- [Extend ${cf} syntax to get output from another region](https://github.com/serverless/serverless/pull/5579)
- [Upgrade aws-sdk dep to fix issues with using AWS …
> v1.35.0 release!

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/zipService.test.js
Fixed a regression for some users where the `package: include: ` section of their config pointed to files outside the current working directory. The performance impact of this is directly correlated with how many patterns (not files behind those patterns) a user specifies inside their include, and should therefore not be a problem.
Closes #5600 
Added the `include` patterns specified by the user to the initial glob matching.
A test was added for this specific use case, which now passes.
> fix: fixed regression preventing including files outside working dir

- CHANGELOG.md
- package-lock.json
- package.json
- [Update gitignore](https://github.com/serverless/serverless/pull/5599)
- [fix: fixed regression preventing including files outside working dir](https://github.com/serverless/serverless/pull/5602)
- [Comparison since last release](https://github.com/serverless/serverless/compare/v1.35.0...master)
> version bump to fix regression out of project includes

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Logging AWS SDK calls when SLS_DEBUG is activated.
Closes #5603 
Configure the AWS.config.logger when SLS_DEBUG environment is activated.
In that case the AWS.config.logger will simply use the serverless.cli.log function to log AWS SDK calls.
Based on the official AWS documentation for logging :
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/logging-sdk-calls.html
In any serverless projects :
```
SLS_DEBUG=true serverless deploy
```
The console output should show the AWS SDK calls made by serverless :
```
...
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.653s 0 retries] describeStacks({ StackName: 'aws-nodejs-dev' })
Serverless: [AWS cloudformation 200 0.416s 0 retries] describeStackResource({ StackName: 'aws-nodejs-dev',
LogicalResourceId: …
```
> feat(log): Log AWS SDK calls in debug mode

- docs/providers/aws/events/apigateway.md
The link for "HTTP Endpoints with AWS_IAM Authorizers" was broken. Changed link from:
(#http-endpoints-with-aws-iam-authorizers) to (#http-endpoints-with-aws_iam-authorizers)
Closes #XXXXX
- [ X] Enable "Allow edits from maintainers" for this PR
- [X ] Update the messages below
> AWS Docs: Fixing link for HTTP Endpoints with AWS_IAM..

- docs/providers/aws/cli-reference/slstats.md
> updating with more detail about service tracking

- docs/providers/cloudflare/cli-reference/invoke.md
- docs/providers/cloudflare/events/http.md
- docs/providers/cloudflare/guide/debugging.md
- docs/providers/cloudflare/guide/deploying.md
- docs/providers/cloudflare/guide/events.md
- docs/providers/cloudflare/guide/functions.md
- docs/providers/cloudflare/guide/intro.md
- docs/providers/cloudflare/guide/quick-start.md
- docs/providers/cloudflare/guide/services.md
- lib/plugins/create/templates/cloudflare-workers-enterprise/package.json
- lib/plugins/create/templates/cloudflare-workers-enterprise/serverless.yml
- lib/plugins/create/templates/cloudflare-workers/package.json
- lib/plugins/create/templates/cloudflare-workers/serverless.yml
- package-lock.json
Closes #5619 
I did the following:
* Bumped the version of the serverless-cloudflare-workers plugin specified in the package.json files of the Cloudflare templates from 0.1.1 to 1.0.5
* Corrected function `name` properties in serverless.yml files of the Cloudflare templates so that the value of the `name` property matches the declared name of the function (serverless-cloudflare-workers throws an exception on `serverless deploy` if these names do not match).
* Updated the docs to reflect this.
To reproduce the issue, you can simply `serverless create --template cloudflare-workers`, update the generated serverless.yml file with your Cloudflare account id, zone id, and zone url (in the `events.http.url` property), then attempt to `serverless deploy`. This will fail with the message "Cannot …
> Issue #5619 - Update Cloudflare Templates

- docs/providers/openwhisk/guide/credentials.md
Closes #4777 by adding documentation to run a required command.
Added docs.
Set up IBM Cloud CLI on a dev machine and attempt to deploy the OpenWhisk template without performing the added step. Note that it will fail, claiming you need to set an `OW_APIHOST` env var.
> Add step to populate ~/.wskprops file to OpenWhisk docs.

- README.md
Add Ruby to supported languages.
> Add Ruby to supported languages in README.md

- lib/plugins/aws/package/compile/events/schedule/index.js
- lib/plugins/aws/package/compile/events/schedule/index.test.js
Closes #3306
* Add validation to `compileScheduledEvents` so users can find error before deploy.
* Note: `cron` validation checks only number of fields, since it requires [very complex regex](https://gist.github.com/dkandalov/a2aed17cfdeb65243022) to validate full cron syntax.
* Polish error message: include `cron` syntax and a link to doc.
Run test.
> AWS: Validate rate/cron syntax before Deploy

- lib/plugins/aws/invokeLocal/fixture/handlerWithInitializationError.js
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
I addressed regression introduced with #4912 as since then due to following line:
https://github.com/serverless/serverless/blob/011a6510491f94c4d766d1aa50a9fa8e3dd958d9/lib/plugins/aws/invokeLocal/index.js#L271
errors are logged as `{}` (errors do not have JSON representation), example of log I received:
Proposed patch ensures that errors are logged properly (with stack trace and all it's properties) and in red (as proposed with #4912)
/cc @lewisf
I used Node.js native `util.inspect`
> Fix error log output

- lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json
Closes #5502 
Changed the plugins/create/templates/aws-nodejs-typescript/tsconfig.json to contain es2017 for lib and target
Run _serverless create --template aws-nodejs-typescript_ which should now target es2017 instead of es6
- [n/a] Write tests
- [n/a] Fix linting errors
- [n/a] Make sure code coverage hasn't dropped
- [n/a] Provide verification config / commands / resources
> Issue #5502 Support for native async/await in AWS Lambda for aws-nodejs-typescript template 

- lib/plugins/create/templates/aws-csharp/build.cmd
- lib/plugins/create/templates/aws-csharp/build.sh
- lib/plugins/create/templates/aws-csharp/serverless.yml
**The problem:**
* The template for aws-csharp creates an artifact (using `build.sh`) called `deploy-package.zip`.
* Serverless uploads all artifacts to the same prefix in the S3 bucket.
* To create a second artifact for a second function the basename of the artifact needs to be changed to something else.
* If you use the same basename (in another directory), you get an unexplained error during the deployment:
```
An error occurred: HelloLambdaVersionGtHPSWSbQu5erGQ1qsmWTuL5axFax9OvH53cRMS4yHA - CodeSHA256 (buSKlTnYj3iptkvZOp+HzA1my2aAHCfzE9YYl0jQrqE=) is different from current CodeSHA256 in $LATEST (+5nQZZsPn2CzTTHHeZPKO6Kqt6XJJxVOboMVKg6pSHg=). Please try again with the CodeSHA256 in $LATEST. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: …
```
> aws-csharp create template uses handler-specific artifact

- lib/plugins/aws/deploy/lib/createStack.js
- lib/plugins/aws/lib/monitorStack.js
Closes #5630
Change stack creation failed behaviour to `DELETE`.
Deploy a failing stack to confirm. e.g trigger a lambda with a nonexistent sns resource.
> change behaviour on initial stack create failed

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes #4737
Add hyphen validation to `AwsProvider` constructor, so users can get informed about what is invalid stage name before deploy which is time-consuming.
* Hyphen in stage name will be an error only if `http` events are present, since API Gateway does not support hyphen in stage name.
* Why validation in constructor?  Because I think it can raise error in both createStack and updateStack time.
Underscore is already implemented in
https://github.com/serverless/serverless/blob/3c1b4393af2416eff5ce269fd187363512ede/lib/plugins/aws/deploy/lib/createStack.js#L50-L57 so this PR does not touch underscore.
Run test.
> Add stage name validation to AWS provider.

- docs/providers/cloudflare/guide/functions.md
- docs/providers/cloudflare/guide/services.md
As detailed in cloudflare/serverless-cloudflare-workers#1 the provider specific configuration is usually set under the `provider` property. cloudflare/serverless-cloudflare-workers#2 made the change.
Documentation change to stay consistent with [template](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/cloudflare-workers/serverless.yml#L6-L8).
Compare documentation change to [template](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/cloudflare-workers/serverless.yml#L6-L8).
> Cloudflare config should be under provider property

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes #5606 
`${cf.REGION}` syntax changes `region` field of the credentials object returnd by `awsProvider.getCredentials()`, to get stack info in different region.
However, `getCredentias()` returns a reference to mutable credentials.
So the modified region are accidentally used for later AWS request, then a stack is deployed to wrong region which is specified by `${cf.REGION}` syntax.
This PR fixes the issue by add deep-cloning the credentials before changing region.
1. Install custom build of serverless from this PR
`npm i -g exoego/serverless#fix-cf-region-syntax`
2. Create a service to be referenced: `sls create -t aws-nodejs --path my-service`
3. Update serverless.yml of `my-service`
``` yaml
service: my-service
provider:
name: aws
region: ap-northeast-1 …
```
> AWS: Fix ${cf.REGION} syntax causes deployment in wrong region

- lib/plugins/aws/invokeLocal/java/pom.xml
- lib/plugins/create/templates/aws-java-maven/pom.xml
- lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml
Closes Security alerts by updating `jackson-databind`
updated to 2.8.11.3 per gh security alert recomendation
> update jackson-databind to secure version

- docs/providers/aws/guide/variables.md
- lib/classes/Service.js
- lib/classes/Service.test.js
- lib/classes/Utils.js
- lib/classes/Variables.js
- lib/classes/Variables.test.js
- lib/plugins/print/print.js
- lib/plugins/print/print.test.js
Closes #4494 by extending the changes in https://github.com/serverless/serverless/pull/4528.
Changed the file name/path matching regex to a blacklist.
It now allows any valid characters but the excluded ones and should also work with Windows path separators if needed.
Additionally absolute paths are now allowed.
Added `@` to the allowed variable syntax so file paths with `@` are resolved.
I added a unit test to verify this case, which uses both changes, I can't see any related integration tests testing any variable resolution so have not added any.
Use any filename with `${file(./@scope/file)}`.
_**Is this ready for review?**_: YES
_**Is it a breaking change?**_: NO
> Handle scoped npm packages in ${file()} variables

- docs/providers/aws/events/cloudwatch-log.md
- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Closes #3447
As per CloudFormation nature, it won't delete a resource before trying to create a new one firstly, and the problem come up once it tries to create a new subscription filter, as it will hit CloudWatch's hard limit of 1 subscription filter per log group (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html). The unique option to make it work is to manually delete the resource and then run the CF update again -- since the resource is gone CF is going to be able to create the new one, and also delete the old as its definition is not on template anymore. The idea is to delete the subscription filter whenever the destination function ARN is different from the one that was just configured at `serverless.yml`.
I haven't added UT at all because I'd like …
> Fix ResourceLimitExceeded for cloudwatchLog event

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes #5685
Now AWS Provider's request cache consider `region` as a part of cache key.
So `${cf.REGION:stackA.key1}` and `${cf.ANOTHER-REGION:stackA.key1}` can request separately and does not affect each cache.
1. `npm install -g exoego/serverless#cross-region-same-stack-name`
2. Run `sls deploy` against below: `dev-foo` to `eu-central-1`
```yml
service: foo
provider:
name: aws
region: eu-central-1
stage: dev
functions:
hello:
resources:
Outputs:
foo:
Value: 123
Export:
Name: foo
```
2. Run `sls deploy` against below:  `dev-foo` to `us-east-1` (same stack name but different region)
```yml
service: foo
provider:
name: aws
stage: dev
functions:
hello:
resources:
Outputs:
foo:
Value: 456 …
```
> AWS: Request cache should add region as key to prevent cross-region cache collision

- docs/providers/aws/cli-reference/slstats.md
Fixes a wrong link in the documentation.
Click on the link .
> Fixed a link

- docs/providers/google/events/http.md
This adds a few notes to better explain what you can and cannot do within `serverless.yml` when using GCF. I hope this will address a few common questions for newcomers around HTTP verbs and path configuration in the place they are most likely to find them.
Revisions to this are more than welcome - explaining the URL configuration clearly and concisely was a challenge.
> Clarify docs for the http key for GCF

- docs/providers/kubeless/guide/functions.md
Added documentation for Kubeless secrets
> docs: Kubeless secrets

- docs/providers/aws/events/streams.md
Fix array notation in stream ARN
Just a doc change to actually show people what works for referencing an ARN from a newly created DynamoDB stream
Closes https://github.com/serverless/serverless/issues/5671
I just changed the docs.
> Fix array notation in stream ARN

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #4953 
Closes #5353
Closes #5717 
`Variable#warnIfNotFound(variableString, valueToPopulate)` outputs a confuging warning `A valid undefined ...` when `variableString` does not match any of variable syntaxes.
Such situation can happen when deep variable resolution fails.
This PR suppress warnings when `variableString` does not match any of variable syntaxes, since a root cause of deep variable resolution failure is warned in other call of `#warnIfNotFound`.
1. `npm i -g exoego/serverless#valid-undefined`
2. `sls print` over the below severless.yml
```
provider:
name: aws
stage: ${env:NODE_ENV}
vpc:
securityGroupIds: ${self:custom.config.stage.vpc.securityGroupIds}
custom:
config:
stage: ${file(config/${self:provider.stage}.yml)}
```
3.  Warnings
* should contains `A valid file to …
> Suppress confusing warning "A valid undefined..." 

- docker-compose.yml
- docs/providers/google/cli-reference/create.md
- lib/plugins/create/create.js
- lib/plugins/create/create.test.js
- lib/plugins/create/templates/google-go/.gitignore
- lib/plugins/create/templates/google-go/Makefile
- lib/plugins/create/templates/google-go/fn.go
- lib/plugins/create/templates/google-go/fn_test.go
- lib/plugins/create/templates/google-go/serverless.yml
- lib/plugins/create/templates/google-nodejs/serverless.yml
- tests/templates/test_all_templates
close #5724
Cloud Functions Go runtime has bees released! 🎉 So I wrote a template for it.
I added template, list of template and tests.
```
$ cd $GOPATH/src/github.com/[your repo]
$ serverless create -t google-go -p sample-app
$ cd sample-app
$ make gomodgen
```
> Add google go template

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes #5661
Exactly like the AWS_REGION environment code.
Create two profiles in .aws/config, make profile1 default
Set provider.profile to profile2
Run `invoke` - see that it runs as profile2
Run `invoke local` - see that it runs as profile1
> Provide AWS_PROFILE from configuration for invoke local

- lib/utils/downloadTemplateFromRepo.js
Closes #4566
* When doing a `serverless create`, we can specify a `template-url` to fetch the template from a private github git repo HTTPS url using a personal access token. For instance:
```
mkdir mine
cd mine
npm init -f
npm install serverless --save-dev
SLS_DEBUG="*" npx serverless create --template-url https://x-access-token:${GITHUB_AUTH_TOKEN}@github.com/${PRIVATEFORKOWNER}/serverless/tree/master/lib/plugins/create/templates/aws-nodejs --name 'mine' --path mine
```
When `URL.parse(inputUrl.replace(/\/$/, ''))` is [invoked](https://github.com/serverless/serverless/blob/master/lib/utils/downloadTemplateFromRepo.js#L148), it saves the auth portion of the url object if found, but this [is discarded](https://github.com/serverless/serverless/blob/master/lib/utils/downloadTemplateFromRepo. …
> Enable download template from a private github repo using personal access token

- lib/plugins/plugin/install/install.js
- lib/plugins/plugin/install/install.test.js
Allow `sls plugin install -n @serverless/enterprise-plugin` for example
if the plugin name starts with an `@` follow different logic for splitting on `@` to get the version.
install this branch of sls, then run `sls plugin install -n @serverless/enterprise-plugin`
- [n/a] ~~Write documentation~~
> Fix sls plugin install -n @scoped/package

- CHANGELOG.md
- package-lock.json
- package.json
- [AWS: Consolidates Lambda::Permission objects for cloudwatchLog events](https://github.com/serverless/serverless/pull/5531)
- [Suppress confusing warning "A valid undefined..." ](https://github.com/serverless/serverless/pull/5723)
- [Add google go template](https://github.com/serverless/serverless/pull/5726)
- [Provide AWS_PROFILE from configuration for invoke local](https://github.com/serverless/serverless/pull/5662)
- [Test that CLI does not convert numeric option to number](https://github.com/serverless/serverless/pull/5727)
- [Remove duplicate-handler warnings based on community feedback.](https://github.com/serverless/serverless/pull/5733)
- [Enable download template from a private github repo using personal access token](https://github.com/serverless/serverless/pull/5715)
- [Fix …
> Version bump for 1.36.3 release

- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Closes #5698 
Converting reservedConcurrency variable to integer
Store serverless.yaml
```
service: env-test
provider:
name: aws
functions:
cronFunc:
handler: handler.cronFunc
reservedConcurrency: '${env:CONCURRENCY}'
```
then compile
```env CONCURRENCY=10 serverless package```
see 
```"ReservedConcurrentExecutions": 10```
for example using
```cat .serverless/serverless-state.json```
> Convert reservedConcurrency to integer to allow use env var

- docs/providers/azure/examples/hello-world/node/README.md
The Azure Hello World example has several errors, including incorrect Provider Plugin name and incorrect invocation command.
1. Change plugin name in example documentation from 'serverless-azure' to the correct 'serverless-azure-functions' name. The 'serverless-azure' listed currently is the incorrect name of the package and does not exist.
2. Changed the invocation command to a working command based on the [Azure/boilerplate-azurefunctions](https://github.com/Azure/boilerplate-azurefunctions) parent project. 
3. Changed the expected test invocation output to match the sample event provided.
1. Changed package name in document.
2. Changed the invocation command in document.
3. Changed example output in document.
4. Ran all commands and verified successful example.
1. Try the current …
> Fix broken Azure Hello World Example documentation

- lib/plugins/aws/package/compile/layers/index.js
- lib/plugins/aws/package/compile/layers/index.test.js
Cast account to string if passed as a number (according to docs, you are able to do it)
https://serverless.com/framework/docs/providers/aws/guide/layers/
Change is self-explainatory really, I just make sure that account is a number, if it is - switch it to string
Provide layers config with account as a number
```
layers:
test:
path: testPath
allowedAccounts:
- 11111111
```
After triggering there is going to be an error as integer doesn't have replace method:
```
account.replace is not a function
at Object.getLambdaLayerPermissionLogicalId ({...}/node_modules/serverless/lib/plugins/aws/lib/naming.js:148:15)
```
With this fix, generation is going to pass
> Lambda Layers - cast account id to string if number provided

- docs/providers/aws/cli-reference/create.md
- docs/providers/aws/guide/services.md
- lib/plugins/create/create.js
- lib/plugins/create/create.test.js
- lib/plugins/create/templates/aws-provided/bootstrap
- lib/plugins/create/templates/aws-provided/gitignore
- lib/plugins/create/templates/aws-provided/handler.sh
- lib/plugins/create/templates/aws-provided/serverless.yml
- tests/templates/test_all_templates
Added an `aws-provided` template including AWS's bash example of using the Runtime API
* added template to create plugin 
* added to list of templates(todo)
```
npm i -g serverless/serverless#provided-template
sls create -t aws-provided
sls deploy
sls invoke -f hello
```
> Add template for provided runtime with the bash sample from AWS

- docs/providers/aws/examples/hello-world/ruby/README.md
Added hello world example document for  Ruby.
Closes #XXXXX
Based on python document.
ref: https://github.com/serverless/serverless/blob/master/docs/providers/aws/examples/hello-world/python/README.md
Please confirm the document.
> Add Hello World Ruby Example

- lib/Serverless.js
- lib/classes/CLI.js
- lib/classes/CLI.test.js
Closes #5676
If `print` command is used, `CLI#log` become no-op.
Therefore logs are suppressed, except printing service definition.
Though duplicate-warnings are getting removed in #5733, 
I think this change is worth to prevent similar "unexpected log while print" issues in future.
1. `npm install -g exoego/serverless#print-no-log`
2. Prepare the below yml.
```yml
service: 
name: myservice
provider:
name: aws
functions:
function1:
handler: lib/proxy.handler
function2:
handler: lib/proxy.handler
```
3. `sls print`, it should only give yml, no warnings.
> Do not print logs if print command is used.

- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Closes #5699
Translate the "The specified bucket does not exist" error into more detailed error containing below:
* Bucket name
* stack name
* Possible recovery operation.
1. `npm i -g exoego/serverless#fix-5699;`
1. `sls deploy` anything
1. Delete the deployment bucket manually.
1. `sls deploy`
1. Verify that new error message is shown.
> AWS: Tell S3 bucket name and how to recover if deployment bucket does not exist

- lib/plugins/aws/rollback/index.js
- lib/plugins/aws/rollback/index.test.js
When running sls rollback -t 1546961025152 the timestamp was being parsed as a string inside a Date Object.
This would return an Invalid Date, therefore, failing to convert the timestamp into a valid date.
In here we are checking to see if the date is already a valid one, otherwise convert the timestamp to a number and try again.
We are checking first because most cases we don't want to convert to numbers.
Fix #5664
Ps: We could add another check, if the date is still invalid, throw an Error, but that's not the scope of the issue.
Closes #5664 
When running `sls rollback -t 1546961025152` the timestamp was being parsed as a string inside a Date Object.
This would return an Invalid Date, therefore, failing to convert the timestamp into a valid date.
In here we are checking to see if the …
> Fix #5664 - Rollback fails due to a timestamp parsing error

- docs/providers/aws/guide/functions.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Arn references for SQS queues are now available using:
```
Fn::GetAtt:
- Queue
- Arn
```
According to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-properties-sqs-queues-ref an SQS reference returns its URL which is not sufficient for Lambda DLQ config which requires an ARN.
`isArnRefOrImportValue` is renamed to `isArnRefGetAttOrImportValue` and extended to also look for `Fn::GetAtt`.
Write a minimal Serverless setup that mimics that of the new test: `'should create necessary resources if a Fn::GetAtt is provided'`. 
> Allows Fn::GetAtt with Lambda DLQ-onError

- lib/classes/Variables.js
- lib/classes/Variables.test.js
- lib/plugins/aws/provider/awsProvider.js
closes #4311
closes #4725
* added profile to list of variables that must resolve to a constant before SSM (and cfn & s3) variables are attempted to be resolved.
* updated `AwsProvider` to check the `aws-profile` option instead of `profile` since that's what's actually implemented(afaik).
* updated `getProfileSourceValue` return value to be more like that of the `getStageSourceValue` and `getRegionSourceValue`
set `profile` to a variable and try to `sls print` with stable install and then again with this branch
> Resolve profile before performing aws-sdk dependent actions

- lib/plugins/aws/invokeLocal/invoke.py
In #5354/#5355 a call to `tty` was called to ensure it was available to prevent issues in CI systems. However, when I merged it, I didn't have a mac and saw no issue with this. When I joined the team at serverless, I got a mac so I could better test the UX that our many mac users experience. I've found that this tty call doesn't work on macs, so I'm disabling this check on macOs since there shouldn't be odd environments like CI to consider on a mac;
skip call to `tty` when `sys.platform == 'darwin'`
On a mac (no changes on other OSes)
```
sls create -t aws-python3
echo -e 'def hello(event, context):\n    import pdb;pdb.set_trace()' > handler.py
--Return--
> /Users/dschep/code/tmp/handler.py(2)hello()->None
-> import pdb;pdb.set_trace()
(Pdb)
```
on master it …
> don't check call tty on macs

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
- lib/plugins/package/lib/zipService.js
handle layers paths with trailing slash
closes #5646
use `path.resolve` on the layer path before using it as a prefix
create a service with a layer with a path ending in `/`
> handle layers paths with trailing slash and leading ./ or just .

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Require provider.credentials vars to be resolved before s3/ssm/cf vars, similar to long standing region/stage and new profile preresolve.
test uses the service definition instead of `getCredentials` because
`getCredentials` is much more complex than `getStage`/`getProfile`/`getRegion`
and we only need to test that the config is updated, not all the
credential setting logic
added `credentials` in the prepopulate step of variable system
Create an SSM var called `sls-5763` containing the value `sls-5763`
Create a service with the following config, replacing the key id & secret key of course:
```yaml
service: sls-5763
custom:
creds:
sls-5763:
accessKeyId: YOURACCESSKEYID
secretAccessKey: YOURSECRETACCESSKEY
provider:
credentials: ${self:custom.creds.${ssm:sls-5763}}
name: aws
runtime: …
```
> Require provider.credentials vars to be resolved before s3/ssm/cf vars

- lib/Serverless.js
- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
This is a revisit of a previous developer experience bug where executing a serverless command in a path with no `serverless.yml` would fail silently. I noticed that this issue has returned in the latest release.
The tests appeared to be passing because the method to validate a plugins config dependency was working, but the rejection was not being caught during execution, possible because of the asynchronous nature of loading the config file in `getServerlessConfigFile`
`getServerlessConfigFile` was being called twice within the pluginManager, so serverless will now ask the PluginManager to load the config file earlier and then store it to lookup during plugin execution, rather than try to load in it's methods as it was previously.
Currently, running `sls info` provides no feedback when …
> Throw an error if plugin is executed outside of a serverless directory

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #5398 
In #5594, `cleanVariable` does not clean whitespaces if variable is double-quote string literal.
Atter this PR, it also does not clean whitespace if variable is single-quote string literal.
1. `npm install -g exoego/serverless#single-quote-fallback`
2. `sls deploy` below and confirm it completes successfully.
```
service: aws-nodejs
provider:
name: aws
functions:
hello:
events:
- schedule: ${env:SCHEDULE, 'rate(2 hours)'}
- schedule: ${env:SCHEDULE, "rate(3 hours)"}
```
> Preserve whitespaces in single-quote literal fallback

- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Closes #5779
Closes #5780
* Now checking if `origins` is empty to ensure `origin` is only set where appropriate.
* `validate.js` now copies `cacheControl` into `corsPreflight` so the configured value is available in `compileCors()`.
See above.
Modified existing unit tests to cover these scenarios and tested with my own stack.  The linked issues describe how to recreate.
***Is this ready for review?: YES
***Is it a breaking change?: NO
> Fixes for AWS cors config issues

- docs/providers/aws/guide/variables.md
closes #5024 
Thanks to @alexdebrie for pointing me to the AWS docs on how to use Secrets Manager via SSM: https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html
Added documentation on how to use Secrets Manager via SSM
Create a secret and try to use it via an `${ssm:/aws/reference/secretsmanager/secret_ID_in_Secrets_Manager~true}`:
- n/a ~~Fix linting errors~~
- n/a ~~Make sure code coverage hasn't dropped~~
> Document how to use Secrets Manager

- lib/Serverless.js
- lib/classes/PluginManager.js
This PR fixes a race condition issue caused by #5636, in which the loading of the config file is not awaited and as a result could sometime cause the "must be in a service directory" error even when you are running inside a service.
> Fix race condition when loading config file

- lib/plugins/aws/invokeLocal/index.js
closes #5792
set the same default context as the java invoke local implementation
run @mnylen's example repo in #5792 
> Set timout & others on context in python invoke local

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Respect custom variable syntaxes when appending to deep variables.
Closes #5769 
See new unit test.  For manual confirmation, run `sls print` against the following assets from #5769:
```
description: this is dummy
```
```service: template
provider:
name: aws
variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"
custom:
settings: ${{file(./env.yml)}}
functions:
hello:
description: ${{self:custom.settings.description}}
```
> Append in Custom Syntax

- lib/plugins/config/config.js
- package-lock.json
Change the config command to not require loading of the `serverless.*` configuration file.
> Don't load config for `config`

- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Closes: N/A
This PR implements a TODO that was left in `checkForChanges.js` > `checkIfDeploymentIsNecessary` which makes reading the zipFiles asynchronously, therefore should make checkForChanges run a bit faster, specially considering there is already a costly blocking operation after the read to compute the checksum per zipFile.
Simply replaced blocking `fs.readFileSync` with non blocking `fs.readFile`. 
N/A
> Replace blocking fs.readFileSync with non blocking fs.readFile in checkForChanges.js

- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/deployFunction/index.test.js
Closes #5786
Added the processing code for layer option, and the corresponding test and validations
I've verified myself that this layer update config works fine.
> Added layer option for deploy function update-config

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #5807 
https://github.com/serverless/serverless/commit/5ed78b8024eead58452012b9e74f0dfdc20ec3a7 added preservation of white space in a single-quote literal. This caused `makeDeepVariable` to not replace the `variableString` properly with the `deep:0` syntax because white space was only being removed from the variableContainer. 
To fix I just added the removal of white space from `variableString` as well. 
I added a new test for the case for it. The sample in #5807 works as well now. 
> fix makeDeepVariable replacement

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/invoke.rb
Make local ruby debugging work
This follows a similar change for local python invocation at https://github.com/serverless/serverless/blob/ad5decb080a7aa92cac1bc0f8632e3e57b99fe46/lib/plugins/aws/invokeLocal/invoke.py#L76-L82
A handler such as the following will now pause at the breakpoint:
```ruby
require 'json'
require 'pry'
def hello(event:, context:)
binding.pry # breakpoint
{ statusCode: 200, body: JSON.generate('Go Serverless v1.0! Your function executed successfully!') }
end
```
FWIW: I put this PR up for feedback rather than to expecting to get it merged, especially w.r.t. e30e24222bd9cd584e
> Make local ruby pry work

- lib/plugins/package/lib/packageService.js
fixes #5745 because nanomatch only supports / as a path separator
replace `\` with `/` on windows before passing patterns into nanomatch
on windows:
```
npm i -g serverless/serverless#sls-5745
sls plugin install -n serverless-offline
sls package
```
then if you check `.serverless/aws-nodejs.zip`, it should not contain the dev dependencies
> Replace \ with / in paths on windows before passing to nanomatch

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
I failed to properly test it after a slight refactor befor emerge
> Fix windows go rework

- docs/providers/aws/events/sns.md
Uses join operator first argument so lines containing only ":" can be removed.
I've tested it on a real sls file and it works.
> Make use of join operator first argument in sns docs

- lib/classes/CLI.js
- lib/classes/CLI.test.js
- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
Closes: #5806
- Added a new command type "container", which can be used when you want nested commands but the top level command on its own doesn't do anything. 
- Note this is different from the `entrypoint` command type which hides its children commands.
- "container" commands cannot be invoked, only its children. 
- "container" commands will not be displayed on the CLI, only its children. 
**ServerlessCustomPlugin.js**
```
class ServerlessCustomPlugin {
constructor(serverless, options) {
this.serverless = serverless;
this.options = options;
this.commands = {
mycommand: {
type: 'container',
commands: {
foo: {
usage: 'Child foo command',
lifecycleEvents: ['foo1']
},
bar: {
usage: 'Child bar command',
lifecycleEvents: ['bar1']
}
}
}
};
this.hooks = {
'mycommand:foo:foo1': …
```
> add support for command type='container'

- docs/providers/aws/guide/deploying.md
- lib/plugins/aws/package/lib/core-cloudformation-template.json
- lib/plugins/aws/package/lib/generateCoreTemplate.js
- lib/plugins/aws/package/lib/generateCoreTemplate.test.js
- lib/plugins/aws/package/lib/mergeCustomProviderResources.test.js
Closes https://github.com/serverless/serverless/issues/5797
Trivial change to the default bucket policy.
Trivial change. Creating a simple Hello World function, and checking that the deployment bucket creating has default server-side encryption and versioning enabled via the AWS console would do it.
> Update bucket conf to default AES256 encryption.

- lib/plugins/package/lib/packageService.js
Ability to override [wildcard glob pattern](https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/packageService.js#L210)  by a negative `params.include` to avoid unnecessary traversal and get much faster glob matching during packaging in some cases.
When `globby` is provided with an array of patterns, it adds all _subsequent_ negative patterns as `ignore` option of a particular task ([source code here](https://github.com/sindresorhus/globby/blob/master/index.js#L34-L41)). However, that is not useful when the wildcard comes the last (as it is now) - `ignore` for the relevant matching task is always empty.
Putting the least specific pattern first makes it possible to override it with a subsequent negative one and avoid unnecessary traversal in e.g. `node_modules`, …
> Fix: override wildcard glob pattern (**) in resolveFilePathsFromPatterns

- lib/plugins/create/templates/aws-nodejs-typescript/handler.ts
Closes #5773.
I added a underscore to the `context` variable in `handler.ts` in the `aws-nodejs-typescript` template to indicate that it is unused as per Microsoft/TypeScript#9464.
The following sequence of commands should not emit errors and the deploy should be successful:
```
serverless create --template aws-nodejs-typescript
npm install
```
> Indicate unused context in aws-nodejs-typescipt

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Closes #5834.
I added `err.stack` to the error result that `aws/invokeLocal/index.js#handleError` returns to include a stack trace in the error message. 
1. `serverless create --template aws-nodejs`
2. Add the following handler:
```js
module.exports.testError = async function(data, context) {
throw new Error('testError');
return 'unreachable';
};
```
3. `serverless invoke local -s aws-nodejs -l --function testError` should error with a stack trace:
```json
{
"errorMessage": "testError",
"errorType": "Error",
"stackTrace": [
"Error: testError",
"    at module.exports.testError (C:\\Users\\user\\Desktop\\test_serverless\\handler.js:17:11)",
"    at Promise (C:\\Users\\user\\Documents\\GitHub\\externalProjects\\serverless\\lib\\plugins\\aws\\invokeLocal\\index.js:409:30)",
"    at new …
```
> Add stack trace to aws/invokeLocal errors

- docs/providers/openwhisk/events/messagehub.md
Looking at the remainder of the documentation it seems that the Message Hub event key should be `message_hub` and not `messagehub`.
> Missing underscore

- docs/providers/aws/guide/services.md
The documentation page was describing that there was a list of runtimes, when in fact its a list of templates
Replaced:
Here are the available runtimes for AWS Lambda:
with
Here are the available templates for AWS Lambda:
Because these are in fact templates and not actual runtimes in AWS Lambda
> [Docs] Replacing "runtimes" with "templates"

- docs/providers/aws/guide/variables.md
- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #5838
After this PR, `${ssm}` resolves variable as JSON only if referencing to a secret stored in AWS Secrets Manager and returned value is valid JSON.
Otherwise it returns plain text.
It do not throw an error if *invalid* JSON, since AWS Secrets Manager can store any text including invalid JSON. 
1. `npm install -g exoego/serverless#ssm-should-fail`
2. Create a secret `foo` in AWS Secrets Manager.
```json
{
"num": 1,
"str": "secret"
}
```
3. Create a `serverless.yml`
```yml
service: new-service
provider: aws
functions:
hello:
name: hello
custom:
supersecret: ${ssm:/aws/reference/secretsmanager/foo~true}
```
4. Run `sls print` and confirm `supersecret` is like
```
custom:
supersecret: 
num: 1
str: secret
```
***Is it a …
> AWS: ${ssm} resolve vairbale as JSON if it is stored as JSON in Secrets Manager

- lib/plugins/create/create.js
- lib/plugins/create/create.test.js
- lib/plugins/install/install.js
- lib/plugins/install/install.test.js
- lib/utils/downloadTemplateFromRepo.js
- lib/utils/downloadTemplateFromRepo.test.js
Closes #5802.
I had `downloadTemplateFromRepo()` return the service name instead of the final directory name, so that `create.js` and `install.js` can correctly display the service name both when creating / installing a service by default and when a service name is explicitly specified.
`serverless install --url https://github.com/mnylen/serverless-python-fake-context-timeout-issue` should output:
```
Serverless: Downloading and installing "serverless-python-fake-context-timeout-issue"...
Serverless: Successfully installed "serverless-python-fake-context-timeout-issue"
```
`serverless install --url https://github.com/mnylen/serverless-python-fake-context-timeout-issue --name timeout` should output:
```
Serverless: Downloading and installing …
```
> Fix service name in template install message

- docs/providers/aws/events/apigateway.md
Closes #XXXXX
Update shared API instructions 
The [instructions for shared APIs ](https://serverless.com/framework/docs/providers/aws/events/apigateway/#easiest-and-ci-cd-friendly-example-of-using-shared-api-gateway-and-api-resources) (see the 'easiest and ci/cd friendly' section) would always give me errors such as : 
```
The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource ApiGatewayRestApi
```
After much googling I found https://forum.serverless.com/t/micro-services-with-shared-api-gateway/6486/2 and the solution proposed (deploying the API and exports as their own service)  worked for me.
I thought to update the instructions so more people don't waste hours. Alternatively, if there's a way of making it work the way mentioned, …
> Update shared API instructions

- docs/providers/aws/guide/packaging.md
- lib/classes/PluginManager.js
- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
- lib/utils/getServerlessConfigFile.js
- lib/utils/getServerlessConfigFile.test.js
Closes #5772
I've made `packageService.getExcludes` async, so we can check what the serverless config file being used is. Therefore we don't need anymore in the default excludes any of the serverless.yml | yaml | js | json values. 
`serverless.yml` which includes a function pointing to a file serverless.js (as noted in the open issue)
After running `sls package`, the serverless.js file is included in the zip:
> Packaging exclude only config file being used

- lib/plugins/create/templates/aws-nodejs/handler.js
AWS no longer adds the 'context' parameter by default to Node 8 functions created through AWS's console. 
In order to keep **_Serverless_** consistent with AWS, I think it's worth removing the 'context' parameter from the aws-nodejs template as well. 
If this PR is accepted, I can go ahead and modify the other Node templates by removing the mentioned parameter from them.
The tests have passed so I assume nobody ever used this parameter anyways.
EDIT: The parameter is still passed to the function, it's just that most developers never use it. If one wants to use it, then the the argument should be added back manually. My point here is just to have the templates create the same code that AWS's console would.
Thanks!
> Removing the context parameter from aws-nodejs template

- docs/providers/aws/events/sns.md
- lib/plugins/aws/package/compile/events/sns/index.js
- lib/plugins/aws/package/compile/events/sns/index.test.js
- tests/integration/aws/sns/existing-topic/service/serverless.yml
- tests/integration/aws/sns/existing-topic/tests.js
Closes #3824 
An improper string check is failing when the `arn` property has an object value and `topicName` is not a string, so the logic was modified to more accurately tell the user where the issue is. Additionally, a check to make sure usages of `Fn::ImportValue` do not include `Fn::GetAtt` or `Ref` was added.
As cleanup, I also consolidated some of the error messages, as there were some subtle differences between them trying to convey the same information.
serverless:
```
service: aws-nodejs
provider:
name: aws
functions:
hello:
events:
- sns:
arn:
Fn::Join:
- ':'
-
- 'arn:aws:sns'
- 'us-east-1'
- '1234567890'
- 'MyTopic'
topicName: 'MyTopic'
```
Relevant Cloudformation:
```
"HelloSnsSubscriptionMyTopic": {
"Type": "AWS::SNS::Subscription", …
```
> Improves usage and documentation of SNS event sources.

- docs/providers/aws/events/apigateway.md
It's a organizational change. Reviewer can verify accessing the Github Markdown Viewer of [apigateway.md](docs/providers/aws/events/apigateway.md) and on [API Gateway Events page](https://serverless.com/framework/docs/providers/aws/events/apigateway/)
> Put `Custom Response Headers` into `[Responses]`

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
Closes #5858
Replace special characters with alphanumeric ones, as we've done with other logical IDs
```yml
functions:
hello:
events:
- websocket: 'echo'
- websocket: 'echo/echo'
- websocket: 'echo-echo'
- websocket: 'echo_echo'
- websocket: 'echo.echo'
```
> Websockets: Support more route characters

- docs/providers/aws/events/websocket.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/websockets/index.js
- lib/plugins/aws/package/compile/events/websockets/index.test.js
- lib/plugins/aws/package/compile/events/websockets/lib/authorizers.js
- lib/plugins/aws/package/compile/events/websockets/lib/authorizers.test.js
- lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
- lib/plugins/aws/package/compile/events/websockets/lib/permissions.test.js
- lib/plugins/aws/package/compile/events/websockets/lib/routes.js
- lib/plugins/aws/package/compile/events/websockets/lib/routes.test.js
- lib/plugins/aws/package/compile/events/websockets/lib/validate.js
- lib/plugins/aws/package/compile/events/websockets/lib/validate.test.js
Closes #5857
Closes #5874 
Using the Authorizer CF template, and mapping it to the Route template, and setting the required permissions.
Using the following service:
```yml
service: websocket-authorizers
provider:
name: aws
stage: dev
functions:
connect:
handler: handler.connect
events:
- websocket:
route: $connect
authorizer:
name: auth
identitySource:
- 'route.request.header.Auth'
- 'route.request.querystring.Auth'
default:
handler: handler.default
events:
- websocket:
route: $default
auth:
handler: handler.auth
```
```js
// handler.js
'use strict';
const AWS = require('aws-sdk')
// the following section injects the new ApiGatewayManagementApi service
// into the Lambda AWS SDK, otherwise you'll have to deploy the entire new version of the SDK
/* START …
```
> Added websockets authorizer support

- lib/plugins/aws/info/getStackInfo.js
- lib/plugins/aws/info/getStackInfo.test.js
Correct function names in `sls info` & `sls deploy` output when customized
used `getFunction(funcId).name` in gather info instead of generating the name again.
Create a service with a function that specifies `name: customized` and on deploy you should see that name instead of `SERVICENAME-STAGENAME-FUNCTIONNAME`
> Print customized function names correctly in sls info output

- docs/getting-started.md
Made two changes:
1. Improves link hitboxes by having the `a` tag wrap the whole `docsSection` instead of just the image and title. Currently hovering over the `docsSection` makes it change colour, but not actually become clickable which I thought was weird behavior.
2. Orders `menuItem`s in same order as main page content.
Closes #5893
Wrap whole `docsSection` in `a` tag.
Try rending the markdown to HTML, and try clicking various parts.
> Update getting started page

- lib/plugins/aws/package/compile/events/websockets/lib/api.js
- lib/plugins/aws/package/compile/events/websockets/lib/api.test.js
Closes #5868 
Skip the logic that adds websocket policies to the default role when using custom roles.
```yml
functions:
myWebSocket:
handler: myWebsocket.handler
role: { "Fn::GetAtt": [ "MyWebSocketLambdaFunctionRole", "Arn" ] }
events:
- websocket:
route: $connect
- websocket:
route: $disconnect
- websocket:
route: $default
resources:
Resources:
MyWebSocketLambdaFunctionRole: 
Type: "AWS::IAM::Role,
Properties:
#custom role policies
```
> Fix bug when using websocket events with functions with custom roles

- lib/plugins/aws/lib/normalizeFiles.js
- lib/plugins/aws/lib/normalizeFiles.test.js
Closes #5873 
normalizeCloudFormationTemplate() now removes timestamp suffix from ApiGatewayDeployment resource name. 
> Fix CloudFormation template normalization

- docs/providers/aws/guide/functions.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
This PR implements AWS x-ray support for Lambda. It's a refactored and updated version of https://github.com/serverless/serverless/pull/3742, so shout-outs to @e-r-w whi implemented the first pass in #3742.
**Aside:** We'll tackle AWS x-ray support for API Gateway separately (as per #5564)
Closes #3495
Added the CloudFormation config to the function and Lambda IAM role level.
```yml
service:
name: test
provider:
name: aws
stage: dev
tracing:
lambda: true # this will result in `Active`, you can change it to true, `Active` or `PassThrough`
functions:
hello:
world:
handler: handler.world
tracing: PassThrough
```
> Add AWS x-ray support for Lambda

- docs/providers/aws/events/sqs.md
- lib/plugins/aws/package/compile/events/sqs/index.js
- lib/plugins/aws/package/compile/events/sqs/index.test.js
Closes #5345 
Allowed `Fn::Join` to be used in the dynamic ARN builder for SQS events.
Install this branch:
```
npm install git://github.com/serverless/serverless.git#SQSFnJoin
```
Try to deploy an SQS trigger that uses `Fn::Join`:
```yml
service: myservice
custom:
region: eu-central-1
mySQSQueue:
Fn::Join:
- ":"
- - arn
- aws
- sqs
- Ref: AWS::Region
- Ref: AWS::AccountId
- ${env:MY_SQS_QUEUE}
provider:
name: aws
region: ${self:custom.region}
functions:
fun:
handler: handler.myhandler
events:
- sqs:
arn: ${self:custom.mySQSQueue}
batchSize: 10
```
Make sure it works.
@AndreaAdvanon Can you try this branch and confirm it solves your problem? Also make sure it doesn't cause any issues with CloudFormation.
***Is it a breaking …
> Allow Fn::Join in SQS arn builder

- docs/providers/aws/guide/resources.md
I think it would be a good idea to have a link to the core concepts when mentioning them.
When I was reading I start to think "what these things mean in this context".
> Add links to the respective core concepts

- docs/providers/aws/guide/serverless.yml.md
Add a small description to docs for providers > aws > guide > serverless.yml
I looked for a while and finally found that the authorizer configuration has a `type` options that defaults to `token` but can be set to `response` to return the entire Api Gateway event to the authorizer, but that is not currently reflected in the serverless.yml documentation, so that's what this attempts to address.
Add a small entry to document that the `type` option exists with `token` and `response` as values, and that it defaults to `token`
This behavior is already documented somewhat in the Api Gateway events documentation here:
[https://serverless.com/framework/docs/providers/aws/events/apigateway/#http-endpoints-with-custom-authorizers](https://serverless.com/framework/docs/providers/aws/events/apigateway …
> Add type configuration to aws serverless.yml guide for authorizer

- docs/providers/aws/events/cloudwatch-event.md
- docs/providers/aws/events/schedule.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js
- lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test.js
- lib/plugins/aws/package/compile/events/schedule/index.js
- lib/plugins/aws/package/compile/events/schedule/index.test.js
Support for specifying the InputTransformer option for cloudwatch events.
The code is pretty self-explanatory, but it simply allows inputTransformer option to be mapped to the [cloudformation InputTransformer spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-inputtransformer.html#cfn-events-rule-inputtransformer-inputpathsmap) in both the schedule and cloudwatchEvent events.
```yaml
service: input-transformer-example
provider:
name: aws
functions:
printEvent:
description: Simply logs the event
handler: printEvent.handler
events:
- schedule:
name: everyMinute
rate: rate(1 minute)
enabled: true
inputTransformer:
inputPathsMap:
eventTime: '$.time'
inputTemplate: '{"time": <eventTime>, "key1": "value1"}'
``` …
> Support for Cloudwatch Event InputTransformer

- docs/providers/aws/cli-reference/invoke-local.md
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/invoke/invoke.js
- package-lock.json
- package.json
This is a work in progress for implementing docker based invoke local support. 
**Feedback greatly appreciated**
Closes #5848 by using docker with the [docker-lambda images from lambci](https://github.com/lambci/docker-lambda).
Closes #3456
The main benefits are:
* More runtimes supported, even `provided`!
* Layers support
* runtime environments more closely resemble real lambda env
* logging environment
* paths (your handler is actually run at `/var/task`)
* linux (as opposed to host OS)
The feature is currently implemented by default for previously unsupported runtimes, and can be enabled for python/javascript/java/ruby with the the `--docker` flag.
* local layers are resolved by traversing the `Ref` and arn based layers are downloaded and extracted into …
> Invoke local docker

- docs/providers/aws/events/websocket.md
The PR template said not to delete it, but I did. Sorry. This is just a 1 character change, a typo in the docs. Surely I don't have to fill all that out? Seems code-PR oriented.
> Fixed typo "disonnect"

- docs/providers/aws/cli-reference/invoke-local.md
> Fixing minor typo

- docs/providers/aws/events/apigateway.md
Documentation tweak to note that shared authorizers of type REQUEST are also fine
Per [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html), which are referenced in the existing docs here:
> The type of authorizer. Valid values include:
> TOKEN: A custom authorizer that uses a Lambda function.
> COGNITO_USER_POOLS: An authorizer that uses Amazon Cognito user pools.
> REQUEST: An authorizer that uses a Lambda function using incoming request parameters.
And per https://github.com/serverless/serverless/issues/4325, it appears that REQUEST type authorizers are supported by serverless generally
> Documentation tweak around shared authorizers

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Closes #4862
```yml
service: env-test
provider:
name: aws
functions:
lambda:
events:
- http:
path: users
method: post
async: true
```
Running `sls package` should generate template that has 
```
"RequestParameters": {
"integration.request.header.X-Amz-Invocation-Type": "'Event'"
}
```
Didn't test with real AWS API GW. Expected beheviour would that it return HTTP 202.
> Support for asynchronous lambda invocation with integration type AWS

- lib/classes/Utils.test.js
Adds test for the `getLocalAccessKey` function in the `Utils` class. This PR is a preparation to merge https://github.com/serverless/serverless/pull/5335
> Add unit tests for getLocalAccessKey function

- docs/providers/aws/guide/services.md
Add `stackName` and `apiName` to `serveless.yml` example in docs. Documents feature added in #4951.
Was attempting to change my CloudFormation stack name the other day and found the PR adding the feature; however, I noticed there were no official docs for the change.
> Document changes from #4951

- docs/providers/aws/guide/resources.md
- docs/providers/aws/guide/variables.md
- lib/Serverless.js
- lib/Serverless.test.js
- lib/classes/Variables.js
- lib/classes/Variables.test.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js
- lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
This PR implements the concept of an `instanceId` which is auto-generated everytime the Serverless CLI is run. The `instanceId` is a random variable which will be used internally by the Framework to generate predictable ResourceLogicalIds where a random part needs to be involved.
The `instanceId` is exposed via the new `${sls:instanceId}` variable extension. All Serverless Core variables which are used internally can and should be exposed via `${sls:}` in the future.
The addition of an `instanceId` concept solves #2233. The initial idea was to introduce an `${apig:}` Serverless Variable with a `deploymentLogicalId`. However this is impractial because the AWS API Gateway Plugin generates the random id and is therefore not accessible in the Variable population step which happens way before …
> Add Serverless instanceId concept

- docs/providers/aws/events/apigateway.md
Experimenting with async invocation I expected to see a 202 status code. Documenting the real status code: 200.
> Doc: Include that APIGateway status code of async events

- lib/plugins/deploy/deploy.js
- lib/plugins/deploy/deploy.test.js
Closes #5876.
I added a check in the `before:deploy:deploy` hook to check if the specified provider in `serverless.yml` exists, and to throw an error if it does not.
1. Specify a non-existent provider in `serverless.yml`:
```yaml
provider:
name: nonExistentProvider
```
2. `serverless deploy` should throw an error:
```
The specified provider "nonExistentProvider" does not exist.
```
> Add error message when provider does not exist

- docs/providers/aws/cli-reference/invoke-local.md
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/invoke/invoke.js
Closes #5993 
Added new option `--docker-arg` to pass additional arguments to docker run command used in `invoke local --docker`
```yml
service: debuggable-lambda
provider:
name: aws
functions:
hello:
```
`handler.js`
```js
'use strict';
require('inspector').open(9229, "0.0.0.0", true);
module.exports.hello = async (event) => {
debugger;
let var_to_debug = "hello"
return var_to_debug;
};
```
`.vscode/launch.json`
```json
{
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "attach",
"name": "Attach",
"port": 9229,
"localRoot": "${workspaceFolder}",
"remoteRoot": "/var/task"
}       
]
}
```
* Run below commands
```sh
cd debuggable-lambda
code .
npm install -g …
```
> #5993: Ability to pass args for docker run command during invoke local docker

- lib/plugins/aws/deploy/lib/createStack.js
- lib/plugins/aws/deploy/lib/createStack.test.js
- lib/plugins/aws/lib/updateStack.js
- lib/plugins/aws/lib/updateStack.test.js
Closes #5995 
When creating or updating a stack, it checks the CloudFormation template to see if a `Transform` directive is found.  If it is, it adds the additional capability CAPABILITY_AUTO_EXPAND, which is required when using a CloudFormation Macro via the `Transform` directive.
This serverless.yml should be successfully deployed:
```
service: transform-test
provider:
name: aws
resources:
Transform: 'AWS::Serverless-2016-10-31'
Resources:
SimpleTable:
Type: AWS::Serverless::SimpleTable
Properties:
PrimaryKey:
Name: id
Type: String
ProvisionedThroughput:
ReadCapacityUnits: 5
WriteCapacityUnits: 5
```
(I'm not sure what documentation would be required for this, but I'm happy to add some if necessary...)
> Add additional Capability when Transform is detected

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Closes #5947
- The invoke local command runs `package` command before invoking docker. The `package` command as usual ensures dependencies are included in package
- The `package` command sets the `service.package.artifact` path to generated package path. This way `extractArtifact()` unzips the packaged artifact into docker before running the handler
- During this fix, I noticed an issue with `extractArtifact` where it fails to unzip folder with subfolder. This has been fixed by ensuring subfolder is created before creating the file in the subfolder
```yml
service: dependency-bug
provider:
name: aws
functions:
hello:
plugins:
- serverless-python-requirements
```
`handler.py`
```py
import os
import dns.resolver
def hello(event, …
```
> #5947: Ensure invoke local docker runs lambda with the dependencies

- lib/plugins/create/templates/aws-nodejs-ecma-script/serverless.yml
Node.js 6.10 is deprecated for AWS Lambda.
Updated Node.js runtime version to 8.10 (6.10 is being phased out).
Changed the serverless.yml file.
`sls create -t aws-nodejs-ecma-script -p nodetest`
Then confirm serverless.yml is using `nodejs8.10`.
> Updating Node.js runtime version

- lib/plugins/create/templates/aws-nodejs-ecma-script/second.js
- lib/plugins/create/templates/aws-nodejs-typescript/handler.ts
- lib/plugins/create/templates/aws-nodejs/handler.js
Make the first result a javascript developer has with Serverless, easier in the eyes by just adding better formatting to the `JSON.stringify()` function.
Added `JSON.stringify(response, null, 2)` instead of `JSON.stringify(response)`
> Make it easier on the eyes of serverless newcomers

- docs/providers/aws/guide/layers.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/layers/index.js
- lib/plugins/aws/package/compile/layers/index.test.js
closes #5765 by adding an option to allow the retention of previous layer verions
If the user specifies `retain: true` for their layer, `DeletionPolicy: Retain` is added to the cloudformation template, and the sha of the layer CFN is appended to the logical ID (otherwise old layer versions are still deleted)
```
npm i -g serverless/serverless#retain-layer-versions
echo 'layers: {foobar: {path: foobar, retain: true}}' >> serverless.yml
echo foo > foobar/foo
sls deploy
echo bar > foobar/bar
sls deploy
```
Then check that your lambda console has 2 versions of the foobar layer.
> Allow specifying a retention policy for lambda layers

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/resources.md
- lib/plugins/aws/info/getApiKeyValues.js
- lib/plugins/aws/info/getApiKeyValues.test.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js
Closes #4846
This PR adds support for multiple usage plan keys via an array definition as proposed by @thinkski in #4846
It's implemented in a backward compatible way, meanig that one can choose between an object or array representation where object describes 1 usage plan and an array (can) describe multiple usage plans. Using the object notation will create the exact same resources with the exact same logical ids like the Framework did prior to this PR (see the tests which validate that).
Updated the API Gateway plugin `lib` methods.
```yaml
service:
name: test
provider:
name: aws
stage: dev
apiKeys:
- free:
- freeKeyOne
- freeKeyTwo
- paid:
- paidKeyOne
- paidKeyTwo
usagePlan:
- free:
quota:
limit: 1
offset: 2
period: MONTH
throttle:
burstLimit: 100
rateLimit: 200
- …
```
> Add support for multiple usage plans

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Closes #5945
- The environment variables configured at provider level, service level and from command line options are passed to docker container using `--env` option for `docker run` command
```yml
service: env-var-bug
provider:
name: aws
environment:
SOME_ENV_VAR: some-value
functions:
hello:
```
`handler.py`
```py
import os
return os.environ['SOME_ENV_VAR']
```
```sh
npm install -g github:endeepak/serverless#bugfix/5945_invoke_local_docker_env_vars
sls invoke local -f hello --docker
```
> #5945: Invoke local docker to pass env vars to lambda container

- README.md
Made the following updates to our readme:
1) added link to Serverless's enterprise offering 
2) updated newsletter subscription link (mailchimp form -> form on serverless.com)
> update newsletter + enterprise link in readme

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
Added support for JSONSchema request body validation with API Gateway, Closing #3464. Reading the various docs for request validation(notably with CloudFormation), I couldn't quite understand how parameter or header validation would work. Any input regarding this implementation or how param/header validation would work is greatly appreciated.
Closes #3464
When you add a `schema` containing JSON schema to an HTTP event, the following are added:
* `AWS::ApiGateway::Model` with the schema specified
* `AWS::ApiGateway::RequestValidator` with `ValidateRequestBody: true` and attached to the `AWS::ApiGateway::RestApi` that serverless generates
* attach the model above to the `AWS::ApiGateway::Method` for the event
1. Install serverless from this branch: `npm i -g serverless/serverless#sls-3464` …
> AWS API Gateway request body validation

- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
Closes #6035 
Before sending the user to `getCommandSuggestion`, if the previous commands are valid, return a message telling the user how better to self-correct. Admittedly this message is only to tell the user how to run a command that will give him/her a better error message. Most error handling is handled well in the serverless framework. However, for these niche cases, I feel this is a slight improvement. 
This is only handled in error cases where the framework is basically saying "We don't know what you want". I couldn't find any tests for this case to modify.
Current handling: 
With this change:
This change does not conflict with any other `validation` methods. For example `validateOptions()` still runs as anticipated since this error case is only with commands or aliases.
***Is …
> Add more specific sub command error handling.

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test.js
- lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
- lib/plugins/aws/package/compile/events/websockets/lib/deployment.test.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
I replaced the region name in IAM Roles and ServiceEndpoint with a reference to `AWS::Region` [pseudo parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html). With this change to CloudFormation template output could be exported and re-applied in an other region. This is a really small change but could be part of a complete export of produced CloudFormation to be share with other and apply with a click (making deployment bucket public).
Followed the AWS documentation about pseudo parameters: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html
Create a new project, go to AWS Console under **CloudFormation -> Stacks -> Your service name**, then open the tab **Template** and you should see the …
> Use region pseudo parameter

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
Closes #4661 
Adds support for authorization scopes for COGNITO_USER_POOLS authorizer
Add property to http event authorizer
Package a function containing the additional properties
```
- http:
path: /my/api
method: get
authorizer:
arn:arn:aws:cognito-idp:ap-southeast-2:XXXXXXX:userpool/ap-southeast-2_mypool
scopes:
- myscope/read
- aws.cognito.signin.user.admin
```
Verify the AuthorizationScopes:  property is present in the generated cloudformation.
> Add authorization scopes support for cognito user pool integration

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js
Adds support for wildcards in cors domains for API gateway
Closes #6012
Transforms wildcarded domain to Java regex, which can be used in VLT template
Deploy an AWS with one lambda with multiple cors domains with wildcards. Use the following command
```
curl -H "Origin:<testing domain>"  -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: X-Requested-With"  -X OPTIONS --verbose <your api gateway URL>
```
If testing domain satisfies the wildcard, it will be returned in the Acces-Control-Allow-Origin header
***Is this ready for review?: ***Yes
***Is it a breaking change?: ***No
> Support wildcard in API Gateway cors domains

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes #5561
I tested with https://www.charlesproxy.com/ proxy.
I setup proxy to localhost:8888 and downloaded charles root certificate from the help menu.
Then ran command
`env https_cafile=charles-ssl-proxying-certificate.pem  proxy='http://localhost:8888' ../bin/serverless deploy`
with a sample project. It gives forbidden   `ServerlessError: The security token included in the request is invalid.` since I tested with invalid key(to not accidently deploying)
So the https connection with proxy and custom certificate seems to work.
> Support setting both proxy and ca file for awsprovider AWS config agent

- docs/providers/aws/events/streams.md
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
Closes #6047 
I added `Fn::Join` as an allowed dynamic ARN builder for stream type events. This only required adding `Fn::Join` to the conditionals checking valid input, and returning the array of elements to join as the stream name.
Deploying any Serverless config with a stream event using `Fn::Join` should work:
```yml
service: my-service
provider:
name: aws
functions:
my-function:
handler: handler.myHandler
events:
- stream:
type: kinesis
arn:
Fn::Join:
- ":"
- - arn
- aws
- kinesis
- Ref: AWS::Region
- Ref: AWS::AccountId
- stream/my-stream
```
> Allow Fn::Join in stream event arns

- lib/classes/CLI.js
- lib/classes/CLI.test.js
- lib/plugins/aws/deploy/lib/checkForChanges.js
Closes #6069 
Higghlights the log message when deployment are skipped.
I extended the `log` funciton to support `options` which can be passed in to e.g. underline or colorize the log output.
I looked into our Enterprise plugin and decided to **use the color `orange`** here which is used for warnings. This way the Serverless Framework CLI is consistent with what we're doing with our Enterprise plugin.
Here's how it looks like:
Alternatively I tested a way to print out the message in bold. Here's how that would look like:
Again. I've implemented the color `orange` to make it consistent with our Enterprise plugin. However I'm open to change it to be e.g. bold.
Just deploy a service and then re-deploy it.
> Highlight skipping of deployments

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/stage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/stage.test.js
Adds native support for API Gateway logs via the API Gateway stage resource.
Closes #4461
Merge in all the resources necessary to setup API Gateway logging via CloudFormation. Set the correct settings in the API Gateway Stage resource.
Deploy the following `serverless.yml`:
```yml
service: test
provider:
name: aws
apiGateway:
logs: true
functions:
hello:
events:
- http: GET hello
```
After that `curl` the endpoint and look into CloudWatch logs for the `api-gateway` log group.
> Add support for API Gateway REST API Logs

- lib/plugins/create/templates/aws-scala-sbt/build.sbt
- lib/plugins/create/templates/aws-scala-sbt/project/plugins.sbt
- lib/plugins/create/templates/aws-scala-sbt/src/main/resources/log4j2.xml
- lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Handler.scala
- lib/plugins/create/templates/aws-scala-sbt/src/main/scala/hello/Request.scala
Closes #XXXXX
+ Implemented logging that [recommended by AWS](https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html#java-logging-log4j2).
```
$ sls create -t aws-scala-sbt -p sls-scala
$ cd sls-scala
$ sbt assembly
$ sls deploy
$ sls invoke -f hello
$ sls logs -f hello # Please check to log from the function.
```
> Implement logging with Log4j2 for aws-scala-sbt

- CHANGELOG.md
- lib/plugins/aws/package/compile/events/apiGateway/index.js
- lib/plugins/aws/package/compile/events/apiGateway/index.test.js
- package-lock.json
- package.json
Fixed the use of `cors: true` in http event configs
Closes #6098
Closes #6102
Validate fails when called a second time with `cors: true` and I don't see
why it has to be called again. the service config doesn't change during a deploy
and it's already saved on `this.validated`.
But maybe there's a reason `this.validate()` has to also be called after deployment. @pmuens this was added in your PR.
```
sls deploy # this should give the origin/origins error
npm i -g serverless/serverless#sls-6098
sls deploy # no error
```
- ~~Write documentation~~
> fix use of cors: true

- CHANGELOG.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
- package-lock.json
- package.json
Fixed resolution of `restApiId` in post CF deployment phase
Closes #6100 
- Custom `restApiId` as set in `serverless.yml` where not taken into account. Ensure it's not the case
- Ensure `restApiId` is resolved as expected even if user has over 500 API's deployed.
1. Create APIGateway manually (e.g. through AWS Console)
2. Create a project that refers to that APIGateway (via `restApiId` and `restApiRootResourceId` settings) and adds some new HTTP endpoints
3. Confirm project deploys without an error and that HTTP endpoint is created
> Fix restApiId resolution in post CF deployment phase

- lib/Serverless.js
- lib/Serverless.test.js
- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
needed for SFE to enable deployment profiles serverless/enterprise-plugin#116
Added a hook for plugins to perform async initialization too.
added a check for an `asyncInit` function in plugins, and if it exists, call it expecting a promise.
install this branch & install the plugin from the pr referenced above & deploy
> Add a hook for plugins to perform asyncronous initialization.

- bin/test
- lib/classes/CLI.test.js
- lib/plugins/aws/invokeLocal/index.test.js
- package-lock.json
- package.json
As we test CLI output of some comment we have disabled color output for whole test run.
As having color output is convenient, I've updated those few tests to work as expected with colors on
I ensured we test non-colored output with help of [strip-ansi](https://www.npmjs.com/package/strip-ansi) package
Run tests
> Support color output in tests

- lib/classes/Service.test.js
- lib/classes/Utils.js
- lib/classes/Utils.test.js
- lib/plugins/aws/lib/getServiceState.js
- lib/plugins/aws/lib/getServiceState.test.js
- lib/plugins/aws/package/compile/events/apiGateway/index.js
- lib/plugins/aws/package/compile/events/apiGateway/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Closes #6117 
Fixes the bug where the event validation fails when the packaged service is deployed.
Added a helper method which checks if a given event is used in a service.
Use the following `serverless.yml` file:
```yaml
service: test
provider:
name: aws
tags:
foo: bar
baz: qux
num: 1234
tracing:
apiGateway: true
logs:
restApi: true
apiGateway:
binaryMediaTypes:
- '*/*'
functions:
test:
events:
- http:
method: GET
path: hello
```
Run
```
serverless package -p package
```
Comment out the whole `functions` section (with this we check the `after:deploy:deploy` hook will use the correct `serverless-state.json` file to check if API Gateway setup needs to be updated).
Run
```
serverless deploy --package package
```
Validate …
> Fix validation after API Gateway deployment

- CHANGELOG.md
- lib/plugins/aws/package/compile/events/apiGateway/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
- package-lock.json
- package.json
It appears there are cases where we cannot reliably resolve REST API id (as it can be set directly in CloudFormation, and even resolved via CF functions, for which there are no means to resolve reliably locally).
In light of that, hack that applies custom APIGateway settings post CF deployment was updated to 
not apply any settings, if no customizations are found in `serverless.yml` and we cannot resolve REST API id.
Additionally added support for custom `apiName` (before only default resolution was assumed)
Closes #6100 
- Added early exit if there are no APIGateway customizations and REST API id cannot be resolved.
- Added fallback for `provider.apiName` if provided
Deploy a service that resembles documented case, and test whether it deploys as expected.
***Is this ready for review?:*** …
> Improve handling of custom API Gateway options

- lib/plugins/create/templates/azure-nodejs/serverless.yml
.funcignore is not being used so have to add the ignore files
to the `exclude` section in serverless.yml
Update `azure-nodejs/serverless.yml` to exclude `vscode` settings and `local.settings.json` in function artifact.
```
sls create -t azure-nodejs -p myApp
cd myApp
npm install
sls deploy # verify that those files are not uploaded to the app
```
> azure: exclude development dependency files when packaging functions

- .travis.yml
- VERSIONING.md
- bin/serverless
- package.json
Closes #6076
Updates the required Node.js version to match the major Cloud providers Node.js runtime requirements.
Updated the version number in the `package.json` file.
Use the Serverless Framework with a Node.js version older than 8.
> Update required Node.js version / Add version check

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Closes #6133
Closes #6170
Use [tagResource](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#tagResource-property) and [untagResource](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#untagResource-property) that can use tag containing space. 
The following should deploy successfully where API GW stage are tagged with `bar bar` & `foo`.
```yaml
service: fix-6133
provider:
name: aws
tags:
foo: XXX
stackTags:
bar bar: ZZZ
functions:
hello:
events:
- http: GET hello
```
- N/A Write documentation
***Is this ready for review?:*** YES 
> Fix tagging API Gateway stage fails if tag contains special characters like space

- .eslintrc.js
- lib/plugins/aws/lib/getServiceState.js
- lib/utils/fs/readFileIfExists.js
- lib/utils/log/consoleLog.js
- lib/utils/log/fileLog.js
- lib/utils/log/log.js
- lib/utils/renameService.js
- lib/utils/sentry.js
- lib/utils/userStats.js
- tests/setupTests.js
It's about basic fixes and improvements (as otherwise bigger refactor into serverless projects common config is pending)
- Fix parsing option, with so far setting ESLint treated our modules as ESM, and disallowed certain syntax which is perfectly valid in CJS
- Fix configuration of `strict` rule, so it correctly enforces usage of `'use strict'` (having that, fixed few modules in which it was missing)
- Turn on `prefer-rest-aparams` rule (and fixed few modules which didn't obey)
- Configure `import/no-extraneous-dependencies` rules, so it works for us.
> Fix and improve ESlint config

- lib/plugins/aws/invokeLocal/index.test.js
- package.json
- tests/mocha-reporter.js
Fix regression introduced with #6169
_**Note**: To support used syntax, https://github.com/serverless/serverless/pull/6188 needs to merged first_
By mistake param was named `-R` not `R`. Unfortunately mocha silently ignored that error (proposed an improvement at: https://github.com/mochajs/mocha/issues/3936)
This patch brings back correct Mocha setup
Additionally async leaks detector was turned off in Node.js v6 testing, as proven to produce there false positives
> Tests: Fix mocha config

- .eslintrc.js
- docs/providers/aws/events/websocket.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/stage.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
- lib/plugins/package/lib/zipService.js
- scripts/postinstall.js
Adds support for Websocket logs.
Closes #6082
Add compilation of necessary CloudFormation resources.
```yaml
service: test
provider:
name: aws
logs:
websocket: true
functions:
connect:
handler: handler.connect
memory: 512
events:
- websocket: $connect
disconnect:
handler: handler.disconnect
memory: 512
events:
- websocket:
route: $disconnect
default:
handler: handler.default
memory: 512
events:
- websocket:
route: $default
echo:
handler: handler.echo
memory: 512
events:
- websocket: echo
```
```javascript
// handler.js
// handler.js
'use strict';
const AWS = require('aws-sdk')
// the following section injects the new ApiGatewayManagementApi service
// into the Lambda AWS SDK, otherwise you'll have to deploy the entire new version of the SDK
/* …
```
> Add support for Websocket Logs

- lib/plugins/package/lib/zipService.test.js
_Addresses #6116 (not closing yet as there are some further steps to make)_
Stub for sync function was configured to return rejected promise instead of throwing an error.
That theoretically produces unhandled rejection, still [`sinon-blubird` doesn't create real promises for `rejects()`](https://github.com/toddbluhm/sinon-bluebird/blob/2c496d62948460fe20ce43e5f7e19284629dbb4d/index.js#L12-L13), that's why it came unnoticed on our side.
With [Sinon upgrade](https://github.com/serverless/serverless/pull/6206) this issue will be eminent.
> Tests: Fix stub configuration

- .travis.yml
Regression after #6178 
It appears that Travis generated secrets are [not exposed to PR's coming from forks](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)
Therefore we turn off any integration test runs in context of PR's
> Do not run integration tests for PR's

- docs/providers/aws/guide/packaging.md
- lib/classes/Utils.js
- lib/classes/Utils.test.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
- tests/utils/fs/index.js
Adds support for package artifacts hosted on S3.
Closes #5315
One can now point to package artifacts hosted on S3.
The first implementation replaced the `Code` property of the Lambda function to point to the S3 artifact. However since the `artifactFilePath` traces through the whole codebase it's pretty much guaranteed that we break something if we try to mitigate checks related to the presence of the `artifact` in the given `artifactFilePath`.
The second iteration (the one implemented here) downloads the `.zip` file from S3 and sets the `artifactFilePath` on the function-level. This way we touch minimal code and Serverless does it's thing as if you're using the regular `package` configuration.
Create a S3 bucket, upload a deployment artifact (e.g. previously created via `serverless …
> Add support for S3 hosted package artifacts

- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Closes #2508, Closes #4686 
Our team has started to hit limitations on some growing services regarding the maximum allowed size for an IAM role, which is 10240 bytes.
```
An error occurred: IamRoleLambdaExecutioncanary - Maximum policy size of 10240 bytes exceeded for role hello-world-service-prod-us-east-1-lambdaRole
```
Checking the CloudFormation's templates I realized that somewhere between 60%-70% of the role policy is this:
```
{
"Action": [
"logs:CreateLogStream"
],
"Resource": [
{
"Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hello-world-service-prod-helloWorld:*"
}
...this repeats for every function on the project
]
}
```
and this:
```
{
"Action": [
"logs:LogPutEvents"
],
"Resource": [
{
"Fn::Sub": …
```
> Use common prefix for log groups permissions at Lambdas' execution roles

- .travis.yml
- package.json
Fix regression introduced with https://github.com/serverless/serverless/pull/6178
Setting _branches_ to `only: master` prevented all tag builds. It's also noted in Travis CI [documentation](https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches) that it's expected behavior:
> Note that safelisting also prevents tagged commits from being built. If you consistently tag your builds in the format v1.3 you can safelist them all with regular expressions, for example /^v\d+\.\d+(\.\d+)?(-\S*)?$/.
This patch ensures that release tags are whitelisted, and that deploy job runs with latest Node.js version (if not specified Travis tries to install project with its default which is v0.10).
Additionally fix mocha config property name. Current setting works, but it …
> Fix Travis CI deploy config

- CHANGELOG.md
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
- package-lock.json
- package.json
Fixes #6236 
It appears that #6212 handled only function names as resolved when no `name` is provided.
This patch ensure that proper polices are also created for function with custom `name
> Fix IAM policies setup for functions with custom name

- docs/providers/cloudflare/guide/intro.md
Documentation formatting issue
Closes #XXXXX (nothing)
Markdown hyperlink was missing a closing ")".
I added a ")".
By looking at it in Markdown preview mode.
> Fix formatting issue with Markdown link

- docs/providers/aws/events/apigateway.md
Docs update -> You can't use provider.tags together with shared API Gateway
> Update docs | dont use provider.tags with shared API Gateway

- .eslintrc.js
- tests/integration-all/api-gateway/service/serverless.yml
- tests/integration-all/api-gateway/tests.js
- tests/utils/misc/index.js
- Improved`createTestService` shape, so it accepts service config customization hook
- Ensure unique pre-prepared API key among different integration test runs (without that, another test cannot run if previous haven't cleaned up yet). This should address integration test fails as observed on master, e.g.: https://travis-ci.org/serverless/serverless/jobs/544767262
- Turned off `no-param-reassign` as it seems unjustified, and prevents on spot arguments handling
> Ensure integration tests do not fail when run concurrently

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
- lib/plugins/package/lib/zipService.js
- lib/plugins/package/lib/zipService.test.js
- tests/utils/fs/index.js
Closes #5748 
Basically, if your `include` items have `./` before them, it would grab the same file twice
```
package:
exclude:
- ./**
include:
- ./bin/**
```
This would grab `./bin/file` as well as `bin/file`.
As a fix, I'm stripping the `./` from the start of the pattern before adding the include patterns to globby.
Using the `aws-go` template, have a serverless.yml with the following:
```yml
service: golang-package # NOTE: update this with your service name
provider:
name: aws
runtime: go1.x
package:
exclude:
- ./**
include:
- ./bin/**
functions:
hello:
handler: bin/hello
events:
- http:
path: hello
method: get
```
Run `sls package` with the current Framework, and your zipfile in `.serverless/golang-package.zip` should have a duplicated file.
Checkout this branch and run `sls package` …
> Fix duplicate packaging issue

- .travis.yml
Issue observed at e.g. https://github.com/serverless/serverless/tree/v1.45.1
`lint-updated` crashes on tags and non-master branch runs, as master branch then is not retrieved by Travis.
Reconfigured so all files are linted in non PR cases.
> Fix Travis configuration for branch/tag runs

- docs/providers/aws/guide/plugins.md
- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
Closes #6017 
The list of plugins can now contain relative paths.
For example:
```yaml
plugins:
- 'myfirstplugin/plugin'
- 'mysecondplugin/plugin'
```
I added the service path (the one containing `serverless.yml`) to the list of path in which Node can load modules. That way relative paths work.
- in a directory with a `serverless.yml` file, create a sub-directory `foo`
- create a `bar.js` plugin in there, for example:
```js
'use strict';
class ServerlessPlugin {
constructor(serverless, options) {
}
}
module.exports = ServerlessPlugin;
```
- in `serverless.yml` import the plugin:
```yaml
plugins:
- 'foo/bar'
```
> #6017 Allow to load plugin from path

- docs/providers/cloudflare/guide/quick-start.md
Corrected document entry to be accurate.
> Added correction based on community feedback

- lib/classes/Service.js
- lib/classes/Service.test.js
the current default is using AWS region naming syntax,
this mean other cloud provider would have to add extra code
to set their default value.
Instead, region default should be left to each provider.
one line code change
1. Install this branch
1. Run `sls deploy` in 3 different scenario:
* set region as a flag
* set region in `serverless.yml`
* don't set region in flag or `serverless.yml`
> Remove default stage value in provider object

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/disassociateUsagePlan.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/disassociateUsagePlan.test.js
Updated `disassociateUsagePlan.js` to use naming service for determining stack name rather than directly appending stage to the service name.
Closes #6283
Utilized the naming service for retrieving the stack name rather than directly appending stage to the service name.
Before pulling down changes, in a directory with:
serverless.yml:
```
service:
name: my-test-service
frameworkVersion: ">=1.0.0 <2.0.0"
provider:
name: aws
runtime: python3.7
stage: myStage
region: us-west-2
stackName: ${self:service.name}
apiKeys:
- statusCheckKey
apiName: ${self:provider.stackName}
endpointType: regional
functions:
hello:
events:
- http:
method: post
path: "/hello
```
handler.py
```
import json
body = {
"message": "Go Serverless v1.0! Your function …
```
> Use naming to get stackName

- docs/providers/aws/README.md
"events" was misspelled as "evetns" in the url to alb.md
Fixed AWS docs. Link to ALB was broken due to typo.
I updated the URL to correct the typo.
1. Preview the change.
2. Click/tap on the link to the ALB event.
3. Verify that the link correctly takes you to the [AWS Application Load Balancer doc](https://github.com/serverless/serverless/blob/master/docs/providers/aws/events/alb.md).
> Fix typo in link to ALB docs

- docs/providers/aws/events/alb.md
- lib/plugins/aws/package/compile/events/alb/lib/listenerRules.js
- lib/plugins/aws/package/compile/events/alb/lib/listenerRules.test.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.test.js
Closes #6242
Add the following conditions for ALB events.
- header
- method
- query
- ip
Also allow multiple values for `host` and `path` conditions as @jviolas suggested.
I modified `lib/plugins/aws/package/compile/events/alb/lib/listenerRules.js` and `lib/plugins/aws/package/compile/events/alb/lib/validate.js` so that it supports the remaining conditions.
I added extra validation (especially for `ip` condition) because it's easy to specify a wrong configuration (an IP instead of a valid CIDR block for example). 
I added multiple values support for `host` and `path` conditions by using `_.concat` function in `validate.js`. Though I'm not sure this is the cleanest way of doing that.
I updated @pmuens example from #6073.
Use the following as `handler.js` and `serverless.yml`, then follow …
> Add ip, method, header and query conditions to ALB events

- .travis.yml
Travis by default restricts deploys to branch master, therefore it was not picked for [tag build](https://travis-ci.org/serverless/serverless/jobs/550690774) as expected.
This patch ensures deploy runs for tag builds
-- 
_As. a workaround v1.46.0 was published via temporary hack commit -> https://travis-ci.org/serverless/serverless/jobs/550696745_
> Ensure deploy is triggered in CI

- README.md
Add null as a consultant in the README.
[null](https://null.tc/) is the company maintaining [Bref](https://bref.sh/). Consulting helps us fund work on the open source project.
> Add null as a consultant

- docs/providers/aws/guide/credentials.md
Just fixed a tiny typo
insert `AWS API`
read it
> Update very minor typo in credentials.md

- lib/classes/Error.js
- lib/classes/Error.test.js
Currently when non-error object is thrown, it's simply stringified, so it can be displayed as:
```
Error --------------------------------------------------
[object Object]
Stack Trace --------------------------------------------
Error: [object Object]
at module.exports.logError (/Users/medikoo/npm-packages/serverless/lib/classes/Error.js:93:11)
at /Users/medikoo/npm-packages/serverless/bin/serverless.js:69:9
at processImmediate (internal/timers.js:439:21)
at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
at /Users/medikoo/npm-packages/serverless/bin/serverless.js:65:6
at Object.<anonymous> (/Users/medikoo/npm-packages/serverless/bin/serverless.js:71:7)
at Module._compile …
```
> Expose non-errors in informative way

- tests/mocha-reporter.js
Original detection just picked v8 and v9, this patch fixes that
> Fix async leaks detection conditional

- lib/plugins/aws/package/compile/events/websockets/lib/stage.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
The log group ARN contains a trailing ":*" that seems to cause
deployment to fail. Instead, generate the ARN with the trailing
wildcard.
Closes #6304 
Construct the log group ARN using Fn::Sub.
See issue referenced above.
_Note: Run `npm run test-ci` to run all validation checks on proposed changes_
> Websockets: fix passing log group ARN

- README.md
Add option for `serverless invoke local` apart from `serverless invoke`
> specify invoke local option in the guide

- lib/plugins/create/templates/aws-nodejs-ecma-script/package.json
- lib/plugins/create/templates/aws-nodejs-ecma-script/webpack.config.js
The current config will not work in the newest webpack version
Closes #XXXXX
Using currently webpack.config.js will not work in the recent webpack version, you will get the following error when running `invoke`:
With the new config:
Just updating the webpack config file.
Install this template and run 
`sls invoke local -f first` with the current config will fail, with the webpack.config.js that I'm proposing will succeed. 
_Note: All reported issues can be automatically fixed by running `npm run …
> Update Webpack version and usage of aws-nodejs-ecma-script template

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.test.js
Closes #6320 
This is a fix proposal, might have to wait until a better solution is found.
Instead of using `<normalizedFunctionName>-<stage>` as a Target Group name, use a md5 hash of the combination of service name, function name and stage. It would ensure uniqueness across services.
Also, to make Target Groups searchable in the EC2 console, add a `Name` tag to the Target Group with value `<service name>-<function name>-<stage>`.
Important: Target Group names are limited to 32 chars, that's why I had to use a hash instead of using a readable name. This is not satisfying but I could not come up with a better solution, so if someone has a better one, that would be great ! I hope AWS will increase this limitation in the futur.  
Added some functions in `lib/plugins/aws/lib/naming.test.js` …
> Make ALB event target group names unique

- .travis.yml
- Ensure that latest versions of dependencies are installed for each build
- Configure cache (reduces install time from ca 30s to 5s)
- Instead of joining scripts with `&&`, configure Travis bash with `set -e`. Improves configuration readability and makes Travis behave up to expectations (fail build on first script fail)
- Ensure to fail builds if deployment fails
- Reduplicate env vars configuration (by configuring common global group via `env.global`)
- Improve inline comments
> Improve Travis CI conf

- docs/providers/aws/cli-reference/install.md
- docs/providers/azure/cli-reference/install.md
- docs/providers/google/cli-reference/install.md
- docs/providers/openwhisk/cli-reference/install.md
- lib/utils/downloadTemplateFromRepo.js
- lib/utils/downloadTemplateFromRepo.test.js
Closes #5332 
Check wether the provided repository url contains 'github' keyword. I originally intended to also check if the url was a valid github entreprise url (using the /api/v3 endpoint as a verification endpoint), but i had trouble having the test running fine after, so i stopped at "if url is not github.com, but contains github, then it's a github entreprise url".
Provided you have a github entreprise setup:
`./bin/serverless create --template-url https://github.mydomain.com/serverless-template/tree/master/non-prod/aws-nodejs --path test`
`./bin/serverless create --template-url https://username:password@github.mydomain.com/serverless-template/tree/master/non-prod/aws-nodejs --path test`
I tested with my own setup (I'm working in a company that has its own dedicated github …
> Support for Github Entreprise in sls create

- .travis.yml
- CHANGELOG.md
- lib/plugins/aws/provider/awsProvider.js
- package.json
Merging the Patch release artifacts (e.g. updates to `CHANGELOG.md`) back into `master` to keep the history.
**IMPORTANT:** Don't delete the branch after merging as we might have other patch releases we want to do and need to merge back into `master` once released.
> Merge patch 1.46.1 release artifacts back into master

- docs/providers/aws/events/s3.md
- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/index.test.js
- lib/plugins/aws/customResources/resources/README.md
- lib/plugins/aws/customResources/resources/s3/handler.js
- lib/plugins/aws/customResources/resources/s3/lib/bucket.js
- lib/plugins/aws/customResources/resources/s3/lib/permissions.js
- lib/plugins/aws/customResources/resources/utils.js
- lib/plugins/aws/customResources/resources/utils.test.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/s3/index.test.js
- lib/utils/fs/createZipFile.js
- lib/utils/fs/createZipFile.test.js
- tests/integration-all/s3/service/core.js
- tests/integration-all/s3/service/serverless.yml
- tests/integration-all/s3/service/utils.js
- tests/integration-all/s3/tests.js
- tests/utils/misc/index.js
- tests/utils/s3/index.js
This PR adds support for existing S3 buckets via a custom resource.
Refs #4241
Checks the `existing` config property of the `s3` event and swaps out the S3 CloudFormation resource with a custom resource the Serverless Framework provides. The custom resource basically does raw SDK calls to update the existing S3 bucket. This way everything is encapsulated via CloudFormation and the stack won't get out of sync if we implement it via raw SDK calls.
```yaml
service: test
provider:
name: aws
functions:
test:
events:
- s3:
bucket: existing-s3-bucket
event: s3:ObjectCreated:*
rules:
- prefix: uploads
- suffix: .jpg
existing: true
```
> Add support for existing S3 buckets

- docs/providers/aws/guide/variables.md
- lib/classes/Variables.js
- lib/classes/Variables.test.js
Closes #4608
Per @lorengordon's suggestion in the issue, I looked at the `Type` field in the `getParameter` response and, based on the presence of the `~split` extended option, I split the resulting string by comma.
1. Create an AWS SSM StringList parameter:
```sh
aws ssm put-parameter --name /Testing/MyStringListParam --type StringList --value "Val1,Val2"
```
2. Reference that parameter in `serverless.yml`:
```yml
custom:
array: ${ssm:/Testing/MyStringListParam~split}
```
3. Print the CloudFormation template using `sls print` and verify that the `array` variable value is an array:
```sh-session
$ sls print
#...
custom:
array:
- Val1
- Val2
#...
``` …
> Allow optionally splitting SSM parameter value for StringList type

- lib/plugins/interactiveCli/index.js
Fix bug that prevents reasonable detection of interactive CLI by `sls.interactiveCli` (doesn't affect any users currently)
> Fix premature interactiveCli setup

- lib/classes/CLI.js
- lib/classes/Error.js
- lib/classes/Error.test.js
In `logWarning` function, added a check for an environment variable named `SLS_NO_WARNINGS`.
When this env var is set (much like `SLS_DEBUG`) all the warnings are hidden from the output.
Closes #6346 
Well, I added a guard clause at the beginning of the `logWarning` function.
If the env var is set, the function exits without printing.
* In your `serverless.yml`, try to define some SSM parameters that are not defined
* Run `sls deploy` and see the warnings about undefined SSM params
* Run `SLS_NO_WARNINGS=* sls deploy` and enjoy no warnings
**Validate via …
> Add SLS_NO_WARNINGS env var

- lib/plugins/interactiveCli/setupAws.js
It didn't allow '+' chars, which may appear in secret keys (although are not present in all cases, hence didn't pick initially)
> Fix AWS secret access key validation in interactive CLI

- scripts/postinstall.js
via @skierkowski:
> since `serverless` creates the new folder, we can truncate `in a new folder.` from the `npm i` message.
> Improve post install message

- lib/plugins/create/create.js
- lib/utils/createFromTemplate.js
- lib/utils/createFromTemplate.test.js
Service name in `serverless.yml` of interactively created project was not updated to chosen project name.
This patch ensures that `createFromTemplate` util that covers that part
Additionally improved error handling of eventual file system access issue.
> PLAT-1385 Ensure expected service name in interactively created project

- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Closes #5700 
Just changed the expecting log subscription ARN from being calculated using `functionName` (which is always the name of the function object in `serverless.yml`, to instead use `functionObj.name`, which will use the `name` field if provided, and the default name if not (as it is set in the `setFunctioNames` method in `Service.js`).
`serverless deploy` a function with CloudWatch Logs triggers and with the `name` field set (an example is given in the original issue and re-listed below).
~~~~
functions:
app:
name: cloudwatch2loggly
handler: src/index.handler
events:
- cloudwatchLog: '/aws/lambda/${self:provider.stage}-function1'
- cloudwatchLog: '/aws/lambda/${self:provider.stage}-function2'
- cloudwatchLog: '/aws/lambda/${self:provider.stage}-function3'
~~~~
Opening CloudWatch …
> Changed AWS subscription filters to use function object name

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes [PLAT-936](https://serverlessteam.atlassian.net/browse/PLAT-936)
Adds default profile load attempt to list of credentials attempted (the fact it worked before was purely bc `aws-sdk` falls back to that), and then if no credentials are found at all, throws an error.
```
npm i serverless/serverless#missing-aws-creds-fail-fast
mv ~/.aws ~/.awsbak
sls deploy
```
**_Is it …
> Fail faster when no AWS creds exist

- lib/utils/renameService.js
- lib/utils/renameService.test.js
Trailing comments in most template cases is a following instruction
```
```
Leaving it after rename is misleading
> Strip trailing comment when renaming a service

- lib/classes/Variables.test.js
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/package/lib/packageService.js
- lib/utils/getServerlessConfigFile.js
It appears that `@serverless/eslint-config` v1.1.0 unexpectedly broke lint status.
It's due to  this change: https://github.com/serverless/eslint-config/pull/9
Could be observed in CI master fail: https://travis-ci.org/serverless/serverless/jobs/561062590
> Fix broken lint outcome after 'no-confusing-arrow' change

- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/permissions.js
- tests/integration-all/cognito-user-pool/tests.js
Closes #6418
Updated regular expression to remove spaces.
Simply create a Cognito User Pool with a name that has spaces in it.
> Remove spaces from Cognito Pool Name

- lib/classes/CLI.js
- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/interactiveCli/setupAws.js
Updated the copy in the CLI to use the shorter slss.io links
Replacing a number of strings in the CLI, AWS Provider, and Interactive sign up.
- run `sls --help` and the "Framework" section should show the new link
- run `sls` without a '~/.aws/credentials` file and the wizard should prompt for AWS credentials. In the subsequent step the link should be updated.
- Run `sls deploy` without a `~/.aws/credentials` or an AWS Access Role in SFE. It should fail and display the new link
> Use slss.io for links

- lib/plugins/interactiveCli/setupAws.js
because this is how the sfe plugin sets creds
partially implements PLAT-1390
also check the AWS provider class's `cachedCredentials` property that the plugin uses to pass credentials into serverless
> PLAT-1390 - check for cached creds in interactive setupAws

- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Closes #6443
Rather than calling `getAccountId`, call `getAccountInfo` which will include the partition, and include the partition as a variable when setting [`newDestinationArn `](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/checkForChanges.js#L220)
```
service: my-service
provider:
name: aws
runtime: python3.6
region: us-gov-west-1
functions:
hello:
events:
- cloudwatchLog:
logGroup: '/var/log/cloud-init-output.log'
filter: 'some filter'
```
Deploy a function with a cloudwatch log group with a [filter](https://serverless.com/framework/docs/providers/aws/events/cloudwatch-log/) as the event source on a gov-cloud account.
Make some kind of update to the event source, or to the function and `sls deploy` again. The event source …
> Remove hard coded partition when validating subscription filters

- docs/providers/aws/events/sns.md
- lib/plugins/aws/package/compile/events/sns/index.js
- lib/plugins/aws/package/compile/events/sns/index.test.js
Closes #6444
If Lambda function subscribes to multiple topics with the same name allow defined `topicName` to take precedence when creating CloudFormation resources and to prevent resource name collisions.
Configure two topics with the same name in two different accounts (or in two different regions):
```
functions:
hello:
handler: handler.run
events: 
- sns: 
arn: arn:aws:sns:us-east-1:00000000000:topicname
topicName: topicname-account-1-us-east-1
- sns: 
arn: arn:aws:sns:us-east-1:11111111111:topicname
topicName: topicname-account-2-us-east-1
```
Deployment should succeed without an error. Check if two CloudFormation resources of type AWS::SNS::Subscription exist and if they have "sanitized" name taken from `topicName`.
_**Note: Run `npm run test-ci` to run all validation checks on …
> Fix cross-account/cross-regions SNS subscriptions to topics with the same name

- docs/providers/aws/cli-reference/invoke-local.md
Added a note / warning about precisely when the environment variables will become available for use.
I updated the documentation for invoke-local to warn people about when environment variables will be available. Importantly, IS_LOCAL is *not available* when parsing the `serverless.yml` file. This may actually be a bug, in which case it should be reported and fixed, but I suspect there is a good reason for the current behaviour so I am proposing a documentation edit accordingly.
Documentation change - per the contribution policy, I opened a pull request straight away, rather than opening an issue first and seeing if enough people were confused like me.
Please let me know if this is more appropriately handled somewhere else, such as a self-answered StackOverflow post. I won't be offended …
> Update invoke-local.md documentation

- docs/dashboard/insights.md
Fixed documentation for new error type insight alert to indicate that inspection is performed on every execution (and not on a scheduled 5 minute period as previously).
Adding markdown docs in `./docs`
Verified by comparing with current implementation.
> New error insight alert doc update to reflect per execution inspection

- lib/plugins/aws/customResources/resources/s3/lib/bucket.js
- lib/plugins/aws/customResources/resources/utils.test.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/s3/index.test.js
- tests/integration-all/s3/service/serverless.yml
- tests/integration-all/s3/tests.js
Closes #6409
Fixes some issues with existing S3 buckets. E.g. the prefix / suffix values were always lowercased. Also uses Refs and AWS Variables to construct IAM policies.
Fix it and write regression tests.
The easiest way is to run the integration tests for S3 buckets.
Otherwise you can also deploy the following service:
```yaml
provider:
name: aws
custom:
idx: 0
bucket: serverless-existing-s3-bucket # change this with your bucket name
functions:
test:
events:
- s3:
bucket: ${self:custom.bucket}
events: s3:ObjectCreated:*
rules:
- suffix: .txt
- prefix: CamelCase/
existing: true
```
**Validate via `npm …
> Existing S3 bucket fixes

- lib/plugins/create/templates/aws-ruby/handler.rb
Enhanced `aws-ruby` handler template to render event information in response JSON, just like `aws-nodejs` template does.
Closes #6462 
Changed `handler.rb` to render `event` information under `input` key in body - just like in `aws-nodejs` template. Also - ditched `JSON.generate` in favor of `to_json`, since `JSON.generate` is invalid syntax till ruby-2.4.0 and it may be discouraging for new people.
```
$ bin/serverless -t aws-ruby --path test
$ cd test
$ serverless deploy # given aws configured
$ curl -X GET url-gained-from-previous-output
``` …
> Render event information in aws-ruby handler template

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
fix for https://github.com/serverless/serverless/issues/6482
Normalize paths before matching
Closes #6482
I wrapped the paths in `path.normalize` 
Deploy a Golang binary (built & packaged on Windows with linux as target) to AWS lambda and try to execute it.
None
(This is my first contribution on Github ever, feedback is much appreciated)
> Fix invalid path char in GoLang packaging on Windows

- docs/providers/aws/events/s3.md
- lib/plugins/aws/customResources/resources/s3/handler.js
- lib/plugins/aws/customResources/resources/s3/lib/bucket.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/s3/index.test.js
- tests/integration-all/s3/service/core.js
- tests/integration-all/s3/service/serverless.yml
- tests/integration-all/s3/tests.js
Closes #6461
Adds support to define multiple S3 events in one function.
Fix it and write regression tests.
Use the following `serverless.yml` file or run the S3 integration tests (which were updated as well).
```yaml
provider:
name: aws
custom:
idx: 0
bucket: serverless-existing-s3-bucket # replace this with your bucket name
functions:
created:
events:
- s3:
bucket: ${self:custom.bucket}
events: s3:ObjectCreated:*
rules:
- suffix: .txt
- prefix: files
existing: true
- s3:
bucket: ${self:custom.bucket}
events: s3:ObjectCreated:*
rules:
- suffix: .pdf
- prefix: files
existing: true
removed:
events:
- s3:
bucket: ${self:custom.bucket}
event: s3:ObjectRemoved:*
rules:
- …
```
> Multiple event definitions for existing S3 bucket

- lib/classes/CLI.js
- lib/classes/CLI.test.js
Removed `Enterprise` and `Platform` from logline
With the `delete` key.
run `serverless -v` against this branch, or require this class in a node console and run `getVersionNumber()`
> Remove Enterprise and Platform from log info

- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Closes #5817 
Closes #6263 
As suggested in #6263, changed cloudwatch log subscription filters to name their logical IDs using their log group name rather than using an incrementing serial number. This prevents CloudFormation from getting confused (due to new subscription filters having the same name but different log groups than older ones) when a subscription filter is added to or removed from anywhere except the end of a template.
However, this brings up another problem: this would break any projects that already existed using the serial number naming scheme (I tested and confirmed that this problem does exist). Therefore, I also added an extra condition to the code that removes subscription filters if the old and new destination ARNs don't match: they must also have the same logical …
> Allow AWS Subscription Filters to be reordered

- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/s3/index.test.js
What did you implement:
Adds a check if more than 1 S3 bucket is being configured.
Related to changes made in #6491
Track S3 bucket names while compiling CloudFormation resources.
```yaml
provider:
name: aws
custom:
idx: 0
bucket: serverless-existing-s3-bucket
functions:
created:
events:
- s3:
bucket: ${self:custom.bucket}
existing: true
- s3:
bucket: ${self:custom.bucket}-2
existing: true
```
should throw, while the following doesn't:
```yaml
provider:
name: aws
custom:
idx: 0
bucket: serverless-existing-s3-bucket
functions:
created:
events:
- s3:
bucket: ${self:custom.bucket}
existing: true …
```
> Check if more than 1 existing bucket is configured

- docs/providers/aws/events/cognito-user-pool.md
- lib/plugins/aws/customResources/resources/cognitoUserPool/handler.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
- tests/integration-all/cognito-user-pool/service/core.js
- tests/integration-all/cognito-user-pool/service/serverless.yml
- tests/integration-all/cognito-user-pool/tests.js
- tests/utils/cognito/index.js
Closes #6420 
Adds support to define multiple Cognito User Pool events in one function.
Fix it and write regression tests.
Use the following serverless.yml file or run the Cognito User Pool integration tests (which were updated as well).
```yaml
provider:
name: aws
custom:
idx: 0
pool: ExistingUserPool
functions:
pre:
events:
- cognitoUserPool:
pool: ${self:custom.pool}
trigger: PreSignUp
existing: true
- cognitoUserPool:
pool: ${self:custom.pool}
trigger: DefineAuthChallenge
existing: true
post:
events:
- cognitoUserPool:
pool: ${self:custom.pool}
trigger: CreateAuthChallenge
existing: true
- cognitoUserPool:
pool: ${self:custom.pool}
trigger: …
```
> Multiple event definitions for existing Cognito User Pools

- bin/serverless.js
- lib/classes/Error.js
- lib/classes/Error.test.js
- Do not pass _handled_ errors via _unhandled rejections_ channel - it's a logic error, that's also  indirect cause of #6441 
- Use default error logging for _uncaught exceptions_, but ensure process exits immediately after report is made (improves UX)
- Propagate _unhandled rejections_ as _uncaught excpeptions_ but only if no other _unhandled rejection_ handlers were registered (it's to resemble eventual future Node.js behavior, and to allow users to opt out from this handling - related issue: https://github.com/dherault/serverless-offline/issues/255)
- Use default error logging for non error exceptions (improves UX)  
_~~(Note: here to distinguish error instances I decided to rely on `type/error/is`, which makes it a new dependency. It's the best way known to me to detect a native …
> Improve error handling

- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
Closes #5513 
Added PreTokenGeneration & UserMigration triggers to the validTriggerSources since CloudFormation already supports [it](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html):
```js
const validTriggerSources = [
'PreSignUp',
'PostConfirmation',
'PreAuthentication',
'PostAuthentication',
'PreTokenGeneration',
'CustomMessage',
'DefineAuthChallenge',
'CreateAuthChallenge',
'VerifyAuthChallengeResponse',
'UserMigration',
];
```
1. Bootstrap Serverless framework project.
2. Add the following code to `serverless.yml`:
```yaml
service:
name: testservicename
custom:
stage: ${opt:stage, 'dev'}
region: ${opt:region, 'eu-central-1'}
provider:
name: aws
stage: ${self:custom.stage}
region: …
```
> Add PreTokenGeneration & UserMigration Cognito triggers

- docs/providers/kubeless/guide/functions.md
Added documentation on using kubeless with custom Ingress Controllers and adding annotations. 
Updated the example serverless.yml at the top of the guide, and added a fleshed out section further down.
Proofread the docs and check it largely makes sense.
> Update kubeless guide docs

- lib/plugins/interactiveCli/setupAws.js
- lib/utils/open.js
- lib/utils/openBrowser.js
- package.json
closes PLAT-1341
implemented by asking if the user has an account, if not, open browser to sign up
and then open browser (in new or existing acct case) to create an admin user for
user with serverless.
added open as a dependency to open the browser
```
npm i -g serverless/serverless#nicer-aws-creds-flow
mv ~/.aws ~/.awsbak
sls
```
> Improve interactive AWS creds flow

- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
- tests/integration-all/cognito-user-pool/tests.js
- tests/utils/cognito/index.js
Closes #6499 
Ensures that the existing Cognito User Pool Config is retained.
Fetch the current config and re-apply it to the params when updating the Cognito User Pool with the desired Trigger config.
1. Create a new User Pool
1. Add a tag
1. Deploy the following `serverless.yml` service
The Trigger config should be updated. The tag should not be removed.
Otherwise you can also run the integration tests.
**_Is …
> Retain existing Cognito User Pool config

- .travis.yml
- package.json
- scripts/test-isolated.js
- tests/integration-all/api-gateway/tests.js
- tests/integration-all/cognito-user-pool/tests.js
- tests/integration-all/event-bridge/tests.js
- tests/integration-all/s3/tests.js
- tests/integration-basic/tests.js
- tests/integration-package/cloudformation.tests.js
- tests/integration-package/lambda-files.tests.js
- tests/mocha-reporter.js
- tests/setup-tests.js
- tests/utils/misc/index.js
There are various problems with Jest:
- It runs tests in copied/hacked Node.js environment which introduces some issues (not patchable)
- `stdout` and `stderr` are output of out sync https://github.com/facebook/jest/issues/6718
- Some public Node.js API's are replaced with non standard alternatives -> https://github.com/facebook/jest/issues/6725
- Due to non standard and uneven modules cache handling it's prone to OOM errors: https://github.com/facebook/jest/issues/6399#issuecomment-415083479
- Tests progress is not output until tests finalize, which is inconvenient in long going tests (as integration ones) -> https://github.com/facebook/jest/issues/6616 (not easily patchable)
- Any stdout/stderr output is hidden until test finalizes -> https://github.com/facebook/jest/issues/5281 …
> Switch integration tests runner from Jest to Mocha

- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Check that a function was modified after artifact when deciding to deploy.
Closes #3983 
The problems arose because serverless put the user's code inside the s3 bucket, but the stack update failed to update the lambda's code. On the next deploy attempt serverless would see that the artifacts in the s3 bucket are identical to the ones it is trying to push, and incorrectly assume that the deploy is a no-op. This fixes the issue by adding an additional check when deciding if the deploy would be a no-op or not: Was the function last edited **after** the s3 objects, or **before** the s3 objects? If it was edited after, you can presume that the cloudformation was succesful since you can only run the cloudformation after updating the objects in s3. If it was edited after, you can infer that …
> Change strategy for deciding to deploy new function.

- lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js
- lib/plugins/aws/package/compile/events/eventBridge/index.js
- lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Closes #6514 
Fixes support for EventBridge partner event sources.
Fix the arn parser.
See [service config](https://github.com/serverless/serverless/issues/6514#issue-478071889) posted in the issue.
> Fix support for EventBridge partner event sources

- .travis.yml
Coveralls is down for maintainace. Do not crash Ci in such cases
> Do not crash CI on Coveralls error

- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Closes #6262 
Made serverless only add the wildcard IAM policy for canonically named functions if there are actually canonically named functions in the service.
Full source: [log-group-policy.zip](https://github.com/serverless/serverless/files/3496926/log-group-policy.zip)
```yml
service: log-group-policy
provider:
name: aws
functions:
testFunction:
name: ${self:service}-custom-named-fn
```
```
mkdir /tmp/test-packaging-for-6262
cd /tmp/test-packaging-for-6262
unzip log-group-policy.zip
cd log-group-policy
echo '{}' > package.json
npm i serverless@1.44.1
./node_modules/.bin/sls package
cp .serverless/cloudformation-template-update-stack.json cf-update-stack-v1.44.1.json
${PATH_TO_SERVERLESS_CLONE}/bin/serverless package
cp …
```
> Only add merged IAM policies for Lambda when they will be used (#6262)

- README.md
- lib/plugins/aws/deploy/lib/extendedValidate.js
- lib/plugins/aws/deploy/lib/extendedValidate.test.js
Closes #6120
The issue was that `sls deploy` didn't work if package.individually was set on a function-level. According to the docs, it should work but looks like it has never worked.
I simplified & cleaned up the validation logic that runs before deployment.
I gave two examples in the comment: https://github.com/serverless/serverless/issues/6120#issuecomment-520944321. Both works now.
**_Is this ready for …
> Fix deploy command if package.individually set on a function-level

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Added support for specifying the AWS API Gateway log level to be used. I also updated the sample AWS serverless.yml.md file to include the log format option as that was missing when that feature was added.
This is an enhancement to API Gateway logs as part of #6094.
Users can now customize the log level by setting the `provider.logs.restApi.level` optional setting in serverless.yml to either INFO (default value) or ERROR:
```yml
provider:
name: aws
logs:
restApi: 
level: ERROR
```
An error will be thrown if something other than INFO or ERROR is provided. I updated updateStage.js to use the user-provided log level if available, otherwise it falls back to the default INFO as before.
Create a serverless project and set `provider.logs.restApi.level` to either INFO or ERROR and run a deploy. …
> AWS API Gateway customize log level

- lib/classes/Utils.js
- lib/classes/Utils.test.js
Closes #6555
Return `null` from `logStat` promise to remove Bluebird `Warning: a promise was created in a handler but was not returned from it` when NODE_ENV=development
http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it
Setting `NODE_ENV=development` triggers these warnings to be written to the console by Bluebird with `serverless@1.48.1` and above. I was also running locally with `serverless-offline` when I noticed this new warning. …
> Fix: Remove Bluebird promise warning when NODE_ENV=development

- lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.test.js
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/provider/awsProvider.js
What did you implement:
Implemented setting the value of RetentionInDays to provider.logRetentionInDays on the API Gateway LogGroup created when logging is enabled.
This is an enhancement to API Gateway logs as part of #6094.
The created API Gateway log group will now respect the value set on logRetentionInDays:
```yml
provider:
aws: aws
logRetentionInDays: 30
logs:
restApi: true
```
If this value is unset then the expiration is set to never expire, which is the current default.
Create a serverless project and set provider.logs.restApi=true and provider.logRetentionInDays to an integer greater than 0 and run a deploy. Remove the value to unset the log retention value.
> AWS API Gateway set value of provider.logRetentionInDays for log group expiration

- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Regression introduced with https://github.com/serverless/serverless/pull/6520
Prepared mocks did not cover some tests which (after #6520 improvement) invoked `Lambda.getFunction` AWS SDK endpoints.
Those calls either crashed quickly (which didn't affect test result, as there's catch all), or timed out depending on AWS creds env setup.
This patch ensures no real SDK calls are made
> Ensure AWS SDK is mocked for tests that call it

- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Implemented to ability to control enabling and disabling both access and execution logs for API Gateway, as well as the ability to configure the dataTrace parameter ("Log full requests/responses data" in the AWS Console). This allows for finer-grained control over which aspects of logging are enabled for the API Gateway.
This is an enhancement to API Gateway logs as part of #6094.
You can now configure whether or not access logging is enabled by setting enableAccessLogging to true/false (defaults to true if not set), dataTrace to true/false (defaults to true) and level to OFF to disable execution logging.
```yml
provider:
aws: aws
logs:
restApi:
enableAccessLogging: false
level: OFF
dataTrace: true
```
Create a serverless project and set any of the provider.logs attributes mentioned above …
> API Gateway enable/disable access/execution logs

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
Closes #6140 
With #6048 (published with v1.42.0), we've introduced support for `logs`, `tags` (and improved `tracing`) options for APIGateway settings.  Still as modifications to those settings are not supported in CloudFormation, we decided to update them directly via SDK calls (after CloudFormation stack is successfully deployed)
To be able to pursue SDK calls we need to be able to resolve Rest API id programmatically.
If we're unable to resolve Rest API id, we crash. Still with one of the further patches (to revert from reported regression) we've improved the behavior, so we crash only if one of the new options is used 
Still that fix was not complete, as `tags` option is service wide, and was supported before v1.42.0 to tag on lambda resources.
Therefore if `tags` option is used …
> Allow unresolved Rest API id with  provider.tags setting

- lib/classes/Error.js
- lib/classes/Error.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
1. Ensure that Rest API resolution error is reported as _user_ error (via `ServerlessError`), so no stack trace is shown by default.
2. Improve formatting of multiline messages
Before:
```
Rest API id could not be resolved.
This might be caused by a custom API Gateway configuration.
In given setup stage specific options such as `tracing`, `logs` and `tags` are not supported.
Please update your configuration (or open up an issue if you feel that there's a way to support your setup).
```
After:
```
Rest API id could not be resolved.
This might be caused by a custom API Gateway configuration.
In given setup stage specific options such as `tracing`, `logs` and `tags` are not …
```
> Improve error reporting

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Fixes #6251
Our REST API id resolution is quite high level and not fully reliable, as it's based on checking of some configuration settings as setup by user (searching for custom `provider.apiName` and if not found assuming the name will be default as setup by Framework).
It didn't work for cases where API Gateway resource was configured at lower level, e.g. fully in `resources.Resources` or extended there with custom name.
This patch ensures we read the API name directly from generated CloudFormation template.
At same time, it fixes the regression introduced with v1.42.0 after which relying on `tracing.apiGateway` option (with shared API Gateway setup) started to crash as Rest API was not resolved programmatically (reported at #6251)
> Improve Rest API id resolution for SDK updates

- lib/plugins/interactiveCli/index.js
- package.json
Added `interactiveCli:end` lifecycle hook to enable serverless/enterprise-plugin#226
added `'end'` lifecycle hook to the interactiveCli plugin
checkout this branch and use the plugin from the other pr and try the sls interactive flow, you should get the messages at the end.
> Interactive CLI interactive hook

- lib/classes/Error.js
- lib/classes/Error.test.js
- lib/plugins/aws/deploy/lib/createStack.js
- lib/plugins/aws/deploy/lib/createStack.test.js
I've just approached following error:
```
Type Error ---------------------------------------------
TypeError: message.split is not a function
at writeMessage (/Users/medikoo/npm-packages/serverless/lib/classes/Error.js:42:29)
at module.exports.logError (/Users/medikoo/npm-packages/serverless/lib/classes/Error.js:71:3)
at /Users/medikoo/npm-packages/serverless/bin/serverless.js:70:9
```
It's caused by error object passed directly to `ServerlessError`: 
https://github.com/serverless/serverless/blob/4d64b9d21b961cbb77e671256e8868e2a0bc8c74/lib/plugins/aws/deploy/lib/createStack.js#L91
And then being assigned to `error.message`:
https://github.com/serverless/serverless/blob/4d64b9d21b961cbb77e671256e8868e2a0bc8c74/lib/classes/Error.js#L52
I've fixed the error passing, so it's direclty the …
> Fix ServerlessError handling

- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/index.test.js
Currently with long service names, there's a chance that generated lambda function names for custom resources will extend 64 lenght limit.
With this patch we ensure such names are truncacted (without a risk of collision, and without changing the names of already deployed functions)
> PLAT-1629 - Fix custom resource lambda naming

- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/index.test.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.test.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
- lib/plugins/aws/package/compile/events/eventBridge/index.js
- lib/plugins/aws/package/compile/events/eventBridge/index.test.js
- lib/plugins/aws/package/compile/events/lib/ensureApiGatewayCloudWatchRole.js
- lib/plugins/aws/package/compile/events/lib/ensureApiGatewayCloudWatchRole.test.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/s3/index.test.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
With #6531 we moved API Gateway CloudWatch role setup to custom resource (as it appeared it cannot be done reliably in context of CloudFormation stack)
Still we missed the fact that CloudWatch role is configured also with setup of WebSockets logs, and that part was left out.
This PR ensures CloudWatch role is setup same way in both cases, and that it's setup once if logs for both are configured.
--- 
I've run WebSocket integration tests to confirm nothing accidently got broken. Tests passed fine
> Ensure API Gateway CloudWatch role is setup via custom resource

- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/index.test.js
It's helpful when debugging custom resources to be able to inspect their logs.
Still at this point those logs are not written to CloudWatch (I take it's intentional, as we want to generate as least resources as possible).
I've added an option to have those logs written if needed.
> Support optional CloudWatch logs writing for custom resource lambdas

- lib/plugins/interactiveCli/inquirer.js
- package.json
Fixes #6605 
Patch through which we ensure that inquirer works with hacked version of `chalk` was relying on resolution of module id (path), which did not took into account eventual symlinks redirection (hence when symlinks were involved, the resolved chalk path was not necessary correct).
This patch updates `ncjsm` to version that exposes module file real path (so one that's definitely used as module id).
> Ensure inquirer's chalk override works through symlinks

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Fixes aws partition name in apigateway resourceArn to allow for a govcloud partition name of aws-us-gov in the case where one is trying to deploy to AWS GovCloud -- without this adjustment, serverless template fails when trying to deploy apigateway to AWS GovCloud
Closes #XXXXX
Relates to: https://github.com/serverless/serverless/issues/4102
When trying to deploy to apigateway in AWS GovCloud, the wrong partition is put into the resource arn (aws instead of aws-gov-us).  Here is an example error:
```
Expected ARN arn:aws-us-gov:apigateway:us-gov-east-1::/... for Stage <stage> on RestApi <api id>, not arn:aws:apigateway:us-gov-east-1::/...
```
Added a conditional to change the resourceArn variable to have aws-us-gov instead of aws when the region has 'gov' in it.
Make an apigateway …
> Fixes aws partition name in apigateway resourceArn to support GovCloud

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
AWS reports `403` (bad credentials) errors as retryable.
Still we definitely do not want to retry requests if credentials are outdated or invalid.
> Do not retry on AWS 403 errors

- lib/plugins/package/lib/packageService.js
- lib/plugins/package/lib/packageService.test.js
- tests/integration-package/fixtures/individually-function/handler.js
- tests/integration-package/fixtures/individually-function/handler2.js
- tests/integration-package/fixtures/individually-function/serverless.yml
- tests/integration-package/lambda-files.tests.js
Closes #6120 
I'm not sure how did I miss that with my previous PR (https://github.com/serverless/serverless/pull/6537) but without this fix `sls deploy` (with `package.individually: true` on function level) still returns an error. I probably tested it with the wrong config.
The issue is that during function zipping whole `package` object is overwritten instead of just setting `artifact` prop.
I gave two examples in the comment: https://github.com/serverless/serverless/issues/6120#issuecomment-520944321. Both works now. …
> Fix overriding package settings after packaging function

- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
Update to the Consultants section of the README. SC5 merged with Nordcloud, so time to make the replacement.
Only Markdown changes.
Be helpful to verify my spelling..
- [n/a ] Write tests and confirm existing functionality is not broken.  
- [ x] Write documentation
- [n'a ] Ensure there are no lint errors.  
- [ n/a] Ensure introduced changes match Prettier formatting.  
- [ n/a] Make sure code coverage hasn't …
> Update Readme to replace SC5.io with nordcloud.com

- lib/plugins/aws/lib/cloudformationSchema.js
- lib/utils/fs/parse.test.js
Fixed `!GetAtt` parsing to allow for nested properties on the value -- e.g. `Resource.Outputs.MyValue`
This was triggered by [this tweet](https://twitter.com/aaron_osborne_/status/1167238870800510977) asking why he couldn't use an SAR Output in his serverless.yml. After reviewing, I noticed that `!GetAtt RequirementsLayerApp.Outputs.LayerVersion` was getting converted to:
```
Fn::GetAtt:
- RequirementsLayerApp
- Outputs
```
Notice that `LayerVersion` has been stripped off of Outputs.
The original parsing of `!GetAtt` splits on a period and allows for two return values, as most usage of GetAtt don't have nested attributes. I updated the logic to split on all the periods, then rejoin all elements after the first period.
Use [Aaron's sample …
> Allow for tail on GetAtt parsing

- lib/utils/getServerlessConfigFile.js
- lib/utils/getServerlessConfigFile.test.js
Currently an empty config files resolves to `undefined`, which produces obscure errors as:
```
TypeError: Cannot read property 'frameworkVersion' of undefined
```
I take if config exists, it always should resolve to object, eventually empty
> Resolve empty config object for an empty config file

- lib/classes/PluginManager.js
I changed the wording of the upgrade message from Enterprise to Dashboard, and added `the`
By deleting and adding text
You can pull this branch with an outdated version of the enterprise-plugin and see this message
> Remove enterprise from upgrade notes

- lib/plugins/aws/configCredentials/awsConfigCredentials.test.js
- lib/plugins/aws/invoke/index.test.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/utils/credentials.test.js
- lib/plugins/interactiveCli/initializeService.js
- lib/plugins/interactiveCli/initializeService.test.js
- lib/plugins/interactiveCli/setupAws.js
- lib/plugins/interactiveCli/setupAws.test.js
- lib/plugins/interactiveCli/test/configure-inquirer-stub.js
- lib/plugins/interactiveCli/test/fixtures/some-aws-service/serverless.yml
- lib/plugins/interactiveCli/test/fixtures/some-other-service/serverless.yml
- lib/plugins/interactiveCli/utils.js
- package.json
- tests/utils/run-serverless.js
We heavily missed tests for this important functionality.
To ensure tests do not depend too much on implementation internals (but more on an actual outcome with which user is faced). I've prepared an util that helps to create fully functional and isolated serverless instance mocks, which allow to test specific plugins and hooks (it's proposed in `tests/utils/run-serverless.js`)
I've also introduced a mock generator for `inquirer`, and having that configured tests for _intiailize project_ and _setup AWS credentials_ case.
--- 
Additionally cleanup problems were exposed in unrelated test files, fixed those.
> Tests for interactive CLI 

- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/package/compile/events/cloudFront/index.test.js
- package.json
What did you implement:
Fixes a bug where a function with 0 events caused the removal to fail.
Add a check if the function has events defined in the CloudFront removal logger. Also added a regression test.
Deploy and remove the following service (the removal fails without this fix):
```yaml
provider:
name: aws
custom:
idx: 0
functions:
hello:
handler: handler.greeter
```
_Note: All reported issues can be automatically fixed by …
> Support functions without events in CloudFront remove logging

- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
Currently any plugin initialization errors are reported as _user_ errors (unless `SLS_DEBUG=*` flag is on). That makes reasoning about eventual programming errors  that happen at that stage difficult (e.g. good case is this crash: https://travis-ci.org/serverless/serverless/jobs/581213485)
I've refactored error reporting, taking into account following use cases which lead to current state of errors handling
- [Do not crash on unknown modules when running `sls --help`](https://github.com/serverless/serverless/issues/3956)
- [Do not crash on unknown modules when running `sls plugin` commands](https://github.com/serverless/serverless/issues/3956)
- [Distinguish plugin not found from plugin initialization errors](https://github.com/serverless/serverless/pull/4322)
New solution:
- Do not crash …
> Improve plugin loading error reporting

- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Fixes a bug caused by using the plugin constructor to log a removal reminder for `cloudFront` events. This was mainly an issue where events were pulled-in via variable definitions (e.g. [smth. like this](https://github.com/serverless/enterprise-plugin/blob/fe071921b90b3a0b34ebe36a0b86223d841115c5/integration-testing/service/serverless.yml#L80))
Moved the code from the constructor to the hooks section. This way we can be sure that all the variables are populated and the check for function events will be successful. …
> Use hooks to log Lambda@Edge removal reminder

- lib/plugins/create/templates/aws-alexa-typescript/serverless.yml
- lib/plugins/create/templates/aws-clojure-gradle/serverless.yml
- lib/plugins/create/templates/aws-clojurescript-gradle/serverless.yml
- lib/plugins/create/templates/aws-csharp/serverless.yml
- lib/plugins/create/templates/aws-fsharp/serverless.yml
- lib/plugins/create/templates/aws-go-dep/serverless.yml
- lib/plugins/create/templates/aws-go-mod/serverless.yml
- lib/plugins/create/templates/aws-go/serverless.yml
- lib/plugins/create/templates/aws-groovy-gradle/serverless.yml
- lib/plugins/create/templates/aws-java-gradle/serverless.yml
- lib/plugins/create/templates/aws-java-maven/serverless.yml
- lib/plugins/create/templates/aws-kotlin-jvm-gradle/serverless.yml
- lib/plugins/create/templates/aws-kotlin-jvm-maven/serverless.yml
- lib/plugins/create/templates/aws-kotlin-nodejs-gradle/serverless.yml
- lib/plugins/create/templates/aws-nodejs-ecma-script/serverless.yml
- lib/plugins/create/templates/aws-nodejs-typescript/serverless.yml
- lib/plugins/create/templates/aws-nodejs/serverless.yml
- lib/plugins/create/templates/aws-provided/serverless.yml
- lib/plugins/create/templates/aws-python/serverless.yml
- lib/plugins/create/templates/aws-python3/serverless.yml
- lib/plugins/create/templates/aws-ruby/serverless.yml
- lib/plugins/create/templates/aws-scala-sbt/serverless.yml
* replace `tenant` with `org` in docs & tmplates
* added comment about purpose of app & org since we get so many bug reports from people randomly(afaict) uncommenting them without knowing why.
sed
read the docs or use a template via `sls create` from this sls branch
> replace use of tenant with org in docs & templates

- lib/plugins/aws/package/compile/events/websockets/lib/stage.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Closes #6657 
Set `RetentionInDays` in `LogGroup` resource, in the same manner in #6548
https://github.com/serverless/serverless/blob/f187ba711330c518e0f47ef4a7bdf791739dd84a/lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js#L114-L117
1. `npm install -g exoego/serverless#log-retention-for-websocket`
2. `sls deploy`
```yaml
service: logs
provider:
name: aws
logRetentionInDays: "3"
logs:
websocket: true
functions:
helloWebSocket:
events:
- websocket: "$connect"
```
**Validate …
> Respect logRetentionInDays in log group for websocket

- docs/providers/aws/events/sns.md
Provides a solution to referencing a topic ARN when it doesn't exist in AWS, but is in the serverless.yml file.
> [Docs] Added clarification on specifying SNS ARN

- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Also, remove leading `.*` in the regular expression. It will still match
if there are any characters preceding the matching text.
Fixes: https://github.com/serverless/serverless/issues/6688
Fixed a small error in a regular expression. Added relevant test.
Closes #6688
Modify the regular expression as appropriate, and add a test that fails on current master branch but passes with this change.
Code change is very small. Run test provided in this PR on master, then compare to result when running with the change here. …
> Fix regular expression escaping in aws plugin.

- package.json
A tiny thing that we probably should've done long time ago. Gives us that quick shortcut to the docs
```
npm home serverless
```
> Update homepage in package.json to point to the docs

- docs/providers/aliyun/events/README.md
Currently the menuText for aliyun events is [Alibaba Cloud Functions Events]
Above breaks our sidebar styling, so similar to other providers I made it just [Events]
**_Is this ready for review?:_** YES 
> Truncated aliyun events menuText

- docs/providers/google/guide/credentials.md
A simple documentation fix to make Google roles more legible. Previously, it was hard to tell where a role ended at where it began.
> Add commas when specifying Google roles for legibility

- docs/dashboard/access-roles.md
Update docs to remove incorrect instruction.
Explanation: after setting up a new serverless project with an AWS Access Role through the serverless dashboard, I attempted to run `serverless info`, and it failed for the following reason:
`Stack with id my-app-dev does not exist`
The docs instruct you to run `sls info` before `sls deploy,` to verify your access roles are working. But, you cannot run `sls info` without running `sls deploy` first, and having a stack generated for you.
I didn't feel this was worth a whole Github issue, so I just went ahead and offered a PR. If there is a better way to verify access roles are working, I think that should be added here, rather than just deleting the current failing option.
Removed text
**_Is it a breaking …
> Remove incorrect AWS Access Role test instruction

- docs/providers/aws/cli-reference/invoke.md
- lib/plugins/aws/invoke/index.js
- lib/plugins/aws/invoke/index.test.js
- lib/plugins/invoke/invoke.js
Closes #6289 
This adds a `--qualifier (-q)` option to the invoke CLI that enables calling specific version numbers or aliases.
Try invoking any function that has more than one version and confirm that the versioned (or aliased) is being called instead of $LATEST, in case the option is passed.
> Feat: add qualifier option to invoke command

- package.json
Tested that this patch fixes #6667
It appears that fix is to rely on 4.2.1 globally, I've also described it at https://github.com/isaacs/node-graceful-fs/issues/174
> Lock graceful-fs at 4.2.1

- lib/plugins/plugin/install/install.js
- lib/plugins/plugin/install/install.test.js
- lib/plugins/plugin/lib/utils.js
- lib/plugins/plugin/lib/utils.test.js
- lib/plugins/plugin/uninstall/uninstall.js
- lib/plugins/plugin/uninstall/uninstall.test.js
Closes #6710
There are enterprise use cases where we need to install plugins and add them to the serverless.yml using the `plugin install`. For example, we have a CICD pipeline that executes `serverless deploy`. Individual developers do not have that access from their local machines. When the pipeline deploys, we want to `plugin install` certain plugins automatically that are only implementation details of the pipeline. For example, we do this for `serverless-aws-alias`. But we have a monitoring plugin that gathers deployment metadata so we can track usage and compliance. This plugin does not exist in the serverless registry as it is published to our internal npm registry. This PR relaxes the restriction on only installing things in the serverless registry.
`npm install` is not an …
> Allow plugins not in registry to be installed

- docs/providers/kubeless/guide/deploying.md
Documentation update for `serverless-kubeless` provider, describing `url+zip` function deployment option.
> documented url+zip deploy strategy for serverless-kubeless

- lib/plugins/interactiveCli/setupAws.js
Currently we unconditionally output *nix path. This update ensures Windows users get their variant
> Improve message for Windows users in AWS credentials setup

- lib/plugins/aws/customResources/index.js
Fixes #6557 
As I investigated, the problem is in `npm install --prefix ${dirPath}` command.
The `--prefix` option is not documented on [npm](https://docs.npmjs.com/cli/install), so it's not clear exactly what it's intended to do (maybe it was supported in some older versions)
I found a few stackoverflow answers that were suggesting it, so I guess hint was taken from there.
Still when testing locally, I found it behaves differently on Linux than on Windows (where indeed it hangs and does processing against current working directory)
Fixed the issue, by switching to (imo) more natural approach where bare `npm install` is run in context of specified directory.
Tested, and now custom resources setup works now same on Windows as it was on macOs or Linux.
> Fix custom resources install

- docs/providers/aws/events/streams.md
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
Closes: #6725
AWS [recently announced support for a `Batch Window` property on Kinesis & DynamoDB streams](https://aws.amazon.com/about-aws/whats-new/2019/09/aws-lambda-now-supports-custom-batch-window-for-kinesis-and-dynamodb-event-sources/). This allows users to specify that property in their `serverless.yml`.
Usage looks as follows:
```yml
functions:
preprocess:
handler: handler.preprocess
events:
- stream:
arn: arn:aws:kinesis:region:XXXXXX:stream/foo
batchWindow: 10
```
Added it to the `compile` stage for Kinesis & DynamoDB stream events.
Note that it's not a required property, and I don't know a good default value for it. Thus, I didn't set a default value at all. We only add this property if the user includes it on the `stream` event. Because of that, it's applied later in the …
> Add support for MaximumBatchingWindowInSeconds property on stream events

- lib/plugins/aws/customResources/resources/apiGatewayCloudWatchRole/handler.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/handler.js
- lib/plugins/aws/customResources/resources/eventBridge/handler.js
- lib/plugins/aws/customResources/resources/s3/handler.js
- lib/plugins/aws/lib/naming.test.js
nane -> name
resouce -> resource
> Fixing typos in variable names

- .github/workflows/update-sfe-next.yml
- scripts/update-sfe-dep.js
This uses github actions to automatically update the `sfe-next` branch. On pushes to master, it will update the package json, commit, & force push to the `sfe-next` branch.
example commit (from a version of this branch that had `branch: sfe-next-update-test` instead of `branch: master`) created by this: https://github.com/serverless/serverless/commit/e17690e05044e4ba8ab823451aa1b217bad11c53
and here's the build that created it: https://github.com/serverless/serverless/commit/9ea3244ccbc39f746232931918d7661328d884ca/checks
> Automate keeping the sfe-next branch upto date

- docs/providers/aws/guide/variables.md
Added brief showcase how to use AWS SDK in serverless helpers.
I've stumbled across issue that I couldn't get account id at some times - depending on where I needed it -  that I think it's worth mentioning method that does not interfere with current serverless flow in documentation.
Mentioned also in #5001 
Snippet is available in docs, this is only docs update
<details>
</details>
**_Is this ready for …
> Showcase how to use AWS SDK in sls helpers

- lib/plugins/aws/invokeLocal/java/src/main/java/com/serverless/InvokeBridge.java
- lib/plugins/aws/invokeLocal/java/src/test/java/com/serverless/AbstractRequestHandler.java
- lib/plugins/aws/invokeLocal/java/src/test/java/com/serverless/ConcreteRequestHandler.java
- lib/plugins/aws/invokeLocal/java/src/test/java/com/serverless/InvokeBridgeInheritanceTest.java
Allowing InvokeBridge to find handleRequest method from super classes
Closes #4867
Provided the unit test
<details>
</details>
> Issue 4867 - Allowing InvokeBridge to find handleRequest method from super classes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/questions.md
Add a new **Questions** issue template that is intended to navigate users to forums.
Inspired from scala-js repository https://github.com/scala-js/scala-js/issues/new/choose
IIUC, the issue tracker for serverless is dedicated for **Bug report** and **Feature request**.
But not a small number of people open a question.
I think it is because they think the existing issue template are not for **Question**, then they find a `open a regular issue`. One such example is https://github.com/serverless/serverless/issues/6783#issuecomment-538282539
Also added fancy icons.
N/A
<details>
- `npm run lint:fix` --> Automatically fix lint problems …
> Add Questions issue template that navigate users to forums

- docs/providers/aws/cli-reference/deploy.md
- docs/providers/azure/cli-reference/deploy-list.md
- docs/providers/azure/cli-reference/deploy.md
- docs/providers/azure/cli-reference/invoke.md
- docs/providers/cloudflare/cli-reference/deploy.md
- docs/providers/fn/cli-reference/deploy.md
- docs/providers/google/cli-reference/deploy.md
- docs/providers/kubeless/cli-reference/deploy.md
- docs/providers/openwhisk/cli-reference/deploy.md
- docs/providers/spotinst/cli-reference/deploy.md
- lib/classes/PluginManager.js
Update the documentation for the `--config or -c` argument. This option currently does not support path-based `serverless.yml` files like `my_dir/another_dir/serverless.yml`. Instead, it currently only supports non-standard naming conventions of the `serverless.yml` file (`serverless.yml|.yaml|.js|.json`).
Closes #XXXXX
With a directory structure like: `my_dir/another_dir/serverless.yml`, if you run:
```
sls deploy --config my_dir/another_dir/serverless.yml
```
It will fail with the error message:
```
This command can only be run in a Serverless service directory
```
<details>
- `npm run lint:fix` --> Automatically fix lint …
> Update SLS Deploy Documentation

- lib/classes/Variables.js
- lib/classes/Variables.test.js
This is just a quick follow-up to https://github.com/serverless/serverless/pull/6554
Now that empty arrays are not warned, the variable override e.g. `foo: ${opt:xyz, self:custom.emptyArray}` doesn't default foo to an array, which can be surprising/annoying for plugin developers and users.
I added a test, and this is a simple example:
```
service: empty-array-test
provider:
name: aws
functions:
hello:
custom:
emptyArray: []
foo: ${opt:foo, self:custom.emptyArray}
```
<details>
- `npm run prettier-check-updated` --> …
> Allow empty arrays in overrides

- lib/plugins/aws/package/index.js
- lib/plugins/aws/package/index.test.js
This allows credential validation checks to be applied when running the `package` hook only if the initial command is to create an artifact for deployment, that is explicitly `sls package`. Since the package hook is invoked by other commands like `deploy`, the validation step is deferred to that command's hook.
Closes #6576
Setup an MFA requirement with the AWS CLI and attempt to deploy: `sls deploy`. It should await input on the MFA prompt.
<details>
- `npm run …
> Pause for mfa input

- lib/classes/CLI.js
- lib/classes/PluginManager.test.js
- lib/plugins/aws/deployFunction/index.test.js
- lib/plugins/aws/invoke/index.js
- lib/plugins/aws/invoke/index.test.js
- lib/plugins/aws/invokeLocal/java/src/main/java/com/serverless/InvokeBridge.java
- lib/plugins/aws/package/compile/functions/index.test.js
- lib/plugins/aws/rollbackFunction/index.test.js
- lib/plugins/package/lib/zipService.test.js
Switch all uses of `new Buffer()` to `Buffer.from()`, as the former is deprecated. This change was done by running:
```sh
git ls-files -z | xargs -0 sed -i -e 's/new Buffer/Buffer.from/g'
```
Does not close any issues that are currently open.
Automated tests
<details>
</details>
> Chore - stop using deprecated 'new Buffer()' method.

- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/deploy/lib/validateTemplate.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/updateStack.js
- lib/plugins/aws/rollback/index.js
The name of the CloudFormation template file in S3 is `compiled-cloudformation-template.json`. Instead of hardcoding that string everywhere, this PR hardcodes it once in `naming.js`. 
Does not close any issues that are currently open.
Automated tests.
<details>
</details>
> AWS - adding naming function for S3 compiled template file name.

- lib/plugins/aws/package/index.js
- lib/plugins/aws/package/index.test.js
Reverts serverless/serverless#6780 and reopens: #6576
After merging #6780 our integration tests started to fail: https://travis-ci.org/serverless/serverless/jobs/597530715#L486
As I've investigated problem is that generated log grup has name `/aws/websocket/{serviceName}-undefined` while before that merge it was `/aws/websocket/{serviceName}-{stage}`.
What was overlooked, is that `validate()` method aside of resolving AWS credentials, also normalizes `options.stage` and `options.region`: https://github.com/serverless/serverless/blob/a4342239ea46e6c4b3951a23464a8f93e8daab16/lib/plugins/aws/lib/validate.js#L16-L17
And now it's not done before some logic which depends on it jumps in.
@drexler To come up with proper solution for https://github.com/serverless/serverless/issues/6576 can you …
> Revert "Pause for mfa input"

- docs/providers/aws/events/cloudwatch-log.md
- lib/plugins/aws/package/compile/events/cloudWatchLog/index.js
- lib/plugins/aws/package/compile/events/cloudWatchLog/index.test.js
Closes #6266 and possibly #5833
This PR completes the work associated to https://github.com/serverless/serverless/pull/5531. But in some specific cases it did not work when several events were provided for the samel AWS Lambda function.
See the test cases to see 2 cases were the CloudWatch Log Group ARN prefix with `*` was not correctly created.
Withou this fix the following error could be encountered (because the expression was not "complete enough" to target all the CloudWatch Log Groups specified).
```
Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function. (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: 0b096e01-87d2-11e9-b52a-59a1410a5e04
```
I tested the fix and successfully deployed …
> Fix perms with several CloudWatch log subscriptions

- docs/providers/azure/guide/quick-start.md
Clicking the original link in the [Serverless web site](https://serverless.com/framework/docs/providers/azure/guide/quick-start/) leads to a broken link.
Click on the link.
<details>
</details>
> Fixing an Azure docs broken link

- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Support for NotAction and NotResource in IAM role statements.
Closes #6841
```yaml
service: simple-service
provider:
name: aws
- Effect: 'Allow'
Action: 'sns:Publish'
NotResource: 'arn:aws:sns:*:*:*'
functions:
hello:
```
<details>
</details>
> Support for NotAction and NotResource in IAM role statements

- docs/dashboard/sdk/README.md
- docs/dashboard/sdk/nodejs.md
- docs/dashboard/sdk/python.md
There was frontmatter missing in the new sdk docs (docs/dashboard/sdk) and this broke serverless.com website build. 
I've fixed this by adding frontmatter to the docs mentioned above.
> added frontmatter to sdk docs

- docs/providers/google/guide/functions.md
- Added a section in the Google Provider documentation to explain how to define environment variables. To feature was added with [PR 117](https://github.com/serverless/serverless-google-cloudfunctions/pull/117), but was never documented. Was also added some clarifications on the expected format of those environment variables, especially when the type could be confused, as illustrated in [issue 128](https://github.com/serverless/serverless-google-cloudfunctions/issues/128).
- Corrected mistaken documentation about labels. Example provided was not working and could confuse new users, as illustrated in [issue 185](https://github.com/serverless/serverless-google-cloudfunctions/issues/185). Fixed example and added a note about labels requirements and pointed to official Google Cloud …
> Update Google provider documentation for functions

- tests/integration-all/sns/service/core.js
- tests/integration-all/sns/service/serverless.yml
- tests/integration-all/sns/tests.js
- tests/utils/sns/index.js
Integration tests for SNS:
* Minimal setup with topic created by name
* Complex setup with multiple lambdas triggering on the same topic (created with name and display name) filtered on message metadata
* Existing setup where lambda is triggered by existing topic specified by ARN. 
Closes #6737 
I do not think that the integration tests run as part of the CI for PRs.
`npm run integration-test-run-all` will run all integration tests against a the locally configured AWS account (so make sure you set-up a test one!).
I developed against a modified version of this command which limited the suite to `mocha-isolated --pass-through-aws-creds --skip-fs-cleanup-check tests/integration-all/sns/tests.js"` as the whole suite takes circa 30 minutes to run.
**_Is it …
> SNS integration tests

- tests/integration-all/sqs/service/core.js
- tests/integration-all/sqs/service/serverless.yml
- tests/integration-all/sqs/tests.js
- tests/utils/sqs/index.js
Integration tests for lambda invoked by SQS message on an existing topic (Serverless does not support queue creation).
This required writing an SQS test utility module, following the pattern of the existing SNS one.
Closes #6738 
I do not think that the integration tests run as part of the CI for PRs.
`npm run integration-test-run-all` will run all integration tests against a the locally configured AWS account (so make sure you set-up a test one!).
You can use `mocha-isolated --pass-through-aws-creds --skip-fs-cleanup-check tests/integration-all/sqs/tests.js"` to specifically run the SQS tests.
> SQS integration tests

- tests/integration-all/stream/service/core.js
- tests/integration-all/stream/service/serverless.yml
- tests/integration-all/stream/tests.js
- tests/utils/dynamodb/index.js
- tests/utils/kinesis/index.js
- tests/utils/misc/index.js
Integration tests for stream event sources:
* Kinesis with `TRIM_HORIZON` to ensure messages prior to trigger attachment are processed
* DynamoDB
This required writing a Kinesis test utility module, following the pattern of the existing SNS one. The setup and tear-down of the DynamoDB table and stream was done using the `resources` key in the serverless yaml file to simplify the process.
Closes #6739 
I had to modify the `tests/utils/misc/index.js > getFunctionLogs` to catch the case where the logs are waited for prior to the first invocation. This seems very common with Kinesis which can take around 30 seconds to first invoke. **Is there a better way of doing this?**.
I do not think that the integration tests run as part of the CI for PRs.
`npm run integration-test-run-all` will run all …
> Streams integration tests

- tests/integration-all/schedule/service/core.js
- tests/integration-all/schedule/service/serverless.yml
- tests/integration-all/schedule/tests.js
- tests/utils/misc/index.js
Integration tests for schedule event sources:
* Minimal setup using `rate` notaiton
* Extended setup using `cron` notation and input transformations
Closes #6736 
I had to modify `tests/utils/misc/index.js > getFunctionLogs` to catch the case where the logs are waited for prior to the first invocation. Even though the lambdas scheduled is set to the minium (every minute), it can still take up to 60 seconds for the first invoke. During this time the previous `getFunctionLogs` would throw and cause the test to end. **Is there a better way of doing this?**.
I do not think that the integration tests run as part of the CI for PRs.
`npm run integration-test-run-all` will run all integration tests against a the locally configured AWS account (so make sure you set-up a test one!).
You can use …
> Schedule integration tests

- tests/integration-all/iot/service/core.js
- tests/integration-all/iot/service/serverless.yml
- tests/integration-all/iot/tests.js
- tests/integration-all/s3/tests.js
Integration tests for AWS IoT rule invoked lambdas.
Closes #6735 
~The test `AWS - IoT Integration Test > Basic Setup` should run as part of the CI for this PR.~
I do not think that the integration tests _did_ run as part of the CI.
`npm run integration-test-run-all` will run all integration tests against a the locally configured AWS account (so make sure you set-up a test one!). I developed against a modified version of this command which limited the suite to `mocha-isolated --pass-through-aws-creds --skip-fs-cleanup-check tests/integration-all/iot/tests.js"` as the whole suite takes circa 30 minutes to run.
*The owner of the AWS account doing the integration test may need to visit https://console.aws.amazon.com/iot/home?region=us-east-1#/settings to provision the IoT Core endpoint.* …
> IoT integration tests

- docs/providers/aws/events/streams.md
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
This PR allows usage of `Ref` in stream arn properties. When using the `Reg` it has to be included in CloudFormation parameters.
Usage & use cases:
```yaml
resources:
Parameters:
DynamoDbStreamArn1:
Description: 'ARN stored to SSM parameter store'
Type: 'AWS::SSM::Parameter::Value<String>'
Default: '/my/dynamodb/stream-arn'
DynamoDbStreamArn2:
Description: 'ARN from manually / other that cloudformation created Dynamo/Kinesis stream'
Type: 'String'
functions:
myStreamFunction:
events:
- stream:
type: dynamodb
arn: !Ref DynamoDbStreamArn1
- stream:
type: dynamodb
arn: !Ref DynamoDbStreamArn2
```
<details>
- `npm run lint:fix` --> …
> Allow to use Ref in stream arn property

- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/index.test.js
Fixes #6595
Some projects rely on setup where access rights is handled externally (not in a scope of Serveless service), and those cannot be reliably now run with custom resources involved, as any IAM roles creation crashes the deployment.
This improvements, ensures that `cfnRole` setting is honored as a role under which custom resources lambda invocation should be made.
When it's provided no custom IAM role is created when custom resources are setup.
> Honor cfnRole in custom resources

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/lib/core-cloudformation-template.json
- lib/plugins/aws/package/lib/generateCoreTemplate.test.js
This PR adds a policy to the deployment S3 bucket to reject all non-HTTPS requests.
I believe no documentation updates are necessary, but if wrong am happy to be pointed to the right places that require updates. 
Closes #5621
```yaml
service: simple-service
provider:
name: aws
functions:
hello:
```
Once deployed:
* CloudFormation will include a `ServerlessDeploymentBucketPolicy` resource
* S3 bucket with logical ID `ServerlessDeploymentBucket` will have a policy attached that restricts non-HTTPS requests
<details>
- …
> AWS - deployment bucket policy for HTTPS only

- docs/providers/kubeless/guide/intro.md
Fix minor typo in `docs/providers/kubeless/guide/intro.md`
Nothing to verify, no changes to functionality
- [* ] Write documentation
> Fix minor typo

- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Fixes a problem where the `ServerlessError` class was not used correctly. Also added the unit tests which checks if the region is validated.
Run `serverless package` with the following `serverless.yml`. You shouldn't see an error due to a `ServerlessError` misuse (but you should see the error that the region is incorrect).
```yaml
provider:
name: aws
region: eu-central-1
stage: dev
custom:
idx: 0
functions:
hello:
handler: functions/handler.handler
events:
- cloudFront:
eventType: viewer-response
origin: https://serverless.com/framework/docs
```
<details> …
> Fix region error handling in Lambda@Edge implementation

- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Use both the domain name and the origin path to determine if two origins are equal
Closes #6864
Unit test has been added.
The following serverless.yaml should create two origins, previously only one was created
```
service:
name: cloudfront-test
provider:
name: aws
functions:
first:
handler: first.handler
events:
- cloudFront:
eventType: viewer-request
origin: s3://bucketname.s3.amazonaws.com/files
second:
handler: second.handler
events:
- cloudFront:
eventType: viewer-request
pathPattern: /second
origin: s3://bucketname.s3.amazonaws.com/files
```
> Find origin by domain name and path

- docs/providers/kubeless/guide/functions.md
minor typo fix in `./docs/providers/guide/functions.md`
nothing to verify, no logic is affected
- [* ] Write documentation
> fix minor typo in kubeless docs

- CHANGELOG.md
- lib/plugins/aws/package/lib/generateCoreTemplate.js
- lib/plugins/aws/package/lib/generateCoreTemplate.test.js
- package.json
Fixes #6908
Regression introduced with #6823 where we've introduced a bucket policy for our default S3 bucket. Still it should not be introduced where custom deployment bucket is provided.
> Fix deployment bucket policy handling with custom bucket

- docs/providers/aws/guide/variables.md
- lib/classes/Variables.js
- lib/classes/Variables.test.js
Variables can now cast values to booleans. For example, if a parameter expects a boolean, but a string is passed, it will convert a `"true"` to `true`, a `"false"` to `false`, and `"anything"` to `true`.
Closes #6782
Reference an SSM value and cast it in the API Gateway logging and X-ray tracing provider sections.
```yaml
tracing:
apiGateway: ${strToBool(${ssm:API_GW_DEBUG_ENABLED})}
logs:
restApi:
accessLogging:     ${strToBool(${ssm:API_GW_DEBUG_ENABLED})}
executionLogging:  ${strToBool(${ssm:API_GW_DEBUG_ENABLED})}
fullExecutionData: ${strToBool(${ssm:API_GW_DEBUG_ENABLED})}
```
Set `API_GW_DEBUG_ENABLED` to `true` in SSM, deploy and see the API Gateway settings turn on. Update `API_GW_DEBUG_ENABLED` to `false` in SSM, deploy and see the API Gateway settings turn off.
<details> …
> Allow casting to boolean in Serverless variables

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/alb/lib/listenerRules.js
- lib/plugins/aws/package/compile/events/alb/lib/listenerRules.test.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.test.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.test.js
Closes #6382 
This creates unique target groups for each event of each function by adding the priority to the target group name/hash.
Since serverless.yml requires a pre-existing ALB to add an ALB route, there's not a single serverless.yml that can be posted to test this. 
Below is an example of a single function with routes on different ALBs:
```yml
functions:
ingest:
handler: src/ingest/ingest-handler.ingest
events:
- alb:
listenerArn: arn:aws:elasticloadbalancing:us-east-1:1234:listener/app/alb-one/88b747/8e6f9
priority: 1
conditions:
path: /foo/bar/*
- alb:
listenerArn: arn:aws:elasticloadbalancing:us-east-1:1234:listener/app/alb-two/92eb3a/385da
priority: 2
conditions:
path: /foo/bar/*
```
I also tried deploying these functions with master and then updating with this branch to ensure …
> Create distinct target groups for different ALBs

- lib/utils/tracking.js
Fixes  #6917
When multiple invocation of `sls` command occur, there's a risk of race conditions.
One of the error scenarios was not handled gently. This PR fixes that
> Fix race conditions handling in stats requests

- docs/providers/aws/events/cloudfront.md
- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Updated [AWS Limits on Lambda@Edge](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge)
Closes #6913 
```yml
originResponseFunction:
handler: originResponseFunction/index.handler
timeout: 30
memorySize: 896
role: LambdaAtEdgeRole
events:
- cloudFront:
eventType: origin-response
origin: nameOfOrigin
```
</details>
> Update AWS Limits on Lambda@Edge

- lib/plugins/aws/package/compile/events/sns/index.js
- lib/plugins/aws/package/compile/events/sns/index.test.js
Fixes the split of of arn for sns topic, when using pseudo params.
Closes #6760 
Tests updated.
<details>
</details>
> Fixes bug with sns-cross-region definition using psuedo params

- CHANGELOG.md
- package.json
When preparing, I've discovered that with v1.56.1 we also sneaked `aws-nodejs-typscript` improvements (wasn't aware of that then). Updated the changelog to reflect that
> Release v1.57.0

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/alb/lib/permissions.js
- lib/plugins/aws/package/compile/events/alb/lib/permissions.test.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.test.js
A fix for the missing Application Load Balancer trigger in the Lambda console.
Closes #6818 .
The problem is caused by the incorrect Lambda [resource-based policy](https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html) created by Serverless.
Take this example of policy created by Serverless:
```json
{
"Version": "2012-10-17",
"Id": "default",
"Statement": [
{
"Sid": "test-dev-Hello1LambdaPermissionAlb-2WKZLN09SNOZ",
"Effect": "Allow",
"Principal": {
"Service": "elasticloadbalancing.amazonaws.com"
},
"Action": "lambda:InvokeFunction",
"Resource": "arn:aws:lambda:us-east-1:11111111111:function:test-dev-hello1"
}
]
}
```
An then this example of policy created by the AWS console when you manually add the ALB trigger:
```json
{
"Version": "2012-10-17",
"Id": …
```
> Fix missing ALB trigger in console

- lib/plugins/aws/package/lib/core-cloudformation-template.json
- lib/plugins/aws/package/lib/generateCoreTemplate.js
- lib/plugins/aws/package/lib/generateCoreTemplate.test.js
- lib/plugins/aws/provider/awsProvider.js
Fixes https://github.com/serverless/serverless/issues/6933
Additionally:
- Reconfigure `lib/plugins/aws/package/lib/generateCoreTemplate.test.js` so they're based on `runServerless` util
- Fix handling of `--no-aws-s3-accelerate` option (exposed after running test through `runServerless` util)
> Fix handling of China region in S3 bucket policy

- lib/plugins/aws/package/lib/core-cloudformation-template.json
- lib/plugins/aws/package/lib/generateCoreTemplate.test.js
Regression just introduced with https://github.com/serverless/serverless/pull/6934
It appears AWS doesn't accept pseudoparams in strings sneaked into Fn::Join
> Fix policy definition

- docs/providers/azure/cli-reference/create.md
- docs/providers/azure/guide/workflow.md
- lib/plugins/create/create.js
- lib/plugins/create/create.test.js
Add `azure-python` template to valid templates of the CLI.
Closes #6944 
`sls create -t azure-python`
<details>
</details>
> Add azure python to cli

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Updated the section for adding tags to API gateway resources to use whatever partition the user is deploying from, rather than only checking whether commercial or govcloud
Closes #6925 
```yaml
provider:
name: aws
stage: ${opt:stage, 'dev'}
region: cn-northwest-1
memorySize: 128
timeout: 15
tags:
foo: 'bar'
functions:
hello-world:
handler: functions/hello-world.handler
endpointType: regional
events:
- http:
path: /
method: GET
cors: true
```
<details>
- …
> Update API Gateway tagging to use partition for deployed region

- docs/providers/aws/events/alb.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/alb/lib/listenerRules.js
- lib/plugins/aws/package/compile/events/alb/lib/permissions.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.test.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.test.js
Closes #6504
Add multi-value header support.
Cf. [AWS documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#multi-value-headers)
I added the `TargetGroupAttributes` property to the Target Group definition.
There are a few things to consider tho while reading the code.
Because of this use case:
```yaml
functions:
hello1:
events:
- alb:
listenerArn: { Ref: HTTPListener }
multiValueHeaders: true
priority: 1
conditions:
path: /hello1
- alb:
listenerArn: { Ref: HTTPListener }
multiValueHeaders: false
priority: 2
conditions:
path: /hello2
```
Normally a single Target Group would be created for the function and used for both events. But this is not possible anymore since multiValueHeaders is set on the Target Group. Hence …
> Add support for multi-value headers in ALB events

- lib/classes/PromiseTracker.js
- lib/classes/PromiseTracker.test.js
The language used to report promise status is challenging to understand and doesn't state when completion has occurred.  This PR attempts to improve this.  For reference, see [comments on #4984](https://github.com/serverless/serverless/issues/4984#issuecomment-545388840).
Improves on #4984
Progress:
```
############################################################################################
##########################################################################################
```
Completion:
```
############################################################################################
##########################################################################################
```
New tests added.
> Add promise completion report and improve promise reporting verbiage

- lib/classes/PromiseTracker.js
- lib/classes/PromiseTracker.test.js
@erikerikson sorry, I didn't look carefully enough. We actually need to revert that improvement, as it logs promises report unconditionally on every command, we definitely do not want that (I thought it's triggered only on SLS_DEBUG or some other special env var).
Can you reopen the PR with that, and clarify what use case it serves for you (?)
At least what it currently does, it's adding output on every command that involves variable resolution, which seems not that useful
```
Serverless Information ----------------------------------
############################################################################################
##########################################################################################
```
> Revert "Add promise completion report and improve promise reporting verbiage"

- lib/utils/config/index.js
When processing config crashes could be observed when:
- For some reason `os.homedir()` resolves to not existing directory (e.g. it seems to be the case in this report: https://stackoverflow.com/questions/58842120/aws-serverless-unknown-error-shows-up-when-trying-to-reach-my-lambda )
- Process has no write access to `~/.serverless` folder (observed in case of some global installations)
This patch ensures that such errors are handled gently
> Improve config error handling

- lib/classes/PromiseTracker.js
- lib/classes/PromiseTracker.test.js
The language used to report promise status is challenging to understand and doesn't state when completion has occurred. This PR attempts to improve this and is an improvement over previous solution #6960.  For motivation, see [user comment](https://github.com/serverless/serverless/issues/4984#issuecomment-545388840) on #4984 and [my discussion](https://github.com/serverless/serverless/pull/6960#issuecomment-554515331) on #6960 which was properly reverted under #6963.  To solve those concerns, this reduces the noise of this component by only printing a final report if progress was previously reported.
Examples of the new messages:
Progress:
```
############################################################################################ …
```
> Add variable completion report if variable progress was reported

- docs/providers/aws/guide/layers.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/create/templates/aws-python3/serverless.yml
Updated serverless.yml template for `aws-python3` to use python3.8.
https://aws.amazon.com/jp/blogs/compute/python-3-8-runtime-now-available-in-aws-lambda/
Closes #XXXXX
<details>
</details>
> Python3.8 support!

- docs/dashboard/output-variables.md
Minor doc changes to rename "output variables" to "outputs" in the Serverless Framework Pro dashboard. This alleviates some of the confusion around using the term "variable".
Changes can be previewed here:
https://5dd2c66b9280830008a2a588--serverless.netlify.com/framework/docs/dashboard/output-variables/
The URL `output-variables` will stay as-is instead of being renamed to `outputs` to avoid broken links and redirects.
> rename output variables to outputs

- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
Bugfix to support multiple schemas per function.
Closes #6162
- See the ticket for `serverless.yml` and template file.  
- run `serverless package`
- Confirm both mime-types are in `ApiGatewayMethodUsersCreatePost.Properties.RequestModels`
> #6162: Support multiple schemas, don't overwrite RequestModels for each

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
This allows setting `deploymentPrefix: ''` in `serverless.yml` to use an empty `deploymentPrefix` instead of the default "serverless" prefix. Without this change, `deploymentPrefix: ''`, `deploymentPrefix: 0`, `deploymentPrefix: off`, `deploymentPrefix: false`, etc. all are equivalent to `deploymentPrefix: serverless`.
Note that this will only clear out the `deploymentPrefix` if one is explicitly included in the config file, or if the deploymentPrefix is falsey (e.g. `false`). If the key is not included, it will still return "serverless".
This could be interpreted as a breaking change, although I can imagine that the number of folks impacted is very small.
* `provider.deploymentPrefix` can be set to the following too indicate an empty prefix:
* `false`
* `off`
* `0`
* `''`
* …
> Support empty deploymentPrefix

- lib/utils/autocomplete.js
- lib/utils/downloadTemplateFromRepo.js
Simplifying code and improve function parameters style.
> Code cleanup and refactoring

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
Option to set `contentHandling` property of API gateway [method integration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration.html#cfn-apigateway-method-integration-contenthandling) and [integration response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration-integrationresponse.html#cfn-apigateway-method-integrationresponse-contenthandling).
Closes #6949 
```
service: content-handling
provider:
name: aws
logs:
restApi:
level: INFO
region: eu-central-1
apiGateway:
binaryMediaTypes:
- 'image/jpeg'
functions:
hello:
events:
- http:
method: POST
path: hello
request:
contentHandling: CONVERT_TO_TEXT
template: …
```
> Add support for contentHandling - Fixes gh-6949

- lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js
Minor addition to #6150 to make authorizer type check case insensitive
same as #6150
> Make authorizer type check from #6150 case insensitive

- lib/plugins/aws/customResources/resources/apiGatewayCloudWatchRole/handler.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/handler.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/permissions.js
- lib/plugins/aws/customResources/resources/eventBridge/handler.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/permissions.js
- lib/plugins/aws/customResources/resources/s3/handler.js
- lib/plugins/aws/customResources/resources/s3/lib/permissions.js
- lib/plugins/aws/customResources/resources/utils.js
- lib/plugins/aws/customResources/resources/utils.test.js
Closes #6995 .  Fix GovCloud Region ARN and Environment parsing utilities in the AWS Plugin for Custom Resources.
Deploy a serverless function to `us-gov-west-1` or `us-gov-east-1`  that uses S3 Bucket events on an existing S3 bucket, for example:
```yml
service:
name: myService
provider:
name: aws
stage: dev
region: us-gov-west-1
functions:
users:
handler: users.handler
events:
- s3:
bucket: legacy-photos
event: s3:ObjectCreated:*
rules:
- prefix: uploads/
- suffix: .jpg
existing: true
```
<details>
- `npm run prettier-check-updated` --> …
> Govcloud custom resource fix

- lib/classes/PluginManager.test.js
- lib/plugins/aws/deploy/lib/existsDeploymentBucket.test.js
- lib/plugins/aws/package/lib/generateCoreTemplate.test.js
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/package/lib/packageService.test.js
Purely style updates:
- ESlint with v6.7.0 got a [bug fix](https://github.com/eslint/eslint/pull/12495) to `operator-assignment`rule, on which we rely on, and that exposed few lint issues on our side -> https://travis-ci.org/serverless/serverless/jobs/616586600. Fixed here
- Prettier with v1.19 introduced minor changes to formatting, which affected few files. Updated those files to reflect new formatting. It's to help users avoid unrelated changes in their PR's (some prettify whole project)
> Lint and style patches

- lib/plugins/aws/package/compile/events/websockets/lib/stage.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
It looks like AWS may have recently introduced a change where `$context.status` is invalid on API Gateway WebSocket APIs (or at least now they're enforcing invalid tokens).
> The following context variables are not supported: [$context.status] (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: a37f886a-d719-485d-9593-fe2b14182df7)
This change simply removes the offending token from the WebSocket log format so WebSocket APIs will deploy properly.
Create a WebSocket-based service.
```yaml
service: websocket-test
provider:
logs:
websocket: true
functions:
websocket:
handler: src/websocket
events:
- websocket: $default
```
<details>
- `npm run …
> fix: remove `$context.status` from websocket access log format

- docs/providers/azure/guide/credentials.md
- docs/providers/azure/guide/quick-start.md
Updated the documentation to make it more clear.
Closes #N/A
Run through the procedure.
<details>
</details>
> Clarifying Azure setup

- docs/providers/aws/events/streams.md
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
Exposed the new `ParallelizationFactor` prop for Kinesis Streams.
Closes #7019
This config should default the `ParallelizationFactor` to 1:
```yaml
functions:
preprocess:
handler: handler.preprocess
events:
- stream:
arn: arn:aws:kinesis:region:XXXXXX:stream/foo
```
This config should set the `ParallelizationFactor` to 10:
```yaml
functions:
preprocess:
handler: handler.preprocess
events:
- stream:
arn: arn:aws:kinesis:region:XXXXXX:stream/foo
parallelizationFactor: 10
```
> Expose ParallelizationFactor prop for Kinesis Streams

- docs/providers/aws/events/sqs.md
Update SQS event docs regarding AWS support for triggering a Lambda function from an SQS FIFO queue.
Closes #7023 
See [AWS documentation for SQS](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html).
None.
<details>
</details>
> Update AWS SQS event docs regarding FIFO queue trigger for Lambda

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Support for AWS SDK sub-classes
Closes #7030
`serverless.yml`:
```yaml
service: myService
provider:
name: aws
plugins:
- serverless-test-plugin
functions:
hello:
```
`.serverless_plugins/serverless-test-plugin.js`:
```js
'use strict';
class TestPlugin {
constructor(serverless) {
this.provider = serverless.getProvider('aws');
this.serverless = serverless.service;
this.hooks = {
'after:package:finalize': () => this.test()
};
}
async test() {
await this.provider.request('DynamoDB.DocumentClient', 'put', {});
}
}
module.exports = TestPlugin;
```
The code snippet errors both before and after the change, but still shows the `DynamoDB.DocumentClient` sub-class is being used.
Before:
```
Type Error ---------------------------------------------
TypeError: …
```
> awsprovider - adding support for SDK sub-classes.

- docs/providers/aws/cli-reference/deploy.md
- lib/plugins/aws/lib/monitorStack.js
- lib/plugins/aws/provider/awsProvider.js
Closes #6980 
I did create that inside the github console, given the simple logic I do believe that its fine. But those might also be famous last words!
> Provide backoff for retryable aws requests and the option to adjust the cf status check interval via an environment variable

- lib/plugins/aws/customResources/generateZip.js
- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/index.test.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.test.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
This should partially address custom resource installation efficiency issues, as discussed recently on slack.
It ensures that custom resource package is prepared once for installed Serverless versions, and in further runs existing package is re-used.
> Optimize custom resources generation

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Fixes https://github.com/serverless/serverless/issues/6165
If given APIGW stage parameter is not explicitly set in configuration, then it should not be updated by deployment.
> Update API GW stage settings only when explicitly set

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Fixes https://github.com/serverless/enterprise-plugin/issues/266
And partially addresses https://github.com/serverless/serverless/issues/6584
> Do not apply APIGW wide settings on externally referenced APIGW

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Added the `--disable-content-trust=false` flag to the `docker pull` command to ensure that images are signed correctly (`lambci/lambda` images are now signed):
https://docs.docker.com/v17.09/engine/security/trust/content_trust/
Run invoke local with the docker option
You could potentially add an option for this in case people don't want to check signed images...? Not sure why they'd want that.
The other way to implement it would be to set `DOCKER_CONTENT_TRUST=1` in the environment that you spawn the Docker command with. Not sure if you'd prefer that either
> Enable Content Trust checking when pulling lambci/lambda images

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Fixes: #7036 
Test was invalid, hence it wasn't picked earlier
> Fix resolution of user configured APIGW

- docs/providers/aws/events/websocket.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/websockets/lib/stage.js
- lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Add option to change the log level of websocket logs to ERROR. Note that I did not add an option to disable logs on purpose in order to keep the change small. 
```
service: serverless-ws-test
provider:
name: aws
logs:
websocket:
level: ERROR
websocketsApiName: custom-websockets-api-name
functions:
connectionHandler:
handler: handler.connectionHandler
events:
- websocket:
route: $connect
defaultHandler:
handler: handler.defaultHandler
events:
- websocket: $default
```
1. Run `sls deploy`
1. Open the _Logs/Tracing_ settings of the API gateway. 
1. Should look like this: <img width="883" alt="Screen Shot 2019-12-02 at 23 28 21" src="https://user-images.githubusercontent.com/7386945/70000544-883b0d00-155b-11ea-9ce2-3bd4b7d6dce4.png">
1. Change `level: ERROR` to `level: …
> Add option to change log level for websocket logs

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Fixes #7013 
Regression introduced with #6938
> Fix AWS creds handling

- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
When testing locally it now, when it's available, I've realized it was not setup properly, and that it should be setup on `AWS::Lambda::Version` resource.
Having that patch in, I've successfully deployed new lambdas with provisioned concurrency setup. 
However I observed `Internal error` CF stack udpate crashes when trying to update already deployed lambdas with that config (This looks as AWS issue, which I discuss with them over email)
> Fix lambda provisioned concurrency setup

- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Provides default apig resource policy.  This ensures any previously defined resource policy gets overwritten.  
Closes #6789 
First create a resource policy that limits traffic to your source ip address.
```yaml
provider:
name: aws
resourcePolicy:
Principal: '*'
Action: execute-api:Invoke
Resource:
- execute-api:/*/*/*
Condition:
IpAddress:
aws:SourceIp:
- '123.123.123.123'
```
Now remove said policy, and test accessing the endpoint using a different source address from original policy.
```yaml
provider:
name: aws
```
<details>
- `npm run lint:fix` --> Automatically fix lint …
> Resource policy

- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Reverts serverless/serverless#7002
It appears that added policy doesn't reflect default behavior when no policy is added (our integration tests fail now: https://travis-ci.org/serverless/serverless/jobs/620628266 )
btw. We probably need to find a way to run integration tests on selected PR's prior merging them
> Revert "Resource policy" fix

- .travis.yml
- CHANGELOG.md
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
- package.json
Regression introduced with #7044
Fixes #7050
--- 
It's based against `release-fast-track` which points last release, so we can release it as v1.59.1 (without taking any other stuff that was eventually merged to master after v1.59.0)
Handling of `release-fast-track` branch will be mostly automated shortly (I will prepare PR with CI config update today), still to not hold this, patch, I will issue v1.59.1 mostly manually now.
After it's merged to `release-fast-track`, I'll tag it on that branch and in result CI will automatically publish new version to npm, then I'd also ensure that it's merged into master and that release notes are added.
> Fix cached credentials mishandling

- docs/providers/aws/events/streams.md
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
Adding MaximumRetryAttempts for stream event sourcing to avoid retry attempts to be default 10000 and potential poison pill scenarios and related documentation
`Details`
Adding configurability of MaximumRetryAttempts for stream event sourcing(Dynamo& Kinesis) to avoid maximum retry attempts(default 10000) and potential poison pill scenarios and related documentation
Closes #7012
`Example serverless.yml:`
```yml
functions:
preprocess:
handler: handler.preprocess
events:
- stream:
arn: arn:aws:kinesis:region:XXXXXX:stream/foo
batchSize: 100
maximumRetryAttempts: 10
startingPosition: LATEST
enabled: false
```
<details>
</details>
> Adding configurable MaximumRetryAttempts for stream(Dynamo& Kinesis) event sourcing

- .travis.yml
- CHANGELOG.md
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- package.json
- tests/integration-all/api-gateway/tests.js
- tests/utils/cognito/index.js
It appears that when in a same service we refer to both, to be created and existing Cognito Pool, then one marked as existing is also created.
This issue was actually constantly exposed by repeatedly failing integration test as here: https://travis-ci.org/serverless/serverless/jobs/620574993
Updated test logic so this issue is exposed at all times meaningfully, and fixed the issue.
This PR initially was about fixing our tests (as integration tests after having #7058 will pre-validate all our releases). Therefore it comes also with fix to other integration test issue (e.g. exposed here: https://travis-ci.org/serverless/serverless/jobs/620679229 ), where defined API key sometimes demand a bit more time to be in effect.
Additionally fixed …
> Fix handling of existing cognito pools

- lib/plugins/aws/lib/validate.js
- lib/plugins/aws/lib/validate.test.js
Closes #6961
Stop using aws metadata service to validate if serveless is running inside of an ec2 machine or not. The check will never be relaible as it is not guaranteed that the latency of the api will be below .1 second.
<details>
</details>
> New flag to bypass validation when deploying from ec2 machine

- docs/dashboard/cicd/README.md
Documentation on added support for Python in the Serverless Framework Pro CI/CD and a note about using package.json scripts for running scripts before/after tests and install.
Just docs, nothing executable to verify. I added Rowell as reviewer to check for accuracy.
> Add docs on Python support in CI/CD

- .travis.yml
- CHANGELOG.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
- package.json
Fixes https://github.com/serverless/serverless/issues/7059, although with cost of limited support for provisioned concurrency (via CF means it seems there's no reliable mean to set it up with versioning enabled, I'm currently figuring it out on a side with AWS team).
Fixes https://github.com/serverless/serverless/issues/7049, by ensuring that `ParallelizationFactor` is not set, if not explicitly configured.
_Brought under one PR, to issue both under same patch release._
Additionally fixed few issues observed in recently published new CI config:
- Pushed commits from CI were not signed with recognizable email address. Fixed that by configuring expected email for git
- Fix issue with fast-forward merge to master
- There are duplicate tag create attempts in `master` or `release-fast-track` …
> Fix provisioned concurrency & ParallelizationFactor handling

- .travis.yml
It's to fix issue observed here: https://travis-ci.org/serverless/serverless/jobs/623555231
It appears that `--depth` setting for some npm versions makes optional dependencies not optional. Workaround it with `--no-optional` with that npm will not attempt to install optional dependencies.
Additionally decreased `--depth` to make npm updates a bit faster
--- 
Based against `release-fast-track`, so we have that fix available also for eventual patch releases
> CI: Fix npm update related issues

- .travis.yml
- tests/mocha-reporter.js
Addresses two exposed CI issues:
- https://travis-ci.org/serverless/serverless/jobs/623639175
It's likely caused by fact that for each test file run home dir is cleared, hence once generated `custom-resources.zip` is not available to further tests.
This issues seems to expose occasionally (it probably depends on order in which tests are run).
Ensured that for each test run generation cache is cleared, hence further test runs do not start with assumption that this file was already generated.
- https://travis-ci.org/serverless/serverless/jobs/623639182
It appears that `--no-optional` patch for npm update fails with npm@3. In this case upgrade to npm version that comes with Node.js v8
> CI improvements

- lib/classes/Variables.test.js
- lib/plugins/aws/customResources/index.test.js
- lib/plugins/aws/package/lib/generateCoreTemplate.test.js
- lib/plugins/config/config.test.js
- lib/plugins/interactiveCli/initializeService.test.js
- lib/plugins/interactiveCli/setupAws.test.js
- lib/plugins/interactiveCli/tabCompletion.test.js
- lib/utils/fs/copyDirContentsSync.test.js
- package.json
- Improve error information in case of a test fail in custom resource tests
- Upgrade to `@serverless/test` v3 - it replaced _whitelist_ approach with _blacklist_ which makes test configured with `runServerless` more reliable, and also makes tests configuration significantly easier (diff nicely confirms on that)
- Ensure to pass _after_ callbacks to dynamic skip conditionals. Not doing that, resulted with `process.env` being altered for further test file runs, which most likely was responsible for some CI fails as: https://travis-ci.org/serverless/serverless/jobs/623668512 (observed mostly on Windows)
- Ensure to start each test file run with `process.env` being at state in which it was before any tests were run. Thanks to that any uncleaned `process.env` modifications will not affect any …
> Test setup improvements

- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Allows to use Ref, Fn::GetAtt or Fn::ImportValue in awsKmsKeyArn config.
My first PR to this project so not sure how good approach this is but tried to mimic stuff that already exists. 
I'm mainly interested in Fn:GetAtt and Fn::ImportValue in my own project but used the ready-made function which now also supports the Ref. Not sure if needed here?
Modified error message a bit and added a couple of simple test cases. 
Closes https://github.com/serverless/serverless/issues/7057
```
service:
name: test-service
awsKmsKeyArn: !GetAtt ['MyKmsKey', 'Arn']
resources:
Resources:
CustomKmsKey:
Type: "AWS::KMS::Key"
Properties:
KeyPolicy:
Version: "2012-10-17"
Id: "CustomKmsKey"
Statement:
- Sid: "Enable IAM User Permissions"
Effect: "Allow"
Principal:
AWS: <aws account_id>
Action:
- "kms:*" …
```
> Allow use of Ref, Fn::GetAtt and Fn::ImportValue in awsKmsKeyArn

- lib/classes/PluginManager.js
- lib/classes/PluginManager.test.js
Previously, the plugin manager did not properly set the default value if the default value is `0`, `false`, or `''`. This PR fixes that.
Closes #XXXXX (none that I can find)
`serverless.yml`:
```yaml
service: foo
provider:
name: aws
plugins:
- serverless-test-plugin
```
`.serverless_plugins/serverless-test-plugin.js`:
```js
'use strict';
class TestPlugin {
constructor(serverless, options) {
this.options = options;
this.commands = {
options: {
usage: 'Options viewer',
lifecycleEvents: ['options'],
commands: {
log: {
usage: 'Log all options',
options: {
zero: { default: 0 },
'empty-string': { default: '' },
false: { default: false }
},
lifecycleEvents: ['log']
}
}
}
};
this.hooks = {
'options:log:log': () => this.log()
};
}
log() {
console.log('log()'); …
```
> Plugins - now allow falsy default values.

- package.json
Travis currently runs integration tests one by one (no concurrent runs). It's due to fact, that only one CPU core is provided for test run (so technically it behaves as expected).
Still in case of this tests we do a lot of network calls, so introducing a concurrency will speed up a build time (we already reached maximum allowed time of 50 minutes by Travis: https://travis-ci.org/serverless/serverless/jobs/624151922)
And as I tested, this patch speeds this up from 40-50, to just 8 minutes.
> CI: Run integration tests concurrently

- lib/plugins/aws/package/compile/events/lib/ensureApiGatewayCloudWatchRole.js
Addresses issue mentioned in #7100
Run all integration tests (including those that involve creation of APIGW logs) to confirm it doesn't break anything by accident
> Fix AWS partition reference in APIGW CloudWatch role setup

- .travis.yml
- commitlint.config.js
- scripts/pkg/build.js
- Ensure upload of binaries to GitHub release (with missing tag, it didn't happen, I've already fixed it manually for v1.60.0
- Ensure to bundle binary with latest stable npm (as validated by Node.js)
Additionally fixed CI fail observed here: https://travis-ci.org/serverless/serverless/jobs/626651988
(It appears that tags for taken commits are visible in trimmed repository, and failed happened in a command which was not secured to ignore it)
> Binary installer improvements

- commitlint.config.js
- lib/classes/Variables.js
- lib/classes/Variables.test.js
Fixes #7098
When same variable declarations are used across configuration, the config ended with same shared instances of resolved object.
It affected situation where some normalization were made directly on resolved objects.
This patch ensures no duplicate instances are shared across config.
> Ensure no same object instances are shared across config

- lib/plugins/aws/customResources/generateZip.js
- lib/plugins/aws/customResources/index.test.js
- tests/integration-all/api-gateway/tests.js
- tests/integration-all/websocket/tests.js
- tests/integration-basic/tests.js
- tests/utils/api-gateway/index.js
- tests/utils/cloudformation/index.js
- tests/utils/cloudwatch/index.js
- tests/utils/cognito/index.js
- tests/utils/dynamodb/index.js
- tests/utils/eventBridge/index.js
- tests/utils/iot/index.js
- tests/utils/kinesis/index.js
- tests/utils/misc/index.js
- tests/utils/s3/index.js
- tests/utils/sns/index.js
- tests/utils/sqs/index.js
- tests/utils/websocket/index.js
Addresses fail observed at: https://travis-ci.org/serverless/serverless/jobs/626693791
`Rate exceeded` is retryable error, from which test could recover.
Update tests to rely on common newly introduced `awsRequest` util, which will ensure recovery in such situations. Additionally `awsRequest` exposes all request logs if needed.
> Integration tests: Recover from retryable errors

- lib/plugins/aws/customResources/index.js
Issue exposed occasionally in CI fails, e.g. https://travis-ci.org/serverless/serverless/jobs/627729256
It appears that for every custom resource registration we attempted to copy generated zip file into  a service folder.
In tests when multiple custom resources registrations are issues at same time, it introduced a race condition, where copying logic finding the custom resource already in a folder, was trying to delete (before again copying over), but on deletion it found it's no longer there.
On Windows it exposed as EPERM error, as second copy process didn't have write access to file as being created by other copy process.
This patch ensure we copy generated artifact only once in context of given service.
> Fix multiple custom resource generation

- docs/getting-started.md
An additional note to inform users that they newly installed binary will work only in new terminal windows
> Improve binary installer documentation

- commitlint.config.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Fixes #7059 
Setup provisioned concurrency on an alias that references function version. This allows us use provisioned concurrency easily with lambda versioning (otherwise we will have to somehow resolve old version hash to ensure to clear provisioned concurrency from there), and also workarounds "Internal Failure" error, which happens on AWS side, when we try to update version's provisioned concurrency configuration.
Link API Gateway endpoint against created alias, as when it's linked against function, it in all cases addresses `$LATEST` alias, which is not provisioned (and cannot be provisioned).
Additionally added workaround for current AWS issue, where changing referenced lambda version under alias with provisioned concurrency setup, resulted with `Alias with weights can not be used …
> Fix provisioned concurrency setup issues

- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/index.test.js
- lib/plugins/aws/package/lib/iam-role-lambda-execution-template.json
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Since some recent changes on AWS side, IAM access rules we assign for lambda are no longer good enough to write CloudWatch logs.
This patch ensures our access rules are complete
Closes #6241 (is related to it, puts proposed solution out of a table)
Closes #6692 (implements it in safe way)
> Fix access rules for CloudWatch logs creation

- .travis.yml
- lib/plugins/aws/package/compile/events/apiGateway/index.js
- lib/plugins/aws/package/compile/events/apiGateway/index.test.js
Fixes #7036 
Sometimes users create a service in which they just configure the API Gateway, and configure endpoints in other services which reference it.
We didn't support applying stage settings on API Gateways configured that way. This patch fixes that.
Additionally increased git history depth in `.travis.yml` to avoid CI fails as:  https://travis-ci.org/serverless/serverless/jobs/628681233
> Ensure API GW stage settings are applied when no endpoints are configured

- commitlint.config.js
- lib/utils/config/index.js
Fixes #7077 
Expose eventual save error only when SLS_DEBUG is on.
This error doesn't affect how framework works, while confuses new users when happening
> Improve user config error handling

- CHANGELOG.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
- package.json
Regression introduced with #7126. After which update stage logic complains it cannot find API id, when there's no API, no HTTP endpoints configured but there are some API rest settings configured (in case of dashboard they're automatically implied)
> Fix Rest API id detection when no API GW involved

- commitlint.config.js
- lib/Serverless.js
- lib/classes/CLI.js
- lib/plugins/plugin/install/install.test.js
- lib/plugins/plugin/lib/utils.js
- lib/plugins/plugin/lib/utils.test.js
- lib/plugins/plugin/uninstall/uninstall.test.js
- lib/utils/resolveCliInput.js
Fixes #7106 and #7130 
Problems:
- We document `-c` shortcut for `--config`, while support for it never seamed to be implemented
- Plugin install logic, relies on some side serverless config file path resolver
Solution:
- Unified resolution of input arguments, and provided basic minimist configuration (never used before) to ensure that e.g. `-c` is always aliased to `--config`
- Ensure plugin logic relies on commonly used serverless config file resolver
> Fix config option handling

- package.json
I noticed the version of download was pretty old (almost 3 years old).
The new version (which is still from 2018) fix a moderate vulnerability (download > caw > tunnel-agent, see https://www.npmjs.com/advisories/598).
From the repo, I tried theses install option to validate everything went fine:
```bash
./bin/serverless install -u https://github.com/serverless/examples/tree/master/openwhisk-node-simple-http-endpoint -n github
./bin/serverless install -u https://gitlab.com/laardee/serverless-template-example -n gitlab
```
<details>
- `npm run …
> Update download deps to latest

- package.json
We've relied on `commitlint` which is now an alias to `@commitlint/cli`.
Still `commitlint` started to crash badly with `The "path" argument must be of type string. Received type undefined` as we can see here: https://travis-ci.org/serverless/serverless/jobs/632251308
Issue seems not shared by `@commitlint/cli`
> Switch to @commitlint/cli

- bin/serverless.js
- commitlint.config.js
- lib/utils/standalone-patch.js
- package.json
- scripts/pkg/config.js
Some dynamically referenced files from dashboard plugin were not picked automatically.
Additionally it appeared that due to bug in pkg-> zeit/pkg#420 copying of wrapper files crashed, introduced a generic workaround for that issue.
Other issue is already fixed in https://github.com/serverless/enterprise-plugin/pull/339 which is bumped here to fixed version
> PLAT-2171 Fix bundling of dashboard plugin for standalone

- tests/integration-all/event-bridge/tests.js
- tests/utils/misc/index.js
It's to address observed CI fail: https://travis-ci.org/serverless/serverless/jobs/632251893
There's a possible race condition where events issued right after deployment do not trigger lambda yet.
Similar issue was observed when testing Websocket logs, and for that then I've created an utility which invokes the lambda trigger until logs are written (or until timeout occurs).
Updated  event bridge tests to rely on same util.
> Fix event bridge related integration tests

- lib/plugins/aws/lib/updateStack.js
- lib/plugins/aws/lib/updateStack.test.js
Until now, failed stack deploys when using deploymentBucket to specify an existing bucket were left in ROLLBACK_COMPLETE state. This required manual 'sls remove' before a redeploy.
This was partly addressed by #5631, which changed createStack to auto-delete CloudFormation stacks on failure. However, it looks like when using a custom deploymentBucket, the stacks are lazily created via some duplicated code in updateStack.js. This code still used the ROLLBACK setting for newly created stacks.
Closes #6612.
Create an S3 bucket named `some.unique.s3.bucket.that.serverless.can.access`
Deploy this `serverless.yml`:
```
service: test-service
provider:
name: aws
deploymentBucket:
name: some.unique.s3.bucket.that.serverless.can.access
resources:
Resources:
Bucket:
Type: AWS::S3::Bucket
Properties: …
```
> fix: Auto-delete on AWS stack create failure when using a custom deployment bucket

- package.json
Closes #7168 
Seems safe to do, as support for Node.js v6 is maintained
> Upgrade https-proxy-agent to v4

- docs/providers/aws/events/streams.md
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
What did you implement
Add the ability to configure the BisectBatchOnFunctionError feature for failure handling on Kinesis and DynamoDB streams.
Closes #7041 
Sample serverless.yml:
```yml
functions:
preprocess:
handler: handler.preprocess
events:
- stream:
arn: arn:aws:kinesis:region:XXXXXX:stream/foo
bisectBatchOnFunctionError: true
```
<details>
</details>
**_Is it a …
> Add BisectBatchOnFunctionError option for Dynamo and Kinesis event sourcing

- lib/utils/downloadTemplateFromRepo.test.js
Suddenly I've started to observe downloadTemplateFromRepo test failing for me locally.
It might have been influenced by #7155, still real issue was that successful run depended on order in which two async operations proceed their tasks.
Applied a patch that ensures fixed order
> Tests: Fix download template race condition

- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js
Fixes #7189  (Regression introduced with https://github.com/serverless/serverless/pull/7102)
Additionally ensured old function arn format, when no provisioned concurrency setup is involved, this should help partially solve issues for users of plugins which relied on old template format -> https://github.com/davidgf/serverless-plugin-canary-deployments/issues/71
> Fix lamdba permissions setup when authorizer is involved

- package.json
We were fixed on v4.2.1 due to critical bug in v4.2.2 (more info at  #6667) but that's fixed with v4.2.3.
While v4.2.1 might be responsible (not confirmed) for CI crashes which happen occasionally: https://travis-ci.org/serverless/serverless/jobs/632275541
> Upgrade `graceful-fs` to ^4.2.3

- docs/providers/aws/cli-reference/invoke-local.md
- lib/utils/resolveCliInput.js
- package.json
- scripts/pkg/upload.js
Replaces minimist with yargs-parser
Also fixes an issue where "nested" arguments contain an equals sign
Closes https://github.com/serverless/serverless/issues/6083
invoke local --function hello --docker --docker-arg="-e AWS_ACCESS_KEY_ID=1" --docker-arg="-e AWS_SECRET_ACCESS_KEY=1"
<details>
</details>
> Replace minimist with yargs-parser

- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Regression introduced with #7138
After contacting AWS Support, I've learned that default policy (so no policy) can be ensured by passing an empty string with a setting
Fixes #7194 #7211
>  Fix default APIGW resource policy configuration

- CHANGELOG.md
- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
- package.json
Fixes https://github.com/serverless/enterprise-plugin/issues/340
Dashboard plugin at initialization eventually resolves credentials for a framework, and as region resolution comes with it, it also ensures that [region is resolved](https://github.com/serverless/enterprise-plugin/blob/961d33b303af3e3811d6af74269492b083a5fd3f/lib/deployProfile.js#L16)
Still this is taken care of prior variables resolution and there's no guarantee that region value is resolved, hence if region is configured with variables, then unresolved value is passed to AWS SDK, resulting with crash.
> PLAT-2173 Separate AWS region and credentials resolution concern

- lib/classes/Error.js
- lib/classes/Error.test.js
- lib/classes/Variables.test.js
- lib/plugins/aws/provider/awsProvider.js
`code` allows to programmatically identify the errors, which is valuable when testing.
It's a common pattern used in Node.js and related projects.
I'm replacing `statusCode` (which is misleading as suggests HTTP request handling), which was added as internal aid with #2189 and doesn't seem to be used and documented, hence seems safe to remove.
> Support `code` on ServerlessError

- docs/providers/aws/events/sns.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/sns/index.js
- lib/plugins/aws/package/compile/events/sns/index.test.js
This allows to define the redrivepolicy for sns events (so messages that can't be delivered to lambda end in a SQS for future retries/error handling). This will also create a queuePolicy to allow the SNS topic to submit messages to the DLQ.
This is my first attempt ti create a PR to the serverless repo, so not sure what other parts could be missing.
Closes #7229
Should be possible to test this by adding to a SNS event:
````
redrivePolicy:
deadLetterTargetArn: !Ref myDLQ
````
A queue must be defined on the resources section with
````
myDLQ:
Type: AWS::SQS::Queue
Properties:
QueueName: myDLQ
````
> Implement redrivePolicy for SNS events

- lib/classes/Variables.js
- lib/classes/Variables.test.js
Regression introduced with: https://github.com/serverless/serverless/pull/7237
Fixes  #7255
Additionally searched whole codebase for eventual `.statusCode` handling as here and not found any more cases.
> Fix AWS request statusCode handling

- docs/dashboard/output-variables.md
- docs/dashboard/parameters.md
This adds documentation on the `output` and `param` sub commands available via the enterprise-plugin to access the Serverless Framework Pro outputs and parameters.
All of the dependencies have been released, so this is ready to be merged & deployed (after review).
> Adds docs on param & output sub commands

- scripts/pkg/generate-choco-package.js
When switching from `minimist` one place was left out.
It happened probably because two PR's (#7187 and #7109) were merged around same time (with one not being in sync with master after other was taken in) and we don't have linter setup on master which would pick this up afterwards.
To avoid such issues in a future, I've turned on (experimentally) "_Require branches to be up to date before merging_" setting. Hopefully it won't be too obtrusive.
> Ensure to use proper CLI params parser in a script

- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js
Fixes a permission issue when using custom authorizers for API Gateways.
❗️ **NOTE:** Note entirely sure about the impact, but thus could result in a breaking change... ❗️
The easiest way would be to run the integration tests. Other than that you could use this service config (provided by @glb):
```yaml
service: test
provider:
name: aws
functions:
example:
role: exampleRole
handler: bin/example
events:
- http:
path: /echo
method: GET
authorizer:
name: authorizer
arn: arn:aws:lambda:us-east-1:111111111111:function:sample
```
**_Is it a breaking change?:_** MAYBE
> fix: Limited permission for authorizers

- docs/providers/aws/events/apigateway.md
The link is broken because the section is called "Request Schema **Validators**", but in the Table of Contents it's "Request Schema **Validation**".
This commit updates the section name in the TOC with the correct one.
You can check out the problem trying to open the "Request Schema Validation" link in the following page: 
https://serverless.com/framework/docs/providers/aws/events/apigateway
> Fix "Request Schema Validators" TOC link

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
There are use cases where an API creator does not have access to add permissions to the custom authorizer function; one example is when the custom authorizer function exists in a separate AWS account. In these cases, we need to be able to omit the `AWS::Lambda::Permission` resource that allows API Gateway to call the authorizer function from the stack.
This change adds the `managedExternally` attribute to the `authorizer`. When `managedExternally` is `true`, the stack will not create the `AWS::Lambda::Permission` resource that allows API Gateway to call the authorizer function.
**Important note:** The permission does still need to be created before the stack is deployed, or creating the authorizer will fail.
Closes #7296.
1. Copy `serverless.yml (before)` to `serverless.yml`.
2. Run …
> feat: support externally-managed custom authorizers

- docs/providers/aws/events/streams.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
Closes #5510
I added the a new configuration property for Kinesis data stream events which configures the event source mapping to use a stream consumer instead of shard iterator.
It creates a new stream consumer when set to `true` and uses an existing consumer if given the ARN of one.
It manages the necessary IAM permissions and supports functions such as `Ref` and `ImportValue` (essential since stream consumer ARNs are AWS generated with timestamps in them).
This is my first PR of this size to this project, so apologies if I didn't quite get some conventions right.
```yaml
service: dct
provider:
name: aws
functions:
hello:
events:
- stream:
batchSize: 1
type: kinesis
arn:
Fn::GetAtt:
- ExampleStream
- Arn
consumer: true
- stream:
batchSize: 1 …
```
> Add support for Kinesis Data Streams Enhanced Fan-out (Consumers)

- .travis.yml
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
- tests/integration-all/http-api/tests.js
As @Nemo64 suggested here: https://github.com/serverless/serverless/issues/7052#issuecomment-584267234 There's no valid point to nest endpoint behind stage prefixes.
This PR improves that, so we rely on `$default` stage instead
> HTTP API: Switch to default stage deployments

- .travis.yml
As in case of other repos, it hit that one.
https://travis-ci.org/serverless/serverless/jobs/652173262
In light of above crash I've published v1.64.0 manually, and ensure standalone binaries are generated
> Workaround Travis CI regression

- docs/providers/aws/events/http-api.md
I fixed a small typo in the documentation where "authorizers" was spelled as "autorizers".
> Fix spelling of "authorizers"

- lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
- lib/utils/tracking.js
While being in New Zealand on good cable internet connection I've observed that technically no stats requests succeed, as on average they take 2s, sometimes leaning over 3s.
Therefore I think we should increase timeout, to ensure we cover more remote areas.
--- 
Additionally addressed test race condition issue, exposed by CI fail: https://travis-ci.org/serverless/serverless/jobs/652705887
> Increase stats request timeout

- lib/plugins/aws/customResources/resources/eventBridge/lib/eventBridge.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js
- lib/plugins/aws/customResources/test/eventBridge.test.js
- lib/plugins/aws/customResources/test/utils.test.js
- lib/plugins/aws/package/compile/events/eventBridge/index.js
- lib/plugins/aws/package/compile/events/eventBridge/index.test.js
AWS EventBridge RuleName and TargetId shortener in order to prevent exceeding max string length of 64 chars.
Closes https://github.com/serverless/serverless/issues/7356
```yml
service: myService
provider:
name: aws
stage: dev
region: eu-west-1
functions:
myVeryLongAndVeryComplicatedFunction:
events:
- eventBridge:
eventBus: myBus
pattern:
source:
- mySource
```
> fix(AWS EventBridge): Truncate rule names, target ids longer than allowed 64 chars

- lib/utils/fs/fileExistsSync.js
- lib/utils/fs/fileExistsSync.test.js
Use normal `stat` instead of `lstat` for checking the configuration to allow symlinks for people that keep rc's in source control.
Closes #7369
Make your `.serverlessrc` a symlink and see that it changes every time you do anything.
Apply this change, and you'll see it no longer does that.
> Allow symlink for config

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Amazon API Gateway support associating your API with an interface VPC endpoint. This is supported in cloudformation via EndpointConfiguration. Associating your API with the VPCE creates a custom DNS alias which allows you to access your private gateway through the VPCE without the need of a Host header, which is necessary in certain situations, particularly if you want to make ajax calls to your private API from a browser.
Closes #6715 & #7112 
```
service: api-private-test
provider:
name: aws
stage: ${env:AWS_ENV}
region: ${env:AWS_DEFAULT_REGION}
timeout: 30
memorySize: 128
endpointType: PRIVATE
endpointVpcIds: 
- vpce-0250d95e899edfa1b
- vpce-0250d95e899edfa1c
resourcePolicy:
Principal: ''
Action: execute-api:Invoke
Resource:
- execute-api:/// …
```
> Enable association of VPC endpoint ids on AWS private API Gateways

- lib/plugins/aws/lib/getServiceState.js
- lib/plugins/aws/lib/getServiceState.test.js
Should resolve #7318 by using `path.resolve` instead of `path.join`
For arbitrary project, run commands that were described in the issue #7318:
`serverless package --package {somePath}`
`serverless deploy --package {somePath}`
The result should be no error thrown and usual info regarding project deployment is shown.
**_Is this ready for review?:_** Yes
**_Is it a breaking change?:_** No
> Fix path resolving

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
Addresses #7052 
To be able to enrich default stage with additional settings as log access, or be able to enrich default route with authorization or make it removable, we should not rely on default route configuration (that could be added with `AWS::ApiGatewayV2::Api` resource), but need to define stage and route explicitly.
This patch ensures we configure default route that way
> Fix HTTP API default stage handling

- .travis.yml
Addresses fail observed in https://travis-ci.org/serverless/serverless/jobs/655178713
Recently we've patch Windows Unit tests build -> https://github.com/serverless/serverless/commit/29b37d7c442c2b1dca1e20d732f367ad8d5b84e4#diff-354f30a63fb0907d4ad57269548329e3 but deploy build remained affected
> Fix install in deploy build on windows

- docs/providers/aws/guide/iam.md
CloudFormation gives an error otherwise (when using  - { 'Fn::Join': [':', ['arn:aws:iam:', { Ref: 'AWSAccountId' }, 'some/path']] } as it is currently documented): 
"Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [AWSAccountId] in the Resources block of the template"
see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html 
Closes: dont know. I just fixed it without a bug report by clicking the link in the docs
Try using the code in the current docs without the colons in a serverless.yml
It will give the error mentioned above.
Then try it with a serverless.yml that uses the "AWS::AccountID instead"
It's a documentation change - it cannot be tested automatically I believe.
**_Is this ready …
> docs: add missing colons to AWSAccountID

- package.json
Updates `object-hash` to use the current version that dropped support for old versions of node
Closes #7403
`npm install` or `yarn install`
**_Is this ready for review?: Yes
**_Is it a breaking change?: No
> Update object-hash to 2.0.3

- lib/Serverless.js
Fixes a bug in the Update logic for the Standalone binary: 
`TypeError: chalk(...).dim is not a function`
Closes https://stackoverflow.com/questions/60457609/serverless-typeerror-chalk-dim-is-not-a-function
Expected Result:
> fix(Standalone): Fix bug where chalk is called as a method

- lib/plugins/aws/customResources/resources/s3/handler.js
- lib/plugins/aws/customResources/resources/s3/lib/permissions.js
- lib/plugins/aws/package/compile/events/s3/index.js
This PR adds the `SourceAccount` condition with the current account to the lambda permission for s3 events.
Closes #7103 
Deploy a function with an s3 event trigger:
```yaml
photoupload:
handler: photoupload.handler
description: Process images dropped into S3
events:
- s3:
bucket: mybucket
event: s3:ObjectCreated:*
```
The lambda policy will now include the `AWS:SourceAccount` condition:
```json
{
"Version": "2012-10-17",
"Id": "default",
"Statement": [
{
"Sid": "autogensid",
"Effect": "Allow",
"Principal": {
"Service": "s3.amazonaws.com"
},
"Action": "lambda:InvokeFunction",
"Resource": "arn:aws:lambda:us-east-1:999999999999:function:photoupload",
"Condition": {
"StringEquals": {
"AWS:SourceAccount": "999999999999"
},
"ArnLike": {
"AWS:SourceArn": "arn:aws:s3:::mybucket"
}
}
}
]
}
``` …
> Fix #7103 Add source account to lambda permissions for s3 events

- docs/providers/aws/events/http-api.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
Additionally deprecate (by not documenting) a `timeout` setting on HTTP API endpoint.
As HTTP API endpoints can only be configured through functions, it seems logical to treat function timeout setting as the only source of truth.
Should be considered as bug fix.
> AWS HTTP API: Ensure function timeout setting is respected

- commitlint.config.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
Fixes #7414 
In operation in which we read existing configuration to reliably update the configuration, one of the properties were not filtered as expected
> Fix cognito pool update handling

- docs/providers/aws/guide/layers.md
Modify the docs so that if someone copy pastes a block of text regarding lambda layers they don't inadvertently grant world read access.
> modify sample block to exclude insecure by default copy pasta

- .travis.yml
Revert from --depth as it appears buggy. It started to expose fails: https://travis-ci.org/serverless/serverless/jobs/658977392 suggesting that `--no-optional` is not effective in some (not exactly clear which) scenarios
> CI: Fix buggy npm configuration

- lib/plugins/aws/package/compile/events/websockets/lib/api.js
- lib/plugins/aws/package/compile/events/websockets/lib/api.test.js
During [`compileApi`](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/websockets/lib/api.js#L7), the websockets AWS policy generated currently assumes the standard 'aws' partition (see [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/websockets/lib/api.js#L42)). This PR replaces 'aws' with the `AWS::Partition` pseudo parameter.
Closes #7149
A new websockets service using a non-standard region; for example:
```yml
service: api
frameworkVersion: '>=1.28.0 <2.0.0'
provider:
name: aws
runtime: go1.x
stage: production
region: us-gov-west-1
...
```
Will result in something like the following error:
```shell
Serverless: Packaging service...
Serverless: Excluding development dependencies...
... …
```
> Fix #7149 <WSS> Use AWS partition pseudo param

- docs/providers/aws/events/http-api.md
Typos found in https://serverless.com/framework/docs/providers/aws/events/http-api/
Just fixed two typos in documentation
Open the URL provided in the first line of this description.
> Fixed typos in http-api.md

- lib/plugins/aws/package/compile/events/httpApi/index.js
Fixes #7440 
In case when there's a function with a timeout over 29s and no `httpApi` events configured, an invalid log warning is issued.
```
Function timeout setting (x) is greater than maximum allowed timeout for HTTP API endpoint...
```
This patch fixes that.
Additionally improved log warning so it includes a function name to which it refers
> AWS HTTP API: Do not validate timeout when no httpApi event

- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Locally created role was uncoditionally assumed when configuring lambda destinations.
This patch fixes that.
Fixes #7448
> Respect external IAM role at lambda destinations

- docs/dashboard/monitoring/README.md
- docs/providers/aws/guide/events.md
This PR updates the docs to include information on the disableHttpSpans and disableAwsSpans configuration options. It also adds a reference from the aws events document to the API Gateway document about path parameters for convenience
Simply view the markdown files here on github:
* https://github.com/serverless/serverless/tree/docs-update/docs/dashboard/monitoring#configuration
* https://github.com/serverless/serverless/blob/docs-update/docs/providers/aws/guide/events.md#pathparameters
> Docs update

- docs/dashboard/monitoring/README.md
- docs/dashboard/sdk/README.md
Fix / update documents around enterprise-plugin configuration and usage
View the documents, make sure the updated link on https://serverless.com/framework/docs/dashboard/monitoring/#http-spans correctly pulls up the SDK page with the `advanced-span-configuration` anchor
> chore: Fix broken link in docs and add clarifying information

- lib/plugins/aws/package/compile/events/httpApi/index.js
Fixes #7496 
An error message for case where function has 29s timeout is confusing. This patch improves that
> AWS HTTP API: improve timeout warning messages

- lib/plugins/executable/index.js
- lib/utils/isInChina.js
- lib/utils/isInChina.test.js
- scripts/pkg/install.sh
Fix https://github.com/serverless/serverless/issues/7332
Downloads from GitHub API appear slow in China. We were provided with a mirror at which binaries of new releases will be uploaded.
Mirror is used whenever we detect that user is most likely in China (by investigating system timezone or locale setting)
> Support China mirror for standalone downloads

- docs/dashboard/monitoring/README.md
This is used instead of a CloudWatch log group subscription,
as there can only be one per log group currently.
Rebasing a previous commit message which now violates the commitlint rules would force me to fix every commitlint violation in the last 300 or so commits. Instead I just cherry picked these changes into a new commit. (https://github.com/serverless/serverless/pull/7121)
> docs: Add documentation for log-based polling option

- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
Fix configuring custom HTTP API name
Closes #7433 
```
service: http-api-service
provider:
name: aws
httpApiName: http-api
functions:
test-function:
events:
-  httpApi: 'GET /'
```
Without this change, the API name would be "undefined" (literally)
> fix(AWS HTTP API): set correct api name

- lib/utils/downloadTemplateFromRepo.js
- lib/utils/downloadTemplateFromRepo.test.js
Support ssh format template url, like `git@example.com/sample-service.git`, actually, many company has their private gitlab, so I think supporting these format template urls is a must.
I have add unit test for it:
```js
it('should download the service based on a regular .git URL start with git@', () => {
const url = 'git@example.com/sample-service.git';
return expect(downloadTemplateFromRepo(url)).to.be.fulfilled.then(() => {
expect(spawnStub.calledOnce).to.equal(true);
expect(downloadStub.calledOnce).to.equal(false);
expect(spawnStub.args[0][0]).to.equal('git');
expect(spawnStub.args[0][1][0]).to.equal('clone');
expect(spawnStub.args[0][1][1]).to.equal(url);
});
});
it('should download and rename the service based on a regular .git URL start with git@', () => {
const url = …
```
> fix: support ssh format download template url

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/create/templates/aws-ruby/serverless.yml
Updated serverless.yml template for aws-ruby to use ruby2.7.
https://aws.amazon.com/about-aws/whats-new/2020/02/aws-lambda-supports-ruby-2-7/
Closes #7527
<details>
</details>
> Add support for Ruby 2.7

- lib/plugins/aws/package/compile/events/sqs/index.js
- lib/plugins/aws/package/compile/events/sqs/index.test.js
The `Enabled` property on the `SQS` resource was typed as a `string` but should be a `boolean`
Closes #7438
Input `serverless.yml`
```
service: issue-7438
provider:
name: aws
functions:
hello:
events:
- sqs:
enabled: true
arn:
Fn::GetAtt:
- notifyAppSyncAboutActivitySQSQueue
- Arn
```
Run `> sls package`
Output `cloudformation-template-update-stack.json`
```
"HelloEventSourceMappingSQSNotifyAppSyncAboutActivitySQSQueue": {
"Type": "AWS::Lambda::EventSourceMapping",
"DependsOn": "IamRoleLambdaExecution",
"Properties": {
"BatchSize": 10,
"EventSourceArn": {
"Fn::GetAtt": [
"notifyAppSyncAboutActivitySQSQueue",
"Arn"
]
},
"FunctionName": {
"Fn::GetAtt": [
"HelloLambdaFunction",
"Arn"
]
},
"Enabled": true
}
}
```
Enabled is now being set to a boolean …
> SQS 'Enabled' should be of type 'Boolean'

- docs/providers/kubeless/guide/deploying.md
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
This changes the generated CloudFormation for AWS events to actually use the boolean values true and false, instead of the strings 'True' and 'False'. Right now, these trigger a warning from AWS' cfn-lint tool saying that boolean values are expected.
The tests have been altered to test for the correct values as well.
<details>
</details>
> fix(AWS Events): I don't know why you did this, but that's not how booleans work

- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/s3/index.test.js
When you input an incorrect s3 bucket property you expect a nice error message, instead you get the following error: this.allowedBucketProperties.map is not a function
After the fix the correct error is shown again
${key}" is not a valid bucket property. ....
Create a bucket with a typo in one of the top level properties
provider:
s3:
bulkJobBucket:
name: some-bucket-name
bucketEncryption1:
ServerSideEncryptionConfiguration:
- ServerSideEncryptionByDefault:
SSEAlgorithm: "AES256"
Will end up with the following error message
this.allowedBucketProperties.map is not a function
> Fix error message when s3 bucket is configured with invalid propery name

- lib/plugins/aws/package/compile/events/httpApi/index.js
> AWS HTTP API: Fix default log format

- tests/integration-all/websocket/tests.js
We observe occasional fails as follows: https://travis-ci.org/github/serverless/serverless/jobs/678119380
They most likely occur because message is not delivered (this technically can happen with Websockets). I updated the tests, to resend message if delivery is not confirmed in one second.
> Tests:  Improve Websocket integration test

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
Support `operationId` so it can be used in `Resources` of type `AWS::ApiGateway::Method`.  This enables lambda functions to have custom names associated with them, when exporting the api from API Gateway -- which can then be used in code generators (e.g., swagger).
Closes #7565 
```
functions:
CreateUser:
handler: functions/users.main
events:
- http:
method: post
operationId: createUser
```
<details>
- `npm run prettify:updated` --> Prettify all the updated …
> Add operationId to support AWS API Gateway Method OperationName

- docs/providers/aws/events/http-api.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
HTTP API / Lambda integration supports two event/payload formats, 1.0 is compatible with REST API / Proxy Lambda integration, but 2.0 has new 'cookies' property and overall structure is a bit cleaned up.
Closes #7477 
Added a global (provider level) configuration option and a test case:
```
provider:
httpApi:
payload: '2.0'
```
> feat(AWS HTTP API): configure payload format version

- docs/providers/aws/guide/variables.md
- lib/classes/Variables.js
- lib/classes/Variables.test.js
Aligned SSM variables parsing features to existing CloudFormation variable by enabling region selection.
You can now use `ssm.REGION:/path/to/param` in serverless.yml files like you could `cf.REGION:stackName.outputKey`.
Closes #7416 
```yml
service: new-service
provider:
name: aws
functions:
hello:
name: ${ssm.ap-northeast-1:/path/to/service/myParam}-hello
```
<details> …
> Region selection for SSM variables

- docs/providers/aws/events/sqs.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/sqs/index.js
- lib/plugins/aws/package/compile/events/sqs/index.test.js
I added Max retry to SQS because support just became available
Addresses #7012
functions:
compute:
handler: handler.compute
events:
- sqs:
arn: arn:aws:sqs:region:XXXXXX:stream/foo
batchSize: 10
maximumRetryAttempts: 10
<details>
</details>
> Adding in configurable MaximumRetryAttempts for SQS

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses.js
Closes #7575 
Pass down `allowCredentials` directive to method and integration responses: Enable browsers to read the request subsequent to the OPTIONS request without having to additionally specify the `Access-Control-Allow-Credentials` header.
```
functions:
test:
handler: functions/test.main
events:
- http:
method: get
path: api/test
cors:
origin: http://localhost:3000/
allowCredentials: true
```
The `Access-Control-Allow-Credentials` header should be configured in the method and integration responses.
Inside a browser, the same header should be present in the responses, not only to the preflight request but also to the subsequent request.
<details>
- `npm run …
> Pass allowCredentials directive to method and integration response (#7575)

- docs/providers/aws/cli-reference/rollback-function.md
- lib/plugins/aws/rollbackFunction/index.js
- lib/plugins/aws/rollbackFunction/index.test.js
- lib/plugins/rollback/index.js
Changed `version` option in rollback command to `function-version` to avoid confusion with `version` option from core
Closes #7645
```
service: test-rollback
provider:
name: aws
region: us-east-2
stage: ${env:NODE_ENV}
timeout: 900
functions:
app:
```
If you try to rollback with the following command before the fix, it will throw an error that `1 is not a sub command of version`
`npx serverless rollback -f app --version 1`
If you try this command after the fix, it will not throw that error
`npx serverless rollback -f app --function-version 1`
_Please note that this test keeps failing on my side (I'm using windows currently) `calls docker with packaged artifact`_
- I'm not sure if we should change/remove the shortcut `v`
<details>
<summary>Useful …
> Change version to function-version in rollback command

- lib/plugins/aws/package/compile/events/eventBridge/index.js
- lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Closes #7643 
On my project, I deployed a stack with 20+ lambdas connected to EventBridge and ran into a "Maximum policy size" error during deployment for the IamRoleCustomResourcesLa policy.
Upon inspection, I found that a policy for event bus creation/deletion is duplicated for each lambda. I managed to reduce the size of the custom resources policy  by ~30% by removing this duplication (in the case where it contains only lambdas using event bridges).
```
service:
name: serverless-issue-7643
package:
exclude:
- .git/**
- .gitignore
plugins:
- serverless-webpack
provider:
name: aws
region: eu-west-2
stage: ${opt:stage, 'dev'}
usagePlan:
quota:
limit: 5000
offset: 2
period: MONTH
throttle:
burstLimit: 200
rateLimit: 100
functions:
test1:
handler: test.handler
events:
- …
```
> Filter out duplicate create/delete event bus custom policies

- docs/providers/aws/guide/variables.md
- lib/classes/Variables.js
- lib/classes/Variables.test.js
Added syntax matcher for true|false bool in overwrite syntax.
Wanted to include int overwrite syntax as well, but a similar pattern for int brakes 40+ tests, I have to rethink the way to do it for this primitive.
Closes #7462 
You can run `sls print` with the following `serverless.yml` and see the correct output :
```yml
service:
name: test
plugins:
- serverless-webpack
provider:
name: aws
functions:
hello:
events:
- http:
method: get
path: hello
enabled: ${self:custom.doesnotexist, false}
```
and expect to see :
```yml
service:
name: test
plugins:
- serverless-webpack
provider:
name: aws
functions:
hello:
events:
- http:
method: get
path: hello
enabled: false
```
<details>
<summary>Useful …
> Implement bool primitive overwrite

- docs/providers/aws/cli-reference/rollback-function.md
- lib/plugins/aws/rollbackFunction/index.js
- lib/plugins/rollback/index.js
Removed `-v` shortcut for `function-version` as it's till confused with `-v` for version
Closes #7645
<details>
</details>
**_Is it a breaking change?:_** YES
> Remove -v from rollback command

- lib/plugins/aws/lib/monitorStack.js
Conditional made impression that `stackLatestError` is optional. While in body of it we may see it's required.
Updated conditional to better reflect the intention
> Refactor conditional logic flaw in deployment monitoring logic

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Modify CORS header validation to accept single string value
Closes #7652
```yml
service: test-service
provider:
name: aws
functions:
hello:
events:
- http:
path: product/{id}
method: get
cors:
origin: '*' # <-- Specify allowed origin
headers: '*'
allowCredentials: false
```
Running `npx serverless deploy` shouldn't throw an error `CORS header values must be provided as an array ...`
<details>
- `npm run prettify:updated` --> Prettify all the updated …
> Modify cors headers validation to accept single value

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
So far `updateStage` logic was invoked also when it shouldn't be applied, and that produced different issues.
This implementation ensures that `updateStage` logic applies only if Rest API is defined in top level stack and has also deployment configured (so is actually deployed with a stack deployment).
This will bring regression to users which eventually had REST API defined in a nested stack, but such configuration worked so far only by blind assumption on settings in `serverless.yml`, and cannot be resolved easily directly from a nested CF stack.
I feel it's more important to fix this broken cases, which were reported many times in different issues. 
Fixes #7186 #7650 #6699
Confirmed nothing is broken, also by running integration tests
> Ensure to update API Gateway stage only for deployed API's

- .gitignore
- lib/plugins/aws/package/compile/events/stream/index.js
This will fix below minor bug in event stream mapping.
**Issues it will resolve**
1. In the event of stream if i want to specify `maximumRetryAttempts` to `0` then i can't due to falsy condition of 0 in code. And
2. Once i set `bisectBatchOnFunctionError` to `true` and again if i want to make it `false` then i am not able to do that due to falsy condition of the code.
When this merge request will be approved then we will able to define mapping of stream event
`maximumRetryAttempts` and `bisectBatchOnFunctionError` to `0` and `false` respectively.
**Is this ready for review?: Yes
Is it a breaking change?: NO**
> Updating stream event properties "MaximumRetryAttempts" & "BisectBatchOnFunctionError" when value is falsy.

- docs/providers/aws/events/cloudfront.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/cloudFront/index.js
Currently, Lambda@edge implementation is missing the `includeBody` option in `serverless.yml`
```
functions:
myLambdaAtEdge:
handler: myLambdaAtEdge.handler
events:
- cloudFront:
eventType: viewer-response
includeBody: true
origin: s3://bucketname.s3.amazonaws.com/files
```
<details>
</details>
> Add `includeBody` param for Lambda@edge

- lib/plugins/aws/customResources/generateZip.js
In case of custom resource lambda packaging process being stopped in a middle, we were left with broken zip that was accepted for further deployment.
Fix is to generate zip to temporary directory and move it once generation of archive is finalized
Closes: #7242
> Fix generation of custom resource lambda zip

- docs/providers/google/guide/credentials.md
- Change [https://www.serverless.com/framework/docs/providers/google/guide/credentials#enable-the-necessary-apis](https://www.serverless.com/framework/docs/providers/google/guide/credentials#enable-the-necessary-apis) page.
In my change, user can copy api name and serach api.  
For example, when search `Stackdriver Logging`, result is `No results found`.  
So I thought, docs should be written real api service name.  
With my change, user can access the API directly by searching for the API name in the docs.
> change api name for serachable

- lib/classes/PluginManager.js
- lib/classes/Service.js
- lib/classes/Variables.js
- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/info/getApiKeyValues.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/utils/findReferences.js
- lib/plugins/plugin/install/install.js
- lib/plugins/plugin/uninstall/uninstall.js
- lib/plugins/print/print.js
- lib/utils/config/index.js
- lib/utils/getCommandSuggestion.js
- lib/utils/yamlAstParser.js
See https://github.com/serverless/serverless/pull/7680#discussion_r422044932
Let's minimize lodash dependency where native ways are available.
* Better performance thanks to native implementation
* Smaller bundle size thanks to depend only small portion of lodash (e.g. `require('lodash.pick')`)
> Replace _.isArray with native Array.isArray

- docker-compose.yml
- docs/providers/aws/examples/hello-world/csharp/README.md
- lib/plugins/create/templates/aws-csharp/Handler.cs
- lib/plugins/create/templates/aws-csharp/aws-csharp.csproj
- lib/plugins/create/templates/aws-csharp/build.cmd
- lib/plugins/create/templates/aws-csharp/build.sh
- lib/plugins/create/templates/aws-csharp/serverless.yml
There is no issue for this pull request, but suffice to say it updates the aws-csharp template from 2.x (which is no longer supported by Microsoft) to 3.1 (which has LTS support) [inline with the AWS 3.1 support post](https://aws.amazon.com/blogs/compute/announcing-aws-lambda-supports-for-net-core-3-1/).
> Update aws-csharp to .NET Core 3.1

- package.json
Upgraded `archiver` from 1.3.0 to 3.1.1. Package remains within outdated list. Package latest version 4 is not compatible with Node 6.
Closes: #7685
> Upgrade archiver to 3.1.1

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Custom stack name should be used only for naming CloudFormation stack, however with #7357 it was used to generate role and policy name, and that was precedence.
It also imposed a various issues for users (as outlined in #7357 comments)
This PR reverts that behavior
> Fix IAM role and policy name resolution

- lib/utils/standalone-patch.js
Closes #7696 
It appears workaround was not prepared to work on Windows, hence it failed over there.
> Fix `pkg` issue workaround, so it works on Windows

- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/updateStack.js
- lib/plugins/aws/lib/updateStack.test.js
This change allows parameters to be passed in leveraging plugins.  There are occasions when parameters offer a better option than directly compiling values into the cloudformation.  One example of this is passwords.   If a password were embedded into a cloudformation, anyone with read access could see the password.  Using a parameter for this field with NoEcho, will result in the parameter being masked.
This PR allows plugins to leverage the cloudformation parameters, which helps with specific use cases where embedding values (such as passwords) is not preferable and can create security issues in accounts.
Closes #No Bug
This enables plugins, and is not directly accessible by the yml file.
<details>
- `npm run test:ci` --> Run all validation checks on …
> Allow parameters to be passed in by plugins

- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/package/compile/events/cloudFront/index.test.js
- tests/fixtures/functionCloudFront/index.js
- tests/fixtures/functionCloudFront/serverless.yml
> Ensure lambda edge has no vpc or env

- lib/utils/resolveCliInput.js
- lib/utils/resolveCliInput.test.js
Closes: #7683
If multiple `--config` options are provided, crash with `ServerlessError`
example
`node .\bin\serverless.js --config hello --config world`
Error
```
Serverless Error --------------------------------------- 
Got 2 config paths: [hello, world].Expected single value 
Get Support -------------------------------------------- 
Issues:        forum.serverless.com
```
> Display error message on duplictate conf path

- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Fixes a bug introduced in PR #7720  which closes issue #7599 
In `mergeIamTemplates.js` LogGroup Resource creation is skipped if `disableLogs` is `true`. In `compile/function/index.js` the `LogGroup` still apears in `DependsOn` section
This caused a crash error on `deploy` command, in the `validating template` stage
> Fix disabled LogGroup exists in DependsOn

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
In setup where resources are distributed into nested stacks, API Gateway resource may not be present in main stack.
With https://github.com/serverless/serverless/pull/7663 we've changed behavior, and assume there's no API Gateway if it doesn't appear in main stack. Still it broke for services relying on e.g. `serverless-plugin-split-stacks` plugin.
This patch ensures that if there are `http` events configured we unconditionally attempt to find the Rest API Id and it's deployment.
Additionally improved configuration check to be based on deployment id and not just rest API id (if there's no deployment, then we're also incapable on applying any stage settings)
> Fix handling of stage specific setting for split stacks case

- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/checkForChanges.test.js
Closes: #6030
`checkIfDeploymentIsNecessary` in `checkForChanges` now consider user-packed artifact from `package.artifact`, so deployment will not be skipped when local artifact is updated.
> checkForChanges should consider user-defined artifact

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/invokeLocal/index.test.js
Use the recommended docker arg to mount `/var/task` as read only to
improve time spent running the command.
See https://github.com/lambci/docker-lambda#running-lambda-functions
**Without this commit**
```
$ time sls invoke local -f create --docker
REPORT RequestId: 95<SNIPPED> Init Duration: 24701.33 ms
real	0m39.686s
user	0m12.625s
sys	0m3.083s
```
**Using this commit with /var/task:ro,delegated**
```
$ time sls invoke local -f create --docker
REPORT RequestId: 59<SNIPPED> Init Duration: 12088.04 ms
real	0m24.492s
user	0m12.293s
sys	0m2.897s
```
Mount docker volume read-only when running `sls invoke local --docker`
Closes #7609 
run `time sls invoke local --docker` with and without this commit to observe performance improvements
<details>
- `npm run …
> Fixes serverless#7609 - Improve invoke local docker performance

- lib/classes/PluginManager.js
- lib/plugins/aws/common/lib/artifacts.js
- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/utils/findReferences.test.js
- lib/plugins/package/lib/zipService.js
See https://github.com/serverless/serverless/pull/7680#discussion_r422044932
Let's minimize lodash dependency where native ways are available.
* Better performance thanks to native implementation
* Smaller bundle size thanks to depend only small portion of lodash (e.g. `require('lodash.pick')`)
> Replace lodash utility with String native methods

- docs/providers/aws/guide/variables.md
- lib/classes/Variables.js
- lib/classes/Variables.test.js
Currently, when you import a `.js` file in your configuration, serverless only supports functions.  This change also allows referencing non-function exports from a `.js` file.
Closes #7443 
`config.js`
```
module.exports = {
foo: 'bar',
doesWork: true
}
```
```
service: test
provider:
name: 'test'
custom:
from-js: ${file(./config.js)}
```
Command:
```
sls print
```
Expected output:
```
service: test
provider:
name: test
custom:
from-js:
foo: bar
doesWork: true
```
<details>
- `npm run prettier-check:updated` --> Check if updated files adhere to …
> Support non-function exports when including variables from js files

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
Use API Gateway response contentHandling property only for integration responses with 2XXs status codes
Closes: #7705
> fix: Use API Gateway response contentHandling property only for integration responses with 2XXs status codes

- bin/serverless
- docs/deprecations.md
Deprecate `bin/sererverless` in favor of `bin/serverless.js`
It's a first _deprecation_ to pave path for further deprecations in a project (which will be used to ease migration between different major releases, as documented here: https://github.com/serverless/serverless/issues/7422)
/cc @AhmedFat7y
> Deprecate bin/serverless binary

- lib/classes/YamlParser.js
- package.json
Closes: #7691 
Had to replace `options.relativeBase` with `options.location` for relative reference resolution (cf https://github.com/whitlockjc/json-refs/blob/master/RELEASE_NOTES.md#v300-2017-04-25). Location uses the root file location instead of the base path, thus removing parentDir computation part.
> Update json-refs lib

- lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
- lib/plugins/aws/utils/findReferences.test.js
> Replace lodash _.every(array) with native Array.every

- lib/classes/PluginManager.js
- lib/classes/Variables.js
- lib/plugins/aws/deploy/lib/createStack.js
- lib/plugins/aws/deploy/lib/extendedValidate.js
- lib/plugins/aws/lib/updateStack.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/lib/generateCoreTemplate.js
- lib/plugins/aws/package/lib/saveServiceState.js
- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/plugin/install/install.test.js
- lib/utils/yamlAstParser.test.js
> Replace _.assign and _.extend with Object.assign

- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- lib/plugins/package/lib/zipService.js
> refactor(lodash): Replace _.filter with array.filter

- package.json
While v8 sort of works with Node.js v6, this version of Node.js is not advertised as supported by uuid v8, and we received reports that this upgrade is problematic (e.g. #7777)
Fixes #7718
> Downgrade uuid to v3

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
#6112 
I have changed code to be able to enable detailed cloud watch metrics for api gateway.
In my PR, if you define serverless.yml like below, api gateway enables detailed cloud watch metrics.
```
:
provider: aws
metrics:
restApi: true
:
```
However, I'm not sure this format in serverless.yml is really correct, so please let me know if I did something wrong.
> fix(AWS API Gateway) Enable detailed CloudWatch Metrics

- lib/classes/Utils.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/provider/awsProvider.test.js
> Replace lodash _.size with native array length & object.keys length

- docs/providers/aws/events/apigateway.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
This update makes it easier to use a Cognito User Pool as an APIGW authorizer when the pool is created in the same service.
Before this fix, it required this ([suggested here](https://github.com/serverless/serverless/issues/3212#issuecomment-450574093)):
```yaml
...
functions:
getStuff:
handler: path/to/handler
events:
- http:
path: /path/to/whatever
method: get
authorizer:
type: COGNITO_USER_POOLS
authorizerId:
Ref: ApiGatewayAuthorizer
...
resources:
Resources:
CognitoUserPool:
Type: AWS::Cognito::UserPool
Properties:
UserPoolName: whatever
ApiGatewayAuthorizer:
DependsOn:
- ApiGatewayRestApi
Type: AWS::ApiGateway::Authorizer
Properties:
Name: whatever
IdentitySource: method.request.header.Authorization
RestApiId:
Ref: ApiGatewayRestApi
Type: COGNITO_USER_POOLS
ProviderARNs:
- …
```
> Make it easier to use a CognitoUserPool authorizer when the pool is configured in the same service.

- docs/providers/aws/events/http-api.md
- lib/plugins/aws/info/getStackInfo.js
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
This allows to add external authorizer to `httpApi` event in similar manner to `http` event. 
Closes: #7598
> feat(httpApi): external authorizer

- lib/plugins/aws/info/getApiKeyValues.js
Regression introduced by #5982, with which new format was introduced but resolution of API key names was not updated to it.
Exposed by changes introduced with #7748 in CI run: https://travis-ci.org/github/serverless/serverless/jobs/692075909
> Fix AWS API Gateway key names resolution

- lib/classes/PluginManager.js
- lib/plugins/aws/provider/awsProvider.js
- lib/utils/log/fileLog.js
> Replace lodash _.join with native array.join

- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/plugin/install/install.js
> refactor: Replace `_.isNil(value)` with `value == null`

- lib/classes/PluginManager.js
- lib/classes/Variables.js
> refactor: Replace `_.isFunction(value)` with `typeof value === 'function'`

- lib/classes/PluginManager.js
- lib/classes/Utils.js
- lib/classes/Variables.js
- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/info/getApiKeyValues.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/alexaSkill/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/websockets/lib/validate.js
- lib/plugins/print/print.js
> refactor: Replace `_.isString(value)` with `typeof value === 'string'`

- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js
> Replace lodash _.first with native array[0]

- lib/classes/PluginManager.js
- lib/classes/Variables.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/deployList/index.js
- lib/plugins/aws/info/getApiKeyValues.js
- lib/plugins/aws/lib/cloudformationSchema.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/lib/generateCoreTemplate.js
- lib/plugins/aws/utils/findAndGroupDeployments.js
- lib/plugins/package/lib/packageService.js
Some variables are enclosed in `(var || [])` to avoid *cannot read property map of undefined*. The test results are OK, but I'm not sure about the probability of the other variables being `undefined`. Please tell me if they need to be enclosed as well.
> Replace _.map with array.map

- docs/providers/aws/events/streams.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
Added support for property `MaximumRecordAgeInSeconds` to be used in DynamoDB and Kinesis streams. [Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-maximumrecordageinseconds)
Addresses issue https://github.com/serverless/serverless/issues/7042
> feat: Add support for maximumRecordAgeInSeconds property

- docs/providers/aws/examples/hello-world/README.md
Hi, I found a link to ruby example of hello world is missing. So I added it!
> docs: add link to ruby example

- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
Improves leaky logic introduced with https://github.com/serverless/serverless/pull/5982 exposed by regression introduced with https://github.com/serverless/serverless/pull/7827
Closes: #7844
> AWS API Gateway: Fix handling of usagePlan array

- lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
CloudFormation resources dependency chain was not marked as expected, ntot having that caused race condition where route response could have been created before deployment.
Exposed by randomly appearing CI fails as: https://travis-ci.org/github/serverless/serverless/jobs/699675795
After contacting AWS support, they indicated that we miss that setting
> AWS Websockets: Fix response resource handling

- docs/providers/aliyun/guide/functions.md
AliYun->Guide->function getting the POST body is incorrect. I have updated the documentation
Update the messages below
Is this ready for review?: YES
Is it a breaking change?: NO
> Incorrect Documentation for AliYun

- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/create/create.js
Addresses #7747
@medikoo Hello, sorry for previous PR. I closed previous PR. Could you check for me?
> Replace toString

- lib/classes/PluginManager.js
- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/rollback/index.js
Replace `_.some` with `Array.some` whenever possible
This PR does not remove ALL `_.some` usage - there are still 3 instances of using `_.some` with objects that I didn't rewrite because they will be very easy to address with `Object.values` - that will be unblocked with https://github.com/serverless/serverless/issues/7362
If you strongly feel that this PR should remove all usages of `_.some` - I'm happy to give it a try :100: 
Addresses: https://github.com/serverless/serverless/issues/7747
> chore: reduce _.some usage

- lib/classes/CLI.js
- lib/classes/PluginManager.js
- lib/classes/Service.js
- lib/plugins/aws/deploy/lib/extendedValidate.js
- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/info/display.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- lib/plugins/aws/package/compile/events/schedule/index.js
- lib/plugins/aws/package/compile/events/sns/index.js
- lib/plugins/aws/package/compile/events/sqs/index.js
- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/websockets/lib/validate.js
- lib/plugins/aws/package/lib/mergeIamTemplates.test.js
- lib/plugins/aws/provider/awsProvider.js
Replaced all occurrences of ```_.has(object, property)``` with ```object.property```.
While trying to keep behaviour the same, in some cases ```object.property``` cannot be used. 
See the changes in:
• lib/plugins/aws/provider/awsProvider.js 
• lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
```javascript
// This is false, caused by if(null)
if(obj.prop)
// This is true, since it only checks if 'prop' exists
if(_.has(obj, 'prop'))
// This is true, since it only checks if 'prop' exists
if('prop' in obj)
```
I don't know if those two cases are isolated or not, but maybe another idea would be to replace ```object.property``` with ```'property' in object```.
> Replaced _.has(object, property) with object.property

- docs/deprecations.md
- lib/plugins/aws/package/compile/events/httpApi/index.js
> Added deprecation warning for when aws http api payload version is not set

- CONTRIBUTING.md
- lib/Serverless.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/utils/logDeprecation.js
- lib/utils/logDeprecation.test.js
- package.json
External plugins should also be able to signal deprecated features, after that is in, it'll be possible via `serverless.logDeprecation(code, message)`
Used by https://github.com/serverless/enterprise-plugin/pull/449
> Expose severless.logDeprecation for plugins

- lib/classes/CLI.js
- lib/classes/CLI.test.js
Closes: #7944 (regression introduced with #7924)
Additionally `--help-interactive` was also configured to be only a top level command param
> CLI: Ensure `--version` is only top level command option

- docs/providers/aws/guide/serverless.yml.md
This doesn't actually work currently. See #5472.
Alternatively: Update the framework to really support this option. See [comment here](https://github.com/serverless/serverless/issues/5472#issuecomment-660499909).
Addresses: #5472
> Remove unsupported provider.reservedConcurrency option

- docs/README.md
- docs/dashboard/README.md
- docs/dashboard/access-roles.md
- docs/dashboard/cicd/README.md
- docs/dashboard/cicd/running-in-your-own-cicd.md
- docs/dashboard/monitoring/alerts.md
- docs/dashboard/parameters.md
- docs/dashboard/profiles.md
- docs/dashboard/safeguards/README.md
- docs/dashboard/safeguards/available.md
- docs/getting-started.md
- docs/providers/aws/cli-reference/slstats.md
This updates the docs to use the new dashboard link, app.serverless.com, replacing the old dashboard link, dashboard.serverless.com. No other changes are included in this PR. Making this a draft PR until we are ready to launch the new dashboard.
> docs: Update links to app.serverless.com

- lib/plugins/create/templates/aws-clojurescript-gradle/scripts/node_repl.clj
- lib/plugins/create/templates/aws-clojurescript-gradle/src/main/clojurescript/serverless/functions.cljs
Closes: #7960
invoke local works fine with the change.
```
% sls invoke local -f hello
#js {:awsRequestId id, :invokeid id, :logGroupName /aws/lambda/aws-clojurescript-gradle2-dev-hello, :logStreamName 2015/09/22/[HEAD]13370a84ca4ed8b77c427af260, :functionVersion HEAD, :isDefaultFunctionVersion true, :functionName aws-clojurescript-gradle2-dev-hello, :memoryLimitInMB 1024, :succeed #object[succeed], :fail #object[fail], :done #object[done], :getRemainingTimeInMillis #object[getRemainingTimeInMillis]}
{
"statusCode": 200,
"headers": {
"Content-Type": "text/html"
},
"body": "<h1>Hello, World!</h1>"
}
% sls invoke local -f now
#js {:awsRequestId id, :invokeid id, :logGroupName /aws/lambda/aws-clojurescript-gradle2-dev-now, :logStreamName 2015/09/22/[HEAD]13370a84ca4ed8b77c427af260, …
```
> Use dayjs instead of moment in the aws-clojurescript-gradle template to fix an invocation error.

- lib/plugins/aws/invokeLocal/index.js
The change helps us to narrow down issues like #4415.
Addresses:  #4415
We get the following error messages.
```
% sls invoke local -f hello
Serverless: Building Java bridge, first invocation might take a bit longer.
Exception -----------------------------------------------
'Failed to build the Java bridge. exit code=1 signal=null'
```
```
% env SLS_DEBUG='*' sls invoke local -f hello
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load …
```
> Improve java invoke-bridge build error handling

- docs/providers/aws/events/cloudfront.md
Updated supported lambda@edge runtimes to match linked AWS docs, adding Python 3.8 and Node.js 12.x, and removing Node.js 8.10 as deployments and updates are no longer possible for functions in Node.js 8.10.
> Update Lambda@Edge supported runtimes

- lib/plugins/aws/provider/awsProvider.js
It should not be applied if nslookup command is not found
Closes: #7978
> Fix aws-sdk authentication bug workaround

- docs/deprecations.md
- docs/providers/aws/guide/functions.md
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Adds support for defining `maximumEventAge` and `maximumRetryAttempts` directly on function level and deprecates the configuration on destinations.
Closes: #7678
Open questions:
- I wasn't sure about the approach to deprecation - I went with two separate deprecations for each parameter, but maybe it would make more sense to combine it into one instead? I would love to get your opinion on this one
- I followed the previous approach where I didn't notice any validation of the provided input e.g. if `maximumEventAge` is between 60 seconds and 6 hours. Would it make sense to add such validation or it's unnecessary at this point?
> Add support for `maximumEventAge` and `maximumRetryAttempts` directly on function instead of destinations

- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Minor cleanup, so unrelated properties are not created and they do not affect upcoming Schema validation functionality (implemented at #7335 )
> Cleanup for schema validation

- commitlint.config.js
- lib/classes/ConfigSchemaHandler/index.js
- lib/classes/ConfigSchemaHandler/normalizeAjvErrors.js
- lib/configSchema.js
- tests/fixtures/configSchemaExtensions/serverless.yml
- Recognize `frameworkVersion` and `disabledDeprecations` top level properties
- Ensure errors normalization works with externally referenced types (workaround https://github.com/ajv-validator/ajv/issues/1255)
- Ensure to normalize `oneOf` schema errors (aside of `anyOf` which were already properly normalized)
> Fix schema validation missings

- docs/providers/aws/guide/services.md
Found out the template list doesn't have `aws-go-mod` yet.
> Add aws-go-mod on available templates

- lib/plugins/aws/provider/awsProvider.js
In the AWS provider, the `resourcePolicy` must be an array. If you paste a resource policy from the console, your stack will fail to create.
Closes: #7795 
Addresses: #8018
> fix(Config Schema): validate resourcePolicy is array

- lib/plugins/create/templates/aws-fsharp/Handler.fs
The new SystemTextJson serialization requires a parameterless ctor
On a record that is provided by the CLIMutable attribute
Closes: #8070
> fsharp template - the new SystemTextJson serialization requires a parameterless ctor

- lib/classes/ConfigSchemaHandler/index.js
Closes: #8084 
Additionally all configuration errors are reported as _warnings_, as by default they behave as warnings (let process continue), while "error" gives an impression action was stopped.
> Config Schema: Report configuration errors as warnings

- lib/plugins/package/lib/packageService.js
> Fix Automatically exclude aws-sdk from Node.js lambda bundles

- lib/plugins/aws/package/compile/events/s3/index.js
Q1: Provide link to corresponding issue
No issue - trivial change. Fixing typo in variable name: 'provderS3' -> 'providerS3'
> fix typo in 'provider' in var name

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
- bin/serverless.js
- package.json
- scripts/serverless.js
> Drop support for Node.js versions below v10

- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
Removes support and deprecation message for `maximumEventAge` and `maximumRetryAttempts` set on `function.destinations` level. 
I've decided to leave the note in `docs/deprecations.md` as I'm not sure if the intention is to keep that historic information or clean it up and only show "current" deprecations. Please let me know if it should be removed.
Closes: #8119
> chore(aws): remove deprecated support for maximumEventAge & maximumRetryAttempts on destination

- docs/deprecations.md
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
- Changed default payload version to 2.0
- Removed deprecation warning from both code & documentation
Closes: #7917
> Switch default payload mode to 2.0

- lib/plugins/package/lib/packageService.js
Reverts serverless/serverless#8103
Due to reasons mentioned here: https://github.com/serverless/serverless/issues/8096#issuecomment-682219305
Including `aws-sdk` as dependency signals intent to bundle it
> Revert "Fix Automatically exclude aws-sdk from Node.js lambda bundles"

- docs/providers/aws/guide/plugins.md
- lib/classes/ConfigSchemaHandler/index.js
- lib/classes/Service.js
- lib/configSchema.js
- lib/configSchema.test.js
- lib/plugins/aws/provider/awsProvider.js
- package.json
- tests/mocha-reporter.js
- Ensure to validate direct user config input (where applicable)
- Allow providers to provide its own definitions. Make AWS specific definitions to be defined by AWS provider
- Define `resources` fully in context of provider (move current definition to AWS provider context)
> Config schema improvements

- docs/providers/aws/events/apigateway.md
The line 1543 and 1544 of `docs/provider/aws/events/apigateway.md` were too much indented and set inside the `authorizerId` key instead of `authorizer` key resulting as an error when deploying a function with scopes as described in the example.
Removing indentation to match with the expected syntax.
Closes: #8078
> Fix bad indentation in Share Authorizer docs

- lib/plugins/create/templates/google-nodejs/serverless.yml
Updated NodeJS to 10 version. NodeJS 8 is deprecated in Google Cloud Functions.
Closes: #8151
> #8151 Update google-nodejs template

- lib/classes/Service.js
- lib/classes/Service.test.js
- test/integration-all/file-system-config/tests.js
Some of our tests (https://github.com/serverless/serverless/pull/8163/checks?check_run_id=1057358350)  in v2 pre-release branch got broken when `frameworkVersion` was [unconditionally added](https://github.com/serverless/test/commit/a35fb51f5f0809a46823bc55f025ae0cb01c0041) to serverless configurations.
It's due to pre-releases not being matched by `*` version range (reason unknown -> https://github.com/npm/node-semver/issues/329)
This patch ensures, that `*` matches pre-releases as well.
Additionally provided workaround for EFS integration test CI fail:  https://github.com/serverless/serverless/runs/1056731807
> Fix handling of pre-releases in frameworkVersion validation

- docs/deprecations.md
- lib/plugins/aws/package/compile/events/httpApi/index.js
> AWS HTTP API: Convert "timeout" usage warnings to deprecations

- package.json
Validated the breaking changes introduced in https://github.com/sindresorhus/boxen/releases/tag/v4.0.0 and they don't affect `serverless@v2`.
Addresses: #7486
> build(dependency): upgrade to boxen@v4.2.0

- docs/deprecations.md
- lib/classes/Service.js
It was internally decided to not imply this requirement. Instead `frameworkVersion` recommendation is shown when Framework is used in _debug_ model.
/cc @ac360
> Revert from `frameworkVersion` requirement

- docs/deprecations.md
- lib/Serverless.js
- lib/Serverless.test.js
> Fallback to service local `serverless` installation by default

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/package/lib/packageService.test.js
- package.json
> Drop mkdrip dependency

- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
- lib/plugins/aws/provider/awsProvider.js
BREAKING CHANGE:
`timeout` setting as configured directly for `httpApi` event,  is no longer supported.  Timeout value is now unconditionally resolved from  function timeout setting. It's to guarantee that configured endpoint has necessary room to process function invocation
Closes: #8087
> AWS HTTP API: Drop support for `timeout` setting

- lib/Serverless.js
- package.json
It's replaced with backend notifications, which are more powerful as through which we can also notify about updates across different major releases
>  Remove "update-notifier"notifications

- lib/classes/Service.test.js
- lib/plugins/aws/provider/awsProvider.js
Adds schema for the `resources` top-level element when using the AWS provider.
Does not add tests as directed in #8051. I've run a small manual test.
Addresses: #8118 (flags input issue but error could be better if validation was done before `mergeArrays`, see [comment](https://github.com/serverless/serverless/issues/8118#issuecomment-681058721))
Closes: #8014 (does not cover non-AWS providers)
> feat(aws): schema for `resources` when using AWS provider

- lib/plugins/aws/invokeLocal/fixture/handler.rb
- lib/plugins/aws/invokeLocal/index.test.js
- lib/plugins/aws/invokeLocal/runtimeWrappers/invoke.rb
This property was previously missing from the fake lambda context when running ruby functions locally.
Ref: https://docs.aws.amazon.com/lambda/latest/dg/ruby-context.html
To recreate:
* create a new serverless ruby project, e.g.: `serverless create --template aws-ruby --path sls-ruby-fix`
* add the following in to the generated "hello" function: `puts "deadline_ms: #{context.deadline_ms}"`
Prior to this fix, it will fail with `undefined method `deadline_ms' for #<FakeLambdaContext:0x00007ffcf115e078> (NoMethodError)`
After this fix, the deadline will be printed to stdout.
> Add "deadline_ms" to the local context

- CONTRIBUTING.md
The path in the link previously had a trailing 's'.
> Fix link to test doc

- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
`0` is a value supported by AWS, yet it was not recognized on our side
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-maximumbatchingwindowinseconds
> AWS Stream: Fix support for `batchWindow: 0`

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
Closes: #8191
This change includes the following:
* a `toStartCase()` method was added to the `naming` object (under `plugins/aws/lib`) to replace the regular usage of `_.startCase()`. This method returns a string in title/start case, without replacing non-alpha-numeric characters with whitespace. If an alternative solution is preferable (e.g. one that doesn't use the existing `_.startCase()` method), I'm definitely open to changing this.
* `naming.getModelLogicalId()` was also updated to use the method mentioned above, and a simple unit test was added to cover the case detailed in #8191
* Since this might affect AWS functionality, I went ahead and ran the AWS integration tests (which passed).
Feel free to point out any issues or suggestions – Thanks! 🙂
> update naming.getModelLogicalId() to remove whitespace in contentType (plugins/aws/lib/naming)

- CHANGELOG.md
This change fixes a typo in the word 'maintenance' in changelog.md
> Fix typo in the word 'maintenance' in changelog

- lib/plugins/interactiveCli/initializeService.js
- lib/utils/getServerlessConfigFile.js
Memoize by instance, memoizing by service name doesn't work when test configuration changes in same process
Addresses issue reported here: https://github.com/serverless/serverless/pull/8212#discussion_r486904079
> Fix config file resolution memoization

- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
> Stream schema

- package.json
As we dropped support for Node.js v6, we can safely upgrade to latest version
> Upgrade "uuid" to v8

- package.json
> Upgrade "archiver" to v5

- package.json
> Upgrade "chalk" to v4

- package.json
> Upgrade "download" to v8

- package.json
> Upgrade "filesize" to v6

- package.json
> Upgrade "get-stdin" to v8

- package.json
> Upgrade "is-docker" to v2

- lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js
- lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test.js
> aws cloudwatchEvent event schema

- package.json
> Upgrade "p-limit" to v3

- lib/utils/getCommandSuggestion.js
- package.json
As `fast-levenshtein` was upgraded to use `fastest-levenshtein` under the hood
> Switch from "fast-levenshtein" to "fastest-levenshtein"

- lib/classes/Utils.js
- lib/classes/Utils.test.js
- package.json
> Upgrade "fs-extra" to v9

- package.json
> Upgrade "semver" to v7

- package.json
> Upgrade "untildify" to v4

- package.json
Apparently they're no longer used
> Remove no longer used dependencies

- package.json
> Upgrade "yargs-parser" to v20

- docs/providers/aliyun/guide/services.md
- docs/providers/aws/guide/serverless.yml.md
- docs/providers/aws/guide/services.md
- docs/providers/azure/guide/function-apps.md
- docs/providers/azure/guide/serverless.yml.md
- docs/providers/cloudflare/guide/services.md
- docs/providers/google/guide/services.md
- docs/providers/knative/guide/services.md
- docs/providers/kubeless/guide/services.md
- docs/providers/openwhisk/guide/serverless.yml.md
- docs/providers/openwhisk/guide/services.md
- docs/providers/tencent/guide/services.md
It was overlooked in v2 branch.
Additionally improved style of semver version ranges
> Ensure to reference v2 in `frameworkVersion` in docs

- lib/configSchema.js
> fix(Config Schema): Add enhanced object syntax for plugins

- lib/plugins/aws/provider/awsProvider.js
Allow to use CF functions to define `arn` for `fileSystemConfig`. `Ref` is not supported because it does not return ARN for EFS Access Point. Reference doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-accesspoint.html
Closes: #8189
> feat(aws): add support for cf functions for fileSystemConfig

- docs/deprecations.md
- lib/plugins/aws/package/lib/mergeCustomProviderResources.js
Add deprecation for extending nonexistent resources in `resources.extensions`.
Addresses: #8141
> chore(aws): add deprecation for extending nonexistent resources

- lib/classes/ConfigSchemaHandler/index.js
Issue was exposed by CI fail: https://github.com/serverless/serverless/runs/1134654637
(in test we reset `websocketApiId` with a `null` value: https://github.com/serverless/serverless/blob/e1ca63c06a824e18fdd92f5c6c3efbf7f5f644d2/test/integration/websocket.test.js#L151 which seems as totally valid approach)
Workaround to: https://github.com/ajv-validator/ajv/issues/1287
> Config Schema: Treat `null` or `undefined` as lack of value

- lib/plugins/aws/package/compile/events/sqs/index.js
- lib/plugins/aws/package/compile/events/sqs/index.test.js
> aws sqs event schema

- lib/plugins/aws/package/compile/events/cloudWatchLog/index.js
- lib/plugins/aws/package/compile/events/cloudWatchLog/index.test.js
- lib/plugins/aws/provider/awsProvider.js
> Aws cloudwatchlog event schema

- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Closes: #8025 
A few things I'm not sure of:
1. Is the regex for pathPattern necessary? I derived it from [this doc](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesPathPattern)
2. Should I add the full schema for [origin](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html)? It will be quite verobse...
2. Should I add the full schema for [behavior](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html)? It will be quite verobse...
3. Will the [uri](https://github.com/serverless/serverless/compare/master...thewizarodofoz:aws-cloudfront-event-schema?expand=1#diff-13a25836cc7975b47c0e8dab6460 …
> Aws cloudfront event schema

- lib/classes/ConfigSchemaHandler/normalizeAjvErrors.js
- lib/classes/PluginManager.js
- lib/plugins/aws/deployFunction/index.js
- lib/plugins/aws/info/display.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/utils/findAndGroupDeployments.js
- lib/utils/analytics/generatePayload.js
Replace `_.values` with `Object.values` in order to reduce dependency on `lodash`
> chore: replace usage of _.values with Object.values

- lib/classes/ConfigSchemaHandler/index.js
- lib/classes/ConfigSchemaHandler/normalizeAjvErrors.js
- lib/classes/PluginManager.js
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/lib/mergeCustomProviderResources.js
- lib/plugins/package/lib/packageService.js
Replace `_.entries`, `_.entriesIn` and `_.toPairs` with `Object.entries` to reduce lodash usage.
Note about `toPairs`: I decided to not split it into multiple PRs as `toPairs` in lodash has the same functionality as `entries`. 
Note about `entriesIn`: There was only one instance of it and I didn't notice any use/reliance on prototypal inheritance for tags so I think it's safe to replace it with `Object.entries` as the only difference is in it not including inherited properties. 
> chore: replace _.entries, _.entriesIn and _.toPairs with Object.entries

- lib/classes/CLI.js
- lib/classes/PluginManager.js
- lib/classes/Service.js
- lib/plugins/aws/info/display.js
- lib/plugins/aws/lib/normalizeFiles.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/websockets/lib/validate.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/plugin/install/install.js
- lib/plugins/plugin/uninstall/uninstall.js
- lib/utils/getCommandSuggestion.js
Replace `_.forEach` with `Object.entries().forEach`  + one missed `toPairs` usage to reduce dependency on `lodash`.
Additional note: Unless I'm missing something, there are no instances of `_.each` left as well.
> chore: replace _.forEach with Object.entries().forEach

- docs/deprecations.md
- lib/configSchema.js
- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/provider/awsProvider.js
> Deprecate awsKmsKeyArn for provider and functoin kmsKeyArn

- lib/plugins/aws/package/compile/events/alexaSmartHome/index.js
- lib/plugins/aws/package/compile/events/alexaSmartHome/index.test.js
- lib/plugins/aws/provider/awsProvider.js
> alexa smart home event schema

- lib/classes/PluginManager.js
- lib/plugins/aws/utils/findReferences.js
Replace `_.forOwn` with `Object.entries().forEach` to reduce dependency on `lodash`.
> chore: replace _.forOwn with Object.entries().forEach

- lib/plugins/aws/provider/awsProvider.js
This enables the use of `Ref`, `Fn::Join`, `Fn::Sub` , `Fn::Import` and `Fn::GetAtt` when defining the `vpc.subnetIds` and `vpc.securityGroupIds`
Closes: #8282
> fix(Config Schema): Expand allowable types for vpc config

- docs/deprecations.md
- lib/plugins/aws/package/compile/events/alexaSkill/index.js
- lib/plugins/aws/package/compile/events/alexaSkill/index.test.js
Adds schema definition for `alexaSkill` event.
In addition, it also adds deprecation for defining `alexaSkill` with just an `alexaSkill` string. That configuration is not covered by schema as it would require a rewrite of current utility for defining event schemas. Related discussion in corresponding issue.
Closes: #8023
> feat(aws): add schema for `alexaSkill`

- lib/plugins/aws/package/compile/events/alb/lib/validate.js
Regression introduced with #8275
> AWS ALB: Ensure to treat `provider.alb.authorizers` as optional

- lib/plugins/aws/package/compile/events/sqs/index.js
- lib/plugins/aws/package/compile/events/sqs/index.test.js
Ensure that `EventSourceMapping` depends on provisioned alias if it exists. 
One question: do you think it makes sense to add an integration test with `provisionedConcurrency` as well? I reproduced/tested the fix based on adjusted existing SQS integration test which made me wonder about adding it permanently. 
Closes: #8249
> fix(AWS SQS): ensure sqs event depends on provisioned alias if needed

- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/provider/awsProvider.js
Addresses: https://github.com/serverless/serverless/issues/8285#issuecomment-700391139
Schema was relaxed to recognize all formats as supported for deployment. Improved validation at local invocation where unsupported format is approached
> Recognize deployment valid env variables format

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
- lib/plugins/aws/provider/awsProvider.js
> feat(AJV): Add Rest api logs definition

- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Addresses: #8025 (this is a minor bugfix related to PR #8250)
I noticed some `unsupported configuration format` warnings that occurred after #8250 with CloudFront events and specifically using `AllowedMethods`, `CachedMethods` and `ForwardedValues`:
So I used the example given [here](https://www.serverless.com/framework/docs/providers/aws/events/cloudfront/) to write a test that validates the config. 
Any feedback is welcome!
> Fix schema validation of CloudFront distribution config

- lib/plugins/aws/package/compile/functions/index.js
- lib/plugins/aws/package/compile/functions/index.test.js
- test/integrationPackage/cloudformation.tests.js
This change embeds an environment variable onto each lambda function with the value of the version config hash, ensuring that anytime the config hash changes, the resulting lambda configuration will be changed, meaning the Lambda::Version should always be successfully published.
Closes: https://github.com/serverless/serverless/issues/8251
> Add version digest as lambda env var

- lib/plugins/aws/package/compile/events/sns/index.js
- lib/plugins/aws/package/compile/events/sns/index.test.js
> SNS displayName as optional property when used with topicName

- lib/plugins/aws/package/compile/events/sns/index.js
Fixes regression introduced with #8323 
There are valid scenarios where `arn` and `topicName` should be provided
> Config Schema: Fix SNS event schema (allow both `arn` and `topicName` in `sns` event)

- test/fixtures/provisionedConcurrency/core.js
- test/fixtures/provisionedConcurrency/serverless.yml
- test/integration/provisionedConcurrency.test.js
Add integration test for provisioned concurrency, using `sqs` event.
For additional context: I run this test suite 20 times and on average it takes 7 minutes to run, however, I experienced one run with 8 minutes and one with 9 minutes as well. 
Closes: #8321
> test(AWS SQS): add integration test for sqs with provisioned concurrency

- lib/plugins/aws/provider/awsProvider.js
AWS allows for resource tags to have colons in them. In fact, they use it themselves for their reserved tags and they recommend their use in their [best practices](https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf). Serverless config schema validation should also allow for it.
The schema validation is based on the documentation in this page: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Tag.html.
This PR closes #8304.
> Fix schema for resource tags.

- lib/classes/Service.js
- lib/classes/Variables.js
- lib/classes/Variables.test.js
- lib/plugins/aws/provider/awsProvider.test.js
- test/fixtures/variables/serverless.yml
It was not working for many commands, not long after introduction with https://github.com/serverless/serverless/pull/3208 (published with v1.9.0) - due to not proper handling of circular references (fixed in this PR)
Internal recognition for some commands was additionally wiped out with https://github.com/serverless/serverless/pull/8279 (published with v2.3.0) - due to fine tuning of variables regex (fixed in this PR)
This brings it back, although this functionality feels controversial, and we may consider to deprecate it at some point in a future.
> Variables: Fix support for "${self:}"

- lib/plugins/aws/provider/awsProvider.js
> added Fn::Transport to Resources.resources on validation schema

- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
> aws apiGateway event - make sure http request parameters have boolean value

- lib/plugins/aws/provider/awsProvider.js
Allows delimiter to be the empty string [as documented by AWS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html).
Closes: #8344
> fix(Config Schema): Fix Fn::Join delimiter length schema

- lib/plugins/aws/deployFunction/index.js
If `RoleName` is missing in a [custom function role](https://www.serverless.com/framework/docs/providers/aws/guide/iam/#custom-iam-roles) this passes through `undefined` and single `sls deploy -f funcName` fails with a hard to decipher error: 
```
ServerlessError: The role defined for the function cannot be assumed by Lambda.
at /service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:330:27
at processTicksAndRejections (internal/process/task_queues.js:85:5)
```
After turning on SLS_DEBUG I found the issue where the IAM role name was  `undefined`
```
Serverless: [AWS lambda 400 0.417s 0 retries] updateFunctionConfiguration({
FunctionName: 'service-dev-addNewUser',
Description: 'Add user test function. Gated by …
```
> DX: Throw if missing RoleName in Custom function role

- lib/plugins/aws/customResources/resources/apiGatewayCloudWatchRole/handler.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/permissions.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/eventBridge.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/permissions.js
- lib/plugins/aws/customResources/resources/s3/lib/bucket.js
- lib/plugins/aws/customResources/resources/s3/lib/permissions.js
- lib/plugins/aws/customResources/resources/utils.js
> added awsRequest for aws-sdk call backoff and retry in customResources

- lib/classes/ConfigSchemaHandler/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
Fixes regression introduced with https://github.com/serverless/serverless/pull/8272 (published with v2.2.0) that brought back https://github.com/serverless/serverless/issues/7008 (as `null` properties got removed)
Additionally fixed test introduced with https://github.com/serverless/serverless/pull/8159 so it properly exposes eventual issue
> Config Schema: Ensure to preserve `null` values for config validation
