serverless/serverless

CHANGELOG.md
package.json

Releasing v1.49.0

---

docs/dashboard/README.md

Adding ap-south-1 to supported region list

---

lib/plugins/package/lib/packageService.js

Closes #6333 
Added `yarn-*.log` to `defaultExcludes` list in `packageService.js`
After packaging, the lambda zip file should not have any yarn logs.

Fix exclusion of Yarn logs in Lambda packages

---

CHANGELOG.md
lib/plugins/interactiveCli/index.js
package.json

Realese the v1.50.1 (`interactiveCli`, `end` lifecycle event)

Release v1.50.1

---

lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js

…s not in the main stack
+ a small fix in a function name
Closes #6607

Fix API Gateway name not being resolved API Gateway Resource not in main stack

---

package.json

Bump sfe plugin!

---

CONTRIBUTING.md

Coverage is not generated with `npm test`. Use `npm run coverage`
instead.
Closes #6681
Updated text in CONTRIBUTING.md.
`rm -rf coverage && npm test` to confirm no `coverage` is generated, followed by `npm run coverage` to confirm that `coverage is generated.
(If a checkbox above was non-applicable, I checked it. Hope that's the right …

Make minor correction to CONTRIBUTING.md.

---

docs/providers/azure/cli-reference/create.md
docs/providers/azure/cli-reference/deploy-function.md
docs/providers/azure/cli-reference/deploy-list.md
docs/providers/azure/cli-reference/deploy.md
docs/providers/azure/cli-reference/install.md
docs/providers/azure/cli-reference/invoke.md
docs/providers/azure/cli-reference/login.md
docs/providers/azure/cli-reference/logs.md
docs/providers/azure/cli-reference/plugin-install.md
docs/providers/azure/cli-reference/plugin-list.md
docs/providers/azure/cli-reference/plugin-search.md
docs/providers/azure/cli-reference/plugin-uninstall.md
docs/providers/azure/cli-reference/print.md
docs/providers/azure/cli-reference/remove.md
docs/providers/azure/cli-reference/rollback.md

Updated Azure CLI Reference Docs
Updated existing docs to match `dev` branch of `serverless-azure-functions` repo
Walk through the documentation and try to create an Azure Functions project

Update Azure CLI Reference Docs

---

docs/dashboard/testing.md

Documentation for the `test` command
Adding markdown docs with metadata to be deployed on serverless.com
These docs do not require verification as they have already been reviewed and published, this PR just migrates them to the new site.

Add testing docs

---

CHANGELOG.md
lib/classes/PluginManager.js
lib/classes/PluginManager.test.js
package.json

cherry-picked https://github.com/serverless/serverless/pull/6687 onto 1.52.0
release tag draft: https://github.com/serverless/serverless/releases/edit/untagged-a8f17b375f73749ee203

Rel 1.52.1

---

lib/classes/CLI.js
lib/classes/CLI.test.js
lib/classes/Error.js
package.json

as per https://github.com/serverless/components/issues/468, I've added components core & cli versions to the version list. They will only be added if the user is running Node 8+ (because it requires loading the components CLI, which is not compatible with older versions of Node)
run `sls version`
```
serverless (master)$ serverless version
Framework Core: 1.52.0
Plugin: 2.0.0
SDK: 2.1.1
Components Core: 1.0.0
Components CLI: 1.2.3
serverless (master)$
```
or trigger an error
```
Issues:        forum.serverless.com
Your Environment Information ---------------------------
Operating System:          darwin
Node Version:              12.7.0 …
```

Added Components Versions

---

README.md

Adding Theodo to the consultants section of the README.
Theodo is a software development company that helps startups build projects using Serverless. 
They also run the Serverless Transformation newsletter and blog.
Adding Theodo to the consultants section of the README.
Closes #XXXXX

Add Theodo to the consultants section of the README

---

lib/plugins/interactiveCli/initializeService.test.js
lib/plugins/interactiveCli/setupAws.test.js
package.json

Aside of minor improvements, it fixes issue which causes integration tests fail

Upgrade @serverless/test to v2

---

CHANGELOG.md
package.json

Release v1.52.2

---

lib/plugins/interactiveCli/index.js
lib/plugins/interactiveCli/setupAws.js

Expose an interface that will allow to customize interactive AWS setup (as needed by Dashboard plugin)

PLAT-1599 Modularize interactive AWS setup

---

docs/providers/aliyun/guide/credentials.md

I added a sentence on real name verification which is required to deploy in some regions in China. I also changed a link to the proper function compete page for Alibaba Cloud. And I fixed a small typo.

Alibaba Docs Update

---

lib/plugins/aws/invokeLocal/java/pom.xml
lib/plugins/create/templates/aws-java-gradle/build.gradle
lib/plugins/create/templates/aws-java-maven/pom.xml
lib/plugins/create/templates/aws-kotlin-jvm-gradle/build.gradle
lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml

Updates the Jackson versions used by JVM-based projects --> https://mvnrepository.com/artifact/com.fasterxml.jackson.

Update Jackson versions

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

This PR updates the issue / PR template in order to streamline the process and therefore make it easier for contributors to submit new issues / PRs.
Feel free to provide feedback / enhancements as we'd like to reduce as much friction as possible.

Simplify GitHub Issue / PR templates

---

docs/dashboard/monitoring/README.md

Adds the capture and span documentation to the new doc structure

Capture and span docs

---

docker-compose.yml
lib/plugins/create/templates/aws-scala-sbt/build.sbt
lib/plugins/create/templates/aws-scala-sbt/project/build.properties
lib/plugins/create/templates/aws-scala-sbt/project/plugins.sbt

Closes #XXXXX
```
tests/templates/integration-test-template aws-scala-sbt sbt assembly
```
**Useful scripts:**

Update dependencies in aws-scala-sbt template

---

.github/PULL_REQUEST_TEMPLATE.md

Hide the scripts one can use in an expandable section to make the overall appearance more clean.
Use the Markdown previewer to see how it will look like.
**Useful scripts:**

PR Template --> Hide useful scripts in expandable section

---

docs/providers/azure/events/cosmosdb.md
docs/providers/azure/events/other.md

Azure plugin now supports CosmosDB binding.  Updated the docs to show how to use it.
Documentation change. 
<details>
</details>

doc: add cosmosdb events doc

---

docs/providers/azure/guide/credentials.md
docs/providers/azure/guide/quick-start.md

Updated documentation for Azure environment variables to current names.
1. Create a service principal
2. Update environment variables on machine
3. Make sure you have latest `serverless-azure-functions` plugin installed
4. Deploy an Azure Function App
<details>
</details>

Update Azure environment variable documentation

---

lib/plugins/create/templates/openwhisk-nodejs/handler.js

I added logging to the openwhisk nodejs template
Closes #4721 
Added a log line in the function
<details>
</details>

Added logging Implementation for serverless openwhisk-nodejs template

---

lib/plugins/create/templates/azure-nodejs/serverless.yml

Added a note to the `serverless.yml` to help beginners like me.
Closes #XXXXX
Deploy the template with the different `authLevel` values.
<details>
</details>

Adding note to Azure nodejs template

---

docs/providers/azure/guide/functions.md

Updated the documentation to help beginners like me.
Closes #XXXXX
Deploy an Azure Function app with the different `authLevel` values.
<details>
</details>

Updated Azure Functions documentation

---

docs/providers/aws/guide/serverless.yml.md

Updated the `serverless.yml.md` doc for the AWS provider to include all the event sources we currently offer.
Just read through the updated `.md` file.
<details>
</details>

Update event documentation

---

package.json

Fixes a potential security vulnerability. [Here](https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.0) are the release notes.
Closes #6863
Run `npm run integration-test-run-basic` to verify that the basic functionality is still working.
<details>
</details>

Update https-proxy-agent dependency

---

lib/plugins/package/lib/packageService.test.js

Added some tests for packageService#resolveFilePathsFromPatterns().
Just `$(npm bin)/mocha ./lib/plugins/package/lib/packageService.test.js`
or `npm test` would do.
<details>
</details>

Add Tests for resolveFilePathsFromPatterns()

---

CHANGELOG.md
lib/classes/CLI.js
lib/plugins/interactiveCli/index.js
lib/plugins/interactiveCli/initializeService.js
package.json

Closes PLAT-1691
draft release: https://github.com/serverless/serverless/releases/edit/untagged-3ce51b75493396c33c83

Rel 1.55.1

---

docs/providers/aws/events/apigateway.md

Added documentation for mock integrations, regarding AWS API Gateway events.
Closes #5960  
Reading the documentation, added a simple mock example.

Added mock integration documentation example

---

docs/dashboard/monitoring/alerts.md

Documentation for the unused memory alert in the dashboard

Adds unused memory alert

---

docs/dashboard/README.md

Updated docs to clarify how to reorganize Dashboard-related things.
This was discovered via trying to create a new app by changing `serverless.yml` to use a new (non-existent) app.

Note about how to move services to new apps

---

lib/plugins/create/create.js

- Move Tencent templates up
- Improve visibility of templates in help listing

sls create --help improvements

---

.codecov.yml
.travis.yml
README.md
package.json

Bring back code coverage via Codecov.
Implemented it according to [this guide](https://github.com/codecov/example-node) and by looking into our other repos.
<details>
</details>

Setup Codecov

---

docs/providers/tencent/guide/workflow.md

Fixes a typo (might've been caused by a copy-and-paste) in the Tencent docs.
<details>
</details>

Fix typo in Tencent docs

---

lib/plugins/create/create.js
lib/plugins/create/create.test.js
lib/plugins/create/templates/knative-docker/code/app.py
lib/plugins/create/templates/knative-docker/code/hello-world.dockerfile
lib/plugins/create/templates/knative-docker/gitignore
lib/plugins/create/templates/knative-docker/package.json
lib/plugins/create/templates/knative-docker/serverless.yml

Adds the Knative provider template.
Refs #6930
Closes #5212 
**NOTE:** We need to sync with @billfine and @ganeshvlrk when / how we want to release this.
```
serverless create --template knative-docker
```
Follow the docs in #6930 to deploy a Knative service. This is quite involved and not really necessary to validate that the project scaffolding is created.
I manually tested it on my machine with a fresh template created with `serverless create` while checking out this branch and it worked just fine.
<details>
- `npm run prettier-check-updated` --> Check if …

Add Knative provider template

---

docs/README.md
docs/getting-started.md
docs/providers/README.md
docs/providers/knative/README.md
docs/providers/knative/cli-reference/README.md
docs/providers/knative/cli-reference/create.md
docs/providers/knative/cli-reference/deploy.md
docs/providers/knative/cli-reference/info.md
docs/providers/knative/cli-reference/install.md
docs/providers/knative/cli-reference/invoke.md
docs/providers/knative/cli-reference/remove.md
docs/providers/knative/events/README.md
docs/providers/knative/events/aws-sqs.md
docs/providers/knative/events/cron.md
docs/providers/knative/events/custom.md
docs/providers/knative/events/gcp-pub-sub.md
docs/providers/knative/events/kafka.md
docs/providers/knative/guide/README.md
docs/providers/knative/guide/credentials.md
docs/providers/knative/guide/deploying.md
docs/providers/knative/guide/events.md
docs/providers/knative/guide/functions.md
docs/providers/knative/guide/installation.md
docs/providers/knative/guide/intro.md
docs/providers/knative/guide/packaging.md
docs/providers/knative/guide/plugins.md
docs/providers/knative/guide/quick-start.md
docs/providers/knative/guide/services.md
docs/providers/knative/guide/variables.md
docs/providers/knative/guide/workflow.md

Adds the documentation for the Knative provider integration.
Refs #6936
Closes #5212 
**NOTE:** We need to sync with @billfine and @ganeshvlrk when / how we want to release this.
<details>
</details>

Add Knative documentation

---

docs/providers/README.md
docs/providers/aliyun/README.md
docs/providers/aws/README.md
docs/providers/azure/README.md
docs/providers/cloudflare/README.md
docs/providers/fn/README.md
docs/providers/google/README.md
docs/providers/knative/README.md
docs/providers/kubeless/README.md
docs/providers/openwhisk/README.md
docs/providers/spotinst/README.md
docs/providers/tencent/README.md

Updated provider sort order in docs so things are more consistent between left website doc menu and logo's on the main provider page

updated providers menu order in docs

---

docs/providers/aws/events/apigateway.md
docs/providers/aws/events/streams.md
docs/providers/aws/guide/credentials.md
docs/providers/aws/guide/events.md
docs/providers/aws/guide/functions.md
docs/providers/aws/guide/intro.md

Added links to guides in a few doc pages so it's even more useful for users

Update docs links

---

docs/dashboard/sdk/nodejs.md
docs/dashboard/sdk/python.md

I added documentation for the `tagEvent` feature of the enterprise-plugin
You can read it!

Update documentation to include information about tags

---

docs/dashboard/cicd/README.md

Minor doc updates referencing the CI/CD Settings in Serverless Framework Pro dashboard.
Updates can be previewed here:
https://5dd2f02eb1512f0009d452db--serverless.netlify.com/framework/docs/dashboard/cicd/

Updates to CI/CD settings for the beta

---

lib/plugins/create/templates/aws-kotlin-jvm-gradle/README.md
lib/plugins/create/templates/aws-kotlin-jvm-gradle/build.gradle
lib/plugins/create/templates/aws-kotlin-jvm-gradle/gradle/wrapper/gradle-wrapper.properties
lib/plugins/create/templates/aws-kotlin-jvm-gradle/serverless.yml

- upgrade to Gradle 6.0
- upgrade to Java 11
- update dependencies to recent versions
- configure shadowJar task and johnrengelman plugin
Closes #XXXXX
build: `./gradlew clean build`
deploy: `./gradlew deploy`
If you want to check using an API Gateway use the following as `serverless.yaml` and follow the output url to trigger the function:
```
provider:
name: aws
runtime: java11
package:
artifact: build/libs/hello-dev-all.jar
functions:
hello:
handler: com.serverless.Handler
events:
- http:
method: get
```
**_Is it a breaking change?:_** NO, it is a change in the template section, not in the framework itself

Update aws-kotlin-jvm-gradle template to Gradle 6 and Java 11

---

lib/plugins/interactiveCli/setupAws.js
lib/utils/open.js
lib/utils/openBrowser.js

/cc @garethmcc 
Addresses error reported on Slack:
--- 
- Unconditionally present url to the user
- Prevent uncaught exceptions, which may eventually be thrown by `open`. Issue also persist in latest version -> https://github.com/sindresorhus/open/issues/56

Fix "open browser" issues

---

docs/dashboard/cicd/README.md
docs/dashboard/cicd/best-practices.md
docs/dashboard/cicd/branch-deployments.md
docs/dashboard/cicd/custom-scripts.md
docs/dashboard/cicd/faq.md
docs/dashboard/cicd/mono-repo.md
docs/dashboard/cicd/preview-deployments.md
docs/dashboard/cicd/private-packages.md
docs/dashboard/cicd/running-in-your-own-cicd.md
docs/dashboard/cicd/running-tests.md
docs/dashboard/cicd/troubleshooting.md

This updates the docs for CI/CD in Dashboard with a few key changes: (1) refactoring a few sections into dedicated pages, (2) updating the format of the CI/CD readme, and (3) adding content for new features.
Making this a draft PR as some of the features described are not yet available.
A preview of the docs can be seen [here](https://5df5635489037400084fb4d7--serverless.netlify.com/framework/docs/dashboard/cicd/).

Docs - updates per new dashboard CI/CD features

---

lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
lib/plugins/aws/package/compile/events/eventBridge/index.js
lib/plugins/aws/package/compile/events/eventBridge/index.test.js

Fixes #6579 
Fixed also AWS partition references in few other spotted places.
--- 
Confirmed there's no issues in changes by running all integration tests against PR

Ensure needed access roles when handling existing cognito pools 

---

commitlint.config.js
lib/classes/PluginManager.js
lib/classes/PluginManager.test.js

Fixes #7117 
Regression introduced with #6814

Fix support for relative path in plugins.localPath

---

CHANGELOG.md
lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
package.json

Fix handling of provisionedConcurrency: 0 setting

---

docs/cn/README.md
docs/cn/getting-started.md
docs/cn/providers/tencent/README.md
docs/cn/providers/tencent/cli-reference/create.md
docs/cn/providers/tencent/cli-reference/deploy-function.md
docs/cn/providers/tencent/cli-reference/deploy-list.md
docs/cn/providers/tencent/cli-reference/deploy.md
docs/cn/providers/tencent/cli-reference/info.md
docs/cn/providers/tencent/cli-reference/install.md
docs/cn/providers/tencent/cli-reference/invoke.md
docs/cn/providers/tencent/cli-reference/logs.md
docs/cn/providers/tencent/cli-reference/metrics.md
docs/cn/providers/tencent/cli-reference/remove.md
docs/cn/providers/tencent/cli-reference/rollback.md

/cn Chinese documentation fix.

Update Chinese documentation-1578020091

---

docs/providers/aws/events/apigateway.md

I changed the reference to JSON Schema draft-07 (not supported) to draft-04 which is supported by API Gateway.
This is a docs change, you can make sure I'm making it in the right spot?

Draft 07 to 04

---

docs/dashboard/cicd/mono-repo.md
docs/dashboard/cicd/running-tests.md

Made two minor fixes to the CI/CD documentation:
- A couple list items should have bullet points `-`
- One of the code blocks should have been `json`, not `yaml`.

Docs minor fixes 010820

---

docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/lib/updateStack.js
lib/plugins/aws/lib/updateStack.test.js

Adds support for rollbackConfiguration
Closes #7134 
A unit test was written to cover this change.

add rollbackConfiguration

---

.travis.yml
docs/getting-started.md
package.json
scripts/pkg/choco-package-template/serverless.nuspec
scripts/pkg/choco-package-template/tools/LICENSE.txt
scripts/pkg/choco-package-template/tools/VERIFICATION.txt
scripts/pkg/choco-package-template/tools/chocolateyinstall.ps1
scripts/pkg/choco-package-template/tools/chocolateyuninstall.ps1
scripts/pkg/generate-choco-package.js
scripts/postinstall.js

Follow up to: #7108 
Waiting for clearance from Chocolatey Package manager

Chocolatey, Windows package manager integration

---

lib/utils/downloadTemplateFromRepo.test.js

Continuation to https://github.com/serverless/serverless/pull/7195 (in a meantime another test was introduced with same issue)

Tests: Fix download template race condition

---

package.json
tests/integration-all/api-gateway/tests.js
tests/integration-all/websocket/tests.js
tests/integration-basic/tests.js
tests/utils/api-gateway/index.js
tests/utils/cloudformation/index.js
tests/utils/cloudwatch/index.js
tests/utils/cognito/index.js
tests/utils/dynamodb/index.js
tests/utils/eventBridge/index.js
tests/utils/iot/index.js
tests/utils/kinesis/index.js
tests/utils/misc/index.js
tests/utils/s3/index.js
tests/utils/sns/index.js
tests/utils/sqs/index.js
tests/utils/websocket/index.js

Simple refactor to not host `awsRequest` internally

Tests: Upgrade to @serverless/test v3.4.0

---

.travis.yml
lib/plugins/executable/index.js

Corrects minor spelling errors.

corrected spelling errors

---

CHANGELOG.md
package.json

Just minor a improvement I wish to rely on in dashboard plugin tests

Release v1.61.3

---

lib/plugins/create/templates/aws-go-mod/gomod.sh

Ensures that running `make` does not overwrite `go.mod` if it already exists.
Closes #7244
This is my `serverless.yml`:
```
service: golambda
app: go-lambda
frameworkVersion: '>=1.28.0 <2.0.0'
provider:
name: aws
runtime: go1.x
region: eu-west-1
package:
exclude:
- ./**
include:
- ./bin/**
functions:
hello:
handler: bin/hello
events:
- http:
path: hello
method: get
docs:
handler: bin/docs
environment:
JWT_SECRET: ${env:JWT_SECRET}
events:
- http:
path: v0/docs
method: get
- http:
path: v0/docs
method: post
- http:
path: v0/docs/{id}
method: any
plugins:
- serverless-dotenv-plugin
```
0. You can run this without any actual go code if you delete all function definitions - this will not change the relevant execution.
1. Run `make` in order to generate your `go.mod` file.
2. Edit `go.mod` - …

Do not overwrite `go.mod` on `make` if it exists.

---

docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/lib/mergeIamTemplates.js
lib/plugins/aws/package/lib/mergeIamTemplates.test.js

Added support for permission boundaries: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html

Add iam role permission boundaries

---

docs/providers/openwhisk/events/apigateway.md

Fixed a broken link in the documentation.
Verify that the link points to the right piece of document you intended to reference.

Fix broken link

---

docs/providers/aws/events/http-api.md
lib/plugins/aws/lib/naming.js
lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/package/compile/events/httpApi/index.test.js
tests/integration-all/http-api/tests.js

Follows implementation roadmap as outlined in #7052

HTTP API: JWT Authorizers

---

docs/providers/aws/examples/hello-world/go/README.md

I added a section on `aws-go-mod` template to the documentation page.
<details>
</details>

Include section on `aws-go-mod`

---

docs/providers/aws/guide/serverless.yml.md

For some reason missed in original PR's

AWS HTTP API serverless.yml documenation

---

docs/providers/aws/events/http-api.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/lib/naming.js
lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/package/compile/events/httpApi/index.test.js
tests/integration-all/http-api/tests.js

Addresses #7052 
It also includes https://github.com/serverless/serverless/pull/7383 which ideally should be approved and merged first
Support access logs configuration

HTTP API: Access logs configuration

---

docs/providers/aws/events/http-api.md
lib/plugins/aws/info/getStackInfo.js
lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/package/compile/events/httpApi/index.test.js
tests/fixtures/httpApiExport/serverless.yml
tests/integration-all/http-api/tests.js

HTTP API: Support attachment to externally created API

---

docs/providers/aws/events/http-api.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/package/compile/events/httpApi/index.test.js
tests/fixtures/httpApi/index.js
tests/integration-all/http-api/tests.js

AWS HTTP API: Support `timeout` setting

---

docs/dashboard/README.md

Update docs to add Python support

Update supported runtimes

---

CONTRIBUTING.md

Explain how to become a Framework maintainer

Improve contributors documentation

---

docs/dashboard/cicd/branch-deployments.md
docs/dashboard/cicd/preview-deployments.md

Doc updates on the preview & branch deployment settings in SF Pro dashboard.
A preview of the docs will be generated - confirm the new content is reflected on the docs.

Docs sfp cicd

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/lib/naming.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js
lib/plugins/aws/provider/awsProvider.js
tests/fixtures/functionDestinations/serverless.yml
tests/fixtures/functionDestinations/target.js
tests/fixtures/functionDestinations/trigger.js
tests/integration-all/function-destinations/tests.js

Closes #7007 
Implements support of AWS Lambda destinations via `destinations` function property

AWS Lambda destinations support

---

docs/dashboard/cicd/preview-deployments.md

Corrected typo in preview-deployments.md
Changed `stgae` to `stage`
Read the docs

Corrected typo preview-deployments.md

---

docs/dashboard/sdk/nodejs.md
docs/dashboard/sdk/python.md

Documentation for SFPro SDK `setEndpoint`/`set_endpoint` method.

Document SFPro SDK endpoint instrumentation

---

docs/getting-started.md

Update the /framework/docs/getting-started/ page
Closes https://github.com/serverless/site/issues/556

Update the /framework/docs/getting-started/ page

---

docs/getting-started.md

Content changes according to the mockup:
https://serverless.invisionapp.com/share/ZNWH7H72MPJ#/screens

Update the /framework/docs/getting-started/ page (update content Mar 19)

---

docs/providers/aws/events/http-api.md

Added a link to the AWS Documentation that describes the differences between REST APIs and HTTP APIs.
Closes #XXXXX
<details>
</details>

REST API vs. HTTP API

---

docs/README.md
docs/getting-started.md

Updated docs readme
Closes https://github.com/serverless/site/issues/588

Update docs readme

---

bin/serverless.js
lib/classes/CLI.js
lib/classes/Error.js
lib/components-v1.js
lib/components-v2.js

Handle gently Components initialization errors

---

lib/plugins/create/create.test.js
lib/plugins/create/templates/azure-python/package.json
lib/plugins/create/templates/azure-python/serverless.yml

Fix the Python template for Azure Functions. There is an [existing PR](https://github.com/serverless/serverless-azure-functions/pull/420) that adds Linux and Python support to the Azure Functions plugin.
Wait for the PR 👆 to be merged. Once merged, install the beta version of the plugin `npm i serverless-azure-functions@beta`. Then deploy a function app with this template.
**Update**: the PR has been merged, and the beta package contains this functionality.
<details>
- `npm …

Update Azure Functions Python template

---

docs/providers/aws/examples/hello-world/go/README.md

Updates best practices to include note on Go Modules.
<details>
</details>
- [N/A] Write and run all tests

docs: update go project best practices

---

docs/providers/knative/guide/intro.md

Fixed a typo in the documentation.
N/A
<details>
</details>

Fix typo in documentation

---

docs/providers/azure/guide/serverless.yml.md

Docs update only.
Add missing armTemplate attribute to complete Azure serverless.yml
Closes https://github.com/serverless/serverless-azure-functions/issues/446 (at least partially)
N/A
- [n/a] Write and run all tests

Add missing armTemplate attribute to complete Azure serverless.yml

---

docs/dashboard/README.md

Expand supported regions to include some new ones

Doc: Update supported regions

---

docs/providers/azure/guide/serverless.yml.md

Quick doc improvement.   See code use of config at [armService.ts#L83](https://github.com/serverless/serverless-azure-functions/blob/9b57daccd83cd12f23a775118aef7f6e1577efc3/src/services/armService.ts#L83)

Add missing armTemplate attribute "parameters" to complete serverless.yml

---

package.json

Closes: #7693
update uuid npm pacage v2.0.3 to v8.0.0

update uuid v2.0.3 to v8.0.0 #7693 fix

---

docker-compose.yml
docs/providers/aws/examples/hello-world/fsharp/README.md
lib/plugins/create/templates/aws-fsharp/Handler.fs
lib/plugins/create/templates/aws-fsharp/aws-fsharp.fsproj
lib/plugins/create/templates/aws-fsharp/build.cmd
lib/plugins/create/templates/aws-fsharp/build.sh
lib/plugins/create/templates/aws-fsharp/serverless.yml

Update aws-fsharp to .NET Core 3.1

---

docs/getting-started.md

- Improve logical order of sections
- Add a note about special default interactive experience for China, and provide a hint on how to opt out if one prefers to (addresses #7637)

Improve "Get started.." documentation

---

docs/providers/aws/events/websocket.md

docs: fix typo

---

lib/plugins/aws/deploy/lib/checkForChanges.js
lib/plugins/aws/deploy/lib/checkForChanges.test.js

Closes: -
This is a follow-up of PR #7742.

Join with serverless dir path only if not start with it

---

lib/plugins/package/lib/packageService.js
package.json

Upgrade globby to v9.2.0

---

docs/deprecations.md
docs/providers/aws/guide/serverless.yml.md
lib/classes/Service.js
lib/utils/logDeprecation.js
lib/utils/logDeprecation.test.js

Closes: #7422
I'm not sure if this is what you're expecting, but wanted to push this so we can discuss the code better than just a theory

Add logDeprecation and tests

---

docs/providers/aws/examples/hello-world/csharp/README.md

This is a very trivial documentation fix, hopefully it's welcome anyway.

Fix typo in powershell command example

---

docs/providers/aws/guide/serverless.yml.md

The payload version requires quotes. This should make it more explicit in the documentation.
See https://github.com/brefphp/bref/issues/602#issuecomment-633258464

Improve documentation: API Gateway payload version

---

docs/providers/azure/cli-reference/deploy-list.md
docs/providers/azure/cli-reference/deploy.md
docs/providers/azure/cli-reference/invoke.md
docs/providers/azure/cli-reference/logs.md
docs/providers/azure/cli-reference/remove.md
docs/providers/azure/cli-reference/rollback.md
docs/providers/azure/events/blobstorage.md
docs/providers/azure/events/cosmosdb.md
docs/providers/azure/events/eventhubs.md
docs/providers/azure/events/http.md
docs/providers/azure/events/other.md
docs/providers/azure/events/queuestorage.md
docs/providers/azure/events/servicebus.md
docs/providers/azure/events/timer.md
docs/providers/azure/guide/deploying.md
docs/providers/azure/guide/function-apps.md
docs/providers/azure/guide/functions.md
docs/providers/azure/guide/intro.md
docs/providers/azure/guide/quick-start.md
docs/providers/azure/guide/serverless.yml.md

Update documentation for Azure, including quickstart and other pages, with links back to plugin repo for more info

docs: Azure Functions Doc Updates

---

lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js
lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/lib/generateCoreTemplate.js
lib/plugins/package/lib/zipService.js
lib/utils/yamlAstParser.js

Replace lodash _.keys with native Object.keys

---

docs/providers/aws/events/apigateway.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/info/getApiKeyValues.js
lib/plugins/aws/info/getApiKeyValues.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js

Support customerId in API keys

---

docs/getting-started.md

docs: suggest using latest node version in getting start doc

---

lib/classes/Utils.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js

refactor: Replace _.toUpper(string) with string.toUpperCase

---

lib/plugins/plugin/install/install.js
lib/plugins/plugin/install/install.test.js
lib/plugins/plugin/uninstall/uninstall.js
lib/plugins/plugin/uninstall/uninstall.test.js

didn't cause any errors for me, but I noticed them and decided it was probably worth pushing here just in case

add remaining '.ts' checks

---

lib/plugins/plugin/uninstall/uninstall.js
lib/utils/yamlAstParser.js

Replace lodash unset with native delete objectProp

---

lib/utils/yamlAstParser.js

Replace lodash _.head with array[0]

---

lib/classes/PluginManager.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/lib/cloudformationSchema.js
lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
lib/plugins/aws/package/compile/events/apiGateway/lib/hack/disassociateUsagePlan.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/lib/mergeIamTemplates.js
lib/plugins/aws/utils/findReferences.js

Replace lodash _.includes with native includes

---

lib/plugins/aws/package/compile/events/cloudWatchLog/index.js

Replace _.indexOf with native includes

---

lib/classes/PluginManager.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/invokeLocal/invoke.rb
lib/plugins/aws/package/lib/saveServiceState.js
lib/plugins/aws/provider/awsProvider.js
lib/plugins/invoke/invoke.js
lib/plugins/package/lib/zipService.js
lib/plugins/plugin/install/install.js
lib/plugins/plugin/lib/utils.js
lib/plugins/plugin/uninstall/uninstall.js

Replace _.split with string.split

---

lib/plugins/aws/deploy/lib/cleanupS3Bucket.js

replace _.takeRight with array.slice #7747

refactor: Replace `_.takeRight` with `array.slice`

---

docs/providers/aws/events/sqs.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/events/sqs/index.js
lib/plugins/aws/package/compile/events/sqs/index.test.js

Reverts serverless/serverless#7620
Fixes #7762

Revert "Adding in configurable MaximumRetryAttempts for SQS"

---

lib/classes/Variables.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/package/compile/events/stream/index.js
lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
lib/plugins/aws/package/lib/mergeIamTemplates.js
lib/plugins/aws/provider/awsProvider.js
lib/plugins/print/print.js
lib/utils/yamlAstParser.js

Replace _.isUndefined with native undefined check

---

docs/dashboard/cicd/preview-deployments.md
docs/providers/aws/guide/credentials.md
docs/providers/aws/guide/functions.md
docs/providers/aws/guide/layers.md
docs/providers/aws/guide/serverless.yml.md
docs/providers/aws/guide/services.md
docs/providers/aws/guide/variables.md

fix: replace `${self:provider.stage}` with `${opt:stage, self:provider.stage, 'dev'}` in docs

---

lib/plugins/aws/provider/awsProvider.js

Replace _.nth with array[index]

---

lib/classes/PluginManager.js

Replace _.replace with string.replace

---

lib/classes/CLI.js

Replace _.repeat with string.repeat

---

docs/providers/aws/events/apigateway.md

There where more options added for APIGateway logging in PR https://github.com/serverless/serverless/pull/6578/files
This commit will describe these options and how to configure logging for a websocket

document additional APIGateway logging options

---

lib/plugins/aws/deploy/lib/checkForChanges.js

Replace _.min with Math.min

---

lib/classes/CLI.js
lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
lib/plugins/package/lib/zipService.js

Replace _.sortBy with array.sort

---

lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/package/compile/events/httpApi/index.test.js
tests/fixtures/httpApi/serverless.yml

Respect logRetentionInDays in log group for httpApi

---

lib/plugins/package/lib/zipService.js

Adresses #7747
_.compact() replaced with array.filter(Boolean)

replaced lodash compact with array.filter(Boolean)

---

lib/plugins/aws/logs/index.js
lib/plugins/aws/metrics/awsMetrics.js

Replace lodash chain with native array chain

---

docs/providers/aliyun/guide/workflow.md

AliYun->Guide->Workflow invoke command line was incorrect. I have updated the command line
Update the messages below
Is this ready for review?: YES
Is it a breaking change?: NO

Corrected invoke function command

---

lib/classes/CLI.js
lib/classes/PluginManager.js
lib/classes/Variables.js
lib/plugins/aws/deploy/lib/extendedValidate.js
lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/info/getResourceCount.js
lib/plugins/aws/lib/updateStack.js
lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/lib/generateCoreTemplate.js
lib/plugins/aws/package/lib/mergeIamTemplates.js
lib/plugins/aws/utils/findReferences.js
lib/plugins/package/lib/zipService.js
lib/plugins/plugin/uninstall/uninstall.js
lib/utils/getCommandSuggestion.js
lib/utils/yamlAstParser.js

replace _.isEmpty with array.length and Object.keys()

---

lib/plugins/aws/package/compile/functions/index.js

Replace _.parseInt with Number

---

lib/classes/CLI.js
lib/classes/PluginManager.js
lib/classes/Utils.js
lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
lib/plugins/aws/package/compile/events/cognitoUserPool/index.js

Replace _.reduce with array.reduce

---

lib/plugins/aws/package/compile/events/alb/lib/validate.js
lib/plugins/aws/package/compile/events/alb/lib/validate.test.js

Remove is boolean

---

lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/createStack.test.js
lib/plugins/aws/lib/updateStack.js
lib/plugins/aws/lib/updateStack.test.js

Closes: https://github.com/serverless/serverless/issues/7885

Override default stackTags with custom stackTags using a case-insensitive merge

---

lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js
lib/plugins/aws/provider/awsProvider.js

Remove _.isInteger

---

lib/plugins/index.js
lib/plugins/standalone/index.js
package.json
scripts/pkg/install.sh
scripts/pkg/upload.js
scripts/pkg/upload/china.js
scripts/pkg/upload/index.js
scripts/pkg/upload/world.js

Due to problems in accessing GitHub from China, this solution ensures no dependency on GitHub API when resolving latest binary in China

Standalone: Improve access in China

---

lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/package/compile/events/alb/lib/validate.js
lib/plugins/invoke/invoke.js

Replace _.concat with array.concat

---

lib/plugins/aws/package/compile/events/s3/index.js

Replace _.keyBy with array.reduce

---

lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
lib/plugins/aws/package/compile/events/cloudFront/index.js
lib/plugins/aws/package/compile/layers/index.test.js

Replace _.findKey with Object.keys(object).find

---

CONTRIBUTING.md
docs/anatomy.md
tests/README.md

Addresses https://github.com/serverless/serverless/issues/7781

Contribution documentation improvements

---

bin/serverless.js
docs/deprecations.md

Communicate a breaking change to be introduced with https://github.com/serverless/serverless/issues/7362

Deprecate old nodejs versions

---

lib/plugins/create/templates/aws-fsharp/aws-fsharp.fsproj

... as expected by the rest of the project
SystemTextJson is the proper package to include (version and code expect it).

Switch PackageReference to Amazon.Lambda.Serialization.SystemTextJson

---

lib/plugins/create/templates/azure-nodejs/package.json
lib/plugins/create/templates/azure-nodejs/serverless.yml

Updates serverless-azure-functions to v2 and updates the runtime
Closes: serverless/serverless-azure-functions#477

fix(Templates): azure-nodejs serverless-azure-functions version

---

lib/plugins/aws/info/getStackInfo.js
lib/plugins/aws/info/getStackInfo.test.js
lib/plugins/aws/utils/resolveCfImportValue.js
lib/plugins/aws/utils/resolveCfImportValue.test.js

Allow use of CF ImportValue for httpApi id

---

lib/utils/analytics/generatePayload.js
lib/utils/analytics/generatePayload.test.js
tests/fixtures/index.js

Addresses: https://github.com/serverless/roadmap/issues/362
Closes: #7927

Send service npm package dependencies for analytics

---

lib/classes/CLI.js
package.json

Addresses https://github.com/serverless/components/issues/686
Complements https://github.com/serverless/components/pull/709

CLI: Communicate access to Components CLI

---

lib/plugins/aws/invokeLocal/index.js

Add java11 support. Fixed #7254

---

lib/plugins/aws/invokeLocal/java/pom.xml
lib/plugins/aws/invokeLocal/java/src/main/java/com/serverless/Context.java
lib/plugins/aws/invokeLocal/java/src/main/java/com/serverless/LambdaLogger.java

Closes: #5155
The change allow us to use newer version of aws-lambda-java-* libs.

Upgrade Java 3rd party libraries used for invokeLocal

---

lib/plugins/aws/invokeLocal/java/src/main/java/com/serverless/InvokeBridge.java

Set ContextClassLoader for groovy and clojure. Fixed #7954

---

lib/plugins/aws/lib/validate.js
lib/plugins/aws/lib/validate.test.js
lib/plugins/aws/provider/awsProvider.js

Fix AWS missing credentials handling

---

lib/plugins/package/lib/zipService.js
lib/plugins/package/lib/zipService.test.js

Fix file permissions handling when packaging for lambdas

---

lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses.js

For `AWS::ApiGateway::Method` resources, make [MethodResponse](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration-integrationresponse.html) and [IntegrationResponse](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-methodresponse.html) `StatusCode` property type-compliant with AWS-documented types to avoid validation errors on compiled CloudFormation templates.
Closes: #7970

fix(aws, apigateway): make StatusCode property compliant with AWS-documented types

---

commitlint.config.js
lib/plugins/aws/provider/awsProvider.js
lib/utils/awsSdkPatch.js

Improve AWS SDK credentials resolution workaround

---

lib/plugins/aws/package/compile/events/eventBridge/index.js
lib/plugins/aws/package/compile/events/eventBridge/index.test.js
tests/integration-all/event-bridge/service/core.js
tests/integration-all/event-bridge/service/serverless.yml
tests/integration-all/event-bridge/tests.js
tests/utils/eventBridge/index.js

fix: Failing deploy of lambdas which attach to Event Bridge against "default" stage fails

---

lib/utils/analytics/generatePayload.js
lib/utils/analytics/generatePayload.test.js
tests/integration-all/cognito-user-pool/tests.js

Analytics: Expose isStandalone

---

lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js

Ensure to respect `maximumRetryAttempts` set to `0`

---

docs/providers/aws/guide/intro.md
lib/plugins/create/templates/aws-nodejs-typescript/serverless.ts

Improve documentation on various available service file formats (yml, json, js, ts).

docs: Improve AWS service file documentation

---

lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
lib/plugins/aws/package/compile/events/sqs/index.js
lib/plugins/aws/package/compile/events/sqs/index.test.js

Fix setup of lambdas with provisioned concurrency

---

commitlint.config.js
lib/classes/PluginManager.js

Recognize dashboard service independent commands

---

lib/plugins/create/templates/aws-nodejs-ecma-script/package.json
lib/plugins/create/templates/aws-nodejs-ecma-script/webpack.config.js

Add ES7+ support to aws-nodejs-ecma-script template

---

lib/classes/ConfigSchemaHandler/index.js
lib/classes/ConfigSchemaHandler/normalizeAjvErrors.js
lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/provider/awsProvider.js
package.json

Http api schema validation

---

lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/provider/awsProvider.js

Follow up to #8068. Fix issues exposed by tests (after error exposure was turned on with #8091)
Additionally ensured alphabetical order in schema definitions

Fix HTTP API schema issues

---

lib/configSchema.js
lib/plugins/aws/provider/awsProvider.js

AWS HTTP API: Fix provider.httpApi.id schema

---

lib/classes/PluginManager.js

This PR makes serverless search plugins in installation folder when it can't find them anywhere else.
Closes: #7976

Search installation folder for plugins after everything else fails.

---

lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js

Cognito schema validation

---

lib/configSchema.js
lib/utils/logDeprecation.js
lib/utils/logDeprecation.test.js

- Fix configuration of some _required_ properties in config schema
- Present deprecation logs as warnings

Config schema fix and deprecation warning improvements

---

tests/fixtures/configSchemaExtensions/serverless.yml

Changing package version should not influence tests result

Test: Ensure tests result do not depend on current version

---

scripts/serverless.js

refactor(CLI): Allow wait for serverless command to end

---

docs/providers/google/guide/credentials.md

Since August 2020 Google requires Cloud Build API to be enabled.

Update Google credentials.md documentation

---

CONTRIBUTING.md

Grammatically updated the tech-doc CONTRIBUTING.md

---

bin/slss.js
docs/deprecations.md
package.json
scripts/serverless.js

Add deprecation message for slss alias

---

docs/providers/aws/events/apigateway.md
lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js

Issue 7008 default request templates

---

lib/plugins/aws/package/compile/events/alb/index.test.js
lib/plugins/aws/package/compile/events/alb/lib/validate.js
lib/plugins/aws/package/compile/events/alb/lib/validate.test.js

Closes: #8120
Removes allowUnauthenticated and allowUnauthenticated related tests.

Remove support for `allowUnauthenticated`

---

lib/plugins/aws/package/compile/events/sqs/index.js
lib/plugins/aws/package/compile/events/stream/index.js
lib/plugins/aws/provider/awsProvider.js

It's to make it available for reuse in https://github.com/serverless/serverless/pull/8164

Seclude IAM role resource name resolution logic for reuse

---

docs/providers/aws/events/http-api.md

Documentation related to solved issue #7791 and merged PR #7905

doc(aws): Update http api external http id documentation

---

lib/plugins/aws/package/compile/events/httpApi/index.js

Add CF function to allowed types for httpApi.authorizer.id

---

lib/plugins/aws/provider/awsProvider.js

Fix Fn:Sub function definition

---

lib/plugins/aws/package/compile/events/iot/index.js
lib/plugins/aws/package/compile/events/iot/index.test.js

Add IoT Event Schema + minor cleanup
Closes: #8030

feat(aws): add iot event schema

---

package.json

Upgrade update-notifier to v4

---

CONTRIBUTING.md
RELEASE_PROCESS.md

Tech doc contribution

---

docs/providers/aws/cli-reference/invoke-local.md

Documentation: Invoke local env variable resolution

---

docs/providers/aws/cli-reference/invoke-local.md
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/utils/resolveCfRefValue.js
lib/plugins/aws/utils/resolveCfRefValue.test.js

Local invoke AWS CF function resolution for env variable : Ref

---

lib/plugins/aws/provider/awsProvider.js

Allow use of intrinsic function for http api authorizers

---

docs/configuration-validation.md
lib/classes/ConfigSchemaHandler/index.js

Closes: #8205
After this is merged, we need to merge as well: https://github.com/serverless/site/pull/715

Config Schema: Improve warning logs

---

lib/plugins/aws/provider/awsProvider.js

Config Schema: Recognize `Condition` on resource configuration

---

docs/providers/aws/guide/resources.md
lib/plugins/aws/package/lib/mergeCustomProviderResources.js
lib/plugins/aws/package/lib/mergeCustomProviderResources.test.js

Adds support for the `Condition` attribute in `resources.extensions`.
Related: #8213 
Closes: #8208

feat(Config Schema): Support Condition attribute on resources.extensions

---

docs/providers/knative/guide/quick-start.md

Fixes two code blocks in the knative quick start docs.

Knative QuickStart Docs Typo Fix

---

lib/plugins/aws/provider/awsProvider.js

fix(Config Schema): Transform should be an array of strings

---

lib/plugins/aws/provider/awsProvider.js

Config Schema: Recognize string value at DependsOn

---

lib/plugins/interactiveCli/initializeService.js

It's a temporary patch until #8257 is properly solved
Addresses: #8257

Workaround config schema error on interactive project initialization

---

lib/plugins/aws/package/compile/events/sns/index.js
lib/plugins/aws/package/compile/events/sns/index.test.js

fix sns event redrive policy's deadlettersqs's sqs policy error

---

lib/plugins/aws/invokeLocal/index.js

Correct Dockerfile layer path invalid on Windows

---

commitlint.config.js
lib/plugins/print/print.js

So provider defaults are maintained in single place

Improve "print" command internals

---

lib/plugins/aws/provider/awsProvider.js

Regression introduced with #8309

Config Schema: Recognize boolean format for `provider.logs.restApi`

---

lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/package/compile/functions/index.test.js
test/integrationPackage/cloudformation.tests.js

Reverts serverless/serverless#8310 due to reasons discussed here https://github.com/serverless/serverless/pull/8310#issuecomment-702341802

Revert "Add version digest as lambda env var"

---

lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/lib/monitorStack.test.js

Most likely regression introduced with https://github.com/serverless/serverless/pull/8132
Closes: #8377

AWS Deploy: Fix resolution of CloudFormation error

---

lib/plugins/aws/invokeLocal/index.js

Generate random uuid for awsRequestId in lambda local invocation

---

lib/plugins/aws/package/compile/events/apiGateway/index.js

Fix API Gateway authorizer schema

---

lib/plugins/aws/package/compile/events/websockets/index.js
lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
lib/plugins/aws/package/compile/events/websockets/lib/validate.js
lib/plugins/aws/package/compile/events/websockets/lib/validate.test.js

websocket event authorizer now supports name and arn fields together

---

lib/classes/ConfigSchemaHandler/index.js
lib/plugins/aws/provider/awsProvider.js

Remaining eventInvokeConfig properties on functions[] schema

---

lib/plugins/aws/provider/awsProvider.js

Follow up to: https://github.com/serverless/serverless/pull/8383

Confg Schema: Fix `provider.apiKeys` required properties rules

---

lib/plugins/aws/provider/awsProvider.js

Config Schema: Fix "provider.apiKeys"  schema

---

lib/plugins/aws/provider/awsProvider.js

Config Schema: Do not mark "layers[].path" as required

---

lib/plugins/aws/package/compile/events/alb/index.js
lib/plugins/aws/package/compile/events/apiGateway/index.js
lib/plugins/aws/package/compile/events/cloudFront/index.js
lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js
lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/package/compile/events/msk/index.js
lib/plugins/aws/package/compile/events/schedule/index.js
lib/plugins/aws/package/compile/events/sns/index.js
lib/plugins/aws/package/compile/events/sqs/index.js
lib/plugins/aws/package/compile/events/stream/index.js
lib/plugins/aws/provider/awsProvider.js

Config Schema: Fix AWS `stream` event `consumer` schema

---

docs/deprecations.md

Small fixes in deprecations.md

docs(deprecations) Few fixes

---

docs/anatomy.md

I noticed a typo in this document, so I pasted the entire document into https://grammarly.com and made spelling changes based on its feedback.

docs: anatomy typos

---

lib/utils/getServerlessConfigFile.js

Replace use of `BbPromise.props` with `Promise.all`
Addresses: #8369

chore(bluebird): refactor BbPromise.props usage

---

docs/providers/aws/cli-reference/slstats.md

Easy navigation and easy reading for others

Fix broken url in docs

---

docs/providers/aws/guide/serverless.yml.md

Actually, serverless.yml accepts SQS event source `enabled` like any others.

docs: add enable SQS Event Source

---

lib/classes/Service.js

Addresses issue described here: https://github.com/serverless/serverless/pull/8330#issuecomment-717873881 by @thewizarodofoz 
Ensure to test `provider` config as put on in service config

Config Schema: Fix `provider` validation

---

lib/plugins/aws/provider/awsProvider.js

fix(Config Schema): Fix IAM Policy resource reference schema

---

lib/classes/CLI.test.js
lib/classes/Service.js
lib/classes/Utils.js
lib/plugins/aws/provider/awsProvider.js

refactor: remove "that = this" pattern

---

commitlint.config.js
lib/plugins/aws/lib/naming.js
lib/plugins/aws/package/compile/events/alexaSkill/index.js
lib/plugins/aws/package/compile/events/apiGateway/index.js
lib/plugins/aws/package/compile/events/cloudFront/index.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/deploy/deploy.js

Additionally report deprecations at earliest possible moment

Analytics: Ensure to report all deprecations

---

lib/plugins/aws/provider/awsProvider.js

As only with empty strings where we can override default environment variables
Closes: #8416

Config Schema: Support empty strings at environment variables

---

lib/plugins/aws/package/compile/events/alb/index.js
lib/plugins/aws/package/compile/events/alb/lib/validate.js
lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/deploy/deploy.js

Port of https://github.com/serverless/serverless/pull/8467 to v1

v1: Improve deprecations handling and analytics payload

---

lib/plugins/aws/package/compile/events/alexaSkill/index.js
lib/plugins/aws/package/compile/events/apiGateway/index.js
lib/plugins/aws/package/compile/events/cloudFront/index.js
lib/plugins/aws/package/compile/functions/index.js

Deprecations: Ensure to inspect configuration after it's fully resolved

---

docs/providers/aws/guide/plugins.md
lib/classes/ConfigSchemaHandler/index.js
lib/classes/ConfigSchemaHandler/index.test.js
test/fixtures/configSchemaExtensions/test-plugin.js
test/fixtures/configSchemaExtensionsError/serverless.yml
test/fixtures/configSchemaExtensionsError/test-plugin-with-errors.js

Add cross plugin event definition

---

lib/plugins/aws/package/compile/events/alb/index.js
lib/plugins/aws/package/compile/events/httpApi/index.js
lib/plugins/aws/package/compile/functions/index.js

Port of #8482 to v2 branch
Additionally fixed left over HTTP API deprecaction to be reported at initialization phase

v1: Fix deprecations handling

---

lib/classes/ConfigSchemaHandler/index.js
lib/classes/ConfigSchemaHandler/index.test.js
test/fixtures/configSchemaExtensions/test-plugin.js
test/fixtures/configSchemaExtensionsError/serverless.yml
test/fixtures/configSchemaExtensionsError/test-plugin-with-complex-event-without-object-definition.js
test/fixtures/configSchemaExtensionsError/test-plugin-with-non-existing-event-error.js

Implement defineFunctionEventProperties for event with multiple JSON schema definitions through the use of anyOf keywork

---

lib/utils/renameService.js
lib/utils/renameService.test.js

Templates: Fix service rename logic

---

lib/plugins/aws/package/compile/functions/index.test.js
lib/plugins/aws/package/lib/mergeIamTemplates.test.js
test/utils/run-serverless.js

Needed for https://github.com/serverless/serverless/issues/8396
Refactor tests in:
-  lib/plugins/aws/package/compile/functions/index.test.js
-  lib/plugins/aws/package/lib/mergeIamTemplates.test.js
With:
- Outline spec for new tests to be based on `runServerless` util
- Refactore already configured `runServerless` based tests into new spec
- Remove few questionable tests
To be followed with issues under which final refactor of tests will be covered

Tests: Prepare background for refactor

---

lib/plugins/aws/package/compile/events/cloudFront/index.test.js

Paves path for https://github.com/serverless/serverless/issues/8502

Tests: Improve organization and prepare for refactor CloudFront tests

---

lib/plugins/aws/provider/awsProvider.js

Add API Gateway resource shorthand syntax for Resource-based policies statements

---

docs/guides/access-roles.md

Adding warning message about deprecated feature

---

lib/classes/Service.js
lib/configSchema.js
lib/configSchema.test.js

Closes: #8465 and https://github.com/serverless/typescript/issues/3

Add service string definition

---

lib/plugins/aws/deploy/lib/checkForChanges.test.js
lib/plugins/aws/package/lib/core-cloudformation-template.json
lib/plugins/aws/package/lib/generateCoreTemplate.test.js

So as per you @medikoo .. I have  just apply a change to policy. Beacuse it is not breaking change. 
Closes: #8489

fixed bucket policy for https bucket

---

lib/plugins/create/templates/aws-nodejs-typescript/package.json
lib/plugins/create/templates/aws-nodejs-typescript/serverless.ts

Update nodejs-typescript template with new typescript definitions

---

lib/plugins/aws/common/index.js
lib/plugins/aws/common/lib/artifacts.js
lib/plugins/aws/common/lib/cleanupTempDir.js
lib/plugins/aws/customResources/index.js
lib/plugins/aws/invoke/index.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/lib/validate.js
lib/plugins/aws/lib/validate.test.js
lib/plugins/aws/package/index.js
lib/plugins/aws/package/lib/generateCoreTemplate.js
lib/plugins/aws/package/lib/saveCompiledTemplate.js
lib/plugins/aws/package/lib/saveServiceState.js
lib/plugins/package/lib/zipService.js

Refactor some code to native promises

---

lib/plugins/aws/provider/awsProvider.js

Closes: https://github.com/serverless/typescript/issues/8

Fix resources JSON-schema by removing invalid additionalProperties property

---

lib/plugins/aws/package/compile/events/apiGateway/index.js

AWS API Gateway: Fix `integration` schema

---

docs/providers/aws/guide/functions.md
lib/plugins/aws/deploy/lib/extendedValidate.js
lib/plugins/aws/deploy/lib/uploadArtifacts.js
lib/plugins/aws/deployFunction/index.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/package/compile/functions/index.js
lib/plugins/aws/provider/awsProvider.js
lib/plugins/package/lib/packageService.js
test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
test/unit/lib/plugins/aws/package/compile/functions/index.test.js

Closes: #8570
Tested by deploying a simple stack with both versioned and not versioned lambda that references ECR image.
Additionally tested `sls deploy function` which works as expected (assuming latest version of `aws-sdk` installed).
Integration test will require a Docker CLI to be available, therefore, at least at this point no integration test is configured

AWS Lambda: Container Image Support 

---

test/fixtures/layer/index.js
test/fixtures/layer/layer/index.js
test/fixtures/layer/serverless.yml
test/unit/lib/plugins/aws/package/compile/layers/index.test.js

- Propose schema for new layer tests
- Configure `retain` related ones

Tests: Pave path for layers tests refactor

---

lib/plugins/package/lib/zipService.js

Add error handling for getFileContentAndStat in zipService

---

test/unit/lib/plugins/aws/package/compile/events/httpApi/index.test.js

Tests: Improve AWS HTTP API tests organization

---

lib/plugins/standalone/index.js

Standalone: Fix upgrade command

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Very trivial grammar fixes in the Github templates. Not sure if the lack of articles was intentional.
It was just hurting my eyes a bit. 😅
Feel free to accept or reject.

chore: basic grammar fixes on GitHub templates

---

docs/providers/aws/guide/layers.md

Adresses: #5583, #5892 and #7837

doc: Add details about how layers patterns are resolved

---

docs/guides/cicd/README.md

Updated the page to better reflect changes brought with Providers and the new UI

Update for new dashboard

---

docs/guides/profiles.md

Added notice to warn users not to use the documentation

Added deprecation notice

---

lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/zipService.js
test/unit/lib/plugins/package/lib/packageService.test.js
test/unit/lib/plugins/package/lib/zipService.test.js

fix(Packaging): Add exec bit for packaged files on Windows

---

lib/plugins/package/lib/packageService.js
test/unit/lib/plugins/package/lib/packageService.test.js

Ensures that all `.env` and `.env.{stage}` files are excluded from the packaged artficat.
Addresses: #8566

fix(Packaging): ensure that .env files are excluded from package

---

lib/plugins/aws/provider.js

Addresses: #8636
Improved schema for `functions[].image` to pick some typical configuration errors

AWS Lambda: Improve "image" property validation

---

test/README.md

Fixes some broken URLs (out of date perhaps).

docs: Fix broken URLs within test README

---

docs/providers/aws/guide/plugins.md

docs(Config Schema): Add docs for defineTopLevelProperty and helpers map

---

test/fixtures/invocation/async.js
test/fixtures/invocation/callback.js
test/fixtures/invocation/context-done.js
test/fixtures/invocation/context-succeed.js
test/fixtures/invocation/doubled-resolution-callback-first.js
test/fixtures/invocation/doubled-resolution-promise-first.js
test/fixtures/invocation/init-fail.js
test/fixtures/invocation/invocation-fail.js
test/fixtures/invocation/payload.js
test/fixtures/invocation/payload.json
test/fixtures/invocation/payload.yaml
test/fixtures/invocation/remaining-time.js
test/fixtures/invocation/serverless.yml
test/unit/lib/plugins/aws/invoke.test.js
test/unit/lib/plugins/aws/invokeLocal/index.test.js

- Provide better base for https://github.com/serverless/serverless/issues/8441 (local invocation tests are pretty sophisticated and so far provided aid was not good enough for community)
- Provide new tests base to aid new invocation extension: https://github.com/serverless/serverless/pull/8652
- Remove few tests that were testing characteristics of internal implementation and provided no real value

Tests: Base for invocation tests refactor

---

lib/classes/ConfigSchemaHandler/index.js
test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-custom-property.js
test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-function-event-property.js
test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-function-event.js
test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-function-property.js
test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-provider-property-in-function.js
test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-provider-property-in-provider.js
test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-top-level-property.js
test/unit/lib/classes/ConfigSchemaHandler/index.test.js

Improve schema definition validation to prevent collisions

---

docs/providers/aws/cli-reference/invoke.md
lib/plugins/aws/invoke.js
lib/plugins/invoke.js
test/fixtures/invocation/context.json
test/unit/lib/plugins/aws/invoke.test.js

feat (AWS Invoke): Allow client context to be passed

---

README.md

Fix link of consultant in readme
cc @serverlessguru

docs: Update ServerlessGuru url

---

lib/plugins/aws/package/compile/events/cloudFront.js
test/unit/lib/plugins/aws/package/compile/events/cloudFront.test.js

Discovered when preparing https://github.com/serverless/serverless/issues/8684

AWS CloudFront: Ensure to describe resolved stage in comment

---

docs/providers/aws/cli-reference/print.md
docs/providers/aws/guide/credentials.md
docs/providers/aws/guide/serverless.yml.md
docs/providers/aws/guide/variables.md
docs/providers/azure/guide/serverless.yml.md

We observe community practicing bad patterns , and that's not a surprise seeing we still promote them.
/cc @astuyve

Docs: Remove configuration bad patterns

---

lib/plugins/create/templates/aws-alexa-typescript/serverless.yml
lib/plugins/create/templates/aws-clojure-gradle/serverless.yml
lib/plugins/create/templates/aws-clojurescript-gradle/serverless.yml
lib/plugins/create/templates/aws-csharp/serverless.yml
lib/plugins/create/templates/aws-fsharp/serverless.yml
lib/plugins/create/templates/aws-go-dep/serverless.yml
lib/plugins/create/templates/aws-go-mod/serverless.yml
lib/plugins/create/templates/aws-go/serverless.yml
lib/plugins/create/templates/aws-groovy-gradle/serverless.yml
lib/plugins/create/templates/aws-java-gradle/serverless.yml
lib/plugins/create/templates/aws-java-maven/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-gradle-kts/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-gradle/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-maven/serverless.yml
lib/plugins/create/templates/aws-kotlin-nodejs-gradle/serverless.yml
lib/plugins/create/templates/aws-nodejs-ecma-script/serverless.yml
lib/plugins/create/templates/aws-nodejs-typescript/serverless.ts
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-provided/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml
lib/plugins/create/templates/aws-python3/serverless.yml
lib/plugins/create/templates/aws-ruby/serverless.yml
lib/plugins/create/templates/aws-scala-sbt/serverless.yml
lib/plugins/create/templates/cloudflare-workers-enterprise/serverless.yml
lib/plugins/create/templates/cloudflare-workers-rust/serverless.yml
lib/plugins/create/templates/cloudflare-workers/serverless.yml
lib/plugins/create/templates/fn-go/serverless.yml
lib/plugins/create/templates/fn-nodejs/serverless.yml

Update templates to not trigger deprecation warnings right after creation. Related discussion: https://github.com/serverless/serverless/pull/8676

refactor(Templates): Upgrade to avoid using deprecated functionality

---

CONTRIBUTING.md
docs/anatomy.md
docs/providers/aws/cli-reference/invoke-local.md
docs/providers/aws/guide/functions.md
docs/providers/aws/guide/plugins.md

docs: Fix typos and dead links

---

lib/utils/standalone.js
scripts/pkg/install.sh
scripts/pkg/upload/china.js
scripts/pkg/upload/index.js
scripts/pkg/upload/world.js

Resolve network issue we met while uploading standalone files to `sp-shanghai` region from GitHub action: https://github.com/serverless/serverless/runs/1576133295?check_suite_focus=true
Tested in my local machine, Tencent SV region is accessible from China.

ci: Upload standalone to na-siliconvalley region for users in China

---

test/unit/lib/plugins/aws/invoke.test.js

I tried taking a first stab at this.  One of the tests I moved out the common section as I thought it would be easier to implement the test in that way.  I figured a smaller PR would potentially help me get a feel for what your thoughts are on how to implement these tests.
Addresses: #8662

test: Refactor some tests for AWS invoke to use runServerless.

---

docs/guides/profiles.md

Updating the release date and migration date of the deployment profile deprecation notice.

docs: Updating migration and release dates

---

lib/plugins/aws/customResources/index.js
lib/plugins/aws/package/index.js
lib/plugins/aws/package/lib/mergeIamTemplates.js
test/unit/lib/plugins/aws/package/index.test.js

As discussed in #8701 moving related by independent refactors into separate PR

refactor: Cleanup mergeIamTemplates module

---

docs/deprecations.md

I missed that during one of recent PRs that improve docs around deprecations

docs: Add note about disabledDeprecations setting

---

test/unit/lib/plugins/aws/deploy/index.test.js

Refactor serveral AwsDeploy tests to use `runServerless` as discussed in https://github.com/serverless/serverless/pull/8725.
I have mixed feelings about some of these as it's pretty hard to replicate similar assertions - it's specifically hard to cleanly test if e.g. cleaning S3 bucket was triggered in this case. What is your opinion in general on that?

test: Refactor several AwsDeploy tests to runServerless

---

lib/plugins/create/templates/aws-nodejs-typescript/package.json

Fixed a typo in package.json (`serverless.ts` was spelled wrong in main).

refactor(Templates): Fix typo in package.json for template aws-nodejs-typescript

---

lib/plugins/aws/customResources/index.js
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/lib/updateStack.js
lib/plugins/aws/provider.js
lib/plugins/aws/remove/lib/stack.js
test/unit/lib/plugins/aws/customResources/index.test.js

As part of the #8701 change, moving refactor around using custom deployment role into this PR.

refactor: Abstract custom deployment role usage

---

test/unit/lib/plugins/package/lib/packageService.test.js

test: Cleanup invalid before in packageService.test.js

---

lib/plugins/create/templates/aws-nodejs-typescript/.nvmrc
lib/plugins/create/templates/aws-nodejs-typescript/README.md

Addresses: https://github.com/serverless/typescript/issues/18

feat(Templates): Add node version constraint to aws-nodejs-typescript

---

lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js

fix(AWS API Gateway): Correctly set `throttle` when `quota` missing

---

test/mochaPatch.js

As same issue was reported for other Node.js version: https://github.com/serverless/serverless/pull/8798/checks?check_run_id=1741511529

Test: Enable temporary patch unconditionally

---

commitlint.config.js

As a followup to discussion about `CLI Onboarding` scope in: https://github.com/serverless/serverless/pull/8797

chore: Add CLI Onboarding as scope

---

docs/deprecations.md
lib/cli/resolve-configuration-path.js
test/unit/lib/cli/resolve-configuration-path.test.js

Fixes: https://github.com/serverless/serverless/issues/8800

CLI: Bring back support for referencing nested configurations

---

test/fixtures/packaging/serverless.yml
test/unit/lib/plugins/package/lib/packageService.test.js

When reviewing https://github.com/serverless/serverless/pull/8721 I've realized there's some mess and confusing setup in currently configured tests and spec.
This PR straightens this up

Tests: Cleanup packaging tests and spec

---

lib/cli/resolve-configuration-path.js
test/unit/lib/cli/resolve-configuration-path.test.js

CLI: Fix resolution of "--config=<configPath>" format

---

lib/plugins/aws/package/compile/events/cloudFront.js

feat(AWS CloudFront): Support CF functions for origin and domain

---

lib/plugins/aws/package/compile/events/cloudFront.js

fix(AWS CloudFront): Fix origin object schema

---

lib/classes/PluginManager.js
lib/classes/Utils.js
lib/utils/getFrameworkId.js
package.json
test/unit/lib/classes/Utils.test.js

As in description + removal of obsolete method `getLocalAccessKey`.

Upgrade to `serverless/utils` v3.0.0.

---

lib/plugins/aws/provider.js

fix(Config Schema): Add type to logRetentionInDays

---

lib/plugins/create/templates/aws-nodejs-typescript/src/functions/hello/index.ts

Closes: https://github.com/serverless/typescript/issues/18
Closes: https://github.com/serverless/typescript/issues/20

fix(Templates): Fix handler path resolution in aws-nodejs-typescript

---

lib/plugins/create/create.js
lib/plugins/create/templates/aws-nodejs-docker/.gitignore
lib/plugins/create/templates/aws-nodejs-docker/Dockerfile
lib/plugins/create/templates/aws-nodejs-docker/README.md
lib/plugins/create/templates/aws-nodejs-docker/app.js
lib/plugins/create/templates/aws-nodejs-docker/serverless.yml

Adds a basic template for Docker with Node base image

feat(Templates): Add aws-nodejs-docker template

---

lib/plugins/create/create.js
lib/plugins/create/templates/aws-python-docker/.gitignore
lib/plugins/create/templates/aws-python-docker/Dockerfile
lib/plugins/create/templates/aws-python-docker/README.md
lib/plugins/create/templates/aws-python-docker/app.py
lib/plugins/create/templates/aws-python-docker/serverless.yml

Adds a basic template for Docker with Python base image

feat(Templates): Add aws-python-docker template

---

test/unit/lib/cli/resolve-local-serverless-path.test.js

refactor: Replace `fse.promises.realpath` with `fs.promises.realpath`

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/provider.js
test/fixtures/ecr/Dockerfile.dev
test/unit/lib/plugins/aws/provider.test.js

feat(AWS Lambda): Add ability to customize file for Dockerfile

---

docs/guides/profiles.md

Updating docs for profiles to reflect the updated migration date and new deprecation dates

docs: Update migration/deprecation dates

---

test/README.md

Small improvement in the documentation for running integration test. Moved from #8850.

docs: Improve documentation for running integration tests

---

lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/lib/setBucketName.js
lib/plugins/aws/lib/updateStack.js

refactor: Use async in `lib/plugins/aws/lib`

---

lib/plugins/aws/package/compile/events/websockets/index.js
lib/plugins/aws/package/compile/events/websockets/lib/api.js
lib/plugins/aws/package/compile/events/websockets/lib/authorizers.js
lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
lib/plugins/aws/package/compile/events/websockets/lib/integrations.js
lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
lib/plugins/aws/package/compile/events/websockets/lib/routes.js
lib/plugins/aws/package/compile/events/websockets/lib/stage.js
test/unit/lib/plugins/aws/package/compile/events/websockets/lib/api.test.js
test/unit/lib/plugins/aws/package/compile/events/websockets/lib/authorizers.test.js
test/unit/lib/plugins/aws/package/compile/events/websockets/lib/deployment.test.js
test/unit/lib/plugins/aws/package/compile/events/websockets/lib/integrations.test.js
test/unit/lib/plugins/aws/package/compile/events/websockets/lib/permissions.test.js
test/unit/lib/plugins/aws/package/compile/events/websockets/lib/routes.test.js

* `lib/plugins/aws/package/compile/events/websockets`
Made changes to tests where necessary.

refactor: Use `async` in `compile/events/websockets`

---

lib/utils/eventuallyUpdate.js

Closes: #8898
Ensure to handle gently unexpected response from npm

fix: Handle gently npm response errors

---

lib/plugins/aws/configCredentials.js
lib/plugins/aws/deployFunction.js
lib/plugins/aws/deployList.js
lib/plugins/aws/provider.js
lib/plugins/aws/rollback.js
lib/plugins/aws/rollbackFunction.js

* Files put directly into `lib/plugins/aws`

refactor: Use `async/await` in `lib/plugins/aws`.

---

lib/plugins/aws/info/getApiKeyValues.js
lib/plugins/aws/info/getResourceCount.js
lib/plugins/aws/info/getStackInfo.js
lib/plugins/aws/info/index.js
lib/plugins/config.js
lib/plugins/deploy.js
lib/plugins/install.js
lib/plugins/invoke.js
lib/plugins/print.js
lib/plugins/slstats.js
lib/plugins/standalone.js
test/unit/lib/plugins/install.test.js
test/unit/lib/plugins/invoke.test.js
test/unit/lib/plugins/slstats.test.js

Covered the following directories:
* `lib/plugins/aws/info`
* Files added directly to `lib/plugins`
Made changes to tests where necessary.

refactor: Use `async/await` in `lib/plugins`.

---

lib/plugins/create/templates/aws-nodejs-typescript/.nvmrc
lib/plugins/create/templates/aws-nodejs-typescript/package.json
lib/plugins/create/templates/aws-nodejs-typescript/serverless.ts
lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json

This PR implements update for `aws-nodejs-typescript` template :
- use `nodejs14.x` as default layer
- use `ES2020` as target output
- update dependancies

feat(Templates): Update `aws-nodejs-typescript` for `nodejs14.x`

---

lib/plugins/aws/package/compile/events/apiGateway/index.js
lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js
lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js
lib/plugins/aws/package/compile/events/apiGateway/lib/hack/disassociateUsagePlan.js
lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/package/compile/events/apiGateway/lib/stage.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js

* `lib/plugins/aws/package/compile/events/apiGateway`

refactor: Use `async/await` in `events/apiGateway`.

---

lib/plugins/aws/invokeLocal/fixture/asyncHandlerWithError.js
lib/plugins/aws/invokeLocal/fixture/asyncHandlerWithSuccess.js
lib/plugins/aws/invokeLocal/index.js

* `lib/plugins/aws/invokeLocal`

refactor: Use `async/await` in `lib/plugins/aws/invokeLocal`.

---

CONTRIBUTING.md

Docs: Improve deprecations setup doc

---

lib/Serverless.js

Improvement of `useDotenv` deprecation warning per discussion on #8566 
Thank you! Cheers.

chore: Improve deprecation warning related to .env files

---

lib/plugins/create/templates/aws-nodejs-typescript/README.md

Updates Node.js version in README to match the changes from #8914

docs(Templates): Update node version for `aws-nodejs-typescript`

---

lib/cli/parse-args.js
test/unit/lib/cli/parse-args.test.js

CLI: Ensure to support "_" in param names

---

lib/cli/resolve-input.js
test/unit/lib/cli/resolve-input.test.js

CLI: Ensure to recognize "-v" param as boolean in all cases

---

lib/plugins/print.js
test/unit/lib/plugins/print.test.js

Fix a regression introduced with https://github.com/serverless/serverless/pull/8973 due to an ommision during PR review

fix: Correctly define print hook

---

lib/configuration/variables/parse.js
test/unit/lib/configuration/variables/parse.test.js

Variables: Ensure vars are parsed in address followed by source

---

scripts/serverless.js
test/unit/scripts/serverless.test.js

Addresses 2.3 from https://github.com/serverless/serverless/issues/8364

Variables: Communicate not accessible "provider" and "provider.stage" properties

---

lib/configuration/variables/sources/file.js
test/unit/lib/configuration/variables/sources/file.test.js
test/unit/lib/configuration/variables/sources/fixture/file-function-errored-non-error.js
test/unit/lib/configuration/variables/sources/fixture/file-function-errored.js
test/unit/lib/configuration/variables/sources/fixture/file-promise-rejected-non-error.js
test/unit/lib/configuration/variables/sources/fixture/file-promise-rejected.js
test/unit/lib/configuration/variables/sources/fixture/file-property-function-errored-non-error.js
test/unit/lib/configuration/variables/sources/fixture/file-property-function-errored.js

Closes: #9007
Additionally: Improve JS file resolution error handling

Variables: Report with "null" not existing "file" sources

---

lib/configuration/variables/resolve.js
scripts/serverless.js
test/unit/lib/configuration/variables/resolve.test.js

Fixes: #9016
Additionally fixed variables error reporting. If resolution of a property, on which other properties depended, errored. Then same error was shown as many times, as many there were dependent properties. Ensured that given error is listed once

Variables: Fix shared source resolution cache issue

---

lib/plugins/aws/package/compile/functions.js
lib/plugins/aws/package/compile/layers.js
lib/plugins/aws/package/index.js
lib/plugins/aws/package/lib/generateArtifactDirectoryName.js
lib/plugins/aws/package/lib/generateCoreTemplate.js
lib/plugins/aws/package/lib/getHashForFilePath.js
lib/plugins/aws/package/lib/mergeCustomProviderResources.js
lib/plugins/aws/package/lib/saveServiceState.js
test/unit/lib/plugins/aws/package/lib/generateArtifactDirectoryName.test.js
test/unit/lib/plugins/aws/package/lib/mergeCustomProviderResources.test.js
test/unit/lib/plugins/aws/package/lib/saveServiceState.test.js

* Files put directly into `lib/plugins/aws/package/compile`
* Files put directly into `lib/plugins/aws/package`
* `lib/plugins/aws/package/lib`

refactor: Use `async` in `lib/plugins/aws/package`

---

lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/zipService.js
lib/plugins/package/package.js
test/unit/lib/plugins/package/lib/zipService.test.js

refactor: Remove `bluebird` from `lib/plugins/package`

---

lib/configuration/variables/resolve.js
test/unit/lib/configuration/variables/resolve.test.js

Variables: Ensure to resolve variables in resolved strings

---

lib/Serverless.js

fix(Variables): Fix variables setup for external plugins usage

---

lib/classes/CLI.js
lib/classes/PluginManager.js
test/unit/lib/classes/CLI.test.js
test/unit/lib/classes/PluginManager.test.js

Finalize remaining bits of 2.7.0 from https://github.com/serverless/serverless/issues/8364

Rely on "isHelpRequest" util internally

---

lib/configuration/variables/sources/file.js

Variables: Improve error message related to JS function resolver

---

lib/plugins/aws/provider.js

fix(Config Schema): Support CF functions for managed policies

---

lib/plugins/aws/deploy/lib/checkForChanges.js
test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js

fix(AWS Deploy): Warn when invalid IAM policy to fetch lambda

---

lib/plugins/invoke.js
test/unit/lib/plugins/invoke.test.js

fix(AWS Local Invocation): Support `env` vars with `=` in value

---

lib/aws/request.js
lib/plugins/aws/provider.js
test/unit/lib/aws/request.test.js
test/unit/lib/plugins/aws/provider.test.js

refactor: seclude request from aws provider

---

lib/plugins/create/templates/azure-nodejs-typescript/serverless.yml

I receive the error `Error: Runtime nodejs12.x is not supported. Runtimes supported: nodejs10,nodejs12,python3.6,python3.7,python3.8,dotnet2.2,dotnet3.1` when trying to run the current version. Changing to just `nodejs12` helps.
Haven't done much testing on this (struggling with AZ auth and subscription lists), but this fix seems to suppress the error message and allow `sls offline` to run.
This value aligns with [the CONFIG.md doc](https://github.com/serverless/serverless-azure-functions/blob/master/docs/CONFIG.md), and should help prevent further occurrences of #6998 in this repo, as well as issue 393 in the [serverless-azure-functions repo](https://github.com/serverless/serverless-azure-functions).
Closes: #6998

fix(Templates): Fix runtime for `azure-nodejs-typescript`

---

lib/plugins/aws/provider.js
test/unit/lib/plugins/aws/provider.test.js

AWS Credentials: Fix credentials resolution (right way)

---

lib/cli/commands-schema.js
lib/cli/resolve-input.js
test/unit/lib/cli/resolve-input.test.js

Sorry about the lack of a Github bug. I can make one if need be. This is my reference, though: https://forum.serverless.com/t/unexpected-multiple-env/14401

fix(CLI): support multiple env options

---

README.md

Updated link to a new YouTube video describing the dashboard and local credentials methods.

docs: Updated link to video for credentials

---

docs/providers/aws/events/apigateway.md

Closes: N/A (docs change)
I believe this was the intent of the documentation, but the example did not match the wording. I also opted to add details around `executionLogging`.
Based on:
* https://github.com/serverless/serverless/blob/c5ba682a6bc4fc96151c75cdf50cff2468d6def5/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L273-L280
* https://github.com/serverless/serverless/blob/c5ba682a6bc4fc96151c75cdf50cff2468d6def5/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L282-L284

docs(AWS API Gateway): Update how to disable access and execution logs

---

lib/configuration/variables/sources/file.js
test/unit/lib/configuration/variables/sources/file.test.js
test/unit/lib/configuration/variables/sources/fixture/file-ambiguous.json

Fix variable "file" source resolution issues

---

lib/cli/commands-schema/aws-service.js
lib/cli/commands-schema/index.js
lib/cli/commands-schema/no-service.js
lib/cli/commands-schema/service.js
test/unit/lib/cli/commands-schema/aws-service.test.js
test/unit/lib/cli/commands-schema/common-options/aws-service.test.js
test/unit/lib/cli/commands-schema/common-options/global.test.js
test/unit/lib/cli/commands-schema/common-options/service.test.js
test/unit/lib/cli/commands-schema/no-service.test.js
test/unit/lib/cli/commands-schema/service.test.js

Fix issues accidentally sneaked with  #9151 and added some sanity tests to back against regressions

CLI: Fix command schema organization

---

lib/utils/analytics/generatePayload.js
test/unit/lib/utils/analytics/generatePayload.test.js

Detects Serverless CI/CD based on env variable (based on https://gist.github.com/scouredimage/7e0c37f4065be79820296d1a23aeac2b), as well as Seed CI/CD.

feat: Detect Serverless CI/CD engine for analytics

---

docs/deprecations.md
docs/guides/monitoring/README.md
docs/providers/aliyun/guide/packaging.md
docs/providers/aws/guide/packaging.md
docs/providers/aws/guide/serverless.yml.md
docs/providers/azure/guide/packaging.md
docs/providers/azure/guide/serverless.yml.md
docs/providers/google/guide/packaging.md
docs/providers/kubeless/guide/packaging.md
docs/providers/openwhisk/guide/packaging.md
docs/providers/tencent/guide/packaging.md
lib/configSchema.js
lib/plugins/aws/provider.js
lib/plugins/create/templates/aws-clojurescript-gradle/serverless.yml
lib/plugins/create/templates/aws-go-dep/serverless.yml
lib/plugins/create/templates/aws-go-mod/serverless.yml
lib/plugins/create/templates/aws-go/serverless.yml
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-provided/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml
lib/plugins/create/templates/aws-python3/serverless.yml
lib/plugins/create/templates/aws-ruby/serverless.yml
lib/plugins/create/templates/azure-nodejs/serverless.yml
lib/plugins/create/templates/azure-python/serverless.yml
lib/plugins/create/templates/tencent-go/serverless.yml
lib/plugins/create/templates/tencent-nodejs/serverless.yml
lib/plugins/create/templates/tencent-python/serverless.yml
lib/plugins/package/lib/packageService.js
lib/plugins/package/package.js

feat(Packaging): Add patterns setting and deprecate include/exclude

---

test/unit/lib/plugins/aws/provider.test.js

test: Refactor test for `getRegion` for `aws` provider

---

test/unit/lib/plugins/aws/provider.test.js

test: Refactor test for `getStage` for `aws` provider

---

lib/plugins/aws/provider.js

Packaging: Recognize `layers[].package.patterns`

---

lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/zipService.js

Packaging: Ensure to apply dev dependency exclusion rules

---

lib/configuration/variables/sources/instance-dependent/get-ssm.js
test/unit/lib/configuration/variables/sources/instance-dependent/get-ssm.test.js

Addresses issue reported here: https://github.com/serverless/serverless/pull/9229#pullrequestreview-627382651

Variables: Ensure valid region value type in SSM resolution

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/provider.js
test/unit/lib/plugins/aws/provider.test.js

feat(AWS Lambda): Add support for `buildArgs` to `images`

---

lib/utils/analytics/generatePayload.js
test/unit/lib/utils/analytics/generatePayload.test.js

Add detection of functions defined with images + first installation timestamp
note: it should wait before corresponding backend services are deployed

feat: Account for functions with containers for analytics

---

lib/plugins/aws/invokeLocal/.gitignore

fix(AWS Local Invocation): Adjust `.gitignore` #9273.

---

lib/plugins/aws/invokeLocal/index.js

fix(AWS Local Invocation): Correctly `decompress` artifact

---

test/unit/lib/plugins/aws/provider.test.js

test: Refactor test for `getCredentials` for `aws` provider

---

lib/plugins/aws/invokeLocal/index.js

fix(AWS Local Invocation): Dont build bridge if artifact missing

---

test/unit/lib/plugins/aws/provider.test.js

test: Refactor tests for setting profile of `aws` provider

---

lib/plugins/aws/remove/lib/bucket.js
lib/plugins/aws/remove/lib/stack.js

refactor: Mark functions `async` in `plugins/aws/remove`

---

lib/classes/PluginManager.js
lib/utils/analytics/index.js
test/unit/lib/utils/analytics/index.test.js

Finishes 1. of `Local` 
Addresses: #9257

refactor: Use `async/await` in `analytics`

---

lib/plugins/aws/deployFunction.js
lib/plugins/aws/provider.js

Closes: https://github.com/serverless/typescript/issues/38

feat: Support `Fn::Split` for `vpc` properties

---

test/unit/lib/plugins/aws/provider.test.js

refactor: Refactor `aws` provider tests for prefixes

---

docs/providers/aws/guide/layers.md

This was added in #5582 but is not present in the documentation.
Added one example, taken directly from the linked issue.

docs: Document support for service-wide layers

---

lib/plugins/aws/invokeLocal/index.js

fix(AWS Local Invocation): Allow optional `package.artifact` for `java`

---

lib/classes/PluginManager.js
lib/plugins/deploy.js
lib/utils/telemetry/generatePayload.js
lib/utils/telemetry/index.js
scripts/serverless.js
test/unit/lib/plugins/aws/provider.test.js
test/unit/lib/utils/telemetry/generatePayload.test.js
test/unit/lib/utils/telemetry/index.test.js

Last "coding" piece for #9257. It was tested locally, with 50+ events in batch and also on dev environment. 
Addresses: #9257

Support other commands for telemetry

---

lib/configuration/variables/parse.js
lib/configuration/variables/resolve.js
test/unit/lib/configuration/variables/parse.test.js
test/unit/lib/configuration/variables/resolve.test.js

Variables: Clear escape slashes

---

commitlint.config.js
lib/Serverless.js
test/unit/lib/Serverless.test.js

API: Fix accidental omission of `config.servicePath`

---

lib/plugins/interactiveCli/index.js

_Reported internally_
Regression introduced with https://github.com/serverless/serverless/commit/3422a121d787fa716f708051f0bfe97644a3c1aa
No regression test at this point, as the only reliable way to test it is via direct CLI testing of interactive CLI, and we don't have yet setup prepared for that (will have to be introduced at some point)

CLI: Ensure to recognize interactive CLI command properly

---

test/unit/lib/plugins/aws/provider.test.js

test: Refactor base `aws` provider credentials test

---

docs/telemetry.md
lib/utils/telemetry/areDisabled.js

Add docs about `telemetry` and ability to disable it via `SLS_TELEMETRY_DISABLED`

---

docs/providers/aws/guide/quick-start.md

docs: Update `quick-start.md` typos

---

lib/configuration/variables/resolve-unresolved-source-types.js
scripts/serverless.js
test/unit/lib/configuration/variables/resolve-unresolved-source-types.test.js

Closes: #9355
Additionally improved main process flow inline documentation

Variables: Fix unresolved sources resolver

---

docs/providers/aws/events/event-bridge.md

As suggested in: https://github.com/serverless/serverless/commit/5183620e9e4795c3ab07d30e7386d9360a2d7eb7#commitcomment-49875530

docs: Add example on how to enable native CF for eventBridge

---

lib/cli/handle-error.js
lib/utils/is-locally-installed.js
lib/utils/telemetry/generatePayload.js
test/unit/lib/utils/telemetry/generatePayload.test.js

Make `serverless` optional for `generatePayload`

---

test/integration/custom-deployment-bucket.test.js

test(AWS Deploy): Add integration tests for custom deployment bucket

---

lib/cli/handle-error.js
scripts/serverless.js

Pass `serverless` instance to `handle-error`

---

scripts/serverless.js

Skip generating telemetry payload for help commands

Do not report telemetry for help commands

---

lib/Serverless.js
lib/utils/telemetry/generatePayload.js
test/unit/lib/utils/telemetry/generatePayload.test.js

feat(Telemetry): Add `commandOptionNames` to payload

---

lib/cli/handle-error.js
lib/utils/telemetry/anonymize-stacktrace-paths.js
lib/utils/telemetry/resolve-error-location.js
lib/utils/tokenize-exception.js
package.json
scripts/serverless.js
test/unit/lib/cli/handle-error.test.js
test/unit/lib/utils/telemetry/anonymize-stacktrace-paths.test.js
test/unit/lib/utils/telemetry/resolve-error-location.test.js
test/unit/lib/utils/tokenize-exception.test.js

Report if command failed or succeeded 

---

bin/serverless.js
lib/utils/telemetry/generatePayload.js
test/unit/lib/utils/telemetry/generatePayload.test.js

feat(Telemetry): Add `commandDurationMs` to payload

---

docs/providers/aws/events/http-api.md
lib/plugins/aws/package/compile/events/httpApi.js
test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js

fix(AWS HTTP API): Ensure to apply tags to stage

---

docs/providers/aws/events/apigateway.md
docs/providers/aws/events/http-api.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
lib/plugins/aws/provider.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js

feat(AWS API Gateway): Support disabling default endpoint

---

lib/cli/interactive-setup/index.js

Related to: https://github.com/serverless/dashboard-plugin/pull/577#pullrequestreview-658963906

refactor(CLI Onboarding): Introduce `context.history`

---

lib/cli/interactive-setup/service.js
lib/utils/downloadTemplateFromRepo.js
test/unit/lib/cli/interactive-setup/index.test.js
test/unit/lib/cli/interactive-setup/service.test.js

Addresses: https://github.com/serverless/serverless/issues/9367

Fetch templates from `serverless/examples`

---

lib/cli/commands-schema/no-service.js
lib/cli/interactive-setup/service.js
test/unit/lib/cli/interactive-setup/service.test.js

feat(CLI Onboarding): Support `template` and `template-url` options

---

lib/cli/interactive-setup/service.js

Use "Starter" not "Empty" for templates in interactive CLI

---

lib/cli/interactive-setup/service.js
package.json
test/unit/lib/cli/interactive-setup/service.test.js

Addresses: https://github.com/serverless/serverless/issues/9367

Remove initial `confirm` question from the flow

---

docs/providers/aws/cli-reference/config-tabcompletion.md
docs/providers/aws/cli-reference/config.md

Improve `autoupdate` and `tabcompletion` command docs

---

lib/cli/handle-error.js

Supplements https://github.com/serverless/serverless/pull/9519

Telemetry: Ensure to gently handle missing data in local fallback

---

docs/providers/aws/guide/variables.md
lib/configuration/variables/sources/file.js

Variables: Improve new JS function resolver communication

---

docs/providers/aws/guide/serverless.yml.md
docs/providers/aws/guide/variables.md
lib/configSchema.js
lib/configuration/variables/sources/file.js
test/unit/lib/configuration/variables/sources/file.test.js

Variables: Introduce and support project directory setting

---

scripts/serverless.js
test/integration/aws/apiGateway.test.js
test/integration/aws/apiGatewayExternal.test.js
test/integration/aws/cognitoUserPool.test.js
test/integration/aws/custom-deployment-bucket.test.js
test/integration/aws/eventBridge.test.js
test/integration/aws/functionDestinations.test.js
test/integration/aws/httpApi.test.js
test/integration/aws/infra-dependent/fileSystemConfig.test.js
test/integration/aws/infra-dependent/msk.test.js
test/integration/aws/iot.test.js
test/integration/aws/iotFleetProvisioning.test.js
test/integration/aws/provisionedConcurrency.test.js
test/integration/aws/s3.test.js
test/integration/aws/schedule.test.js
test/integration/aws/sns.test.js
test/integration/aws/sqs.test.js
test/integration/aws/stream.test.js
test/integration/aws/websocket.test.js
test/integration/plugin-install.test.js

Closes: #9578
Additionally:
- As introduced _plugin install_ integration test. Nested AWS integration test in `aws` folder
- Ensure to not report recognized sources as unrecognized with `variablesResolutionMode` turned on (addendum to https://github.com/serverless/serverless/pull/9449)

Variables: Improve unresolved sources validation

---

docs/deprecations.md

Follow up to: https://github.com/serverless/serverless/issues/9576

Documentation: Improve deprecations resasoning

---

lib/plugins/aws/lib/naming.js
test/unit/lib/plugins/aws/lib/naming.test.js

fix(AWS Cognito): Correct `logicalIds` based on triggers

---

bin/serverless.js
docs/deprecations.md

Closes: #9586
Updated nodejs version minimum requirement to v12.

refactor: NodeJS version not maintained deprecation

---

lib/plugins/aws/package/compile/events/s3/index.js
test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js

Closes: https://github.com/serverless/serverless/issues/9218

feat(AWS S3): Support CF functions for `bucket` event property

---

lib/plugins/invoke.js

this allow non-AWS providers to use `-e` to declare their environment variables for local invocation
Closes: #9452

fix(invoke): use processed options

---

docs/providers/aws/guide/variables.md

Addresses https://github.com/serverless/serverless/issues/9611#issuecomment-864150253

Documentation: Improve "ssm" resolution docs

---

docs/deprecations.md

Internally we agreed this can be improved
/cc @skierkowski

Documentation: Improve `package.patterns` deprecation doc

---

.github/workflows/validate.yml
lib/plugins/standalone.js
lib/utils/eventuallyUpdate.js
test/unit/lib/plugins/aws/package/compile/functions.test.js

refactor: Replace `fse.rename` with `fs.promises.rename`

---

lib/cli/interactive-setup/aws-credentials.js
lib/utils/resolve-region.js
lib/utils/resolve-stage.js
test/unit/lib/cli/interactive-setup/aws-credentials.test.js
test/unit/lib/cli/interactive-setup/index.test.js
test/unit/lib/utils/resolve-region.test.js
test/unit/lib/utils/resolve-stage.test.js

Support provider creation flow

---

lib/cli/interactive-setup/aws-credentials.js
lib/cli/interactive-setup/deploy.js
lib/cli/interactive-setup/index.js
lib/cli/interactive-setup/service.js
lib/utils/telemetry/generatePayload.js
scripts/serverless.js
test/unit/lib/cli/interactive-setup/aws-credentials.test.js
test/unit/lib/cli/interactive-setup/deploy.test.js
test/unit/lib/cli/interactive-setup/service.test.js
test/unit/lib/utils/telemetry/generatePayload.test.js

Add telemetry for onboarding CLI

---

lib/plugins/standalone.js
lib/utils/eventuallyUpdate.js

refactor: Replace `fse.chmod` with `fs.promises.chmod`

---

lib/plugins/create/templates/aws-go-dep/Makefile
lib/plugins/create/templates/aws-go-mod/Makefile
lib/plugins/create/templates/aws-go/Makefile

fix(Templates): Use `amd64` arch for `aws-go` template

---

lib/plugins/aws/provider.js

feat(AWS Lambda): Support `Fn::FindInMap` for `vpc` config

---

lib/cli/interactive-setup/deploy-progress-plugin.js
package.json

Related to: https://github.com/serverless/serverless/issues/9367

refactor(CLI Onboarding): Adjustments to `deploy` step output

---

lib/cli/interactive-setup/deploy.js

fix(CLI Onboarding): Do not attempt local fallback during onboarding

---

lib/plugins/aws/provider.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js

feat(AWS Lambda): Support `Fn::If` for `Principal.AWS`

---

docs/providers/aws/guide/variables.md
lib/Serverless.js
lib/configuration/variables/sources/instance-dependent/get-aws.js
scripts/serverless.js
test/unit/lib/configuration/variables/sources/instance-dependent/get-aws.test.js

Add support for `aws:region` and `aws:accountId` variables

---

lib/plugins/create/templates/openwhisk-python/serverless.yml

Related to: https://github.com/serverless/examples/pull/629

fix(Templates): Adjust `runtime` for `openwhisk-python` template

---

test/fixtures/programmatic/curated-plugins/package.json
test/fixtures/programmatic/curated-plugins/serverless.yml
test/fixtures/programmatic/curated-plugins/webpack.config.js
test/integration/curated-plugins.test.js

Test: Cover "serverless-webpack" integration

---

docs/providers/aws/events/kafka.md
lib/plugins/aws/package/compile/events/kafka.js
test/unit/lib/plugins/aws/package/compile/events/kafka.test.js

Closes: https://github.com/serverless/serverless/issues/9663

feat(AWS Lambda): Add support for `SASL/PLAIN` auth to `kafka` event

---

lib/configuration/read.js

chore: Fix typo in read.js

---

test/fixtures/programmatic/curated-plugins/package.json
test/fixtures/programmatic/curated-plugins/serverless.yml
test/integration/curated-plugins.test.js

Test: Cover `serverless-domain-manager` & `serverless-prune-plugin` plugins

---

lib/cli/handle-error.js
lib/cli/interactive-setup/index.js
lib/utils/tokenize-exception.js
scripts/serverless.js
test/unit/lib/cli/interactive-setup/index.test.js
test/unit/lib/utils/tokenize-exception.test.js

Addresses: #9367 
Before merging, corresponding backend PRs have to be merged & deployed

refactor(Telemetry): Report `commandUsage` as object

---

lib/plugins/aws/invokeLocal/runtimeWrappers/java/pom.xml

Up AWS event pom version to pull in deserialization fix

---

scripts/serverless.js

Addresses holes in logic, which could result with telemetry reports being stored multiple times for single command
(e.g. not immediately exited Ctrl-C, or Ctrl-C run when error is being processed)

Telemetry: Ensure no doubled reports in edge cases

---

.github/workflows/integrate.yml
test/integration/aws/infra-dependent/msk.test.js
test/integration/aws/sns.test.js

Improves reliability of tests, to address following integration tests fails:
- https://github.com/serverless/serverless/runs/2951533890?check_suite_focus=true SNS, CloudWatch read
- https://github.com/serverless/serverless/runs/2952652434?check_suite_focus=true, MSK, CoudWatch read
- https://github.com/serverless/serverless/runs/2964603919?check_suite_focus=true, Rate exceeded

Improve reliability of integration tests

---

lib/plugins/package/lib/packageService.js

Packaging: Fix `package.artifact` validation for S3 urls

---

docs/providers/aws/guide/serverless.yml.md

docs: Add `s3` config options to `serverless.yml.md`

---

lib/Serverless.js
lib/classes/PluginManager.js
lib/classes/Service.js

Closes: #9731
It's a quick patch that should fix this issue mostly, still proper fix will be done with https://github.com/serverless/serverless/issues/9740

CLI: Improve plugin installation handling

---

test/fixtures/programmatic/curated-plugins/.env
test/fixtures/programmatic/curated-plugins/package.json
test/fixtures/programmatic/curated-plugins/serverless.yml
test/integration/curated-plugins.test.js

Test: Cover`serverless-dotenv-plugin` and `serverless-iam-roles-per-function` with integration tests

---

package.json
test/fixtures/programmatic/curated-plugins/index-ts.ts
test/fixtures/programmatic/curated-plugins/package.json
test/integration/curated-plugins.test.js

Test: Cover `serverless-plugin-typescript` plugin

---

test/unit/lib/plugins/aws/lib/naming.test.js

refactor: fix comment typo

---

lib/utils/telemetry/index.js
test/unit/lib/cli/resolve-configuration-path.test.js
test/unit/lib/configuration/read.test.js
test/unit/lib/utils/telemetry/index.test.js

refactor: Replace `fse.unlink` with `fs.promises.unlink`

---

docs/telemetry.md

Follow up to https://github.com/serverless/utils/pull/90

Telemetry: Update notifications code documentation

---

lib/configSchema.js

Fix a typo in config schema.
ref: https://www.serverless.com/framework/docs/deprecations#notifications-mode

fix(Config Schema): Fix deprecationNotificationMode

---

lib/cli/handle-error.js
lib/configuration/variables/resolve.js
lib/utils/telemetry/generatePayload.js
scripts/serverless.js
test/unit/lib/configuration/variables/resolve.test.js
test/unit/lib/utils/telemetry/generatePayload.test.js

Detect used variable sources 

---

docs/providers/aws/events/event-bridge.md

docs: Fix typo in `event-bridge.md` docs

---

lib/utils/createFromTemplate.js
lib/utils/downloadTemplateFromRepo.js
lib/utils/fs/createZipFile.js
lib/utils/fs/dirExists.js
lib/utils/fs/fileExists.js
lib/utils/fs/readFile.js
lib/utils/fs/writeFile.js
lib/utils/getCacheFile.js
lib/utils/log/muteConsoleLog.js
lib/utils/open.js
lib/utils/yamlAstParser.js

configuring promise returning functions as async
dir: `lib/utils`
issue: #8368

refactor: Use `async` in `lib/utils`

---

lib/utils/processBackendNotificationRequest.js

refactor(CLI): Change formatting of notifications

---

test/fixtures/programmatic/apiGatewayExtended/serverless.yml

Noticed failing test (https://github.com/serverless/serverless/runs/3292286510?check_suite_focus=true) that was caused by merging https://github.com/serverless/serverless/pull/9816

test(AWS API Gateway): Fix integration test for API Gateway

---

lib/plugins/aws/deploy/lib/checkForChanges.js
lib/plugins/aws/package/compile/events/cloudWatchLog.js
test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
test/unit/lib/plugins/aws/package/compile/events/cloudWatchLog.test.js

feat(AWS Lambda): Add support for multiple subscription filters

---

lib/cli/resolve-configuration-path.js
lib/plugins/aws/invokeLocal/index.js
lib/plugins/aws/provider.js
lib/utils/create-from-local-template.js
lib/utils/ensureExists.js
lib/utils/fs/dirExists.js
lib/utils/fs/fileExists.js
lib/utils/npm-command-deferred.js
lib/utils/npmPackage/isWritable.js
scripts/pkg/upload/world.js
test/unit/lib/plugins/aws/configCredentials.test.js

refactor: Replace `fse.stat` with `fs.promises.stat`

---

lib/utils/telemetry/generatePayload.js
package.json
test/unit/lib/utils/telemetry/generatePayload.test.js

Blocked by https://github.com/serverless/utils/pull/100

refactor(Telemetry): Recognize `notificationsMode`

---

docs/cn/providers/tencent/components/README.md
docs/cn/providers/tencent/components/high-level-components/README.md
docs/cn/providers/tencent/components/high-level-components/custom-domain-HTTPS.md
docs/deprecations.md
docs/guides/profiles.md
docs/providers/spotinst/guide/intro.md
docs/providers/tencent/events/COS.md

Q1: Provide a link to the corresponding issue
• made corrections to the typos i have found in the documentations.

docs: Fix typos in docs

---

docs/providers/aws/events/event-bridge.md
lib/plugins/aws/customResources/resources/eventBridge/handler.js
lib/plugins/aws/customResources/resources/eventBridge/lib/eventBridge.js
lib/plugins/aws/package/compile/events/eventBridge/index.js
test/unit/lib/plugins/aws/package/compile/events/eventBridge/index.test.js

ISSUE: https://github.com/serverless/serverless/issues/9864

feat(AWS EventBridge): Support disabling a rule

---

lib/cli/interactive-setup/dashboard-login.js
lib/cli/interactive-setup/dashboard-set-org.js
test/unit/lib/cli/interactive-setup/dashboard-login.test.js

Reported internally, improve messaging when user is not logged in + minor improvements to question with organization setup.

feat(CLI Onboarding): Improve onboarding messaging

---

docs/providers/aws/events/cloudfront.md

https://aws.amazon.com/about-aws/whats-new/2021/04/lambda-edge-support-node14/

docs: Update `cloudfront.md`

---

lib/plugins/aws/invokeLocal/index.js

feat(AWS Local Invocation): Support `python3.9` runtime

---

docs/providers/aws/events/cloudfront.md
lib/plugins/aws/package/compile/events/cloudFront.js
test/unit/lib/plugins/aws/package/compile/events/cloudFront.test.js

feat(AWS CloudFront): Support `behavior.CachePolicyId`

---

docs/providers/aws/events/sqs.md

The previous title had confusing wording. Now it starts from the use case and should be much clearer to users not familiar with Lift.

docs: Improve title in SQS docs

---

lib/plugins/aws/invokeLocal/index.js

refactor: Replace `fse.access` with `fs.promises.access`

---

lib/plugins/aws/package/compile/events/apiGateway/index.js
lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.js

fix(AWS API Gateway): Ensure proper `RequestValidator` name

---

package.json
scripts/serverless.js

Addresses: #9860 
Ensure to indefinitely remove progress bar at certain time events (error, interrupt or finalization of command processing)

CLI: Ensure to clear progress in expected time points

---

docs/environment-variables.md

Addresses: https://github.com/serverless/serverless/issues/9920

Documentation: Improve `dotenv` setup instructions

---

lib/Serverless.js
lib/plugins/aws/info/display.js
test/unit/lib/plugins/aws/info/display.test.js

CLI: Internal service outputs registry

---

lib/configuration/read.js
lib/configuration/variables/sources/file.js
lib/plugins/aws/invokeLocal/index.js
lib/utils/fs/readFile.js
scripts/test/integration-setup/index.js
test/unit/lib/plugins/package/lib/packageService.test.js
test/unit/lib/utils/fs/writeFile.test.js
test/unit/lib/utils/fs/writeFileSync.test.js
test/utils/integration.js

refactor: Replace `fse.readFile` with `fs.promises.readFile`

---

docs/providers/aws/events/event-bridge.md
lib/plugins/aws/package/compile/events/eventBridge/index.js
test/unit/lib/plugins/aws/package/compile/events/eventBridge/index.test.js

feat(AWS EventBridge): Support `deadLetterQueue` and `retryPolicy`

---

lib/classes/PluginManager.js
lib/plugins/aws/package/compile/events/apiGateway/index.js
lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js

fix(AWS API Gateway): Ensure consistent default for `cors` conf

---

lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/lib/cleanupS3Bucket.js
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/uploadArtifacts.js
lib/plugins/aws/info/display.js
lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/lib/updateStack.js
lib/plugins/package/lib/packageService.js
lib/plugins/package/lib/zipService.js

Addresses: #9860
First iteration of verbose mode in `deploy` for modern logs, it will require adjustments as current output is definitely not the final version.

feat(CLI): First iteration of support for `verbose` mode in `deploy`

---

lib/cli/interactive-setup/service.js

Reported internally, related to: https://github.com/serverless/serverless/pull/9777

feat(CLI Onboarding): Switch to `httpApi`-based templates

---

lib/classes/PluginManager.js
lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/lib/checkForChanges.js

Addresess: https://github.com/serverless/serverless/issues/9860

feat(CLI): Add timer to final command message in modern logs

---

lib/utils/logDeprecation.js
package.json

Addresses: https://github.com/serverless/serverless/issues/9860

feat(CLI): Add deprecation summary for modern logs

---

lib/classes/PluginManager.js
lib/plugins/aws/package/index.js

Addresses: https://github.com/serverless/serverless/issues/9860

feat(CLI): Modern logs for `package` command

---

lib/classes/PluginManager.js
lib/cli/commands-schema/aws-service.js
lib/cli/commands-schema/service.js
lib/plugins/aws/deploy/index.js
lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/deploy/lib/uploadArtifacts.js
lib/plugins/aws/info/index.js
lib/plugins/aws/lib/updateStack.js
lib/plugins/aws/package/index.js
lib/plugins/package/lib/packageService.js
package.json

1. Revert from an approach where main process events were configured externally of internal logic, as that method didn't allow any conditional handling, which introduced difficult to workaround issues
2. Rely on generalized handling of main process events as introduced with `@serverless/utils@5.14.0`. Through that all main process events marked to be reflected in feed are automatically reflected (no need to configure additional verbose logs aside)

CLI improve main progress events handling

---

lib/plugins/aws/deployFunction.js
lib/plugins/package/package.js
test/unit/lib/plugins/aws/deployFunction.test.js

CLI: Modern logs for `deploy function` command

---

lib/plugins/aws/info/index.js
lib/plugins/aws/logs.js

CLI: Modern logs for `info` and `logs` commands

---

docs/README.md

Leftover use of "pro dashboard" in README

---

lib/cli/commands-schema/aws-service.js
lib/cli/render-help/command.js
lib/cli/render-help/general.js
lib/cli/render-help/generate-command-usage.js
lib/cli/render-help/interactive-setup.js
lib/cli/render-help/options.js
lib/plugins/aws/deploy/index.js
lib/plugins/aws/deployFunction.js
lib/plugins/aws/package/index.js
package.json

Addresses #9860 
Additionally adapted notice level style decorators as introduced in `@serverless/utils`

CLI: Modern help output

---

lib/Serverless.js
package.json
scripts/serverless.js

Plugins: Ensure to keep `options` as passed to plugins up to date

---

lib/plugins/aws/deployList.js
test/unit/lib/plugins/aws/deployList.test.js

CLI: Modern logs for `deploy list` and `deploy list functions`

---

commands/plugin-install.js
commands/plugin-uninstall.js
lib/plugins/plugin/uninstall.js
scripts/serverless.js
test/unit/commands/plugin-uninstall.test.js

refactor(Plugins): Seclude `plugin uninstall` standalone command

---

commands/plugin-install.js
commands/plugin-uninstall.js
lib/Serverless.js
lib/cli/handle-error.js
lib/plugins/plugin/install.js
lib/plugins/plugin/lib/utils.js
lib/plugins/plugin/search.js
lib/plugins/plugin/uninstall.js
lib/utils/telemetry/generatePayload.js
test/unit/lib/plugins/plugin/lib/utils.test.js
test/unit/lib/plugins/plugin/search.test.js

Addresses #9860 
Additionally fixed handling of corner-case where local installation of `serverless` is removed during a command run

CLI: Modern logs for `plugin ...` commands

---

docs/providers/aws/guide/plugins.md

• Fixes typo in name of example Plugin class from `MyPugin` to `MyPlugin`

Fix typo in providers/aws/guide/plugins.md

---

lib/Serverless.js
lib/cli/interactive-setup/aws-credentials.js
lib/cli/interactive-setup/dashboard-login.js
lib/cli/interactive-setup/dashboard-set-org.js
lib/cli/interactive-setup/deploy.js
lib/cli/interactive-setup/index.js
lib/cli/interactive-setup/service.js
lib/cli/interactive-setup/utils.js
lib/cli/render-help/general.js
lib/cli/render-help/interactive-setup.js
lib/cli/render-version.js
lib/plugins/plugin/lib/utils.js
package.json
test/unit/lib/cli/interactive-setup/dashboard-login.test.js
test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js

CLI: Modern logs for interactive setup

---

CHANGELOG.md
package.json
test/integration/aws/iotFleetProvisioning.test.js

Additionally added a temporary skip on IOT integration test, which started to fail today, and so far reason is unknown (AWS support was contacted about)

Release v2.61.0

---

lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/remove/index.js
lib/plugins/aws/remove/lib/bucket.js
lib/plugins/aws/remove/lib/ecr.js
lib/plugins/aws/remove/lib/stack.js

Addresses: #9860
Supports both "normal" and "verbose" modes

refactor(CLI): Modern logs for `remove` command

---

lib/plugins/aws/deploy/index.js
lib/plugins/aws/info/index.js

Small improvement requested internally

CLI: Improve main progress message

---

lib/plugins/create/templates/aws-nodejs-typescript/package.json

Use new version 2 of `@middy/core` and `@middy/http-json-body-parser` for `aws-nodejs-typescript` template

Update middy to next major on aws-nodejs-typescript template

---

lib/plugins/create/templates/aws-nodejs-typescript/src/functions/hello/index.ts

Implement new `http.request.schemas` instead of `http.request.schema` as per https://github.com/serverless/serverless/blob/master/docs/deprecations.md#aws-api-gateway-schemas for `aws-nodejs-typescript` template

Use new api gateway property names in aws-nodejs-typescript template

---

README.md

Simple documentation update (no corresponding issue):
Updated readme to match accessibility criteria.

docs: change grammar in readme for accessibility purposes

---

docs/providers/aws/cli-reference/invoke-local.md
docs/providers/aws/guide/functions.md
lib/plugins/create/templates/aws-clojure-gradle/serverless.yml
lib/plugins/create/templates/aws-clojurescript-gradle/serverless.yml
lib/plugins/create/templates/aws-csharp/serverless.yml
lib/plugins/create/templates/aws-fsharp/serverless.yml
lib/plugins/create/templates/aws-go-dep/serverless.yml
lib/plugins/create/templates/aws-go-mod/serverless.yml
lib/plugins/create/templates/aws-go/serverless.yml
lib/plugins/create/templates/aws-groovy-gradle/serverless.yml
lib/plugins/create/templates/aws-java-gradle/serverless.yml
lib/plugins/create/templates/aws-java-maven/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-gradle-kts/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-gradle/serverless.yml
lib/plugins/create/templates/aws-kotlin-jvm-maven/serverless.yml
lib/plugins/create/templates/aws-kotlin-nodejs-gradle/serverless.yml
lib/plugins/create/templates/aws-nodejs-docker/serverless.yml
lib/plugins/create/templates/aws-nodejs/serverless.yml
lib/plugins/create/templates/aws-provided/serverless.yml
lib/plugins/create/templates/aws-python-docker/serverless.yml
lib/plugins/create/templates/aws-python/serverless.yml
lib/plugins/create/templates/aws-python3/serverless.yml
lib/plugins/create/templates/aws-ruby/serverless.yml
lib/plugins/create/templates/aws-scala-sbt/serverless.yml

Reported internally, ensure that modern IAM-related syntax is used in docs & templates

Ensure new iam role syntax is used

---

lib/plugins/aws/deploy/index.js

Follows internal agreements
Accompanied by https://github.com/serverless/dashboard-plugin/pull/639

CLI: Expose dashboard provider name in deploy tagline log

---

docs/providers/google/guide/credentials.md

docs: Fix typo in `credentials`

---

lib/Serverless.js

refactor: fix typo in Serverless.js

---

docs/deprecations.md
docs/providers/aws/guide/functions.md
lib/plugins/aws/deploy/index.js
lib/plugins/aws/package/compile/functions.js
test/fixtures/programmatic/apiGateway/serverless.yml
test/fixtures/programmatic/checkForChanges/serverless.yml
test/fixtures/programmatic/curated-plugins-python/serverless.yml
test/fixtures/programmatic/curated-plugins/serverless.yml
test/fixtures/programmatic/function/serverless.yml
test/fixtures/programmatic/functionCloudFront/serverless.yml
test/fixtures/programmatic/functionLayers/serverless.yml
test/fixtures/programmatic/httpApi/serverless.yml
test/fixtures/programmatic/httpApiCatchAll/serverless.yml
test/fixtures/programmatic/httpApiExport/serverless.yml
test/fixtures/programmatic/invocation/serverless.yml
test/fixtures/programmatic/layer/serverless.yml
test/fixtures/programmatic/multiService/serviceA/serverless.yml
test/fixtures/programmatic/packageArtifact/serverless.yml
test/fixtures/programmatic/packageArtifactInServerlessDir/serverless.yml
test/fixtures/programmatic/packaging/serverless.yml
test/fixtures/programmatic/plugin/serverless.yml
test/fixtures/programmatic/requestParameters/serverless.yml
test/fixtures/programmatic/requestSchema/serverless.yml
test/integrationPackage/fixtures/artifact/serverless.yml
test/integrationPackage/fixtures/individually-function/serverless.yml
test/integrationPackage/fixtures/individually/serverless.yml
test/integrationPackage/fixtures/regular/serverless.yml
test/unit/lib/classes/Service.test.js
test/unit/lib/plugins/aws/package/compile/functions.test.js

BREAKING CHANGE: Default lambda hashing algorithm was changed to `20201221`

feat(AWS Lambda): Change default hashing algorithm

---

lib/plugins/create/templates/aws-java-maven/pom.xml
lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml

Update jackson dependencies to a secure version

---

lib/plugins/aws/utils/credentials.js
lib/plugins/aws/utils/resolveCfImportValue.js
lib/plugins/aws/utils/resolveCfRefValue.js

Addresses: [#{8368}](https://github.com/serverless/serverless/issues/8368)
Configures all promise-related functions as async functions.

Refactor lib/plugins/aws/utils with Async

---

docs/guides/upgrading-v3.md

docs: Address #10242 to clarify v3 instructions

---

docs/providers/aws/guide/variables.md
lib/configuration/variables/sources/instance-dependent/get-ssm.js
test/unit/lib/configuration/variables/sources/instance-dependent/get-ssm.test.js

Closes: [https://github.com/serverless/serverless/issues/10314](url)

ssm: Adding noDecrypt param support to SSM #10314

---

docs/providers/aws/guide/variables.md

Small fixes to the Serverless Variables documentation page.

docs: Improve the Serverless Variables page

---

test/unit/lib/plugins/aws/package/compile/events/cloudFront.test.js
test/unit/lib/plugins/aws/package/compile/events/sqs.test.js
test/unit/lib/plugins/aws/package/compile/events/stream.test.js
test/unit/lib/plugins/aws/package/compile/events/websockets/index.test.js

Called out by community needed to accomplish https://github.com/serverless/serverless/issues/8396

Pave path for tests refactors

---

lib/plugins/create/templates/aws-java-maven/pom.xml
lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml

Closes: https://github.com/serverless/serverless/issues/10337

fix(Plugins): Upgrade log4j to version 2.15.0

---

lib/plugins/aws/customResources/index.js
test/unit/lib/plugins/aws/customResources/index.test.js

upgrade node to 14 in adding custom resource

---

lib/plugins/create/templates/aws-kotlin-jvm-gradle/build.gradle

Fixes added to log4j to address the zero day attack vulnerability. 
Closes: #10370

fix(Templates): Upgrade `log4j` in `aws-kotlin-jvm-gradle`

---

lib/configuration/variables/index.js

Needed for dashboard plugin variables test refactor

Variables: Support custom sources in internal resolver

---

docs/deprecations.md

Add missing note informing that deprecation was dropped

Documentation: Update deprecations docs

---

lib/plugins/aws/invokeLocal/runtimeWrappers/java/pom.xml
lib/plugins/create/templates/aws-java-maven/pom.xml
lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml

fix(AWS Local Invocation): Upgrade log4j to version 2.17.0

---

docs/providers/aws/events/apigateway.md

Documenation: AWS API Gateway: Fix binary response example

---

scripts/serverless.js

fix: Typo in TTY error message

---

docs/guides/providers.md

Remove redundant `s3:ListBucket` permission from AWS policy code snippet located at https://www.serverless.com/framework/docs/guides/providers

docs: Remove redundant permission from IAM code snippet

---

docs/deprecations.md
docs/getting-started.md
lib/cli/interactive-setup/aws-credentials.js
lib/cli/interactive-setup/utils.js
scripts/serverless.js
test/unit/lib/cli/interactive-setup/aws-credentials.test.js

Steven tried the whole "getting started" experience and noted some feedback on different wording (docs, CLI text, etc.).
This PR contains various wording improvements.

Various wording improvements

---

docs/guides/cicd/README.md
docs/guides/dashboard.md
docs/guides/parameters.md
docs/guides/plugins/README.md
docs/providers/aws/guide/variables.md

Documentation for #10264 
**Note:** this new feature will be available in v3.

docs: Stage parameters

---

docs/providers/aws/guide/serverless.yml.md

docs: Add stage parameters to the serverless.yml reference

---

lib/plugins/aws/package/compile/events/cloudFront.js
lib/plugins/aws/package/compile/events/eventBridge/index.js
lib/plugins/aws/provider.js

Related to: https://github.com/serverless/serverless/pull/10448

fix(Config Schema): Address invalid schema definitions

---

lib/plugins/aws/deploy/lib/createStack.js
lib/plugins/aws/lib/monitorStack.js
lib/plugins/aws/lib/updateStack.js

Reported internally, take advantage of ChangeSet implementation to improve the way we show progress for deploy command

refactor(CLI): Improve progress for CloudFormation updates

---

lib/classes/Service.js
lib/configSchema.js

A supplement to: https://github.com/serverless/serverless/pull/10156 (I'd add it to same commit)

v3: Cleanup service schema validation

---

lib/classes/ConfigSchemaHandler/resolveAjvValidate.js

After running the whole test suite, it appeared that the actual issue reported https://github.com/ajv-validator/ajv/issues/1390 still happens.
Patch as proposed at https://github.com/ajv-validator/ajv/issues/1390#issuecomment-763138202 is confirmed to fix that, therefore pushing it into our setup

v3: Improve AJV integration

---

lib/plugins/create/templates/aws-java-maven/pom.xml
lib/plugins/create/templates/aws-kotlin-jvm-gradle-kts/build.gradle.kts
lib/plugins/create/templates/aws-kotlin-jvm-gradle/build.gradle
lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml
lib/plugins/create/templates/aws-scala-sbt/build.sbt

Yes, yet another vulnerability. 😭

fix(Templates): Upgrade `log4j` to `2.17.1`

---

README.md
docs/providers/aws/guide/intro.md

docs: Add `ts-node` dependency warning to README

---

docs/guides/dashboard.md

docs: Fix links

---

lib/cli/interactive-setup/dashboard-set-org.js

CLI: Improve user message

---

lib/plugins/aws/provider.js

docs: Fix `initialize` hook reference in comment

---

docs/deprecations.md
docs/providers/aws/guide/serverless.yml.md
docs/providers/aws/guide/variables.md
lib/classes/Service.js
lib/configSchema.js
lib/configuration/variables/sources/file.js
lib/configuration/variables/sources/instance-dependent/get-ssm.js
test/fixtures/cli/variables/serverless.yml
test/fixtures/programmatic/curated-plugins/package.json
test/integration/curated-plugins.test.js
test/integration/plugin-install.test.js
test/unit/lib/configuration/variables/eventually-report-resolution-errors.test.js
test/unit/lib/configuration/variables/sources/file.test.js
test/unit/lib/configuration/variables/sources/instance-dependent/get-ssm.test.js
test/unit/scripts/serverless.test.js

Changes that should be part of #10512.
Additionally, upgraded all plugins in a curated plugins integration test.
_Most of the commits will be integrated into existing commits_

v3: Additional changes related to variables resolver switch

---

docs/providers/aws/guide/serverless.yml.md

Noticed when reviewing https://github.com/serverless/serverless/pull/10468
_(will be merged into corresponding commits)_

v3: Configuration reference cleanup

---

lib/cli/handle-error.js
scripts/serverless.js
test/unit/lib/cli/handle-error.test.js

After local fallback handling was simplified, also internal processing flow can be simplified, this PR tackles that.
- Remove discovered old local fallback handling left over
- Unify final processing steps handling into single function
- Seclude handling of uncaught exception from generic error handlier

v3: CLI: Simplify internal flow

---

lib/classes/ConfigSchemaHandler/index.js
lib/classes/Service.js
lib/plugins/aws/package/compile/events/eventBridge/index.js
lib/plugins/aws/package/compile/functions.js
lib/plugins/package/package.js

Slight tweaks of the deprecation messages that will be in effect in v3.

feat: Clarify deprecation messages for v3

---

lib/cli/interactive-setup/dashboard-set-org.js
lib/cli/interactive-setup/deploy.js
test/unit/lib/cli/interactive-setup/index.test.js

Reported internally, minor wording adjustments

refactor(CLI Onboarding): Minor wording adjustments

---

lib/plugins/create/templates/aws-nodejs-typescript/package.json

fix(Templates): Update dependencies of `aws-nodejs-typescript` to v3 

---

lib/plugins/aws/provider.js

add Jakarta region to supported list

---

test/integration/aws/infra-dependent/msk.test.js

test: Fix `msk` integration test

---

CHANGELOG.md
docs/guides/upgrading-v3.md

docs: Reference changeset-related iam permissions

---

docs/configuration-validation.md

Bring clarity to configValidationMode options. The "error" option was undocumented.

docs: Describe `configValidationMode` options

---

docs/guides/upgrading-v3.md

Reported: https://github.com/serverless/serverless/pull/10636#issuecomment-1031693159

docs: Mention need for `cloudformation:DescribeChangeSet`

---

lib/utils/telemetry/generate-payload.js
package.json
scripts/serverless.js
test/unit/lib/utils/telemetry/generate-payload.test.js

fix: Improve detection of `tty`

---

lib/plugins/aws/remove/lib/bucket.js
test/unit/lib/plugins/aws/remove/index.test.js

fix(AWS Deploy): Add descriptive error if S3 bucket cant be cleaned

---

docs/guides/cicd/mono-repo.md

Documentation Update:
Fixed few errors in mono-repo.md
P.S: Thanks for all the efforts that has been put up in this framework.

docs: Update `mono-repo.md`

---

package.json
test/integration-basic.test.js
test/integration/aws/api-gateway-external.test.js
test/integration/aws/api-gateway.test.js
test/integration/aws/custom-deployment-bucket.test.js
test/integration/aws/function.test.js
test/integration/aws/http-api.test.js
test/integration/aws/infra-dependent/active-mq.test.js
test/integration/aws/infra-dependent/file-system-config.test.js
test/integration/aws/infra-dependent/msk.test.js
test/integration/aws/infra-dependent/rabbit-mq.test.js
test/integration/aws/iot-fleet-provisioning.test.js
test/integration/aws/websocket.test.js
test/utils/api-gateway.js
test/utils/cloudformation.js
test/utils/cognito.js
test/utils/dynamodb.js
test/utils/event-bridge.js
test/utils/iot.js
test/utils/kinesis.js
test/utils/misc.js
test/utils/s3.js
test/utils/sns.js
test/utils/sqs.js
test/utils/websocket.js

Upgrade `@serverless/test` to `v10` along with changes to `awsRequest` usage. I've tested the integration tests locally.

refactor: Upgrade to `@serverless/test` in `v10`

---

lib/cli/ensure-supported-command.js

Reported internally, documentation is upgraded as a part of https://github.com/serverless/serverless/pull/10734/files#diff-4bc8f03915f15ecf2cb9965592fcf933bb06986003613b5633a8dea7962c31a9R249

Improve CLI options deprecation message

---

lib/plugins/aws/package/compile/events/api-gateway/lib/rest-api.js
test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/rest-api.test.js

Closes: #10709
Hello.
Thank you for providing excellent library. 
I'm using this framework in my work, so I'd like to contribute.
Attachment shows before fixing(below one) and after fixing (above one).
Could you please have a moment to take a look at it?

fix(AWS API Gateway): Properly apply `description` to REST API

---

lib/cli/handle-error.js
test/unit/lib/cli/handle-error.test.js
test/unit/scripts/serverless.test.js

refactor: Log environment details of error to stderr

---

lib/classes/console.js

Additional headers are needed for the ingestion server
/cc @Danwakeem

Console: Add extra needed headers for ingestion requests

---

lib/configuration/variables/sources/file.js
test/unit/lib/configuration/variables/sources/file.test.js
test/unit/lib/configuration/variables/sources/fixture/file.cjs

feat(Variables): Add support for `csj` in `file` source

---

lib/cli/commands-schema/no-service.js
lib/cli/interactive-setup/dashboard-login.js
lib/cli/interactive-setup/utils.js
package.json

refactor(Console): Support login with Console

---

lib/cli/commands-schema/no-service.js
lib/cli/interactive-setup/dashboard-login.js
lib/cli/interactive-setup/dashboard-set-org.js
lib/cli/interactive-setup/utils.js
test/fixtures/programmatic/aws-loggedin-console-service/.serverlessrc
test/fixtures/programmatic/aws-loggedin-console-service/serverless.yml
test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js

feat(CLI Onboarding): Support `--console` flag

---

lib/cli/interactive-setup/deploy.js

First step to improve proper variables resolution in interactive deploy - these changes ensure that all our recommended templates can be successfully deployed. In the future it needs to be expanded to handle all variable sources (from potential plugins as well). 
Related: https://github.com/serverless/examples/issues/683#issuecomment-1055503139

fix(CLI Onboarding): Ensure variables resolution for templates

---

lib/cli/commands-schema/no-service.js
package.json

refactor: Recognize `logout` as service-aware command

---

lib/plugins/aws/provider.js

refactor(AWS Lambda): Support `provisionedConcurrency` set to `0` 

---

lib/cli/run-serverless-tencent.js

We have set up CDN for the standalone files to speed up the downloading process
Related PR: https://github.com/serverless/serverless-tencent/pull/154

feat: Update Tencent CLI standalone download URL

---

lib/classes/console.js

Console: Communicate new token implications with verbose mode

---

lib/plugins/aws/invoke-local/runtime-wrappers/java/pom.xml

fix(AWS Local Invocation): Remove log4j dependency from java wrapper

---

lib/cli/commands-schema/aws-service.js
lib/cli/commands-schema/no-service.js
lib/cli/commands-schema/service.js
lib/cli/resolve-input.js
test/unit/scripts/serverless.test.js

fix(CLI): Ensure proper resolution of options for service commands

---

docs/providers/aws/guide/functions.md

This fixes the markdown error in functions.md

docs: Fix markdown issue in `functions.md`

---

lib/plugins/aws/provider.js
test/unit/lib/plugins/aws/package/compile/functions.test.js

Closes: #10058
referred to this commit. (https://github.com/serverless/serverless/commit/63743ade31207049eee1811203db5622bc510f1a)

feat(AWS Lambda): Recognize `Fn::If` for properties of `vpc`

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/lib/merge-iam-templates.js
lib/plugins/aws/provider.js
test/unit/lib/plugins/aws/package/lib/merge-iam-templates.test.js

Closes: #10828
referred to the logic of assigning `memorySize` (https://github.com/serverless/serverless/blob/main/lib/plugins/aws/package/compile/functions.js#L179)

feat(AWS Lambda): Support `logRetentionInDays` per function

---

docs/guides/providers.md

Found typo on docs/guides/providers.md

docs: Fix typo in `docs/guides/providers.md`

---

docs/providers/aws/guide/functions.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/functions.js
lib/plugins/aws/provider.js
test/unit/lib/plugins/aws/package/compile/functions.test.js

feat(AWS Lambda): Support `ephemeralStorageSize`

---

CHANGELOG.md
package.json

Release v3.10.1

---

scripts/serverless.js

fix(CLI): Do not attempt to resolve full config for `login`

---

lib/configuration/variables/sources/file.js
test/unit/lib/configuration/variables/sources/file.test.js
test/unit/lib/configuration/variables/sources/fixture/file-property-promise.js

Fixes: #10948
I consider this as a bug fix, as old resolver supported that

Variables: Ensure support for promise properties at `file` source

---

test/unit/lib/plugins/aws/package/compile/functions.test.js

test: `runServerless`-based tests for "Version hash resolution"

---

bin/serverless.js
lib/cli/run-compose.js
lib/cli/triage.js
test/unit/lib/cli/triage/fixtures/@serverless/compose/js/project/serverless-compose.js
test/unit/lib/cli/triage/fixtures/@serverless/compose/json/project/serverless-compose.json
test/unit/lib/cli/triage/fixtures/@serverless/compose/ts/project/serverless-compose.ts
test/unit/lib/cli/triage/fixtures/@serverless/compose/yaml/project/serverless-compose.yaml
test/unit/lib/cli/triage/fixtures/@serverless/compose/yml/project/serverless-compose.yml
test/unit/lib/cli/triage/index.test.js

refactor: Enable triage process to run `@serverless/compose`

---

docs/guides/cicd/README.md
docs/guides/compose.md
docs/guides/plugins/README.md

This introduces documentation for Serverless Framework Compose, a new feature we discussed in #10753 
This PR should be merged next week, as we aim at releasing this new feature next week. Read the related issue for more details.
Addresses #10753

Document Serverless Framework Compose

---

docs/guides/compose.md

Last minute fixes to the docs.

docs: Fix Compose documentation

---

docs/providers/aws/guide/layers.md

```~/code » sls --version
Framework Core: 3.15.2
Plugin: 6.2.2
SDK: 4.3.2```

docs: Use `!Ref LambdaLayer` instead of { Ref: LambdaLayer }

---

docs/menu.json

docs: Fix URL in documentation menu

---

docs/tutorial.md

Follow-up of https://github.com/serverless/serverless/pull/10915

docs: Change page title with valid YAML

---

docs/providers/aws/guide/intro.md
docs/providers/aws/guide/services.md

I went over these pages:
- https://www.serverless.com/framework/docs/providers/aws/guide/intro
- https://www.serverless.com/framework/docs/providers/aws/guide/services
and tried, as for others, to simplify them and improve them.

docs: Improve and reword the "Concepts" page

---

lib/plugins/aws/package/compile/functions.js
test/unit/lib/plugins/aws/package/compile/functions.test.js

fix(AWS Lambda): Ensure proper `DependsOn` settings when `url: true`

---

lib/utils/telemetry/generate-payload.js
test/unit/lib/utils/telemetry/generate-payload.test.js

Recognize `SLS_COMPOSE`, related PR: https://github.com/serverless/compose/pull/126

refactor(Telemetry): Recognize `isUsingCompose`

---

lib/plugins/aws/deploy/lib/check-for-changes.js
test/unit/lib/plugins/aws/deploy/lib/check-for-changes.test.js

fix(AWS Deploy): Ensure to only remove specific stage deploy artifacts

---

lib/plugins/aws/provider.js

fix: Recognize `Fn::Select` in `environment` config schema

---

lib/cli/parse-args.js

Improve error message for CLI param validation

---

lib/cli/triage.js
test/unit/lib/cli/triage/index.test.js

refactor(CLI): Recognize `--help` for `compose` triage

---

docs/providers/aws/events/apigateway.md
docs/providers/aws/events/http-api.md
lib/plugins/aws/package/compile/events/api-gateway/lib/validate.js
lib/plugins/aws/package/compile/events/http-api.js
lib/plugins/aws/package/compile/functions.js
test/fixtures/programmatic/api-gateway-extended/serverless.yml
test/integration/aws/api-gateway.test.js
test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/validate.test.js
test/unit/lib/plugins/aws/package/compile/functions.test.js

feat: Add `X-Amzn-Trace-Id` to default CORS headers

---

CONTRIBUTING.md

Removed reference to "Anatomy of a Framework", and made minor syntax and punctuation changes to CONTRIBUTING.md.

docs: Minor changes to `CONTRIBUTING.md`

---

lib/plugins/aws/deploy-list.js
lib/plugins/aws/deploy/lib/check-for-changes.js
lib/plugins/aws/deploy/lib/cleanup-s3-bucket.js
lib/plugins/aws/lib/check-if-bucket-exists.js
lib/plugins/aws/remove/lib/bucket.js
lib/plugins/aws/rollback.js
test/unit/lib/plugins/aws/deploy/index.test.js
test/unit/lib/plugins/aws/deploy/lib/check-for-changes.test.js
test/unit/lib/plugins/aws/remove/index.test.js
test/unit/lib/plugins/aws/rollback.test.js

In some cases, the message returned by AWS SDK is very vague and this PR aims to improve it in a few places. 
Related: https://github.com/serverless/serverless/issues/11161
Related: https://github.com/serverless/serverless/discussions/11190#discussioncomment-3057388

fix(AWS Deploy): Improve vague S3-related access errors

---

docs/deprecations.md

This is to fix a spelling error in documentation
environement -> environment
Q1: Provide a link to the corresponding issue
This does not correspond to an issue.

minor typo in example

---

lib/plugins/aws/provider.js

Fix for https://github.com/serverless/serverless/issues/11226
Closes: #11226

Increase lambda layer runtime limit to 15

---

lib/plugins/aws/deploy-function.js
test/unit/lib/classes/console.test.js

Console: Keep currently attached layers with `function deploy`

---

CONTRIBUTING.md

… v14, rather than v12.
Making a note in CONTRIBUTING.MD that development is preferred in node v14, vs node v14; See: https://github.com/serverless/serverless/issues/11249

docs: Improve `CONTRIBUTING.md`

---

CONTRIBUTING.md

Small changes to CONTRIBUTING.md; Added a "Getting Started" section.

docs: Add a "Getting Started" section to CONTRIBUTING.md

---

docs/menu-builder.html

I've closed the survey and removed the link from the online docs.

docs: Remove link to the serverless survey

---

lib/plugins/aws/custom-resources/resources/utils.js

refactor(AWS CloudFormation) Add AWS SDK logging for custom resources

---

CONTRIBUTING.md

Minor adjustments to contributing docs

docs: Minor `CONTRIBUTING.md` adjustments

---

test/README.md

Minor updates to `test/README.md`

docs: Small adjustments to `test/README.md`

---

RELEASE_PROCESS.md

docs: Improve `RELEASE_PROCESS.md`

---

test/utils/api-gateway.js
test/utils/cloudformation.js
test/utils/cognito.js
test/utils/dynamodb.js
test/utils/event-bridge.js
test/utils/iot.js
test/utils/kinesis.js
test/utils/misc.js
test/utils/s3.js
test/utils/sns.js
test/utils/sqs.js
test/utils/websocket.js

`test/utils`
Addresses: https://github.com/serverless/serverless/issues/8368

Refactor test/utils with Async

---

docs/guides/monitoring/README.md

docs: Fix typo in documentation

---

lib/plugins/aws/metrics.js
lib/plugins/aws/package/compile/events/api-gateway/lib/hack/disassociate-usage-plan.js

- Fix regression introduced with https://github.com/serverless/serverless/pull/11271
- Remove obsolete comment added with https://github.com/serverless/serverless/pull/11272

Fix to `.flat()` refactor

---

lib/utils/log-deprecation.js

fix: 11402 add in a try catch block for copy of the healthcheck

---

lib/plugins/aws/provider.js

feat: Extend AWS provider schema to support Fn::ToJsonString in environment variable

---

lib/plugins/aws/info/display.js

Console: Ensure errorneus resolution of url does not break deployments

---

lib/plugins/package/package.js

Avoid null error of package

---

lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js
package.json

Based on #11517 and fully addresses this issue.
Closes: #11517

Avoid JSON parsing error during "ensure-valid-bucket-exists.

---

docs/providers/aws/guide/deploying.md

Grammar update

---

lib/utils/import-esm.js

Improve input path handling, as suggested at https://github.com/serverless/serverless/pull/11586#discussion_r1044169468

Support relative paths in `import-esm` util

---

docs/tutorial.md

Issue 11616: Fix Typo in README

---

docs/providers/aws/events/cognito-user-pool.md

Closes: N/A
Documentation spelling error.

Update spelling error in cognito-user-pool.md

---

lib/configuration/variables/sources/env.js
test/unit/lib/configuration/variables/sources/env.test.js

fix: Sources defined empty env vars

---

lib/plugins/aws/package/compile/events/cloud-front.js
test/unit/lib/plugins/aws/package/compile/events/cloud-front.test.js

feat(AWS CloudFront): Add ResponseHeadersPolicyId to behavior schema

---

docs/providers/aws/events/msk.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/events/msk/index.js
test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js

Addresses: #[11635](https://github.com/serverless/serverless/issues/11635)

feat(AWS MSK): Support `filterPatterns`

---

docs/providers/aws/events/kafka.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/events/kafka.js
test/unit/lib/plugins/aws/package/compile/events/kafka.test.js

feat(AWS Kafka): Support `functions[].events[].filterPatterns`

---

docs/guides/providers.md

fix a typo in providers documentation

fix typos in providers docs

---

docs/providers/aws/events/activemq.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/events/activemq.js
test/unit/lib/plugins/aws/package/compile/events/activemq.test.js

feat(AWS ActiveMQ): Support filterPatterns

---

docs/providers/aws/events/rabbitmq.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/package/compile/events/rabbitmq.js
test/unit/lib/plugins/aws/package/compile/events/rabbitmq.test.js

feat(AWS RabbitMQ): Support filterPatterns

---

lib/plugins/aws/package/compile/events/sqs.js
test/unit/lib/plugins/aws/package/compile/events/sqs.test.js

Enhance default SQS permissions

---

docs/providers/aws/events/sqs.md
lib/plugins/aws/package/compile/events/sqs.js
test/unit/lib/plugins/aws/package/compile/events/sqs.test.js

feat(AWS SQS): Support `Properties.ScalingConfig.MaximumConcurrency`

---

docs/providers/aws/guide/services.md

Add an example of usage using [npx](https://docs.npmjs.com/cli/v7/commands/npx), as it is easier to recognize and use than to search it in the node_modules folder.

Update services.md to show how to use npx

---

lib/plugins/aws/provider.js

feat: Support new Melbourne region

---

docs/providers/google/README.md
docs/providers/google/cli-reference/invoke-local.md
docs/providers/google/cli-reference/invoke.md
docs/providers/google/guide/intro.md
docs/providers/google/guide/quick-start.md

Clarify the level of support provided for GCP Cloud Functions. I've also updated 2 places where there is limited support, to make it clearer what the limitations are - I can put these in a different PR if that's prefered. 
I tried to look for other examples in the documentation for how to format this (so that it stands out, but isn't too loud) - let me know if you'd like it formatted differently and I'll fix.
Closes: [#{8052}](https://github.com/serverless/serverless/issues/8052)

[docs][google] Mark support for google cloud functions as experimental

---

lib/cli/interactive-setup/console-setup-iam-role.js

Console: Improve warning message

---

lib/cli/interactive-setup/dashboard-login.js

CLI Onboarding: Don't crash if Dashboard server is inaccessible

---

lib/plugins/aws/package/compile/events/schedule.js
test/unit/lib/plugins/aws/package/compile/events/schedule.test.js

Add support for Cloudformation if function for schedule

---

docs/providers/aws/events/sqs.md

Maximum concurrency section is not recognized as section.
https://www.serverless.com/framework/docs/providers/aws/events/sqs

docs: replace incorrect white space on SQS Event maxium concurrency

---

lib/aws/has-local-credentials.js
lib/aws/request.js
lib/aws/sdk-v2.js
lib/cli/interactive-setup/aws-credentials.js
lib/cli/interactive-setup/deploy.js
lib/plugins/aws/package/compile/functions.js
lib/plugins/aws/provider.js
lib/utils/telemetry/generate-payload.js
test/unit/lib/aws/request.test.js

Prevent deprecation message by following suggestion from [comment by @kuhe](https://github.com/serverless/serverless/issues/11753#issuecomment-1435134813)
Closes: #11753

Suppress AWS SDK v2 deprecation message

---

lib/plugins/aws/package/compile/events/api-gateway/lib/deployment.js
lib/plugins/aws/provider.js
test/unit/lib/cli/triage/fixtures/@serverless/compose/ts/project/serverless-compose.ts
test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/stage/index.test.js

https://github.com/serverless/serverless/issues/11675
Closes: #11675

Fix for #11675

---

lib/plugins/aws/deploy-function.js

The changes included in this PR aims at improving developer experience by adding additional messaging to AWS Lambda function deployments as discussed in #11614.
Closes: #11614

feat(AWS Lambda): Improved function deployment messaging

---

test/unit/lib/plugins/aws/package/compile/events/websockets/index.test.js
test/unit/lib/plugins/aws/package/compile/events/websockets/lib/deployment.test.js
test/unit/lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js

…it/lib/plugins/aws/package/compile/events/websockets/`

refactor async functions `/test/.../aws/.../events/websockets`

---

test/unit/lib/plugins/aws/package/compile/events/alb/lib/health-check.test.js
test/unit/lib/plugins/aws/package/compile/events/lib/ensure-api-gateway-cloud-watch-role.test.js
test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js

test/unit/lib/plugins/aws/package/compile/events/s3 test/unit/lib/plugins/aws/package/compile/events/alb test/unit/lib/plugins/aws/package/compile/events/lib
Closes: #8368
Refactor 3 folders:
`test/unit/lib/plugins/aws/package/compile/events/s3` 
`test/unit/lib/plugins/aws/package/compile/events/alb`
`test/unit/lib/plugins/aws/package/compile/events/lib`

mark async for functions under events s3, alb & lib

---

test/unit/lib/plugins/aws/package/compile/events/cognito-user-pool.test.js
test/unit/lib/plugins/aws/package/compile/events/http-api.test.js

refactor async functions under `test/.../aws/.../events`

---

test/unit/lib/plugins/aws/package/compile/functions.test.js

refactor async functions under `test/unit/lib/plugins/aws/package/compile`

---

test/unit/lib/plugins/aws/info/get-api-key-values.test.js
test/unit/lib/plugins/aws/info/get-resource-count.test.js
test/unit/lib/plugins/aws/info/get-stack-info.test.js
test/unit/lib/plugins/aws/info/index.test.js

refactor async functions under `test/unit/lib/plugins/aws/info`

---

test/unit/lib/plugins/aws/package/index.test.js
test/unit/lib/plugins/aws/package/lib/generate-core-template.test.js
test/unit/lib/plugins/aws/package/lib/save-compiled-template.test.js

refactor async functions under `test/unit/lib/plugins/aws/package`

---

test/unit/lib/plugins/aws/common/index.test.js
test/unit/lib/plugins/aws/common/lib/artifacts.test.js
test/unit/lib/plugins/aws/common/lib/cleanup-temp-dir.test.js

refactor async funtions under `test/unit/lib/plugins/aws/common`

---

test/unit/lib/plugins/aws/deploy/lib/check-for-changes.test.js
test/unit/lib/plugins/aws/deploy/lib/cleanup-s3-bucket.test.js
test/unit/lib/plugins/aws/deploy/lib/upload-artifacts.test.js
test/unit/lib/plugins/aws/deploy/lib/validate-template.test.js

 refactor async functions under `test/unit/lib/plugins/aws/deploy`

---

test/unit/lib/plugins/aws/remove/lib/stack.test.js

 refactor async functions under `test/unit/lib/plugins/aws/remove`

---

test/unit/lib/classes/config-schema-handler/index.test.js
test/unit/lib/classes/plugin-manager.test.js
test/unit/lib/classes/service.test.js
test/unit/lib/classes/utils.test.js

Refactor async tests under `test/unit/lib/classes`

---

test/unit/lib/plugins/package/lib/zip-service.test.js
test/unit/lib/plugins/package/package.test.js

Refactor async tests under `test/unit/lib/plugins/package`

---

test/unit/lib/utils/download-template-from-repo.test.js
test/unit/lib/utils/fs/create-zip-file.test.js
test/unit/lib/utils/fs/read-file.test.js
test/unit/lib/utils/fs/write-file-sync.test.js
test/unit/lib/utils/fs/write-file.test.js
test/unit/lib/utils/yaml-ast-parser.test.js

Refactor async tests under `test/unit/lib/utils/`

---

test/unit/lib/plugins/plugin/lib/utils.test.js
test/unit/lib/plugins/plugin/list.test.js
test/unit/lib/plugins/plugin/search.test.js

refactor async tests under `test/unit/lib/plugins/plugin`

---

test/unit/lib/config-schema.test.js
test/unit/lib/serverless.test.js

refactor async tests under `test/unit/lib`

---

test/integration/aws/api-gateway-external.test.js
test/integration/aws/api-gateway.test.js
test/integration/aws/cognito-user-pool.test.js
test/integration/aws/iot-fleet-provisioning.test.js
test/integration/aws/s3.test.js
test/integration/aws/schedule.test.js
test/integration/aws/sns.test.js
test/integration/aws/sqs.test.js
test/integration/aws/stream.test.js
test/integration/aws/websocket.test.js

refactor async tests under `test/integration`

---

lib/cli/commands-schema/no-service.js
lib/cli/interactive-setup/console-dev-mode-feed.js

Description
Included a `--verbose` option for dev mode. I was using this a bit over the weekend and thought it would be nice to have an option to get more information out the req and response as well as the input/output of spans 🙏

chore: Include dev mode verbose flag

---

lib/cli/interactive-setup/console-dev-mode-feed.js
test/unit/lib/cli/interactive-setup/console-dev-mode-feed.test.js

Added unit tests for dev mode feed step

chore: Updated unit tests for dev mode feed

---

lib/classes/utils.js
lib/classes/yaml-parser.js

Refactor async function under `lib/classes`

---

test/integration/aws/websocket.test.js

related discussion https://github.com/serverless/serverless/pull/11841#discussion_r1142913677
#8368 
#11841

remove temp var `twoWayPassed`

---

lib/cli/interactive-setup/console-dev-mode-feed.js

We need to add explorerTraceTime so that if a customer attempts to bookmark a url we can filter out traces greater than 30 days old 👍

chore: Added explorerTraceTime

---

README.md
docs/README.md
docs/getting-started.md

These are minor adjustments to the README. WIP

Remove outdated information and add new features to docs

---

package.json
scripts/serverless.js

Fix `logout` operation (described at https://github.com/serverless/utils/pull/204)

Ensure to not login back accidentaly on logout operation

---

lib/plugins/aws/package/compile/events/cloud-watch-log.js
test/unit/lib/plugins/aws/package/compile/events/cloud-watch-log.test.js

Avoid lambda permission for log subscriptions from depending on itself

---

lib/plugins/aws/invoke-local/index.js
lib/plugins/aws/provider.js

This PR add support for Python3.10 on AWS Lambda.
Currently, the following warning is output when deploying, but this can be suppressed.
```
Warning: Invalid configuration encountered  
at 'provider.runtime': must be equal to one of the allowed values [dotnet6, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs12.x, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.6, python3.7, python3.8, python3.9, ruby2.7]
Learn more about configuration validation here: http://slss.io/configuration-validation
```
Closes: #11921

feat(AWS Lambda): Supports Python3.10

---

lib/plugins/aws/deploy-function.js
test/unit/lib/plugins/aws/deploy-function.test.js

Fix `provider.layers` support in `deploy function` command

---

lib/cli/interactive-setup/console-dev-mode-feed.js
lib/cli/interactive-setup/console-enable-dev-mode.js

There was one more copy change request to include Cloudwatch costs also increasing due to sampling not being on for dev mode 👍

refactor: Updated dev mode warning copy

---

docs/README.md

Fix typo, remove repeated word

---

docs/providers/aws/guide/functions.md
lib/plugins/aws/package/compile/functions.js
lib/plugins/aws/provider.js
package.json
test/fixtures/programmatic/function/stream.js
test/integration/aws/function-url.test.js
test/unit/lib/plugins/aws/package/compile/functions.test.js

AWS Lambda response streaming for Lambda URLs

---

lib/plugins/aws/custom-resources/index.js
test/unit/lib/plugins/aws/custom-resources/index.test.js

Closes: [#11856](https://github.com/serverless/serverless/issues/11856)

added custom resource lambda in vpc if vpc is configured

---

lib/plugins/aws/package/compile/events/cloud-front.js

fix(AWS CloudFront): Accept references on ResponseHeadersPolicyId and OriginRequestPolictyId properties

---

lib/plugins/aws/custom-resources/index.js
test/unit/lib/plugins/aws/custom-resources/index.test.js

Reverts serverless/serverless#11985 as it introduced build failuers for users
Fixes #12000
/cc @Lokesh-Jawale

Revert "added custom resource lambda in vpc if vpc is configured"

---

lib/cli/interactive-setup/console-dev-mode-feed.js
lib/cli/interactive-setup/console-enable-dev-mode.js

Removing the dev mode warning per Austen's request 👍

chore: Remove dev mode warning

---

CHANGELOG.md
package.json

Releasing v2.72.4 so that custom resources continue working on v2 (Thanks @AlexMaguey!)

chore: Release v2.72.4

---

lib/cli/interactive-setup/dashboard-login.js
lib/cli/interactive-setup/dashboard-set-org.js
lib/plugins/aws/provider.js
lib/plugins/package/lib/packageService.js
lib/utils/telemetry/generatePayload.js
test/integrationPackage/cloudformation.tests.js
test/unit/lib/cli/interactive-setup/dashboard-login.test.js
test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
test/unit/lib/plugins/aws/invokeLocal/index.test.js
test/unit/lib/plugins/aws/package/compile/functions.test.js
test/unit/lib/plugins/aws/package/compile/layers.test.js
test/unit/lib/plugins/aws/package/lib/stripNullPropsFromTemplateResources.test.js
test/unit/lib/utils/telemetry/generatePayload.test.js

Updated the default runtime to `nodejs16.x`

chore: Node function default

---

docs/providers/aws/guide/credentials.md

docs: Overhauled AWS credentials page

---

CHANGELOG.md
package.json

Releaseing v3.34.0 which includes 3.11 python support, IAM role assignment fixes, and maintenance improvements.

chore: Release v3.34.0

---

lib/plugins/aws/provider.js

Closes: [12124](https://github.com/serverless/serverless/issues/12124)

feat: add AWS Israel (Tel-Aviv) region support

---

lib/plugins/aws/provider.js

feat: recognize ap-south-2 as a valid AWS region

---

lib/cli/interactive-setup/aws-credentials.js
lib/cli/interactive-setup/console-dev-mode-feed.js
lib/config-schema.js
lib/plugins/deploy.js
lib/utils/serverless-dashboard.js
package.json
test/unit/lib/cli/interactive-setup/aws-credentials.test.js
test/unit/lib/cli/interactive-setup/index.test.js

Added deploy hooks to integrate with customer AWS accounts and instrument functions after deploy is complete

feat: Post deploy serverless dashboard integration

---

lib/cli/commands-schema.js
lib/cli/ensure-supported-command.js
lib/cli/render-help/general.js
lib/cli/render-help/generate-command-usage.js
lib/cli/render-help/options.js

feat(v4): improve help formatting

---

lib/plugins/esbuild/index.js

Fixes https://github.com/serverless/serverless/issues/12542

fix: use correct handler for esbuild enabled check

---

lib/plugins/aws/deploy-list.js
lib/plugins/aws/dev/index.js
lib/plugins/aws/dev/shim.js
lib/plugins/aws/dev/shim.min.js
lib/plugins/aws/invoke-local/index.js
lib/serverless.js

Fixes https://github.com/serverless/serverless/issues/12560
Adds support for https://github.com/serverless/serverless/issues/12541
Improves the Dev Mode messaging.

Fix Spinner Experience & Improve Messaging

---

lib/plugins/aws/deploy/index.js

fix: remove extra error log line

---

docs/guides/variables/README.md
docs/guides/variables/env-vars.md
docs/guides/variables/vault.md
docs/menu.json

Fixes a few of the new "Variables" menu items.

docs: fix variables menu

---

docs/guides/variables/terraform.md
docs/menu.json

docs: fix incorrect link

---

lib/plugins/aws/info/display.js

fix(info): bring back verbose mode for the info command

---

lib/plugins/aws/dev/index.js

Closes https://github.com/serverless/serverless/issues/12627

fix(dev): validate region defined in yml

---

lib/plugins/aws/invoke-local/index.js

Closes https://github.com/serverless/serverless/issues/12621

fix(invoke-local): fix invoke local esm issue in windows

---

lib/plugins/aws/dev/index.js
lib/plugins/aws/dev/local-lambda/index.js

Also adds comments, cleans up errors and uses ServerlessError

chore(dev): clean up and refactor dev mode

---

lib/plugins/aws/package/compile/events/cognito-user-pool.js
lib/plugins/aws/package/compile/events/event-bridge/index.js
lib/plugins/aws/package/compile/events/lib/ensure-api-gateway-cloud-watch-role.js
lib/plugins/aws/package/compile/events/s3/index.js

Fixes https://github.com/serverless/serverless/issues/12632

fix(cloudformation): ensure the Version property is a string (SC-2487)

---

docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/custom-resources/index.js
lib/plugins/aws/custom-resources/resources/api-gateway-cloud-watch-role/handler.js

Fixes https://github.com/serverless/serverless/issues/12637

fix(apig): fix enabling api gateway logs (SC-2491)

---

docs/providers/aws/guide/deploying.md
docs/providers/aws/guide/serverless.yml.md
lib/plugins/aws/deploy/lib/create-stack.js
lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js
lib/plugins/aws/lib/update-stack.js

feat: make direct deployments the default

---

docs/providers/aws/guide/building.md
lib/plugins/esbuild/index.js

Closes https://github.com/serverless/serverless/issues/12654

feat: adds support for esbuild plugins (SC-2514)

---

docs/guides/variables/README.md

fix: params syntax

---

README.md
docs/guides/plugins/creating-plugins.md

Update docs to ensure that newly developed plugins are compatible with Serverless Framework v4.

docs: update plugin peer dependencies

---

lib/plugins/esbuild/index.js

Closes https://github.com/serverless/serverless/issues/12706

fix(esbuild): output esm if type: module in package.json (SC-2598)

---

docs/guides/sam.md

Add note on the supported file format & names for SAM/CF

docs: add note on supported SAM/CF files

---

docs/guides/compose.md
docs/guides/deployment-bucket.md

Minor formatting improvements to the new compose docs.

docs: minor formatting updates

---

docs/guides/deployment-bucket.md
docs/guides/license-keys.md
docs/guides/parameters.md
docs/guides/variables/README.md
docs/menu.json
lib/config-schema.js

Added to the "Get Started" menu section

docs: license keys

---

lib/plugins/observability/axiom/index.js

Addresses https://github.com/serverless/serverless/issues/12875

fix: integrate with axiom when using deploy function command

---

docs/guides/license-keys.md
lib/plugins/package/lib/package-service.js

Addresses https://github.com/serverless/serverless/issues/12868

fix(compose): correct layer directory structure when packaging

---

docs/guides/license-keys.md
lib/plugins/observability/axiom/index.js

Addresses https://github.com/serverless/serverless/issues/12874

fix: use aws profile for axiom integration

---

lib/plugins/aws/invoke-local/index.js

Addresses https://github.com/serverless/serverless/issues/12848

fix(invoke-local): replace undefined 'fse' with direct 'fs-extra' imports

---

lib/plugins/esbuild/index.js

fix(esbuild): include package.json in artifact if type is module

---

docs/guides/variables/aws/s3.md

Addresses https://github.com/serverless/serverless/issues/12915

docs: add serverSideEncryption to S3 resolver documentation

---

docs/providers/aws/guide/functions.md
lib/plugins/aws/provider.js

Addresses https://github.com/serverless/serverless/issues/12808

feat: add support for provenance option in docker build

---

docs/providers/aws/cli-reference/dev.md

docs(dev-mode): added note regarding vpc
