serverless/serverless

- lib/plugins/aws/provider/awsProvider.js
- lib/plugins/aws/provider/awsProvider.test.js
Closes: #7676
By default, aws-cli does not take [default] profile from credentials file if ```AWS_DEFAULT_PROFILE``` environment variable is defined. Serverless should behave in exactly same manner when resolving profiles - currently [default] is hard-coded. Fallback mechanism to [default] is still there if ```AWS_DEFAULT_PROFILE``` isn't defined.
Important remark 1: each test in ```getCredentials``` suite seems to carry some state, that's why I had to reset ```newAwsProvider.options['aws-profile']```, below is an interesting log before introducing my changes at all:
```
> serverless@2.4.0 test /home/mpiotrowski/Projects/oss/fork-serverless/serverless
> mocha "lib/plugins/aws/provider/*.test.js" -g "newAwsProvider.options"
AwsProvider
#getCredentials() …
```
> Add support for AWS_DEFAULT_PROFILE env variable when resolving profile

- docs/providers/aws/events/http-api.md
> docs(aws http api): update information about default payload for httpapi

- lib/plugins/aws/provider/awsProvider.js
They were removed by mistake with #8319. It's only primitive/array combinations where singular variant should be removed. object/array should be left intact
Closes: #8365
> Config Schema: Bring back non-array supported variants

- lib/classes/ConfigSchemaHandler/index.js
Fixes issue introduced with https://github.com/serverless/serverless/pull/8319 where properties with `undefined` value were converted to `null`
Closes: #8370
> Ensure to preserve "undefined" values properties when normalizing for schema

- lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js
- lib/plugins/aws/package/compile/events/eventBridge/index.js
- lib/plugins/aws/provider/awsProvider.js
Fixes issues introduced with: #8309, #8114 and #8230 
Idea was to require few properties exchangeably but also allow not provide any of them at all, via:
```json
{ "oneOf": [
{ "required": [] },
{ "required": ["foo"] },
{ "required": ["bar"] }, 
] }
```
That can't work, because if either `foo` or `bar` is provided, two schemas out of listed are matched, and that is invalid against _one of_ rule.
Without using sophisticated `not` constructs there seems no way to reliably validate this by schema, therefore removed it/
Closes: #8373
> Config Schema: Revert invalid "oneOf" based validation

- lib/plugins/invoke/invoke.js
- lib/plugins/invoke/invoke.test.js
Propagating 'IS_LOCAL' env variable to other potential consumers, eg. docker local invocation
Closes: #7227
When running ```sls invoke local -f hello```, ```IS_LOCAL``` environment variable was set to ```true``` as expected. If ```docker``` option was active, however, ```IS_LOCAL``` wasn't propagated to the container.
Currently, ```defaultEnvVars``` dictionary (lib/plugins/invoke/invoke.js) which is supposed to contain "provider-independent" environment variables for local execution, contains only ```IS_LOCAL```. To address the problem more generically, however, we cannot just re-define ```IS_LOCAL``` when starting the container as this collection might grow outside of the aws-specific ```invokeLocal``` module. This is why shared (at least between lib/plugins/invoke/invoke.js and …
> Propagating 'IS_LOCAL' env variable to other potential consumers

- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/package/compile/events/s3/index.test.js
Closes: #8090 
This PR is inspired by #8004 .
Main difference is I did not change the [PutBucketNotification/GetBucketNotification policy](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/s3/index.js#L370) because from the issue description I didn't think it was called for.
There was a [test case](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/s3/index.test.js#L802) which covered the original behaviour, but the test title suggested that the focus was something else (DependsOn) so I decided to write a new test, and remove the part related to this PR from that test.
> Fix handling of lambda permissions removal

- lib/plugins/aws/package/compile/events/stream/index.js
- lib/plugins/aws/package/compile/events/stream/index.test.js
- test/fixtures/provisionedConcurrency/core.js
- test/fixtures/provisionedConcurrency/serverless.yml
- test/integration/provisionedConcurrency.test.js
Ensures that `EventSourceMapping` for `stream` events has proper `alias` attached if one exists, It also ensures that the mapping resource will depend on that alias. This PR also adds a corresponding integration test case for `provisionedConcurrency.test.js`.
Note: The average time it takes to run the test now is pretty much the same, around 7-8 minutes.
Closes: #7802
> feat(aws stream): provisioned concurrency support for aws stream event

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js
- lib/plugins/aws/provider/awsProvider.js
> Aws provider apigateway schema

- docs/deprecations.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/lib/naming.test.js
- lib/plugins/aws/provider/awsProvider.js
The naming of API Gateway will be changed from `${stage}-${service}` to `${service}-${stage}` in the next major version.
This commit adds a deprecation notice and an option to already adapt to this this convetion.
Adresses: #2918
> AWS API Gateway: Fix API Gateway naming convention

- lib/utils/renameService.js
- lib/utils/renameService.test.js
I believe this falls under the "obvious bug fix" category. Upon a service rename after `sls create` from a template, `package-lock.json` does not get renamed even though `package.json`. I confirmed this behaviour before this change, and confirmed `package-lock.json` also gets renamed after this change. I also updated the unit tests and watched them fail before updating the code to make the tests pass.
> fix: renameService now renames package-lock.json if it exists.

- lib/plugins/aws/provider/awsProvider.js
Currently when deploying against a localstack instance an error causes the following stacktrace
```
TypeError: message.startsWith is not a function
at /usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:1150:23
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
We now cast the error code to a string to allow later calls with `startsWith`
fixes bug of calling .startWith on an int
> Cast error code to str to allow later startsWith()

- lib/plugins/aws/package/lib/generateCoreTemplate.test.js
Addressing issue reported at https://github.com/serverless/serverless/pull/8330#issuecomment-713132491 by @thewizarodofoz 
It only worked because all  `provider` properties are mapped on `service.provider`
> Tests: Fix fixture service config

- lib/plugins/aws/info/display.js
- lib/plugins/aws/info/display.test.js
No issue related to this small PR.
AWS increased its Cloudformation resources limit from 200 to 500
https://aws.amazon.com/fr/about-aws/whats-new/2020/10/aws-cloudformation-now-supports-increased-limits-on-five-service-quotas/
> Upgrade warning message trigger for max cloudformation resources to 500

- docs/providers/aws/guide/serverless.yml.md
While adding `useDotenv` to `serverless.yml.md` file, I realised that I didn't update it while implementing support for msk and efs - that PR should fix that.
> Add missing efs and msk to serverless yml md

- lib/plugins/aws/customResources/index.js
When I was studying AWS custom resources in Serverless Framework, I've noticed that there is no log retention being set for the custom resources lambda functions. And when I took a look at AWS Console I could see there "Never expire" in the log retention field even though I've set the logRetentionInDays: 30 in serverless.yml.
Closes: #8439
> feat(Packaging): Include log retention in custom resources log groups

- docs/providers/aws/guide/plugins.md
- lib/classes/ConfigSchemaHandler/index.js
- lib/classes/ConfigSchemaHandler/index.test.js
- lib/configSchema.test.js
- test/fixtures/configSchemaExtensions/serverless.yml
- test/fixtures/configSchemaExtensions/test-plugin.js
Closes: https://github.com/serverless/serverless/issues/8422
- Added new method 'defineFunctionProperties' to 'ConfigSchemaHandler', to allow plugins to define custom properties inside functions
- Update the plugins docs in https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema
> Add new method 'defineFunctionProperties' to 'ConfigSchemaHandler'

- docs/deprecations.md
- lib/classes/Service.js
> Deprecate object notation for `service` 

- lib/classes/CLI.js
- lib/classes/CLI.test.js
- test/fixtures/plugin/plugin.js
- test/fixtures/plugin/serverless.yml
Listing help for commands with no `options` object configured, resulted with following error:
```
Type Error ---------------------------------------------
TypeError: Cannot convert undefined or null to object
at Function.entries (<anonymous>)
at CLI.displayCommandOptions (/Users/medikoo/npm-packages/serverless/lib/classes/CLI.js:154:12)
at CLI.generateCommandsHelp (/Users/medikoo/npm-packages/serverless/lib/classes/CLI.js:353:10)
at CLI.displayHelp (/Users/medikoo/npm-packages/serverless/lib/classes/CLI.js:116:16)
at Serverless.run (/Users/medikoo/npm-packages/serverless/lib/Serverless.js:147:18)
at /Users/medikoo/npm-packages/serverless/scripts/serverless.js:50:26
```
It's a regression introduced with https://github.com/serverless/serverless/pull/8280
> CLI: Fix handling of command options in help display

- lib/plugins/create/templates/aws-nodejs-typescript/package.json
- lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js
A simple PR to update the `aws-nodejs-typescript` template to use webpack5 via `serverless-webpack`
+ Updates the template to use webpack5 and updates corresponding packages to current.
+ Addresses concatenateModules suggestion located here https://github.com/serverless-heaven/serverless-webpack/issues/651
Currently does not pass the integration test due to requirements on non-existent `serverless.yml` file for Typescript: ./integration-test-template aws-nodejs-typescript
> template update: aws-nodejs-typescript - webpack5 updates

- lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js
Tiny fix of error:
```
Serverless: Bundling with Webpack...
Validation Error ---------------------------------------
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
- configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
BREAKING CHANGE since webpack 5: The devtool option is more strict.
Please strictly follow the order of the keywords in the pattern.
```
See https://github.com/aligent/serverless-aws-nodejs-service-template/pull/52 too
> Fix BC since Webpack5: The devtool option is more strict

- lib/plugins/create/templates/aws-go-mod/Makefile
Template `aws-go-mod` is for Go Modules.
It has `make clean` command on Makefile, but it cleans `Gopkg.lock` not `go.sum`.
So I fixed.
> fix: clean command in aws-go-mod template removes go.sum file

- lib/plugins/package/lib/zipService.js
- lib/plugins/package/lib/zipService.test.js
Closes: #8500 
In npm v7.0 default `depth` value has been changed from `Infinity` to `null` which causes `npm ls` command to list only root packages by default. By adding `--all` parameter to `npm ls` command we now can properly exclude all devDependencies from the artifacts.
> fix(packaging): remove devDependencies when npm v7.0 is used

- docs/providers/aws/events/http-api.md
- lib/plugins/aws/package/compile/events/httpApi/index.js
- lib/plugins/aws/package/compile/events/httpApi/index.test.js
- lib/plugins/aws/provider/awsProvider.js
Closes: #8190 
Hi @medikoo , 
This PR implements the change suggested in #8190  . I used the detailedMetrics flag instead of metrics in httpApi because it is closer to the flag used by Cloudformation ([DetailedMetricsEnabled](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-stage-routesettings.html)).
I had to change my commit because when testing my change I noticed that once you've set DetailedMetricsEnabled to true, removing the property from DefaultRouteSettings will not disable the detailed metrics, to do so you have to set DetailedMetricsEnabled to false.
> Add detailed metrics to HttpApi

- lib/Serverless.js
- lib/classes/CLI.js
- lib/classes/CLI.test.js
- lib/classes/PluginManager.js
Closes: #8497 
**Commands**
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--no-color" to disable CLI colors
* Pass "--help" after any <command> for contextual help
**Interactive Quickstart**
* Run serverless (or shortcut sls) without any arguments to initialize an interactive setup
of functionalities related to given service or current environment
* Pass "--help-interactive" for contextual help on interactive CLI options
**Serverless Components**
* Run serverless (or shortcut sls) in context of a component service to initialize a components CLI
* Pass "--help-components" for contextual help on Serverless Components
**Framework**
* Documentation: http://slss.io/docs
**Environment Variables**
* Set SLS_DEBUG=* to see debugging logs
* Set SLS_WARNING_DISABLE=* to …
> Remove help verbose 8497

- docs/providers/aws/events/sqs.md
- lib/plugins/aws/package/compile/events/sqs/index.js
- lib/plugins/aws/package/compile/events/sqs/index.test.js
Update SQS event batch size and add support to batching window according to: https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html
> feat: update Lambda's SQS event batch size and add support to batching window

- lib/plugins/aws/package/lib/mergeIamTemplates.js
- test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
There is no way to disable the CloudWatch logs for a lambda function. One workaround is you can add the policy to your role to disable the CloudWatch logs.
I have added deny policy for that specific lamda so as per now by default all function have **logs:PutLogEvents** permission when there is disableLogs opt to true we are adding deny policy statement for that function
Closes: #8554
> fixed added deny iam policy when user opt disable log for a function

- lib/plugins/aws/package/compile/events/cloudFront/index.js
- lib/plugins/aws/provider/awsProvider.js
- test/unit/lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Following recent [announcements](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-supports-10gb-memory-6-vcpu-cores-lambda-functions/) from re:Invent, this PR adjusts schema restrictions on `memory`, increasing maximum values and also removing the restriction that the value has to be in multiple of 64. It also adjust restrictions imposed on Lambda@Edge, as the origin quotas for memory are the same as for "plain" Lambda.
From CloudFormation [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-memorysize)
From CloudFront/Lambda@Edge [docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html)
> feat(aws): increase memory limits for functions 

- test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js
- Removed tests which simply test characteristics of internal implementation
- Improve organization of existing `runServerless` based tests
> Tests: Refactor main AWS ALB tests

- lib/utils/fs/removeFile.js
- lib/utils/fs/removeFileSync.js
- test/unit/lib/utils/fs/copyDirContentsSync.test.js
Related to #8588 
`removeFile` utils were not really used, and if, their usage could simply be replaced with `fs-extra`
> Refactor: Remove superfluous fs utils

- lib/plugins/package/lib/packageService.js
Adresses: #5583, #5892 and #7837
Can't really add a unit test since the problem is with `globby` resolving and we don't really resolve in the unit tests.
The other problem is that when resolving the patterns (include/exclude) for a layer, they are resolved relative to the layer path, if present. Not only the layer patterns are resolved relative to the layer but also all the others: service-level patterns, pluginsLocalPath, automatically excluded dev dependencies, serverlessConfigFileExclude, etc.
And that seems to confuse people. No easy solution for this though since the folder structure of layers it's important so they shouldn't include any folder upper than they `path`
> fix(Packaging): Not exclude layers when packaging a layer

- lib/plugins/standalone/index.js
- package.json
Just noticed that `stream-promise` was used only once in the solution and it's something that we can do using native node
> refactor: Remove dependency to stream-promise

- lib/plugins/aws/lib/monitorStack.js
- lib/plugins/aws/remove/index.js
- test/unit/lib/plugins/aws/lib/monitorStack.test.js
Closes: #8632 
Error was that, no matter what deploy action was pursued we recognized any, either `CREATE_IN_PROGRESS`, `UPDATE_IN_PROGRESS` or `DELETE_IN_PROGRESS` as first stack operation event.
This lead to situations where for failed _create_ actions, which were followed immediately with _delete_ actions, it was `DELETE_IN_PROGRESS` that was coined as starting one, and due to that real error was not communicated (deploy operation was reported with success by a function which then lead to other obscure errors)
> AWS CF Deployment: Fix resolution of first stack deploy event

- lib/classes/Variables.js
- lib/plugins/aws/configCredentials.js
- lib/plugins/aws/deployFunction.js
- lib/plugins/aws/deployList.js
- lib/plugins/aws/invoke.js
- lib/plugins/aws/invokeLocal/index.js
- lib/plugins/aws/logs.js
- lib/plugins/aws/metrics.js
- lib/utils/timers.js
- test/unit/lib/plugins/aws/deployFunction.test.js
- test/unit/lib/plugins/aws/deployList.test.js
- test/unit/lib/plugins/aws/invoke.test.js
- test/unit/lib/plugins/aws/invokeLocal/index.test.js
- test/unit/lib/plugins/aws/logs.test.js
- test/unit/lib/plugins/aws/metrics.test.js
Addresses: #7171 
I might keep doing the same for other modules. But I think that it's better to merge small increments than wait for a full solution rewrite.
> Remove bluebird and use async/await from most of the AWS plugin

- docs/deprecations.md
- docs/environment-variables.md
- docs/providers/aws/guide/packaging.md
- lib/plugins/package/lib/packageService.js
- test/unit/lib/plugins/package/lib/packageService.test.js
As reported by @mnapoli in https://github.com/serverless/serverless/pull/8634, recent release (v2.16.0) introduced a backward-incompatible change with excluding `.env` files unconditionally. This change ensures that it takes effect only if `useDotenv` is set. 
Addresses: #8566
> fix(Packaging): Exclude .env files only when useDotenv is set

- scripts/pkg/upload/china.js
- scripts/pkg/upload/index.js
At this point it seems we're unable to upload binaries to China region, until that's sorted let's treat upload errors as non fatal
Additionally improved script to write _latest tag_ information only after successful binary uploads
/cc @timqian @zongUMR @hkbarton
> CI: Handle  upload errors of binaries to China region as not fatal

- lib/classes/Variables.js
I thought this qualifies for a small and obvious bug, so I did not open an issue.
What is happening is when my file is empty, `reducedValue` is `null` and throws an error that the variable could not be found. See error below.
```
TypeError: Cannot read property 'XXXXXXXXXXXXXXXXXXXXXXX' of null
at C:\dev\XXXXX\node_modules\serverless\lib\classes\Variables.js:891:40
at tryCatcher (C:\dev\XXXXX\node_modules\bluebird\js\release\util.js:16:23)
at Object.gotValue (C:\dev\XXXXX\node_modules\bluebird\js\release\reduce.js:157:18)
at Object.gotAccum (C:\dev\XXXXX\node_modules\bluebird\js\release\reduce.js:144:25)
at Object.tryCatcher (C:\dev\XXXXX\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\dev\XXXXX\node_modules\bluebird\js\release\promise.js:517:31) …
```
> fix(Variables): Fix when properties are null

- lib/plugins/aws/package/compile/events/httpApi.js
- test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js
Link to the issue: https://github.com/serverless/serverless/issues/8650
This tiny PR adds HttpApi output to the cloudformation template when using AWS ApiGateway's httpApi, in addition to the existing HttpApiUrl output.
Closes: #8650
> feat(AWS API Gateway): Add HttpApiId to httpApi CF Outputs

- docs/deprecations.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/normalizeFiles.js
- lib/plugins/aws/package/compile/functions.js
- lib/plugins/aws/package/lib/getHashForFilePath.js
- lib/plugins/aws/provider.js
- lib/utils/deepSortObjectByKey.js
- test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
- test/unit/lib/plugins/aws/lib/normalizeFiles.test.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
- test/unit/lib/plugins/aws/package/lib/getHashForFilePath.test.js
- test/unit/lib/utils/analytics/generatePayload.test.js
- test/unit/lib/utils/deepSortObjectByKey.test.js
Scope:
1. Added new optional property, `provider.lambdaHashingVersion`
2. Add deprecation notice about `20201221` becoming a default `lambdaHashingVersion` from next major. Also, fixed a small issue where the `initialize` hook wasn't called.
2. Changed function compilation step from serial to parallel
3. Change 2 required adjustments in the normalization of CloudFormation template - to ensure consistent hashing, both Outputs and Resources are now sorted by keys (maybe it makes sense to use `deepSortObjectByKey` here as well?)
4. Introduced `getHashForFilePath` util function
5. Introduced new algorithm of computing version hash based on `lambdaHashingVersion`, ensuring that artifact hash stays the same. 
One thing I'm not sure about is migration guide/documentation. I've currently put …
> feat(AWS Deploy): Introduce new version of hashing algorithm

- docs/providers/aws/guide/functions.md
- lib/plugins/aws/package/compile/functions.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
Adds support for referencing images with tags
To also share a bit more context about it because it seems fairly simple, but there was a little bit more consideration to it. I was also wondering if we should resolve SHA for an image at all times, because it seems like ImageUri can also accept an URI with tag only. My first idea here that maybe (without versioning), if ImageUri would be e.g. `xxx.xxx/repo-name:latest`, then after updating the image under the `latest` tag in that repo will result in new Lambdas being invoked with that newly pushed image. I was a bit surprised to learn that it's not the case, it seems like Lambda internally is somehow still pinning the image to specific sha (maybe during the image optimization process that happens before the first invocation) and you have to …
> feat(AWS Lambda): Support referencing images with tags

- lib/plugins/aws/package/compile/layers.js
- test/unit/lib/plugins/aws/package/compile/layers.test.js
Created as a replacement for https://github.com/serverless/serverless/pull/8579 as I was not able to push new changes into original branch.
Closes: #8578
> fix(AWS Lambda Layers): Permissions on lambda layer retained

- lib/plugins/aws/deployFunction.js
During testing and discussion together with @medikoo we figured out that `deployFunction` does not need to resolve imageUri and is currently working correctly.
Closes: #8691
> docs: Explanation why deployFunction doesn't have to resolve images

- package.json
- test/fixtures/index.js
- test/mochaPatch.js
- test/unit/lib/Serverless.test.js
- test/utils/run-serverless.js
In response to v7.0.0 release of `@serverless/test` -> https://github.com/serverless/test/releases/tag/v7.0.0
Additionally:
- Update `test` script to run tests in _parallel_ (which is possible with Mocha v8) - it significantly speeds up test run (depending on available CPU cores)
- Upgrade `boxen` dependency to v5
> Upgrade test related dependencies

- lib/plugins/aws/lib/cloudformationSchema.js
- lib/plugins/print.js
- lib/utils/fs/parse.js
- lib/utils/fs/writeFile.js
- lib/utils/fs/writeFileSync.js
- package.json
- test/unit/lib/Serverless.test.js
- test/unit/lib/classes/Variables.test.js
- test/unit/lib/classes/YamlParser.test.js
- test/unit/lib/plugins/aws/lib/cloudformationSchema.test.js
- test/unit/lib/plugins/plugin/install.test.js
- test/unit/lib/plugins/plugin/uninstall.test.js
- test/unit/lib/plugins/print.test.js
- test/unit/lib/utils/createFromTemplate.test.js
- test/utils/fs.js
Followed the migration guide: https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md
Used `load` and `dump` references were auto upgraded with more strict variants (in v3 they supported JS injections which were not safe, and I believe we never envisioned to support it)
Additionally improved var naming
> Upgrade "js-yaml" to v4

- lib/plugins/aws/provider.js
Closes: #8704
Referenced these resources:
Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html
> The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
AWS Console:
Cloudformation doesn't allow '@' and console doesn't allow tabs so didn't include them.
Could not find existing tests for this, could someone point me to them?
> fix(Config Schema): Improve AWS tags validation

- lib/classes/PluginManager.js
- test/unit/lib/classes/PluginManager.test.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
> refactor: Replace `_.set` with native assignment

- docs/guides/parameters.md
- docs/guides/profiles.md
- docs/guides/providers.md
This PR updates the documentation for parameters, providers, and deployment profiles in the dashboard per the upcoming changes, deprecation and migration.
- Updates usage docs on parameters
- Moves the migration details from providers to the deployment profiles page
- Adds a reference to the parameters on the deployment profiles page
> Docs params update

- scripts/pkg/build.js
As in title, update to Node 14 when building standalone binaries
> feat: Update to Node 14 for standalone binaries

- lib/classes/ConfigSchemaHandler/index.js
- package.json
This adds missing `ajv-formats` that cause a lot of noise and missed checks for formats such as `ipv4` and similar, which we should avoid when releasing a new version (`sls deploy` creates a lot of noise)
Addresses: #8695
> fix(Config Schema): use ajv formats

- lib/plugins/package/lib/packageService.js
- test/unit/lib/plugins/package/lib/packageService.test.js
Closes: #8325 
Addresses #6752 
Would also close https://github.com/softprops/serverless-rust/issues/82
Although it looks like there may be more than one trigger for issue #6752, this change addresses one case seen as a result of the serverless-rust plugin setting artifacts with an absolute path which wasn't considered by `lib/packageService.js`.
An alternative fix might change serverless-rust to set a relative path, but this seems like a more general fix.
> fix(Packaging): Consider absolute artifact paths (#8325)

- lib/Serverless.js
- lib/classes/Error.js
- lib/cli/handle-error.js
- lib/cli/resolve-local-serverless-path.js
- scripts/serverless.js
- test/mochaPatch.js
- test/unit/lib/Serverless.test.js
- test/unit/lib/classes/Error.test.js
- test/unit/lib/cli/handle-error.test.js
- test/unit/lib/cli/resolve-local-serverless-path.test.js
- test/unit/lib/utils/analytics/generatePayload.test.js
Addresses 0.1 and 0.2 from https://github.com/serverless/serverless/issues/8364
Additionally fixed tests in two unrelated files as they were immune to side effects of already required utils (ensured there `runServerless` runs always run with clear require cache)
> Seclude general error handler and improve process execution span setup

- lib/plugins/aws/provider.js
- test/fixtures/configSchemaExtensions/test-plugin.js
- test/unit/lib/classes/ConfigSchemaHandler/index.test.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
As discussed in https://github.com/serverless/serverless/pull/8701 moving unrelated typo changes into separate PR.
> refactor: Typos in schema

- scripts/serverless.js
Fix regression, accidentally introduced with #8726 and exposed in integration tests run: https://github.com/serverless/serverless/runs/1669093528
Bluebird long stack trace config was moved after the point where eventual bluebird promises are created, and that's not allowed _(observable only with `SLS_DEBUG=1`)_
I decided to remove the config completely as we already migrated some parts from bluebird, so this functionality for sure no longer covers all async spans, and we're about to ditch `bluebird` with #7171
> CLI: Remove bluebird config

- lib/classes/CLI.js
- lib/cli/eventually-list-version.js
- scripts/serverless.js
- test/unit/lib/classes/CLI.test.js
- test/unit/lib/cli/eventually-list-version.test.js
Addresses 1.0 from https://github.com/serverless/serverless/issues/8364
> CLI: Seclude version output functionality out of CLI class

- test/unit/lib/plugins/aws/remove/index.test.js
Refactor AwsRemove tests to use `runServerless`, as discussed in https://github.com/serverless/serverless/pull/8725
> test: Cover AwsRemove with runServerless-based tests

- lib/Serverless.js
As discussed in: https://github.com/serverless/serverless/pull/8742#discussion_r555734879
> refactor: Refactor Serverless.run to async

- lib/plugins/aws/package/compile/events/cloudFront.js
It appears that hook name was mistyped
> AWS CloudFront: Fix deprecations visibility

- package.json
I've observed locally that unhandled rejections are not reported in some scenarios with Mocha `--parallel` mode 
e.g. I've added:
```javascript
require('fs').promises.readFile('foo');
```
at https://github.com/serverless/serverless/blob/461a3965a52eb9707121700608dc8bdbafc367d1/test/unit/lib/plugins/package/lib/packageService.test.js#L673 and `npm test` passed green. After removing `--parallel` from `test` script configuration, unhandled rejection is reported deterministically.
Wanted to report to Mocha, and for that tested without our [patch](https://github.com/serverless/test/blob/ecdb52dc8fda4d7f73662e41930528b2b91a6d45/setup/patch.js#L47-L50) applied, but then tens of other fails surfaced clearly showing that  something is broken in `--parallel` mode in general
> Tests: Do not use Mocha parallel mode

- lib/plugins/aws/package/compile/events/cloudFront.js
- test/unit/lib/plugins/aws/package/compile/events/cloudFront.test.js
While trying to add a lambda@edge function with a cloudfront event, I ran into an issue. I assume that this is an edge case, which is why it wasn't caught so far:
My cloudFront event is specifying a cachePolicy and at the same time a behavior with AllowedMethods and CachedMethods. Independently they work as expected, but when combining them, a broken check triggers.
That check tests for deprecated properties, but instead of checking for the values being `undefined`, it checks if they are `null`, which is not a valid value in regards to CloudFormation.
This PR fixes that check and introduces a unit test to make sure it won't break again in the future.
> fix(AWS CloudFront): Fix check for deprecated CacheBehavior properties

- package.json
- test/unit/lib/plugins/aws/package/compile/layers.test.js
This PR is about refactoring test/unit/lib/plugins/aws/package/compile/layers.test.js to runServerless based variant.
Closes: #8585
> test: Refactor compile layers tests to use `runServerless`

- lib/plugins/aws/lib/naming.js
Fix issue that was revealed by: https://github.com/serverless/serverless/runs/1720823233?check_suite_focus=true
It can be caused if `service` name contains uppercased letters.
> fix(AWS Lambda): Ensure ECR repository name is lowercased

- lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json
Addresses: https://github.com/serverless/typescript/issues/18
> fix(Templates): Compilation target ES2019 in aws-nodejs-typescript

- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/provider.test.js
When live testing today I've noticed the change to only attempt ECR login had a bug and didn't support case where token was present but expired. This PR aims to fix that problem.
> fix(AWS Lambda): Ensure to attempt ECR login on expired token

- lib/plugins/aws/customResources/index.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/handler.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/permissions.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
- lib/plugins/aws/customResources/resources/eventBridge/handler.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/eventBridge.js
- lib/plugins/aws/customResources/resources/eventBridge/lib/permissions.js
- lib/plugins/aws/customResources/resources/s3/handler.js
- lib/plugins/aws/customResources/resources/s3/lib/bucket.js
- lib/plugins/aws/customResources/resources/s3/lib/permissions.js
- lib/plugins/aws/customResources/resources/utils.js
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/deploy/lib/cleanupS3Bucket.js
- lib/plugins/aws/deploy/lib/createStack.js
- lib/plugins/aws/deploy/lib/existsDeploymentBucket.js
- lib/plugins/aws/deploy/lib/extendedValidate.js
- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- lib/plugins/aws/deploy/lib/validateTemplate.js
- lib/plugins/aws/lib/naming.js
- test/unit/lib/plugins/aws/deploy/lib/createStack.test.js
- test/unit/lib/plugins/aws/deploy/lib/extendedValidate.test.js
- test/unit/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
- test/unit/lib/plugins/aws/deploy/lib/validateTemplate.test.js
Refactored Promise-returning functions for:
* `lib/plugin/aws/customResources`
* `lib/plugin/aws/deploy`
I had to refactor a few tests after tagging functions with `async` keyword. I didn't change the functionality of the test, just the syntax.
> refactor: Mark functions async in `aws/customResources` and `aws/deploy`

- docs/providers/aws/events/msk.md
…ute"
It seems like there was a typo where it should specify the function "compute" instead of "company".
> docs: Fix "company" instead of "compute" typo in `msk` docs

- lib/plugins/aws/customResources/resources/apiGatewayCloudWatchRole/handler.js
- lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
- lib/plugins/aws/customResources/resources/utils.js
- lib/plugins/aws/deploy/lib/createStack.js
- test/unit/lib/plugins/aws/deploy/lib/createStack.test.js
- test/unit/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
As in title, fixes regression introduced by https://github.com/serverless/serverless/pull/8698 + completes a few missing functions marked as async
> fix: Complete async refactor for `aws/deploy` and `customResources`

- lib/cli/resolve-configuration-path.js
- test/unit/lib/cli/resolve-configuration-path.test.js
With  https://github.com/serverless/serverless/pull/8770 config path resolution was refactored to standalone util.
Over there it was restricted that no absolute path can be used. Still this restriction doesn't seem valid.
Fact that we're restricting that config needs to be in current working directory should not prevent the ability to pass absolute path to it (concern raised at https://github.com/serverless/serverless/pull/8770#discussion_r560874073)
> CLI: Allow absolute path in `--config`

- lib/plugins/aws/deployFunction.js
- test/unit/lib/plugins/aws/deployFunction.test.js
In relation to discussion started in https://github.com/serverless/serverless/pull/8778.
This PR adds:
- Retrying for up to one minute when `updateFunctionConfiguration` fails due to another update in progress
- Skipping `updateFunctionCode` call when image did not change
- Skipping `updateFunctionConfiguration` when nothing changed/there's nothing to update
- Tests refactoring
> fix(AWS Lambda): Ensure function update works when image used

- lib/plugins/package/lib/zipService.js
- test/unit/lib/plugins/package/lib/zipService.test.js
Use proper OS EOL to split OS-produced output files. 
In this case there was a local temp file produced by this part, on `lib/plugins/package/lib/zipService.js`
```
return childProcess
.execAsync(
`npm ls --${env}=true --parseable=true --long=false --silent --all >> ${depFile}`,
{ cwd: dirWithPackageJson }
)
.catch(() => BbPromise.resolve());
```
But it was being splitted incorrectly using `\n` instead of `\r\n` which is the separator used on Windows. This PR solves the issue by using node native `os.EOL` instead.
Output after testing the fix locally:
```
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service p*******s.zip file to S3 (6.44 MB)... …
```
> fix(Packaging): Properly exclude devDependencies on Windows

- lib/plugins/aws/invokeLocal/index.js
It solves a bug I've introduced as a part of https://github.com/serverless/serverless/pull/8744/files 
Closes: #8806
> fix(Standalone): Ensure proper resolution of runtime wrappers

- lib/plugins/aws/deployFunction.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/deployFunction.test.js
Closes: #[8692](https://github.com/serverless/serverless/issues/8692): `provider.kmsKeyArn` and `functions[].kmsKeyArn` are not supported with single function deployment}
> feat: Support `kmsKeyArn` for `deploy function`

- docs/providers/aws/events/kafka.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/kafka.js
- lib/plugins/index.js
- test/unit/lib/plugins/aws/lib/naming.test.js
- test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
> feat(AWS Lambda): Add support for self-managed `kafka` event

- lib/plugins/package/lib/zipService.js
Ensure to properly exclude dependencies, independent of the platform/os used.
Addresses: #8802
> fix(Packaging): Proper exclusion of dependencies across platforms

- docs/providers/aws/events/cloudfront.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/cloudFront.js
- test/unit/lib/plugins/aws/package/compile/events/cloudFront.test.js
> fix(AWS CloudFront): Ensure unique names for cache policy

- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
This regular expression has been broken before, it's time it gets tested properly
Closes: #8764
I'm not sure whether `naming.js` is the best location to move the regular expression to, but it was the best I could find given that I'm not familiar with the codebase.
> Fix using dashes in AWS resource tags, add unit tests

- lib/Serverless.js
- lib/cli/resolve-configuration-path.js
Closes: https://github.com/serverless/serverless/issues/8833
Not introducing tests as:
- Issue happened only when deprecated functionality was used
- Cannot be tested via `runServerless`, but only via issuing spawned `sls` and confirming it went fine. Don't want to increase maintenance burden introducing such test setup, especially that case will not be addressable with next major
> CLI: fix service path resolution when nested config is involved

- docs/providers/aws/guide/functions.md
- lib/classes/ConfigSchemaHandler/normalizeAjvErrors.js
- lib/plugins/aws/provider.js
- test/unit/lib/classes/ConfigSchemaHandler/normalizeAjvErrors.test.js
When verifying content for blog post, I've noticed a weird behavior around configuration for images and it turns out, that CloudFormation is currently limited in such a way that it always require to provide both `Command` and `EntryPoint`, whenever any of the properties from `ImageConfig` are provided. This Pr adds a clarification around that in docs + improves schema dependencies.
> fix(AWS Lambda): Add schema dependencies for image config

- lib/Serverless.js
- lib/utils/analytics/generatePayload.js
- test/unit/lib/Serverless.test.js
_Fixes issue reported on our internal Slack_
When user has outdated _global_ installation of `serverless` which fallbacks to _local_ one which is latest, there can be a situation where old _global_ version doesn't pass resolved configuration path or object to _local_ one constructor.
That normally triggers a deprecation. Still deprecation is intended to be present to users which attempt to use `Serverless` programmatically, while here situation was effect of valid (and not deprecated) CLI usage.
Patch ensures that given deprecation does not show in such case, also improved internals so in future we can prevent such deprecations if configured directly in constructor (at this point we're unable to prevent `MISSING_SERVICE_CONFIGURATION` deprecation to be shown, which still can happen with …
> CLI: Ensure to not display deprecations specific to programmatic usage

- docs/getting-started.md
- scripts/pkg/install.sh
Closes: #8855 
Added the ability to specify a version in the standalone installer. This is done by setting a `VERSION` variable after the pipe and before `bash`.
```bash
curl -o- -L https://slss.io/install | VERSION=2.21.1 bash 
```
I tested it manually. There are no automated tests for this, right?
Skipped the manual `npm run ...` and `npm test` steps, as this is only touching a single bash script file.
Are there any style guides regarding bash scripts?
> feat(installer) Add ability to specify version in standalone installer

- lib/plugins/aws/invokeLocal/index.js
During refactoring to `async` (https://github.com/serverless/serverless/commit/84d423d3be9d89475a22f29f808d506fb4f56d3c), a little regression sneaked in where we didn't properly handle error that signaled that Java bridge is not present. 
Closes: #8859
> Properly handle error if Java bridge is not present

- lib/plugins/aws/package/compile/events/alb/index.js
- lib/plugins/aws/package/compile/events/cognitoUserPool.js
- lib/plugins/aws/package/compile/events/lib/ensureApiGatewayCloudWatchRole.js
- lib/plugins/aws/package/compile/events/s3/index.js
* `lib/plugins/aws/package/compile/events/*.js`
* `lib/plugins/aws/package/compile/events/alb`
* `lib/plugins/aws/package/compile/events/lib`
* `lib/plugins/aws/package/compile/events/s3`
> refactor: Use `async` in `aws/package/compile/events`

- lib/plugins/aws/provider.js
AWS Lambda now supports nodejs14.x
Updated the validation so that serverless does not throw a warning when using in projects with nodejs14.
> feat(AWS Lambda): Add support for `nodejs14.x` runtime

- docs/providers/aws/guide/variables.md
Update documentation for change added in serverless/serverless#8279
> docs: Add `Sub` function example to pseudo parameters doc.

- lib/plugins/aws/lib/checkIfEcrRepositoryExists.js
- test/unit/lib/plugins/aws/remove/index.test.js
As discussed, I've went with gracefully handling access denied exceptions + emitting warning in cases where there are `images` defined. 
Closes: #8892
> fix(AWS Deploy): Gracefully handle denied access to ecr

- lib/cli/eventually-list-version.js
- lib/cli/handle-error.js
- scripts/serverless.js
Attempt to fix situation where `sls --version` or version reported with thrown error is not accurate if local installation of Serverless is involved
> fix: Properly resolve local version

- lib/plugins/aws/lib/naming.js
- test/unit/lib/plugins/aws/lib/naming.test.js
I missed the fact that we allow `service` and `stage` to use naming patterns that are incompatible with ECR repository naming patterns (consecutive and trailing dashes). That PR should fix that issue. 
Closes: #8905
> fix(AWS Lambda): Ensure proper normalization of ecr repo name

- docs/providers/aws/cli-reference/deploy.md
This matches the Azure, Kubeless and OpenWhisk providers; the AWS `deploy` command
is checking the flag as well.
See https://github.com/serverless/serverless/blob/134db21ed27874ae64db1c8964523b5b5ae6c2bf/lib/plugins/aws/deploy/index.js#L88-L94
Note that there is also the `shouldNotDeploy` flag on the provider, which seems to be an internal flag only.
> docs: Document the `noDeploy` switch for `aws` provider

- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/provider.test.js
Minor fix that should properly resolve repository name when using images with tags defined and repository has slashes in it's name. 
Closes: #8917
> Properly resolve SHA for repo with slashes

- lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json
I fixed issue where serverless.ts could not reference type definitions. see below.
> fix: aws-nodejs-typescript template issue where serverless.ts could not reference type definitions

- docs/deprecations.md
- docs/providers/aws/guide/iam.md
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/provider.js
- lib/utils/report-deprecated-properties.js
- test/unit/lib/plugins/aws/deploy/lib/createStack.test.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
- test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
- test/unit/lib/utils/report-deprecated-properties.test.js
Closes: #8681
This change groups all IAM-related properties of `provider` under `iam` property like so:
new way:
```yaml
provider:
iam:
role: # can be either an arn string or an object like below:
statements:
- Effect: 'Allow',
Resource: '*',
NotAction: 'iam:DeleteUser',
managedPolicies:
- 'arn:aws:iam::123456789012:user/*',
permissionBoundary: arn:aws:iam::123456789012:policy/boundaries
deploymentRole: arn:aws:iam::123456789012:role/my-role
```
old way
```yaml
provider:
role: arn:aws:iam::123456789012:role/my-role
- Effect: 'Allow',
Resource: '*',
NotAction: 'iam:DeleteUser',
iamManagedPolicies:
- 'arn:aws:iam::123456789012:user/*',
rolePermissionsBoundary: arn:aws:iam::123456789012:policy/boundaries
cfnRole: arn:aws:iam::123456789012:role/my-role
```
> feat(AWS IAM): Group IAM-related settings under `provider.iam`

- docs/providers/aws/guide/plugins.md
- lib/plugins/create/templates/plugin/README.md
- lib/plugins/create/templates/plugin/package.json
As discussed, this adds a few small changes to documentation and `plugin` template:
- Introduce `package.json` with `peerDependencies` specified for `plugin` template
- Introduce a simple `README.md` with a few resources on how to build a plugin or how to share it 
- Remove references to `subcommands` in plugins (in relation to recent discussion about removing support for subcommands altogether)
- Add notes regarding development of plugins for Serverless Framework `2.x` (and potential further majors)
I also considered moving the general doc outside of `aws` provider section - what do you think? Do you have any other suggestion to the structure of our current information and/or proposed changes?
> Improve docs and template for `plugins`

- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
Noticed this while looking into an error with `getHttpPath` (it's possible for it to be passed `undefined`), and figured might as well 🤷
> refactor: Remove unneeded `split` in `getHttp`

- scripts/serverless.js
Minor fix - `list-version` was not invoked after require which resulted in version not being printed
> fix: Ensure that `list-version` is invoked

- lib/plugins/create/templates/aws-nodejs-typescript/package.json
This is in response to [@fredericbarthelet's response](https://github.com/serverless/serverless/pull/8646#issuecomment-775933062) to my comment on #8646.
I've inferred from your comment, @fredericbarthelet, that the config is needed for the plugin to work, hence the intent is not to include it, so this PR removes it from the `package.json`.
In regards to the `.gitignore` file, I've just found that [the template already has one](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/aws-nodejs-typescript/.gitignore) - however it isn't created when the template is installed.  A fix for that is beyond me currently.
Thank you!
> chore(Templates): Remove unused deps in `aws-nodejs-typescript`

- lib/plugins/aws/deploy/lib/uploadArtifacts.js
- test/unit/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
[CI fail](https://github.com/serverless/serverless/runs/1909457155?check_suite_focus=true) exposed an internal issue in stream handling.
This patch ensures that eventual stream error is handled
> AWS Deploy: Ensure to handle artifact stream read errors

- .gitignore
- .npmignore
It reverts the previous change as it turned out that it's impossible to include `.gitignore` in npm packages. I've tried adding it to `.npmignore` as well and after some searching it seems like our current approach is the standard (e.g. yeoman, create-react-app are using the same approach). I've also adjusted a few templates that had `.gitignore` with a `.` initially.
> fix(Templates): Bring back `gitignore` to include in package

- lib/plugins/aws/package/compile/functions.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
Throw a more meaningful error when referencing Layer that is not defined as a part of the service. This is just a cosmetic change and full-fledged solution should be implemented as a part of https://github.com/serverless/serverless/issues/8915
Closes: #8960
> fix(AWS Lambda): Throw verbose error when referencing invalid layer

- lib/classes/Variables.js
- test/fixtures/variables/serverless.yml
- test/unit/lib/classes/Variables.test.js
Properly resolve variables if `prototype` is present in `path` to property where that variable should be replaced. Bug was caused by `_.set` preventing updates if `prototype` is present and resulted in infinite loop in variables resolver.
Closes: #8956
> fix(Variables): Properly resolve vars if `prototype` in path

- lib/plugins/create/templates/aws-groovy-gradle/.gitignore
- lib/plugins/create/templates/aws-java-gradle/.gitignore
- lib/plugins/create/templates/aws-kotlin-jvm-gradle-kts/.gitignore
- lib/plugins/create/templates/aws-kotlin-jvm-gradle/.gitignore
Bug discovered when working on #8406 - it turns out that it's not possible to package files with `.jar` extensions into npm package. I've tried explicitly including it via `npmignore` in a similar manner to `.gitignore` but it didn't work. I've also confirmed that our latest version published does not include these `jar`s. After implementing the fix, I've confirmed that it's working correctly by running tests against a package generate with `npm pack`.
> fix(Templates): Properly package `gradle-wrapper` into npm package

- .github/workflows/integrate.yml
- .github/workflows/publish.yml
As discussed, it introduces running integration tests against our standalone binary + adds an extra `prePublish` job, that runs unit tests against the artifact built with `npm pack`. I've tested the CI jobs here: https://github.com/serverless/serverless/actions?query=branch%3Aimprove-testing-of-published-packages++ - I'll remove that branch after merging this PR. 
Closes: #8406
> Improve testing standalone and package artifacts

- lib/plugins/aws/package/compile/events/alb/lib/listenerRules.js
- test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js
- test/unit/lib/plugins/aws/package/compile/events/alb/lib/listenerRules.test.js
Closes: #8954 
Changes the host-header condition to always use HostHeaderConfig dictionary, per documentation at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-rulecondition.html
Updated tests to account for the new structure and added a second host condition test that verifies a multiple-host condition.
> fix(AWS ALB): Conform to CF schema with multiple host header

- lib/classes/PluginManager.js
- lib/classes/Utils.js
- lib/classes/Variables.js
- test/unit/lib/classes/PluginManager.test.js
- test/unit/lib/classes/Variables.test.js
> refactor: Remove `bluebird` from `lib/classes`

- package.json
- test/fixtures/exception/plugin.js
- test/fixtures/exception/serverless.yml
- test/fixtures/uncaughtException/plugin.js
- test/fixtures/uncaughtException/serverless.yml
- test/unit/scripts/serverless.test.js
[`serverless`](https://github.com/serverless/serverless/blob/36c78c70d1cf306556a5a9f8a3c3908e8b4c7d05/scripts/serverless.js) main script is about to be further extended with introduction of new variables resolver, and when working on that I've realized it's no longer safe to continue without tests for this file.
Also we already had [a regression](https://github.com/serverless/serverless/pull/8945) due to lack of such sanity tests.
I've also improved the coverage `exclude` configuration (`script/serverless` was excluded), which is likely to drop numbers in our general coverage report, but at least it'll present fair report.
> Test: Sanity tests for main "serverless" script

- lib/utils/createFromTemplate.js
- lib/utils/downloadTemplateFromRepo.js
- lib/utils/fs/createZipFile.js
- lib/utils/open.js
- lib/utils/yamlAstParser.js
- test/utils/kinesis.js
Addresses: #7171
I have  few more areas asyncified in stashes in my local so I can keep submiting some of these.
> refactor: Remove `bluebird` from `lib/utils`

- lib/plugins/config.js
- lib/plugins/deploy.js
- lib/plugins/install.js
- lib/plugins/invoke.js
- lib/plugins/print.js
- test/unit/lib/plugins/config.test.js
- test/unit/lib/plugins/deploy.test.js
- test/unit/lib/plugins/invoke.test.js
…older
Addresses: #7171
I can keep adding the rest of the folders under `lib/plugins` since I sort of have them. Just need to review then.
> refactor: Remove `bluebird` from top-level `lib/plugins`

- lib/cli/parse-args.js
- test/unit/lib/cli/parse-args.test.js
Addresses issue reported in comment: https://github.com/serverless/serverless/pull/8927#issuecomment-782972623
In current version parser doesn't recognize empty params (as `--param-=`). This patch fixes that
> CLI: Fix resolution of empty valued params as `param=`

- lib/plugins/aws/package/compile/functions.js
When doing some tests, I've noticed that lambda hashing related deprecation is also output when service has no functions configured, it should not be the case.
> Display function versioning related deprecation only when some functions are configured

- docs/deprecations.md
> docs: Fix typo in deprecation docs for `iam` properties

- docs/guides/providers.md
This PR updates the docs on https://www.serverless.com/framework/docs/guides/providers/ to include the Default Organization Provider feature. It also makes some minor tweaks to existing language.
> Update docs to add default org provider for dashboard 

- .github/workflows/publish.yml
Fix invalid resolution of package version via `npm view . version`.
> ci: Properly resolve package version generated by npm pack

- lib/cli/resolve-input.js
- test/unit/lib/cli/resolve-input.test.js
Closes: #8995
- Recognize `--stage` and on special terms `-s` alias (unfortunately some commands use it for something else)
- Refactor handling of `-v` stage to follow same methodology as `-s` handling
- Add recognition of `app` and `org`
> CLI: Recognize "-s" as "--stage" alias, and other common params

- lib/plugins/plugin/install.js
- lib/plugins/plugin/lib/utils.js
- lib/plugins/plugin/list.js
- lib/plugins/plugin/plugin.js
- lib/plugins/plugin/search.js
- lib/plugins/plugin/uninstall.js
- test/unit/lib/plugins/plugin/install.test.js
- test/unit/lib/plugins/plugin/lib/utils.test.js
- test/unit/lib/plugins/plugin/list.test.js
- test/unit/lib/plugins/plugin/plugin.test.js
- test/unit/lib/plugins/plugin/search.test.js
- test/unit/lib/plugins/plugin/uninstall.test.js
Addresses: #7171
I'll keep them coming
> refactor: Remove `bluebird` from `lib/plugins/plugin`

- docs/providers/aws/guide/serverless.yml.md
Adds the documentation for the property `maximumBatchingWindow` added by #8555.
> docs(AWS SQS): Add `maximumBatchingWindow` in `serverless.yml.md`

- docs/providers/aws/README.md
…ng page
I just saw this link was missing the other day.
> docs: Missing `kafka` link on provider landing page

- lib/configuration/variables/parse.js
- test/unit/lib/configuration/variables/parse.test.js
Discovered when testing case posted in: #9010
Additionally improved unterminated literals detection
> Variables: Fix infinite loop parsing issue

- docs/providers/aws/guide/serverless.yml.md
- lib/Serverless.js
- lib/cli/conditionally-load-dotenv.js
- lib/cli/load-dotenv.js
- scripts/serverless.js
- test/unit/lib/Serverless.test.js
- test/unit/lib/cli/conditionally-load-dotenv.test.js
- test/unit/lib/cli/load-dotenv.test.js
- test/unit/scripts/serverless.test.js
Addresses 2.4 from https://github.com/serverless/serverless/issues/8364
Kept fallback to resolve `.env` in `Serverless` class, so it remains working for users which e.g. just upgrade the local installation, but run `serverless` global installation, with v3 we will remove it.
Additionally added some inline documentation, to improve readability of currently extending logic (I expect it to be significantly stripped, once we remove all the deprecations with next major)
> CLI: Resolve ".env" files before initializing "Serverless" constructor

- lib/plugins/create/create.js
- test/unit/lib/plugins/create/create.test.js
> refactor: Remove `bluebird` from `lib/plugins/create`

- docs/providers/aws/guide/variables.md
The section on `Recursively reference properties` is using a feature that is first explained much later in the document at [Overwriting Variables](https://www.serverless.com/framework/docs/providers/aws/guide/variables#overwriting-variables).
I was surprised by the use of `self:provider.stage` which is a dead reference and got no explanation before the end of the document.
Alternative solutions
* Move `Overwriting Variables` to a location before `Recursively reference properties`
* This change making the section more context independent being stateless is a good thing outside of code as well :smile:
> Prevent reader confusion

- docs/providers/aws/guide/variables.md
Fixes an example with invalid syntax
> docs: Add missing `async` keyword in `variables.md`

- lib/plugins/interactiveCli/setupAws.js
- lib/plugins/interactiveCli/tabCompletion.js
- test/unit/lib/plugins/interactiveCli/autoUpdate.test.js
- test/unit/lib/plugins/interactiveCli/setupAws.test.js
- test/unit/lib/plugins/interactiveCli/tabCompletion.test.js
> refactor: Remove `bluebird` from `lib/plugins/interactiveCli`

- test/fixtures/apiGateway/serverless.yml
- test/fixtures/apiGatewayExtended/serverless.yml
- test/fixtures/checkForChanges/serverless.yml
- test/fixtures/cognitoUserPool/serverless.yml
- test/fixtures/eventBridge/serverless.yml
- test/fixtures/function/serverless.yml
- test/fixtures/functionCloudFront/serverless.yml
- test/fixtures/functionDestinations/serverless.yml
- test/fixtures/functionLayers/serverless.yml
- test/fixtures/httpApi/serverless.yml
- test/fixtures/httpApiCatchAll/serverless.yml
- test/fixtures/httpApiExport/serverless.yml
- test/fixtures/invocation/serverless.yml
- test/fixtures/iot/serverless.yml
- test/fixtures/layer/serverless.yml
- test/fixtures/packageArtifact/serverless.yml
- test/fixtures/packageArtifactInServerlessDir/serverless.yml
- test/fixtures/packaging/serverless.yml
- test/fixtures/plugin/serverless.yml
- test/fixtures/provisionedConcurrency/serverless.yml
- test/fixtures/requestSchema/serverless.yml
- test/fixtures/sns/serverless.yml
- test/fixtures/sqs/serverless.yml
- test/fixtures/stream/serverless.yml
- test/integrationPackage/fixtures/artifact/serverless.yml
- test/integrationPackage/fixtures/individually-function/serverless.yml
- test/integrationPackage/fixtures/individually/serverless.yml
- test/integrationPackage/fixtures/regular/serverless.yml
- test/unit/lib/plugins/aws/deploy/index.test.js
- test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
It covers all integration tests. One test that still shows deprecation is eventBridge test which test custom resource deprecation.
When addressing https://github.com/serverless/serverless/issues/9024 it's important to extend config of this test with `deprecationsNotificationMode: warn`.
> Tests: Update integration tests to not rely on deprecated features

- docs/deprecations.md
- lib/plugins/aws/package/compile/functions.js
Message as configured currently gives not real clue what was really changed. I've tried to improve it and keep it relatively concise at same time.
@pgrzesik what do you think?
> Improve deprecation message related to lambda versioning 

- lib/Serverless.js
- lib/configuration/variables/eventually-report-resolution-errors.js
- scripts/serverless.js
- test/unit/lib/configuration/variables/eventually-report-resolution-errors.test.js
Addresses 2.5.0 from #8364
Additionally:
- Ensure no old variables resolver is initialized if per new resolver there are no variables to resolve in a config (this should improve performance on big configuration)
- Improve serverless process logic part responsible for variable resolution, make some parts reusable for further process flow
> Variables: Resolve all env variables with new resolver

- test/integration/schedule.test.js
- test/utils/misc.js
- Increase wait timeout for Cloudwatch logs (in response to observed "Log items not found" fails, as here: https://github.com/serverless/serverless/runs/2008020368?check_suite_focus=true)
- In AWS schedule tests, ensure to wait for logs that contain expected string (in response to CI fail observed here: https://github.com/serverless/serverless/actions/runs/614260648)
> Tests: Improve integration tests reliability

- lib/plugins/aws/provider.js
Addresses issue described at https://github.com/serverless/serverless/issues/9013#issuecomment-785945591
> AWS Credentials: Fix unrecognized profile error reporting

- lib/configuration/variables/parse.js
- lib/configuration/variables/resolve.js
- test/unit/lib/configuration/variables/parse.test.js
- test/unit/lib/configuration/variables/resolve.test.js
Addresses: https://github.com/serverless/serverless/issues/9048#issuecomment-789223294
Needed to recognize old variables notation as `${cf.us-east-1:my-project-dev.MyTableArn}`, which will not be practised with new resolver (as all source params will be passed in parens)
Additionally, ensure proper error handling for variables in result string resolution (added with https://github.com/serverless/serverless/pull/9050)
> Variables: Ensure to recognize "-" in type notation

- lib/plugins/aws/metrics.js
- lib/plugins/aws/provider.js
- lib/plugins/aws/rollback.js
- lib/plugins/aws/rollbackFunction.js
- lib/plugins/aws/utils/credentials.js
- test/unit/lib/plugins/aws/provider.test.js
- test/unit/lib/plugins/aws/rollback.test.js
- test/unit/lib/plugins/aws/utils/credentials.test.js
- test/unit/lib/plugins/aws/utils/resolveCfImportValue.test.js
- test/unit/lib/plugins/aws/utils/resolveCfRefValue.test.js
> refactor: Remove `bluebird` from `lib/plugins/aws`

- lib/Serverless.js
- lib/configuration/variables/resolve.js
- test/unit/lib/configuration/variables/resolve.test.js
Fixes: #9047 
Very similar issue as https://github.com/serverless/serverless/issues/9016, still this time shared property cache imposed a problem
Additionally, fixed a minor omission in https://github.com/serverless/serverless/pull/9040, so that constructor `isConfigurationResolved` config property is also passed locally resolved `Serverless` instance
> Variables: Ensure to not share property cache across resolutions

- scripts/serverless.js
- test/unit/scripts/serverless.test.js
Addresses 2.6 from https://github.com/serverless/serverless/issues/8364
At same time it addresses an old bug where we do not report meaningfully error if someone puts `plugins` section behind variables.
> Variables: Reject unresolved "plugins" property

- docs/providers/aws/cli-reference/invoke.md
- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/functions.md
- docs/providers/aws/guide/serverless.yml.md
- docs/providers/aws/guide/variables.md
Sync up docs with modern iam configuration options. 
Inconsistencies were discovered as part of https://github.com/serverless/serverless/pull/9039
> docs: Update docs around `provider.iam` usage

- lib/Serverless.js
- test/unit/lib/Serverless.test.js
Continuation of https://github.com/serverless/serverless/pull/9060, where patch was applied only behind `SLS_DEBUG` flag, that shouldn't be the case
> Variables: Ensure to apply intialization patch unconditionally

- lib/cli/handle-error.js
- lib/utils/tokenize-exception.js
- scripts/serverless.js
- test/unit/lib/utils/tokenize-exception.test.js
If dashboard error handler errors during reporting, we exposed that error with plain meaningful log.
This patch improves this DX.
Before:
After:
> Fix dashboard error handling reporting

- docs/providers/aws/guide/iam.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/functions.js
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Provide consumers means for setting additional/custom tags to the lambda execution role.
Closes: #8669
> feat(AWS IAM): Allow `tags` parameter on lambda execution role

- lib/plugins/aws/provider.js
Issue around using 
```yaml
resourcePolicy:
Principal:
AWS: 
- 123456789012
- 987654321098
```
causing a schema validation warning
I have added `#/definitions/awsAccountId` and updated `awsIamPolicyPrincipal` to include it as a possible option
Closes: [#9077](https://github.com/serverless/serverless/issues/9077)
> feat(Config Schema): Accept `accountId` as policy principal

- lib/configuration/variables/resolve.js
- lib/configuration/variables/source-resolution-error.js
- lib/configuration/variables/sources/env.js
- lib/configuration/variables/sources/file.js
- lib/configuration/variables/sources/opt.js
- lib/configuration/variables/sources/self.js
- lib/configuration/variables/sources/str-to-bool.js
- package.json
- scripts/serverless.js
- test/unit/lib/configuration/variables/resolve.test.js
- test/unit/lib/configuration/variables/source-resolution-error.test.js
- test/unit/lib/configuration/variables/sources/env.test.js
- test/unit/lib/configuration/variables/sources/file.test.js
- test/unit/lib/configuration/variables/sources/opt.test.js
- test/unit/lib/configuration/variables/sources/self.test.js
- test/unit/lib/configuration/variables/sources/str-to-bool.test.js
Part of  #8364
__Notice__: https://github.com/serverless/test/pull/86 is needed to be merged and published, for tests to pass
More powerful handling of _pending_ sources (e.g. `env` before evntual other env variables are loaded from `.env` or `opt` before we know the full options schema of used command)
In so far implementation, source was marked upfront as `isIncomplete` and then any `null` resolved from it was treated as possibly incomplete resolution that should be confirmed after source is incomplete.
Still in case of `opt` source (when we will know full schema of options) it'll be possible to know upfront that value for supported option is `null` (even if we don't have a schema for all possible commands or options available), and so far implementation didn't give a room to …
> Variables: Improve resolution states handling

- lib/cli/list-version.js
- package.json
- test/unit/lib/cli/list-version.test.js
Upgrade `@serverless/enterprise-plugin` and use `platformClientVersion` instead of deprecated `sdkVersion` for reporting.
> feat(CLI): Report Platform Client instead of SDK version

- lib/plugins/aws/deployFunction.js
- test/unit/lib/plugins/aws/deployFunction.test.js
Any AWS SDK rejection is reported as if it's _function not yet deployed_ error, e.g. missing credentials issue is also reported like that.
> AWS Deploy: Fix "sls deploy function" error handling

- lib/configuration/variables/sources/file.js
- test/unit/lib/configuration/variables/sources/file.test.js
- test/unit/lib/configuration/variables/sources/fixture/file-function-access-unresolvable-property.js
- test/unit/lib/configuration/variables/sources/fixture/file-property-function-access-unresolvable-property.js
Fixes: #9105
When JS function resolvers approach a property that cannot be resolved at given resolution phase, they should be retried (re-run) in next resolution phase
> Variables: Retry JS function resolvers on unresolved dependencies

- lib/plugins/aws/package/compile/functions.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
This small fix allows you to use role ARNs that contain ${AWS::Partition} pseudo-variables. For example:
```
functions:
myfunc:
role: arn:${AWS::Partition}:iam::${AWS::AccountId}:/role/myfuncrole
```
> fix(AWS IAM): Accept `arn:${AWS::Partition}` in function roles

- lib/plugins/aws/provider.js
Currently, invalid `vpc` configuration was failing silently in cases where e.g. one of the properties was missing or had a typo in it - behind the scenes Framework was removing the VPC configuration altogether during compilation which wasn't visible to end user. This aims to fix it by ensuring both properties are present (it is a requirement: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html) and that no other properties are provided.
> fix(AWS Lambda): Ensure correct schema for `vpc` definition

- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/provider.test.js
Unfortunate regression introduced with https://github.com/serverless/serverless/pull/8850
This sensitive part was not really covered by tests, hence it sneaked in.
Technically internal resolution of AWS credentials is ineffective, and if commands work, it's only because AWS SDK resolves credentials on its own
Closes: #9119
> Fix AWS credentials resolution

- docs/providers/aws/events/event-bridge.md
- lib/plugins/aws/package/compile/events/eventBridge/index.js
Clarify the support for CF intrinsic functions for `eventBridge.eventBus` setting + throw an error when someone defines it with a reference to ARN via CF function
> fix(AWS EventBridge): Clarify CF functions support for `eventBus`

- lib/plugins/aws/provider.js
> Bring back "provider.sdk" property, to not break plugins

- lib/classes/Service.js
- test/unit/lib/classes/Service.test.js
It was uncovered with https://github.com/serverless/serverless/issues/9130 that the Framework does not handle situation where someone provides an empty function definition gracefully and instead throws an error that it's not very helpful for user. This PR aims to fix this by ensuring that `functionObj` is always an object which lets our schema engine do the rest of the validation. 
Before the error looked like:
```
Type Error ----------------------------------------------
TypeError: Cannot read property 'events' of null
at testing/node_modules/serverless/lib/classes/Service.js:179:24
at Array.forEach (<anonymous>)
at Service.setFunctionNames (testing/node_modules/serverless/lib/classes/Service.js:178:36)
at Serverless.run (testing/node_modules/serverless/lib/Serverless.js:265:18)
at …
```
> fix: Ensure to handle empty func definition with meaningful error

- lib/plugins/package/lib/zipService.js
During investigation, I discovered that `NODE_ENV` set to `production` breaks the output of `npm ls --dev=true` - this PR aims to address it by zeroing `NODE_ENV` variable for that specific call. 
Closes: #9134
> fix(Packaging): Ensure to properly exclude when NODE_ENV set

- lib/aws/request.js
With `SLS_DEBUG` we're expected to see full stack traces. Still in case of AWS SDK errors, it's still not the case, which may hide useful information (as it's in case of https://github.com/serverless/serverless/issues/9146#issuecomment-802671513)
This patch improves that.
> Improve AWS SDK errors reporting (debugging)

- lib/plugins/aws/lib/monitorStack.js
After recent change, with `SLS_DEBUG`, the error message includes stack trace, which broke the detection of finished stack removal during `sls remove`. This PR aims to fix it.
> fix(AWS Deploy): Correctly detect finished stack removal with DEBUG

- lib/aws/request.js
- lib/plugins/plugin/lib/utils.js
Closes: #9146 
This is a hotfix.
Nevertheless the `url.parse` method is deprecated.
> hotfix(env): (#9146) revert WHATWG URL to use  url to verify usage of https-proxy-agent

- docs/deprecations.md
- lib/plugins/aws/package/compile/events/apiGateway/index.js
As discussed, this PR removes deprecation log for not opting in with new naming convention for API Gateway.
> feat(AWS API Gateway): Remove deprecation for old naming convention

- lib/Serverless.js
Addresses issue reported internall, when user received an error as on below screenshot
Error comes from plugin invoking a variable resolver, which is missing `this.options` due to fact that `populateService()` was not invoked as configuration was assumed to have no properties behind variables.
It also addresses on our side issue originally reported at https://github.com/serverless/serverless/issues/9099
/cc @garethmcc @astuyve
> fix(Variables): Ensure necessary resolution interface for plugins

- docs/providers/aws/guide/iam.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/lib/naming.test.js
- test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Inspired by https://github.com/serverless/serverless/pull/8888
Fixes #8887
Closes: #8887
> feat(AWS IAM): Add support for `iam.role.name` definition

- docs/providers/aws/guide/functions.md
- lib/plugins/aws/provider.js
It looks like AWS fixed the previously quirky behavior of requiring all properties of `ImageConfig` - we no longer need that validation on Framework side. 
Closes: #9173
> feat(AWS Lambda): Do not require all image properties

- docs/providers/aws/guide/serverless.yml.md
[The default payload is now 2.0 for HTTP APIs](https://github.com/serverless/serverless/blob/9f5fd6100978a0bda1c300b9429b24b6e586c52f/lib/plugins/aws/package/compile/events/httpApi.js#L496). 
Also enjoyed and bumped the version to NodeJS 14 as it's available for a while.
> docs: Update default payload of `httpApi` in `serverless.yml.md`

- lib/plugins/package/lib/zipService.js
It seems that `normalizedFilesToChmodPlusX` was removed and does not exist anymore so removing it from the comment seemed appropriate
> chore: Update code comment about file stat chmod

- docs/providers/aws/events/http-api.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/httpApi.js
- lib/plugins/aws/provider.js
- lib/utils/analytics/generatePayload.js
- test/fixtures/httpApi/authorizers.js
- test/fixtures/httpApi/serverless.yml
- test/integration/httpApi.test.js
- test/unit/lib/plugins/aws/lib/naming.test.js
- test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js
- test/unit/lib/utils/analytics/generatePayload.test.js
Adds support for custom Lambda authorizers for HTTP API. There is a slight change to original proposal, instead of `name` and `arn` I used `functionName` and `functionArn` because `name` was already reserved for overriding authorizer name. 
Additionally it includes a small fix to `generatePayload` to a bug that was exposed after adding authorizer functions to `httpApi` fixture. 
Addresses: #8210
> feat(AWS HTTP API): Add support for custom Lambda authorizers

- docs/providers/aws/events/http-api.md
- lib/plugins/aws/package/compile/events/httpApi.js
- test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js
Add support for `AWS_IAM` authorization for `httpApi`
Closes: #8210
> feat(AWS HTTP API): Add support for AWS IAM authorization

- test/fixtures/apiGateway/index.js
- test/fixtures/apiGateway/serverless.yml
- test/integration/apiGateway.test.js
- test/integration/apiGatewayExternal.test.js
Separate external API integration tests and run them as a clean stack instead of using `update` due to bug on AWS side that causes tests to timeout. I've decided to move them to separate module to run them in parallel with the original ones.
> test: Separate external API integration tests for API Gateway

- lib/Serverless.js
- scripts/serverless.js
- Ensure that `commands` are passed to local installation (due to typo they weren't it - it wasn't breaking as then internal logic attempts to resolve commands on they're own, but that's definitive logic leak
- Ensure to not trigger old variables resolver when all variables are resolved with new resolver (forgot to add that when registering revolvers for final sources) - More optimization, than actual fix
> Minor patches to CLI & Variables refactor

- docs/providers/aws/guide/iam.md
- lib/plugins/aws/package/compile/functions.js
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
- test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
When checking out the issue report I've discovered that support for CF functions is broken for `provider.iam.role` and we're silently creating default role that is used by functions. 
Closes: #9199
> fix(AWS IAM): Support for CF functions for `provider.iam.role`

- docs/providers/aws/guide/variables.md
We've recent changes I removed note on AWS pseudo parameters from our variables doc (as resolution of them is not part of our Variables resolver).
Still it appeared to be confusing: https://github.com/serverless/serverless/commit/7e8c202dd02bb641ecde5ffea5ee9bfeeef69720#r48982426
With this update, I bring back notice, that we allow to use them, still there's no implied resolution mechanism on Framework side for them.
> Documentation: Add note on support of AWS CF specific variables

- docs/deprecations.md
#8581 added `patterns`, which deprecated `package.include` & `package.exclude`, but the docs specifies the wrong deprecation code.
> docs: specify correct deprecation code for new `patterns` pattern

- docs/providers/aws/guide/variables.md
- lib/configuration/variables/sources/instance-dependent/get-ssm.js
- test/unit/lib/configuration/variables/sources/instance-dependent/get-ssm.test.js
> Variables: Support resolving "raw" JSON string form of SSM params

- docs/deprecations.md
- docs/providers/aws/guide/plugins.md
- lib/cli/commands-schema/aws-service.js
- lib/cli/commands-schema/common-options/aws-service.js
- lib/cli/commands-schema/common-options/global.js
- lib/cli/commands-schema/common-options/service.js
- lib/cli/commands-schema/no-service.js
- lib/cli/commands-schema/resolve-final.js
- lib/cli/commands-schema/service.js
- lib/cli/resolve-input.js
- scripts/serverless.js
Addresses: https://github.com/dherault/serverless-offline/issues/1203
With recent changes type awareness was introduced to CLI options parsing. Options which do not have _type_ defined were unconditionally assumed as _string_ type, and that introduced errors in handling of _boolean_ options with no type set.
While all Framework commands had types property set, we could not expect that in external plugins.
This patch ensures we do not assume any type for an option, if no type is explicitly defined, and additionaly we communicate lack of type with deprecation
> CLI: Fix handling of options definition plugin extensions 

- lib/plugins/aws/package/compile/events/cloudFront.js
> AWS CloudFront: Recognize "?" character in `pathPattern` property

- lib/configuration/resolve-provider-name.js
- scripts/serverless.js
- test/unit/lib/classes/CLI.test.js
- test/unit/scripts/serverless.test.js
When `sls --help` is run in context of service which does not have set `provider.name`. The error about property being missing is shown instead of help output.
> CLI: Fix help output when provider.name is missing

- lib/plugins/aws/lib/updateStack.js
- test/unit/lib/plugins/aws/lib/updateStack.test.js
> fix(AWS Deploy): Correctly identify "no updates" error during deploy

- lib/configuration/read.js
- test/unit/lib/configuration/read.test.js
When `ts-node` is registered multiple times (e.g. by multiple packages) then errors occur since already-compiled Typescript will be fed through ts-node again. See [this issue](https://www.github.com/TypeStrong/ts-node/issues/409) for details.
Additionally, when exporting config using ES6 module syntax (`export default ...`) - which is typical of TS environments - serverless fails to load the configuration. This is resolved by attempting to interop `.default` before falling back.
> Avoid re-registration of ts-node ~and interop default when config is exported using ES6 module syntax~

- README.md
> docs: Removed reference to `dashboard.serverless.com`

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Note: Not all AWS Accounts are yet affected by this change.
Closes: #9223
> fix(AWS API Gateway): Do not attempt to remove `aws:` tags during update

- lib/plugins/aws/customResources/index.js
- test/unit/lib/plugins/aws/customResources/index.test.js
After recent changes the bug surfaced where the `stage` for custom resource needed for API Gateway logs did not take into account setting from `provider.stage` 
Closes: #9240, #9268
> fix(AWS API Gateway): Proper stage resolution for custom resource

- lib/plugins/aws/package/compile/events/httpApi.js
- lib/plugins/aws/provider.js
Slightly adjust schema to not rely on automatic coercion to `array`, which can produce invalid `serverless/typescript` types. 
Closes: #9269
> fix(AWS HTTP API): Adjust schema for correct `typescript` generation

- lib/plugins/aws/invokeLocal/index.js
- test/unit/lib/plugins/aws/invokeLocal/index.test.js
> fix(AWS Local Invocation): Strip `null` envvars for local invoke

- docs/providers/aws/events/alb.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/alb/index.js
- lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js
- lib/plugins/aws/package/compile/events/alb/lib/validate.js
- test/unit/lib/plugins/aws/lib/naming.test.js
- test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js
- test/unit/lib/plugins/aws/package/compile/events/alb/lib/validate.test.js
Corresponding issue : https://github.com/serverless/serverless/issues/9213
@pgrzesik I'm not sure about the `getAlbTargetGroupNameTagValue` function. For example today it doesn't uses the `provider.alb.targetPrefix` property and creates a name which is more aligned with other generated names by serverless. Also it doesn't require to be less than 32 characters, nor to be unique. So I guess it's a good place to have a more precise name with less constraints. What do you think ?
I didn't modify it but if you want me to change it and juste return  `provider.alb.targetPrefix + targetGroupName` when it's defined I will.
I'm having issues with the master branch of serverless (`pathType.dirSync is not a function` ? it still works with 2.32.1. Or maybe it's not supposed to work using npm link ?) …
> feat(AWS ALB): Make it possible to specify the TargetGroup name

- lib/classes/Variables.js
- lib/plugins/aws/provider.js
- test/unit/lib/classes/Variables.test.js
- test/unit/lib/plugins/aws/invokeLocal/index.test.js
Removes support for undocumented setting `provider.credentials`. 
Addresses: #8356
> refactor(AWS Credentials): Remove undocumented `provider.credentials` setting support

- lib/cli/ensure-supported-command.js
- scripts/serverless.js
- test/unit/lib/cli/ensure-supported-command.test.js
- Ensure to respect `disabledDeprecations` when displaying CLI command usage related deprecation
- Validate command service dependency in CLI context
- Do not resolve variables in configuration in case of `plugin..` commands (fixes #5774)
> CLI & Variables improvements

- lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
For provided `authorizerId` we did not correctly resolve `AuthorizationType` for `AWS::ApiGateway::Method` resource
Closes: #9294
> fix(AWS API Gateway): Correctly recognize `type` for `authorizerId`

- lib/utils/analytics/index.js
- package.json
- test/unit/lib/utils/analytics/index.test.js
Addresses 2 from #9257 
Additionally, it includes cleanup/refactoring for tests
> feat(Analytics): Send all telemetry events with single request

- docs/deprecations.md
- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/apiGateway/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
> fix(AWS API Gateway): Deprecate invalid `apiGateway` settings

- docs/deprecations.md
- docs/providers/aws/guide/iam.md
- lib/plugins/aws/package/lib/mergeIamTemplates.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
fix: Deprecated IAM Role 'permissionBoundary' property in favor of
'permissionsBoundary' to match CloudFormation. The previous property
name will still be supported at present.
Closes: #9215
> fix(AWS IAM): Deprecate 'iam.role.permissionBoundary'

- lib/cli/commands-schema/common-options/aws-service.js
- test/unit/lib/cli/filter-supported-options.test.js
Address issue pointed here: https://github.com/serverless/serverless/issues/8356#issuecomment-821948879
During CLI options refactor, it was lost that internally we also support `--aws-profile` option (this option was never listed in any commands `options` and did not also appeared in help documentation)
> CLI: Recognize `--aws-profile` option by schema

- docs/deprecations.md
- docs/guides/cicd/preview-deployments.md
- docs/providers/aws/guide/credentials.md
- docs/providers/aws/guide/functions.md
- docs/providers/aws/guide/iam.md
- docs/providers/aws/guide/layers.md
- docs/providers/aws/guide/serverless.yml.md
- docs/providers/aws/guide/services.md
- docs/providers/aws/guide/variables.md
- docs/providers/spotinst/cli-reference/stage.md
- lib/configuration/variables/sources/instance-dependent/get-sls.js
- test/unit/lib/configuration/variables/sources/instance-dependent/get-sls.test.js
`${sls:stage}` is a shortcut to:
```
${opt:stage, self:provider.stage}
```
This is a new attempt at solving #6031, replacing older PR #6049.
As a start, I'm only introducing `${sls:stage}` for now, and opening this PR as WIP. Once we're happy with the implementation, I'll add `region` in this PR.
Closes: #6031
Note: `npm run lint` shows errors all over the codebase, so I'm ignoring it for now.
> #6031 Add the `sls:stage` variable

- lib/utils/telemetry/index.js
- test/unit/lib/utils/telemetry/index.test.js
In situations when there was a problem with saving and/or reading telemetry events, we should not attempt to send an empty event list.
> fix(Telemetry): Do not send request when there are no events

- lib/classes/Service.js
Closes: #9351
Brings back `service.serviceFilename` removed with https://github.com/serverless/serverless/commit/fc3a4391b5411f77a51a84f93a166903c51cb80f
> API: Bring back legacy `service.serviceFilename` to not break plugins

- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.js
- test/unit/lib/plugins/aws/lib/naming.test.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.test.js
fix: Create a single request validator for all API Gateway request schemas instead of creating a new request validator per request schema. This resolves the issue of hitting the 20 request validator hard limit imposed by API Gateway.
Closes: #9291
> #9291 fix: Create a single request validator instead of a request validator per request schema

- docs/providers/aws/guide/iam.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/lib/naming.test.js
- test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
feat: Added support for custom IAM Role path via property `provider.iam.role.path`.
Closes: #9347
> 9347 - Support for custom IAM Role path

- docs/providers/aws/guide/variables.md
- lib/configuration/variables/resolve.js
- lib/configuration/variables/sources/file.js
- test/unit/lib/configuration/variables/resolve.test.js
- test/unit/lib/configuration/variables/sources/file.test.js
- test/unit/lib/configuration/variables/sources/fixture/file-function-variable.js
- test/unit/lib/configuration/variables/sources/fixture/file-property-function-variable.js
Closes: #9112 
After all, instead of introducing `resolveSource(name, { params, address })`, I decided to introduce `resolveVariable(variableString)` as that feels way more convenient, and I believe more simple to use (it's also a bit more powerful, as supports fallback sources in same manner as when variables are configured into properties).
> Variables: Expose variable resolver function to variable source resolvers

- lib/Serverless.js
- lib/classes/PluginManager.js
- scripts/serverless.js
Addresses: #9346 
I'm still not sure about potentially refactoring the implementation that currently lives in `PluginManager`, do you feel like we should also change it to report after the command executes? What about further changes to it when we will detect if command failed with error?
> Send telemetry after command is processed in `scripts/serverless.js`

- lib/plugins/create/templates/cloudflare-workers-enterprise/package.json
- lib/plugins/create/templates/cloudflare-workers/package.json
serverless-cloudflare-workers's old version in template not support to config worker's environment variable through `serverless deploy`. Update it in the cli generated template to support this feature.
related issue: https://github.com/serverless/serverless/issues/9372
> feat(Templates): Update dependencies for `cloudflare` template

- lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.test.js
> fix(AWS API Gateway): Ensure unique name for request validator

- test/mochaPatch.js
Make sure that during tests we won't accidentally send telemetry events
> Ensure telemetry is not emitted during tests

- docs/providers/aws/cli-reference/deploy.md
- docs/providers/azure/cli-reference/deploy.md
- docs/providers/kubeless/cli-reference/deploy.md
As a follow up to https://github.com/serverless/serverless/discussions/9389, complements https://github.com/serverless/serverless/commit/688d09b1f7f28f8b1656d3f7f31c6c2765a01b9d
In Azure and Kubeless this option was never supported, so it was simply listed there by mistake.
It is actually supported in Openwhisk so I left it documented there (and it's the only place in our docs where this option remains listed)
Technically removing this option (which was done and published already) can be considered breaking. When I did that, I mistakenly assumed it was added just for internal testing purpose, while it appeared that it was added in early stage of v1 for v0.5 resemblance (where such option was supported)
However:
- This option was not listed in options list internally (so never appeared in …
> Documentation: Remove reference to not supported `--noDeploy`

- lib/cli/resolve-input.js
There's an internal concept of _container_ command, which is a no-op command name in middle, which if invoked we show help showing sub commands, e.g. it's the case for `config tabcompletion`.
Those commands were not marked as _help_ commands, so they're destined for telemetry. Still they also do not have command schema, and that crashes telemetry payload generation here: https://github.com/serverless/serverless/blob/95e063d904443044b73d61e73d04447b298d22ed/lib/utils/telemetry/generatePayload.js#L125
Marking telemetry command as _help_ command fixes the issue
> Telemetry: Ensure that container commands do not trigger telemetry

- lib/cli/render-help/index.js
- test/unit/scripts/serverless.test.js
Discovered that general help is listed under interactive CLI help, that's not expected. This PR fixes that
> CLI: Ensure no general help is listed under interactive setup help

- lib/utils/telemetry/anonymize-stacktrace-paths.js
- test/unit/lib/utils/telemetry/anonymize-stacktrace-paths.test.js
Fixes situation where `commonPrefixPath` was invoked with empty list of paths (all were filtered out because there were all relative)
> fix(Telemetry): Properly resolve location when for only relative paths

- lib/utils/telemetry/resolve-error-location.js
- test/unit/lib/utils/telemetry/resolve-error-location.test.js
I've noticed that the previous version didn't correcly handle situations where the location in stack trace was not enclosed in parentheses, e.g. as reported here: 
```
Error ---------------------------------------------------
Error: spawn E2BIG
at ChildProcess.spawn (node:internal/child_process:403:11)
at Object.spawn (node:child_process:573:9)
at /Users/chris/Projects/Nebula/api/node_modules/bestzip/lib/bestzip.js:75:29
at /Users/chris/Projects/Nebula/api/node_modules/async/dist/async.js:1802:20
at /Users/chris/Projects/Nebula/api/node_modules/async/dist/async.js:248:13
at wrapper (/Users/chris/Projects/Nebula/api/node_modules/async/dist/async.js:268:20)
at iterateeCallback (/Users/chris/Projects/Nebula/api/node_modules/async/dist/async.js:421:28)
at …
```
> fix(Telemetry): Handle error locations not enclosed in parens

- docs/providers/aws/events/alb.md
> docs(AWS ALB): Fixed typo in docs

- lib/plugins/aws/deployFunction.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
We should not attempt to update `VpcConfig` during `deploy function` if `vpc` uses CF intrinsic functions as they cannot be properly resolved during an update. 
Closes: #9423
> Dont update `vpc` during `deploy function` if uses CF intrinsic functions

- lib/cli/handle-error.js
- test/unit/lib/cli/handle-error.test.js
As was discovered in #9426, we should not report errors related to invalid commands as they are usually caused by a typo or missing plugin installation.
> fix(Telemetry): Do not report invalid commands

- lib/Serverless.js
- lib/utils/telemetry/cache-path.js
Closes: #9428
Additionally changed the name of the cache folder for telemetry payload. This may introduce slight friction where after upgrade some stored payload will no longer be send (as new version will look into new version).
Still I assume that loss will be negligible, and renaming of a folder is the only way to fix the issue, where old _global_ sends all cached payload on any command and _local_ fallback send same with `sls deploy`
> CLI: Fix issues related to local version fallback

- scripts/serverless.js
Old versions may not provide information on external plugins, and in such case we do not have a full picture supported commands and options.
We should avoid any validation in such case
Issue reported internally.
When latest global version falls back to older local version (one that doesn't expose `pluginManager.externalPlugins` which was introduced with https://github.com/serverless/serverless/pull/8532 and first published with v2.13.0), then we don't have information on commands and options as exposed by plugins, yet we were attempting on command validation.
With this PR we fix this issue
> CLI: Do not validate command when falling back to old version

- lib/plugins/aws/utils/parse-s3-uri.js
- test/unit/lib/plugins/aws/utils/parse-s3-uri.test.js
#9380 Added support for most S3 bucket URIs, but not ones with region in their format, e.g. any bucket outside of us-east-1.
Closes: #9403
> fix(Packaging): Fix support of the artifact S3 uri with region

- scripts/serverless.js
Fixes invalid report, as showcased in #9442 
In this scenario `self` reveals as _unrecognized_, as it targets property to be resolved with _unrecognized_ source.
I've fixed the implementation to simply filter out all recognized sources from all reported _unresolved_ sources (technically any source may resolve with variable that points _unrecognized_ source, so be subject to this error)
> CLI: Ensure to report only unrecognized sources as unrecognized

- lib/utils/telemetry/resolve-error-location.js
- test/unit/lib/utils/telemetry/resolve-error-location.test.js
It should resolve situations where the regex was not strict enough and was matching phrases as
- `from versions: none` (from Python requirements plugin)
- `unix:///var/run/docker.sock. Is the docker daemon running?.` (from Docker check) 
- `does not match the API schema.` (from webpack)
Additionally, it will not report the stacktrace lines coming from internals such as `node:child_process:573:9'` which are noise anyway.
> fix(Telemetry): Ensure telemetry only matches js stacktrace paths

- lib/plugins/aws/provider.js
> fix(AWS API Gateway): Support `Fn::Split` for `vpcEndpointIds` schema

- lib/cli/render-version.js
> fix(CLI): Correctly resolve version during local fallback

- test/fixtures/programmatic/apiGateway/serverless.yml
- test/fixtures/programmatic/checkForChanges/serverless.yml
- test/fixtures/programmatic/configSchemaExtensionsError/serverless.yml
- test/fixtures/programmatic/ecr/serverless.yml
- test/fixtures/programmatic/function/serverless.yml
- test/fixtures/programmatic/functionCloudFront/serverless.yml
- test/fixtures/programmatic/functionDestinations/serverless.yml
- test/fixtures/programmatic/functionLayers/serverless.yml
- test/fixtures/programmatic/httpApi/serverless.yml
- test/fixtures/programmatic/httpApiCatchAll/serverless.yml
- test/fixtures/programmatic/httpApiExport/serverless.yml
- test/fixtures/programmatic/invocation/serverless.yml
- test/fixtures/programmatic/layer/serverless.yml
- test/fixtures/programmatic/packageArtifact/serverless.yml
- test/fixtures/programmatic/packageArtifactInServerlessDir/serverless.yml
- test/fixtures/programmatic/packaging/serverless.yml
- test/fixtures/programmatic/plugin/serverless.yml
- test/fixtures/programmatic/requestSchema/serverless.yml
- test/unit/lib/classes/ConfigSchemaHandler/index.test.js
When working on CLI refactor, suddenly some tests started to fail for me, because of introduced deprecation logs.
This patch ensures our fixtures do not generate deprecation logs when not expected.
Complements https://github.com/serverless/serverless/pull/9416
Note: Such issues won't happen once we have https://github.com/serverless/serverless/issues/9024 addressed
> Test: Ensure no deprecations in tests

- docs/providers/google/cli-reference/create.md
- lib/plugins/create/templates/google-nodejs-typescript/.gitignore
- lib/plugins/create/templates/google-nodejs-typescript/.nvmrc
- lib/plugins/create/templates/google-nodejs-typescript/README.md
- lib/plugins/create/templates/google-nodejs-typescript/index.ts
- lib/plugins/create/templates/google-nodejs-typescript/package.json
- lib/plugins/create/templates/google-nodejs-typescript/serverless.ts
- lib/plugins/create/templates/google-nodejs-typescript/src/functions/config.ts
- lib/plugins/create/templates/google-nodejs-typescript/src/functions/eventHello/config.ts
- lib/plugins/create/templates/google-nodejs-typescript/src/functions/eventHello/handler.ts
- lib/plugins/create/templates/google-nodejs-typescript/src/functions/httpHello/config.ts
- lib/plugins/create/templates/google-nodejs-typescript/src/functions/httpHello/handler.ts
- lib/plugins/create/templates/google-nodejs-typescript/src/libs/errorHandler.ts
- lib/plugins/create/templates/google-nodejs-typescript/src/libs/logs.ts
- lib/plugins/create/templates/google-nodejs-typescript/tsconfig.json
- lib/plugins/create/templates/google-nodejs-typescript/tsconfig.paths.json
- lib/plugins/create/templates/google-nodejs-typescript/webpack.config.js
I'm currently working with Serverless framework and GCP. I use `typescript` and `serverless-google-cloudfunctions` and I suffered of the lack of examples with this stack.
I propose to add a new template based on the `aws-nodejs-typescript` with GCP specificities to provide an example for typescript users who wants to do serverless on GCP.
> feat(Templates): Add `google-nodejs-typescript` template

- lib/Serverless.js
- lib/cli/handle-error.js
Closes: #9468
It appears we had a few quite critical issues when local fallback is concerned. 
1. Errors happening with local fallback triggered infinite loop, as global handler, invoked local hander, which again was invoking same local handler and so on, so on. Due to this issue it was observed that `serverless` process hangs.
Error in logic was that, in error handler we were unconditionally falling back to local handler if `serverless` installation in question was invoked by global. Still we didn't check wether we're not already in its context. Adding that check fixed the issue
2. Fixing above, exposed an actual error that happens in local fallback case. Error was caused by incomplete command schema provided to `lib/cli/resolve-input` util, which resolves final command schema and …
> CLI: Fix local fallback handling

- CHANGELOG.md
- package.json
- test/integration/stream.test.js
Additionally I've upgraded `dotenv` to new major, as by its [changelog](https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#900-2021-05-05) the only breaking change is dropping support for Node.js v8, which we already not support with v2
Additionally improved integration test setup to workaround race condition which was likely source of last CI fail here: https://github.com/serverless/serverless/runs/2574885747?check_suite_focus=true
> Release v2.41.2

- lib/configuration/variables/sources/file.js
- test/unit/lib/configuration/variables/sources/file.test.js
- test/unit/lib/configuration/variables/sources/fixture/file-function-variable-missing-source.js
- test/unit/lib/configuration/variables/sources/fixture/file-property-function-variable-missing-source.js
Addresses variable resolution error reporting issue showcased here: https://github.com/serverless/serverless/issues/9478
When in JS function variable resolver is used and it crashes with some resolution error, it ends with unfriendly error message as:
```
Cannot resolve variable at "custom.platformConfig": Cannot resolve "platformConfig.js": Returned JS function errored with: ServerlessError: Cannot resolve variable at "custom.platformConfig": Value not found at "s3" source
```
This patch ensures it's reduced to:
```
Cannot resolve variable at "custom.platformConfig": Value not found at "s3" source
```
> Variables: Fix reporting of variable resolution errors

- lib/cli/commands-schema/no-service.js
- lib/cli/interactive-setup/service.js
- lib/utils/create-from-local-template.js
- test/unit/lib/cli/interactive-setup/service.test.js
- test/unit/lib/utils/create-from-local-template.test.js
> Support `template-path` and `name` CLI options for interactive CLI

- package.json
- test/unit/lib/cli/interactive-setup/index.test.js
Adjust interactive CLI test after changes in `dashboard-plugin`'s `5.1.0` release
> test: Adjust interactive CLI test after plugin changes

- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
- test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Updates schema to match existing implementation.
There was an existing test that already covered the apiKeys implementation which I refactored to use runServerless so that the schema is checked as well. I also added an extra test case to this for the case where neither name or value is provided, which were previously required fields in the schema (but not in the implementation).
Closes: #9080
> fix(AWS API Gateway): Fix schema for `apiKeys` and `permissionsBoundary`

- lib/utils/telemetry/generatePayload.js
- test/unit/lib/utils/telemetry/generatePayload.test.js
_Originally proposed by @mnapoli_
This should give good idea of what missing functionalities in a Framework are in demand
Currently in Framework, user can extend the generated template by defining resources in:
- `resources.Resources` - to introduce new resources, but also extensions to resources already generated by the Framework. This property is scheduled to be deprecated as it performs blind merge, and unexpected merge side effects can happen (we had reports of that)
- `resources.extensions` - dedicated and recommended property to extend resources as generated by the Framework. It guarantees no surprises and each extension property is treated invididualy.
Above is to be extended with `resource.additions` and having that `resources.Resources` will be deprecated (handled at …
> Telemetry: Report resource types as configured explicitly by user

- lib/cli/interactive-setup/service.js
- test/unit/lib/cli/interactive-setup/service.test.js
Addresses: #9367 
I've decided to NOT provide the default project name in situations where `template-url` or `template-path` is used as it requires parsing/normalization of template names and introduces additional complexity. Please let me know if you feel otherwise.
> Present default project name if possible

- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/events/sqs.test.js
Closes: #8150 
I've decided to implement the test for `sqs`, because it's not really possible to implement different test with `runServerless` for this. Other affected devents are `stream`, `msk` and `kafka`.
> Dont depend on default execution role when custom role provided with `!Sub`

- lib/plugins/aws/lib/monitorStack.js
- lib/plugins/plugin/install.js
- lib/plugins/plugin/uninstall.js
- lib/utils/tokenize-exception.js
- scripts/serverless.js
- test/unit/lib/plugins/aws/lib/monitorStack.test.js
- test/unit/lib/plugins/plugin/install.test.js
Noticed 30+ error reports in mixpanel, pointing fact it's possibe that `ResourceStatusReason` is not provided on event we mark as _error event_.
This patch ensures we do not dirty crash in such case.
Additionally:
- Added missing error codes to `ServerlessError`'s in `scripts/serverless.js`
- Remove internal `YamlParser` dependency (it introduced alternative YAML parsing approach, which was used just in `plugin install/uninstall` command
- Improve `plugin install/uninstall` commands so they're safe in user used variables to define `plugins` (so far such configuration dirty crashed)
- Remove recognition of `YAMLParser` as user error. In new configuration read logic all YAML parse errors are already communicated with `ServerlessError` and same should be in all other cases
> Fix stack errors processing

- lib/plugins/aws/invokeLocal/index.js
Noticed some programmer errors reported here. Fixed our logic to show meaningful error message instead
> Local invocation: Fix invalid result handling

- lib/plugins/aws/lib/monitorStack.js
- Improve code naming consistency (so all cloudformation service errors start with `AWS_CLOUD_FORMATION_`
- Recognize permission errors and report them with `AWS_CLOUD_FORMATION_<action>_INSUFFICIENT_PERMISSIONS`
> refactor(Telemetry): Improve AWS stack error codes

- lib/configuration/variables/sources/instance-dependent/get-cf.js
- lib/configuration/variables/sources/instance-dependent/get-s3.js
- lib/configuration/variables/sources/instance-dependent/get-ssm.js
- test/unit/lib/configuration/variables/sources/instance-dependent/get-cf.test.js
- test/unit/lib/configuration/variables/sources/instance-dependent/get-s3.test.js
- test/unit/lib/configuration/variables/sources/instance-dependent/get-ssm.test.js
Fixes a regression introduced with more granular error codes from AWS calls
Closes: https://github.com/serverless/serverless/issues/9516
> Ensure proper resolution in case of errors for AWS-related variables

- lib/cli/handle-error.js
Not all needed properties were passed during local fallback for error handler which caused crashes. 
Closes: #9512
> Ensure to pass proper config for local fallback during error reporting

- lib/Serverless.js
- lib/classes/ConfigSchemaHandler/index.js
- lib/classes/Service.js
- lib/classes/Variables.js
- lib/configuration/variables/sources/resolve-external-plugin-sources.js
- scripts/serverless.js
- test/unit/lib/classes/ConfigSchemaHandler/index.test.js
- test/unit/lib/configuration/variables/sources/resolve-external-plugin-resources.test.js
Closes: #9523
Proposed solution doesn't map 1:1 in what global does, but it's just few edge cases that are left out, and it should ensure proper variables resolution where there's properly constructed service configuration and there's a local version fallback from older global version.
Additionally:
- Hardcoded assignment of `variableSyntax` default stood in a way here, so I've refactored it a bit
- Secluded `resolveExternalPluginSources` from main script, to have it reusable for this patch
Tested locally (no automated tests unfortunately, as it's a not trivial to emulate local fallback, and this is a temporary patch that will move away with v3)
> Variables: Ensure resolution with new resolver in a local fallback

- lib/aws/request.js
- test/unit/lib/aws/request.test.js
> Fix handling of numeric error codes coming from AWS SDK requests

- docs/guides/providers.md
Adds new documentation to the providers guide for the dashboard. The docs are for advanced IAM and Dashboard users to setup a custom IAM Role/Policy with providers.
> docs: Add details on using a custom policy/role

- lib/templates/recommended-list/index.js
https://github.com/serverless/serverless/pull/9445 adds `google-nodejs-typescript` template but it can't be used because it is not in the `recommended-list`. 
This PR allow the usage of the template by adding its name in the `recommended-list`.
> fix(Templates): Allow usage of `google-nodejs-typescript` template

- lib/cli/resolve-input.js
> chore: Fix typo in `resolve-input.js`

- lib/plugins/aws/package/compile/events/apiGateway/lib/stage.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.test.js
The issue in corresponding ticket was happening due to the fact that the `LogGroup` for API Gateway was referenced, while it was being removed via SDK calls due to disabled access logging. It resulted in CloudFormation resource existing, but actual LogGroup was missing. That change ensures that we're not creating LogGroup in CF if it's not needed.
Closes: https://github.com/serverless/serverless/issues/9552
> fix(AWS API Gateway): Dont create logGroup if logs disabled

- docs/providers/aws/guide/variables.md
> docs: Fix typo in `variables.md`

- lib/utils/telemetry/anonymize-stacktrace-paths.js
- test/unit/lib/utils/telemetry/anonymize-stacktrace-paths.test.js
- test/unit/lib/utils/telemetry/resolve-error-location.test.js
It appears that in mixpanel there's a constraint of maximum 255 characters length for any string value.
In result some of our generated error location paths are stored partially, and we miss some valuable information.
This patch introduces two optimizations:
1. Truncate `/node_modules/` path prefix to `/`
2. If given file path is repeated, in following path it's replaced by `^` character
> Telemetry: Optimise error location paths

- lib/classes/ConfigSchemaHandler/normalizeAjvErrors.js
- test/unit/lib/classes/ConfigSchemaHandler/normalizeAjvErrors.test.js
When two different variants for string value are provided, and value doesn't match, we show message:
```
at 'xxx.xxx': unsupported configuration format
```
Which is vague, as it indicates that we may ve off largely (e.g. value of string type is not expected at all)
This patch improves the messaging to
```
at 'xxx.xxx': unsupported string format
```
Which gives better idea, as it should indicate that we support _string_ here, but not at provided format
> Config Schema: Improve error messaging for same type variants

- lib/Serverless.js
- lib/classes/Service.js
- lib/plugins/print.js
- scripts/serverless.js
Closes: #9589 
Issue happened when top level property was configured behind variable, and used variable sources where provided by plugins, so variable resolution happened after _initialization_ phase.
It was due fact that, at _initialization_ phase in [`Service`](https://github.com/serverless/serverless/blob/8ac249b1eadf3173359e02886e71bb89234ebd51/lib/classes/Service.js#L114-L164) class we copy those properties onto `service` class instance, and in all internal logic they're accessed from there.
This was ok, for objects where deeper properties were behind variables (as objects are passed by reference, without creating a new copy), but didn't work if at first stage property was _string_ and after it was resolved into _object_ (and that's the case reported in #9242)
I've cleaned up …
> Variables: Fix top level properties resolution handling

- lib/configuration/variables/sources/file.js
- lib/configuration/variables/sources/instance-dependent/get-ssm.js
- test/unit/lib/configuration/variables/sources/instance-dependent/get-ssm.test.js
Closes: #9597
Additionally I've improved error message related to `projectDir`
> Variables: Strip unrecognized legacy SSM instructions

- docs/guides/cicd/custom-scripts.md
People copy pasting the config for hooks will copy invalid quotation marks and spend a while debugging it.
It doesn't close an issue.
> docs: Fix quotation marks on serverless hooks

- lib/utils/telemetry/generatePayload.js
- test/unit/lib/utils/telemetry/generatePayload.test.js
Reported internally, recognize `constructs` from `serverless-lift` plugin
> refactor(Telemetry): Recognize `constructs`

- docs/configuration-validation.md
- lib/classes/ConfigSchemaHandler/index.js
Improve communication of configuration schema errors.
> Config Schema: Improve error message and documentation

- lib/Serverless.js
- lib/utils/isStandaloneExecutable.js
- In case of a fallback from some versions (e.g. 2.18.0) on `sls -v` fallback is done directly to `Serverless` instance (in latest we directly fallback to version resolver if provided in a fallback version), and with latest versions it generated the _help_ output and not _version_ output. Addressed by ensuring to render version if `version` option is detected
- Standalone detection was broken for cases, when from standalone global we fallen back to installed locally version.
Detection was based on shape of `process` object, as in this case we're in context of `node` process as provided by _standalone_, detection suggested we're using standalone install (while it's only Node.js that's used from standalone package, and it's Framework installed locally that's executed)
> CLI: Fix issues related to version reporting with a local fallback

- lib/plugins/aws/customResources/generateZip.js
- lib/plugins/aws/customResources/index.js
- lib/utils/fs/safeMoveFile.js
- test/unit/lib/plugins/aws/customResources/generateZip.test.js
- test/unit/lib/utils/fs/safeMoveFile.test.js
- Previously there was a race condition in ensureArtifact where if you were running multiple 'sls package' in parallel, two or more instances of serverless could notice that the custom resources package was missing and try and create it
- This meant that one of the serverless instances would 'win' the race and create it first. Then the other instances would crash because the file already existed
- Now each project gets its own cache folder and they can't conflict with each other, even if they are packaging in parallel
- Also implemented a safe move function that allows files to be renamed across filesystem boundaries
Closes: #9565
> fix: prevent crash when packaging in parallel

- lib/utils/isStandaloneExecutable.js
Complementary fix to https://github.com/serverless/serverless/pull/9641
> CLI: Fix standalone detection on Windows

- docs/providers/aws/guide/serverless.yml.md
The header behaviour should be `HeaderBehaviour` an extra `s` is currently within the documentation
> Fix documentation for CloudFront cache behaviour

- docs/providers/aws/guide/functions.md
_This is purely a documentation rephrasing and does not have a preexisting issue associated._
When the previous paragraph mentions turning off versioning it becomes unclear what "these versions" refers to. Placing the paragraph earlier makes its relation with the default behavior less ambiguous.
I'm genuinely not sure that the "versions are not cleaned up" behavior relates to the default setting or if it actually relates to the `versionFunctions: false` setting - feel free to close this PR if I've misunderstood.
> docs: Improve `versionFunctions` description

- docs/deprecations.md
- lib/cli/commands-schema/aws-service.js
- lib/plugins/deploy.js
> refactor(AWS Deploy): Deprecate `function` option in `deploy` command

- lib/configuration/variables/parse.js
- lib/configuration/variables/resolve.js
- lib/configuration/variables/sources/file.js
- test/unit/lib/configuration/variables/parse.test.js
- test/unit/lib/configuration/variables/resolve.test.js
- test/unit/lib/configuration/variables/sources/file.test.js
- test/unit/lib/configuration/variables/sources/fixture/file-variables-nest-1.yaml
- test/unit/lib/configuration/variables/sources/fixture/file-variables-nest-2.yaml
- test/unit/lib/configuration/variables/sources/fixture/file-variables-nest-3.yaml
When investigating https://github.com/serverless/serverless/issues/9619 I've discovered a two limitations in variables resolver, which felt as nice to have addressed.
- Support variables resolution in string parts that come from different sources, and which are to be concatenated into one value. More info at https://github.com/serverless/serverless/issues/9619#issuecomment-864921557
- Support on the go resolution of values retrieved from files when resolving the `address`
Additionally cleared one redundancy discovered in configured logic
Closes: #9619
> Variables: Improve some resolution scenarios

- lib/cli/interactive-setup/deploy.js
> Only call `handleError` if `interactiveOutputPlugin` plugin defined

- test/fixtures/programmatic/curated-plugins/_setup.js
- test/fixtures/programmatic/curated-plugins/index.js
- test/fixtures/programmatic/curated-plugins/package.json
- test/fixtures/programmatic/curated-plugins/serverless.yml
- test/integration/curated-plugins.test.js
In this PR just test for `serverless-offline` is introduced.
To ensure tests are robust ideally if (as many as possible) plugins are tested in context of same service.
Addresses #9025 
@mnapoli having that in, you may add test that covers `serverless-lift`
> Test: Integration tests for popular plugins

- lib/plugins/aws/invokeLocal/index.js
Addressing error spotted in our telemetry reports
> AWS Local Invocation: Fix error handling of invalid file content

- lib/plugins/aws/deploy/lib/uploadArtifacts.js
Addressing error spotted in our telemetry reports.
I assume it happens when someone configures wrong `package.artifact` path
> AWS Deploy: Report meaningfully inaccessible file artifacts

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
Reported internally.
Addresses the following:
- Add `node16` to testing matrix
- Move running isolated tests to `node16`
- Move running coverage with `node12` tests
- `node10` tests do not run anything "extra" - they will be removed soon
> ci: Add `node16` to testing matrix

- lib/cli/handle-error.js
- lib/cli/interactive-setup/index.js
- lib/utils/tokenize-exception.js
- test/unit/lib/cli/interactive-setup/index.test.js
- test/unit/lib/utils/tokenize-exception.test.js
Reported internally, report `commandUsage` to better understand what might've caused an error during interactive flow
> refactor(Telemetry): Include `commandUsage` in case of error

- lib/classes/ConfigSchemaHandler/index.js
- lib/utils/telemetry/generatePayload.js
- lib/utils/telemetry/resolve-error-location.js
- test/unit/lib/classes/ConfigSchemaHandler/index.test.js
- test/unit/lib/utils/telemetry/generatePayload.test.js
- test/unit/lib/utils/telemetry/resolve-error-location.test.js
In some errors, 5 lines limit appers as not good enough (requires a more demanding investigation) to well coin the source of the issue, e.g.
```
fs.js:474:3
^:375:35
/serverless/lib/utils/fs/readFileSync.js:7:24
/serverless/lib/classes/Utils.js:78:12
/serverless/lib/classes/YamlParser.js:12:40
```
I think it's not harmful to increase it to 7
Additionally:
- Optimize tests to not rely on `runServerless` when it's not justified
- Add `config.configValidationMode` and  `isConfigValid` to generated report (as it's important for programmer errors filtering)
> Telemetry: Increase error location coverage

- lib/cli/interactive-setup/aws-credentials.js
- test/unit/lib/cli/interactive-setup/aws-credentials.test.js
Reported internally - properly recognize situation where we're not in service directory
> fix(Telemetry): Properly handle not in service dir in credentials

- lib/utils/eventuallyUpdate.js
> refactor: Replace `fse.createWriteStream` with `fs.createWriteStream`

- .github/workflows/integrate.yml
- test/fixtures/programmatic/curated-plugins-python/_setup.js
- test/fixtures/programmatic/curated-plugins-python/handler.py
- test/fixtures/programmatic/curated-plugins-python/package.json
- test/fixtures/programmatic/curated-plugins-python/requirements.txt
- test/fixtures/programmatic/curated-plugins-python/serverless.yml
- test/integration/curated-plugins-python.test.js
Addresses: #9025
I've tweaked actions setup for one run, to confirm whether this test which involves Python will work without additional setuyp, and it appers it's the case: https://github.com/serverless/serverless/pull/9679/checks?check_run_id=2971192964
> Test: Cover `serverless-plugin-requirements` plugin

- lib/cli/commands-schema/aws-service.js
This option wasn't documented as `info` command option, while internally is supported: https://github.com/serverless/serverless/blob/cc24bc2ae280237b3d439e1934ab75710e0f259f/lib/plugins/aws/info/display.js#L148
Closes: #9691
> CLI: Recognize `--verbose` option in `info` command

- docs/deprecations.md
- docs/providers/aws/guide/serverless.yml.md
- lib/Serverless.js
- lib/cli/handle-error.js
- lib/configSchema.js
- lib/utils/logDeprecation.js
- scripts/serverless.js
- test/unit/lib/utils/logDeprecation.test.js
_(proposed internally by @skierkowski)_
So far deprecation warning logs are reported on the go, which may result with not great UX experience (especially if at least few are logged).
This improvement changes the approach, so all approached deprecations are logged in single summary block after command finalizes. This improves deprecations visibility, and reduces log clutter when ongoing process logs are concerned.
New logging way was introduced as third `warn:summary` deprecations logging mode, which was also set as default.
To avoid compatibility issues with other Framework versions, in case when local fallback occurs, mode is switched to `warn`, and local version is also ensured to log deprecations with `warn` mode (so one that was default so far).
This will be improved in v3, which will …
> New deprecations logging mode

- lib/Serverless.js
- lib/classes/PluginManager.js
- lib/cli/handle-error.js
- lib/cli/render-version.js
- lib/cli/resolve-local-serverless-path.js
- lib/plugins/config.js
- lib/utils/eventuallyUpdate.js
- lib/utils/is-locally-installed.js
- lib/utils/npmPackage/isGlobal.js
- lib/utils/telemetry/generatePayload.js
- lib/utils/telemetry/index.js
- scripts/postinstall.js
- scripts/serverless.js
- test/unit/lib/cli/handle-error.test.js
- test/unit/lib/cli/resolve-local-serverless-path.test.js
- test/unit/lib/plugins/aws/provider.test.js
- test/unit/lib/utils/telemetry/generatePayload.test.js
- test/unit/lib/utils/telemetry/index.test.js
Discussed internally, the reason behind this change is to ensure that both `storeLocally` and `generatePayload` utils are sync, which makes them safe to be executed as a part of `process.on` handler without interfering with asynchronously running operations in the backgorund.
Related to: https://github.com/serverless/serverless/issues/9367
> Ensure generation and related utils are sync

- lib/classes/Variables.js
- lib/configuration/variables/eventually-report-resolution-errors.js
- scripts/serverless.js
- test/unit/lib/classes/Variables.test.js
Old variables engine will be removed with next major, so there's no point to communicate breaking changes that were supposed to introduced if it was to stay
> Variables: Drop old engine related deprecation

- lib/cli/interactive-setup/index.js
Reported internally. Ensure that we will have `stepsDetails` for each step, even if process errors out before we even consider such step with `isApplicable` check. 
Related to: https://github.com/serverless/serverless/issues/9367
> Ensure to pass all steps with configured questions

- scripts/serverless.js
Due to `inquirer` limitations, addtional mechanism for keeping the process alive had to be implemented. 
Addresses: https://github.com/serverless/serverless/issues/9367
Before merging this PR, corresponding backend PR has to be finalized
> feat(Telemetry): Handle interruptions and persist telemetry data

- lib/utils/telemetry/generatePayload.js
- package.json
- scripts/serverless.js
- test/unit/lib/utils/telemetry/generatePayload.test.js
- Fix handling of `SIGINT` signal (it prevented other attached listeners from working, that was also the source of the CI fails, as: https://github.com/serverless/serverless/runs/3000015103?check_suite_focus=true). This fix ensures that we do not block other listeners, and if there's none set, we pass through the signal (so process exits with `130` code, as it was before this listener was introduced)
- Report all interruption signals (to folllow that was also outlined in spec at #9367 still it was somehow missed), and report with telemetry which signal we faced
- Report whether we're in context of TTY terminal (that'll further help detect human users)
> Telemetry improvements and fixes

- lib/plugins/package/lib/packageService.js
Observed in telemetry programmer errors that relate to fact that invalid paths are configured at `package.artifact`.
Framework so far had no dedicated validation for those paths. This PR fixes that
> Packaging: Validate `package.artifact` paths

- docs/providers/aws/guide/variables.md
Documentation fix.
aws should be at provider.name level
> docs: Adjust `${aws::accountId}` reference example 

- docs/providers/aws/guide/iam.md
I think I noticed some mistakes in the IAM documentation (`,` at the end of some lines, which AFAICT is incorrect in YAML).
> docs(AWS IAM): Fix invalid example

- lib/aws/has-local-credentials.js
- lib/cli/interactive-setup/index.js
- lib/cli/interactive-setup/utils.js
- test/unit/lib/aws/has-local-credentials.test.js
- test/unit/lib/cli/interactive-setup/utils.test.js
> Record preliminary context for Interactive Setup

- package.json
Feels as safe upgrade
[Changelog](https://github.com/avoidwork/filesize.js/blob/master/CHANGELOG.md#700-1) mentions [ESM introduction](https://github.com/avoidwork/filesize.js/commit/4c4363ac7481c8fa6f036d85f9f898d146216bb9) as reason for major bump, but that doesn't look as breaking change (reported that at https://github.com/avoidwork/filesize.js/issues/135)
> Upgrade `filesize` to v7

- docs/environment-variables.md
- lib/cli/load-dotenv.js
- package.json
- test/unit/lib/Serverless.test.js
> feat(CLI): Automatically expand loaded env variables

- lib/configuration/variables/sources/instance-dependent/get-ssm.js
- test/unit/lib/configuration/variables/sources/instance-dependent/get-ssm.test.js
Closes: https://github.com/serverless/serverless/issues/9742
> Variables: In `ssm` source auto parse only object JSON notation

- docs/deprecations.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/index.js
- lib/plugins/aws/package/lib/addExportNameForOutputs.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/lib/addExportNameForOutputs.test.js
> Allow to disable default export names

- lib/classes/Service.js
- test/unit/lib/classes/Service.test.js
Exposed in integration test fail https://github.com/serverless/serverless/runs/3084121219?check_suite_focus=true
Where given function is removed by overriding it with `null`. Such setup should work without issues
> Fix `functions[]` validation (ignore `null` values)

- test/fixtures/programmatic/curated-plugins/package.json
- test/integration/curated-plugins.test.js
Part of #9025 initiative
This is last plugin with over 1k users, and i will stop here.
I've also proposed a variable resolution related fix to a plugin repo: https://github.com/serverless-operations/serverless-step-functions/pull/451
> Test: Cover `serverless-step-functions` plugin

- lib/cli/interactive-setup/deploy.js
- test/unit/lib/cli/interactive-setup/deploy.test.js
Reported internally, do not rely on previously executed steps based on history but always resolve/ensure credentials existence.
> fix(CLI Onboarding): Ensure credentials resolution before deploy

- docs/getting-started.md
Fixed a few typo + made the `serverless` onboarding command less intimidating by setting user expectations (i.e. explaining what the command will do).
> docs: Improve the Getting started guide

- lib/cli/interactive-setup/dashboard-login.js
- lib/cli/interactive-setup/dashboard-set-org.js
- lib/cli/interactive-setup/index.js
- lib/cli/interactive-setup/utils.js
- package.json
- test/fixtures/programmatic/aws-loggedin-monitored-service/.serverlessrc
- test/fixtures/programmatic/aws-loggedin-monitored-service/serverless.yml
- test/fixtures/programmatic/aws-loggedin-noapp-service/.serverlessrc
- test/fixtures/programmatic/aws-loggedin-noapp-service/serverless.yml
- test/fixtures/programmatic/aws-loggedin-service/.serverlessrc
- test/fixtures/programmatic/aws-loggedin-service/serverless.yml
- test/fixtures/programmatic/aws-loggedin-wrongapp-service/.serverlessrc
- test/fixtures/programmatic/aws-loggedin-wrongapp-service/serverless.yml
- test/fixtures/programmatic/aws-loggedin-wrongorg-service/.serverlessrc
- test/fixtures/programmatic/aws-loggedin-wrongorg-service/serverless.yml
- test/unit/lib/cli/interactive-setup/dashboard-login.test.js
- test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
Discussed internally, it moves logic from `dashboard-plugin` that is related to CLI Onboarding flow in order to avoid issues with compatibility between different versions of Framework and Plugin. It will be followed up with a minor PR that marks logic in the plugin that it should be cleaned up with the next major. 
Related to: #9367
> refactor(CLI Onboarding): Move `dashboard-login` step from plugin

- docs/guides/sdk/nodejs.md
Just seemed a bit confusing to have 'an' precede sync, made me look twice to see which case was truly sync versus async
There is a section of the node.js sdk guide where 'an' precedes both async and sync, should have just an 'a' preceding sync function, not 'an' as it implies async is following word due to it starting with a vowel, made me look a couple times
> docs: Adjust spelling in Node SDK guide

- lib/cli/interactive-setup/aws-credentials.js
- lib/cli/interactive-setup/dashboard-login.js
- lib/cli/interactive-setup/dashboard-set-org.js
- lib/cli/interactive-setup/deploy.js
- lib/cli/interactive-setup/service.js
- package.json
- test/unit/lib/cli/interactive-setup/aws-credentials.test.js
- test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
- test/unit/lib/cli/interactive-setup/service.test.js
Use `promptWithHistory` that will automatically record questions in step history. There is one exception where we still use `inquirer.prompt` directly, but it was easier to make an exception here in my opinion as we have to access original prompt from inquirer than to change the implementation just for this case. 
Before merging this PR, corresponding backend PRs have to be merged and deployed.
Addresses: #9367
> refactor(Telemetry): Use `prompt-with-history`

- docs/providers/aws/examples/hello-world/python/README.md
python2 is [no longer a supported runtime](https://aws.amazon.com/blogs/compute/announcing-end-of-support-for-python-2-7-in-aws-lambda/) for AWS.
When I ran this example as it currently is in the docs it created a python2 project. Interestingly selecting `AWS - Python - Starter` from the CLI did create a python3 project, although the code seems to suggest this should be calling the `aws-python` template, but I probably missed a link there.
> docs: Suggest `python3` template over `python2`

- lib/utils/telemetry/index.js
- scripts/pkg/upload/world.js
- test/unit/lib/utils/telemetry/index.test.js
> refactor: Replace `fse.readdir` with `fs.promises.readdir`

- docs/providers/aws/guide/variables.md
- lib/configuration/variables/sources/str-to-bool.js
- test/unit/lib/configuration/variables/sources/str-to-bool.test.js
This change simply adds toLowerCase() when assigning stringValue to allow enable a case-insensitive input (True, TRUE, False, False)
Q1: No link.. no traction in slack either when attempting to discuss this.
> feat(Variables): Accept case-insensitive strings in `strToBool`

- lib/classes/PluginManager.js
When new Serverless Framework users deploy for the very first time, 6.3% of them will face a "Plugin not found" error:
We should aim to fix the issue upstream. But in the meantime, a simple way to improve the experience is to make the error message more actionable:
> fix(Plugins): Improve error message when a plugin is missing

- lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.js
- test/fixtures/programmatic/requestParameters/serverless.yml
- test/fixtures/programmatic/requestParameters/target.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/index.test.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.test.js
Closes: #5034 
This is a simple bugfix/PR that sets the `RequestValidatorId` when the `function.request.parameters` configuration option is present.
> fix(AWS API Gateway): Ensure to attach validator when required

- lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
No linked issue for this one - only noticed this when trying to implement the property myself.
Change overview:
- `minimumCompressionSize` is allowed to be set to 0, however, due to the conditional statement any `0` values will not be added to the properties at deployment time
- Commit fixes the above issue and adds a test to ensure the fix
> fix(AWS API Gateway): Ensure `MinimumCompressionSize` can be 0

- docs/deprecations.md
- lib/plugins/aws/package/compile/events/apiGateway/index.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test.js
Addresses: #9458 
Addresses first part of linked issue by introducing deprecation. The breaking change should be introduced with next major release.
> refactor(AWS API Gateway): Deprecate default `identitySource`

- docs/deprecations.md
- lib/Serverless.js
- scripts/serverless.js
> refactor(CLI): Deprecate `-v` as alias for `--verbose`

- docs/deprecations.md
- lib/plugins/aws/package/compile/events/apiGateway/index.js
- test/fixtures/programmatic/apiGatewayExtended/serverless.yml
Related to: https://github.com/serverless/serverless/issues/9458
After investigating further the issue with failing integration test related to changes from original PR, I've discovered that my initial understanding was wrong and the deprecation should only apply to narrower scope (authorizers with `request` type and with caching disabled). It will change the planned approach a little bit and keep the configuration approaches a bit different for `http` and `httpApi` authorizers. Please let me know what do you think @medikoo
> refactor(AWS API Gateway): Adjust deprecation for `identitySource`

- commitlint.config.js
- lib/plugins/aws/package/compile/functions.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
Closes: #9797 
This fix will not error out if layer referenced by `Ref` will not be found locally, but rather allow such behavior and let the deployment fail is the layer really cannot be referenced.
> fix(AWS Layers): Support references to external layers

- lib/plugins/deploy.js
Just saw in reports, that this depredation is reported with `EXT_` prefix, as it uses our public function (dedicated for plugin usage) and not internal.
Downside was that there was no link to documentation presented. 
> Ensure right deprecation code for `deploy -f` deprecation

- docs/providers/aws/cli-reference/generate-event.md
- docs/providers/aws/cli-reference/print.md
- docs/providers/aws/cli-reference/slstats.md
Closes: #9823
I put it low in the menu, just before the `print` command page. I see the pages order is not strictly alphabetical, but rather the commands are put in some logical order. If you think this should be at any other position, let me know, I will change it.
> docs: Add `generate-event` CLI command description

- lib/cli/interactive-setup/deploy.js
- lib/cli/interactive-setup/index.js
- test/unit/lib/cli/interactive-setup/deploy.test.js
Closes: https://github.com/serverless/serverless/issues/9822
That's how it's going to look like after changes:
> refactor(CLI Onboarding): Adjust summary messages in deploy step

- docs/guides/dashboard.md
Free tier invocations value was still at old value and not the new one.
NA
NA
It is
NA
NA
Documentation update related to the number of free invocations provided under the free tier was incorrect.
> Updated free tier invocations value

- lib/plugins/aws/package/compile/events/httpApi.js
- test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js
> fix(AWS HTTP API): Properly handle authorizer function with alias

- lib/plugins/aws/provider.js
In response to: https://aws.amazon.com/about-aws/whats-new/2021/08/aws-lambda-adds-support-python-3-9/
I've tested locally that deployments with new runtime work without issues
> feat(AWS Lambda): Recognize `python3.9` as valid runtime

- docs/providers/aws/events/http-api.md
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/lib/naming.test.js
**Overview**:  
- Add a option on HTTP API to set the api gateway name starting with the service name.
- Based on Rest API implementation.
- Add unit tests on HTTP API naming function
Closes: [#9631](https://github.com/serverless/serverless/issues/9631)
> feat(AWS HTTP API): Support `shouldStartNameWithService` option

- lib/plugins/aws/package/compile/events/httpApi.js
- test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js
Closes: #9840
---
Removes couple checks to allows for configs such as the following:
```yaml
functions:
handler:
handler: handler.handler
events:
- httpApi: OPTIONS /a
- httpApi: ANY /a
```
That is, catch-all's that shadow other routes with same paths are allowed.
> fix(AWS HTTP API): Always allow to define catch-all route (#9840) 

- test/unit/lib/plugins/aws/provider.test.js
I've noticed that we have failing tests on `master` and I was able to reproduce it locally with `2.973.0` version of `aws-sdk`. With that release, the internals of `aws-sdk` has changed which caused one of our tests to fail as the mock of `aws-sdk` caused the logic that attaches `AWS.util.loadConfig` to not be executed.
> test: Ensure proper `aws-sdk` patch in `provider` tests

- lib/cli/commands-schema/no-service.js
Mark `dashboard` command with optional service dependency mode. It is needed for internal initiative that aims to improve `serverless dashboard` command behavior. Rest of implementation will be submitted as separate PR in `dashboard-plugin` repository.
> fix(CLI): Mark `dashboard` command with optional service dependency

- lib/plugins/aws/deploy/lib/checkForChanges.js
- test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
Closes: #8276, #9528
1. If external defined subscription filter cause `subscription filter per log group limit` exceed, throw error
2. Delete all not-matched(having same logical id & destination arn) subscription filter defined internally.
Previously, serverless try to delete only if limit exceed. (ex. if there is only 1 not matched subscription filter, the deletion is processed at CloudFormation, not in serverless) => the removal enforcer changed from CF to serverless
Change num#2 was applied to make code simple. If it seems awkward, it can be revert as the previous way (delete only if limit exceed)
> feat(AWS Lambda): Prevent external subscription filter removal

- lib/plugins/aws/package/compile/events/apiGateway/index.js
Closes: #9885 
@medikoo As for your last comment, I don't think there's a problem as the only issue there was with `mappedValue` property and `required` property still has to be provided, so I don't think we have any issue there.
> Address shortcomings in AWS API Gateway validation schema

- lib/configuration/variables/sources/env.js
- scripts/serverless.js
- test/unit/scripts/serverless.test.js
Closes: https://github.com/serverless/serverless/issues/9880
Implemented solution:
1. Treat _env_ source as _fulfilled_ specifically for `provider.stage` and `useDotenv` resolution.
2. Gather information of missing environment variables which otherwise will influence resolution of those properties
3. After eventual `.env` file is loaded, confirm that no environment variables from above group where loaded from `.env` files. If that's the case throw meaningful error.
> CLI: Enable `env` variables in `provider.stage` property

- package.json
- test/unit/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
- test/unit/lib/plugins/aws/deployFunction.test.js
Per [CHANGELOG](https://github.com/avoidwork/filesize.js/blob/master/CHANGELOG.md) no breaking changes that affect us.
Still it appears that there were some fixes which required an update to our tests.
Default setting in v7 and v8 was to show 2 decimals after `.`, still in v7 it seemed not consistent, where v8 is listing `1.02 kB`, the v7 was listing `1 KB`.
I think it's good to adapt to consistency of v8, therefore I've adjusted our tests.
_This util is strictly used to show filesize in our user directed logs, and any formatting changes there are not breaking in any way_
> Upgrade `filesize` to v8

- lib/plugins/create/templates/tencent-go/index.go
Fixed unnecessary use of `fmt.Sprintf()` in [`lib/plugins/create/templates/tencent-go`](https://github.com/serverless/serverless/blob/b751c505c8050e229edb77d44016925c4e52a05e/lib/plugins/create/templates/tencent-go/index.go#L17).
This is a very small fix, but it bothered me.
> refactor(Templates): Remove unnecessary `fmt.Sprintf` in `tencent-go`

- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
Related to: https://github.com/serverless/serverless/pull/8852#issuecomment-909439919
I've updated the setting for `environment` only as updating it universally is unfortunately a bit more time-consuming as we need to review each case separately as some of them try to extract info from CF intrinsic functions.
> fix(AWS Lambda): Recognize `Fn::If` function for `environment`

- lib/plugins/aws/package/compile/events/cloudFront.js
Closes: #9595
This PR is built on top of https://github.com/serverless/serverless/pull/9598 addressing https://github.com/serverless/serverless/pull/9598#issuecomment-874777145 also:
> In addition - is it possible to reference these groups e.g. with CF intrinsic functions such as Ref, etc? If yes, we should also allow schema to accept them.
I found [one example](https://github.com/awslabs/amplify-video/issues/249#issuecomment-831432822) were `Ref` is used when defining a trusted key group. But I doubt it _has_ to be a ref since the example resource in the initial issue (see it's `serverless.yrml`) uses a value like `abcdef ` which is obviously not using `Ref`. So I think we should not add intrinsic function constraint to that piece of schema.
> fix(AWS CloudFront): Recognize `behavior.TrustedKeyGroups` in schema

- docs/providers/google/cli-reference/invoke-local.md
- docs/providers/google/cli-reference/login.md
- docs/providers/google/cli-reference/logs.md
- docs/providers/google/cli-reference/plugin-install.md
- docs/providers/google/cli-reference/plugin-list.md
- docs/providers/google/cli-reference/plugin-search.md
- docs/providers/google/cli-reference/plugin-uninstall.md
- docs/providers/google/cli-reference/print.md
Documentation of the invoke local feature of [serverless-google-cloudfunctions](https://github.com/serverless/serverless-google-cloudfunctions) implemented in https://github.com/serverless/serverless-google-cloudfunctions/pull/258 and https://github.com/serverless/serverless-google-cloudfunctions/pull/264 released in https://github.com/serverless/serverless-google-cloudfunctions/releases/tag/v4.2.0
> docs: Add `invoke local` doc for `google` provider

- docs/providers/aws/events/schedule.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/schedule.js
- test/fixtures/programmatic/schedule/core.js
- test/fixtures/programmatic/schedule/serverless.yml
- test/integration/aws/schedule.test.js
- test/unit/lib/plugins/aws/package/compile/events/schedule.test.js
Closes: #9867
This PR adds a feature to allow multiple cron/rate expressions to be specified in a `schedule` event. When doing so, multiple CloudWatch Event  rules are created, sharing the same values for the other attributes (e.g. `input`, `enabled`, etc).
> feat(AWS Schedule): Allow multiple rate expressions in single event

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
Closes: #9137 
Replaces work started in: https://github.com/serverless/serverless/pull/9137/files
> feat(AWS API Gateway): Support `enabled` for `apiKeys` config

- lib/classes/PluginManager.js
Allows to attach command wide catch handler, which otherwise is challenging to construct due to lifecycle engine design
Needed for #9860 (in context of #9934)
> Support `error` hook to be triggered on command error

- lib/plugins/aws/deploy/lib/validateTemplate.js
This makes sure that the specific `naming` instance really is the "source of truth".
> refactor: Use `getCompiledTemplateS3Suffix` from `provider.naming`

- docs/providers/aws/events/apigateway.md
- docs/providers/aws/events/http-api.md
API Gateway's REST APIs and HTTP APIs are confusing.
As we move towards HTTP APIs by default, we want to clarify the differences between the two.
> docs: Clarify the differences between API Gateway versions

- lib/plugins/aws/info/getApiKeyValues.js
- test/unit/lib/plugins/aws/info/getApiKeyValues.test.js
> refactor: Replace `_.pick` with native property assignment

- lib/classes/PluginManager.js
- lib/plugins/aws/invokeLocal/index.js
> refactor: Replace `_.flatMap` usage

- lib/plugins/create/templates/aws-nodejs-typescript/package.json
- lib/plugins/create/templates/aws-nodejs-typescript/serverless.ts
- lib/plugins/create/templates/aws-nodejs-typescript/src/functions/hello/handler.ts
This PR add automatic source maps in errors stacktrace.
The line `import 'source-map-support/register';` will no longer be needed in a handler.
Exemple stack trace with source maps:
> feat(Templates): Add  automatic source maps stacktrace to `aws-nodejs-typescript`

- docs/getting-started.md
- docs/guides/cicd/best-practices.md
- docs/guides/cicd/custom-scripts.md
- docs/guides/cicd/faq.md
- docs/guides/cicd/notifications.md
- docs/guides/cicd/preview-deployments.md
- docs/guides/monitoring/README.md
- docs/guides/safeguards.md
Update docs to remove references to "Serverless Framework Pro" and "Serverless Framework Enterprise"
> docs: Remove Pro and Enterprise references

- lib/Serverless.js
- lib/aws/request.js
- lib/classes/PluginManager.js
- lib/classes/Service.js
- lib/cli/handle-error.js
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/deploy/lib/checkForChanges.js
- lib/plugins/aws/info/display.js
- lib/plugins/aws/info/index.js
- lib/plugins/aws/lib/monitorStack.js
- lib/plugins/aws/package/index.js
- package.json
- test/unit/lib/aws/request.test.js
- test/unit/lib/classes/PluginManager.test.js
- test/unit/lib/plugins/aws/package/compile/events/schedule.test.js
- test/unit/lib/plugins/aws/provider.test.js
Addresses #9860
Some verbose logs are triggered via `--verbose` but some (mostly command agnostic, as not all commands support `--verbose` flag) are triggered via `SLS_DEBUG=*`
This PR converts all remaining those which were exposed with `SLS_DEBUG=*` flag. Some of those logs qualify as indeed _debug_ logs and those were propagated to _debug_ log level (in future to be displayed with `--debug` flag)
Additionally:
- Fixed issue, where `package` command summary was displayed after `deploy` command
- Fixed timing of final status log messages. Now they're guaranteed to be displayed at the end of command processing
- Fix CF stack updates progress bar messaging (due to internal destructive operations triggered only in verbose mode, these messaging was different in verbose mode, and that was not …
> CLI: Refactor to modern interface remaining verbose logs that affect deploy operation

- lib/classes/PluginManager.js
- lib/cli/commands-schema/aws-service.js
- lib/cli/commands-schema/service.js
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/lib/updateStack.js
- lib/plugins/package/lib/packageService.js
- package.json
- test/unit/lib/classes/PluginManager.test.js
Addresses #9860 
To this point main progress titles were configured within internal logic, which shared some issues:
- It was hard to deduct what exactly progress steps are configured for given command
- Was susceptible to gaps, as plugins could inject with some _before_ or _after_ hooks into logic points then attributed to not right progress steps
With this change, main progress steps are configured directly on command schema by referencing lifecycle engine events which mark the start of a given step.
> CLI: Generalize handling of main progress points

- docs/providers/aws/events/streams.md
- lib/plugins/aws/package/compile/events/stream.js
- test/unit/lib/plugins/aws/package/compile/events/stream.test.js
> Support `tumblingWindowInSeconds` for streaming events

- lib/plugins/aws/package/compile/events/s3/configSchema.js
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html
Closes: #9983
> Add "BucketKeyEnabled" to S3 schema

- scripts/serverless.js
Just observed locally, that in such case no AWS specific commands were listed
> CLI: Fix general help output when in context of AWS service

- docs/providers/aliyun/guide/events.md
It [appears](https://github.com/aliyun/serverless-aliyun-function-compute/blob/3bdb19bc8d2fccdbcd5f668abd90f1735f8c7ac7/package/lib/compileFunctions.js#L97-L106) the plugin only supports OSS & HTTP for now.
> Docs: Alibaba Cloud - fixed available events

- lib/cli/commands-schema/resolve-final.js
Instead, signal lack of schema with a warning
> CLI: Remove missing CLI options schema deprecation

- lib/cli/conditionally-load-dotenv.js
Internally we decided to not pursue `.env` loading unconditionally as  we were worried to break for users which already use .env files to configure the environment for lambdas, where the same root folder is shared by both service configuration and lambda logic.
This PR is purely about removing the deprecation with which such move was announced
Closes: #8566
> CLI: Revert from unconditional `.env` support

- lib/plugins/aws/invokeLocal/index.js
Reverts #9948 (it covered a bit more originally but other methods were refactored in a meantime)
There was no intention (yet) to get rid of `_.flatMap` in scope of #7747, as reliable alternative in form of `[].flatMap` doesn't work with Node.js v10
PR proposed to refactor it into less readable `[].reduce` logic, which I think reduced readability of logic.
We should keep `_.flatMap` and refactor it into native `[].flatMap` on the grounds of v3 (which will come with dropped support for Node.js v10)
/cc @JonasMatos0 @pgrzesik
> refactor: Bring back `_.flatMap` usage

- docs/providers/aws/events/streams.md
The following paragraph was duplicated in many sections of the page:
> **Note:** The `stream` event will hook up your existing streams to a Lambda function. Serverless won't create a new stream for you.
I think this was because of contributors copy/pasting that along the way. When reading the page it felt really weird reading that over and over.
If there was a reason this paragraph was there in every section feel free to close.
> docs: Removed duplicated paragraph

- commands/plugin-install.js
- lib/cli/interactive-setup/service.js
- lib/plugins/plugin/install.js
- lib/utils/npm-command-deferred.js
- scripts/pkg/build.js
- test/unit/lib/plugins/plugin/install.test.js
Issue observed in CI fails, after refactoring `plugin install` command.
It appeared npm commands were not configured correctly for `spawn` in the context of _standalone_  installations.
Additionally upgraded to rely on npm that recognizes node.js v14 (as standalone build now is based on Node.js v14)
> Standalone: Fix npm command handling issue

- lib/plugins/aws/package/compile/events/eventBridge/index.js
- test/unit/lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Fix issue reported in closed PR: https://github.com/serverless/serverless/pull/9903#issuecomment-929676031
> AWS EventBridge: Fix `MaximumEventAgeInSecond` template reference

- docs/providers/aws/events/event-bridge.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/eventBridge/index.js
- test/unit/lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Fixes issue reported here: https://github.com/serverless/serverless/pull/9903#issuecomment-930540004
I've also simplified the setting to avoid using nested `arn` or `targetArn` property as the `deadLetterConfig` has only single `arn` property. @medikoo Please let me know what do you think about it - do you think it's worth to still keep that nested? 
Additionally, I've spotted and fixed a bug with setting the target config when more properties are involved. 
I've manually tested it and it seems to work correctly :+1:
> fix(AWS EventBridge): Ensure proper support for `deadLetterConfig`

- lib/cli/handle-error.js
- lib/cli/write-service-outputs.js
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/info/index.js
- lib/plugins/aws/logs.js
- lib/plugins/aws/utils/formatLambdaLogEvent.js
Addresses: #9860
Additionally improved error reporting (issue reported internally)
> CLI: Modern logs adjustements for `logs` and `info` commands

- lib/cli/handle-error.js
> CLI: Fix resolution of handler in case of local fallback

- lib/plugins/install.js
- lib/utils/downloadTemplateFromRepo.js
- test/unit/lib/plugins/install.test.js
> refactor(CLI): Modern logs for `install` command

- lib/plugins/slstats.js
> refactor(CLI): Modern logs for `slstats` command

- lib/plugins/aws/configCredentials.js
- lib/plugins/config.js
- test/unit/lib/plugins/aws/configCredentials.test.js
> refactor(CLI): Modern logs for `config`-related command

- lib/plugins/aws/invoke.js
> refactor(CLI): Modern logs for `invoke` command

- lib/plugins/standalone.js
> Modern logs for `standalone`-specific commands

- lib/cli/handle-error.js
- lib/plugins/aws/lib/monitorStack.js
- scripts/serverless.js
Addresses: #9860 
- Ensured no resources progress on create stack (as it's only about addition of deployment bucket)
- Ensured empty line at the end of the output (from the google doc feedback)
> CLI: Improve modern logs for create stack

- lib/plugins/aws/invokeLocal/runtimeWrappers/invoke.py
Parity with how AWS Bootstrap Operates.
Closes: No Issue
> feat(AWS Local Invocation): Support decimal serialization for Python

- lib/Serverless.js
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/info/display.js
- lib/plugins/aws/info/index.js
Goal is to show sections as introduced by plugins after sections set in the core. For that we need to use different section collections.
This PR proposes so `serverless.addServiceOutputSection` is dedicated just for use within plugins, and internally we add sections directly into `serviceOutputs` collection.
> Separate internal and plugin output sections

- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/provider.js
- lib/utils/telemetry/generatePayload.js
- test/unit/lib/plugins/aws/deploy/lib/extendedValidate.test.js
- test/unit/lib/plugins/aws/deployFunction.test.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
- test/unit/lib/plugins/aws/package/lib/generateCoreTemplate.test.js
- test/unit/lib/plugins/aws/package/lib/stripNullPropsFromTemplateResources.test.js
- test/unit/lib/utils/telemetry/generatePayload.test.js
Reported internally, add `projectId` to telemetry
Before releasing, related backend PR needs to be merged
> feat(Telemetry): Add `projectId` to payload

- docs/deprecations.md
- lib/plugins/aws/package/compile/functions.js
- lib/plugins/aws/provider.js
Allow to use `legacy` option for `lambdaHashingVersion` to keep using the old algorithm
> feat: Allow `legacy` option for `lambdaHashingVersion` property

- lib/cli/ensure-supported-command.js
- test/unit/commands/doctor.test.js
- test/unit/lib/cli/ensure-supported-command.test.js
BREAKING CHANGE: Unrecognized CLI options will no longer be supported and
will result in an error.
> Remove support for unrecognized CLI options

- lib/cli/commands-schema/aws-service.js
BREAKING CHANGE: Remove `studio` command schema
Related PR: https://github.com/serverless/dashboard-plugin/pull/638
> feat: Remove `studio` command schema

- lib/classes/CLI.js
We agreed to remove any default decoration for logs written via `serverless.cli.log`.
This will make the logs appear closer to the new logs design
> v3: CLI: Do not decorate `cli.log` logs

- lib/plugins/aws/package/compile/events/apiGateway/index.js
- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
BREAKING CHANGE: Enabling logs or tracing for imported API Gateway will
now result in an error instead of warning
> feat(AWS API Gateway): Error on tracing or logs set for external API

- lib/classes/Service.js
When playing with v3 pre-release spotted the following log, I think we should not recommend setting `frameworkVersion` when pre-release is run:
```
To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^3.0.0-pre")
```
> CLI: Do not recomment `frameworkVersion` when running pre release

- lib/cli/resolve-configuration-path.js
- test/unit/lib/cli/resolve-configuration-path.test.js
BREAKING CHANGE: Custom nested configuration paths will no longer be
supported and such usage will result in an error.
> feat: Disallow custom nested configuration path

- docs/deprecations.md
- docs/getting-started.md
- docs/guides/upgrading-v3.md
This is the "V3 upgrading guide" we had documented internally. I added that into the "Guides" documentation section.
cc @pgrzesik
> docs: Add v3 upgrading guide

- lib/configuration/variables/parse.js
- test/unit/lib/configuration/variables/parse.test.js
Reported internally. It addresses missing support for all cases of `output` variable source. Ref: https://www.serverless.com/framework/docs/guides/output-variables
> feat(Variables): Recognize `:` in address to support `output` source

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
The closing of #8720 was a workaround by supplying an optional option `apiName`.
In a perfect world it should correctly deploy with the recommended `provider.apiGateway.shouldStartNameWithService` without having to provide a custom `apiName`. But the workaround in the issue make it a required option, otherwise the script exits with code 1, and my CI environment is not happy about it.
This PR is a continuation of the discussion I started after the closing of the issue.
For more context please see https://github.com/serverless/serverless/issues/8720#issuecomment-955037755
> fix(AWS API Gateway): Ensure `shouldStartNameWithService` support

- docs/deprecations.md
- docs/guides/upgrading-v3.md
- lib/cli/commands-schema/aws-service.js
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/package/compile/functions.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
Reported internally, introduce a way to ease the lambda hashing algorithm migration
> feat: Introduce `enforce-hash-update` flag to help hashing migration

- lib/plugins/aws/deployList.js
Deployment timestamp serves as an identifier which is used e.g. in `rollback -t <timestamp>` command.
Therefore we improve its visibility in `deploy list` command
Changes output of `deploy list` from:
Into:
> CLI: Improve timestamp visiblity in `deploy list` output

- lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Closes: https://github.com/serverless/serverless/issues/10220
related: https://github.com/serverless/serverless/pull/10177
cc @vicary
> fix(AWS API Gateway): Ensure proper `apiId` resolution

- lib/plugins/create/templates/aws-nodejs-typescript/package.json
Updating `ts-node` from 9.x to 10.x to allow support for more recent `tsconfig.json`.
This remove support for node 10. However this template requires node 14.
> feat(Templates): Update `ts-node` for es2020 and es2021 support

- lib/plugins/aws/invoke.js
- lib/plugins/aws/logs.js
- lib/plugins/aws/utils/formatLambdaLogEvent.js
- test/unit/lib/plugins/aws/utils/formatLambdaLogEvent.test.js
BREAKING CHANGE: Output from `logs` is simplified and no longer follows
standard CloudWatch formatting
> feat: Simplify `logs` command output

- test/fixtures/programmatic/curated-plugins/_setup.js
Otherwise it leaves a broken symlinks of which copying crashes `fse.copy` https://github.com/jprichardson/node-fs-extra/issues/765 (observable in v9 of `fs-extra` we're still relying on).
This issue was responsible for tests not passing in v3 branch once switching to Node.js v16
> Test: Ensure to fully cleanup `serverless` installation when testing plugins

- test/integrationPackage/lambda-files.tests.js
- test/unit/lib/plugins/aws/invokeLocal/index.test.js
- test/unit/lib/utils/fs/fileExistsSync.test.js
After switching integration testing on v3 branch to Node.js v16, package integration tests started to fail. It's due to npm v8 leaving more files behind.
Additionally, ensure the reliability of Windows tests. Discovered that some tests fail on my side, due to slightly different environmental characteristics.
> Test: Fix npm v8 related issues, improve reliablity of Windows testing

- lib/cli/commands-schema/aws-service.js
- lib/cli/commands-schema/common-options/global.js
- test/unit/lib/cli/filter-supported-options.test.js
This PR just ensures that flags are recognized globally by schema.
Actual support is implemented at https://github.com/serverless/utils/pull/149
> v3: CLI: Global `--verbose` and `--debug` flags

- docs/providers/aws/events/sqs.md
- lib/plugins/aws/package/compile/events/sqs.js
- test/unit/lib/plugins/aws/package/compile/events/sqs.test.js
Added functionResponseTypes property support to SQS event source mapping so 'ReportBatchItemFailures' can be set.
- compile/events/sqs.js now handles functionResponseTypes property.
- compile/events/sqs.test.js new test to prove feature works as intended.
- Update in aws/events/sqs.md
> Add functionResponseTypes sqs

- lib/plugins/aws/package/compile/events/s3/index.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js
> feat(AWS S3): Support `Fn::If` CF function for s3 event

- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/deploy/lib/createStack.js
- lib/plugins/aws/lib/updateStack.js
- lib/plugins/aws/provider.js
> feat(AWS Deploy): Support `disableRollback` parameter

- docs/providers/aws/events/streams.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/stream.js
- test/unit/lib/plugins/aws/package/compile/events/stream.test.js
> Add event filtering patterns to stream event type

- docs/providers/aws/cli-reference/invoke.md
Updated the list of supported runtimes for 
`invoke local` to match the actual [supported runtimes](https://github.com/serverless/serverless/blob/4da08996736c9a8f2b0a0193f7cca4b24f3fc6f1/lib/plugins/aws/invokeLocal/index.js#L266-L294).
> docs(AWS Local Invocation): Update supported runtimes

- lib/plugins/aws/deployFunction.js
- test/unit/lib/plugins/aws/deployFunction.test.js
- test/unit/lib/plugins/package/lib/packageService.test.js
After doing a bit of more research I've noticed that at the moment, `updateFunctionConfiguration` is already resilient and does retries in situations where function is still being updated, so I've decided to stick to only ensuring that function is in updated state at the end of `deploy function`.
> feat(AWS Deploy): Ensure consistent function state in `deploy function`

- docs/providers/aws/events/sqs.md
- docs/providers/aws/events/streams.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/sqs.js
- lib/plugins/aws/package/compile/events/stream.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/events/sqs.test.js
> feat(AWS SQS): Support `filterPatterns`

- lib/configuration/variables/resolve.js
- test/unit/lib/configuration/variables/resolve.test.js
Fixes: https://github.com/serverless/serverless/issues/10294
Addresses scenarios where _address_ or _param_ is constructed of variables, which resolve with strings that contain variables. Such case was handled properly for end property values (https://github.com/serverless/serverless/pull/9657), but remained not addressed for internal results that play part in variables resolution.
> Variables: Ensure complete resolution of address and params values

- docs/providers/aws/events/kafka.md
- lib/plugins/aws/package/compile/events/kafka.js
- test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
Closes: #{10260}
https://github.com/serverless/serverless/issues/10260
> feat(AWS Kafka): Add support for `mTLS` access configuration

- lib/plugins/aws/package/lib/stripNullPropsFromTemplateResources.js
- test/unit/lib/plugins/aws/package/lib/stripNullPropsFromTemplateResources.test.js
Previously, `stripNullPropsFromTemplateResources` stripped null from top-level resource properties in the compiled CFN template.
This PR:
- adds functionality to traverse the properties deeply, and strips null from nested objects within the properties
- allows for users to provide default value as null if they would like the variable to be removed from the template if the initial value is not available (see #10279)
Closes: #10279
> Strip null values from CloudFormation template resource properties

- .github/workflows/integrate.yml
- .github/workflows/publish.yml
- .github/workflows/validate.yml
- lib/utils/standalone.js
- package.json
- scripts/pkg/build.js
- scripts/pkg/install.sh
Scope:
- support for binary installation for M1 Macs (still using x86 binary)
- Switch to Node 16 for standalone binaries
- Use Node 16 as main in CI
> Adjust install script for m1 macs & switch to Node 16

- lib/cli/commands-schema/common-options/global.js
- lib/cli/resolve-input.js
- test/unit/lib/cli/resolve-input.test.js
Supporting options at every point lead to ambiguous results and made parsing logic more convoluted.
This patch improves the CLI parsing landscape
> v3: Drop support for placing CLI params (options) before command tokens

- lib/classes/PluginManager.js
- lib/cli/commands-schema/aws-service.js
Lifecycle events marked as deprecated (in context of v1) are no longer evaluated.
They were deprecated in the very early stage of v1, and no known plugins ever relied on them. Currently it's just noise in codebase, good to have cleaned up
> v3: Remove evaluation of deprecated lifecycle events

- docs/deprecations.md
- lib/cli/commands-schema/aws-service.js
- lib/cli/param-reg-exp.js
- lib/cli/parse-args.js
- lib/cli/resolve-input.js
- lib/plugins/deploy.js
- scripts/serverless.js
- test/unit/lib/plugins/deploy.test.js
Additionally, remove `--function` option documentation from `deploy` help
> v3: Deprecate `deploy -f` 

- docs/deprecations.md
- lib/cli/parse-args.js
- test/unit/lib/cli/parse-args.test.js
When `--help` or `-h` flag is passed, we should unconditionally show help
> CLI: Do not crash on help request when invalid options

- lib/plugins/create/templates/aws-java-maven/pom.xml
- lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml
Additional fixes had to be introduced to log4j to address the zero day attack vulnerability.  Hopefully this will be the end of it.
Closes: https://github.com/serverless/serverless/issues/10337
> fix(Plugins): Upgrade log4j to version 2.16.0

- lib/plugins/aws/package/compile/functions.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
> AWS Lambda: Fix event config setup for provisioned lambdas

- lib/cli/handle-error.js
Ensure it's bulletproof against serverless installation issues
If the local installation of `serverless` is not fully installed, there could be a scenario where we optimistically assume the error handler is being placed on the `Error` class.
This patch ensures we handle that right, and do not fall back to local installation
Fixes #10364
> CLI: Improve error handler resolution

- lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
> fix(aws apiGateway): restApiRootResourceId is required when restApId is configured

- docs/providers/aws/guide/serverless.yml.md
Closes: None
This PR documents in the `serverless.yml` reference the following features:
* [HttpApi detailed metrics](https://github.com/serverless/serverless/pull/8510)
* [Disable the default HttpApi endpoint](https://github.com/serverless/serverless/pull/8649)
> docs: Update `httpApi` reference in `serverless.yml.md`

- docs/deprecations.md
- lib/cli/commands-schema/resolve-final.js
Bring back deprecation removed in context of v2 
(Complement to: #10348)
> v3: CLI:  Deprecate missing options schema

- lib/plugins/create/templates/aws-kotlin-jvm-gradle/build.gradle
Updated log4j-api, log4j-core to 2.17.0, aws-lambda-java-log4j2 to 1.5.0
#10370 
Addresses: 10370
> update log4j dependencies.

- lib/plugins/aws/package/compile/events/apiGateway/index.js
- test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Closes: [#8769](https://github.com/serverless/serverless/issues/8769)
> feat(AWS API Gateway): Allow use of custom authorizer with authorizerId

- lib/configSchema.js
- lib/plugins/aws/provider.js
The actual implementation is placed at https://github.com/serverless/dashboard-plugin/pull/648 here we just need to recognize the `params` property in the configuration schema.
Additionally restricted `stage` with pattern validation. Not setting this was overlooked in the context of v2, hence it's now better to add it in v3 (it's a safe change, I've browsed stage values in mixpanel and all I've scrolled through fit the proposed pattern, also stage name as used in stack name and resource names is already restricted by AWS naming rules)
> v3: Support `params` configuration

- lib/plugins/aws/deployFunction.js
- test/unit/lib/plugins/aws/deployFunction.test.js
Ensure that ordering does not matter when comparing VPC-related values.
> fix(AWS Deploy): Check for VPC config change in `deploy function`

- lib/cli/interactive-setup/deploy.js
- lib/cli/interactive-setup/index.js
- lib/plugins/aws/deploy/lib/createStack.js
- lib/plugins/aws/lib/updateStack.js
- lib/utils/telemetry/generatePayload.js
- scripts/serverless.js
- test/unit/lib/cli/interactive-setup/deploy.test.js
- test/unit/lib/utils/telemetry/generatePayload.test.js
Reported internally:
- Ensure to report `projectId` for interactive flow deployments
- Ensure to report creation of a new stack during deployment
> refactor(Telemetry): Ensure to report `projectId` for interactive

- lib/plugins/aws/remove/index.js
- lib/utils/telemetry/generatePayload.js
> feat(Telemetry): Report `projectId` in remove command

- package.json
- scripts/postinstall.js
At same time drop `boxen` dependency, which takes one step forward, towards addressing #10182
> v3: Improve post install log to reflect modern style

- lib/utils/telemetry/index.js
By mistake they were issued at _notice_ level
> CLI: Ensure telemetry logs are issued at debug level

- lib/classes/ConfigSchemaHandler/resolveAjvValidate.js
Reported internally, to avoid memory leaks in tests
> test(Config Schema): Improve caching of Ajv validator

- docs/providers/aws/events/cognito-user-pool.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/cognitoUserPool.js
- test/unit/lib/plugins/aws/package/compile/events/cognitoUserPool.test.js
I tried to implement the proposed solution which can be found [here](https://github.com/serverless/serverless/issues/9635#issuecomment-874320921). I added a `forceDeploy` flag that once set will set a random property in the custom resource that is used to attach triggers - if the flag is set to false then it sets the property to `0`. I updated tests as well, and made sure the linter is happy.
Addresses: #9635
> Add forceDeploy property in Cognito User Pools

- docs/providers/aws/cli-reference/config-credentials.md
- docs/providers/aws/cli-reference/config.md
- docs/providers/aws/cli-reference/create.md
- docs/providers/aws/cli-reference/deploy-function.md
- docs/providers/aws/cli-reference/invoke-local.md
- docs/providers/aws/cli-reference/invoke.md
- docs/providers/aws/cli-reference/login.md
- docs/providers/aws/cli-reference/logs.md
- docs/providers/aws/cli-reference/metrics.md
- docs/providers/aws/cli-reference/rollback-function.md
- docs/providers/aws/events/apigateway.md
- docs/providers/aws/examples/hello-world/csharp/README.md
- docs/providers/aws/examples/hello-world/fsharp/README.md
- docs/providers/aws/examples/hello-world/go/README.md
- docs/providers/aws/examples/hello-world/node/README.md
- docs/providers/aws/examples/hello-world/python/README.md
- docs/providers/aws/examples/hello-world/ruby/README.md
- docs/providers/aws/guide/credentials.md
- docs/providers/aws/guide/services.md
- docs/providers/aws/guide/workflow.md
As discussed internally, there are some code examples (especially CLI snippets) that don't render well. For example:
I tried to go over the main ones (AWS docs, CLI snippets mostly, I avoided the huge YAML code examples for now) and make these multi-line.
> docs: Fix long lines in code examples

- lib/utils/telemetry/generatePayload.js
- test/unit/lib/utils/telemetry/generatePayload.test.js
Reported internally, recognize count of unique params defined
Should be merged after merging corresponding backend request
> Recognize `params_count` 

- lib/cli/interactive-setup/service.js
- test/unit/lib/cli/interactive-setup/service.test.js
Reported internally, ensure that v2 Framework uses examples from `v2` branch for interactive onboarding.
> refactor(CLI Onboarding): Download templates from v2 examples branch

- bin/serverless.js
- package.json
Depends on: https://github.com/serverless/cli/pull/23 being published
> v3: CLI: Remove `@serverless/cli` CLI integration 

- docs/providers/aws/guide/serverless.yml.md
- docs/providers/aws/guide/variables.md
- lib/configuration/variables/sources/file.js
- test/fixtures/programmatic/multiService/serviceA/serverless.yml
- test/unit/lib/configuration/variables/sources/file.test.js
As decided internally, resign from `projectDir` concept.
After that change, files in variables can be resolved from any system path
> Variables: Resign from `projectDir` concept

- lib/plugins/package/lib/packageService.js
- test/unit/lib/plugins/package/lib/packageService.test.js
Reverts serverless/serverless#10259 as it was detected that it breaks some projects that rely on local plugins
More context: https://github.com/serverless/serverless/pull/10259#issuecomment-1008771301
I've decided to keep most of the work from the PR, as it's highly likely we will need a resolution of local plugins, and cleanup of the tests improved maintenance
> Packaging: Revert exclusion of local plugins from a bundle

- lib/cli/interactive-setup/service.js
- test/unit/lib/cli/interactive-setup/service.test.js
Reported internally, switch to `v3` branch in `examples` for onboarding templates
> refactor(CLI Onboarding): Download templates from v3 examples branch

- lib/plugins/create/templates/aws-nodejs-typescript/package.json
Explicitely define `esbuild` dev dependency in aws-nodejs-typescript since `serverless-esbuild` added it as a peer dependency
Closes: #10470
> fix(Templates): Ensure `esbuild` dependency in `aws-nodejs-typescript`

- lib/classes/ConfigSchemaHandler/regexpKeyword.js
- lib/classes/ConfigSchemaHandler/resolveAjvValidate.js
- package.json
Reported internally, `ajv-keywords` together with `npm@6` and dependencies that use different version of `ajv` cause an error due to a bug in how `npm` hoists dependencies: https://github.com/ajv-validator/ajv-keywords/issues/170
It will be added to original commit that upgrades `ajv` to `v8`
> refactor(Config Schema): Do not rely on `ajv-keywords`

- docs/guides/upgrading-v3.md
Document the v3 migration for the [serverless-dotenv-plugin](https://github.com/neverendingqs/serverless-dotenv-plugin).
I'll send a similar PR to the plugin's README once we have validated this PR here.
> docs: Document the migration for `serverless-dotenv-plugin`

- .github/workflows/integrate.yml
- .github/workflows/validate.yml
- bin/serverless.js
When working on local fallback updates, I've realized our Node.js version detection works well only in recent versions of Node.js
e.g. if someone attempts to run Framework with Node.js v6 will see an ugly syntax error. This patch fixes that, and configures test to prevent further regression in that area.
> CLI: Respect old Node.js versions in version detection

- .github/workflows/integrate-v3.yml
- .github/workflows/integrate.yml
- .github/workflows/validate-v3.yml
- .github/workflows/validate.yml
- bin/serverless.js
In v2 error message that states that given Node.js version is not supported is prefixed with `Serverless:`, in v3 to adhere to new logs look I believe it should not be the case.
I've updated it, so it looks as:
@mnapoli if you have any further improvement suggestions, let me know
_(It'll be integrated into commit with which we dropped support for Node.js v10)_
> CLI: Improve Node.js version resolution error message

- lib/classes/ConfigSchemaHandler/index.js
- lib/cli/commands-schema/no-service.js
- lib/configSchema.js
- lib/plugins/aws/deployFunction.js
- lib/plugins/aws/provider.js
- Expose `sls doctor` command
- Cleanup left overs of `awsKmsKey` and `deploy function` handling (will be added to their commits)
> v3: Expose `sls doctor` command and cleanup

- lib/utils/logDeprecation.js
> refactor: Ensure support for `warn` mode for modern deprecations

- docs/deprecations.md
- lib/classes/Service.js
`projectDir` property has not effect. It's recognition will be dropped in v4
> v3: Deprecate `projectDir`

- lib/cli/interactive-setup/dashboard-login.js
- test/unit/lib/cli/interactive-setup/dashboard-login.test.js
Reported internally, related to changes in onboarding flow. 
Question: Should we also have similar behavior if it's existing service with `org` configured already in service config? @medikoo @mnapoli
> feat(CLI Onboarding): Auto login if `--org` flag provided

- docs/guides/cicd/running-in-your-own-cicd.md
- docs/providers/aws/cli-reference/slstats.md
It's a long time `tenant` concept was renamed to `org`. Yet few occurrences can still be found in the docs
> Docs: Remove `tenant` wording

- lib/classes/Service.js
- lib/cli/interactive-setup/utils.js
- scripts/serverless.js
This property is a long time not used by users. v3 is a good time to also drop support for it in a codebase.
Accompanied by https://github.com/serverless/dashboard-plugin/pull/656
> v3: Dashboard: Drop support for `tenant`

- docs/deprecations.md
- docs/environment-variables.md
- docs/providers/aws/events/event-bridge.md
- docs/providers/aws/guide/variables.md
I've gone over sentences like "next major version" or documentation for some deprecated features: the goal was to make it up to date for v3, and a bit less ambiguous ("next major version" will mean v4 next week, so it could be confusing).
There shouldn't be any conflicts with #10468 (which I'll rebase on v3 separately).
> docs: Various updates for the v3 release

- lib/cli/run-serverless-tencent.js
Reported internally by @zongUMR 
Resolution of npm root folder worked ok with npm v6 but not npm v7 and v8. 
Resolution of local installation seemed to never been tested properly, this time I've confirmed that it works
> v3: Fix detection of npm installed `serverless-tencent`

- lib/aws/request.js
- lib/configuration/variables/eventually-report-resolution-errors.js
- lib/plugins/aws/package/compile/functions.js
- lib/utils/npmPackage/isWritable.js
Reported internally, some of the logs haven't been refactored properly with modern implementation
> refactor: Refactor direct use of `@serverless/utils/log`

- lib/cli/interactive-setup/aws-credentials.js
- lib/cli/interactive-setup/dashboard-set-org.js
- lib/cli/interactive-setup/deploy.js
- lib/cli/interactive-setup/utils.js
- test/unit/lib/cli/interactive-setup/aws-credentials.test.js
- test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
- test/unit/lib/cli/interactive-setup/deploy.test.js
- test/unit/lib/cli/interactive-setup/utils.test.js
Follows https://github.com/serverless/dashboard-plugin/pull/661, tests won't pass until PR on `@serverless/dashboard-plugin` side is merged
> v3: Adapt to renames in `@serverless/dashboard-plugin`

- lib/configuration/variables/resolve.js
- test/unit/lib/configuration/variables/sources/file.test.js
- test/unit/lib/configuration/variables/sources/fixture/file-function-many-variables.js
- test/unit/lib/configuration/variables/sources/fixture/file-function-many-variables.yaml
Closes: #10549
This is a minor change to the resolver that removes a false-positive nesting depth error.
When importing a file from a js function (using `resolveVariable`), all variables in that file are resolved in a loop. The loop passes a nest depth of one lower, but did so by decrementing the loop counter on each iteration. This means that once you hit your 10th variable, it aborts because it thinks you've nested to deep (while in fact you're still only one level deep).
Effectively this changes `--nestTracker` to `nestTracker - 1`, so that the actual depth is kept, allowing for normal behavior.
I also added a test case for this particular use-case. Note that while the test case does file inclusion inside the file-included file, it affects any variable resolving, but I did not want to …
> fix: nesting-tracking in resolver aborting too eagerly

- package.json
- test/unit/lib/plugins/aws/customResources/generateZip.test.js
I've got false failures locally, due to `generateZip` being resolved against my local home dir. This fixes that.
While we consider `master` frozen. It's fine to take this in (so it also serves later v2 branch), as it doesn't touch any functionality
> test: Ensure we tests against unached version

- lib/aws/request.js
- test/unit/lib/aws/request.test.js
- test/utils/integration.js
I did not submit the log change to current `master` as I don't want to release yet another v2 release before v3 major
> refactor: Remove leftover `SLS_DEBUG` references

- docs/cn/getting-started.md
- docs/getting-started.md
- docs/guides/upgrading-v3.md
See https://github.com/npm/cli/issues/3175 why `npm update -g` is broken.
I targeted v3 to avoid unnecessary rebase. ATM we don't document the command with a version number, so the risk of keeping that around 1 more week is low I think.
> docs: Switch to `npm i` instead of broken `npm update`

- lib/classes/config-schema-handler/resolve-ajv-validate.js
Reported internally, improve the error message a bit when plugin does not conform to strict schema validation
> fix: Report more meaningful strict schema mode error

- docs/guides/upgrading-v3.md
I've noticed that we see a significant amount of errors about mismatching framework versions - we don't mention the need to update it in our upgrading guide - I think it would be good to include that information there.
> docs: Add information about setting `frameworkVersion`

- docs/providers/aws/events/msk.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/msk/index.js
- test/integration/aws/infra-dependent/msk.test.js
- test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js
Looking at the AWS docs for [EventSourceMappingConfig](https://docs.aws.amazon.com/lambda/latest/dg/API_EventSourceMappingConfiguration.html), it says:
> When you set `BatchSize` to a value greater than 10, you must set `MaximumBatchingWindowInSeconds` to at least 1.
This (bug fix :grimacing:) PR adds the `maximumBatchingWindow` property to serverless.yaml + updates the existing unit test + have updated the integration test, but unable to get the integration test setup working properly.
[new PR after attempting to rebase #10579 failed]
> feat(AWS MSK): Support `maximumBatchingWindow`

- docs/providers/aws/events/kafka.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/kafka.js
- test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
As per #10580, this PR adds `maximumBatchingWindow` property to serverless.yaml for kafka event sources
> feat(AWS Kafka): Support `maximumBatchingWindow`

- docs/providers/aws/events/activemq.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/activemq.js
- test/unit/lib/plugins/aws/package/compile/events/activemq.test.js
As per #10580, this PR adds `maximumBatchingWindow` property to serverless.yaml for ActiveMQ event sources
> feat(AWS ActiveMQ): Support `maximumBatchingWindow`

- docs/guides/plugins/cli-output.md
Hello ! I noticed that a warning that v3 was not released yet was still on the docs website :)
> docs(cli-output): remove v3 warning

- docs/providers/aws/events/rabbitmq.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/rabbitmq.js
- test/unit/lib/plugins/aws/package/compile/events/rabbitmq.test.js
As per #10580, this PR adds maximumBatchingWindow property to serverless.yaml for RabbitMQ event sources
> feat(AWS RabbitMQ): Support `maximumBatchingWindow`

- scripts/serverless.js
- test/fixtures/programmatic/custom-config-filename/serverless.custom.yml
- test/unit/scripts/serverless.test.js
Regression was accidentally introduced with https://github.com/serverless/serverless/pull/10332.
Back in v2, the resolution of `-c/--config` was hardcoded into `lib/cli/resolve-input.js`. While in v3 it was generalized, and co-relies on schema, which defines this option only for _service specific_ commands.
Having that `-c` shortcut stopped being recognized on time, as initial CLI flags resolution (which precedes configuration file resolution), loads schema only for _non-service command flags_
This patch ensures that before we attempt to resolve configuration filename, we have flags common for _service specific_ commands also loaded from schema
Closes: #10601
> CLI: Fix support for `-c` (`--config`) shortcut

- lib/cli/render-version.js
While we support falling back to `serverless-tencent` CLI being installed in three different locations (npm local, npm global, standalone), on printing version info we took into account only the last one. This PR fixes that, so all supported locations are taken into account.
This, unfortunately, slows down `sls -v` output by 200ms (on a fast machine), and it's not much we can do about it
/cc @zongUMR
> CLI: Get `serverless-tencent` version from all supported locations

- docs/getting-started.md
This is a follow-up of Steven's getting started run-through.
We can see in his recording that he:
- installs `serverless`
- then immediately updates it
This is because the "getting started" is structured like this:
- Install
- Upgrade
- Create a project & deploy
We could move "Upgrade" somewhere else, but I don't have a clear vision on that. Maybe a more ambitious solution would be to split into 2 pages:
- _Installation_ -> install & upgrade
- _Getting started_ -> more of a tutorial
However I'm not 100% sure about that yet so I'd rather ship a small improvement today instead of waiting forever for a better option.
So this change is very minimal, but the goal is to suggest that upgrading is **optional**: "you can upgrade" instead of just "upgrade".
> docs: Clarify that upgrading isn't required when getting started

- lib/plugins/aws/lib/get-create-change-set-params.js
- lib/plugins/aws/lib/update-stack.js
- test/unit/lib/plugins/aws/deploy/index.test.js
I've made a mistake during implementation of changeset-based deployments where I omitted that `StackBodyPolicy` is not supported on ChangeSet level directly - I've changed it here to be applied during deployment, after the change set is created (I've tested that it doesn't really have any influence on changeset creation, e.g. if policy prevents update that would be created as a part of changeset, the changeset will still be created and will only fail during execution) to apply it at last possible moment during the update. 
I've also investigated if it's possible to remove the `stackPolicy` during update, because I've noticed that in old logic we've never done it, e.g. if you set `stackPolicy`, deployed, removed `stackPolicy` setting and deployed again, stackPolicy was still left on the …
> fix(AWS Deploy): Properly apply `stackPolicy` with changesets

- lib/plugins/aws/lib/get-create-change-set-params.js
- test/unit/lib/plugins/aws/deploy/index.test.js
It fixes a long-standing bug that is still present on `v2` branch, but due to some internal AWS quirks never surfaced as an error during deployment when `createStack` and `updateStack` operations were used instead of changesets. 
The root of the problem was that when `notificationArns` were specified during deployment and in subsequent deployment they were removed from configuration, they still stayed configured for stack on CloudFormation level. Suprisingly, if the topic was removed and configured ARN pointed to nonexistent topic, the CF updates still happened normally - that changed with ChangeSets, where an attempt to execute ChangeSet results in an error with missing topic. Logic in this PR ensures to explicitly pass empty list to clear any previously set and uncleared notification …
> fix(AWS Deploy): Ensure to clear `notificationArns` if needed

- lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js
- test/integration-package/lambda-files.tests.js
In #10619 report, we can see that AWS SDK's `CloudFormation.getTempalte` can return empty string for `TemplateBody`, we do not handle such scenario well, and that triggers the programmer error. This patch fixes that
--- 
In CI packaging test timed out, most likely due to some npm service issue. I've increased test timeout to follow one set as default
> AWS Deploy: Handle gently missing template body

- lib/cli/interactive-setup/deploy.js
- test/unit/lib/cli/interactive-setup/deploy.test.js
Proposal: 
I have a question though, as the proposed messaging is a bit different than what we show when we setup the dashboard integration during the interactive onboarding - it looks like this:
@mnapoli - do you think we should make them more similar or should I keep it as it is currently proposed? 
Closes: #10611
> feat(CLI Onboarding): Improve deploy messaging

- lib/classes/config-schema-handler/resolve-ajv-validate.js
Happens from time to time in CI: https://github.com/serverless/serverless/runs/5022323764?check_suite_focus=true
Also reported on our forum: https://forum.serverless.com/t/error-on-deploy-after-upgrading-to-v3-typeerror-validate-is-not-a-function/16626/4
I'm not throwing more meaningful error yet because I'm not sure what we should even throw to users as they cannot really act on it in any way
> chore: Add log statements for ajv validation debugging

- docs/guides/upgrading-v3.md
- lib/plugins/aws/package/compile/events/http-api.js
This PR fixes a typo in the serverless execution logs.
All instances of `succesful` were changed to `successful`.
> refactor: Change all occurences of succesful to successful

- lib/classes/plugin-manager.js
- lib/cli/conditionally-load-dotenv.js
- scripts/serverless.js
Improve variable resolution queuing logic.
It also fixes one shortcoming, where after registering all non-AWS specific sources, logic immediately moved to validation on whether properties that influence AWS authentication logic are resolved.
This patch ensure that we attempt to re-resolve those properties having additional information, before validating them. This e.g. allows to configure `provider.profile` with `param` variable sources.
Fixes https://github.com/serverless/serverless/issues/10642
---
Additionally dropped support for `enterpriseDisabled` user configuration property, which didn't seem to be documented anywhere, and if used it prevented to use `param` variables, even with no dashboard enabled in service config.
> Variables: Improve resolution queuing and related cleanup

- CHANGELOG.md
- bin/serverless.js
- docs/guides/upgrading-v3.md
I propose to validate versions against first Node 12 LTS as @medikoo suggested. Please let me know what do you think @mnapoli
> fix: Improve validation of min supported Node version

- docs/deprecations.md
Fix a small typo in the documentation.
BTW, the link at the end of each documentation page is dead since your renamed `master` into `main`: https://github.com/serverless/serverless/edit/master/docs/deprecations.md
> docs: Fix typo in deprecations

- .github/PULL_REQUEST_TEMPLATE.md
Framework Version 3 require Node 12 but the PR template still mention the v10.
> docs: Update PR template to mention Node 12 requirement

- docs/providers/aws/events/websocket.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/provider.js
I used it back with the v1 version, and now on v2 (at least) I got a _Configuration warning_ when defining that value:
```
Serverless: Configuration warning at 'provider': unrecognized property 'websocketsDescription'
```
The value is used in different places but is missing in the config schema.
I've also updated the doc about it.
Simple schema to reproduce the warning:
```yaml
service: serverless-ws-test
provider:
name: aws
websocketsApiRouteSelectionExpression: $request.body.route
websocketsDescription: Hi, I'm here to trigger a warning!
functions:
wsHandler:
handler: handler.wsHandler
events:
- websocket:
route: $connect
- websocket:
route: $disconnect
- websocket:
route: $default
```
> fix(Config Schema): Recognize `provider.websocketsDescription`

- lib/cli/run-serverless-tencent.js
Reported internally by @zongUMR 
It appears that in case of falling back to _binary_ `serverless-tencent` we never exposed it's exit code, and `sls` CLI always exited with `0`, which definitely should not be the case.
> CLI: Ensure to pass through `serverless-tencent` exit code

- docs/providers/aws/cli-reference/invoke-local.md
This PR makes some updates and improvements to the docs for `invoke local` (current docs [here](https://www.serverless.com/framework/docs/providers/aws/cli-reference/invoke-local#local-function-invocation-with-data-passing)):
- Removed the `--skip-package` arg, because it doesn't exist
- Updated examples to prefer JSON event and context, because most of the codebase parses the input as JSON.
- Changed the context example to be more in line with recommended use. There's no point doing weird things with the context (like making it a string) when it has a fixed, documented shape in the Lambda env.
- Improved the wording of some of the options to be clearer.
> docs: Improve `invoke local` documentation

- lib/cli/render-version.js
Noticed in bug reports, that version prints as:
```
Running "serverless" from node_modules
Framework Core: 3.2.0 (local) 3.2.1v (global)
Plugin: 6.0.0
SDK: 4.3.1
```
`v` postfix should not be there
> CLI: Remove obsolete `v` postfix when listing global version

- docs/providers/aws/cli-reference/deploy.md
- docs/providers/aws/cli-reference/info.md
- docs/providers/aws/cli-reference/remove.md
- docs/providers/aws/cli-reference/rollback.md
- docs/providers/aws/guide/services.md
- docs/providers/azure/cli-reference/deploy.md
- docs/providers/azure/cli-reference/rollback.md
- docs/providers/azure/guide/function-apps.md
- docs/providers/cloudflare/cli-reference/deploy.md
- docs/providers/fn/cli-reference/deploy.md
- docs/providers/kubeless/cli-reference/deploy.md
- docs/providers/kubeless/cli-reference/info.md
- docs/providers/kubeless/cli-reference/remove.md
- docs/providers/kubeless/guide/services.md
- docs/providers/openwhisk/cli-reference/deploy.md
- docs/providers/openwhisk/cli-reference/info.md
- docs/providers/openwhisk/guide/services.md
- docs/providers/spotinst/cli-reference/deploy.md
- docs/providers/spotinst/cli-reference/info.md
- docs/providers/spotinst/cli-reference/remove.md
- docs/providers/tencent/cli-reference/rollback.md
> docs: Remove reference to `-v` as shortcut for `--verbose`

- lib/plugins/aws/invoke-local/index.js
- lib/plugins/aws/invoke-local/runtime-wrappers/invoke.rb
This PR improves the quality of the `invoke local` integration for Ruby (specifically the fake context), bringing it closer to par with the Node.js and Python ones:
- Fixes bug that made `FakeLambdaContext` crash when extra options were supplied. The existing code `send(k, v)` calls nonexistent methods.
- Fixes bug that makes `invoke local` crash on Ruby 2.5 if a context is passed by the user
- Randomizes the `aws_request_id`, so each request has a different ID (something tracing code often depends on)
- Sets the function name correctly (which makes the invoked_function_arn, log group and log stream name more correct)
- Sets the memory limit as specified in `serverless.yml`
- Allows for the user to correctly override the defaults (though they shouldn't need to)
- Cleaned up the code so …
> fix(AWS Local Invocation): Improve `ruby` context

- docs/guides/parameters.md
- lib/cli/commands-schema/common-options/service.js
- test/unit/lib/cli/filter-supported-options.test.js
Due to the fact that resolution logic for it is implemented in `dashboard-plugin`, actual support will be introduced after merging https://github.com/serverless/dashboard-plugin/pull/670/files
Addresses: #9817
> feat(Variables): Support for `--param` CLI options

- .github/workflows/publish.yml
Spotted in https://github.com/serverless/serverless/pull/10735#pullrequestreview-889594161
> ci: Ensure id for cache step when publishing

- docs/deprecations.md
- docs/guides/upgrading-v3.md
Improved documentation for the 3 main deprecations impacting v2 users:
- CLI free-form options: mention `--param`
- New variable resolver: dedicated section in the upgrade guide, more explicitly instructions in the deprecation docs
- Lambda hashing version: fix links, centralize and simplify instructions
> Improve v3 upgrade guide

- lib/plugins/aws/provider.js
Add support for the new [.NET 6 runtime](https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/).
> feat(AWS Lambda): Add support for `dotnet6` runtime

- lib/utils/telemetry/generate-payload.js
- package.json
After upgrade to `isInteractive` logic in `serverless/utils`, we should not rely on that for `isTtyTerminal` as it might have false negatives in CI environments.
> refactor(Telemetry): Rely on direct evaluation of `isTtyTerminal`

- lib/utils/fs/safe-move-file.js
> fix: Properly move directories across filesystems

- docs/providers/aws/guide/serverless.yml.md
Reported to @garethmcc: in v3 the key has been renamed from `schema` to `schemas` (https://www.serverless.com/framework/docs/deprecations#aws-api-gateway-schemas).
Please double-check my change just in case :)
> docs: Fix `schemas` documentation following v3 release

- scripts/serverless.js
I've noticed that some of the events have `shouldSendTelemetry` field included in the payload while inspecting telemetry implementation for totally unrelated purposes. This PR should fix it.
> fix(Telemetry): Ensure excluding `shouldSendTelemetry` from payload

- docs/providers/aws/events/event-bridge.md
I was looking for a way to use EventBridge with s3 event instead of the existing s3 event integration.
I then discovered we can have a robust content filtering for EventBridge pattern and thought it was a good idea to add it to the documentation.
> docs: Add example for EventBridge with content filtering

- docs/README.md
- docs/providers/README.md
Since almost all of the actually useful documentation is currently in "Provider > AWS", I thought it would make sense to rename the menu. Mentioning "CLI" is confusing to me, because most of the documentation is also about YAML configuration.
My guess is that the "CLI" word made sense with the perspective of mixing Dashboard documentation with Framework docs. But at the moment I think it's bringing more confusion.
**Note: I don't know enough about how the menu is built to guarantee that this PR will actually change the menu, code review on this is welcome.**
> docs: Rename menu to "Provider References"

- lib/classes/console.js
- lib/cli/interactive-setup/dashboard-login.js
- lib/cli/interactive-setup/dashboard-set-org.js
- lib/cli/interactive-setup/index.js
- lib/cli/interactive-setup/service.js
- lib/cli/interactive-setup/utils.js
- lib/utils/telemetry/generate-payload.js
- package.json
- test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
- test/unit/lib/cli/interactive-setup/utils.test.js
- Support joint Console & Dashboard integrations
- Do not list not supported by Console services when Console integration is to be setup
- Fix discovered logic bugs
- Introduce additional `isConsoleEnabled` property for `initialContext`
> Console: Interactive CLI improvements

- docs/providers/aws/guide/serverless.yml.md
I was unable to use the syntax as provided. 
```yaml
apiKeys:
- myFirstKey
value: myFirstKeyValue
description: myFirstKeyDescription
customerId: myFirstKeyCustomerId
enabled: false
```
It gave an error:
```
Cannot parse "serverless.yml": bad indentation of a sequence entry in "/src/serverless.yml" (14:20)
```
From trial and error, I realized that it should be this:
```yaml
apiKeys:
- name: myFirstKey
value: myFirstKeyValue
description: myFirstKeyDescription
customerId: myFirstKeyCustomerId
enabled: false
```
> docs: Fix incorrect `apiKeys` example

- lib/plugins/aws/package/compile/events/kafka.js
- test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
This removes a check that prevented us from using a Kafka server root ca cert without using TLS client auth.
The check was previously implemented based on wrong assumptions. The two certs are actually independent from each other.
Addresses: [#10260](https://github.com/serverless/serverless/issues/10260)
> fix(AWS Kafka): Allow usage of Server Root CA without client TLS auth

- scripts/pkg/upload/index.js
Mitigate issue where on publication, assets are not uploaded to GitHub as expected.
We upload to two servers in parallel, failure of any of them was resulting in rejection and immediate process exit, therefore breaking the upload of the other.
In this patch, I've ensured that we put priority on GitHub upload and handle eventual error in China upload, after successful GitHub upload. It's ok for China, as for them new releases of `serverless` are mostly meaningless. It's only about triage logic, which in turn falls back to Tencent Cli, and that triage doesn't change across releases
Fixes #10852
> Standalone: Ensure error in China upload don't break GitHub upload

- lib/classes/console.js
- Upgrade to rely on `0.2` version of the layer extension
- Fix handling, when no creation template is created (custom deployment bucket), extension packaging then failed as `.serverless` dir wasn't ensured to exist yet.
> Console: Upgrade otel extension & fix packaging

- lib/classes/console.js
- lib/utils/telemetry/generate-payload.js
- test/unit/lib/classes/console.test.js
It appears https://github.com/serverless/serverless/pull/10860 wasn't good enough. Configured some tests to cover that test case this time.
Additionally report to telemetry eventually used extension version
> Console: Fix custom deployment bucket handling

- lib/classes/console.js
- lib/cli/interactive-setup/dashboard-set-org.js
- lib/cli/interactive-setup/utils.js
- lib/config-schema.js
- lib/configuration/is-dashboard-enabled.js
- lib/plugins/aws/info/get-stack-info.js
- lib/plugins/aws/package/compile/functions.js
- lib/plugins/aws/package/index.js
- lib/plugins/aws/package/lib/validate-template.js
- test/unit/lib/classes/console.test.js
- test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
- test/unit/lib/cli/interactive-setup/deploy.test.js
- Revert from disabling Dashboard integration when `console: true` (user needed to add `dashboard: true` to have Dashboard enabled). After this change, `org` and `console` enables the Console, and `org` and `app` enables the Dashboard (so with `org`, `app` and `console`, both Console and Dashboard integrations are on)
- Support `dashboard.disableMonitoring` to introduce a way to rely on Dashboard providers feature but having Dashbaord integration turned off (needs also https://github.com/serverless/dashboard-plugin/pull/685)
- List extension layer in `layers` outputs section
- Introduce meaningful error reporting when service for given function has already 5 layers configured
- Fix issue (reported in contributors slack channel) where for layers configured at `providers.layers` console …
> Console: Support dashboard providers and validate layers count

- docs/configuration-validation.md
No corresponding issue.
Just a PR to mention default behavior as initially thought this was a optional feature, but it seems that this is enabled by default.
Reference: https://github.com/serverless/serverless/issues/8985
Please let me know in case you want some phrasing to be changed.
> docs: Default of `configValidationMode` option

- lib/plugins/aws/info/get-stack-info.js
It's to avoid plugin breakage as communicated at https://github.com/serverless/serverless/pull/10895#issuecomment-1079705625
> AWS Deploy: Ensure no internal dependency on `console`

- lib/plugins/aws/lib/update-stack.js
- test/unit/lib/plugins/aws/deploy/index.test.js
Closes: #10904
~This change could probably be tested with `sinon.assert.callOrder(spy1, spy2, ...)`, but I could not find any existing tests around this code.~ Added a new test in `test/unit/lib/plugins/aws/deploy/index.test.js` as well.
> fix(AWS Deploy): Apply stack policy after executing change sets

- lib/plugins/aws/invoke-local/index.js
If the image is missing the output will be the empty string. Otherwise, the output contains an image id. And `true` should be returned in this case.
> fix(AWS Local Invocation): Ensure package before resolving runtime

- lib/cli/interactive-setup/dashboard-set-org.js
- package.json
Reported internally, this change removes the check for unsupported runtimes in Dashboard as it's still possible to track deployments of services, user dashboard params, or providers with unsupported runtimes, as seen below:
During deployment, the warning will still be visible and inform that Dashboard doesn't support certain runtimes
> feat(CLI Onboarding): Support all runtimes for dashboard

- lib/plugins/create/create.js
This PR fixes a typo in CLI that occurs after creating a project:
```
✔ Project sucessfully created in
```
->
```
✔ Project successfully created in
```
> refactor(CLI): Fix typos in `create` CLI messages

- lib/plugins/aws/lib/naming.js
- test/unit/lib/plugins/aws/lib/naming.test.js
I could not use `replaceAll` because it's only available since Node 15. 
I decided to not replace `-` with `Dash` word to keep the consistency with the previous intention. 
Closes: #10938
> fix(AWS API Gateway): Correctly construct resource name for schema

- lib/utils/telemetry/index.js
- test/unit/lib/utils/telemetry/index.test.js
Reported internally - pass unique ID to events for deduplication purposes
> refactor(Telemetry): Ensure to pass unique id with events

- lib/plugins/aws/invoke-local/index.js
1. Clone the latest https://github.com/SerheyDolgushev/serverless-rust-example:
```bash
git clone git@github.com:SerheyDolgushev/serverless-rust-example.git
cd serverless-rust-example
```
2. Install Node.js dependencies:
```bash
npm install --only=dev
```
3. Run `get_variable` action for `AccountElasticsearchDomainEndpoint` variable:
```bash
npx serverless invoke local -f hello -d '{"action": "get_variable", "name": "AccountElasticsearchDomainEndpoint"}'
```
```bash
{"name":"AccountElasticsearchDomainEndpoint","value":"[object Object]"}
```
```bash
{"name":"AccountElasticsearchDomainEndpoint","value":"search-account-test-24zc7k4nrcwra44odfw7jy4v44.us-east-1.es.amazonaws.com"}
```
> fix(AWS Local Invocation): Ensure env vars resolve for docker

- docs/providers/aws/events/websocket.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/websockets/lib/stage.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Addresses: #6218
Also related to #6578 and #7836
The PR adds `accessLogging`, `executionLogging`, `fullExecutionData`, and `format` options to websocket log configuration, which only provides the `level` option now.
By that, you can configure websocket log just like restApi log.
```yaml
provider:
name: aws
logs:
websocket:
level: INFO
fullExecutionData: false
```
It's more like a bug fix rather than feature improvement, becuase it just implements what [the documentation describes](https://github.com/serverless/serverless/blob/main/docs/providers/aws/events/apigateway.md#logs).
> feat(AWS Websocket): Add ability to configure log format and types

- lib/cli/run-compose.js
Reported internally, handle `@serverless/compose` install in non-interactive environments
> Handle `@serverless/compose` install in non-interactive

- lib/configuration/variables/resolve.js
- test/unit/lib/configuration/variables/resolve.test.js
Support custom error in variable resolution mechanism, e.g. along those lines
Related: https://github.com/serverless/dashboard-plugin/pull/690
> refactor: Support custom error message for variables resolution

- lib/classes/console.js
- lib/config-schema.js
- lib/utils/telemetry/generate-payload.js
- test/unit/lib/classes/console.test.js
- Propagate `disableLogsCollection` into extension, so it doesn't observe logs internally
- Propagate `disableRequestResponseCollection` into extension so no request and response data is collected
Additionally fixed issue in telemetry related to console deployment reporting. It appears Console deployments were reported only when they came together with Dashboard deployments. I was surprised to see a Dashboard advertisement when doing console deployment and when investigating that found the issue.
> Console: New monitoring configuration options

- lib/classes/console.js
- package.json
It appears in a meantime extension was configured with additional server URL (to be read from environment variables) and Framework didn't set it up. This PR fills the gap
> Console: Ensure to send lambda requests and responses to ingestion server

- lib/plugins/aws/invoke-local/index.js
Occasionally we observe timeout issues on Windows in CI (e.g. https://github.com/serverless/serverless/runs/6131171414?check_suite_focus=true), yet written logs do not provide a clue.
Switch to observable `spawn`, so child process logs are provided in test output
> AWS Local Invocation: Improve debugabilty of Python invocations

- commands/plugin-install.js
- commands/plugin-uninstall.js
- scripts/serverless.js
- test/unit/commands/plugin-install.test.js
Discovered as a part of Discussion: https://github.com/serverless/serverless/discussions/10980
Ensures to only ensure selected properties are resolved for plugin commands + ensures to not add duplicate entries for plugins if they're hidden behind a variable.
> fix: Ensure to attempt minimal config resolution for plugin commands

- lib/plugins/aws/deploy/lib/check-for-changes.js
All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/
> chore: Remove references to git.io

- lib/plugins/aws/package/compile/events/s3/index.js
- test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js
> fix: Allow S3 event rule prefix and suffix to use CF functions

- lib/cli/triage.js
- test/unit/lib/cli/triage/index.test.js
Improve triage process to do not run `compose` engine when command is not service specific. Reported internally
> feat(CLI): Do not run `compose` for non-service commands

- docs/providers/aws/guide/deploying.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/deploy/lib/create-stack.js
- lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js
- lib/plugins/aws/lib/get-create-change-set-params.js
- lib/plugins/aws/lib/get-create-stack-params.js
- lib/plugins/aws/lib/get-shared-stack-action-params.js
- lib/plugins/aws/lib/get-update-stack-params.js
- lib/plugins/aws/lib/update-stack.js
- lib/plugins/aws/provider.js
- lib/plugins/aws/rollback.js
- test/unit/lib/plugins/aws/deploy/index.test.js
Re-introduce the ability to use direct stack updates instead of changeset based deployments.
Addresses: https://github.com/serverless/serverless/issues/10815
> Re-introduce ability to use direct stack updates

- docs/providers/aws/guide/serverless.yml.md
Document max retry attempts for async Lambda invocations: https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html
It's supported by Serverless, just not documented as far as I can see
> [Docs] Add maximumRetryAttempts to AWS guide

- docs/deprecations.md
- docs/providers/aws/events/websocket.md
- lib/plugins/aws/package/compile/events/websockets/lib/api.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/package/compile/events/websockets/index.test.js
**What is problem?**
Websockets API Gateway created by serverless framework does not have tags.
**Fix**
Adding of tags for Websocket API GW wasn't implemented.  The fix is ​​to add the missing functionality.
> feat(AWS Websocket): Allow propagating tags to Websocket APIGW

- README.md
@mnapoli @pgrzesik added `serverless --console` info to the `README` file, in favour of clarity in how to integrate with other tools in the Serverless ecosystem.
> Add Console integration procedure to `README`

- lib/plugins/aws/provider.js
AWS Lambda now supports nodejs16.x
https://github.com/aws/aws-lambda-base-images/issues/14#issuecomment-1120864028
Updated the validation so that serverless does not throw a warning when using in projects with nodejs16.
> feat(AWS Lambda): Add support for `nodejs16.x` runtime

- docs/providers/aliyun/README.md
- docs/providers/aliyun/cli-reference/README.md
- docs/providers/aliyun/events/README.md
- docs/providers/aliyun/guide/README.md
- docs/providers/aws/cli-reference/README.md
- docs/providers/aws/events/README.md
- docs/providers/aws/examples/README.md
- docs/providers/azure/cli-reference/README.md
- docs/providers/azure/events/README.md
- docs/providers/azure/examples/README.md
- docs/providers/azure/guide/README.md
- docs/providers/cloudflare/cli-reference/README.md
- docs/providers/cloudflare/events/README.md
- docs/providers/cloudflare/guide/README.md
- docs/providers/fn/cli-reference/README.md
- docs/providers/fn/events/README.md
- docs/providers/fn/guide/README.md
- docs/providers/google/cli-reference/README.md
- docs/providers/google/events/README.md
- docs/providers/google/examples/README.md
- docs/providers/google/guide/README.md
- docs/providers/kubeless/cli-reference/README.md
- docs/providers/kubeless/events/README.md
- docs/providers/kubeless/guide/README.md
- docs/providers/kubeless/guide/debugging.md
- docs/providers/openwhisk/cli-reference/README.md
- docs/providers/openwhisk/events/README.md
- docs/providers/openwhisk/examples/README.md
- docs/providers/openwhisk/guide/README.md
- docs/providers/spotinst/guide/README.md
Replace Gitter links with Slack links.
> docs: Replace Gitter links with Slack

- docs/providers/aws/events/s3.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/s3/index.js
- package.json
- test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js
I have added a forceDeploy flag to the s3 bucket event trigger. The same logic has been used as in [#10435](https://github.com/serverless/serverless/pull/10435). I have tested this locally and it seems to work.
Closes: [issue 10939](https://github.com/serverless/serverless/issues/10939)
> feat(AWS S3): Support `forceDeploy` setting

- lib/plugins/aws/provider.js
The [current list of supported log retention days](https://github.com/serverless/serverless/blob/main/lib/plugins/aws/provider.js#L622-L625) for AWS CloudWatch Logs is not inclusive of the [supported list by AWS](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#API_PutRetentionPolicy_RequestSyntax).
Missing supported options are: 2192, 2557, 2922, and 3288. This change adds those options.
Closes: https://github.com/serverless/serverless/issues/11075
> refactor(AWS Lambda): Recognize all supported log retention days

- docs/providers/aws/events/http-api.md
This is an output that will get more and more used with Compose.
Currently it's only mentioned once in a forum post (https://www.google.com/search?client=firefox-b-d&q=serverless.yml+httpapiurl) so I thought I'd document it.
> docs: Document the HTTP API URL output

- lib/cli/commands-schema/resolve-final.js
- lib/configuration/variables/resolve-unresolved-source-types.js
- scripts/serverless.js
- test/unit/lib/configuration/variables/resolve-unresolved-source-types.test.js
- test/unit/lib/configuration/variables/resolve.test.js
- test/unit/scripts/serverless.test.js
When investigating https://github.com/serverless/serverless/issues/11068 I've discovered two bugs, which this PR fixes.
1. Trying to run unrecognized command in context of custom provider resulted with programmer error as `TypeError: Cannot convert undefined or null to object`. It's due to regression introduced with https://github.com/serverless/serverless/pull/10846 where dependency on newly added `.commonOptions` was introduced, yet this property was not secured at final schema resolution.
2. Configuring property with not recognized variable source but which used recognized variable source for _param_ or _address_ (e.g. `${unrecognized(${self:service})}`, resulted with error message as `Unrecognized configuration variable sources: ""`. It's because unresolved source resolver was …
> CLI & variable resolution issues

- docs/providers/aws/guide/layers.md
Support for "package.include" and "package.exclude" will be removed in the next major release. Please use "package.patterns" instead
More info: https://serverless.com/framework/docs/deprecations/#PACKAGE_PATTERNS
> docs: Mention `patterns` instead of `exclude` in layers.md

- lib/cli/interactive-setup/aws-credentials.js
- lib/cli/interactive-setup/deploy.js
- test/unit/lib/cli/interactive-setup/aws-credentials.test.js
- test/unit/lib/cli/interactive-setup/deploy.test.js
PR addresses the following issues:
- With Console integration on, Dashboard providers were not handled as expected in the AWS credentials setup step
- In the Deployment step, providers check was skipped when `dashboard.disableMonitoring` was set (although this setting is meant to prevent deploying to dashboard but still allow to resolve providers)
> CLI Onboarding: Fix providers recognition

- lib/cli/interactive-setup/console-login.js
- lib/cli/interactive-setup/utils.js
Following the discussion on Slack, this PR improves the onboarding messages for Console, for existing projects only (to minimize risk).
Before:
After:
> feat: Improve CLI messages when onboarding into Console

- lib/classes/console.js
- lib/config-schema.js
- test/unit/lib/classes/console.test.js
We've agreed internally to switch to a new user settings format (corresponding PR on runtime side: https://github.com/serverless/runtime/pull/57)
This technically is a  breaking change, but we consider this feature still experimental, so it's ok to push it that way.
Urls for logs and request/response collection are now propagated unconditionally as that's not harmful. Extension on it's own in response to user settings does not observe function logs, requests or responses.
--- 
Additionally reconfigured to support new format of `SLS_OTEL_USER_SETTINGS` as introduced with https://github.com/serverless/runtime/pull/62
> Console: Support new user settings format

- lib/cli/interactive-setup/utils.js
Reported internally (https://serverlessinc.atlassian.net/browse/SC-100): the landing page is a better resource to explain the product.
> chore: Update Console link in onboarding

- README.md
The Console ad in the README incorrectly says "View docs": the short URL was changed to point to the register page. That creates a very confusing and poor experience for visitors.
This PR adds a link to the console home page (for those looking to learn _what_ Console is), and rewords the link to "Register" to set expectations to visitors.
I also took the opportunity to fix the "bold" style caused by the table heading.
> docs: Fix Console link in README

- docs/providers/google/guide/README.md
Remove a old note about the availability of Google Functions. Seems like availability isn't an issue anymore 
- [Locations](https://cloud.google.com/functions/docs/locations)
> docs: Remove incorrect note about google functions availability

- .github/ISSUE_TEMPLATE/bug-report.yml
Users are repeatedly reporting issues with v2, marking they're relying on the latest version.
Either they intentionally mark the checkmark with false information, or they do not have a good understanding of what the latest version is (even though we provide a link under the question to verify that).
This update should reduce such reports, and push users to upgrade to v3 before reporting v2 issues to us.
> Issue template:  Improve latest version requirement

- lib/plugins/aws/invoke.js
- lib/plugins/aws/logs.js
- test/unit/lib/plugins/aws/invoke.test.js
> fix(AWS Invocation): Ensure proper log formatting for `invoke`

- docs/deprecations.md
The provided link `https://www.serverless.com/framework/docs/parameters#cli-parameters` was dead.
> docs: Fix link to `--param` CLI option

- test/fixtures/programmatic/iot-fleet-provisioning/package.json
Upgrade the related library as new, fixed version was just released: https://github.com/aws/aws-iot-device-sdk-js-v2/issues/264
> test: Upgrade to latest `aws-iot-device-sdk-v2`

- lib/plugins/aws/invoke-local/index.js
- test/fixtures/programmatic/invocation/async-cjs.cjs
- test/fixtures/programmatic/invocation/serverless.yml
- test/unit/lib/plugins/aws/invoke-local/index.test.js
Found out about this problem internally when working on https://github.com/serverless/dashboard-plugin/pull/692
Adds support for `.cjs` extension for handlers in local invoke for Node
> feat(AWS Local Invocation): Support Node handlers with `.cjs` extension

- docs/menu-builder.html
I've updated the online docs to link to the [Serverless Community Survey](https://slss.io/survey).
This PR reflects that in the menu script.
> docs: Link to the serverless survey

- lib/plugins/aws/invoke-local/index.js
- package.json
- test/fixtures/programmatic/invocation/esm/async-esm.js
- test/fixtures/programmatic/invocation/esm/package.json
- test/fixtures/programmatic/invocation/serverless.yml
- test/unit/lib/plugins/aws/invoke-local/index.test.js
- fallback to dynamic import if require fails and errorcode says 'ERR_REQUIRE_ESM'
Closes: #11143
> feat(AWS Local Invocation): Support Node handlers that are ECMAScript modules

- commands/login.js
- lib/cli/interactive-setup/console-login.js
- lib/commands/login/console.js
For telemetry purposes, we want to send information on what command originated the login.
Technically there are two commands (`` (onboarding) and `login`) which originate the login. As onboarding is command-less CLI invocation, I've decide to cover it under `onboarding` name (empty string won't work well here)
Proposed change here is ineffective until we have https://github.com/serverless/utils/pull/183 merged and published (yet it's safe to be merged earlier)
> Console: Report command which originated login operation

- lib/classes/console.js
- lib/plugins/aws/deploy-function.js
- lib/plugins/aws/deploy/index.js
- lib/plugins/aws/deploy/lib/upload-artifacts.js
- lib/plugins/aws/info/get-stack-info.js
- lib/plugins/aws/lib/naming.js
- lib/plugins/aws/package/compile/functions.js
- lib/plugins/aws/package/compile/layers.js
- lib/plugins/aws/package/lib/save-service-state.js
- lib/plugins/aws/package/lib/validate-template.js
- lib/plugins/aws/rollback.js
- lib/plugins/package/lib/package-service.js
- lib/utils/telemetry/generate-payload.js
- test/unit/lib/classes/console.test.js
Since v0.5 release of extension layers. The extension layers are setup as made specifically for Serverless Console (they're no longer observability tool agnostic) and are pre-published to our AWS accounts into all regions (so there's no longer need to upload them to user account and reference from there)
This PR ensures we rely on those layers and upgrade to v0.5
> Console: Rely on Console ready layers pre-published to AWS

- docs/providers/aws/events/http-api.md
- lib/plugins/aws/package/compile/events/http-api.js
- test/unit/lib/plugins/aws/package/compile/events/http-api.test.js
Closes: https://github.com/serverless/serverless/issues/11222
This is already the behavior with the REST API Gateway. The previous computation didn't consider the cold start of the functions. More details in the issue
> feat(AWS HTTP API): Use the default API Gateway timeout of 30s

- lib/cli/triage.js
Addresses: https://github.com/serverless/compose/issues/151
> refactor: Ignore `doctor` in Compose triage

- docs/providers/aws/events/cognito-user-pool.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/custom-resources/resources/cognito-user-pool/lib/user-pool.js
- lib/plugins/aws/package/compile/events/cognito-user-pool.js
- test/fixtures/programmatic/cognito-user-pool/core.js
- test/fixtures/programmatic/cognito-user-pool/serverless.yml
- test/integration/aws/cognito-user-pool.test.js
- test/unit/lib/plugins/aws/package/compile/events/cognito-user-pool.test.js
Hi all!
I saw that #10834 stalled, and I see a need for supporting Custom Sender Triggers for Cognito. I used #10834 as a guide to create my own implementation of the custom sender triggers.
This PR adds support for `CustomSMSSender` and `CustomEmailSender` as [documented by AWS](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sender-triggers.html).
To address [a comment from the original pull request](https://github.com/serverless/serverless/pull/10834#issuecomment-1068027407), only 1 `kmsKeyId` can be configured per Cognito User Pool.
I have also added various unit tests, as well as an integration test. I did not make new files for these, rather updated the original tests for Cognito User Pools.
Thank you!
Closes: #8889
> feat(AWS Cognito): Add Support for Custom Sender Triggers

- lib/cli/commands-schema/resolve-final.js
- lib/plugins/aws/invoke-local/index.js
- lib/plugins/aws/package/compile/events/api-gateway/lib/hack/disassociate-usage-plan.js
> refactor: Replace `_.flatMap` with `Array.prototype.flatMap`

- lib/plugins/aws/deploy/lib/check-for-changes.js
- lib/plugins/aws/metrics.js
- lib/plugins/aws/package/compile/events/api-gateway/lib/api-keys.js
- lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
- lib/plugins/aws/utils/get-s3-objects-from-stacks.js
> refactor: Replace `_.flatten` with `Array.prototype.flat`

- lib/configuration/variables/resolve.js
- test/unit/lib/configuration/variables/resolve.test.js
In specific scenarios, there can be multiple resolution batches which attempt to resolve same variable. Resolver internally was doing modifications on variables meta, which could result in breaking flow for other resolution that's done in parallel. 
This patch ensures it's no longer the case
Closes: #11286
> Variables: Fix handling of parallel resolution of same variable

- docs/providers/aws/events/apigateway.md
The documentation on using shared authorizer seemed misleading, as in one of the two examples the authorizer specifiers (`type` and `authorizerId` properties) were not nested under the `authorizer` property.
Added a missing line specifying the 'authorizer' property as a parent for `authorizerId` and `type` properties.
> docs: Add missing line in Shared Authorizer example

- docs/providers/aws/cli-reference/print.md
- docs/providers/aws/events/apigateway.md
- docs/providers/aws/events/websocket.md
- docs/providers/aws/guide/credentials.md
- docs/providers/aws/guide/functions.md
- docs/providers/aws/guide/services.md
- docs/providers/aws/guide/variables.md
- docs/providers/azure/guide/serverless.yml.md
Changes deafult nodejs version from 12.x to 14.x in docs for AWS provider.
AWS is ending support fon nodejs12.x during late 2022. Read more here: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy
> docs: Default to nodejs14.x in AWS docs

- docs/providers/aws/events/kafka.md
- docs/providers/aws/events/msk.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/kafka.js
- lib/plugins/aws/package/compile/events/msk/index.js
- test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
- test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js
Context: this has just been added to the event trigger as a feature and is an extremely useful missing feature: https://aws.amazon.com/about-aws/whats-new/2022/08/aws-lambda-consumer-group-ids-msk-kafka-event-sources/
Closes: (No issue created yet for this)
> feat(AWS Lambda): Add support for consumer group ID to kafka event

- lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js
When the deployment bucket is not found, add the bucket name to the exception so that it is easier to determine what is wrong.
This is especially useful when the specified bucket name is an interpolated string and confirming variables are properly being set is useful.
Closes: #11387.
Thanks!
> Add bucket name to exception

- lib/plugins/aws/custom-resources/index.js
- test/unit/lib/plugins/aws/custom-resources/index.test.js
> NodeJS updated to 16.x

- docs/providers/aws/events/cloudfront.md
Per the docs listed within this page Lambda at edge now support Python 3.9 and node 16.x runtimes. Updating docs to reflect that.
> Update Docs for Allowed CloudFront Lambda@Edge Runtimes

- docs/guides/upgrading-v3.md
The `-v` flag has changed meaning.
```
Options
--help / -h                     Show this message
--version / -v                  Show version info
--verbose                       Show verbose logs
--debug                         Namespace of debug logs to expose (use "*" to display all)
```
> docs: Fix note about -v flag

- lib/plugins/aws/package/compile/events/http-api.js
- test/unit/lib/plugins/aws/package/compile/events/http-api.test.js
> fix: Set API gateway timeout to 30 seconds by default

- docs/providers/aws/events/streams.md
- lib/plugins/aws/package/compile/events/stream.js
- test/unit/lib/plugins/aws/package/compile/events/stream.test.js
> feat: add support for kinesis event startingPositionTimestamp 

- docs/providers/aws/events/kafka.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/kafka.js
- test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
> feat: add support for kafka event startingPositionTimestamp

- docs/providers/aws/guide/packaging.md
The implementation includes `yarn-*.log` in the default exclusion list in `package.patterns`:
https://github.com/serverless/serverless/blob/bb37f4fe75ff5234fae48ada433cd52ddf51cb91/lib/plugins/package/lib/package-service.js#L18
However, the documentation did not include `yarn-*.log`, so I fixed this.
> Fixed docs as `yarn-*.log` is the default exclude file for `package.patterns`

- lib/plugins/aws/package/compile/events/api-gateway/index.js
- test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/method/index.test.js
Closes: [11492](https://github.com/serverless/serverless/issues/11492)
> REST API (API Gateway v1) Cognito User Pool authorizer CF intristic functions

- lib/plugins/aws/provider.js
Node 18 is now officially supported by AWS Lambda. I could not find a corresponding issue.
Reference: https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/
> feat: Add support for `nodejs18.x` runtime

- docs/providers/openwhisk/examples/hello-world/java/pom.xml
There are 1 security vulnerabilities found in com.google.code.gson:gson 2.8.2
- [CVE-2022-25647](https://www.oscs1024.com/hd/CVE-2022-25647)
Upgrade com.google.code.gson:gson from 2.8.2 to 2.8.9 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>
> fix(sec): upgrade com.google.code.gson:gson to 2.8.9

- lib/plugins/aws/invoke-local/runtime-wrappers/java/pom.xml
There are 1 security vulnerabilities found in com.fasterxml.jackson.core:jackson-databind 2.11.0
- [CVE-2020-36518](https://www.oscs1024.com/hd/CVE-2020-36518)
Upgrade com.fasterxml.jackson.core:jackson-databind from 2.11.0 to 2.14.0-rc1 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>
> fix(sec): upgrade com.fasterxml.jackson.core:jackson-databind to 2.14.0-rc1

- docs/providers/aws/events/cloudfront.md
This PR adds a note including a possible solution for CloudFront Functions, respectively Lambda@Edge. There's a function size limit of 10KB, which can easily get solved by bundling and minification.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-functions
https://www.serverless.com/plugins/serverless-esbuild
> docs(AWS CloudFront): maximum function size limit

- lib/plugins/aws/invoke-local/runtime-wrappers/java/pom.xml
> Rollback jackson-databind version to 2.11.0

- docs/guides/plugins/custom-configuration.md
- docs/guides/plugins/extending-configuration.md
- docs/menu.json
- lib/serverless.js
- scripts/serverless.js
- test/fixtures/programmatic/plugin/extend-config-plugin/index.js
- test/unit/lib/serverless.test.js
Adds a new method in serverless-object for extending the internal configuration. This method extends variablesMeta with the newly added and parsed configuration.
VariablesMeta is now exposed via serverless-object.
Addresses the issue discussed in https://github.com/serverless/serverless/issues/11034.
Closes: #11034
> 11034 extend configuration

- docs/providers/cloudflare/guide/intro.md
> docs: fix markdown header missing space

- docs/providers/aws/events/event-bridge.md
- lib/plugins/aws/package/compile/events/event-bridge/index.js
- test/unit/lib/plugins/aws/package/compile/events/event-bridge/index.test.js
> Add ability to give EventBridge events custom names

- docs/providers/openwhisk/examples/hello-world/php/README.md
The function name is `hello`, not `helloWorld`. The result will also differ. Just a small improvement to keep the docs up to date :)
> Update the PHP Readme based on actual usage

- lib/plugins/aws/package/compile/functions.js
- lib/plugins/aws/provider.js
I need to dynamically have provisioned concurrency turned on in some cases, but the current implementation doesn't support that scenario. This fix is similar to what I did for #10129 for reserved concurrency.
> Add support for cloudformation functions for provisioned concurrency

- docs/guides/providers.md
- docs/providers/aws/guide/iam.md
- lib/plugins/aws/custom-resources/index.js
- lib/plugins/aws/package/compile/events/cloud-front.js
- lib/plugins/aws/package/lib/iam-role-lambda-execution-template.json
- test/unit/lib/plugins/aws/custom-resources/index.test.js
- test/unit/lib/plugins/aws/deploy/index.test.js
- test/unit/lib/plugins/aws/package/compile/events/cloud-front.test.js
- test/unit/lib/plugins/aws/package/lib/merge-iam-templates.test.js
As announced by AWS in Dec 2022, there is a new API for tagging CloudWatch resources. New accounts/roles that need to tag CloudWatch LogGroups need the new logs:TagResouce permission.
Closes: #11762
> fix(AWS Lambda): add logs:TagResource permission to AWS Lambda IAM role

- docs/providers/aws/guide/serverless.yml.md
Updates the documentation on logRetentionInDays for CloudWatch log groups, as it wasn't mentioned anywhere that setting it for a function overrides the provider value (can be seen in `/lib/plugins/aws/package/lib/merge-iam-templates.js`):
```
const logRetentionInDays = functionObject.logRetentionInDays || this.provider.getLogRetentionInDays();
if (logRetentionInDays) {
newLogGroup[logGroupLogicalId].Properties.RetentionInDays = logRetentionInDays;
}
```
> Update ambiguous logRetentionInDays documentation

- lib/plugins/aws/package/compile/functions.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
It was not in sync with Cloudformation, could be Cloudformation is wrong, just syncing this with CF. Here's the link to the documentation:- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-runtimemanagementconfig.html#cfn-lambda-function-runtimemanagementconfig-updateruntimeon
Fix for PR #11715
> fix: Changed Map for runtimeManagementMap

- docs/providers/aws/guide/variables.md
> remove invalid variable references from the documentation

- lib/plugins/aws/package/compile/events/api-gateway/lib/request-validator.js
- test/unit/lib/plugins/aws/package/compile/functions.test.js
Addresses: #7747 
There are 2 places that are left with `_.entries()`
Tested with:
`npx mocha test/unit/lib/plugins/aws/package/compile/functions.test.js`
`npx mocha test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/request-validator.test.js`
> refactor _.entries() to Object.entries()

- lib/utils/deep-sort-object-by-key.js
> replace lodash _.fromPairs() with Object.fromEntries()

- test/unit/lib/plugins/aws/package/compile/events/api-gateway/index.test.js
- test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/authorizers.test.js
- test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/hack/disassociate-usage-plan.test.js
- test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/hack/update-stage.test.js
- test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/method/request-parameters.test.js
- test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/stage/index.test.js
- test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/validate.test.js
…it/lib/plugins/aws/package/compile/events/api-gateway/`
`/test/unit/lib/plugins/aws/package/compile/events/apiGateway`
Consideration: during refactoring I notice several test functions return promise -> reduce readability with nested blocks -> to should refactor with `await/async` wherever applicable
Perform test for this PR:
`npx mocha "test/unit/lib/plugins/aws/package/compile/events/api-gateway/**/*.test.js"`
> refactor async functions `/test/.../aws/.../events/apiGateway`

- lib/plugins/aws/package/lib/strip-null-props-from-template-resources.js
- test/unit/lib/plugins/aws/package/lib/strip-null-props-from-template-resources.test.js
Closes: #11530 
Some considerations:
* This implementation only removes Properties if it is explicitly defined as null
* It leaves Properties = {} as is, since removing might damage some downstream logic that depends on this attribute to exist
Another implementation might be stripping Properties when it is either null or empty (code reference below):
```
if ('Properties' in resource) {
// sanitize resource.Properties from all null attributes if itself is not null/empty
if (resource.Properties) {
stripNullPropsFromObj(resource.Properties);
}
// totally scrape out resource.Properties if it is null or empty (after sanitizing)
// 1. either resource.Properties is null/empty by default
// 2. or resource.Properties becomes empty after stripping all its null values
if (!resource.Properties || …
```
> Sanitize null Properties for AWS resources

- lib/plugins/aws/package/compile/functions.js
Closes: #8369
Include my comment along with the new code. We download package artifacts from S3 sequentially instead of running in async (maybe there was a reason behind that)
Another implementation can be:
```
return Promise.all(allFunctions.map((functionName) => this.downloadPackageArtifact(functionName)));
```
> refactor to remove BbPromise.each()

- package.json
I encountered an issue while trying to deploy a serverless app (v3.28.1).
When a environment variable contains special characters, variable interpolation fails.
This issue has been tracked upstream here: https://github.com/motdotla/dotenv-expand/pull/73
and fixed in https://github.com/motdotla/dotenv-expand/pull/74
Bumped `dotenv-expand` to v10, which addresses this specific issue.
Please find a stacktrace below:
```
Environment: linux, node 16.19.1, framework 3.28.1 (local), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
TypeError: Cannot read properties of undefined (reading 'split')
at /home/runner/work/[redacted]/node_modules/serverless/node_modules/dotenv-expand/lib/main.js:20:33 …
```
> chore: bump dotenv-expand

- docs/providers/aws/events/event-bridge.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/event-bridge/index.js
- test/unit/lib/plugins/aws/package/compile/events/event-bridge/index.test.js
Add support for Description property to EventBridge rules
```yaml
functions:
hello:
handler: handlers.fn
events:
- eventBridge:
name: 'eventBridgeRule'
description: 'My EventBridge rule description'
inputTransformer: 
inputPathsMap:
time: '$.time'
inputTemplate: '{"time": <time>}'
enabled: true
schedule: 'cron(0 5 * * ? *)'
```
> Add support for Description property to EventBridge rules

- lib/plugins/aws/package/compile/events/cloud-front.js
This PR addresses a small and obvious bug fix.
Amazon has [introduced Origin Access Control (OAC)](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html) as a replacement for Origin Access Identities (OAI) to connect CloudFront distributions to S3 origins. Configuring this requires setting the `OriginAccessControlId` field in the `origin` configuration object ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html#cfn-cloudfront-distribution-origin-originaccesscontrolid)).
Serverless already allows setting this field just fine and will pass it along properly in the generated CloudFormation template. But it was not covered in the schema, so it fails validation and …
> Allow OriginAccessControlId field for CloudFront origins

- lib/plugins/aws/deploy/lib/create-stack.js
- test/unit/lib/plugins/aws/deploy/index.test.js
- test/unit/lib/plugins/aws/deploy/lib/check-for-changes.test.js
- test/unit/lib/plugins/aws/deploy/lib/upload-artifacts.test.js
- test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/hack/update-stage.test.js
- test/unit/lib/plugins/package/lib/package-service.test.js
An error that occurs when Serverless Deploy is forcibly terminated has been corrected.
When the status of the **CloudFormation Stack** is, `REVIREW_IN_PROGRESS` the code is configured to output an error message as discussed in the issue.
Closes: #11852
> fix(AWS Deploy): Handle error for abnormal CloudFormation stack state during AWS deployment

- docs/providers/aws/guide/functions.md
- lib/plugins/aws/invoke-local/index.js
- lib/plugins/aws/provider.js
Adds java17 also as a supported runtime since this is now officialy supported : https://aws.amazon.com/blogs/compute/java-17-runtime-now-available-on-aws-lambda/
Closes issue #11937
> feat: Support for Java17 as runtime for AWS Lambda functions

- docs/providers/aws/guide/functions.md
- docs/providers/kubeless/cli-reference/create.md
- docs/providers/kubeless/cli-reference/info.md
- docs/providers/kubeless/events/http.md
- docs/providers/kubeless/events/pubsub.md
- docs/providers/kubeless/guide/debugging.md
- docs/providers/kubeless/guide/deploying.md
- docs/providers/kubeless/guide/functions.md
- docs/providers/kubeless/guide/services.md
- docs/providers/spotinst/examples/python/README.md
- docs/providers/tencent/cli-reference/create.md
- lib/plugins/aws/invoke-local/index.js
- lib/plugins/aws/provider.js
- test/unit/lib/cli/interactive-setup/dashboard-login.test.js
- test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
- test/unit/lib/plugins/aws/invoke-local/index.test.js
what.
- Remove references to deprecated AWS Lambda runtimes (Python 2.7, 3.6 and Node 10.x).
- Update tests, documentation, etc.
why.
Since AWS is no longer supporting these runtimes it would be better if the documentation was up to date and pointed users towards new/supported configuration that actually works.
references.
Based on [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy).
Test results (local run, excluding Ruby):
```text
2823 passing (2m)
179 pending
Notice: Some tests were skipped due to following environment issues:
- test/unit/lib/plugins/aws/invokeLocal/index.test.js: Ruby: "before all" hook in "Ruby" (in: t/unit/lib/plugins/aws/invoke-local/index.test.js)
Ruby runtime is not installed
```
> fix: Remove references to deprecated AWS Lambda runtimes

- lib/plugins/aws/package/compile/events/event-bridge/index.js
- test/unit/lib/plugins/aws/package/compile/events/event-bridge/index.test.js
Closes: #11951
This PR enables the use of `$or` in eventbridge pattern blocks.
```yaml
pattern:
'$or':
- source: ['aws.ec2']
- detail-type: ['AWS API Call via CloudTrail']
```
I made the schema enforce using an array, but have otherwise left the items to be anything.
[AWS EventBridge Pattern Docs](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html#eb-create-pattern)
> fix: Adding support for '$or' property in EventBridge pattern schema

- lib/cli/interactive-setup/console-dev-mode-feed.js
- lib/cli/interactive-setup/console-enable-dev-mode.js
Adding warning about dev mode increasing console usage due to traces not being sampled out.
**During instrumentation**
**When dev mode is waiting for activity**
> feat: Added warning about dev mode

- lib/plugins/aws/invoke-local/index.js
- lib/plugins/aws/provider.js
- test/unit/lib/plugins/aws/invoke-local/index.test.js
[Ruby 2.7 went EOL](https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/) in the ruby community on March 30, 2023. AWS has already announced deprecation for Ruby 2.7 on [November 15, 2023](https://docs.aws.amazon.com/lambda/latest/dg/ruby-image.html#ruby-image-base).
According to [this comment](https://github.com/aws/aws-lambda-base-images/issues/54#issuecomment-1486974882) from March 28th, 2023 on the AWS Lambda Base Images repo, Ruby 3.2 support is coming the end of this month:
> Update: We have today released a [container base image for Ruby 3.2 support in Lambda](https://gallery.ecr.aws/lambda/ruby). This container image is fully supported and suitable for production applications. We will release the corresponding managed runtime within 90 days.
> …
> prepare for supporting Ruby 3.2 runtime coming end of Q2 2023

- docs/providers/aws/events/msk.md
- docs/providers/aws/guide/serverless.yml.md
- lib/plugins/aws/package/compile/events/msk/index.js
- test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js
Closes: #12033
- Add support for a StartingPosition of AT_TIMESTAMP to MSK event source mappings. When this configuration is used,
StartingPositionTimestamp must also be provided, in Unix Time seconds, which is consistent with the existing support in the `kafka` event
- Support for this starting position has recently been added to AWS Lambda event source mappings using MSK
(https://aws.amazon.com/about-aws/whats-new/2023/06/aws-lambda-starting-timestamp-kafka-sources/)
- Since `runServerless` tests are expensive, test the happy path in the existing test of a valid configuration rather than adding an explicit separate test for it, but add a new test to explicitly verify the unhappy path in which a timestamp at which to start is not provided
> feat: Add support for starting position AT_TIMESTAMP to MSK events

- lib/plugins/aws/package/compile/events/schedule.js
- test/unit/lib/plugins/aws/package/compile/events/schedule.test.js
Fix the role for scheduler so that it matches the role of the function.
Closes #12022
> fix scheduler role

- test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js
- follow up to #12033
- fix a typo I made in the description of the test of the unhappy path whereby
an `msk` event is defined with `startingPosition` of `'AT_TIMESTAMP'` but
without a `startingPositionTimestamp`
> refactor: Fix typo in description of test of MSK event startingPosition config

- .github/workflows/integrate.yml
- docs/providers/aws/guide/functions.md
- docs/providers/aws/guide/layers.md
- docs/providers/aws/guide/serverless.yml.md
- docs/providers/kubeless/cli-reference/create.md
- docs/providers/kubeless/cli-reference/info.md
- docs/providers/kubeless/events/http.md
- docs/providers/kubeless/events/pubsub.md
- docs/providers/kubeless/guide/debugging.md
- docs/providers/kubeless/guide/deploying.md
- docs/providers/kubeless/guide/functions.md
- docs/providers/kubeless/guide/services.md
- docs/providers/spotinst/examples/python/README.md
- lib/plugins/aws/invoke-local/index.js
- lib/plugins/aws/provider.js
- test/fixtures/programmatic/curated-plugins-python/serverless.yml
- test/fixtures/programmatic/invocation/serverless.yml
- test/unit/lib/cli/interactive-setup/dashboard-login.test.js
- test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
- test/unit/lib/plugins/aws/invoke-local/index.test.js
AWS have now made the Lambda Python 3.11 runtime available, at least through the Lambda API: https://github.com/aws/aws-sdk-js/commit/baa3b7d22f754b5bec88930fd054946e72037839#diff-0521ffc53e94f05cb64ddd5e240950f5c51fb408c695f4aa9999db81b2ea42a4. ~I expect CloudFormation support is coming in a matter of hours or days, across all regions.~ **EDIT**: officially launched: https://aws.amazon.com/blogs/compute/python-3-11-runtime-now-available-in-aws-lambda/.
> Support the new Python 3.11 lambda runtime and update examples to use Python 3.11

- docs/guides/dashboard/monitoring/sdk/nodejs.md
This is a docs-only change. It adds documentation on setting up Source Maps to work with the Node.js Serverless SDK. It is a general solution, not specific to Dashboard, but required for Dashboard to properly get the stacks for captured error events.
> docs: Add Dashboard docs on source maps

- lib/plugins/aws/provider.js
Node 20 is now supported by AWS Lambda. Corresponding issue https://github.com/serverless/serverless/issues/12252
Related AWS Blog Post: https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/
Related AWS SAM CLI Release: https://github.com/aws/aws-sam-cli/releases/tag/v1.102.0
Related AWS SDK Release: https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.446.0
> feat: Add support for nodejs20.x runtime

- lib/plugins/aws/provider.js
AWS Lambda now supports Amazon Linux 2023 (AL2023) as a managed runtime. Closes: [#12250](https://github.com/serverless/serverless/issues/12250)
Related AWS Blog posts : https://aws.amazon.com/jp/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/
Related AWS SAM Release : https://github.com/aws/aws-sam-cli/releases/tag/v1.101.0
Related aws-sdk-js-v3 release : https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.448.0
> feat: Add support for provided.al2023 runtime

- docs/providers/aws/guide/functions.md
- lib/plugins/aws/invoke-local/index.js
- lib/plugins/aws/provider.js
Adds java21 also as a supported runtime since this is now officialy supported : https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-java-21/
Closes issue #12273
> feat: Add support for java21 runtime (#12273)

- lib/plugins/esbuild/index.js
It throws an exception when running a command that doesn’t require a config file to be present.
> fix: check if config file is present

- lib/plugins/aws/dev/local-lambda/index.js
> fix(dev): ensure a hyphen for each logged line

- docs/providers/aws/guide/building.md
- lib/plugins/esbuild/index.js
Fixes:
- https://github.com/serverless/serverless/issues/12645
- https://github.com/serverless/serverless/issues/12617
- https://github.com/serverless/serverless/issues/12616
> fix(esbuild): do not pass invalid properties to esbuild (SC-2463, SC-2464, SC-2500)

- lib/plugins/aws/package/compile/functions.js
The custom logGroup is incorrectly set to the LogFormat key.
> fix: use LoggingConfig.LogGroup for custom log group

- lib/plugins/aws/package/lib/merge-iam-templates.js
IAM Policy Document for Lambda functions in the service does not take into account the custom log group specified in the `logs.logGroup` key. This PR addresses the issue by adding the custom log group name to the Resource array in the IAM Policy Document, instead of the default log group name, when necessary.
> fix: add custom lambda log group to resource array in iam policy doc

- lib/plugins/aws/lib/set-bucket-name.js
- lib/plugins/aws/package/lib/generate-core-template.js
- lib/plugins/aws/provider.js
- lib/plugins/aws/remove/lib/bucket.js
This addresses https://github.com/serverless/serverless/issues/12799.
The recent change in the `getServerlessDeploymentBucketName` function signature caused errors in plugins that use it internally.
> fix: revert to original signature of getServerlessDeploymentBucketName

- package.json
This package is old and throws a node warning.
> fix(sam): remove stream buffers

- docs/guides/plugins/creating-plugins.md
Because we deprecated `this.serverless.cli` and should use utils instead.
> docs(plugins): update deprecated example code

- lib/plugins/aws/invoke-local/index.js
Addresses https://github.com/serverless/serverless/issues/12912
> fix: ignore invalid credentials errors when retrieving AWS env vars for local invoke

- lib/plugins/aws/provider.js
[Node.js 22 runtime now available in AWS Lambda](https://aws.amazon.com/blogs/compute/node-js-22-runtime-now-available-in-aws-lambda/).
Addresses https://github.com/serverless/serverless/issues/12914
> feat: add nodejs22.x runtime

- lib/plugins/package/lib/zip-service.js
- package.json
This PR addresses issues (https://github.com/serverless/serverless/issues/12911) in the dev dependency exclusion logic:
1. Call `execAsync` instead of `childProcess.execAsync`:
- Fixes the usage of the `exec` function by replacing `childProcess.execAsync` with `execAsync` using `promisify` for proper execution.
2. Adjust `pMap` usage with `.then` -> `.filter` and `.then -> .pReduce`:
- Updates the code to handle `pMap` results correctly, as `pMap` does not have `filter` and `reduce` methods like `bluebird`. These operations are now handled explicitly with `.then`.
- Uses `pReduce` to properly handle the async `readFile` operation.
3. Add debug logs for error handling:
- Improves error visibility by adding debug logs for errors instead of swallowing them silently, making the debugging …
> fix: correct dev dependency exclusion and async processing logic

- lib/plugins/package/lib/package-service.js
Addresses https://github.com/serverless/serverless/issues/12775 by updating artifact paths to be relative. These paths are now saved in the `serverless-state.json` file. Previously, artifact paths were absolute, which worked with the `serverless deploy` command but caused issues when using `serverless deploy --package deployment-artifact` from a different directory than where `serverless package --package deployment-artifact` was executed. This resulted in the error: `No {package}.zip file found in the package path you provided`. Using relative paths resolves this issue, ensuring deployment artifacts can be found regardless of the execution directory, as long as the correct deployment package is provided in the `--package` option.
> fix: use relative paths for artifacts
